= ocp4-workload-quay - Deploy Red Hat Quay Registry

== Role overview

* This role installs Red Hat Quay Registry and Clair Security Scanner into an OpenShift Cluster. It consists of the following playbooks:
** Playbook: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an
 environment for the workload deployment.
*** Debug task will print out: `pre_workload Tasks completed successfully.`

** Playbook: link:./tasks/workload.yml[workload.yml] - Used to deploy Red Hat Quay Registry
*** This role creates a namespace (project), secrets, postgres, redis, routes, services, and deployments for Red Hat Quay and Clair
*** Debug task will print out: `workload Tasks completed successfully.`

** Playbook: link:./tasks/post_workload.yml[post_workload.yml] - Used to
 configure the workload after deployment
*** This role doesn't do anything here
*** Debug task will print out: `post_workload Tasks completed successfully.`

** Playbook: link:./tasks/remove_workload.yml[remove_workload.yml] - Used to
 delete the workload
*** This role removes the Red Hat Quay Registry project (and therefore Red Hat Quay Registry)
*** Debug task will print out: `remove_workload Tasks completed successfully.`

== Review the defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you need to define to control the deployment of your workload.
* The variable *ocp_username* is mandatory to assign the workload to the correct OpenShift user.
* A variable *silent=True* can be passed to suppress debug messages.
* Other variables:
** *_quay_project*: The name of the project to create and install Red Hat Quay to. Default: `gpte-quay`
** *_quay_project_display*: The display name of the project. Default: `Red Hat Quay Registry`
** *_quay_postgres_admin_password*: The PostgreSQL admin password.  pgsql is not exposed externally. Default: `quay`
** *_quay_postgres_database*: The PostgreSQL Database Red Hat Quay uses. Default: `quay`
** *_quay_postgres_user*: The PostgreSQL Database User Red Hat Quay uses. Default: `quay`
** *_quay_postgres_password*: The PostgreSQL Database Password Red Hat Quay uses. Default: `quay`
** *_quay_clair_postgres_database*: The PostgreSQL Database Clair uses. Default: `clair`
** *_quay_clair_postgres_user*: The PostgreSQL Database User Clair uses. Default: `clair`
** *_quay_clair_postgres_password*: The PostgreSQL Database Password Clair uses. Default: `clair`
** *_quay_config_password*: Password used for Quay in Config mode, agnosticD should only run in registry mode so this should not be necessary. Default: `password`
** *_quay_config_super_users*: The super users for quay. format: user1, user2. (Default is pre-created in the database, others might need to be registered via the Red Hat Quay portal.) Default `opentlcmgr`
** *_quay_clair_paginationkey*: Random set of characters clair uses for pagination. Default `XxoPtCUzrUv4JV5dS+yQ+MdW7yLEJnRMwigVY/bpgtQ=`
** *_quay_dockerconfigjson*: The quay.io pull_secret. Reference https://access.redhat.com/solutions/3533201 *Should be overwritten via Global Variable!!*
** *_quay_config_secret_key*: The secret key used in quay-config to communicate with clair. *Should be overwritten via Global Variable!!*
** *_quay_clair_key_id*: The secret key used in clair-config to communicate with quay. *Should be overwritten via Global Variable!!*
** *_quay_clair_security_scanner_pem*: Base64 encoded certificate for clair. *Should be overwritten via Global Variable!!*

* You can modify any of these default values by adding `-e "variable_name=variable_value"` to the command line

=== Deploy a Workload with the `ocp-workload` playbook [Mostly for testing]

----
TARGET_HOST="bastion.na311.openshift.opentlc.com"
OCP_USERNAME="wkulhane-redhat.com"
WORKLOAD="ocp4-workload-quay"
GUID=1001
QUAY_DOCKERCONFIGJSON="wk_quay_dockerconfigjson" # change this
QUAY_CONFIG_SECRET_KEY="wk_quay_config_secret_key" # change that
QUAY_CLAIR_KEY_ID="wk_quay_clair_key_id" # obviously change that
QUAY_CLAIR_SECURITY_SCANNER_PEM='wk_quay_clair_security_scanner_pem'

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=ec2-user" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"_quay_dockerconfigjson=${QUAY_DOCKERCONFIGJSON}" \
    -e"_quay_config_secret_key=${QUAY_CONFIG_SECRET_KEY}" \
    -e"_quay_clair_key_id=${QUAY_CLAIR_KEY_ID}" \
    -e"_quay_clair_security_scanner_pem=${QUAY_CLAIR_SECURITY_SCANNER_PEM}" \
    -e"ACTION=create"
----

=== To Delete an environment

----
TARGET_HOST="bastion.na311.openshift.opentlc.com"
OCP_USERNAME="wkulhane-redhat.com"
WORKLOAD="ocp4-workload-quay"
GUID=1002

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=ec2-user" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"guid=${GUID}" \
    -e"ACTION=remove"
----


== Other related information:

=== Deploy Workload on OpenShift Cluster from an existing playbook:

[source,yaml]
----
- name: Deploy a workload role on a master host
  hosts: all
  become: true
  gather_facts: False
  tags:
    - step007
  roles:
    - { role: "{{ocp_workload}}", when: 'ocp_workload is defined' }
----
NOTE: You might want to change `hosts: all` to fit your requirements


=== Set up your Ansible inventory file

* You can create an Ansible inventory file to define your connection method to your host (Master/Bastion with `oc` command)
* You can also use the command line to define the hosts directly if your `ssh` configuration is set to connect to the host correctly
* You can also use the command line to use localhost or if your cluster is already authenticated and configured in your `oc` configuration

.Example inventory file
[source, ini]
----
[gptehosts:vars]
ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem
ansible_user=ec2-user

[gptehosts:children]
openshift

[openshift]
bastion.cluster1.openshift.opentlc.com
bastion.cluster2.openshift.opentlc.com
bastion.cluster3.openshift.opentlc.com
bastion.cluster4.openshift.opentlc.com

[dev]
bastion.cluster1.openshift.opentlc.com
bastion.cluster2.openshift.opentlc.com

[prod]
bastion.cluster3.openshift.opentlc.com
bastion.cluster4.openshift.opentlc.com
----
