include::../../tools/00_0_Lab_Header.adoc[]

== Simple Workload - Lab

.Goals

* Understand the structure and function of a OCP Workload Role
* Understand the Workload Development Process
* Setup Environment for a Workload Role
* Run a Simple Workload Role
* Create your own workload role
* Understand Variable Conventions

include::../../tools/00_0_Lab_Setup.adoc[]

[[labexercises]]
:numbered:

== Overview

=== About OCP Workloads

In previous modules you were introduced to AgnosticD's _base configs_.  You were able to deploy virtual machines, networks, and general infrastructure.

In this module you will learn how to write and deploy workloads on top of the base configs that are already deployed. You might do this to apply custom configurations to infrastructure to support some sort of demonstration, workshop, or class. In this module you'll be using OpenShift 4 workloads to prepare a demo sample application.

To execute a workload, you execute the base config `ocp-workload`, and supply it your workload's name and any necessary variables.  This will be covered in depth in this lab.

== Create your own OCP4 Workload Role

=== Copying the Example Workload

All workload roles must be developed in the proper location in the AgnosticD directory tree.  The option to create workloads outside the tree will be covered in later training, as the option becomes available.

OCP4 based workloads must be placed in a subdirectory of `agnosticd/ansible/roles_ocp_workloads/`, and named with a prefix of `ocp4_workload_`.  For example, `ocp4_workload_example`.

Workload roles are a pattern based on standard Ansible roles.  As in Ansible, the typical subdirectories are supported.  

. Examine the role directories as follows:
+
[source,sh]
----
tree ansible/roles_ocp_workloads/ocp4_workload_example
----
+
.Sample Output
[source,sh]
----
ocp4_workload_example
├── README.md
├── defaults
│   └── main.yml
├── files
├── handlers
│   └── main.yml
├── meta
│   └── main.yml
├── readme.adoc
├── tasks
│   ├── main.yml
│   ├── post_workload.yml
│   ├── pre_workload.yml
│   ├── remove_workload.yml
│   └── workload.yml
├── templates
├── tests
│   ├── inventory
│   └── test.yml
└── vars
    └── main.yml
----
+
To create your own new workload role, follow on with this lab.

. Set your Ansible working directory environment variables.
We assume you've cloned AgnosticD into your $HOME, so export the following:
+
[source,sh]
----
export WORKLOADS=$HOME/agnosticd/ansible/roles_ocp_workloads
----
+
. Create your own workload directory:
+
[source,sh]
----
mkdir $WORKLOADS/ocp4_workload_${USER}
----

. Copy the example role into your new role directory:
+
[source,sh]
----
cp -rv ${WORKLOADS}/ocp4_workload_example/  ${WORKLOADS}/ocp4_workload_${USER}
----


=== Default Variables

You have a new role structure, but you don't know what it does. Worse, many of the variable names in it are still the old name and will not work in your new role.
Let's edit the files, describe what they do, and update the variables to support our new role.

. Change directory into your new role directory to begin working on it:
+
[source,sh]
----
cd ${WORKLOADS}/ocp4_workload_${USER}
----
. Edit the default role variables
+
The variables in default/main.yml define the defaults variable values that will be shipped with your role.  They should be "sane defaults" that work in as many forseeable contexts as possible.  In this case, we have five variables. The first three variables are critical for AgnosticD to work, and the last two are unique to the role:
+
[source,sh]
----
cat defaults/main.yml
----
+
.Example Output
[source,yaml]
----
become_override: False <1>
ocp_username: wkulhane-redhat.com <2>
silent: False <3>

# If your workload needs customization options provide variables to be used.
# Variable names must be prefixed by the role name "<role name>_<variable>".
# Therefore because this example workload is called "ocp4_workload_example" the variables
# should be named "ocp4_workload_example_variable".
#
# You can override the defaults as parameters to the Ansible run that runs
# your workload.

# Documentation for variable 1 (what does it do?)
ocp4_workload_example_variable_1: "value 1" <4>

# Documentation for variable 2 (what does it do?)
ocp4_workload_example_variable_2: "value 2" <5>
----
+
* These variables are critical to your workload functioning properly, your deployer (like CloudForms) will override them as necessary.
<1> `False` is the default.  If you must run your workload as the root user, set to `True`
<2> Your should use this ocp_username to own OpenShift objects.  It is usually supplied by the user or deployment system.
<3> Debugging
<4> A role variable.  Note that it is prefixed by the role name (`ocp4_workload_example_`) and suffixed with the name of the variable (`variable_2`)
<5> Another role variable.

. Change the name of your default role variables to match your new role name:
+
[source,sh]
----
perl -pi -e 's/_example_/_${USER}_/g' defaults/main.yml
----
+
. Examine the file to make sure the `_example_` string was replaced correctly.
+
----
cat defaults/main.yml
----

=== Role Tasks and the Workload Pattern

The tasks are the most imporant parts of the role, and the most complicated.  The base config `ocp-workload` understands how to process and apply the tasks to the OCP cluster you've already deployed.

. Examine the `tasks/main.yml` to understand how the other tasks are called.
+
[source,sh]
----
cat tasks/main.yml
----
+
.Sample Output
----
---
# Do not modify this file

- name: Running Pre Workload Tasks
  include_tasks:
    file: ./pre_workload.yml
    apply:
      become: "{{ become_override | bool }}"
  when: ACTION == "create" or ACTION == "provision"

- name: Running Workload Tasks
  include_tasks:
    file: ./workload.yml
    apply:
      become: "{{ become_override | bool }}"
  when: ACTION == "create" or ACTION == "provision"

- name: Running Post Workload Tasks
  include_tasks:
    file: ./post_workload.yml
    apply:
      become: "{{ become_override | bool }}"
  when: ACTION == "create" or ACTION == "provision"

- name: Running Workload removal Tasks
  include_tasks:
    file: ./remove_workload.yml
    apply:
      become: "{{ become_override | bool }}"
  when: ACTION == "destroy" or ACTION == "remove"
----
+
There are four included tasks above.  Three of them are executed during "create" or "provision" phases, and one is executed during the "destroy" or "remove" phase.  When you execute this workload, you will indicate which phase you'd like `ocp_workload` to run by setting the environment variable ACTION.
+
* *pre_workload.yml* - Write tasks here to set up an environment for the workload deployment.
* *workload.yml* - Write tasks here to deploy the actual workload, i.e, 3scale, Mobile, some Demo or OpenShift customization
* *post_workload.yml* - Write tasks here to configure the workload after deployment, i.e. add workload users or storage

=== Example `workload.yml`

The `workload.yml` playbook is usually the most important and complex.  This is where you will deploy your workload to the OCP cluster.  This is a simple example for you to build from.  Further labs will have more robust examples.

. Examine the playbook.  Note that this role only emits a debug messages.  It emits standard debug messages, and the value of the workload variables.
+
[source,sh]
----
cat tasks/workload.yml
----
+
.Sample Output
[source,yaml]
----
---
- name: Setting up workload for user <1>
  debug:
    msg: "Setting up workload for user ocp_username = {{ ocp_username }}"

# To Do: Implement your workload deployment tasks here
# -------------------------------------------------------------------------

- name: Example Workload, print variable values
  debug:
    msg: "{{ item }}"
  loop:
  - "Variable 1: {{ ocp4_workload_example_variable_1 }}" <2>
  - "Variable 2: {{ ocp4_workload_example_variable_2 }}" <2>

# Leave this as the last task in the playbook.
# --------------------------------------------
- name: workload tasks complete <1>
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool
----
+
<1> These are standard debug messages that should be in EVERY workload playbook to track progress.  Do not remove them.
<2> These are your custom workload variables.  You should change these to match the name of your workload.
+
. Use a text editor or the follow script to edit the `workload.yml` file and change the variable names to match your new workload role.
+
[source,sh]
----
perl -pi -e "s/_example_/_${USER}_/g" tasks/workload.yml
----
+
. Verify your changes produced the desired variable names.
+
[source,sh]
----
cat tasks/workload.yml
----

=== Update Role Metadata, Test, and ReadMe

Your workload is nearly ready to test, but some best-practice housekeeping is necessary.

. Edit the `meta/main.yml` file to ensure that you and your role can be identified properly in the AgnosticD and Ansible Galaxy tools.
. Edit the `tests/test.yml` file to make sure your proper role name is called from any testing frameworks that migth be employed.
. Take some time to thoroughly edit the README.adoc file. Describe the tasks you add to each of the included tasks.  Make sure users and operators of your workload will understand its purpose and any gotchas you experienced or think might arise.

Your workload is now properly reconfigured and is ready to begin testing.

== Setup Your Testing Execution Enviornment

This is usually done on your laptop, or on a dedicated development host.

Executing workloads differs only in minor ways to executing the base configs you're already accustomed to. You'll setup a variables file, if needed.  You'll setup some environment variables.  And you'll prepare a command line with the TARGET_HOST being the bastion of the OCP cluster you have access to.

. Gather Details
.. *GUID* of the OCP cluster you plan to deploy to.
.. *Target Host* is the Fully Qualified Domain Name of the bastion host of that cluster.
.. *Ansible User* of the bastion host of that cluster.  On AWS, it's `ec2-user`, on OpenStack, it's `cloud-user`.
NOTE
==== 
You'll need the proper ssh keys setup for passwordless login to the *Ansible User* account.
* You migth have an email with an SSH username and password for the cluster.  Do a `ssh-copy-id <username>@<bastion host>` to setup passwordless SSH.
* You might already have keys setup if you created the cluster.  Validate that they work from the command line.
====
.. *OCP Username* of the user you want to be on the OpenShift cluster.

. To make testing complex workloads that require many parameters easier, create a `<role name>_vars.yaml` input file to add to your command line.  Change the variables below to match your workload role.
+
.ocp4_workload_example_vars.yaml
[source,sh]
----
# You can set any variable
silent: False

# Set Variable 2
ocp4_workload_example_variable_2: "My variable 2"
----
+
NOTE
====
We recommend creating this file with sample values and including it in your workload role in order to aide other developers and operators in the use of the workload.
We recommend creating this file instead of using environment variables or `ansible-playbook -e` values.
===

. Set up Environment Variables indicating the bastion host you want to run this role to run on. Change the WORKLOAD value to match your workload role name.
+
[source,sh]
----
export GUID=1001 <1>
export TARGET_HOST="bastion.dev.openshift.opentlc.com" <2>
export OCP_USERNAME="wkulhane-redhat.com" <3>
export ANSIBLE_USER="ec2-user" <4>
export WORKLOAD="ocp4_workload_example" <5>
----
<1> The GUID of the cluster.
<2> Change to match your cluster bastion.
<3> Change to match your OSP username - the user must already exist. In OpenTLC, users will be dynamically created.
<4> `ec2-user` for AWS, `cloud-user` for OpenStack
<5> The workload is all your hard work!
+
NOTE
====
* Use environment variables for parameters that will be re-used through your deploy-test-fix-remove development cycle.  
* Use `ansible-playbook -e` command line variables for values that will change from test run to test run.
====

== Run the Workload with Verbose logs

You are now ready to start the deployment of your workload, and the first step of the deploy-test-fix-remove loop of developing workload roles.

. Create a shell script file with the following, or run it directly from the command line.
+
[source,sh]
----
# a TARGET_HOST is specified in the command line, without using an inventory file
cd $HOME/agnosticd/
ansible-playbook -i ${TARGET_HOST}, -vvv ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=${ANSIBLE_USER}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"guid=${GUID}" \
    -e"ACTION=create" \
    -e @./ocp4_workload_${USER}_vars.yaml
----
+
NOTE
====
All these parameters can be delivered to the `./configs/ocp-workload.yml` playbook the way that works best for you.
For example, you can include them all literally in the shell script file, or export them into your environment, or you can put the majority of them in the `<role name>_vars.yaml` file.  
As above, we recommend setting variables as follows:
* `<role name>_vars.yaml` file for safe example variables for all users
* environment variables for settings that will not change for your current development working session.
* `ansible-playbook -e ` variable settings for values that will change between your test runs.
====

. The output of the run should be quite verbose.  Examine the output for the desired outcomes.  You should see verbose output thanks to the `-vvv` in the `ansible-playbook` command AND debugging output thanks to the `silent: False` variable.

. After inspecting the output, you might be able to run the command again to correct errors.
You might need to prepare and run the `remove.yml` playbook from this workload to reset the cluster to run another test without interference from resources created by this run.  In this case, no changes were made, so you are free to run the workload role again.  We will cover writing and running the `remove.yml` playbook in the next lab.

== Modify Variables and Run Again

=== Modify from the Command Line or Environment

During testing, you'll want it to be easy to experiment with different parameters and values.  Use the command line or environment to make changing those values easy.

. Change an environment variable
+
[source,sh]
----
export WORKLOAD_VAR_2="Var2: Changed in Environment"
----

. Change a command line environment variable to output different data:
+
[source,sh]
----
ansible-playbook -i ${TARGET_HOST}, -vvv ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=${ANSIBLE_USER}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"guid=${GUID}" \
    -e"ACTION=create" \
    -e @./ocp4_workload_${USER}_vars.yaml \
    -e"ocp4_workload_${USER}_variable_1=New Test Variable" <1> \
    -e"ocp4_workload_${USER}_variable_2=${WORKLOAD_VAR_2}" <2>
----
+
NOTE: BOTH this variables override the value in the *_vars.yaml file.
<1> Variable 1 uses a literal. 
<2> Variable 2 was exported in the shell environment in the previous step and included in the `-e` values.

=== Modify from Parameters Files

. Change your parameters file to reflect a parameter that you don't expect to change during this development session:
+
[source,sh]
----
# You can set any variable
# Silent: False emits debug logging for your role
silent: False

# Set Variable 2
# Write a comment about what this variable does
ocp4_workload_example_variable_2: "Example of my variable 2 for other deployers"
----
+
WARNING: Be sure to update the `ocp4_workload_example_variable_2` name to match your role name.

. Remove the `-e` setting from the command line and execute again:
+
[source,sh]
----
ansible-playbook -i ${TARGET_HOST}, -vvv ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=${ANSIBLE_USER}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"guid=${GUID}" \
    -e"ACTION=create" \
    -e @./ocp4_workload_${USER}_vars.yaml \
    -e"ocp4_workload_${USER}_variable_1=New Test Variable" <1>
----
+
NOTE: Variable 2 is now used from the `<role name>_vars.yaml` file.


=== Modify the Role Defaults Variables File

Now that you are confident in your variable names and values, go ahead and enshrine them in the `defaults/main.yml`.
Every deployer that does not set this variable explicitly will pick up this value.
This is the BEST place to document your variables - other than the README.

. Edit the `defaults/main.yml` default role variables file:
+
[source,sh]
----
----

