WARNING: DO NOT EXECUTE THIS LAB. THIS LAB HAS NOT BEEN TESTED IN FULL.


include::../../tools/00_0_Lab_Header.adoc[]

== Dedicated Cluster Workloads - Lab

.Goals

* Understand Dedicated OCP Clusters base config provisioning
* Deploy infrastucture workloads to support a workshop
* Deploy a sample app for all users

include::../../tools/00_0_Lab_Setup.adoc[]

[[labexercises]]
:numbered:

== Overview

If you're writing a workload to be used on a dedicated cluster, it's perhaps for a customer workshop or classroom of some kind.  It could also be a multi-user demo.

First you'll need a OSP cluster.  The base config "ocp4-cluster" can deploy OpenShift onto AWS or OpenStack.

This lab assumes that the base config `ocp4-cluster` has already been deployed in its most basic format.  You will then deploy ocp4_workloads to supply infrastructure and student oriented workloads.

To get your base cluster deployed, please proceed to order the "OpenShift 4 Configuration Lab" from the catalog OPENTLC OpenShift 4 Labs. You will receive all the access info in your email at the end of the provisioning.

The ocp-workshop base config can deploy many workload roles in the order they appear.
In this lab, we will deploy one workload at a time, much as you would when developing.

== Test Cluster Connectivity

Ansible needs privileged access to your cluster to execute the workloads.
Your OpenTLC ID has sudo priviledges on the bastion host, so you can run Anaible as root there.
You received an email with authentication information to your bastion host.
Validate that authentication information, and setup password-less login.

. Validate authentication by supplying the password mailed to you:
+
[source,sh]
----
ssh jmaltin-redhat.com@bastion.7d97.sandbox1734.opentlc.com.
----
+
If the above command worked, exit the bastion host and run the following command to setup password-less ssh.
+
. Run the following command and supply the password again to setup key based authentication.
+
[source,bash]
----
ssh-copy-id jmaltin-redhat.com@bastion.7d97.sandbox1734.opentlc.com.
----

== Workload Deployments

=== Setup Execution Environment

Export the following variables to handle all your authentication for this development session.  It will be common across all the workloads you wish to deploy, because you are deploying to the same cluster.

The bastion host username and the OCP username as the same.

. Set Environment Variables
+
[source,bash]
----
export TARGET_HOST="bastion.GUID.sandbox1734.opentlc.com" <1>
export OCP_USERNAME="wkulhane-redhat.com" <2>
export WORKLOAD="ocp4_workload_example" <3>
export GUID="1001" <4>
----
<1> The bastion host you just setup keys on
<2> The username you used
<3> The workload role. You will override this in later steps.
<4> The GUID of your cluster.  7d97 was mine.
+
. Do a test run with the ocp4_example_workload
+
[source,bash]
----
cd $HOME/agnosticd/ansible/
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=$HOME/.ssh/id_rsa" \ <1>
    -e"ansible_user=${OCP_USERNAME}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"ACTION=create"
----
<1> Change this to match your private key used above

. As long as the test was successful, you may continue.
If the test failed, contact your instructor.

////
# Doesn't work because there's no AWS creds on the Catalog Item: OCP4 Configuration

=== Let's Encrypt

. Request and install certificates from Let's Encrypt
+
[source,bash]
----
export WORKLOAD="ocp4_workload_le_certificates"
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=${OCP_USERNAME}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"ACTION=create"
----
////

=== Authorization

The `ocp4_workload_authentication` is a flexible workload for setting up authenticatoin on OCP for one or more users.  It supports htpasswd and LDAP authentication.  We'll use htpawwd authentication in this lab.

By default this workload will::

* setup htpasswd authentication
* add 10 basic users to htpasswd named "user1" through "user10"
* create random default passwords for basic users
** we will update this with the password 'openshift' using the variable `ocp4_workload_authentication_htpasswd_user_password: openshift`
* create and admin user
** generate a random password for the admin user
* report results in the logs

//- adoc List Divider

. Run the Authentication Workload
+
[source,bash]
----
export WORKLOAD="ocp4_workload_authentication"
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/id_ras" \
    -e"ansible_user=${OCP_USERNAME}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"ocp4_workload_authentication_htpasswd_user_password=openshift" \
    -e"ACTION=create"
----

. Validate User Creation:
+
* SSH into your bastion
* attempt to login as *user1*
* create a new project named 'test-proj-jmaltin-redhatcom'
+
[source,bash]
----
ssh ${OCP_USERNAME}@${TARGET_HOST} "oc login -u user1 -p openshift; oc new-project test-${OCP_USERNAME/\./}"
----
+
.Sample Output:
+
[source,text]
----
Login successful.

You don't have any projects. You can try to create a new project, by running

    oc new-project <projectname>

Now using project "test-jmaltin-redhatcom" on server "https://api.cluster-7d97.7d97.sandbox1734.opentlc.com:6443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app ruby~https://github.com/sclorg/ruby-ex.git

to build a new example application in Python. Or use kubectl to deploy a simple Kubernetes application:

    kubectl create deployment hello-node --image=gcr.io/hello-minikube-zero-install/hello-node
----

////
. Delete the test project
+
[source,bash]
----
ssh ${OCP_USERNAME}@${TARGET_HOST} "oc login -u user1 -p openshift; oc project delete test-${OCP_USERNAME/\./}"
----
////

=== Project Request Template

Project request templates help govern your cluster by providing defaults for important resources associated with projects.

By default, the `ocp4_workload_project_request_template` workload creates:

* A project Request Message appropriate to OpenTLC or RHPDS
* Network Policies that allow 
** access from the Ingress to the project
** between all pods in the project
* A limit range that sets some maimums and defaults for containers and pods

Deploy the Project Request Template workload and examine its effects.

. Make sure that you're logged into OpenShift as the `system:admin` account
+
[source,bash]
----
ssh ${OCP_USERNAME}@${TARGET_HOST} "oc login -u system:admin"
----

. Run the Project Request Template workload:
+
[source,bash]
----
WORKLOAD="ocp4_workload_project_request_template"
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=$HOME/.ssh/id_ras" \
    -e"ansible_user=${OCP_USERNAME}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"become_override=True" \# <1>
    -e"ACTION=create"
----
<1> By default, the workload runs as a semi-privileged user.  `become_override` 
include::../../tools/00_0_Lab_Header.adoc[]

== Dedicated Cluster Workloads - Lab

.Goals

* Understand Dedicated OCP Clusters base config provisioning
* Deploy infrastucture workloads to support a workshop
* Deploy a sample app for all users

include::../../tools/00_0_Lab_Setup.adoc[]

[[labexercises]]
:numbered:

== Overview

If you're writing a workload to be used on a dedicated cluster, it's perhaps for a customer workshop or classroom of some kind.  It could also be a multi-user demo.

First you'll need a OSP cluster.  The base config "ocp4-cluster" can deploy OpenShift onto AWS or OpenStack.

This lab assumes that the base config `ocp4-cluster` has already been deployed in its most basic format.  You will then deploy ocp4_workloads to supply infrastructure and student oriented workloads.

The ocp-workshop base config can deploy many workload roles in the order they appear.
In this lab, we will deploy one workload at a time, much as you would when developing.

== Test Cluster Connectivity

Ansible needs privileged access to your cluster to execute the workloads.
Your OpenTLC ID has sudo priviledges on the bastion host, so you can run Anaible as root there.
You received an email with authentication information to your bastion host.
Validate that authentication information, and setup password-less login.

. Validate authentication by supplying the password mailed to you:
+
[source,sh]
----
ssh jmaltin-redhat.com@bastion.7d97.sandbox1734.opentlc.com.
----
+
If the above command worked, exit the bastion host and run the following command to setup password-less ssh.
+
. Run the following command and supply the password again to setup key based authentication.
+
[source,bash]
----
ssh-copy-id jmaltin-redhat.com@bastion.7d97.sandbox1734.opentlc.com.
----

== Workload Deployments
=== Setup Execution Environment

Export the following variables to handle all your authentication for this development session.  It will be common across all the workloads you wish to deploy, because you are deploying to the same cluster.

The bastion host username and the OCP username as the same.

. Set Environment Variables
+
[source,bash]
----
export TARGET_HOST="bastion.GUID.sandbox1734.opentlc.com" <1>
export OCP_USERNAME="wkulhane-redhat.com" <2>
export WORKLOAD="ocp4_workload_example" <3>
export GUID="1001" <4>
----
<1> The bastion host you just setup keys on
<2> The username you used
<3> The workload role. You will override this in later steps.
<4> The GUID of your cluster.  7d97 was mine.
+
. Do a test run with the ocp4_example_workload
+
[source,bash]
----
cd $HOME/agnosticd/ansible/
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=$HOME/.ssh/id_rsa" \ <1>
    -e"ansible_user=${OCP_USERNAME}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"ACTION=create"
----
<1> Change this to match your private key used above

. As long as the test was successful, you may continue.
If the test failed, contact your instructor.

////
# Doesn't work because there's no AWS creds on the Catalog Item: OCP4 Configuration

=== Let's Encrypt

. Request and install certificates from Let's Encrypt
+
[source,bash]
----
export WORKLOAD="ocp4_workload_le_certificates"
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=${OCP_USERNAME}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"ACTION=create"
----
////

=== Authorization

The `ocp4_workload_authentication` is a flexible workload for setting up authenticatoin on OCP for one or more users.  It supports htpasswd and LDAP authentication.  We'll use htpawwd authentication in this lab.

By default this workload will::

* setup htpasswd authentication
* add 10 basic users to htpasswd named "user1" through "user10"
* create random default passwords for basic users
** we will update this with the password 'openshift' using the variable `ocp4_workload_authentication_htpasswd_user_password: openshift`
* create and admin user
** generate a random password for the admin user
* report results in the logs

//- adoc List Divider

. Run the Authentication Workload
+
[source,bash]
----
export WORKLOAD="ocp4_workload_authentication"
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/id_ras" \
    -e"ansible_user=${OCP_USERNAME}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"ocp4_workload_authentication_htpasswd_user_password=openshift" \
    -e"ACTION=create"
----

. Validate User Creation:
+
* SSH into your bastion
* attempt to login as *user1*
* create a new project named 'test-proj-jmaltin-redhatcom'
+
[source,bash]
----
ssh ${OCP_USERNAME}@${TARGET_HOST} "oc login -u user1 -p openshift; oc new-project test-${OCP_USERNAME/\./}"
----
+
.Sample Output:
+
[source,text]
----
Login successful.

You don't have any projects. You can try to create a new project, by running

    oc new-project <projectname>

Now using project "test-jmaltin-redhatcom" on server "https://api.cluster-7d97.7d97.sandbox1734.opentlc.com:6443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app ruby~https://github.com/sclorg/ruby-ex.git

to build a new example application in Python. Or use kubectl to deploy a simple Kubernetes application:

    kubectl create deployment hello-node --image=gcr.io/hello-minikube-zero-install/hello-node
----

////
. Delete the test project
+
[source,bash]
----
ssh ${OCP_USERNAME}@${TARGET_HOST} "oc login -u user1 -p openshift; oc project delete test-${OCP_USERNAME/\./}"
----
////

=== Project Request Template

Project request templates help govern your cluster by providing defaults for important resources associated with projects.

By default, the `ocp4_workload_project_request_template` workload creates:

* A project Request Message appropriate to OpenTLC or RHPDS
* Network Policies that allow 
** access from the Ingress to the project
** between all pods in the project
* A limit range that sets some maimums and defaults for containers and pods

Deploy the Project Request Template workload and examine its effects.

. First make sure you're bastion host user is logged in as OpenShift `system:admin`:
+
[source,bash]
----
ssh ${OCP_USERNAME}@${TARGET_HOST} "oc login -u system:admin"
----
+
.Sample Output:
[source,text]
----
Logged into "https://api.cluster-7d97.7d97.sandbox1734.opentlc.com:6443" as "system:admin" using existing credentials.

You have access to 58 projects, the list has been suppressed. You can list all projects with 'oc projects'

Using project "default".
----

. Now validate that no default resources were created. For example, no Network Policies were created.
+
[source,bash]
----
ssh ${OCP_USERNAME}@${TARGET_HOST} "oc login -u user1 -p openshift; oc get netpol"
----
+
.Sample Output:
[source,text]
----
Login successful.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    test-jmaltin-redhatcom

Using project "test-jmaltin-redhatcom".
No resources found in test-jmaltin-redhatcom namespace.
----

. Make sure you're logged in as the `system:admin` account in OpenShift
+
[source,bash]
----
ssh ${OCP_USERNAME}@${TARGET_HOST} "oc login -u system:admin"
----

. Run the Project Request Template workload and examine the output for errors:
+
[source,bash]
----
WORKLOAD="ocp4_workload_project_request_template"
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=$HOME/.ssh/id_ras" \
    -e"ansible_user=${OCP_USERNAME}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"ACTION=create"
----

. Create a new project that will use the project request template
+
[source,bash]
----
ssh ${OCP_USERNAME}@${TARGET_HOST} "oc login -u user1 -p openshift; oc new-project test-templated-${OCP_USERNAME/\./}"
----

. Validate that Network policies were created:
+
[source,bash]
----
ssh ${OCP_USERNAME}@${TARGET_HOST} "oc login -u user1 -p openshift; oc get netpol"
----
+
.Sample Output:
[source,text]
----
Login successful.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    test-jmaltin-redhatcom
  * test-templated-jmaltin-redhatcom

Using project "test-templated-jmaltin-redhatcom".
NAME                           POD-SELECTOR   AGE
allow-from-all-namespaces      <none>         51s <1>
allow-from-ingress-namespace   <none>         51s <1>
----
<1> two network policies were created by default.

The Default Project Template is working.


==  Your Custom Role

