include::../../tools/00_0_Lab_Header.adoc[]

== Simple Workload - Lab

.Goals

* Understand the structure and function of a OCP Workload Role
* Understand the Workload Development Process
* Setup Environment for a Workload Role
* Run a Simple Workload Role
* Create your own workload role
* Understand Variable Conventions

include::../../tools/00_0_Lab_Setup.adoc[]

[[labexercises]]
:numbered:

== Overview

=== About OCP Workloads

In previous modules you were introduced to AgnosticD's _base configs_.  You were able to deploy virtual machines, networks, and general infrastructure.

In this module you will learn how to write and deploy workloads on top of the base configs that are already deployed. You might do this to apply custom configurations to infrastructure to support some sort of demonstration, workshop, or class. In this module you'll be using OpenShift 4 workloads to prepare a demo sample application.

To execute a workload, you execute the base config `ocp-workload`, and supply it your workload's name and any necessary variables.  This will be covered in depth in this lab.

== Create your own OCP4 Workload Role

=== Copying the Example Workload

All workload roles must be developed in the proper location in the AgnosticD directory tree.  The option to create workloads outside the tree will be covered in later training, as the option becomes available.

OCP4 based workloads must be placed in a subdirectory of `agnosticd/ansible/roles_ocp_workloads/`, and named with a prefix of `ocp4_workload_`.  For example, `ocp4_workload_example`.

Workload roles are a pattern based on standard Ansible roles.  As in Ansible, the typical subdirectories are supported.  

. Examine the role directories as follows:
+
[source,sh]
----
tree ansible/roles_ocp_workloads/ocp4_workload_example
----
+
.Sample Output
[source,sh]
----
ocp4_workload_example
├── README.md
├── defaults
│   └── main.yml
├── files
├── handlers
│   └── main.yml
├── meta
│   └── main.yml
├── readme.adoc
├── tasks
│   ├── main.yml
│   ├── post_workload.yml
│   ├── pre_workload.yml
│   ├── remove_workload.yml
│   └── workload.yml
├── templates
├── tests
│   ├── inventory
│   └── test.yml
└── vars
    └── main.yml
----
+
To create your own new workload role, follow on with this lab.

. Set your Ansible working directory environment variables.
We assume you've cloned AgnosticD into your $HOME, so export the following:
+
[source,sh]
----
export WORKLOADS=$HOME/agnosticd/ansible/roles_ocp_workloads
----
+
. Create your own workload directory:
+
[source,sh]
----
mkdir $WORKLOADS/ocp4_workload_${USER}
----

. Copy the example role into your new role directory:
+
[source,sh]
----
cp -rv ${WORKLOADS}/ocp4_workload_example/  ${WORKLOADS}/ocp4_workload_${USER}
----


=== Default Variables

You have a new role structure, but you don't know what it does. Worse, many of the variable names in it are still the old name and will not work in your new role.
Let's edit the files, describe what they do, and update the variables to support our new role.

. Change directory into your new role directory to begin working on it:
+
[source,sh]
----
cd ${WORKLOADS}/ocp4_workload_${USER}
----
. Edit the default role variables
+
The variables in default/main.yml define the defaults variable values that will be shipped with your role.  They should be "sane defaults" that work in as many forseeable contexts as possible.  In this case, we have five variables. The first three variables are critical for AgnosticD to work, and the last two are unique to the role:
+
[source,sh]
----
cat defaults/main.yml
----
+
.Example Output
[source,yaml]
----
become_override: False <1>
ocp_username: wkulhane-redhat.com <2>
silent: False <3>

# If your workload needs customization options provide variables to be used.
# Variable names must be prefixed by the role name "<role name>_<variable>".
# Therefore because this example workload is called "ocp4_workload_example" the variables
# should be named "ocp4_workload_example_variable".
#
# You can override the defaults as parameters to the Ansible run that runs
# your workload.

# Documentation for variable 1 (what does it do?)
ocp4_workload_example_variable_1: "value 1" <4>

# Documentation for variable 2 (what does it do?)
ocp4_workload_example_variable_2: "value 2" <5>
----
+
* These variables are critical to your workload functioning properly, your deployer (like CloudForms) will override them as necessary.
<1> `False` is the default.  If you must run your workload as the root user, set to `True`
<2> Your should use this ocp_username to own OpenShift objects.  It is usually supplied by the user or deployment system.
<3> Debugging
<4> A role variable.  Note that it is prefixed by the role name (`ocp4_workload_example_`) and suffixed with the name of the variable (`variable_2`)
<5> Another role variable.

. Change the name of your default role variables to match your new role name:
+
[source,sh]
----
perl -pi -e 's/_example_/_${USER}_/g' defaults/main.yml
----
+
. Examine the file to make sure the `_example_` string was replaced correctly.
+
----
cat defaults/main.yml
----

=== Role Tasks and the Workload Pattern

The tasks are the most imporant parts of the role, and the most complicated.  The base config `ocp-workload` understands how to process and apply the tasks to the OCP cluster you've already deployed.

. Examine the `tasks/main.yml` to understand how the other tasks are called.
+
[source,sh]
----
cat tasks/main.yml
----
+
.Sample Output
----
---
# Do not modify this file

- name: Running Pre Workload Tasks
  include_tasks:
    file: ./pre_workload.yml
    apply:
      become: "{{ become_override | bool }}"
  when: ACTION == "create" or ACTION == "provision"

- name: Running Workload Tasks
  include_tasks:
    file: ./workload.yml
    apply:
      become: "{{ become_override | bool }}"
  when: ACTION == "create" or ACTION == "provision"

- name: Running Post Workload Tasks
  include_tasks:
    file: ./post_workload.yml
    apply:
      become: "{{ become_override | bool }}"
  when: ACTION == "create" or ACTION == "provision"

- name: Running Workload removal Tasks
  include_tasks:
    file: ./remove_workload.yml
    apply:
      become: "{{ become_override | bool }}"
  when: ACTION == "destroy" or ACTION == "remove"
----
+
There are four included tasks above.  Three of them are executed during "create" or "provision" phases, and one is executed during the "destroy" or "remove" phase.  When you execute this workload, you will indicate which phase you'd like `ocp_workload` to run by setting the environment variable ACTION.
+
* *pre_workload.yml* - Write tasks here to set up an environment for the workload deployment.
* *workload.yml* - Write tasks here to deploy the actual workload, i.e, 3scale, Mobile, some Demo or OpenShift customization
* *post_workload.yml* - Write tasks here to configure the workload after deployment, i.e. add workload users or storage

=== Example `workload.yml`

The `workload.yml` playbook is usually the most important and complex.  This is where you will deploy your workload to the OCP cluster.  This is a simple example for you to build from.  Further labs will have more robust examples.

. Examine the playbook.  Note that this role only emits a debug messages.  It emits standard debug messages, and the value of the workload variables.
+
[source,sh]
----
cat tasks/workload.yml
----
+
.Sample Output
[source,yaml]
----
---
- name: Setting up workload for user <1>
  debug:
    msg: "Setting up workload for user ocp_username = {{ ocp_username }}"

# To Do: Implement your workload deployment tasks here
# -------------------------------------------------------------------------

- name: Example Workload, print variable values
  debug:
    msg: "{{ item }}"
  loop:
  - "Variable 1: {{ ocp4_workload_example_variable_1 }}" <2>
  - "Variable 2: {{ ocp4_workload_example_variable_2 }}" <2>

# Leave this as the last task in the playbook.
# --------------------------------------------
- name: workload tasks complete <1>
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool
----
+
<1> These are standard debug messages that should be in EVERY workload playbook to track progress.  Do not remove them.
<2> These are your custom workload variables.  You should change these to match the name of your workload.
+
. Use a text editor or the follow script to edit the `workload.yml` file and change the variable names to match your new workload role.
+
[source,sh]
----
perl -pi -e "s/_example_/_${USER}_/g" tasks/workload.yml
----
+
. Verify your changes produced the desired variable names.
+
[source,sh]
----
cat tasks/workload.yml
----

=== Update Role Metadata, Test, and ReadMe

Your workload is nearly ready to test, but some best-practice housekeeping is necessary.

. Edit the `meta/main.yml` file to ensure that you and your role can be identified properly in the AgnosticD and Ansible Galaxy tools.
. Edit the `tests/test.yml` file to make sure your proper role name is called from any testing frameworks that migth be employed.
. Take some time to thoroughly edit the README.adoc file. Describe the tasks you add to each of the included tasks.  Make sure users and operators of your workload will understand its purpose and any gotchas you experienced or think might arise.

Your workload is now properly reconfigured and is ready to begin testing.

== Setup Your Testing Execution Enviornment

Executing workloads differs only in minor ways to executing the base configs you're already accustomed to. You'll setup a variables file, if needed.  You'll setup some environment variables.  And you'll prepare a command line with the TARGET_HOST being the bastion of the OCP cluster you have access to.

. If your workload uses lots of parameters, create a `<role name>_vars.yaml` input file.
+
.ocp4_workload_example_vars.yaml
[source,sh]
----
# You can set any variable
silent: true

# Set Variable 2
ocp4_workload_example_variable_2: "My variable 2"
----

. Set up Environment Variables indicating the bastion host you want to run this role to run on.
+
[source,sh]
----
TARGET_HOST="bastion.dev.openshift.opentlc.com" <1>
OCP_USERNAME="wkulhane-redhat.com" <2>
ANSIBLE_USER="ec2-user" <3>
WORKLOAD="ocp4_workload_example" <4>
GUID=1001 <5>
----





=== Creating a Sample Vars file

Your workload likely uses parameters that you want to encourage your users to take advantage of.  Go ahead and create a `<role name>_vars.yaml` input file in the role root directory..
+
.ocp4_workload_example_vars.yaml
[source,yaml]
----
# You can set any variable, not just the dictionary
silent: true

# Set Variable 2
ocp4_workload_example_variable_2: "My variable 2"
----

== Run the Workload

== Modify Variables and Run Again

. Modify from the Command Line

. Modify from Parameters Files

. Modify the Role Defaults Variables File



