---
# Post-workload cleanup and completion tasks

# =============================================
# Cleanup
# =============================================

- name: Cleanup temporary content repository
  when: r_content_repo_dir is defined
  ansible.builtin.file:
    path: "{{ r_content_repo_dir.path }}"
    state: absent

# =============================================
# Completion message
# =============================================

- name: Post-workload tasks complete
  when:
    - not silent | bool
    - not workload_shared_deployment | default(false) | bool
  ansible.builtin.debug:
    msg: "Post-Workload tasks completed successfully."

- name: Post-workload tasks complete (shared cluster)
  when:
    - not silent | bool
    - workload_shared_deployment | default(false) | bool
  ansible.builtin.debug:
    msg: "Post-Software checks completed successfully"
