== Naming convention ==

=== Execution environments ===

Execution environments should be named using one of the following conventions:

* `ansible<major.minor>-python<major.minor>` - Multi-cloud execution environment.
Components should be the latest tested functional versions as of the date in the filename.
Ansible version should be 2.9+ and python version should be 3.6+.
Ex: `ansible2.9-python3.6`.

* `<purpose>-ansible<major.minor>-python<major.minor>` - execution environment customized for a particular purpose.
For example, the `<purpose>` string could be to support a particular version of a cloud provider different from what is included in the multi-cloud environment.
Ansible version should be 2.9+ and python version should be 3.6+.
Ex: `gcp0.34.0-ansible2.9-python3.6`.

== Run supported images ==

Available images are listed on Quay here: https://quay.io/repository/redhat-gpte/agnosticd-images?tab=tags

.Example with test-empty-config
[source,shell]
----
# Run from agnosticd directory

ansible-runner run \
--container-image=quay.io/redhat-gpte/agnosticd-images:ansible2.9-python3.6-2021-10-29 \
-p main.yml \
--cmdline "-e @configs/test-empty-config/sample_vars.yml" \
--process-isolation \
$PWD
----

.Example with test-empty-config With AWS
[source,shell]
----
mkdir -p ~/secrets
vim ~/secrets/dev.yml # add your credential variables

# Run from agnosticd directory

ansible-runner run \
--container-image=quay.io/redhat-gpte/agnosticd-images:ansible2.9-python3.6-2021-10-29 \
-p main.yml \
--cmdline "-e @configs/test-empty-config/sample_vars_ec2.yml -e @/secrets/dev.yml" \
--process-isolation \
--container-volume-mount ~/secrets:/secrets \
$PWD
----

== Build  ==

Requirements:

* podman installed and configured

.Setup your workstation
----
mkdir -p ~/virtualenvs/ansible-builder
python3 -mvenv ~/virtualenvs/ansible-builder
. ~/virtualenvs/ansible-builder/bin/activate
pip install --upgrade pip
pip install -r requirements-ee.txt
----

Execution environment images should always target specific dated versions.

.Example
----
ansible-builder build --tag ansible2.9-python3.6-2021-10-29
----

=== Push to quay.io ===

----
#replace with the image tag you want to push
tag=ansible2.9-python3.6-2021-10-29
podman push $tag quay.io/redhat-gpte/agnosticd-images:tag
----
