:scrollbar:
:data-uri:
:toc2:
:linkattrs:

= Red Hat FSI Open APIs Sandbox

:numbered:

== Overview

This workload provisions all the required infrastructure for the **link:https://github.com/open-accelerators/open-banking[Red Hat FSI Open API Sandbox]** on OpenShift 4. The following are provisioned:

. 3scale Operator
. 3scale API Manager 2.9 (using RWO System Storage or S3 compatible provider)
.. Gateway Operator 2.9
.. Portal Endpoint secret for connecting to corresponding 3scale tenant admin
.. Staging API Gateway
. Microcks Operator 0.3.0
. Microcks instance
. The AgnosticD link:https://github.com/redhat-cop/agnosticd/tree/development/ansible/roles/ocp4-workload-minio[Minio role] (a S3 compatible provider)
. Preconfigured Open APIs solution scenario
.. ActiveDocs configuration of standard APIs from UK Open Banking
.. Mock data used to provide endpoints responses
.. 3scale API CRDs (Backend and Product)
.. Developer Portal customized

=== Prerequisites and assumptions

This workload is an automated provisioning that works as *standalone deployment* at will or in self-service, which is available on the __Red Hat Product Demo System__ (RHPDS) catalog. It's based on the __Ansible Agnostic Deployer__ framework, or simply *link:https://github.com/redhat-cop/agnosticd[AgnosticD]*

Bear in mind the following pratical considerations before running this workload:

. You should have an active Red Hat 3scale subscription in your Red Hat account. Otherwise the *3scale Operator* cannot download the lastest certified images from the image repository.
+
To generate a __Registry Service Account__, use your Red Hat login and follow the instructions at https://access.redhat.com/terms-based-registry.
+
Once created, look at the _Token Information_ tab where you can find the token *Username* and the token *Password* in encoded format. You might want to use the __Copy__ icon on the right. Keep it to use later on the deployment step.

. An OCP 4 cluster is provisioned and this role is run using a cluster admin.
+
This version of OpenShift should already be pre-installed before executing this ansible role.
+
The version of 3scale provisioned in this lab is known to run on OpenShift Container Platform v4.

. link:https://redhat-cop.github.io/agnosticd/#_preparing_your_workstation[Prepare your workstation to run AgnosticD], requiring `sshd` service enabled as the playbook will SSH into the localhost to execute the Ansible __roles__ in a __virtualenv__ setup.
+
You can choose to run AgnosticD in a container instead of setting up your workstation with additional software - Ansible 2.9, Python3, VirtualEnv, etc.

. The *standalone deployment* also requires a version of `oc` utility that corresponds to your target OCP cluster, ensure oc utility is already authenticated as the `cluster-admin`.
+
Can it be a OCP 4.3+ cluster instance provision in anywhere. Or a local install using *CodeReady Containers*.

. The `git` commands are used on this guide, you should have it installed and in the path of your Shell. You can also do equivalent Git operations on any other tooling of choice.

=== Project Layout

. Notice the directory layout and files included in this project:
+
-----
$ tree

├── defaults
│   └── main.yml
├── files
│   └── 3scale-operator-3-discovery.yml
├── meta
│   └── main.yml
├── README.adoc
├── tasks
│   ├── 3amp-deploy-full-api.yml
│   ├── 3amp-portal-create-section.yml
│   ├── 3amp-portal-upload-builtin-page.yml
│   ├── 3amp-portal-upload-file.yml
│   ├── 3amp-portal-upload-layout.yml
│   ├── 3amp-portal-upload-page.yml
│   ├── main.yml
│   ├── microcks-import-collection.yml
│   ├── post_workload.yml
│   ├── pre_workload.yml
│   ├── remove_workload.yml
│   └── workload.yml
└── templates
    └── << all the k8s object J2 files >>
-----

. Highlights of the most important files are as follows:

.. *defaults/main.yml* : ansible variables and their defaults
.. *tasks/workload.yml* : ansible tasks executed when provisioning 3scale API Manager
.. *tasks/3amp-deploy-full-api.yml* : ansible tasks executed when provisioning 3scale API Manager
.. *tasks/3amp-portal-***.yml* : ansible tasks executed when provisioning 3scale API Manager


== Deployment

First of all, you have to check out the AgnosticD or a fork of this repo to your environment.

In the working directory to clone the repo, execute the following command:

**OpenShift namespaces**

Additional namespaces deployed with this workload.

- microcks: the Mocking APIs service
- minio: the S3 compatible object storage service
- sandbox: the 3scale admin console, developer portal and staging gateway

**Workload configuration**

Check the file `./defaults/main.yml` for customization of the deployment configuration.

=== Standalone Deployment

Use this deployment mode if you want to get this workload deployment on an existing OCP cluster instance. You have to execute the `deploy-to-openshift.sh` file.

Check the content of `deploy-to-openshift.sh` file if any modification you might want to add. 

[source,bash]
-----
#/bin/sh

###
# Usage:
#   ./deploy-on-openshift.sh <ACTION> [options]
#
#       ACTION  - either "create" or "remove"
#       options - extended arguments to ansible-playbook
#
# Execute create with verbose example:
#   ./deploy-on-openshift.sh create -vvvv

RHT_SVC_ACCT_TOKEN="<CHANGE ME!!!>"

### uncomment below to login CRC cluster using 'kubeadmin'
#crc console --credentials | tail -n 1 | cut -d "'" -f 2 | sh

OCP_USERNAME="$( oc whoami )"
TARGET_HOST="localhost"
WORKLOAD="ocp4-workload-openbanking-sandbox"
ACTION="create"

BASEDIR=$(dirname "$0")
cd ${BASEDIR}/../../

if [ "$1" == "remove" ]; then
    ACTION="$1"
    shift
fi

ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e @./roles/${WORKLOAD}/defaults/main.yml \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"obsandbox_3scale_registry_token=${RHT_SVC_ACCT_TOKEN}" \
    -e"silent=False" \
    -e"ACTION=${ACTION}" $@
-----

If using CodeReady Containers you can comment out the line with `crc` command to make sure the `oc` command get logged in. You should have a block similar to this:

[source,bash]
-----
### uncomment below to login CRC cluster using 'kubeadmin'
crc console --credentials | tail -n 1 | cut -d "'" -f 2 | sh
-----

NOTE: Make sure the Red Hat Service Account token parameter is set in the `deploy-to-openshift.sh` file. The `RHT_SVC_ACCT_TOKEN` parameter.

=== RHPDS Deployment

When using RHPDS, you can execute the `deploy-using-rhpds-bastion.sh` file to deploy this workload on an existing OCP4 cluster instance.

Edit the `deploy-using-rhpds-bastion.sh` file to replace the following parameters with target environment values:

- TARGET_HOST
- ANSIBLE_SSH_USER
- ANSIBLE_SSH_PWD
- RHT_SVC_ACCT_TOKEN

This is the content of your file:

[source,bash]
-----
#/bin/sh

###
# Usage:
#   ./deploy-using-rhpds-bastion.sh <ACTION> [options]
#
#       ACTION  - either "create" or "remove"
#       options - extended arguments to ansible-playbook
#
# Execute create with verbose example:
#   ./deploy-using-rhpds-bastion.sh create -vvvv

RHT_SVC_ACCT_TOKEN="<CHANGE ME!!!>"

### change placeholders with RHPDS values
TARGET_HOST="<CHANGE ME!!!>"

ANSIBLE_SSH_USER="<CHANGE ME!!!>"
ANSIBLE_SSH_PWD="<CHANGE ME!!!>"

OCP_USERNAME="opentlc-mgr"
WORKLOAD="ocp4-workload-openbanking-sandbox"
ACTION="create"

BASEDIR=$(dirname "$0")
cd ${BASEDIR}/../../

if [ "$1" == "remove" ]; then
    ACTION="$1"
    shift
fi

ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e @./roles/${WORKLOAD}/defaults/main.yml \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"obsandbox_3scale_registry_token=${RHT_SVC_ACCT_TOKEN}" \
    -e"silent=False" \
    -e"ACTION=${ACTION}" \
    -e"ansible_user=${ANSIBLE_SSH_USER}" \
    -e"ansible_password=${ANSIBLE_SSH_PWD}" $@-----
-----

NOTE: Make sure the Red Hat Service Account token parameter is set in the `deploy-using-rhpds-bastion.sh` file. The `RHT_SVC_ACCT_TOKEN` parameter.


=== Provisioning the Workload

. Execute the following command:
+
-----
$ . scriptname.sh
-----


. Or, to run in verbose mode:
+
-----
$ . scriptname.sh create -vvv
-----

After about 20 minutes, provisioning of the sandbox workload deployment should complete.


=== Remove Provisioned Workload

The __AgnosticD__ framework expects `ACTION=remove` as environment variable to execute the workload removal. It will clean up all resources provisioned ín the deployment of the workload. 

. Execute:
+
----
$ . scriptname.sh remove
----

All the projects created as part of this workload will be removed.
