ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Ansible Infoblox
:toc:

= Overview

ansible-infoblox deploys an Infbolox vNIOS (NIOS) instance along with Ansible Tower (Tower) and VSCode into OSP. This can be used to demonstrate IP Administration (IPAM) or DNS automation with NIOS and Ansible.  It can also be used as a sandbox for testing automation workflows with NIOS.

= Deploying the config

Before deployment, you will need to update sample_infoblox_lab.yml and your secrets.yaml files with credentials and adjust settings to your own environment. 

=== Deployment Variables

Update variables as needed. If you need additional pip packages, add them to the pip_packages variable.

.sample_infoblox_lab.yml
[options="header,footer"]
|=======================
|Variable | Value | Definition
|email    | gejames@redhat.com | replace with your email address
|key_name | gejames-key | replace with a unique key name
|guid     | nioslab     | a short unique identifier
|nios_temp_license  |nios IB-V825 dns dhcp enterprise     |NIOS license types
|pip_packages       |infoblox-client psutil ansible |python packages to install in the venv
|=======================

WARNING: It is not advised to change `nios_temp_license` unless you have a specific need.  

=== Secrets

In addition to the credentials for OSP, you will need the following in your secrets.yaml.  This config defaults to using satellite as the repo_method. Add your satellite connection info in order to register with Satellite. Beginning with Ansible Tower 3.8, you register Tower with Satellite.  This requires a manifest zip file.  Add in your satellite_manifest details in order to apply the manifest automatically during deployment.

[source,yaml]
----
set_repositories_satellite_url: "{{ satellite_url }}"
set_repositories_satellite_org: "{{ satellite_org }}"
set_repositories_satellite_activationkey: "{{ satellite_activationkey }}"

satellite_manifest:
  username: "{{ sat_username }}"
  password: "{{ sat_password }}"
  url: "{{ sat_url }}"   # url to the Tower manifest zip file
----

=== Updating collection versions

This config uses the `awx.awx` and `infoblox.nios_modules` collections during deployment.  If you need to update the versions, edit `requirements.yml`.  Default version numbers are listed at the bottom of this readme.

=== Deploy

You can deploy this config by running the following command from the `ansible` directory of `agnosticd`.

[source,bash]
$ ansible-playbook main.yml -e @configs/ansible-infoblox/sample_vars/sample_infoblox_lab.yml -e @<YOUR_SECRET_VARS.yml>

=== Delete

[source,bash]
$ ansible-playbook destroy.yml -e @configs/ansible-multitier-infra/sample_vars_ec2.yml -e @<YOUR_SECRET_VARS.yml>


= Working with the lab

* When writing playbooks, use the `infoblox.nios_module` collection. See the sample playbook below.
* A new custom credential type called `NIOS Custom Credentials` is created in Tower and can be used to pass nios connection variables.
* A new credential called `nios creds` is added to Tower as type `NIOS Custom Credentials` with per-lab connection variables predefined.
* A new inventory called `nios` will be created and populated with extra_vars specific to each lab. See the variables section below for details.
* Use `/var/lib/awx/venv/nios` for  `ANSIBLE ENVIRONMENT` in Tower or jobs will fail.
* You will need to pass `ansible_python_interpreter: /usr/bin/python3` to your playbook in Tower. This has been done for you in the `nios` inventory.
* A `10.0.0.0/8` network container is automatically added to NIOS. The playbook for this is in `files/nios_network.j2`  

=== NIOS Variables

The following variables can be used in your playbooks to connect to the NIOS instance. They will be added to Tower during deployment. See the `nios_provider` dictionary in the sample playbook below for an example of their use.

[options="header,footer"]
|=======================
|Variable           |Definition   | Tower Assest
|nios_grid_ip       |private IP of the NIOS server  | nios inventory
|nios_grid_url      |public url used for API calls | nios inventory
|ansible_python_interpreter |/usr/bin/python3 | nios inventory
|wapi_version       | defaults to 2.11.1  | nios inventory
|nios_grid_admin    |defaults to admin | nios credential
|nios_grid_password |lab generated password  | nios credential
|=======================


=== Virtualenv

The `infoblox-client` python library is required by the nios modules.  It is installed in a python3 virtualenv in `/var/lib/awx/venv/nios` on the Tower and Bastion instances during lab deployment.  You will need to have this virtualenv selected as your `ANSIBLE ENVIRONMENT` at the Organization, Project, or Job Template level in Tower in order for playbooks to run properly. 

TIP: Set the venv at the Project level so it's used automatically by all your playbooks.

TIP: To access the venv from the bastion: `$ source /var/lib/awx/venv/nios/bin/activate` 

=== Sample playbook

[source,yaml]
---
- name: get next available network from nios
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - infoblox.nios_modules
  vars:
    parent_container: 10.0.0.0/8
    cidr: 24
    nios_provider:
      host: "{{ nios_grid_url }}"
      username: "{{ nios_grid_username }}"
      password: "{{ nios_grid_password }}"
  tasks:
    - name: RETURN NEXT AVAILABLE NETWORK
      set_fact:
        networkaddr: "{{ lookup('nios_next_network', parent_container, cidr=cidr, provider=nios_provider) }}"
  
= Software Versions

[options="header,footer"]
|=======================
| Software | Version
| NIOS     | 8.5.1
| Tower    | 3.8
| RHEL     | 7.8
| ansible  | 2.9
| infoblox.nios_modules | 1.0.2
| awx.awx  | 17.1.0
| infoblox-cli | 0.5.0
|=======================

= Change log

2021-04-06 Initial release
