
= How to set up your laptop to develop AgnosticD workloads [[configs-laptop]]

In this document is aimed to be a reference on how to setup your laptop (both Linux and Mac OS) for Ansible Agnostic Deployer development with OpenStack, AWS and Azure.

Whilst this document primarily at Red Hatters, and partners, who can self provision an OpenStack (OSP) Sandbox via Red Hat’s link:https://rhpds.redhat.com[RHPDS] it may also be useful to others working both with OpenStack and Ansible Agnostic Deployer aka AgnosticD.

For the purpose of this exercise we’ll use the AgnosticD config link:https://github.com/redhat-cop/agnosticd/tree/development/ansible/configs/a-base-config[a-base-config] which is simple to deploy, and extensible for anyone looking to deploy some instances on OpenStack.

I’ll assume you have either self provisioned, or been provided with, an OpenStack Sandbox instance and have the necessary ssh login details etc. 

In order to request an OpenStack Sandbox instance, please go to link:labs.opentlc.com[labs.opentlc.com] and follow these steps:
. Log in to link:https://labs.opentlc.com[https://labs.opentlc.com] using your opentlc user.
. Go to *Services* -> *Catalogs* -> *Novello testing* -> *DEV OSP Sandbox*.
. Click *Order* -> *Submit*

NOTE: You will receive three emails indicating the status of the environment and instructions for accessing the environment.
In the third email you receive all information you need to login to the client machine that would have the rest of required information.

NOTE: You can use the VM as your ansible host or copy the files over to your laptop and work locally.

== Configure your environment for running OpenStack Ansible

In this document, I will use an OSP Sandbox instance as working machine, however, you can configure your own machine for this purpose. If you prefer to do so, please follow the instructions for link:https://github.com/redhat-cop/agnosticd/blob/development/training/02_Getting_Started/config_your_linux.adoc[Linux] or link:https://github.com/redhat-cop/agnosticd/blob/development/training/02_Getting_Started/configure_your_mac.adoc[Mac OS X machines].

=== Deployment Stages

Deployment can be divided logically into 4 short stages. In the course of this blog we’ll work our way through each stage:

1. Validating the OSP Sandbox instance can communicate with OpenStack
2. Validating the Ansible AgnosticD deployer
3. Creating a python virtualenv for working with OpenStack
4. Preparing your secrets, and credentials, for OpenStack

==== Validating the OSP (OpenStack Platform) Sandbox instance can communicate with OpenStack

Before going further lets just validate your OSP ClientVM (be it your laptop or the bastion machine) can actually talk to an OpenStack Cluster. 

Credentials have been provided to you via email if you have requested access via link:https://labs.opentlc.com[https://labs.opentlc.com].

1. Please log into your bastion machine as follows:
[Cibeles@sassenach:~] $ ssh agilpipp-redhat.com@bastion.a890.red.osp.opentlc.com

2. Execute a simple openstack command. The openstack cli is pre-installed and will pick up both your credentials and API endpoint from `~/.config/openstack/clouds.yaml`.
+
[source,bash]
----
$ openstack project list
----

You should see something similar to this:
[source,bash]
----
+----------------------------------+--------------+
| ID                               | Name         |
+----------------------------------+--------------+
| ca3ef1650c6940058d1dd96236fc8619 | a890-project |
+----------------------------------+--------------+
----

You can also inspect your project details:
[source,bash]
----
$ openstack --os-cloud=GUID-project server list
+--------------------------------------+-----------+--------+--------------------------------------------------+-------+---------+
| ID                                   | Name      | Status | Networks                                         | Image | Flavor  |
+--------------------------------------+-----------+--------+--------------------------------------------------+-------+---------+
| b8e24e81-d500-46d6-bbf3-c327f0b0e92d | bastion   | ACTIVE | a890-testnet-network=192.168.0.30, 169.47.188.96 |       | 2c2g30d |
+--------------------------------------+-----------+--------+--------------------------------------------------+-------+---------+
----

3. If the above fails ensure you have both the OpenStack CLI client and a clouds.yaml in `~/config/openstack/clouds.yaml`

Review your `~/.config/openstack/clouds.yaml`:
[source,bash]
----
$ cat ~/.config/openstack/clouds.yaml
clouds:
  a890-project:
    auth:
      auth_url: "http://169.47.188.15:5000/v3"
      username: "a890-user"
      project_name: "a890-project"
      project_id: "ca3ef1650c6940058d1dd96236fc8619"
      user_domain_name: "Default"
      password: "QAEbTYD5eZp6"
    region_name: "regionOne"
    interface: "public"
    identity_api_version: 3
----

4. Try to login to OpenStack UI: link:http://horizon.red.osp.opentlc.com/dashboard/auth/login/[]. You must use the credentials from `.config/openstack/clouds.yaml` to login to the UI.

==== Validating the Ansible AgnosticD deployer

. Clone the AgnosticD repository, if not already there:
+
[source,bash]
----
git clone https://github.com/redhat-cop/agnosticd
----

. Create your `secrets.yml` file *oustide the repository*, and edit it using the correct credentials based on your `clouds.yml` file:

+
[source,bash]
----
cat << EOF >> ~/secrets.yml
# Authenication for OpenStack in order to create the things
# RED
osp_auth_username: CHANGEME
osp_auth_password: CHANGEME
osp_project_name: CHANGEME
osp_project_id: CHANGEME


osp_auth_url: http://169.47.188.15:5000/v3
osp_auth_project_domain: default
osp_auth_user_domain: default

# DNS
osp_cluster_dns_server: ddns01.opentlc.com
osp_cluster_dns_zone: students.osp.opentlc.com
ddns_key_name: PROVIDED_BY_ADMIN          # default value is set to "hmac-dm5"
ddns_key_secret: PROVIDED_BY_ADMIN

# Repo
own_repo_path: PROVIDED_BY_ADMIN

# Do not create PROJECT, we already have one and want to use it
osp_project_create: false

EOF
----

NOTE: You can find a secrets.yml file provided to you on the home directory of your user at your bastion machine, use this to populate the file as previously stated.

[source,bash]
----
[agilpipp-redhat.com@bastion ~]$ ls
agnosticd  openstack  secrets.yml
----

NOTE: It is required that OpenStack SDK is installed on your working machine. For further information, please refer to its link:https://docs.openstack.org/openstacksdk/latest/user/[web page]

For simplicity go into the agnosticd/ansible directory. You can explore the main playbooks, the roles directory, and the configs directory where AgnosticD gets it’s recipes to deploy both infrastructure and workloads across multiple Cloud Providers and OpenShift.
[source,bash]
----
cd agnosticd/ansible
----

Make sure this secret file is correct by running the test-empty-config. To test it, simply execute the ansible deployer playbook main.yml with the test config called test-empty-config.
[source,bash]
----
ansible-playbook main.yml \
  -e @configs/test-empty-config/sample_vars_osp.yml \
  -e @~/secrets.yml
----

The `-e @configs/test-empty-config/sample_vars.yml` syntax tells ansible-playbook to load the vars in that configs `sample_vars.yml` file. This is a common pattern and used widely with AgnosticD. This is how you will customize your configs going forward.

Expect to see the ansible logs, which may include skipped tasks and plays, complete successfully
[source,bash]
----
<output truncated>
...
PLAY RECAP *************************************************************************************************************
localhost                  : ok=34   changed=3    unreachable=0    failed=0    skipped=19   rescued=0    ignored=0
...
----

At this point we have now confirmed that the Sandbox can both communicate with OpenStack and can also execute an, albeit simple, AgnosticD config which in fact doesn’t create any instances.

==== Creating a Python virtualenv for working with OpenStack

Ansible is written in Python and requires certain dependencies to work with cloud platforms. In this case it uses a python package called openstacksdk and others depending on the config being deployed.

Particularly as we transition from Python 2 to Python 3 the optimal way to work is to use a python virtualenv to isolate your environment. We will be using Python3 given the EOL of Python 2.

NOTE: Both Python 2 and 3 are installed and the default Python on the current RHEL 7.7 instance is Python 2 as can be seen if you execute `python --version`

1. Create a virtualenv, called openstack taking care to use python3.
+
[source,bash]
----
$ python3 -m venv openstack
----

2. Activate the virtualenv, (you will need to do this every-time you login).
+
[source,bash]
----
$ source openstack/bin/activate
----

Please note that your prompt will now change to indicate the virtualenv has been activated. e.g. `(openstack) [agilpipp-redhat.com@bastion]$`

3. Upgrade pip, the python package manager, to the latest.
+
[source,bash]
----
$ pip install -U pip
----

4. Install the 4 python packages you will need for your config: ansible, openstacksdk, selinux and dnspython. Each will pull in any necessary secondary dependencies.
+
[source,bash]
----
$ pip install ansible openstacksdk selinux dnspython
----

NOTE: You can list all the installed packages with `pip` list and if you wish to transfer them to another machine it is common pattern to capture them with `pip freeze > requirements.txt` and to install on say your local machine via transferring the file (typically via a `git pull`) and `pip install -r requirements.txt`. This will create a matching environment on your local machine.

5. Validate your new virtualenv can communicate, via ansible, with OpenStack.
+
[source,bash]
----
[agilpipp-redhat.com@bastion ansible]$ ansible localhost -m os_auth
----

Expect a successful outcome listing of JSON services and API endpoints with no error message ending similar to this, but with different IP addresses etc:
[source,bash]
----
... <output omitted>
                        "id": "723dd5a9c44147a6942c1760c462bfae",
                        "interface": "admin",
                        "region": "regionOne",
                        "region_id": "regionOne",
                        "url": "http://10.211.62.15:8004/v1/ca3ef1650c6940058d1dd96236fc8619"
                    },
                    {
                        "id": "cc6667ae59dc4a5a8c94c0f23578a5c5",
                        "interface": "internal",
                        "region": "regionOne",
                        "region_id": "regionOne",
                        "url": "http://10.211.62.15:8004/v1/ca3ef1650c6940058d1dd96236fc8619"
                    }
                ],
                "id": "e62a39d2cb0c421b9ccb4e26b837e639",
                "name": "heat",
                "type": "orchestration"
            }
        ]
    },
    "changed": false
}
----

==== Preparing your secrets and credentials for OpenStack

There are a number of ways to find, and authenticate to, OpenStack APIs. So far both the `openstack` and the Ansible ad-hoc command you just executed using the os_auth module found the necessary meta data via a `clouds.yaml` file. In this particular case here: `~/.config/openstack/clouds.yaml`.

Whilst Ansible itself can use `clouds.yaml` via the openstacksdk package you pip installed earlier AgnosticD actually uses a different way of authenticating to OpenStack via vars expressed in YAML. Fortunately your environment has been, largely, pre-configured via a file located at` ~/.secrets.yml` as shown before.

Please make sure your `clouds.yaml` and `secrets.yml` file are present and populated correclty.
[source,bash]
----
(openstack) [agilpipp-redhat.com@bastion ~]$ ls
agnosticd  openstack  secrets.yml
----

NOTE: If you are using a yum server via own_repo_path or have other sensitive variables for your deployment it makes sense to add them to your new `~/secrets.yml` file. If you are doing a workshop your instructor or facilitator can often supply these.

Configuration of your environment is now complete.
