= How to set up your Linux laptop to develop AgnosticD workloads

In order to have a working Ansible configuration in your Linux laptop, please make sure the file `/etc/ansible/hosts` doesn't exist or is empty, otherwise this default inventory file will cause problems later.

NOTE: It is required that OpenStack SDK is installed on your working machine. For further information, please refer to its link:https://docs.openstack.org/openstacksdk/latest/user/[web page]

== Creating a Python virtualenv for working with OpenStack

Ansible is written in Python and requires certain dependencies to work with cloud platforms. In this case it uses a python package called `openstacksdk` and others depending on the config being deployed.

Particularly as we transition from Python 2 to Python 3 the optimal way to work is to use a python virtualenv to isolate your environment. We will be using Python3 given the EOL of Python 2.

NOTE: Both Python 2 and 3 are installed and the default Python on the current RHEL 7.7 instance is Python 2 as can be seen if you execute `python --version`

1. Create a virtualenv, called openstack taking care to use python3.
+
[source, shell]
----
$ python3 -m venv openstack
----

2. Activate the virtualenv, (you will need to do this every-time you login).
$ source openstack/bin/activate

NOTE: Your prompt will now change to indicate the virtualenv has been activated. e.g. (openstack) [amaya@sassenach ]$

3. Upgrade pip, the python package manager, to the latest.
+
[source, shell]
----
$ pip install -U pip
----

4. Install the 4 python packages you will need for your config: ansible, openstacksdk, selinux and dnspython. Each will pull in any necessary secondary dependencies.
+
[source, shell]
----
$ pip install ansible openstacksdk selinux dnspython
----

TIP: You can list all the installed packages with pip list and if you wish to transfer them to another machine it is common pattern to capture them with `pip freeze > requirements.txt` and to install on say your local machine via transferring the file (typically via a `git pull`) and `pip install -r requirements.txt`. This will create a matching environment on your local machine.

5. Validate your new virtualenv can communicate, via ansible, with OpenStack.
$ ansible localhost -m os_auth

Expect a successful outcome listing of JSON services and API endpoints with no error message ending similar to this, but with different IP addresses etc:
+
[source, shell]
----
... <output omitted>
                        "id": "cc6667ae59dc4a5a8c94c0f23578a5c5",
                        "interface": "internal",
                        "region": "regionOne",
                        "region_id": "regionOne",
                        "url": "http://10.211.62.15:8004/v1/ca3ef1650c6940058d1dd96236fc8619"
                    }
                ],
                "id": "e62a39d2cb0c421b9ccb4e26b837e639",
                "name": "heat",
                "type": "orchestration"
            }
        ]
    },
    "changed": false
}
----

== Preparing your secrets and credentials for OpenStack
There are a number of ways to find, and authenticate to, OpenStack APIs. So far both the openstack command you used in Stage 1 and the Ansible ad-hoc command you just executed using the os_auth module found the necessary meta data via a clouds.yaml file. In this particular case here: ~/.config/openstack/clouds.yaml.

Create your clouds.yaml file with the content which has also have been emailed to you. Again your values may differ:
+
[source, shell]
----
$ cat ~/.config/openstack/clouds.yaml
clouds:
  9956-project:
    auth:
      auth_url: http://169.47.188.15:5000/v3
      username: a890-user
      project_name: a890-project
      project_id: ca3ef1650c6940058d1dd96236fc8619
      user_domain_name: Default
      password: QAEbTYD5eZp6
    region_name: regionOne
    interface: public
    identity_api_version: 3
----

Whilst Ansible itself can use `clouds.yaml` via the `openstacksdk` package you pip installed earlier AgnosticD actually uses a different way of authenticating to OpenStack via vars expressed in YAML. Fortunately your environment has been, largely, pre-configured via a file located at `~/.secrets.yml`

Now you need to create your secrets file, in this case, the content has not been mailed to you, but copied into your home directory on the bastion host. You can create this file in the directory that you like best, I personally use a directory where I store different config files, you will be calling it with the absolute path.

+
[source, shell]
----
cat << EOF >> ~/secret.yml
# Authenication for OpenStack in order to create the things
# RED
osp_auth_username: CHANGEME
osp_auth_password: CHANGEME
osp_project_name: CHANGEME
osp_project_id: CHANGEME

osp_auth_url: http://169.47.188.15:5000/v3
osp_auth_project_domain: default
osp_auth_user_domain: default

# DNS
osp_cluster_dns_server: ddns01.opentlc.com
osp_cluster_dns_zone: students.osp.opentlc.com
ddns_key_name: PROVIDED_BY_ADMIN          # default value is set to "hmac-dm5"
ddns_key_secret: PROVIDED_BY_ADMIN

# Repo
own_repo_path: PROVIDED_BY_ADMIN

# Do not create PROJECT, we already have one and want to use it
osp_project_create: false
EOF
----

NOTE: If you are using a yum server via own_repo_path or have other sensitive variables for your deployment it makes sense to add them to your new `~/secrets.yml` file. If you are doing a workshop your instructor or facilitator can often supply these.