= How to set up your Mac OS X laptop to develop AgnosticD workloads [[configs-mac-laptop]]

In order to have a working Ansible configuration in your Mac OS X laptop, please make sure the file `/etc/ansible/hosts` doesn't exist or is empty, otherwise this default inventory file will cause problems later.

Please note that Mac OS X has not support and it's best efforts based on my own experiences configuring my machine, PRs to this doc are welcomed.

NOTE: It is required that OpenStack SDK is installed on your working machine. For further information, please refer to its link:https://docs.openstack.org/openstacksdk/latest/user/[web page]

== Creating a Python virtualenv for working with OpenStack

Ansible is written in Python and requires certain dependencies to work with cloud platforms. In this case it uses a python package called `openstacksdk` and others depending on the config being deployed.

Particularly as we transition from Python 2 to Python 3 the optimal way to work is to use a python virtualenv to isolate your environment. We will be using Python3 given the EOL of Python 2.

NOTE: You will need to make sure Python 3 is installed on Mac OS X, in case you already have it installed, you can see the instance if you execute `python --version`

IMPORTANT: AgnosticD does not work with Python 3.9 at the time of this writting, make sure you install Python 3.8.

*1.* Install Python on your Mac
I will use brew for that, which I find the easiest way, but other forms can be used. If you haven't installed brew on your Mac, you can follow these link:https://docs.brew.sh/Installation[instructions].

[source, shell]
----
$ brew install python pyenv-virtualenv
----

NOTE: You may need to previously install the following dependencies:

[source, shell]
----
$ brew install openssl readline sqlite3 xz zlib
----

*2.* Create a virtualenv, called openstack taking care to use python3 (you can give your virtual environment the name you want, but it's useful to give it one that is meaningful).

[source, shell]
----
$ pyenv virtualenv openstack-ansible-3.8
----

NOTE: You can also stick to a particular version, which is particularly useful in our case, as I mentioned erarlier, AgnosticD does not work with python 3.9.

[source, shell]
----
$ pyenv install -v 3.8.7
$ pyenv virtualenv -v 3.8.7 agd 
----

*3.* Activate the virtualenv, (you will need to do this every-time you login).

[source, shell]
----
$ source /Users/[USER]/.pyenv/versions/openstack-ansible-3.8/bin/activate
----

NOTE: Your prompt will now change to indicate the virtualenv has been activated. e.g. `(openstack-ansible-3.8) [amaya@sassenach ]$`

*4.* Verify the python version in your virtual env is correct by simply executing:

[source, shell]
----
$ python --version
Python 3.8.7
----

*5.* Upgrade pip, the python package manager, to the latest.

[source, shell]
----
$ pip install --upgrade pip
----

NOTE: if you find the error "`error: pyenv: pip: command not found`", it could because you need `pip3`, in that case please do:

[source, shell]
----
$ alias pip=pip3
$ pip install --upgrade pip
----

*6.* Install the 4 python packages you will need for your config: `ansible`, `openstacksdk`, `selinux` and `dnspython`. Each will pull in any necessary secondary dependencies.

Install python modules needed by Ansible:
[source, shell]
----
sudo pip install openstacksdk
----

Install OpenStack CLIs:
[source, shell]
----
sudo pip install python-openstackclient python-heatclient
----

You can install all packages needed directly from a requirements text file:

[source,shell]
----
$ pip3 install -r https://raw.githubusercontent.com/redhat-cop/agnosticd/development/ansible/configs/ocp4-disconnected-osp-lab/files/macos_requirements.txt
----

*7.* Validate your new virtualenv can communicate, via ansible, with OpenStack.
[source,shell]
----
$ ansible localhost -m os_auth
----

Expect a successful outcome listing of JSON services and API endpoints with no error message ending similar to this, but with different IP addresses etc:

[source, shell]
----
... <output omitted>
                        "id": "cc6667ae59dc4a5a8c94c0f23578a5c5",
                        "interface": "internal",
                        "region": "regionOne",
                        "region_id": "regionOne",
                        "url": "http://10.211.62.15:8004/v1/ca3ef1650c6940058d1dd96236fc8619"
                    }
                ],
                "id": "e62a39d2cb0c421b9ccb4e26b837e639",
                "name": "heat",
                "type": "orchestration"
            }
        ]
    },
    "changed": false
}
----

NOTE: Shall you encounter issues with your Mac OS X machine setup, please note this is best efforts and comes with no supply.

== Preparing your secrets and credentials for OpenStack
There are a number of ways to find, and authenticate to, OpenStack APIs. So far both the openstack command you used in Stage 1 and the Ansible ad-hoc command you just executed using the `os_auth` module found the necessary meta data via a `clouds.yaml` file. In this particular case here: `~/.config/openstack/clouds.yaml`.

Create your clouds.yaml file with the content which has also have been emailed to you. Again your values may differ (it is useful to have a directory with all your clouds in one file and then link it to the default directory):

[source, shell]
----
$ cat ~/.config/openstack/clouds.yaml
clouds:
  9956-project:
    auth:
      auth_url: http://169.47.188.15:5000/v3
      username: a890-user
      project_name: a890-project
      project_id: ca3ef1650c6940058d1dd96236fc8619
      user_domain_name: Default
      password: QAEbTYD5eZp6
    region_name: regionOne
    interface: public
    identity_api_version: 3
----

Whilst Ansible itself can use `clouds.yaml` via the `openstacksdk` package you pip installed earlier AgnosticD actually uses a different way of authenticating to OpenStack via vars expressed in YAML. Fortunately your environment has been, largely, pre-configured via a file located at `~/.secrets.yml`

Now you need to create your secrets file, in this case, the content has not been mailed to you, but copied into your home directory on the bastion host. You can create this file in the directory that you like best, I personally use a directory where I store different config files, you will be calling it with the absolute path.

[source, shell]
----
cat << EOF >> ~/secret.yml
# Authenication for OpenStack in order to create the things
# RED
osp_auth_username: CHANGEME
osp_auth_password: CHANGEME
osp_project_name: CHANGEME
osp_project_id: CHANGEME

osp_auth_url: http://169.47.188.15:5000/v3
osp_auth_project_domain: default
osp_auth_user_domain: default

# DNS
osp_cluster_dns_server: ddns01.opentlc.com
osp_cluster_dns_zone: students.osp.opentlc.com
ddns_key_name: PROVIDED_BY_ADMIN          # default value is set to "hmac-dm5"
ddns_key_secret: PROVIDED_BY_ADMIN

# Repo
own_repo_path: PROVIDED_BY_ADMIN

# Do not create PROJECT, we already have one and want to use it
osp_project_create: false
EOF
----

NOTE: If you are using a yum server via `own_repo_path` or have other sensitive variables for your deployment it makes sense to add them to your new `~/secrets.yml` file. If you are doing a workshop your instructor or facilitator can often supply these.

== Invoking AgnosticD from your Mac

At this point, your Mac is able to invoke AgnosticD without the need to log into a sandbox, you simply need to git clone the AgnosticD repository:

[source, shell]
----
$ git clone https://github.com/redhat-cop/agnosticd.git 
Cloning into 'agd-training'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 65811 (delta 4), reused 8 (delta 2), pack-reused 65791
Receiving objects: 100% (65811/65811), 67.32 MiB | 9.02 MiB/s, done.
Resolving deltas: 100% (44708/44708), done.
----

And verify you can comminicate with your instance:

[source, shell]
----
$ openstack stack list --os-cloud=9956-project
+--------------------------------------+--------------------+-----------------+----------------------+--------------+
| ID                                   | Stack Name         | Stack Status    | Creation Time        | Updated Time |
+--------------------------------------+--------------------+-----------------+----------------------+--------------+
| a6786eda-645d-46ef-87ba-cb8b83159312 | base-stack-wth01   | CREATE_COMPLETE | 2021-02-18T17:52:28Z | None         |
| 6c31285d-7adc-480b-8338-7f82dc658cfc | base-stack-test-01 | CREATE_COMPLETE | 2021-02-18T16:30:18Z | None         |
| b5bf3ca3-da63-444d-a19e-68f5ff35c8ea | base-stack-9956    | CREATE_COMPLETE | 2021-02-18T14:30:58Z | None         |
+--------------------------------------+--------------------+-----------------+----------------------+--------------+
----

And execute any of the AgnosticD playbooks from your Mac with your own vars file in any of your directories:

[source, shell]
----
$ ansible-playbook main.yml -e @../../amaya-stuff/agd-training/2Users.yml -e @../../amaya-stuff/secrets/secrets.yml -e guid=test-01
----