= Red Hat OpenShift Service Mesh LPE - Latest Product Enviorment

== Role overview

This role installs Red Hat OpenShift Service Mesh (OSSM) into an OpenShift Cluster.

It installs all the required operators as documented link:https://docs.openshift.com/container-platform/4.10/service_mesh/v2x/installing-ossm.html[here].

* OpenShift Elasticsearch
* OpenShift Distrubuted Tracing (Jaeger)
* Kiali
* Red Hat OpenShift Service Mesh

== Review the defaults variable file

This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you need to define to control the deployment of your workload.

The variables *ocp4_workload_lpe_servicemesh_smcp_install* and *ocp4_workload_lpe_servicemesh_smcp_namespace* allows you to optionally deploy a basic Service Mesh Control Plane in your cluster.

=== Deploy this workload from a workstation

The recommended way to deploy this role is via link:https://github.com/redhat-cop/agnosticd/blob/development/tools/execution_environments/readme.adoc#ansible-navigator[ansible-navigator execution environments (EE)].

Use the quay.io/agnosticd/ee-multicloud:v0.0.6 container EE.

*First*, create a config file ocp-workloads.yaml.

[source,yaml]
----
guid: your-own-guid

cloud_provider: none
env_type: ocp-workloads
ocp_workloads:
  - ocp4_workload_lpe_servicemesh

ansible_user: ec2-user
target_host: "bastion.{{ guid }}.sandbox123.opentlc.com"
ansible_ssh_private_key_file: "/ansible-output/{{ guid }}/ocp4-cluster/ssh_provision_{{ guid }}"

ocp_username: opentlc-mgr

output_dir: "/ansible-output/{{ guid }}/ocp_workloads"
----

*Second*, run the playbook.

[source,bash]
----
ansible-navigator run ansible/main.yml -e @ocp-workloads.yaml
----

=== Remove the workload

With the same approach described above, run the following command.

[source,bash]
----
ansible-navigator run ansible/destroy.yml -e @ocp-workloads.yaml
----
