= Cloud Sandbox
This config will provision a sandbox environment.
A sandbox environment has no resources provisioned, other than a user and/or API key.

== Supported Providers
The following cloud providers are supported:

* ibm (account only)
* ec2 (account only)
* vmware (account + bastion) 

== Usage
This config is split into the standard AgnosticD phases.

. `pre-infra.yml`: This playbook should include any tasks or roles required to provision a sandbox account.
Depending on the cloud provider, this could be through the account assignment API or through a legacy bash script.
Any variables or logging necessary to identify the assigned account should be included here.

. `cloud_provider_infrastructure_deployment`: This file can be found in the `cloud_providers` folder.
It should provision nothing.

. `post-infra.yml`: Any tasks that are required to finish configuring the infrastructure.
For a sandbox, this should generally be empty, but it may include tasks that do something like configuring DNS.

. `pre-software.yml`: This should be empty for a sandbox.

. `software.yml`: Add tasks or roles if you are installing a bastion.
These should be very minimal and should be behind a `cloud_provider` conditional.

. `post-software.yml`: Add any messages that will be sent to the user here.
This should use the `agnosticd_user_info` module with either the `msg` or `body` variable defined.
