== asset_injector

Injects assets, or artifacts, into a target host. Assets can be sourced from a variety of locations, including git, http, templates, and local files.

=== Requirements

N/A - these are basic ansible modules that should be available in any ansible installation.

(Future support for say `S3` bucket objects will require the `amazon.aws` collection to be installed for example)

=== Role Variables

Only 1 var `asset_injector_assets ` is required, which is a list of assets to inject. Each asset is a dictionary with the following keys:

[source,yaml]
----
asset_injector_assets:

    - name: Multi Tier App multi-tier-app-deployer
      src: https://github.com/tonykay/multi-tier-app-deployer.git
      dest: /home/devops/multi-tier-app-deployer
      type: git
      scm_ref: main
      owner: devops
      
    - name: Docker inventory
      type: http
      src: https://raw.githubusercontent.com/tonykay/multi-tier-app-deployer/main/inventory-docker
      dest: /home/devops/docker-inventory
      owner: devops
      group: users
      mode: u=rw,g=r,o=r

    - name: AAP2 Manifest
      type: http
      dest: /home/devops/manifest_31_10_2022.zip
      src: https://example.com/assets/manifest_31_10_2022.zip
      url_username: "{{ url_username }}"
      url_password: "{{ url_password }}"
      dest: /home/devops/manifest.zip
      owner: devops
      group: users
      mode: u=rw,g=r,o=r

    - name: Copy local stuff
      type: 'copy'
      src: ./file/Makefile
      dest: /home/devops/Makefile
      owner: devops
      group: users
      mode: u=rw,g=r,o=r

    - name: Make ssh config
      type: 'template'
      src: ./files/ssh_config.j2
      dest: /home/devops/ssh-config
      owner: devops
      group: users
      mode: "u=r,g-rwx,o-rwx"
----

=== Dependencies

N/A

=== Example Playbook

Including an example of how to use your role (for instance, with variables passed in as parameters) is always nice for users too:

[source,yaml]
----
- hosts: servers
  tasks:

    - name: Inject assets
      when: 
        - asset_injector_asset is defined
        - asset_injector_asset | length > 0
      include_role: 
        name: asset_injector
----

=== License

BSD

== Author Information

tony kay tok@redhat.com