== asset_injector

Injects assets, or artifacts, into a target host. Assets can be sourced from a variety of locations, including git, http, templates, and local files.

=== Capabilities

* Inject assets from:
** git
** http
** templates
** local files
* Remove files and directories 
* Insert blocks into files (eg insert a block of text into a config file)
* Manage services (eg restart a service after injecting new assets or configuration)

=== Requirements

N/A - these are basic ansible modules that should be available in any ansible installation.

(Future support for say `S3` bucket objects will require the `amazon.aws` collection to be installed for example)

=== Role Variables

Only 1 var `asset_injector_assets ` is required, which is a list of assets to inject. Each asset is a dictionary with the following keys:

[source,yaml]
----
asset_injector_assets:

    - description: Multi Tier App multi-tier-app-deployer
      src: https://github.com/tonykay/multi-tier-app-deployer.git
      dest: /home/devops/multi-tier-app-deployer
      type: git
      scm_ref: main
      owner: devops
      
    - description: Docker inventory
      type: http
      src: https://raw.githubusercontent.com/tonykay/multi-tier-app-deployer/main/inventory-docker
      dest: /home/devops/docker-inventory
      owner: devops
      group: users
      mode: u=rw,g=r,o=r

    - description: AAP2 Manifest
      type: http
      dest: /home/devops/manifest.zip
      src: https://example.com/assets/manifest_31_10_2022.zip
      url_username: "{{ url_username }}"
      url_password: "{{ url_password }}"
      owner: devops
      group: users
      mode: u=rw,g=r,o=r

    - description: Copy local stuff
      type: 'copy'
      src: ./file/Makefile
      dest: /home/devops/Makefile
      owner: devops
      group: users
      mode: u=rw,g=r,o=r

    - description: Make ssh config
      type: 'template'
      src: ./files/ssh_config.j2
      dest: /home/devops/ssh-config
      owner: devops
      group: users
      mode: "u=r,g-rwx,o-rwx"

    # Next 3 examples show how reconfiguring sshd

    - description: Remove 50-cloud-init.conf, ssh issue
      type: remove
      path: /etc/ssh/sshd_config.d/50-cloud-init.conf

    - description: Update sshd_config for password auth
      type: blockinfile
      path: /etc/ssh/sshd_config
      state: present
      block: |
        ChallengeResponseAuthentication no
        PasswordAuthentication yes
        UsePAM yes

    - description: Restart sshd to pick up new configuration
      type: service
      service: sshd
      state: restarted

----

=== Dependencies

N/A

=== Example Playbook

Including an example of how to use your role (for instance, with variables passed in as parameters) is always nice for users too:

[source,yaml]
----
- hosts: servers
  tasks:

    - name: Inject assets
      when: 
        - asset_injector_asset is defined
        - asset_injector_asset | length > 0
      include_role: 
        name: asset_injector
----

=== License

BSD

== Author Information

tony kay tok@redhat.com