== asset_injector

Injects assets, or artifacts, into a target host. Assets can be sourced from a variety of locations, including git, http, templates, and local files.

=== Capabilities

* Inject assets from:
** git
** http
** templates
** local files
* Remove files and directories
* Insert blocks into files (eg insert a block of text into a config file)
* Manage services (eg restart a service after injecting new assets or configuration)
* Change capabilities
* Manage Groups

=== Requirements

N/A - these are basic ansible modules that should be available in any ansible installation.

(Future support for say `S3` bucket objects will require the `amazon.aws` collection to be installed for example)

=== Role Variables

Only 1 var `asset_injector_assets ` is required, which is a list of assets to inject. Each asset is a dictionary with the following keys:

[source,yaml]
----
asset_injector_assets:

    # Users - only for simple use cases

    - description: Set root passwd
      name: root
      state: present
      password: "{{ password | password_hash('sha512') }}"

    # Git Repos

    - description: Multi Tier App multi-tier-app-deployer
      src: https://github.com/tonykay/multi-tier-app-deployer.git
      dest: /home/devops/multi-tier-app-deployer
      type: git
      scm_ref: main
      owner: devops

    # Files via http

    - description: Docker inventory
      type: http
      src: https://raw.githubusercontent.com/tonykay/multi-tier-app-deployer/main/inventory-docker
      dest: /home/devops/docker-inventory
      owner: devops
      group: users
      mode: u=rw,g=r,o=r

    # Files via http with htpasswd

    - description: AAP2 Manifest
      type: http
      dest: /home/devops/manifest.zip
      src: https://example.com/assets/manifest_31_10_2022.zip
      url_username: "{{ url_username }}"
      url_password: "{{ url_password }}"
      owner: devops
      group: users
      mode: u=rw,g=r,o=r

    # Copy

    - description: Copy local stuff
      type: 'copy'
      src: ./file/Makefile
      dest: /home/devops/Makefile
      owner: devops
      group: users
      mode: u=rw,g=r,o=r

    # Templates

    - description: Make ssh config
      type: 'template'
      src: ./files/ssh_config.j2
      dest: /home/devops/ssh-config
      owner: devops
      group: users
      mode: "u=r,g-rwx,o-rwx"

    # Next 3 examples show how reconfiguring sshd

    # Remove

    - description: Remove 50-cloud-init.conf, ssh issue
      type: remove
      path: /etc/ssh/sshd_config.d/50-cloud-init.conf

    # Blockinfile

    - description: Update sshd_config for password auth
      type: blockinfile
      path: /etc/ssh/sshd_config
      state: present
      block: |
        ChallengeResponseAuthentication no
        PasswordAuthentication yes
        UsePAM yes

    # Lineinfile

    - description: Add line to file
      type: lineinfile
      path: /etc/quote.txt
      state: present
      line: 'All good things to those who wait'

    # DNF - good for S3 bucket RPMs etc

    - description: Install upstream podman rpm
      type:'dnf'
      name: podman-latest.rpm
      state: present
      disable_gpg_check: true

    # Service

    - description: Restart sshd to pick up new configuration
      type: service
      service: sshd
      state: restarted

    # Capabilities

    - description: Fix Setr cap_setuid+ep on newuidmap for podman issue
      type: capability
      path: /usr/bin/newuidmap
      capability: cap_setuid+ep
      state: present

    # File

    - description: Create proprietary directory
      type: file
      path: /srv/proprietary
      mode: "0640"
      group: root
      owner: root
      state: directory

    # Commands
    - description: Run command on system
      type: command
      cmd: 'updatedb'

    # Groups
    - description: Add group team
      type: group
      name: team
      state: present

    # Unarchive tar archive
    - description: Unarchive a massive set of LLMs
      type: unarchive
      src: /root/lots-of-llms.tar
      dest: /root

----

=== Dependencies

N/A

=== Example Playbook

Including an example of how to use your role (for instance, with variables passed in as parameters) is always nice for users too:

[source,yaml]
----
- hosts: servers
  tasks:

    - name: Inject assets
      when:
        - asset_injector_assets is defined
        - asset_injector_assets | length > 0
      include_role:
        name: asset_injector
----

=== License

BSD

== Author Information

tony kay tok@redhat.com
