---
- name: Retrieve Gitlab root private token
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: root-user-personal-token
    namespace: "{{ ocp4_workload_advanced_developer_suite_post_install_gitlab_namespace }}"
  register: r_root_token
  retries: 120
  delay: 10
  until:
  - r_root_token is defined
  - r_root_token.resources is defined
  - r_root_token.resources | length > 0
  - r_root_token.resources[0] is defined
  - r_root_token.resources[0].data is defined
  - r_root_token.resources[0].data.token is defined
  - r_root_token.resources[0].data.token | length > 0

- name: Decode root token
  ansible.builtin.set_fact:
    _gitlab_root_token: "{{ r_root_token.resources[0].data.token | b64decode }}"

- name: Integrate gitlab
  become: true
  ansible.builtin.shell: |
    ./bin/tssc integration gitlab \
    --token="{{ _gitlab_root_token }}" \
    --host="{{ _gitlab_host }}" \
    --group="{{ ocp4_workload_advanced_developer_suite_tssc_cli_gitlab_group }}"
  args:
    chdir: ~/tssc_cli