---
- name: Wait until Jenkins is fully up and running
  k8s_info:
    api_version: v1
    kind: Deployment
    name: jenkins
    namespace: "{{ ocp4_workload_advanced_developer_suite_jenkins_namespace }}"
  register: r_jenkins
  retries: 60
  delay: 10
  until:
  - r_jenkins.resources[0].status is defined
  - r_jenkins.resources[0].status.readyReplicas is defined
  - r_jenkins.resources[0].status.readyReplicas == r_jenkins.resources[0].spec.replicas

- name: Generate Jenkins API Token
  uri:
    url: "{{ _jenkins_host }}/me/descriptorByName/jenkins.security.ApiTokenProperty/generateNewToken"
    user: "{{ ocp4_workload_advanced_developer_suite_jenkins_admin_user }}"
    password: "{{ ocp4_workload_advanced_developer_suite_jenkins_admin_password }}"
    method: POST
    force_basic_auth: true
    validate_certs: false
    body_format: form-urlencoded
    body:
      newTokenName: backstage
  register: r_jenkins_token
  retries: 60
  delay: 10
  until: r_jenkins_token is not failed

- name: Set Jenkins Token Fact
  set_fact:
    _jenkins_token: "{{ r_jenkins_token.json.data.tokenValue }}"

- name: Integrate gitlab
  become: true
  ansible.builtin.shell: |
    ./bin/tssc integration jenkins \
    --token="{{ _jenkins_token }}" \
    --url="{{ _jenkins_host }}" \
    --username="{{ ocp4_workload_advanced_developer_suite_jenkins_admin_user }}"
  args:
    chdir: ~/tssc_cli