---
- name: Set platform dependent products
  include_tasks: "{{ item }}"
  loop:
  - ./setup_gitlab.yml
  - ./setup_jenkins.yml

# - name: Create Openshift resources for RHTAP
#   kubernetes.core.k8s:
#     state: present
#     definition: "{{ lookup('template', item) | from_yaml }}"
#   loop:
#   - openshift-gitops-application-controller-admin.yml.j2