= ocp4_workload_example - Example Workload Role

== Role overview

* This is a working no-op role that can be used to develop new OpenShift 4 workload roles. It consists of the following tasks files:
** Tasks: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an environment for the workload deployment
*** Debug task will print out: `pre_workload Tasks completed successfully.`

** Tasks: link:./tasks/workload.yml[workload.yml] - Used to deploy the actual workload, i.e, 3scale, Mobile, some Demo or OpenShift customization
*** This role only prints the current username for which this role is provisioning.
*** Debug task will print out: `workload Tasks completed successfully.`

** Tasks: link:./tasks/post_workload.yml[post_workload.yml] - Used to configure the workload after deployment
*** This role doesn't do anything here
*** Debug task will print out: `post_workload Tasks completed successfully.`

** Tasks: link:./tasks/remove_workload.yml[remove_workload.yml] - Used to delete the workload
*** This role doesn't do anything here
*** Debug task will print out: `remove_workload Tasks completed successfully.`

== The defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you need to define to control the deployment of your workload.
* The variable *ocp_username* is mandatory to assign the workload to the correct OpenShift user.
* A variable *silent=True* can be passed to suppress debug messages.
* You can modify any of these default values by adding `-e "variable_name=variable_value"` to the command line
* You can modify any of these default values by adding `-e "variable_name=variable_value"` to the command line
* Your deployer will override any of these variables (usually CloudForms)
* Add long-name scoped workload parameters. Example: `ocp4_workload_example_machineconfigpool_name: worker`

=== Variable Naming

You *must* use long-name scope parameters for your workload to avoid variable clashing.
Ansible lacks robust variable scoping.
For example, parameters named `ocp4_workload_example_*` would be recognized as unique to this workload

== Deploy a Workload with the `ocp-workload` playbook [Mostly for testing]

. If your workload uses parameters create a `<role name>_vars.yaml` input file.
+
.ocp4_workload_example_vars.yaml
[source,yaml]
----
# You can set any variable, not just the dictionary
silent: true

# Set Variable 2
ocp4_workload_example_variable_2: "My variable 2"
----

. Set up Environment Variables for the bastion you want to run this role on.
+
[source,yaml]
----
TARGET_HOST="bastion.dev.openshift.opentlc.com"
OCP_USERNAME="wkulhane-redhat.com"
ANSIBLE_USER="ec2-user"
WORKLOAD="ocp4_workload_example"
GUID=1001
----

. Finally run the workload passing the input files as parameters:
+
[source,sh]
----
# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=${ANSIBLE_USER}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"guid=${GUID}" \
    -e"ACTION=create" \
    -e @./ocp4_workload_example_vars.yaml
----
+

=== To Delete an environment

----
TARGET_HOST="bastion.dev.openshift.opentlc.com"
OCP_USERNAME="wkulhane-redhat.com"
ANSIBLE_USER="ec2-user"
WORKLOAD="ocp4_workload_example"
GUID=1002

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=ec2-user" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"guid=${GUID}" \
    -e"ACTION=remove" \
    -e @./ocp_workload_example_vars.yaml \
    -e @./ocp_workload_example_secrets.yaml
----

== Deploying a Workload with AgnosticV

When creating a configuration in AgnosticV that includes the deployment of the workload you can specify the variables straight in the AgnosticV config.
AgnosticV configs are usually created by combining a `common.yaml` file with either `dev.yaml`, `test.yaml` or `prod.yaml`.
You can specify different variables in each of these files.
For example you could have common values defined in the `common.yaml` file and then specific values overriding the common ones for development or production environments in `dev.yaml` or `prod.yaml`.

AgnosticV merges the definition files starting with `common.yaml` and then adding/overwriting what comes from either `dev.yaml` or `prod.yaml`.

Example of a simple AgnosticV config:

.common.yaml
[source,yaml]
----
# --- Quay Shared Workload Deployment for RPDS
# --- System: RHPDS
# --- Catalog: OpenShift Demos
# --- Catalog Item: Quay 3 on OpenShift 4

# --- Platform
platform: rhpds

# --- Cloud Provider
cloud_provider: none

# --- Config
env_type: ocp4-cluster
ocp_workload: ocp4_workload_quay_operator
# This workload must be run as ec2-user (or cloud-user on OpenStack)
# because it has tasks requiring sudo.
ansible_user: ec2-user
ansible_ssh_private_key_file: /home/opentlc-mgr/.ssh/opentlc_admin_backdoor.pem

# --- Ensure the workload prints the correct statements for CloudForms to realize it finished
workload_shared_deployment: true

# --- Workload Configuration
ocp4_workload_quay_operator_project: "quay-{{ guid }}"

# --- AgnosticV Meta variables
agnosticv_meta:
  params_to_variables:
    user: ocp_username
  secrets:
  # This secret file holds the token to pull the Quay image
  - ocp4_workload_quay_secrets
----

.dev.yaml
[source,yaml]
----
purpose: development

# --- Use specific variable values for Development
target_host: bastion.dev4.openshift.opentlc.com

# --- Workload Configuration Overrides
# Deploy Quay v3.2.0 in dev for testing purposes
ocp4_workload_quay_operator_quay_image_tag:  "v3.2.0"
ocp4_workload_quay_operator_clair_image_tag: "v3.2.0"
----

.prod.yaml
[source,yaml]
----
---
purpose: production

# --- Use specific variable values for Production
target_host: bastion.rhpds.openshift.opentlc.com

# --- Workload Configuration Overrides
# Deploy Quay v3.1.3 in prod for production purposes
ocp4_workload_quay_operator_quay_image_tag:  "v3.1.3"
ocp4_workload_quay_operator_clair_image_tag: "v3.1.3"

# --- AgnosticV Meta variables
agnosticv_meta:
  agnosticd_git_tag_prefix: ocp4-workload-quay-rhpds-prod
----

== Complex Examples

If you want to see more examples of how this works in a real world workload the following workloads already use this approach:

* ocp4_workload_authentication
* ocp4_workload_machinesets
* ocp4_workload_logging
* ocp4_workload_quay_operator

