#!/bin/bash

dnf remove -y google-rhui-client*
dnf clean all

dnf install -y tmux

echo "Adding wheel" > /root/post-run.log
usermod -aG wheel rhel

echo "Setting password" >> /root/post-run.log
echo redhat | passwd --stdin rhel

echo "Fixing permissions" >> /root/post-run.log
chown -R rhel:rhel /home/rhel/