#! /usr/bin/env python
# A Ravello SDK example for storing user credentials in a file
#
# Copyright 2011-2016 Ravello Systems, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations under
# the License.

import base64
import os
import getpass
from sys import version_info

py3 = version_info[0] > 2
if py3:
	username = input("Enter username: ")
else:
	username = raw_input("Enter username: ")

password = getpass.getpass('Enter a Password: ')

encryped_password = base64.b64encode(password.encode('utf-8'))

with open(os.path.expanduser("~/.ravello_login"),"wb") as f:
	f.write(str(username+'\n').encode())
	f.write(encryped_password)

