---
- name: Running workload tasks
  when: ACTION == "create" or ACTION == "provision"
  ansible.builtin.include_tasks: workload.yml

- name: Running workload remove tasks
  when: ACTION == "remove" or ACTION == "destroy"
  ansible.builtin.include_tasks: remove_workload.yml
