---
- name: Remove KataConfig
  kubernetes.core.k8s:
    state: absent
    api_version: kataconfiguration.openshift.io/v1
    kind: KataConfig
    name: example-kataconfig
  ignore_errors: true

- name: Remove peer-pods-cm ConfigMap
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: ConfigMap
    name: peer-pods-cm
    namespace: openshift-sandboxed-containers-operator
  ignore_errors: true

- name: Remove OSC Subscription
  kubernetes.core.k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: openshift-sandboxed-containers-operator
    namespace: openshift-sandboxed-containers-operator
  ignore_errors: true

- name: Remove workload complete
  ansible.builtin.debug:
    msg: "OSC configure workload removed"
