= tower-custom-venv

This role is a tower infra workload for the link:../../configs/ansible-tower[ansible-tower config].

It has the particularity, as a workload for this config, to be executed from the bastion.
That is why it uses `delegate_to` in tasks to configure the tower instances.

The purpose of this role is to create custom virtualenv in ansible Tower masters and workers. It follows this documentation: https://docs.ansible.com/ansible-tower/latest/html/upgrade-migration-guide/virtualenv.html

. Create the virtualenv directory based on the list variable `tower_custom_virtualenvs`. See below for examples.
. Call Tower API to update the settings to specify in Tower the directories to watch for virtualenvs.


After that, you should be able to use the virtualenvs in your job_templates, organizations, ...

== Examples

.ansible-latest and ansible-2.9.3
[source,yaml]
-------------------------------------------
tower_custom_virtualenvs:
  - dest: /opt/rh/virtualenvs
    name: ansible-2.9.3
    requirements:
      - ansible==2.9.3

  - dest: /opt/rh/virtualenvs
    name: ansible-latest
    requirements:
      - ansible
-------------------------------------------

.virtualenvs for deploying to AWS and OSP using agnosticd
[source,yaml]
-------------------------------------------
tower_custom_virtualenvs:
  - dest: /opt/rh/virtualenvs
    name: aws-ansible-2.9
    requirements:
      - ansible==2.9.4
      - awscli==1.17.7
      - boto==2.49.0
      - boto3==1.11.7
      - botocore==1.14.7
      - cffi==1.13.2
      - colorama==0.4.1
      - cryptography==2.8
      - docutils==0.15.2
      - Jinja2==2.10.3
      - jmespath==0.9.4
      - MarkupSafe==1.1.1
      - pyasn1==0.4.8
      - pycparser==2.19
      - python-dateutil==2.8.1
      - PyYAML==5.3
      - rsa==3.4.2
      - s3transfer==0.3.1
      - six==1.14.0
      - urllib3==1.25.8

  - dest: /opt/rh/virtualenvs
    name: openstack-ansible-2.9
    requirements:
      - ansible==2.9.3
      - appdirs==1.4.3
      - asn1crypto==1.3.0
      - attrs==19.3.0
      - Babel==2.8.0
      - bcrypt==3.1.7
      - certifi==2019.11.28
      - cffi==1.13.2
      - chardet==3.0.4
      - cliff==2.18.0
      - cmd2==0.8.9
      - colorama==0.4.3
      - configparser==4.0.2
      - contextlib2==0.6.0.post1
      - cryptography==2.8
      - debtcollector==1.22.0
      - decorator==4.4.1
      - distro==1.4.0
      - dnspython==1.16.0
      - dogpile.cache==0.9.0
      - enum34==1.1.6
      - funcsigs==1.0.2
      - functools32==3.2.3.post2
      - futures==3.3.0
      - idna==2.8
      - importlib-metadata==1.4.0
      - ipaddress==1.0.23
      - iso8601==0.1.12
      - Jinja2==2.10.3
      - jmespath==0.9.4
      - jsonpatch==1.24
      - jsonpointer==2.0
      - jsonschema==3.2.0
      - keystoneauth1==3.18.0
      - MarkupSafe==1.1.1
      - monotonic==1.5
      - more-itertools==5.0.0
      - msgpack==0.6.2
      - munch==2.5.0
      - netaddr==0.7.19
      - netifaces==0.10.9
      - openstacksdk==0.39.0
      - os-client-config==2.0.0
      - os-service-types==1.7.0
      - osc-lib==2.0.0
      - oslo.config==7.0.0
      - oslo.context==2.23.0
      - oslo.i18n==3.25.1
      - oslo.log==3.45.2
      - oslo.serialization==2.29.2
      - oslo.utils==3.42.1
      - paramiko==2.7.1
      - pathlib2==2.3.5
      - pbr==5.4.4
      - prettytable==0.7.2
      - pycparser==2.19
      - pyinotify==0.9.6
      - PyNaCl==1.3.0
      - pyOpenSSL==19.1.0
      - pyparsing==2.4.6
      - pyperclip==1.7.0
      - pyrsistent==0.15.7
      - python-cinderclient==5.0.0
      - python-dateutil==2.8.1
      - python-glanceclient==2.17.0
      - python-heatclient==1.18.0
      - python-keystoneclient==3.22.0
      - python-neutronclient==6.14.0
      - python-novaclient==16.0.0
      - python-openstackclient==4.0.0
      - python-swiftclient==3.8.1
      - pytz==2019.3
      - PyYAML==5.3
      - requests==2.22.0
      - requestsexceptions==1.4.0
      - rfc3986==1.3.2
      - scandir==1.10.0
      - selinux==0.2.1
      - simplejson==3.17.0
      - six==1.14.0
      - stevedore==1.31.0
      - subprocess32==3.5.4
      - unicodecsv==0.14.1
      - urllib3==1.25.7
      - warlock==1.3.3
      - wcwidth==0.1.8
      - wrapt==1.11.2
      - zipp==1.0.0
-------------------------------------------
