= ocp4-workload-rhte19-shadowman - Shadowman Sprint Demo

== Role overview

* This role deploys the Quay 3.x workshop. It consists of the following tasks files:
** Tasks: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an
 environment for the workload deployment.
*** Debug task will print out: `pre_workload Tasks completed successfully.`

** Tasks: link:./tasks/workload.yml[workload.yml] - Used to deploy the workshop.
*** This role creates a namespace (project) and deploys all the components of the demo.
*** Debug task will print out: `workload Tasks completed successfully.`

** Tasks: link:./tasks/post_workload.yml[post_workload.yml] - Used to
 configure the workload after deployment
*** This role doesn't do anything here
*** Debug task will print out: `post_workload Tasks completed successfully.`

** Tasks: link:./tasks/remove_workload.yml[remove_workload.yml] - Used to
 delete the workload
*** This role removes OpenShift Pipelines
*** Debug task will print out: `remove_workload Tasks completed successfully.`

== Review the defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you need to define to control the deployment of your workload.10
* The variable *ocp_username* is mandatory to assign the workload to the correct OpenShift user.
* A variable *silent=True* can be passed to suppress debug messages.

=== Deploy a Workload with the `ocp-workload` config [Mostly for testing]
```bash
TARGET_HOST=$(hostname)
OCP_USERNAME="$(oc whoami)"
WORKLOAD="ocp4_workload_quay_workshop"
GUID=$(hostname | cut -d\. -f2)
USER=$(whoami)
#from the root of the agnosticd project
ansible-playbook -u ${USER} -k -i /etc/ansible/hosts ./ansible/configs/ocp-workloads/ocp-workload.yml \
   -e "ansible_ssh_private_key_file=~/.ssh/id_rsa" \
   -e "ansible_user=${whoami}" \
   -e "ocp_workload=${WORKLOAD}" \
   -e "ocp_username=${OCP_USERNAME}" \
   -e "guid=${GUID}" \
   -e "ACTION=create" \
   -e "silent=False"
```

Create a file `workload_vars.yaml` with your variables:
----
cloud_provider: none
env_type: ocp-workloads
target_host: bastion.dev4.openshift.opentlc.com

ocp_workloads:
- ocp4_workload_quay_workshop

#become_override: false

# If the ocp-workload supports it, you should specify the OCP user:
ocp_username: system:admin

# Usually the ocp-workloads want a GUID also:
guid: changeme
----

From the Agnosticd/ansible directory run the playbook:

----
ansible-playbook main.yml -e @workload_vars.yml -e ACTION="create"
----

=== To Delete an environment

From the Agnosticd/ansible directory run the playbook:

----
ansible-playbook main.yml -e @workload_vars.yml -e ACTION="remove"
----