:role: control-user
:author1: Mitesh The Mouse <mitsharm@redhat.com>
:author2: Prakhar Srivastava <psrivast@redhat.com>
:author3: Tony Kay <tok@redhat.com>
:team: GPTE DevOps & Automation


Role: {role}
============

The role {role} creates a user, can enable sudoers, setup ssh keys/config, resource directory and copies content/files in resource dir .

Requirements
------------

* To run the role one should have root privilege.

Role tree structure
-------------------

[source=textinfo]
----
roles/control-user/
├── README.adoc
├── defaults
│   └── main.yml
├── files
│   └── .vimrc
├── meta
│   └── main.yml
├── tasks
│   ├── copy-user-files.yml
│   ├── create-user.yml
│   ├── main.yml
│   ├── resource-dir-setup.yml
│   └── ssh-config.yml
└── templates
    └── ssh_config.j2

5 directories, 9 files
----

Role Variables
--------------

. List of variables used in {role} role-
+
[cols="5",options="header"]
|===
| Variable | Type | Choices/Defaults | Example | Description

| control_user_enable_skel | Bool | true | control_user_enable_skel=true | Enable skel task, Click link:tasks/main.yml#L8[task] to read

| control_user_skel_files | List of files | [.vimrc] | control_user_skel_files=[.vimrc, ./files/test.txt] | list of user skel files, Click link:tasks/main.yml#L7[task] to read

| control_user_name | String  | devops | control_user=devops | User name, Click link:tasks/create-user.yml#L5[task] to read

| control_user_private_group  | String | users | control_user_private_group=users | User's private group name, Click link:tasks/create-user.yml#L6[task] to read

| control_user_groups_append | Bool | true | control_user_groups_append=true | Click link:tasks/create-user.yml#L7[task] to read

| control_user_groups | Comma separated list | omit | control_user_groups=wheel,root | List of secondary groups, Click link:tasks/create-user.yml#L8[task] to read

| control_user_password | Hash | omit | control_user_password="{{ 'redhat' \| password_hash( 'sha512' ) }}"| User's password, Click link:tasks/create-user.yml#L9[task] to read

| contole_user_password_update | String | omit |  contole_user_password_update=always | Run password update, Click link:tasks/create-user.yml#L10[task] to read

| control_user_enable_sudoers | Bool | true | control_user_enable_sudoers=true | Enable sudoers, Click link:tasks/main.yml#L30[task] to read

| control_user_sudo_commands | String | "NOPASSWD: ALL" | control_user_sudo_commands: "NOPASSWD: ALL" or "ALL" | Sudoer's commands, Click link:tasks/main.yml#L15[task] to read

| control_user_setup_ssh | Bool | true | control_user_setup_ssh=true | To run ssh setup, Click link:tasks/main.yml#L34[task] to read
| control_user_enable_env_ssh_keys | Bool | true | control_user_enable_env_ssh_keys=true | Copy config environment key to user, Click link:tasks/ssh-config.yml#L11[task] to read

| control_user_custom_ssh_keys | List of files | None | control_user_custom_ssh_keys=[private.pem, public.pub] | Copy custom ssh keys to user, Click link:tasks/ssh-config.yml#L37[task] to read

| control_user_ssh_config | file | ssh_config.j2 | control_user_ssh_config=ssh_config.j2 | Copy ssh host config, Click link:tasks/ssh-config.yml#L43[task] to read

| control_user_enable_resource_dir | Bool | true | control_user_enable_resource_dir=true | Enable resource directory, Click link:tasks/main.yml#L38[task] to read

| control_user_resource_dir_name | String | user-resource-dir | control_user_resource_dir_name=user-resource-dir | Resource Directory name, Click link:tasks/resource-dir-setup.yml#L5[task] to read 

| control_user_resource_materials | List of files | None | control_user_resource_materials=[materials.txt, readme.adoc ] | Files which will copied to resource dir, Click link:tasks/resource-dir-setup.yml#L18[task] to read 

| control_user_resource_templates | List of Nested Dictionary Jinja template | None | control_user_resource_templates=[{ template: httpd.conf.j2, file: httpd.conf}, { template: ./file/clouds.yaml.j2, file: clouds.yaml} ] | Jinja Templates which will copied to resource dir, Click link:tasks/resource-dir-setup.yml#L29[task] to read 

| control_user_resource_contents | List of nested dictionary | None | control_user_resource_contents=[{content: "Welcome to my page", file: "index.html"}] | List of content which will be placed in file in resource dir, Click link:tasks/resource-dir-setup.yml#L40[task] to read 

 

| control_user_copy_user_files | List of nested dictionary | None | Look at variables examples below | Dictionary of files to copy, Click link:tasks/copy-user-files.yml#L10[task] to read 


| control_user_copy_user_templates | List of nested dictionary | None | Look at variables examples below | Dictionary of templates to copy, Click link:tasks/copy-user-files.yml#L21[task] to read 

| control_user_copy_user_contents | List of nested dictionary | None | Look at variables examples below | Dictionary of contents to copy, Click link:tasks/copy-user-files.yml#L32[task] to read 

| control_user_directory | List of directory | None | Look at variables examples below | Creates directory set in variable, Click link:tasks/main.yml#L21[task] to read

|===
 
Example of Variables and Values
--------------------------------
. Example -- following variables will copy files in /etc/skel directory
+
[source=text]
----
control_user_enable_skel: true  
control_user_skel_files:
  - .vimrc
  - .bashrc
  - .bash_profile
----

. Example -- following variables will create user and groups
+
[source=text]
----
## User's variable used in tasks/create-user.yml
control_user_name: devops                    
control_user_private_group: users       
control_user_groups_append: true
control_user_groups: root,wheel
control_user_password: "{{ 'redhat' \| password_hash( 'sha512' ) }}"
contole_user_password_update: true
----


. Example -- following variables will create user's directory in user's home
+
[source=text]
----
control_user_directory:
  - ".config/openstack"
  - "public_html"  

----


. Example -- following variables will setup sudoers
+
[source=text]
----
control_user_enable_sudoers: true  
control_user_sudo_commands: "NOPASSWD: ALL"
----

. Example -- following variables will setup ssh keys and copy them in ~/.ssh/ directory
+
[source=text]
----
## SSH setup variables 
control_user_setup_ssh: true            
control_user_enable_env_ssh_keys: true  
control_user_ssh_config: ssh_config.j2 
control_user_custom_ssh_keys:
  - private.key
  - public.key
  - openstack.pem
  - openstack.pub
----

. Example -- following variables will create and copy all files/templates/content in resource directory (name) as defiend
+
[source=text]
----
control_user_enable_resource_dir: true   
control_user_resource_dir_name: user-resource-dir 
control_user_resource_materials:
  - file1.txt
  - file2.txt

control_user_resource_templates:
  - template: vsftpd.j2
    file_name: vsftpd.conf
  - template: httpd.j2
    file_name: httpd.conf

control_user_resource_contents:
  - content: "Welcome to my page"
    file_name: index.html
  - content: "{{ tower_license | from_json }}"
    file_name: license.txt
----

. Example -- following variables will create and copy all files/templates/content in in the path as defined
+
[source=text]
----
## Copy user's file/template to any path as defined
control_user_copy_user_files:
  - file: user_info
    path: /home/devops/user.txt

control_user_copy_user_templates:
  - template: clouds.yaml.j2
    path: /home/devops/clouds.yaml

control_user_copy_user_contents:
  - content: "welcome to my page"
    path: /home/devosp/public_html/index.html
----

Example of Sample Variables and Playbook
----------------------------------------

. Example-
+
[source=text]
----
[user@desktop ~]$ cat sample_variables.yml
control_user_name: bob

control_user_skel_files:
    - ./files/.vimrc

control_user_sudo_commands: "NOPASSWD: /bin/fdisk,/bin/ip"

control_user_ssh_config: ./templates/ssh_config.j2

control_user_resource_dir_name: lab_materials

control_user_resource_templates:
    - template: httpd.conf.j2
      file: httpd.conf
    - template: ./file/clouds.yaml.j2
      file: clouds.yaml} 

control_user_resource_contents:
  - content: "{{ tower_license | from_json }}"
    file: "license.txt"
  - content: "Welcome to page"
    file: "index.html"
----
+
[source=text]
----
[user@desktop ~]$ cat playbook.yml

- hosts: all
  roles:
   - control-user

[user@desktop ~]$ ansible-playbook playbook.yml -e sample_variables.yml

----

. Example-
+
[source=text]
----
[user@desktop ~]$ cat playbook.yml

- hosts: all
  roles:
   - role: control-user
     vars: 
       control_user_name: bob
       control_user_ssh_config: ./templates/ssh_config.j2
       control_user_resource_contents:
         - content: "{{ tower_license | from_json }}"
           file: "license.txt"
----

. Example-
+
[source=text]
----
[user@desktop ~]$ cat playbook.yml

- hosts: all
  tasks:
   - include_role: 
        name: control-user
     vars: 
       control_user_name: bob
       control_user_ssh_config: ./templates/ssh_config.j2
       control_user_resource_contents:
         - content: "{{ tower_license | from_json }}"
           file: "license.txt"
----


Author Information
------------------

* Author/owner:
** {author1}

* Alternative Contacts:
** {author2}
** {author3}

* Team:
** {team}
