:role: satellite-manage-organization
:author: GPTE Team
:tag1: configure_satellite
:tag2: configure_satellite_organization
:main_file: tasks/main.yml
:version_file: tasks/version_6.4.yml


Role: {role}
============

This role creates organization. 

Requirements
------------

. Satellite must be install and setup. 
. Hammer cli config must be configured/updated with privileged user and password to run the satellite cli.

Role Variables
--------------

|===
|satellite_version: "Digit" |Required |satellite version
|org: "String" |Required |Organization name
|org_label: "String" |Required | Organization label in string without space
|org_description: "String" |Required | Organization description
|===

* Example variables

[source=text]
----
satellite_version: 6.4
org: "gpte"
org_label: "gpte"
org_description: "Global Partner Training and Enablement"
----

Tags
---

|===
|{tag1} |Consistent tag for all satellite config roles
|{tag2} | This tag is specific to this role only
|===

* Example tags

[source=text]
----
## Tagged jobs
ansible-playbook playbook.yml --tags configure_satellite,configure_satellite_organization

## Skip tagged jobs
ansible-playbook playbook.yml --skip-tags configure_satellite,configure_satellite_organization

----


Example Playbook
----------------

How to use your role (for instance, with variables passed in playbook).

[source=text]
----
[user@desktop ~]$ cat playbook.yml
- hosts: satellite.example.com
  vars:
    satellite_version: 6.4
    org: "gpte"
    org_label: "gpte"
    org_description: "Global Partner Training and Enablement"
  roles:
    - satellite-manage-organization 

[user@desktop ~]$ ansible-playbook playbook.yml
----

Tips to update Role
------------------

To extend role works for other version, create new file named  version_{{satellite_version}}.yml and import newly created file in main.yml

for reference look at link:{main_file[main.yml] and link:{version_file}[version_6.4.yml]


Author Information
------------------

{author}
