= ocp4_workload_fuse_online - Deploy Fuse Online to OpenShift

== Role overview

* This role installs Fuse Online into an OpenShift Cluster. +
The role is primarily meant to provide the lab environment for the GPTE Fuse Foundations Part I course. +
It consists of the following playbooks:
** Playbook: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an
 environment for the workload deployment. Deploys cluster resource quota for thenamespace created by this workload.
*** Debug task will print out: `pre_workload Tasks completed successfully.`

** Playbook: link:./tasks/workload.yml[workload.yml] - Deploys Fuse Online
*** This role creates a namespace (project) and deploys the Fuse Online operator. It will then create the custom resource for a Fuse Online deployment.
*** This role also deploys a application (catalog service) which is used in the labs of the Fuse Foundations Part I course.
*** Debug task will print out: `workload Tasks completed successfully.`

** Playbook: link:./tasks/post_workload.yml[post_workload.yml] - Used to
 configure the workload after deployment
*** This role doesn't do anything here
*** Debug task will print out: `post_workload Tasks completed successfully.`

** Playbook: link:./tasks/remove_workload.yml[remove_workload.yml] - Used to
 delete the workload
*** This role removes the namespace where Fuse Online was deployed. It also removes the cluster resource quota.
*** Debug task will print out: `remove_workload Tasks completed successfully.`


== Review the defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you need to define to control the deployment of your workload.
* The variable *ocp_username* is mandatory to assign the workload to the correct OpenShift user.
* A variable *silent=True* can be passed to suppress debug messages.

=== Deploy a Workload with the `ocp-workload` playbook [Mostly for testing]

----
TARGET_HOST="bastion.dev.openshift.opentlc.com"
OCP_USERNAME="btison-redhat.com"
WORKLOAD="ocp4_workload_fuse_online"
GUID=1001

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=opentlc-mgr" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"ACTION=create"
----

=== To Delete an environment

----
TARGET_HOST="bastion.ocp43.openshift.opentlc.com"
OCP_USERNAME="btison-redhat.com"
WORKLOAD="ocp4_workload_fuse_online"
GUID=1002

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=opentlc-mgr" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"guid=${GUID}" \
    -e"ACTION=remove"
----

