---
apiVersion: mirror.openshift.io/v2alpha1
kind: ImageSetConfiguration
mirror:
  platform:
    graph: false
    channels:
    - name: stable-4.18
      minVersion: 4.18.33
      maxVersion: 4.18.33
    - name: stable-4.19
      minVersion: 4.19.24
      maxVersion: 4.19.24
    - name: stable-4.20
      minVersion: 4.20.8
      maxVersion: 4.20.8
    architectures:
    - amd64
  additionalImages:
  - name: registry.redhat.io/rhacm2/multicluster-operators-subscription-rhel9:v2.15.1-1
  - name: registry.redhat.io/openshift4/ztp-site-generate-rhel8:v4.20.0-1
  - name: registry.redhat.io/openshift4/openshift-telco-core-rds-rhel9:v4.18.5-5
  - name: registry.redhat.io/openshift4/openshift-telco-core-rds-rhel9:v4.19.3-1
  - name: registry.redhat.io/openshift4/openshift-telco-core-rds-rhel9:v4.20.1-3
  - name: quay.io/karmab/curl:multi
  - name: quay.io/karmab/origin-coredns:multi
  - name: quay.io/karmab/haproxy:multi
  - name: quay.io/karmab/origin-keepalived-ipfailover:multi
  - name: quay.io/karmab/mdns-publisher:multi
  - name: quay.io/karmab/kubectl:multi
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.18-1771330977
    packages:
    - name: sriov-network-operator
      channels:
      - name: stable
    - name: ptp-operator
      channels:
      - name: stable
    - name: cluster-logging
      channels:
      - name: stable-6.4
    - name: loki-operator
      channels:
      - name: stable-6.4
    - name: metallb-operator
      channels:
      - name: stable
    - name: kubernetes-nmstate-operator
      channels:
      - name: stable
    - name: cephcsi-operator
      channels:
      - name: stable-4.18
    - name: mcg-operator
      channels:
      - name: stable-4.18
    - name: numaresources-operator
      channels:
      - name: "4.18"
    - name: ocs-client-operator
      channels:
      - name: stable-4.18
    - name: ocs-operator
      channels:
      - name: stable-4.18
    - name: odf-csi-addons-operator
      channels:
      - name: stable-4.18
    - name: odf-dependencies
      channels:
      - name: stable-4.18
    - name: odf-operator
      channels:
      - name: stable-4.18
    - name: odf-prometheus-operator
      channels:
      - name: stable-4.18
    - name: recipe
      channels:
      - name: stable-4.18
    - name: rook-ceph-operator
      channels:
      - name: stable-4.18
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.19-1772552013
    packages:
    - name: sriov-network-operator
      channels:
      - name: stable
    - name: ptp-operator
      channels:
      - name: stable
    - name: cluster-logging
      channels:
      - name: stable-6.4
    - name: loki-operator
      channels:
      - name: stable-6.4
    - name: metallb-operator
      channels:
      - name: stable
    - name: kubernetes-nmstate-operator
      channels:
      - name: stable
    - name: cephcsi-operator
      channels:
      - name: stable-4.19
    - name: mcg-operator
      channels:
      - name: stable-4.19
    - name: numaresources-operator
      channels:
      - name: "4.19"
    - name: ocs-client-operator
      channels:
      - name: stable-4.19
    - name: ocs-operator
      channels:
      - name: stable-4.19
    - name: odf-csi-addons-operator
      channels:
      - name: stable-4.19
    - name: odf-dependencies
      channels:
      - name: stable-4.19
    - name: odf-operator
      channels:
      - name: stable-4.19
    - name: odf-prometheus-operator
      channels:
      - name: stable-4.19
    - name: recipe
      channels:
      - name: stable-4.19
    - name: rook-ceph-operator
      channels:
      - name: stable-4.19    
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.20-1769431701
    packages:
    #hub
    - name: openshift-gitops-operator
      channels:
      - name: latest
    - name: lvms-operator
      channels:
      - name: stable-4.20
    - name: advanced-cluster-management
      channels:
      - name: release-2.15
    - name: multicluster-engine
      channels:
      - name: stable-2.10
    - name: topology-aware-lifecycle-manager
      channels:
      - name: stable
    # mno
    - name: sriov-network-operator
      channels:
      - name: stable
    - name: ptp-operator
      channels:
      - name: stable
    - name: cluster-logging
      channels:
      - name: stable-6.4
    - name: loki-operator
      channels:
      - name: stable-6.4
    - name: metallb-operator
      channels:
      - name: stable
    - name: kubernetes-nmstate-operator
      channels:
      - name: stable
    - name: cephcsi-operator
      channels:
      - name: stable-4.20
    - name: mcg-operator
      channels:
      - name: stable-4.20
    - name: mcg-operator
      channels:
      - name: stable-4.20
    - name: numaresources-operator
      channels:
      - name: "4.20"
    - name: ocs-client-operator
      channels:
      - name: stable-4.20
    - name: ocs-operator
      channels:
      - name: stable-4.20
    - name: odf-csi-addons-operator
      channels:
      - name: stable-4.20
    - name: odf-dependencies
      channels:
      - name: stable-4.20
    - name: odf-operator
      channels:
      - name: stable-4.20
    - name: odf-prometheus-operator
      channels:
      - name: stable-4.20
    - name: recipe
      channels:
      - name: stable-4.20
    - name: rook-ceph-operator
      channels:
      - name: stable-4.20