#!/bin/bash

LAB_REPO=https://github.com/openshift/federation-dev
LAB_FOLDER=~/federation-dev

if [ -d ${LAB_FOLDER} ]
then
  echo "Backing up original lab folder ${LAB_FOLDER}"
  mv ${LAB_FOLDER}{,.$RANDOM}
fi

echo "Cloning ${LAB_REPO} in ${LAB_FOLDER}"

git clone ${LAB_REPO} ${LAB_FOLDER} &> /dev/null

echo "Lab initialization complete"
