#!/bin/bash

READY=0
WAIT=0
MAX_WAIT=300
APP_NAME="$1"
echo "Checking if application ${APP_NAME} is ready"

DESIRED_STATUS="Healthy"
while [ $READY -eq 0 ]
do
  STATUS=$(argocd app get ${APP_NAME} 2>/dev/null | grep "Health Status" | awk -F ":" '{print $2}' | tr -d " ")
  if [ "0$STATUS" == "0$DESIRED_STATUS" ]
  then
    echo "Application is ready"
    READY=1
  else
    echo "Application is not ready yet, waiting... [$WAIT/$MAX_WAIT]"
    sleep 5
    WAIT=$(expr $WAIT + 5) 
  fi
  if [ $WAIT -ge $MAX_WAIT ]
  then
    echo "Timeout while waiting application ${APP_NAME} to become ready"
    exit 1
  fi
done
