#!/bin/bash

READY=0
WAIT=0
MAX_WAIT=300
CLUSTER="$1"
DEPLOYMENT_NAMESPACE="$2"
DEPLOYMENT_NAME="$3"
echo "Checking if deployment ${DEPLOYMENT_NAME} from namespace ${DEPLOYMENT_NAMESPACE} on cluster ${CLUSTER} is ready"
DESIRED_REPLICAS=$(oc --context=${CLUSTER} -n ${DEPLOYMENT_NAMESPACE} get deployment ${DEPLOYMENT_NAME} -o jsonpath='{ .spec.replicas }')
while [ $READY -eq 0 ]
do
  CLUSTER_REPLICAS_READY=$(oc --context=${CLUSTER} -n ${DEPLOYMENT_NAMESPACE} get deployment ${DEPLOYMENT_NAME} -o jsonpath='{ .status.readyReplicas }')
  if [ "0$CLUSTER_REPLICAS_READY" -eq "0$DESIRED_REPLICAS" ]
  then
    echo "Deployment is ready"
    READY=1
  else
    echo "Deployment is not ready yet, waiting... [$WAIT/$MAX_WAIT]"
    sleep 5
    WAIT=$(expr $WAIT + 5) 
  fi
  if [ $WAIT -ge $MAX_WAIT ]
  then
    echo "Timeout while waiting deployment ${DEPLOYMENT_NAME} from namespace ${DEPLOYMENT_NAMESPACE} on cluster ${CLUSTER} to become ready"
    exit 1
  fi
done