function org_jbpm_workbench_cm_jBPMCaseManagement(){var Q='bootstrap',R='begin',S='gwt.codesvr.org.jbpm.workbench.cm.jBPMCaseManagement=',T='gwt.codesvr=',U='org.jbpm.workbench.cm.jBPMCaseManagement',V='startup',W='DUMMY',X=0,Y=1,Z='iframe',$='position:absolute; width:0; height:0; border:none; left: -1000px;',_=' top: -1000px;',ab='CSS1Compat',bb='<!doctype html>',cb='',db='<html><head><\/head><body><\/body><\/html>',eb='undefined',fb='readystatechange',gb=10,hb='Chrome',ib='eval("',jb='");',kb='script',lb='javascript',mb='moduleStartup',nb='moduleRequested',ob='org_jbpm_workbench_cm_jBPMCaseManagement',pb='Failed to load ',qb='head',rb='meta',sb='name',tb='org.jbpm.workbench.cm.jBPMCaseManagement::',ub='::',vb='gwt:property',wb='content',xb='=',yb='gwt:onPropertyErrorFn',zb='Bad handler "',Ab='" for "gwt:onPropertyErrorFn"',Bb='gwt:onLoadErrorFn',Cb='" for "gwt:onLoadErrorFn"',Db='#',Eb='?',Fb='/',Gb='img',Hb='clear.cache.gif',Ib='baseUrl',Jb='org.jbpm.workbench.cm.jBPMCaseManagement.nocache.js',Kb='base',Lb='//',Mb='locale',Nb='default',Ob='locale=',Pb=7,Qb='&',Rb='__gwt_Locale',Sb='_',Tb='Unexpected exception in locale detection, using default: ',Ub=2,Vb=3,Wb=4,Xb=5,Yb='user.agent',Zb='webkit',$b='safari',_b='msie',ac=11,bc='ie10',cc=9,dc='ie9',ec=8,fc='ie8',gc='gecko',hc='gecko1_8',ic='selectingPermutation',jc='org.jbpm.workbench.cm.jBPMCaseManagement.devmode.js',kc='628A09CFAA2053F914E44E839DC4FD17',lc='es_ES',mc=':1',nc='fr_FR',oc=':2',pc='ja_JP',qc=':3',rc='pt_BR',sc=':4',tc='zh_CN',uc=':5',vc='F50E98B2EAAE68D967BF318D28DA0B72',wc=':',xc='.cache.js',yc='link',zc='rel',Ac='stylesheet',Bc='href',Cc='loadExternalRefs',Dc='jquery-ui/jquery-ui.min.css',Ec='bootstrap-daterangepicker/daterangepicker.css',Fc='bootstrap-select/css/bootstrap-select.min.css',Gc='prettify/bin/prettify.min.css',Hc='uberfire-patternfly.css',Ic='css/patternfly.min.css',Jc='css/patternfly-additions.min.css',Kc='css/bootstrap-switch-3.3.2.min.cache.css',Lc='css/showcase.css',Mc='end',Nc='http:',Oc='file:',Pc='_gwt_dummy_',Qc='__gwtDevModeHook:org.jbpm.workbench.cm.jBPMCaseManagement',Rc='Ignoring non-whitelisted Dev Mode URL: ',Sc=':moduleBase';var q=window;var r=document;t(Q,R);function s(){var a=q.location.search;return a.indexOf(S)!=-1||a.indexOf(T)!=-1}
function t(a,b){if(q.__gwtStatsEvent){q.__gwtStatsEvent({moduleName:U,sessionId:q.__gwtStatsSessionId,subSystem:V,evtGroup:a,millis:(new Date).getTime(),type:b})}}
org_jbpm_workbench_cm_jBPMCaseManagement.__sendStats=t;org_jbpm_workbench_cm_jBPMCaseManagement.__moduleName=U;org_jbpm_workbench_cm_jBPMCaseManagement.__errFn=null;org_jbpm_workbench_cm_jBPMCaseManagement.__moduleBase=W;org_jbpm_workbench_cm_jBPMCaseManagement.__softPermutationId=X;org_jbpm_workbench_cm_jBPMCaseManagement.__computePropValue=null;org_jbpm_workbench_cm_jBPMCaseManagement.__getPropMap=null;org_jbpm_workbench_cm_jBPMCaseManagement.__installRunAsyncCode=function(){};org_jbpm_workbench_cm_jBPMCaseManagement.__gwtStartLoadingFragment=function(){return null};org_jbpm_workbench_cm_jBPMCaseManagement.__gwt_isKnownPropertyValue=function(){return false};org_jbpm_workbench_cm_jBPMCaseManagement.__gwt_getMetaProperty=function(){return null};var u=null;var v=q.__gwt_activeModules=q.__gwt_activeModules||{};v[U]={moduleName:U};org_jbpm_workbench_cm_jBPMCaseManagement.__moduleStartupDone=function(e){var f=v[U].bindings;v[U].bindings=function(){var a=f?f():{};var b=e[org_jbpm_workbench_cm_jBPMCaseManagement.__softPermutationId];for(var c=X;c<b.length;c++){var d=b[c];a[d[X]]=d[Y]}return a}};var w;function A(){B();return w}
function B(){if(w){return}var a=r.createElement(Z);a.id=U;a.style.cssText=$+_;a.tabIndex=-1;r.body.appendChild(a);w=a.contentWindow.document;w.open();var b=document.compatMode==ab?bb:cb;w.write(b+db);w.close()}
function C(k){function l(a){function b(){if(typeof r.readyState==eb){return typeof r.body!=eb&&r.body!=null}return /loaded|complete/.test(r.readyState)}
var c=b();if(c){a();return}function d(){if(!c){if(!b()){return}c=true;a();if(r.removeEventListener){r.removeEventListener(fb,d,false)}if(e){clearInterval(e)}}}
if(r.addEventListener){r.addEventListener(fb,d,false)}var e=setInterval(function(){d()},gb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=e.body;var g;if(navigator.userAgent.indexOf(hb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(ib));for(var i=X;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(Y,j.length-Y)))}h.appendChild(e.createTextNode(jb));g=e.createElement(kb);g.language=lb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=X;i<c.length;i++){g=e.createElement(kb);g.language=lb;g.text=c[i];f.appendChild(g);d(f,g)}}}
org_jbpm_workbench_cm_jBPMCaseManagement.onScriptDownloaded=function(a){l(function(){m(a)})};t(mb,nb);var n=r.createElement(kb);n.src=k;if(org_jbpm_workbench_cm_jBPMCaseManagement.__errFn){n.onerror=function(){org_jbpm_workbench_cm_jBPMCaseManagement.__errFn(ob,new Error(pb+code))}}r.getElementsByTagName(qb)[X].appendChild(n)}
org_jbpm_workbench_cm_jBPMCaseManagement.__startLoadingFragment=function(a){return G(a)};org_jbpm_workbench_cm_jBPMCaseManagement.__installRunAsyncCode=function(a){var b=A();var c=b.body;var d=b.createElement(kb);d.language=lb;d.text=a;c.appendChild(d);c.removeChild(d)};function D(){var c={};var d;var e;var f=r.getElementsByTagName(rb);for(var g=X,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(sb),k;if(j){j=j.replace(tb,cb);if(j.indexOf(ub)>=X){continue}if(j==vb){k=i.getAttribute(wb);if(k){var l,m=k.indexOf(xb);if(m>=X){j=k.substring(X,m);l=k.substring(m+Y)}else{j=k;l=cb}c[j]=l}}else if(j==yb){k=i.getAttribute(wb);if(k){try{d=eval(k)}catch(a){alert(zb+k+Ab)}}}else if(j==Bb){k=i.getAttribute(wb);if(k){try{e=eval(k)}catch(a){alert(zb+k+Cb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};u=d;org_jbpm_workbench_cm_jBPMCaseManagement.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(Db);if(b==-1){b=a.length}var c=a.indexOf(Eb);if(c==-1){c=a.length}var d=a.lastIndexOf(Fb,Math.min(c,b));return d>=X?a.substring(X,d+Y):cb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=r.createElement(Gb);b.src=a+Hb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Ib);if(a!=null){return a}return cb}
function h(){var a=r.getElementsByTagName(kb);for(var b=X;b<a.length;++b){if(a[b].src.indexOf(Jb)!=-1){return e(a[b].src)}}return cb}
function i(){var a=r.getElementsByTagName(Kb);if(a.length>X){return a[a.length-Y].href}return cb}
function j(){var a=r.location;return a.href==a.protocol+Lb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==cb){k=h()}if(k==cb){k=i()}if(k==cb&&j()){k=e(r.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return org_jbpm_workbench_cm_jBPMCaseManagement.__moduleBase+a}
function H(){var i=[];var j=X;function k(a,b){var c=i;for(var d=X,e=a.length-Y;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var l=[];var m=[];function n(a){var b=m[a](),c=l[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(u){u(a,d,b)}throw null}
m[Mb]=function(){var b=null;var c=Nb;try{if(!b){var d=location.search;var e=d.indexOf(Ob);if(e>=X){var f=d.substring(e+Pb);var g=d.indexOf(Qb,e);if(g<X){g=d.length}b=d.substring(e+Pb,g)}}if(!b){b=__gwt_getMetaProperty(Mb)}if(!b){b=q[Rb]}if(b){c=b}while(b&&!__gwt_isKnownPropertyValue(Mb,b)){var h=b.lastIndexOf(Sb);if(h<X){b=null;break}b=b.substring(X,h)}}catch(a){alert(Tb+a)}q[Rb]=c;return b||Nb};l[Mb]={'default':X,'es_ES':Y,'fr_FR':Ub,'ja_JP':Vb,'pt_BR':Wb,'zh_CN':Xb};m[Yb]=function(){var a=navigator.userAgent.toLowerCase();var b=r.documentMode;if(function(){return a.indexOf(Zb)!=-1}())return $b;if(function(){return a.indexOf(_b)!=-1&&(b>=gb&&b<ac)}())return bc;if(function(){return a.indexOf(_b)!=-1&&(b>=cc&&b<ac)}())return dc;if(function(){return a.indexOf(_b)!=-1&&(b>=ec&&b<ac)}())return fc;if(function(){return a.indexOf(gc)!=-1||b>=ac}())return hc;return cb};l[Yb]={'gecko1_8':X,'ie10':Y,'ie8':Ub,'ie9':Vb,'safari':Wb};__gwt_isKnownPropertyValue=function(a,b){return b in l[a]};org_jbpm_workbench_cm_jBPMCaseManagement.__getPropMap=function(){var a={};for(var b in l){if(l.hasOwnProperty(b)){a[b]=n(b)}}return a};org_jbpm_workbench_cm_jBPMCaseManagement.__computePropValue=n;q.__gwt_activeModules[U].bindings=org_jbpm_workbench_cm_jBPMCaseManagement.__getPropMap;t(Q,ic);if(s()){return G(jc)}var o;try{k([Nb,hc],kc);k([lc,hc],kc+mc);k([nc,hc],kc+oc);k([pc,hc],kc+qc);k([rc,hc],kc+sc);k([tc,hc],kc+uc);k([Nb,$b],vc);k([lc,$b],vc+mc);k([nc,$b],vc+oc);k([pc,$b],vc+qc);k([rc,$b],vc+sc);k([tc,$b],vc+uc);o=i[n(Mb)][n(Yb)];var p=o.indexOf(wc);if(p!=-1){j=parseInt(o.substring(p+Y),gb);o=o.substring(X,p)}}catch(a){}org_jbpm_workbench_cm_jBPMCaseManagement.__softPermutationId=j;return G(o+xc)}
function I(){if(!q.__gwt_stylesLoaded){q.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=r.createElement(yc);b.setAttribute(zc,Ac);b.setAttribute(Bc,G(a));r.getElementsByTagName(qb)[X].appendChild(b);__gwt_stylesLoaded[a]=true}}
t(Cc,R);c(Dc);c(Ec);c(Fc);c(Gc);c(Hc);c(Ic);c(Jc);c(Kc);c(Lc);t(Cc,Mc)}
D();org_jbpm_workbench_cm_jBPMCaseManagement.__moduleBase=F();v[U].moduleBase=org_jbpm_workbench_cm_jBPMCaseManagement.__moduleBase;var J=H();if(q){var K=!!(q.location.protocol==Nc||q.location.protocol==Oc);q.__gwt_activeModules[U].canRedirect=K;function L(){var b=Pc;try{q.sessionStorage.setItem(b,b);q.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(K&&L()){var M=Qc;var N=q.sessionStorage[M];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(N)){if(N&&(window.console&&console.log)){console.log(Rc+N)}N=cb}if(N&&!q[M]){q[M]=true;q[M+Sc]=F();var O=r.createElement(kb);O.src=N;var P=r.getElementsByTagName(qb)[X];P.insertBefore(O,P.firstElementChild||P.children[X]);return false}}}I();t(Q,Mc);C(J);return true}
org_jbpm_workbench_cm_jBPMCaseManagement.succeeded=org_jbpm_workbench_cm_jBPMCaseManagement();