:role: satellite-manage-activationkey
:author: GPTE Team
:tag1: configure_satellite
:tag2: configure_satellite_activationkey
:main_file: tasks/main.yml
:version_file: tasks/version_6.4.yml
:script_file: files/activationkey_script_version_6.4.sh

Role: {role}
============

This role creates, adds repos and publish satellite content-view.

Requirements
------------

Following are the requirements:

. Satellite must be install and setup.
. Hammer cli config must be configured/updated with privileged user and password to run the satellite cli.
. Subscription, Life-cycle, and content-view should be exist. 
 

Role Variables
--------------

* Following are the variable which needs to be defined 

|===
|satellite_version: "Digit" |Required |satellite version
|org: "String" |Required |Organization name
|org_label: "String" |Required | Organization label in string without space
|org_description: "String" |Required | Organization description
|satellite_content: {Dictionary} |Required | Main dictionary variable
|content_view: "String" | Requird | Name of content-view
|life_cycle: "String" | Required | Name of life_cycle for activation key
|subscriptions: [List] | Required | List of subscriptions to add in activation key
|===
    
* Example variables

[source=text]
----
satellite_version: 6.4
org: "gpte"
org_label: "gpte"
org_description: "Global Partner Training and Enablement"
satellite_content:
  - name:             "Ansible server"
    life_cycle:       "Prod"
    content_view:     "Ansible servers content"
    activation_key:   "capsule_server_key"
    subscriptions:
      - "Employee SKU    
  - name:             "Three Tier App"
    life_cycle:       "Dev"
    content_view:     "Three Tier App"
    activation_key:   "three_tier_app"
    subscriptions:
      - "Employee SKU"

----

Tags
---

|===
|{tag1} |Consistent tag for all satellite config roles
|{tag2} |This tag is specific to this role only
|===

* Example tags

----
## Tagged jobs
ansible-playbook playbook.yml --tags configure_satellite,configure_satellite_activationkey

## Skip tagged jobs
ansible-playbook playbook.yml --skip-tags configure_satellite,configure_satellite_activationkey
----

Example Playbook
----------------

How to use your role (for instance, with variables passed in playbook).

[source=text]
----
[user@desktop ~]$ cat sample_vars.yml
satellite_version: 6.4
org: "gpte"
org_label: "gpte"
org_description: "Global Partner Training and Enablement"
satellite_content:
  - name:             "Ansible server"
    life_cycle:       "Prod"
    content_view:     "Ansible servers content"
    activation_key:   "capsule_server_key"
    subscriptions:
      - "Employee SKU    
  - name:             "Three Tier App"
    life_cycle:       "Dev"
    content_view:     "Three Tier App"
    activation_key:   "three_tier_app"
    subscriptions:
      - "Employee SKU"

[user@desktop ~]$ cat playbook.yml
- hosts: satellite.example.com
  vars_files:
    - sample_vars.yml
  roles:
    - satellite-manage-activationkey

[user@desktop ~]$ ansible-playbook playbook.yml
----

Tips to update Role
------------------

To extend role works for other version, create new file named  version_{{satellite_version}}.yml and import newly created file in main.yml . Create new script in files directory for activation key action.

for reference look at link:{main_file}[main.yml] , link:{version_file}[version_6.4.yml] and link:{script_file}[script]


Author Information
------------------

{author}
