= VMware vSphere Configuration: vmware-vcenter-config

== Overview

The `vmware-vcenter-config` is an Agnosticd configuration designed to streamline the provisioning of user accounts and the creation of virtual machines (VMs) in a VMware vSphere environment. This configuration is optimized for use with Binder but can also be utilized independently if there is a need to set up a user and create VMs.

== Configuration Details

The configuration performs the following tasks:
1. Adds a user in the vCenter.
2. Creates three VMs in the VMware environment:
   - `database`
   - `winweb01`
   - `winweb02`

== Usage

This configuration is primarily intended for use with Binder but is versatile enough to be used separately. When used standalone, it provides a simple and effective method for creating user accounts and VMs in a VMware vSphere environment.

== Instructions

1. Ensure you have the necessary permissions and access to the VMware vSphere environment.
2. Apply the `vmware-vcenter-config` using the appropriate Agnosticd playbooks and commands.
3. Verify that the user is created in the vCenter and that the VMs (`database`, `winweb01`, `winweb02`) are successfully deployed.

== Contact Information

For more information or assistance, please contact:
- Author: Mitesh Sharma <Mitsharm@redhat.com>
- Author: Prakhar Srivastava <prakhar@redhat.com>
- Manager: Aleksandr <manager_email@domain.com>

== Running Ansible Playbook


=== Deploying the config

You can deploy this config by running the following command from the `ansible`
directory. You will have to provide credentials and adjust settings to your own
environment.
You can run the playbook with the following arguments, from the `ansible` directory, to overwrite the default variable values:

[source,bash]
.Create your own copy of sample_vars.yml
----
cp configs/vmware-vcenter-config/default_vars.yml \
  configs/vmware-vcenter-config/my_vars.yml
----

[source,bash]
.Edit the variables to enter your pull_secret and set deployment options
----
vi configs/vmware-vcenter-config/my_vars.yml
----

[source,bash]
.Run agnosticd provision
----
ansible-playbook main.yml \
  -e @configs/vmware-vcenter-config/my_vars.yml \
  -e @~/secret.yml
----

=== To Delete an environment

To delete an environment, just run `destroy.yml` instead of `main.yml` with the same set of variables.

[source,bash]
.Run agnosticd destroy
----
ansible-playbook destroy.yml \
  -e @configs/vmware-vcenter-config/my_vars.yml \
  -e @~/secret.yml
----
