---
- name: Install Operator and configure external Ceph
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/{{ cluster_name }}/auth/kubeconfig
  block:
    - name: Set up ODF operator
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template',  item ) | from_yaml }}"
      loop:
        - odf-ns.yaml
        - odf-og.yaml
        - odf-sub.yaml.j2

    - name: Set up StorageCluster
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template',  item) | from_yaml }}"
      register: r_storagecluster
      until: r_storagecluster is success
      retries: 30
      delay: 30
      loop:
        - secret.yaml.j2
        - storageclass.yaml.j2
        - storagecluster.yaml.j2

    - name: Create PVC for image registry
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template',  'pvc-imageregistry.yaml') | from_yaml }}"
      register: r_pvc
      until: r_pvc is success
      retries: 30
      delay: 30

    - name: Configure registry
      ansible.builtin.shell: >
        oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch
        '{"spec":{"rolloutStrategy":"Recreate","replicas":1,"storage":{"pvc":{"claim":"pvc-image-registry"}},
        "managementState": "Managed"}}'

    - name: Enable ODF UI plugin
      ansible.builtin.shell: >
        oc patch console.operator cluster -n openshift-storage --type json -p '[{"op": "add", "path": "/spec/plugins", "value": ["odf-console"]}]'

    - name: Configure NooBaa pvPool numVolumes
      block:
        - name: Wait until NooBaa BackingStore is available
          kubernetes.core.k8s_info:
            api_version: noobaa.io/v1alpha1
            kind: BackingStore
            name: noobaa-default-backing-store
            namespace: openshift-storage
            wait: true
            wait_sleep: 10
            wait_timeout: "{{ ocp4_workload_external_odf_noobaa_deploy_timeout }}"
            wait_condition:
              type: Available
              status: "True"

        - name: Set NooBaa pvPool numVolumes
          kubernetes.core.k8s:
            state: patched
            api_version: noobaa.io/v1alpha1
            kind: BackingStore
            name: noobaa-default-backing-store
            namespace: openshift-storage
            definition:
              spec:
                pvPool:
                  numVolumes: "{{ ocp4_workload_external_odf_noobaa_pv_pool_num_volumes | int }}"
