# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:/usr/local/maven/bin:$PATH
export GUID=`hostname | awk -F. '{print $2}'`
