# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

export PATH=$PATH:$HOME/bin:/usr/local/bin:/usr/local/apache-maven-3.5.4/bin
export GUID=`hostname | awk -F. '{print $2}'`