= OSP Sandbox

== Config Description

This config is primarily used to simply provision an OpenStack project. The intended use is for development and testing of AgnosticD configs and workloads. The config includes:

* OSP project with basic quota
* One bastion host
* Credentials for OSP project

== Review the Env_Type variable file

* This file link:./env_vars.yml[./env_vars.yml] contains all the variables you need to define to control the deployment of your environment.  These are the defaults.

* Override the defaults for your environment by creating your own myenvironment-variables.yml file, as below.

== Running Ansible Playbook

=== Running Playbook With Environment and Secrets files

You can create yaml files of your desired configs and secrets and execute them:

`ansible-playbook ansible/main.yaml -e @myenvironment-variables.yml  -e @my-secrets.yml`

=== To Delete an environment

Run the `destroy_env.yml` playbook.

Ex: `ansible-playbook ansible/configs/osp-sandbox/destroy_env.yml -e @myenvironment-variables.yml  -e @my-secrets.yml`

The teardown process is roughly as follows:
* Delete compute & storage resources
** Use `openstack purge`
** ex: `openstack --os-cloud sten2 project purge --keep-project --project sten2-project`
* Delete network resources
** Use `neutron purge`
** ex: `neutron --os-cloud sten2 purge bb4e371f4bf443feb6e4435c8f5df6ae`
* Delete any trunk ports
* Delete the Heat stack
** If you don't delete the HOT as the user that created it, the keypair will not be deleted
* Delete Keypair if necessary
** TODO: add this functionality
* Cleanup DNS entries for bastion & OpenShift
* Delete project

== Workstation Setup:
With either setup, you also need to have a `clouds.yaml` file on your system with credentials.
You can store this either in your working directory or in `~/.config/openstack/clouds.yaml`.

=== RHEL:

To prepare an admin host to deploy this config. This has been tested on RHEL 7.7.
sudo subscription-manager register
sudo subscription-manager attach --pool=<yourpool>
sudo subscription-manager repos --disable=* --enable rhel-7-server-optional-rpms \
  --enable rhel-7-server-rpms --enable rhel-7-server-extras-rpms

sudo yum update -y

sudo yum install python-virtualenv git gcc

git clone https://github.com/redhat-cop/agnosticd.git
cd agnosticd
git checkout disco-ocp4

virtualenv ~/venv-openstack
source ~/venv-openstack/bin/activate

pip install -r ./ansible/configs/ocp4-disconnected-ha-lab/files/admin_host_requirements.txt

=== MacOS:
==== Install python3:
brew install python

==== Make sure your path has this in it:
PATH="/usr/local/opt/python/libexec/bin:/usr/local/bin:$PATH"

==== Make sure virtualenv and virtualenvwrapper are installed system wide
pip install virtualenv
pip install virtualenvwrapper

==== Add this to your .bashrc
export WORKON_HOME=~/.virtualenvs
[ -f /usr/local/bin/virtualenvwrapper.sh ] && source /usr/local/bin/virtualenvwrapper.sh

==== To start a new python virtual env
mkvirtualenv venv-openstack

==== Activate virtual env
workon venv-openstack

==== Clone repo and install python libraries
git clone https://github.com/redhat-cop/agnosticd.git
cd agnosticd
git checkout disco-ocp4
pip install -r ./ansible/configs/ocp4-disconnected-ha-lab/files/macos_requirements.txt