= Ansible Agnostic Deployer

:numbered!:

=== << docs/About.adoc  About this Tool>> 

== Directory Structure

This section discusses the subdirectories of 
`ansible_agnostic_deployer/ansible`.  

Unless otherwise stated, files contained within a given directory are not 
intended to be modified as part of general use.

==== cloud_providers 

Playbooks which interact with cloud provider APIs.

==== configs

Directory to store environment configurations.

Each subdirectory corresponds to a preconfigured environment type, and 
contains playbooks and config files used to deploy and configure the 
environment.

Ansible recognizes exactly one of these configs per deployment via the 
variable `{{ env_type }}`.  Exactly one `env_type` may be specified per 
deployment.  

Users are intended to copy and modify existing environment configs to suit 
their own needs, or write their own configs following the following minimum 
file structure:

```
<config_name>/
  pre_infra.yml
  post_infra.yml
  pre_software.yml
  post_software.yml
  env_vars.yml
  env_secret_vars.yml
  ssh_vars.yml
  files/
    cloud_providers/
      <cloud_provider>_cloud_template.j2
```
The purpose of each file will be discussed later in this document.

==== library

Python modules for communicating with cloud providers. 

==== roles

Ansible roles which are common among multiple configurations.

==== software_playbooks

Playbooks which install and configure a software environment.  Must be cross 
environment compatible provided hardware, software, and ansible hostvars 
dependencies are met.

Hardware, software, and ansible hostvars dependencies should be documented 
in each playbook.

Ansible recognises exactly one of these software playbooks per environment via 
the ansible variable `software_to_deploy`.

Users may utilise existing software playbooks, modify copies of existing 
software playbooks, or write their own software playbooks from scratch.

==== workdir

Empty directory which is used to store temporary files at runtime.

=== tools

Optional tools for generating environment configs and cloud provider templates.  
A tutorial for these tools can be found at link:docs/Tools.adoc[Tools.adoc].


== Deploying to Cloud Providers

A deployment is executed by running the `main.yml` playbook with Ansible.  
The following are variables are always necessary to be specified on the
command line:

`env_type`
  the name (not path) of a directory in 
  `ansible_agnostic_deployer/ansible/configs`

`cloud_provider`
  the name of the cloud provider to use

`ANSIBLE_REPO_PATH`
  full path to `ansible_agnostic_deployer/ansible`

Some environments in `configs` will require extra ansible variables to be 
passed on the command line.  Be sure to read the individual documentation 
for an environment configuration before attempting to deploy it.

In addition, credentials will need to provided for any cloud-provider you 
wish to use. Please see link:docs/Credentials.adoc[Credentials] 
for details.

Example usage:

```
ansible-playbook main.yml \
  -e "env_type=hello_world" \
  -e "cloud_provider=ravello" \
  -e "ANSIBLE_REPO_PATH=/path/to/ansible_agnostic_deployer/ansible"
```

Once run, `main.yml` will execute a series of playbooks based on the command 
line arguments it was passed.  The resulting deployment is be considered to 
occur in two sequential phases, an infrastructure phase, and a software phase.

=== Infrastructure Deployment Phase

The infrastructure deployment phase configures the virtual hardware and base operating 
system.  The primary work which happens in this phase occurs in 
`ansible/cloud_providers/<cloud_provider>_infrastructure_deployment.yml`.

The `<cloud_provider>_infrastructure_deployment.yml` playbook makes API calls 
to the cloud provider to set up the virtual hardware and disk images as it is 
defined in the environment config's cloud template.  This template is located 
in `ansible_agnostic_deployer/ansible/configs/files/cloud_providers/
<cloud_provider>_cloud_template.j2`.

Cloud templates are provider specific, and a template must exist for each 
provider the environment is intended to be deployed to.  Information on 
creating cloud provider templates is located link:docs/Cloud-Templates.adoc[here]. 
We are working on making this process more provider agnostic.  In the meantime, we 
have created some tools to assist in generating these templates, located
link:ansible/tools[here].  

It is possible to manually configure the infrastructure deployment phase 
before and after the `<cloud_provider>_infrastructure_deployment.yml` playbook 
is called by adding tasks to the `pre_infra.yml` and `post_infra.yml` playbooks 
respectively.  

The entire calling order of playbooks in the infrastructure phase is as follows:

```
configs/<env_type>/pre_infra.yml 
  Extra configuration tasks which occur before virtual hardware provisioning
    |
    V
cloud_providers/<cloud_provider>_infrastructure_deployment.yml 
  Provisions virtual hardware and registers hostnames with ansible
    |
    V
configs/<env_type>post_infra.yml
  Extra provisioning tasks which occur after the basic 
```
=== Software Deployment Phase

The software deployment phase installs and configures software in a deployed 
environment.  The principal playbook for this task will be selected from 
`ansible/software_playbooks`. 


It is possible to manually configure the software deployment phase before and 
after `software_playbooks/<software_to_install>.yml` is called by adding tasks 
to the `pre_software.yml` and `post_software.yml` playbooks respectively.  

The entire calling order of playbooks in the infrastructure phase is as follows:

```
configs/<env_type>/pre_software.yml 
  Extra environment-specific tasks which occur before software is installed
    |
    V
software_playbooks/<software_to_install>.yml
  Installs and configures a software environment
  (these are shared between environment configurations)
    |
    V
configs/<env_type>post_infra.yml
  Extra environment-specific configuration tasks 
  which occur after the software playbook is called
```

=== Vars Files

Most plays you run should include the following vars files:

env_vars.yml

  With a few exceptions, all global ansible variables are stored in this file.

env_secret_vars.yml

  Any variables containing sensitive data are stored here. This file is not
  tracked by git.

ssh_vars.yml

  This file stores the information Ansible needs for using a bastion
  host as a proxy workstion.

=== Creating Cloud Provider Templates

The minimum hardware configuration for creating an environment is a bastion 
proxy machine.

Please see link:docs/Cloud-Templates.adoc[Cloud Templates].

=== Setting up cloud provider credentials

link:docs/Credentials.adoc[Credentials]

=== Creating and running a deployment

link:docs/Tutorial-Ravello.adoc[Tutorial (Ravello)]
