= User Stories for AAD

* A new product was acquired by Red Hat and the Architect wants to provide a new product as part of a deployable environment with AAD

* It's time consuming to put together environments. The Engineer wants to re-use deployment and configuration management for a product that's already implemented in AAD to provide it integrated with another product.

* There's a new feature in OpenShift, and the Enineer wants to implement a feature in a product that will only impact a subset of the users of a product, and the engineers who rely on the product in their environments.

* The SA wants to deliver a demo, and test their environment immediately before a demo, and clean up test data so the demo will be pristine.

* The SA Manager wants needs to track effort and spending per opporunity, and wants a report of each her SA's activities, and a cost-per-opportunity report.

* The Enablement Architect wants to set a date to automatically destroy student envionrments.

* The Enablement Architect wants to increase lab testing velocity by deploying environments via API.

* The Enablement Architect wants to teach in a situation where two environments networked together, so multiple clusters can intercommunicate.

* The Operators want a dashboard of environments as they launch, run, and are destroyed. Example: It's difficult to respond to the question, "Are there any problems deploying or destroying any environments?  Operators cannot quickly see the entire operational landscape of the system.

* The Architect wants a new cloud service feature added to an environment.  Example: New class requirements demand object storage for environemtns. So, S3 buckets with quotas need to be setup for each environment.

* The SA wants to use AAD to create a demo of Quay for their customer from a basic deployment, as an upstream of a new OpenShift Cluster with Jenkins CI, a test Java application and user policies for dev/test/qa/admin/security. Quay will use Clair to check images.  There will be geo-replication of the underlying Quay datastore (S3 or the like).
