= ocp4_workload_opendatahub_old - Deploy Open Data Hub version 'legacy' into openshift project

== Role overview

*This role installs the legacy Open Data Hub operator into an openshift namespace. 'old' refers to the operator being a per-namespace operator. Later versions of the operator are cluster-wide, so will not install correctly with this role.


* This role installs the Open Data Hub operator into an openshift namespace. It consists of the following tasks files:
** Tasks: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an
 environment for the workload deployment.
*** Debug task will print out: `pre_workload Tasks completed successfully.`

** Tasks: link:./tasks/workload.yml[workload.yml] - Used to deploy ODH
*** This deploys odh into an existing namespace, parametrised as ocp4_workload_odh_namespace.
*** Debug task will print out: `workload Tasks completed successfully.`

** Tasks: link:./tasks/post_workload.yml[post_workload.yml] - Used to
 configure the workload after deployment
*** This role doesn't do anything here
*** Debug task will print out: `post_workload Tasks completed successfully.`

** Tasks: link:./tasks/remove_workload.yml[remove_workload.yml] - Used to
 delete the workload
*** This role removes ODH
*** Debug task will print out: `remove_workload Tasks completed successfully.`

== Review the defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you need to define to control the deployment of your workload.

* The variable *odh_project* is mandatory to assign the workload to the correct OpenShift user.
* A variable *silent=True* can be passed to suppress debug messages.


=== Deploy a Workload with the `ocp-workload` config [Mostly for testing]

Create a file `workload_vars.yaml` with your variables:
----
cloud_provider: none
env_type: ocp-workloads
target_host: bastion.dev4.openshift.opentlc.com

ocp_workloads:
- ocp4_workload_codeready_workspaces

#become_override: false

# If the ocp-workload supports it, you should specify the OCP user:
ocp_username: system:admin

# Usually the ocp-workloads want a GUID also:
guid: changeme
----

From the Agnosticd/ansible directory run the playbook:

----
ansible-playbook main.yml -e @workload_vars.yml -e ACTION="create"
----

=== To Delete an environment

From the Agnosticd/ansible directory run the playbook:

----
ansible-playbook main.yml -e @workload_vars.yml -e ACTION="remove"
----
