= Ansible Linklight Config

Ansible Linklight is an example of an existing deployer being wrapped by
Ansible. Linklight is capable of deploying multiple different lab environments:

link:https://github.com/network-automation/linklight[Ansible Linklight Project]

* Engine
** 4 Linux nodes
* Networking 
** V1 Networking Lab with 2 Linux nodes, 2 Cisco routers
* Networking V2
** V2 Networking Lab with 2 Linux nodesi, 4 Cisco routers
** (This is acheieved by seting the varaible `networking; true` 

The `linklight` deployer is called by first running a fairly typical `Ansible Agnostic Deployer`
`pre_infra.yml` but at the end of that playbook:

Cloning the `linklight` repo to a specfic commit, this is currently hard coded into the deployer script
and executing the cloned provisioioning playbook. `linklight` specfic vars are made availble via:

* linklight_all_vars.yml

And one of:

* linklight_engine_vars.yml
* linklight_networking_v1_vars.yml
* linklight_networking_v2_allcisco_vars.yml


== How the Different Labs get Configured

For deployment via RHPDS or similar deployer script will substitute the value of
`student_workloads` into a call to the relevant lab var file e.g.

Deployer Usage:
[source,bash]
----
$ mydeploy-script.sh --student_workloads=linklight_engine --more_args ...
----

[source,bash]
----
ansible-playbook main.yml \
  -e ANSIBLE_REPO_PATH=${ANSIBLE_REPO_PATH} \
  -e guid=${GUID} \
  ..... args omitted for brevity
  -e @configs/linklight/linklight_all_vars.yml \
  -e @configs/linklight/${STUDENT_WORKLOAD}_vars.yml 
----


== Set up your "Secret" variables

* You need to provide some credentials for deployments to work
* Create a file called "env_secret_vars.yml" and put it in the
 ./ansible/configs/CONFIGNAME/ directory.
** At this point this file *has to be created* even if no vars from it are used.
* You can choose to provide these values as extra vars (-e "var=value") in the
 command line if you prefer not to keep sensitive information in a file.

.Example contents of "Secret" Vars file
----
# ## Logon credentials for Red Hat Network
# ## Required if using the subscription component
# ## of this playbook.
rhel_subscription_user: ''
rhel_subscription_pass: ''
#
# ## LDAP Bind Password
bindPassword: ''
#
# ## Desired admin name and password if required
admin_user: ""
admin_user_password: ""
#
# ## AWS Credentials. This is required.
aws_access_key_id: ""
aws_secret_access_key: ""
#If using repo_method: satellite, you must set these values as well.
satellite_url: satellite.example.com
satellite_org: Sat_org_name
satellite_activationkey: "rhel7basic"

----

== Running Ansible Playbook

You can run the playbook with the following arguments 

[NOTE]
====

Also it sets an ANSIBLE_CONFIG var to load a specfic set of vars for these labs.
This is the HIGHEST precedence for `ansible.cfg` so will mask any other
`ansible.cfg`
====


[source,bash]
----
export ANSIBLE_CONFIG=configs/linklight/ansible.cfg

GUID=td08
ENV_TYPE=linklight
CLOUD_PROVIDER=ec2

EC2_REGION=us-east-1
EC2_NAME_PREFIX=${GUID}
EC2_KEYNAME=${GUID}-link

STUDENT_TOTAL=2

ANSIBLE_REPO_PATH=$(pwd)

ansible-playbook main.yml \
  -e ANSIBLE_REPO_PATH=${ANSIBLE_REPO_PATH} \
  -e guid=${GUID} \
  -e env_type=${ENV_TYPE} \
  -e project_tag=${ENV_TYPE}-${GUID} \
  -e ec2_key_name=${EC2_KEYNAME} \
  -e ec2_region=${EC2_REGION} \
  -e ec2_name_prefix=${GUID} \
  -e cloud_provider=${CLOUD_PROVIDER} \
  -e "{'student_total': ${STUDENT_TOTAL}}" \
  -e software_to_deploy=none \
  --skip-tags=deploy_infrastructure,post_infra_tasks,pre_software_tasks,deploy_software,post_software,email \
  -e @configs/linklight/linklight_all_vars.yml \
  -e @configs/linklight/linklight_engine_vars.yml 

----

== Deploying other Linklight Labs

=== Networking v1 Lab

To deploy networking v1 substitute the last line above (`-e @configs/linklight/linklight_engine_vars.yml`) for 
`-e @configs/linklight/linklight_networking_v1_vars.yml`

=== Networking v2 Lab (all Cisco)

To deploy networking v1 substitute the last line above (`-e @configs/linklight/linklight_engine_vars.yml`) for 
`-e @configs/linklight/linklight_networking_v2_allcisco_vars.yml`


=== To Delete an environment

This deletes the Ansible Engine Lab, notes below for the Networking labs

[source,bash]
----
GUID=td08
ENV_TYPE=linklight

EC2_NAME_PREFIX=${GUID}
EC2_REGION=us-east-1

ANSIBLE_REPO_PATH=$(pwd)

ansible-playbook ${ANSIBLE_REPO_PATH}/configs/${ENV_TYPE}/destroy_env.yml \
  -e ANSIBLE_REPO_PATH=${ANSIBLE_REPO_PATH} \
  -e ec2_name_prefix=${GUID} \
  -e ec2_region=${EC2_REGION} \
  -e @configs/linklight/linklight_all_vars.yml \
  -e @configs/linklight/linklight_engine_vars.yml
----

To delete networking v1 substitute the last line above (`-e @configs/linklight/linklight_engine_vars.yml`) for·
     `-e linklight_networking_v1_vars.yml`

To delete networking v2 substitute the last line above (`-e @configs/linklight/linklight_engine_vars.yml`) for·
     `-e linklight_networking_v2_allcisco_vars.yml`
