= EC2 image generator

This role have three ways to operate:

It will be possible to do:
* Copy a VM disk (ephemeral) as a new Image (for testing before upload to IBM Cloud)
* Copy a Volume as a new Image (for testing before upload to IBM Cloud)
* Upload images/vms/volumes to IBM Cloud (after convert it to `qcow2` format)

Variables used in this role:
* ec2_copy_vm_disk_to_image_task = False 
* ec2_copy_vm_disk_to_image_list = []
* ec2_copy_volume_to_image_task = False
* ec2_copy_volume_to_image_list = []
* ec2_upload_storage_to_ibmcloud_task = False
* ec2_upload_storage_to_ibmcloud_list = []

Examples:

* ec2_copy_vm_disk_to_image_list: [{src: "myvm1", dest: "myvm1-image"}, {src: "myvm2", dest: "myvm2-image"}]
* ec2_copy_volume_to_image_list: [{src: "volume-rhel-8.4-osp162-ipmihost", dest: "rhel-8.4-osp162-ipmihost"}]
* ec2_upload_storage_to_ibmcloud_list: [{types: "vms", items: [{src: "3compute01", dest: "3compute01-root-162.qcow2"}, {src: "3compute02", dest: "3compute02-root-162.qcow2"] }]

TODO:
Libraries examples:
* Copy a VM disk to image:
     ec2_copy_vm_disk_to_image:
       project: "{{ ec2_project }}"
       ceph_cluster: "{{ ceph_cluster | default('red') }}"
       items:
        - src: myvm1
          dest: myvm1-image
        - src: myvm2
          dest: myvm2-image

* Copy a Volume as a new Image
     ec2_copy_volume_to_image:
       project: "{{ ec2_project }}"
       ceph_cluster: "{{ ceph_cluster | default('red') }}"
       items: 
          - src: volume-rhel-8.4-osp162-ipmihost
            dest: rhel-8.4-osp162-ipmihost


* Upload images/vms/volumes to IBM Cloud
     ec2_upload_storage_to_ibmcloud:
       ibm_endpoint: "{{ ibm_endpoint }}"
       ibm_auth_endpoint: "{{ ibm_auth_endpoint }}"
       ibm_api_key: "{{ ibm_api_key }}"
       ibm_resource_id: "{{ ibm_resource_id }}"
       bucket: "{{ ibm_bucket_name }}"
       project: "{{ image_store }}"
       output_dir: "{{ output_dir }}"
       glance_pool: "{{ ceph_cluster | default('red') }}-{{ type }}"
       overwrite: "{{ overwrite_image | default('false') }}"
       type: "vms"
       items: 
         - src: 3compute01
           dest: 3compute01-root-162.qcow2
         - src: 3compute02
           dest: 3compute02-root-162.qcow2
         - src: 2ctrl01
           dest: 2ctrl01-root-162.qcow2



