= ocp-workload-integreatly-rhte-2019-lab

== Role overview

This deploys the `ocp-workload-integreatly` and then creates a 3scale tenant
for each user that was created on the cluster.

== Deployment

Refer to the readme for `ocp-workload-integreatly` for more information. A
simple set of commands to test this on an RHPDS OpenShift 3.11 (or Integreatly
Workshop instance after running an uninstall) are outlined below.

Note that `NAME` and `GUID` are the values from your RHPDS deployment.
For example, if your master is `master.incredible-6802.openshiftworkshop.com`
then `NAME=incredible` and `GUID=6802`.

=== 1. Prepare the install

1. SSH to the Bastion from your local machine
2. Become root
3. Clone this installer repository
4. Create an inventory file

Here's an example:

```bash
$ ssh -i ~/.ssh/ocp-workshop.pem ec2-user@bastion.$NAME-$GUID.openshiftworkshop.com

Last login: Wed Aug 14 17:45:48 2019 from 206.169.83.146
[ec2-user@bastion 0 ~]$ sudo -i

# If you're developing a workload then this URL will be your fork
[root@bastion 0 ~] git clone https://github.com/redhat-cop/agnosticd agnosticd
[root@bastion 0 ~] cd agnosticd
[root@bastion 0 ~] git checkout development
```

=== 2. Create an inventory file

While still logged in as root on the Bastion, create a file containing the
following, and replacing `$NAME` and `$GUID` with correct values:

```
[OSEv3:children]
master

[OSEv3:vars]
ansible_user=ec2-user

[master]
master1.$NAME-$GUID.internal
```

You can write it anywhere, e.g a file `install-inventory` in the home dir.

=== 3. Run the installation

Finally, run the following command from the root of the repository you cloned
as root user from the Bastion to start the install:

_Note: The variables below are for an OCP 3 RHPDS Workshop with self-signed
certs. Change the cert related variables if valid SSL certs are configured._

```
ansible-playbook -i ~/install-inventory ./ansible/configs/ocp-workloads/ocp-workload.yml -v \
  -e"ocp_workload=ocp-workload-integreatly-rhte-2019-lab" \
  -e"ansible_user=ec2-user" \
  -e"guid=${GUID}" \
  -e"silent=false" \
  -e"inventory_hosts_file=inventories/tower.template" \
  -e"self_signed_certs_enabled=true"\
  -e"ocp_user_needs_quota=false" \
  -e"lets_encrypt_production=false" \
  -e"eval_self_signed_certs=true" \
  -e"eval_seed_users_count=50" \
  -e"rhsso_identity_provider_ca_cert_path=ca.crt" \
  -e"ACTION=create"
```

Explanation of variables:

* `ocp_workload` is the workload to run, leave this as is
* `inventory_hosts_file` must be set to `inventories/tower.template` (this file is link:https://github.com/integr8ly/installation/blob/master/inventories/tower.template[on GitHub])
* `silent` controls log output from the playbook(s)
* `rhsso_identity_provider_ca_cert_path` needs to be set to `ca.crt` unless letsencrypt is available (i.e when `lets_encrypt_production` is `true`)
* `self_signed_certs_enabled` needs to be `true` unless the RHPDS instance has valid certs configured
* `lets_encrypt_production` must be `false` unless the RHPDS instance has valid certs configured
* `eval_self_signed_certs` needs to be `true` unless the RHPDS instance has valid certs configured