= ocp-workload-rhte-mw-api-biz

== NOTES

=== Common Lab Setup
. Using a version of oc utility that corresponds to your target OCP cluster, ensure oc utility is already authenticated as the cluster-admin:   opentlc-mgr
. This workload only needs to be executed once per OCP cluster
. This workload provisions the following:
.. A project *rhdm* into which the quoting decision manager is deployed.
.. Imports templates for RH-SSO & Quoting apps.

=== Tenants

This workload can also create the nultiple tenants for the lab.

. Specify following values:
.. specify `ACTION="tenant_mgmt"`
..  specify `START_TENANT` and `END_TENANT` variables

. This workload provisions the following:
.. An empty project *userX-client*
.. A project *userX-sso* provisioned with RH SSO ephemeral deployment.
.. A project *userX-fuse-ignite* provisioned with Syndesis

. In addition, the following changes are effected on the *userX-gw* project:
.. Delete the default routes.
.. Create staging and production routes for quote application.
.. Resume deployment of staging and production apicast containers.



== Execution using localhost oc client

-----


WORKLOAD="ocp-workload-rhte-mw-api-biz"
SUBDOMAIN_BASE=`oc whoami --show-server | cut -d'.' -f 2,3,4,5 | cut -d':' -f 1`


# API manager provision
ansible-playbook -i localhost, -c local ./configs/ocp-workloads/ocp-workload.yml \
                    -e"ocp_workload=${WORKLOAD}" \
                    -e"ACTION=create" \
                    -e"subdomain_base=$SUBDOMAIN_BASE"


# Tenant management
START_TENANT=1
END_TENANT=1


# Tenant Management
ansible-playbook -i localhost, -c local ./configs/ocp-workloads/ocp-workload.yml \
                    -e"ocp_workload=${WORKLOAD}" \
                    -e"ACTION=tenant_mgmt" \
                    -e"start_tenant=$START_TENANT" \
                    -e"end_tenant=$END_TENANT" \
                    -e"subdomain_base=$SUBDOMAIN_BASE"


# Delete
REMOVE_TENANTS_ONLY=true
ansible-playbook -i localhost, -c local ./configs/ocp-workloads/ocp-workload.yml \
                    -e"ocp_workload=${WORKLOAD}" \
                    -e"ACTION=remove" \
                    -e"subdomain_base=$SUBDOMAIN_BASE" \
                    -e"REMOVE_TENANTS_ONLY=$REMOVE_TENANTS_ONLY"
-----


