---
become_override: false
ocp_username: opentlc-mgr
silent: false
num_users: 5
kserve_agent_image: >-
  registry.redhat.io/rhoai/odh-kserve-agent-rhel9@sha256:191aa92865c26ef1e5f9856a8ca91263782b4627db65bfcc61c9879537d34b0b
