= NooBaa Workload

This workload deploys and configures NooBaa operator on OpenShift 4 cluster. 

== Deploy the workload
[source, bash]
----
ansible-playbook -i "bastion.${GUID}.${BASE_DOMAIN}", ./ansible/configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=${ANSIBLE_USER_KEY_FILE}" \
    -e"ansible_user=${ANSIBLE_USER}" \ 
    -e"ocp_workload=ocp-workload-ocs-operator" \ 
    -e"silent=False" \
    -e"ACTION=create" \
    -e @./secret.yaml \ <1>
    -e @./workload_vars.yaml <2>
----
<1> This is the same file you used while deploying OCP cluster using agnosticd. Your AWS credentials go in this file

|===
| Variable | Required? | Default Value | Description

| ocs_operator_source
| No
| redhat-operators-snapshot
| Name of the operator source to use

| ocs_operator_source_namespace
| No
| openshift-storage
| Namespace of the operator source to use

| ocs_channel
| No
| stable-4.2
| OCS Operator OLM release channel

| ocs_cluster_monitoring_enabled
| No
| true
| Enable / disable cluster monitoring on OCS namespace

|===

== Delete the workload
----
ansible-playbook -i "bastion.${GUID}.${BASE_DOMAIN}", ./ansible/configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=${ANSIBLE_USER_KEY_FILE}" \
    -e"ansible_user=${ANSIBLE_USER}" \ 
    -e"ocp_workload=ocp-workload-ocs-operator" \ 
    -e"silent=False" \
    -e"ACTION=remove" \
    -e @./secret.yaml \ <1>
    -e @./workload_vars.yaml <2>
----
<1> This is the same file you used while deploying OCP cluster using agnosticd. Your AWS credentials go in this file
