:config: satellite-vm
:author: GPTE Team
:tag1: install_satellite
:tag2: configure_satellite



Config: {config}
===============

With {config}, we can deploy bastion and Satellite on OpenStack and AWS cloud providers.


Requirements
------------

Following are the requirements:

. Yum repositories are required for bastion and satellite host.
. Aws credentials are required.


Config Variables
----------------

* Cloud specfic settings related variables.

|===
|*Variable* | *State* |*Description*
| env_type: satellite-vm |Required | Name of the config
| output_dir: /tmp/workdir |Required | Writable working scratch directory
| email: satellite_vm@example.com |Required |  User info for notifications
| guid: defaultguid | Reqired |Unique identifier
| cloud_provider: ec2 |Required        | Which AgnosticD Cloud Provider to use
|*Common* | |
| bastion_repo_method: "String" | Optional(*file*) | Method to setup bastion repositories
| satellite_host_repo_method: "String" | Optional(*satellite*) | Method to setup satellite host repositories
| satellite_host_repo_registration: {org, activationkey, url} | Required for satellite | Registration informations for satellite method
| rhel7_repos: [List] | Optional | List of rhel7 repositories to be enabled
| satellite_repos: [List] | Required | List of satellite repositories to be enabled on satellite
|*AWS* | |
|aws_regions: "String" |Required | aws region
|===


* Satellite specfic settings related variables.

|===
|*Variable* | *State* |*Description*
|install_satellite: Boolean   |Required | To enable installation roles
|configure_satellite: Boolean |Required | To enable configuration roles
|satellite_version: "Digit" |Required |satellite version
|org: "String" |Required |Organization name
|org_label: "String" |Required | Organization label in string without space
|org_description: "String" |Required | Organization description
|satellite_hosts: [List] | Optional | List of hosts to create while deploying infrastructure
|satellite_org_set_default: Bool |Optional(*true*) |Wheter to create an org as default org, or additional one
|satellite_enable_rex_on_satellite_host: Bool |Optional(*false*) |Wheter we should enable running remote execution jobs agains main satellite host
|satellite_roles: [list] |Optional | List of roles to create - see `satellite-manage-userroles`
|satellite_users: [list] |Optional | List of users to create - see `satellite-manage-userroles`
|satellite_compute_profiles: [list] |Optional | List of compute profiles to create - see `satellite-manage-compute-profile`
|satellite_hostgroups: [list] |Optional | List of hostgroups to create - see `satellite-manage-hostgroup`
|satellite_settings: [list] |Optional | List of hostgroups to create - see `satellite-manage-hostgroup`
|lifecycle_environment_path: [list] |Required | Contains nested list of environment path
|satellite_content: [list] |Required | Main List variable
| satellite_manifest: {Dictionary} |Required | Where satellite manifest is stored
|satellite_libvirt_provisioning: "Bool" |Optional(*false*) | Whether configure libvirt provisioning
|satellite_libvirt_network: {Dictionary}
!===
!name: "String"
!domain: "String"
!network: "String"
!gateway: "String"
!netmask: "String"
!range_from: "String"
!range_to: "String"
!===
|Optional
|Libvrit default network setting
!===
!Name for the subnet in satellite
!What domain should the subnet belong to
!Network address
!Gateway address - this is the hosting system address in this nat network
!Network mask - full format
!First IP to be included in the subnet used for provisioning
!Last IP to be included in the subnet used for provisioning
!===
|===

[NOTE]
For more about variables read README.adoc of the roles.

* Example variables files

. Sample of sample_vars.yml
[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible

[user@desktop ~]$ cat ./configs/satellite-vm/sample_vars.yml

env_type: satellite-vm
output_dir: /tmp/workdir
email: satellite_vm@example.com
cloud_provider: ec2
aws_region: ap-southeast-2

install_satellite: True
configure_satellite: True
satellite_version: 6.4
org: gpte
org_label: gpte
org_description: "Global Partner Training and Enablement"

satellite_roles:
  - name: Template Manager
    description: Role to allow template management
    filters:
      - permissions:
          - generate_report_templates
          - edit_report_templates
          - create_report_templates
          - view_report_templates
satellite_users:
  - name: event-admin
    description: 'User with template management permissions'
    firstname: Summit
    lastname: Admin
    mail: 'admin@summit.example.com'
    admin: yes
    password: event2020

satellite_libvirt_provisioning: yes
satellite_libvirt_network:
  domain: example.org
  network: '192.168.122.0'
  gateway: '192.168.122.1'
  netmask: '255.255.255.0'
  range_from: '192.168.122.2'
  range_to: '192.168.122.254'

lifecycle_environment_path:
    - name: "Dev"
      label: "dev"
      description: "Development Environment"
      prior_env: "Library"
    - name: "QA"
      label: "qa"
      description: "Quality Environment"
      prior_env: "Dev"
    - name: "Prod"
      label: "prod"
      description: "Production Enviornment"
      prior_env: "QA"

satellite_content:
  - name:             "Capsule Server"
    activation_key:   "capsule_key"
    subscriptions:
      - "Employee SKU"
    life_cycle:       "Library"
    content_view:     "Capsule Content"
    content_view_update: False
    repos:
      - name: 'Red Hat Enterprise Linux 7 Server (RPMs)'
        product: 'Red Hat Enterprise Linux Server'
        basearch: 'x86_64'
        releasever:  '7Server'

      - name: 'Red Hat Satellite Capsule 6.4 (for RHEL 7 Server) (RPMs)'
        product: 'Red Hat Satellite Capsule'
        basearch: 'x86_64'
  - name:             "Three Tier App"
    activation_key:   "three_tier_app_key"
    content_view:     "Three Tier App Content"
    life_cycle:       "Library"
    subscriptions:
      - "Employee SKU"
    repos:
      - name: 'Red Hat Enterprise Linux 7 Server (RPMs)'
        product: 'Red Hat Enterprise Linux Server'
        basearch: 'x86_64'
        releasever:  '7Server'
----
for reference look at link:sample_vars.yml[]

. Sample of AWS secrets.yml
[source=text]
----
[user@desktop ~]$ cat ~/secrets.yml
aws_access_key_id: xxxxxxxxxxxxxxxx
aws_secret_access_key: xxxxxxxxxxxxxxxxxx
rhel7_repo_path: http://localrepopath/to/rhel7
satellite_repo_path: http://localrepopath/to/repo
openstack_pem: ldZYgpVcjl0YmZNVytSb2VGenVrTG80SzlEU2xtUTROMHUzR1BZdzFoTEg3R2hXM
====Omitted=====
25ic0NTTnVDblp4bVE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

openstack_pub: XZXYgpVcjl0YmZNVytSb2VGenVrTG80SzlEU2xtUTROMHUzR1BZdzFoTEg3R2hXM
====Omitted=====
53ic0NTTnVDblp4bVE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
----

. Sample of OpenStack secrets.yml
[source=text]
----
[user@desktop ~]$ cat ~/secrets.yml
# Authenication for OpenStack in order to create the things
# RED
osp_auth_username: xxxxxx-xxxx-user
osp_auth_password: xxxxxxxxxx
osp_project_name: xxxxxx-xxxx-project
osp_project_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


osp_auth_url: http://169.47.188.15:5000/v3
osp_auth_project_domain: default
osp_auth_user_domain: default

osp_cluster_dns_server: ddns01.opentlc.com
osp_cluster_dns_zone: <cluster>.osp.opentlc.com
ddns_key_name: xxxxxxxxxx
ddns_key_secret: xxxxxxxxxx


rhel7_repo_path: "http://d3s3zqyaz8cp2d.cloudfront.net/repos/ocp/common"

# This path won't be used - here to ilustrate option for file repo method
satellite_repo_path: "http://d3s3zqyaz8cp2d.cloudfront.net/repos/satellite"
satellite_host_repo_method: satellite
satellite_host_repo_registration:
  org: Summit-2020
  activationkey: Summit-2020
  url: labsat.opentlc.com

satellite_repos:
  - Summit-2020_Summit-Contents_Satellite_Maintenance_Next_RHEL7
  - Summit-2020_Summit-Contents_Satellite_6_7_RHEL7
  - Summit-2020_Summit-Contents_Satellite_Tools_6_7_RHEL7_x86_64

osp_project_create: false
----


Roles
-----

* List of satellite roles


|===
|*Role*| *Link* | *Description*
|satellite-public-hostname | link:../../roles/satellite-public-hostname[satellite-public-hostname] | Set public hostname
|satellite-installation |link:../../roles/satellite-installation[satellite-installation] | Install and configure satellite
|satellite-hammer-cli |link:../../roles/satellite-hammer-cli[satellite-hammer-cli] | Setup hammer cli
|satellite-libvirt |link:../../roles/satellite-libvirt[satellite-libvirt] | Install libvirt (kvm) on capsule for provisioning
|satellite-provisioning |link:../../roles/satellite-provisioning[satellite-provisioning] | Register provisioning resources (compute resource, subnet, domain) to satellite
|satellite-manage-organization |link:../../roles/satellite-manage-organization[satellite-manage-organization] | Create satellite organization
|satellite-manage-userroles |link:../../roles/satellite-manage-userroles[satellite-manage-userroles] | Create satellite users and user roles
|satellite-manage-manifest |link:../../roles/ssatellite-manage-manifest[satellite-manage-manifest] | uploads manifest
|satellite-manage-repositories |link:../../roles/satellite-manage-repository[satellite-manage-repositories] | Manage subscriptions/repositories and synchronize
|satellite-manage-lifecycle |link:../../roles/satellite-manage-lifecycle[satellite-manage-lifecycle]  | Create lifecycle environment
|satellite-manage-content-view |link:../../roles/satellite-manage-content-view[satellite-manage-content-view]  | Create content-view
|satellite-manage-activationkey |link:../../roles/satellite-manage-activationkey[satellite-manage-activationkey]  | Create activation key
|satellite-manage-compute-profile |link:../../roles/satellite-manage-compute-profile[satellite-manage-compute-profile]  | Create compute profiles
|satellite-manage-hostgroup |link:../../roles/satellite-manage-hostgroup[satellite-manage-hostgroup]  | Create hostgroups
|satellite-manage-capsule-certificate | link:../../roles/satellite-manage-capsule-certificate[satellite-manage-capsule-certificate]  | Create certificates for capsule installation on satellite
|===

* List of capsule roles

|===
|*Role*| *Link* | *Description*
|satellite-capsule-installation |link:../../roles/satellite-capsule-installation[satellite-capsule-installation]  | Install capsule packages
|satellite-capsule-configuration | link:../../roles/satellite-capsule-configuration[satellite-capsule-configuration] | Setup capsule server
|===

* List of satellite hosts roles

|===
|*Role*| *Link* | *Description*
|satellite-register-host |link:../../roles/satellite-register-host[satellite-register-host]  | Register satellite host instances into Satellite
|===

Tags
---

|===
|{tag1} |Consistent tag for all satellite installation roles
|{tag2} |Consistent tag for all satellite configuration roles
|===

* Example tags

----
## Tagged jobs
ansible-playbook playbook.yml --tags configure_satellite

## Skip tagged jobs
ansible-playbook playbook.yml --skip-tags install_satellite
----

Example to run config
---------------------

How to use config (for instance, with variables passed in playbook).

[source=text]
----
[user@desktop ~]$ cat ~/satellite_vars.yml
---
guid: 'defaultguid'
satellite_admin: admin
satellite_admin_password: 'changeme'
satellite_manifest:
  type: 'file'
  path: '/path/to/manifest_satellite_6.4.zip'

[user@desktop ~]$ cd agnosticd/ansible

[user@desktop ~]$ ansible-playbook  main.yml \
  -e @./configs/satellite-vm/sample_vars.yml \
  -e @~/secrets.yml \
  -e @~/satellite_vars.yml
----

Example to stop environment
---------------------------

[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible

[user@desktop ~]$ ansible-playbook  ./configs/satellite-vm/stop.yml \
  -e @./configs/satellite-vm/sample_vars.yml \
  -e @~/secrets.yml \
  -e guid=defaultguid
----

Example to start environment
---------------------------

[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible

[user@desktop ~]$ ansible-playbook  ./configs/satellite-vm/start.yml \
  -e @./configs/satellite-vm/sample_vars.yml \
  -e @~/secrets.yml \
  -e guid=defaultguid
----

Example to destroy environment
------------------------------

[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible

[user@desktop ~]$ ansible-playbook  ./configs/satellite-vm/destroy.yml \
  -e @./configs/satellite-vm/sample_vars.yml \
  -e @~/secrets.yml \
  -e guid=defaultguid
----




Author Information
------------------

{author}
