= ocp4_workload_plus - Deploy Advanced Cluster Management + Advanced Cluster Security (Stackrox) + Quay to an OpenShift Cluster

== Role overview

* This role installs Advanced Cluster Management + Advanced Cluster Security (Stackrox) + Quay into an OpenShift Cluster. It consists of the following tasks files:
** Tasks: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an
 environment for the workload deployment.
*** Debug task will print out: `pre_workload Tasks completed successfully.`

** Tasks: link:./tasks/workload.yml[workload.yml] - Used to deploy OpenShift Plus
*** Debug task will print out: `workload Tasks completed successfully.`

** Tasks: link:./tasks/workload_argocd.yml[workload_argocd.yml] - Used to deploy OpenShift Gitops (ArgoCD), which is used to deploy the other tools.

** Tasks: link:./tasks/workload_acm.yml[workload_acm.yml] - Used to deploy Advanced Cluster Management

** Tasks: link:./tasks/workload_acs.yml[workload_acs.yml] - Used to deploy Advanced Cluster Security

** Tasks: link:./tasks/workload_quay.yml[workload_quay.yml] - Used to deploy Quay

** Tasks: link:./tasks/post_workload.yml[post_workload.yml] - Used to
 configure the workload after deployment
*** Debug task will print out: `post_workload Tasks completed successfully.`

** Tasks: link:./tasks/remove_workload.yml[remove_workload.yml] - Used to
 delete the workload
*** This role removes OpenShift Pipelines
*** Debug task will print out: `remove_workload Tasks completed successfully.`

== Review the defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you need to define to control the deployment of your workload.
* The variable *ocp_username* is mandatory to assign the workload to the correct OpenShift user.
* A variable *silent=True* can be passed to suppress debug messages.


=== Deploy a Workload with the `ocp-workload` config [Mostly for testing]

Create a file `ocp_plus_vars.yaml` with your variables:
----
mkdir ~/configs
export GUID=changeme
export ADMIN_USER='opentlc-mgr'
export ADMIN_PASSWD=''
export USER_BASE='user'
export USER_PASSWORD='openshift'

cat <<EOF > ~/configs/ocp_plus_vars.yml
---
# --- OpenShift 4 Plus Demo
cloud_provider: ec2
env_type: ocp4-cluster
update_packages: false
install_student_user: true
sandbox_student_user: true
student_name: lab-user
install_ipa_client: false
install_ftl: false
student_workloads: []
guid: '$GUID'

software_to_deploy: openshift4
ocp4_installer_version: "4.9.6"

infra_workloads:
- ocp4_workload_authentication
- ocp4_workload_le_certificates
- studentvm_ocp4
- ocp4_workload_plus

# Authentication
ocp4_workload_authentication_idm_type: htpasswd
ocp4_workload_authentication_htpasswd_user_base: '$USER_BASE'
ocp4_workload_authentication_htpasswd_user_password: '$USER_PASSWORD'
ocp4_workload_authentication_htpasswd_user_count: 5
ocp4_workload_authentication_admin_user: '$ADMIN_USER'
ocp4_workload_authentication_htpasswd_admin_password: '$ADMIN_PASSWD'
ocp4_workload_authentication_remove_kubeadmin: true

EOF
----

Create a file `secrets.yaml` with the sensitive variables (NEVER commit it to git or expose them):
----
export AWS_ACCESS_KEY_ID=''
export AWS_SECRET_ACCESS_KEY=''
export AWS_REGION="" # example: 'us-east-2'
export AWS_HOSTED_ZONE_ID=""
export SUBDOMAIN="" # example: '.sandbox1420.opentlc.com'
export PULL_SECRET=''
export RHN_USER=""
export RHN_PASSWORD=''
export RHN_POOL_ID='' # Pool id to register bastion host
export SSH_KEY_NAME='' # ssh private key file name

cat <<EOF > ~/configs/secrets.yml
---
aws_access_key_id: '$AWS_ACCESS_KEY_ID'
aws_secret_access_key: '$AWS_SECRET_ACCESS_KEY'
aws_region: '$AWS_REGION'
HostedZoneId: '$AWS_HOSTED_ZONE_ID'
key_name: '$SSH_KEY_NAME'
subdomain_base_suffix: $SUBDOMAIN
ocp4_pull_secret: '$PULL_SECRET'

repo_method: rhn
rhel_subscription_user: $RHN_USER
rhel_subscription_pass: '$RHN_PASSWORD'
rhsm_pool_ids: '$RHN_POOL_ID'
EOF
----

From the Agnosticd/ansible directory run the playbook:

----
TARGET_HOST="<BASTION_IP>"                   # BASTION HOST IP
OCP_USERNAME="opentlc-mgr"                  # OCP CLUSTER ADMIN
WORKLOAD="ocp4_workload_plus"              # ROLE NAME
GUID=changeme                                     # GUID
SSH_PRIVATE_KEY='~/.ssh/id_rsa'              # SSH PRIVATE KEY TO CONNECT TO BASTION HOST

ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=${SSH_PRIVATE_KEY}" \
    -e"ansible_user=ec2-user" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"ACTION=create" \
    -e @~/configs/ocp_plus_vars.yml \
    -e @~/configs/secrets.yml
----

=== To Delete an environment

From the Agnosticd/ansible directory run the playbook:

----
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=${SSH_PRIVATE_KEY}" \
    -e"ansible_user=ec2-user" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"ACTION=remove" \
    -e @~/configs/ocp_plus_vars.yml \
    -e @~/configs/secrets.yml
----
