#!/bin/bash

# This has to be run after installation.
# source /etc/profile.d/bash_completion.sh


echo "Adding wheel" > /root/post-run.log
usermod -aG wheel rhel

echo "setting password" >> /root/post-run.log
echo redhat | passwd --stdin rhel

echo "DONE" >> /root/post-run.log

echo "${SSHKEY}" > r4ekey

chmod 600 r4ekey

mkdir /images
tee -a /images/dl_edge_iso.sh << EOF
#!/bin/bash

:<<'__COMMENT__'

To use:
export PROXY_USER=PROXYUSERNAMEHERE
export PROXY_PASS=PROXYPASSWORDHERE
export PROXY_URL=PROXYSERVERURLHERE

dl_edge_iso.sh <iso_url>

__COMMENT__

URL=\$1
# grab the redirect url from the API
#INIT_REDIRECT_URL=\$(curl -s --basic --proxy \${PROXY_URL} -u "\${PROXY_USER}:\${PROXY_PASS}" --proxy-user "\${PROXY_USER}:\${PROXY_PASS}" "\$URL")
#INIT_REDIRECT_URL=\$(curl -s --basic "\$URL")
INIT_REDIRECT_URL=\$(curl -s --basic -u "\${EDGEMGMT_USER}:\${EDGEMGMT_PASS}" "\$URL")
# clean up the html encoding
REDIRECT_URL=\$(echo \$INIT_REDIRECT_URL | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%&:;-]*" | sed 's/amp;//g')
# grab the basic URL
BASE_URL=\$(echo \$REDIRECT_URL | grep -o -P '(?=https).*(?=\?)')
# grab the filename of the ISO
FILENAME=\$(echo "\${BASE_URL##*/}")

echo "Downloading..."
echo \$REDIRECT_URL
echo "... to ..."
#echo \$FILENAME

# download the ISO
wget -q --show-progress -O \$FILENAME "\$REDIRECT_URL"
EOF

chmod 600 /images/dl_edge_iso.sh
chmod +x /images/dl_edge_iso.sh

# virsh destroy vm1
# virsh undefine vm1
# rm -rf /images/vm1.qcow2