---
ocp4_workload_open_ssh_from_bastion_enable: false

ocp4_workload_open_ssh_from_bastion_silent: true

ocp4_workload_open_ssh_from_bastion_region: ''
ocp4_workload_open_ssh_from_bastion_access_key_id: ''
ocp4_workload_open_ssh_from_bastion_secret_access_key: ''

ocp4_workload_open_ssh_from_bastion_cluster_cidr: "10.0.0.0/16"
ocp4_workload_open_ssh_from_bastion_bastion_cidr: "192.168.0.0/16"
