= ocp4-workload-quay-operator - Deploy Red Hat Quay Registry via the Quay Operator

== Role overview

* This role installs the Red Hat Quay Operator and via the Operator Red Hat Quay Registry into an OpenShift Cluster.

* The Operator source is at https://github.com/redhat-cop/quay-operator.

* The role consists of the following tasks files:
** Tasks: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an
 environment for the workload deployment.
*** Debug task will print out: `pre_workload Tasks completed successfully.`

** Tasks: link:./tasks/workload.yml[workload.yml] - Used to deploy Red Hat Quay Registry Operator
*** This role creates a namespace (project), operator and a Quay instance
*** Debug task will print out: `workload Tasks completed successfully.`

** Tasks: link:./tasks/post_workload.yml[post_workload.yml] - Used to
 configure the workload after deployment
*** This role doesn't do anything here
*** Debug task will print out: `post_workload Tasks completed successfully.`

** Tasks: link:./tasks/remove_workload.yml[remove_workload.yml] - Used to
 delete the workload
*** This role removes the Red Hat Quay Registry project (and therefore Red Hat Quay Registry)
*** Debug task will print out: `remove_workload Tasks completed successfully.`

== Review the defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you need to define to control the deployment of your workload.
* The variable *ocp_username* is mandatory to assign the workload to the correct OpenShift user.
* A variable *silent=True* can be passed to suppress debug messages.
* Other variables:
** *_quay_project*: The name of the project to create and install Red Hat Quay to. Default: `quay`
** *_quay_project_display*: The display name of the project. Default: `Red Hat Quay Registry`
** *_quay_name*: The name of the Quay CR. Default: `quay`
** *_quay_operator_image*: The name of the quay operator image. Default: `quay.io/redhat-cop/quay-operator`
** *_quay_operator_image_tag*: The image tag to use for the Quay Operator.
** *_quay_superuser_username*: The super user username for quay. Default: `quayadmin`
** *_quay_superuser_password*: The password for the super user. Default: 'quaypassword'
** *_quay_superuser_email*: The email for the super user. Default: 'rhpds-admins@redhat.com'
** *_quay_config_app_password*: Password used for Quay in Config mode. Default: `quayconfig`
** *_quay_volume_size*: Volume size for Quay. Default: 20Gi
** *_quay_database_volume_size*: Volume size for the Quay database. Default: 20Gi
** *_quay_dockerconfigjson*: The quay.io pull_secret, bas64 encoded! Reference https://access.redhat.com/solutions/3533201 *This has to be overwritten via Global Variable!!*

* You can modify any of these default values by adding `-e "variable_name=variable_value"` to the command line

=== Deploy a Workload with the `ocp-workload` playbook [Mostly for testing]

----
TARGET_HOST="bastion.na311.openshift.opentlc.com"
OCP_USERNAME="wkulhane-redhat.com"
WORKLOAD="ocp4-workload-quay-operator"
GUID=1001
QUAY_DOCKERCONFIGJSON="wk_quay_dockerconfigjson" # change this

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=ec2-user" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"_quay_dockerconfigjson=${QUAY_DOCKERCONFIGJSON}" \
    -e"ACTION=create"
----

=== To Delete an environment

----
TARGET_HOST="bastion.na311.openshift.opentlc.com"
OCP_USERNAME="wkulhane-redhat.com"
WORKLOAD="ocp4-workload-quay"
GUID=1002

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=ec2-user" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"guid=${GUID}" \
    -e"ACTION=remove"
----


== Other related information:

=== Deploy Workload on OpenShift Cluster from an existing playbook:

[source,yaml]
----
- name: Deploy a workload role on a master host
  hosts: all
  become: true
  gather_facts: False
  tags:
    - step007
  roles:
    - { role: "{{ocp_workload}}", when: 'ocp_workload is defined' }
----
NOTE: You might want to change `hosts: all` to fit your requirements


=== Set up your Ansible inventory file

* You can create an Ansible inventory file to define your connection method to your host (Master/Bastion with `oc` command)
* You can also use the command line to define the hosts directly if your `ssh` configuration is set to connect to the host correctly
* You can also use the command line to use localhost or if your cluster is already authenticated and configured in your `oc` configuration

.Example inventory file
[source, ini]
----
[gptehosts:vars]
ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem
ansible_user=ec2-user

[gptehosts:children]
openshift

[openshift]
bastion.cluster1.openshift.opentlc.com
bastion.cluster2.openshift.opentlc.com
bastion.cluster3.openshift.opentlc.com
bastion.cluster4.openshift.opentlc.com

[dev]
bastion.cluster1.openshift.opentlc.com
bastion.cluster2.openshift.opentlc.com

[prod]
bastion.cluster3.openshift.opentlc.com
bastion.cluster4.openshift.opentlc.com
----
