:config: multi-cloud-capsule
:author: GPTE Team
:tag1: install_capsule
:tag2: configure_capsule



Config: {config}
===============

With {config}, we can capsule server on OpenStack and AWS cloud providers.


Requirements
------------

Following are the requirements:

. Aws OR OpenStack credentials .
. Satellite must be install and setup.
. Satellite should have all capsule repositories in activation key. 

 

Config Variables
----------------

* Cloud specfic settings related variables.

|===
|*Variable* | *State* |*Description*
| env_type: multi-cloud-capsule |Required | Name of the config
| output_dir: /tmp/workdir |Required | Writable working scratch directory
| email: capsule-vm@example.com |Required |  User info for notifications
| guid: defaultguid | Reqired |Unique identifier
| cloud_provider: ec2 |Required        | Which AgnosticD Cloud Provider to use
|aws_regions: "String" |Required | aws region
|===


* Satellite specfic settings related variables.

|===
|*Variable* | *State* |*Description*
|install_satellite: Boolean   |Required | To enable installation roles
|configure_satellite: Boolean |Required | To enable configuration roles
|satellite_version: "Digit" |Required |satellite version
|org: "String" |Required |Organization name
|org_label: "String" |Required | Organization label in string without space
|org_description: "String" |Required | Organization description
|lifecycle_environment_path: [list] |Required | Contains nested list of environment path
|satellite_content: [list] |Required | Main List variable
|subscription_name: "String" |Required | Subscription name mainly required for manifest role
| manifest_file: "/path/to/manifest.zip" |Required | Path of download satellite manifest
|===

[NOTE] 
For more about variables read README.adoc of the roles.
    
* Example variables files

. Sample of sample_vars_ec2.yml
[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible

[user@desktop ~]$ cat ./configs/multi-cloud-capsule/sample_vars_ec2.yml

env_type: multi-cloud-capsule      
output_dir: /tmp/workdir               
email: satellite_vm@example.com 


install_satellite: True
configure_satellite: True 
satellite_version: 6.4
org: gpte
org_label: gpte



satellite_content:
  - name:             "Capsule Server"
    activation_key:   "capsule_key"
    subscriptions:
      - "Employee SKU"
    life_cycle:       "Library"
    content_view:     "Capsule Content"
    content_view_update: False
    repos:  
      - name: 'Red Hat Enterprise Linux 7 Server (RPMs)' 
        product: 'Red Hat Enterprise Linux Server' 
        basearch: 'x86_64'
        releasever:  '7Server'
        
      - name: 'Red Hat Satellite Capsule 6.4 (for RHEL 7 Server) (RPMs)'
        product: 'Red Hat Satellite Capsule' 
        basearch: 'x86_64'
  - name:             "Three Tier App"
    activation_key:   "three_tier_app_key"
    content_view:     "Three Tier App Content"
    life_cycle:       "Library"
    subscriptions:
      - "Employee SKU"
    repos: 
      - name: 'Red Hat Enterprise Linux 7 Server (RPMs)' 
        product: 'Red Hat Enterprise Linux Server' 
        basearch: 'x86_64'
        releasever:  '7Server'    
----
for reference look at link:sample_vars_ec2.yml[]  

. Sample of ec2_secrets.yml
[source=text]
----
[user@desktop ~]$ cat ~/ec2_secrets.yml
aws_access_key_id: xxxxxxxxxxxxxxxx
aws_secret_access_key: xxxxxxxxxxxxxxxxxx
own_repo_path: http://localrepopath/to/repo
openstack_pem: ldZYgpVcjl0YmZNVytSb2VGenVrTG80SzlEU2xtUTROMHUzR1BZdzFoTEg3R2hXM
====Omitted=====
25ic0NTTnVDblp4bVE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

openstack_pub: XZXYgpVcjl0YmZNVytSb2VGenVrTG80SzlEU2xtUTROMHUzR1BZdzFoTEg3R2hXM
====Omitted=====
53ic0NTTnVDblp4bVE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
----



Roles
-----

* List of satellite and capsule roles


|===
|*Role*| *Link* | *Description*
|satellite-public-hostname | link:../../roles/satellite-public-hostname[satellite-public-hostname] | Set public hostname
|satellite-capsule-installation |link:../../roles/satellite-capsule-installation[satellite-capsule-installation]  | Install capsule packages
|satellite-capsule-configuration | link:../../roles/satellite-capsule-configuration[satellite-capsule-configuration] | Setup capsule server
|===

Tags
---

|===
|{tag1} |Consistent tag for all capsule installation roles
|{tag2} |Consistent tag for all capsule configuration roles
|===

* Example tags

----
## Tagged jobs
ansible-playbook playbook.yml --tags configure_capsule

## Skip tagged jobs
ansible-playbook playbook.yml --skip-tags install_capsule
----

Example to run config 
---------------------

How to use config (for instance, with variables passed in playbook).

[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible

[user@desktop ~]$ ansible-playbook  main.yml \
  -e @./configs/multi-cloud-capsule/sample_vars_ec2.yml \
  -e @~/ec2_secrets.yml \
  -e guid=defaultguid  \
  -e satellite_admin=admin \
  -e 'satellite_admin_password=changeme' \
  -e manifest_file=/path/to/manifest_satellite_6.4.zip
----

Example to stop environment 
---------------------------

[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible

[user@desktop ~]$ ansible-playbook  ./configs/multi-cloud-capsule/stop.yml \
  -e @./configs/multi-cloud-capsule/sample_vars_ec2.yml \
  -e @~/ec2_secrets.yml \
  -e guid=defaultguid  
----

Example to start environment 
---------------------------

[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible

[user@desktop ~]$ ansible-playbook  ./configs/multi-cloud-capsule/start.yml \
  -e @./configs/multi-cloud-capsule/sample_vars_ec2.yml \
  -e @~/ec2_secrets.yml \
  -e guid=defaultguid  
----

Example to destroy environment 
------------------------------

[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible

[user@desktop ~]$ ansible-playbook  ./configs/multi-cloud-capsule/destroy.yml \
  -e @./configs/multi-cloud-capsule/sample_vars_ec2.yml \
  -e @~/ec2_secrets.yml \
  -e guid=defaultguid 
----




Author Information
------------------

{author}
