= ocp4-workload-workshop-admin-storage - Deploy app for OpenShift and Container Storage for Administrators
 workshops

:link:https://github.com/openshift/openshift-cns-testdrive/tree/ocp4-dev[Link to Workshop Content]

== Role overview

* This role deploys the labguide app. It consists of the following tasks files:
** Tasks: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an
 environment for the workload deployment.
*** Runs link:./tasks/clean-admin.yml[clean-admin.yml]
*** Debug task will print out: `pre_workload Tasks completed successfully.`

** Tasks: link:./tasks/clean-admin.yml[clean-admin.yml] - Used to
 clear out resources related to the admin application admin to avoid conflicts
 *** Runs in link:./tasks/pre_workload.yml[pre_workload.yml] and during link:./tasks/remove_workload.yml[remove_workload.yml]


** Tasks: link:./tasks/workload.yml[workload.yml] - Used to deploy the app
*** Debug task will print out: `workload Tasks completed successfully.`

** Tasks: link:./tasks/post_workload.yml[post_workload.yml] - Used to
 configure the workload after deployment
*** This role doesn't do anything here
*** Debug task will print out: `post_workload Tasks completed successfully.`

** Tasks: link:./tasks/remove_workload.yml[remove_workload.yml] - Used to
 delete the workload
*** Runs link:./tasks/clean-admin.yml[clean-admin.yml]
*** This role removes the logging deployment and project but not the operator configs
*** Debug task will print out: `remove_workload Tasks completed successfully.`

== Review the defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you need to define to control the deployment of your workload.
* The variable *ocp_username* is mandatory to assign the workload to the correct OpenShift user.
* A variable *silent=True* can be passed to suppress debug messages.
* You can modify any of these default values by adding `-e "variable_name=variable_value"` to the command line

=== Deploy a Workload with the `ocp-workload` playbook [Mostly for testing]

----
TARGET_HOST=$(dig @resolver1.opendns.com A myip.opendns.com +short)
STUDENT_NAME=lab-user
STUDENT_PASSWORD=to_be_changed
GUID=$(oc whoami --show-server | awk -F '[-.]' '{ print $3 }')
SUBDOMAIN_BASE=guid.xxxx.xxxx.com

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=/home/$(whoami)/.ssh/id_rsa" \
    -e"student_name=${STUDENT_NAME}" \
    -e"ansible_user=$(whoami)" \
    -e"guid=${GUID}" \
    -e"subdomain_base=${SUBDOMAIN_BASE}" \
    -e"ocp_workload=ocp4-workload-workshop-admin-storage" \
    -e"silent=False" \
    -e"student_password=${STUDENT_PASSWORD}" \
    -e"ACTION=create"
----

Wait until workshop is ready

----
oc rollout status dc/admin -n labguide
----

To view workshop, go to route. Use ocp_username and its password to go through the http digest authentication

----
oc get route admin -n labguide
----

=== To Delete an environment

----
# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=/home/$(whoami)/.ssh/id_rsa" \
    -e"ansible_user=$(whoami)" \
    -e"guid=${GUID}" \
    -e"subdomain_base=${SUBDOMAIN_BASE}" \
    -e"ocp_workload=ocp4-workload-workshop-admin-storage" \
    -e"silent=False" \
    -e"student_password=${STUDENT_PASSWORD}" \
    -e"ACTION=remove"
----


== Other related information:

=== Deploy Workload on OpenShift Cluster from an existing playbook:

[source,yaml]
----
- name: Deploy a workload role on a master host
  hosts: all
  become: true
  gather_facts: False
  tags:
    - step007
  roles:
    - { role: "{{ocp_workload}}", when: 'ocp_workload is defined' }
----
NOTE: You might want to change `hosts: all` to fit your requirements


=== Set up your Ansible inventory file

* You can create an Ansible inventory file to define your connection method to your host (Master/Bastion with `oc` command)
* You can also use the command line to define the hosts directly if your `ssh` configuration is set to connect to the host correctly
* You can also use the command line to use localhost or if your cluster is already authenticated and configured in your `oc` configuration

.Example inventory file
[source, ini]
----
[gptehosts:vars]
ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem
ansible_user=ec2-user

[gptehosts:children]
openshift

[openshift]
bastion.cluster1.openshift.opentlc.com
bastion.cluster2.openshift.opentlc.com
bastion.cluster3.openshift.opentlc.com
bastion.cluster4.openshift.opentlc.com

[dev]
bastion.cluster1.openshift.opentlc.com
bastion.cluster2.openshift.opentlc.com

[prod]
bastion.cluster3.openshift.opentlc.com
bastion.cluster4.openshift.opentlc.com
----
