:role: satellite-manage-subscription
:author: GPTE Team
:tag1: configure_satellite
:tag2: configure_satellite_subscription
:main_file: tasks/main.yml
:version_file: tasks/version_6.4.yml
:script_file: files/subscription_script_version_6.4.sh

Role: {role}
============

This role enables subscribed repository.

Requirements
------------

Following are the requirements:

. Satellite must be install and setup.
. Hammer cli config must be configured/updated with privileged user and password to run the satellite cli.
. Subscription should be exist in satellite server.
 
Role Variables
--------------

* Following are the variable which needs to be defined 

|===
|satellite_version: "Digit" |Required |satellite version
|org: "String" |Required |Organization name
|org_label: "String" |Notrequired | Organization label in string without space
|org_description: "String" |Not-required | Organization description
|satellite_content: {Dictionary} |Required | Main dictionary variable
|repos: [list] | Required | List of repository name 
|product: "String" |Required | Product name of repository
|name: "String" |Required | Repository Name
|basearch: "String" |Required | Repository Base Arch
|releasever: "String" |Whereever Applicable | Repository Release version
|===
    
* Exammple variables

[source=text]
----
satellite_version: 6.4
org: "gpte"
org_label: "gpte"
org_description: "Global Partner Training and Enablement"
satellite_content:
  - name:             "Ansible server"
    repos:  
      - name: 'Red Hat Enterprise Linux 7 Server (RPMs)' 
        product: 'Red Hat Enterprise Linux Server' 
        basearch: 'x86_64'
        releasever:  '7Server'
       
      - name: 'Red Hat Satellite Maintenance 6 (for RHEL 7 Server) (RPMs)'
        product: 'Red Hat Enterprise Linux Server' 
        basearch: 'x86_64'
          
  - name:             "Three Tier App"
    repos: 
      - name: 'Red Hat Enterprise Linux 7 Server (RPMs)' 
        product: 'Red Hat Enterprise Linux Server' 
        basearch: 'x86_64'
        releasever:  '7Server'
----

Tags
---

|===
|{tag1} |Consistent tag for all satellite config roles
|{tag2} |This tag is specific to this role only
|===

* Example tags

----
## Tagged jobs
ansible-playbook playbook.yml --tags configure_satellite,configure_satellite_subscription

## Skip tagged jobs
ansible-playbook playbook.yml --skip-tags configure_satellite,configure_satellite_subscription
----

Example Playbook
----------------

How to use your role (for instance, with variables passed in playbook).

[source=text]
----
[user@desktop ~]$ cat sample_vars.yml
satellite_version: 6.4
org: "gpte"
org_label: "gpte"
org_description: "Global Partner Training and Enablement"
satellite_content:
  - name:             "Ansible server"
    repos:  
      - name: 'Red Hat Enterprise Linux 7 Server (RPMs)' 
        product: 'Red Hat Enterprise Linux Server' 
        basearch: 'x86_64'
        releasever:  '7Server'
       
      - name: 'Red Hat Satellite Maintenance 6 (for RHEL 7 Server) (RPMs)'
        product: 'Red Hat Enterprise Linux Server' 
        basearch: 'x86_64'
          
  - name:             "Three Tier App"
    repos: 
      - name: 'Red Hat Enterprise Linux 7 Server (RPMs)' 
        product: 'Red Hat Enterprise Linux Server' 
        basearch: 'x86_64'
        releasever:  '7Server'

[user@desktop ~]$ cat playbook.yml
- hosts: satellite.example.com
  vars_files:
    - sample_vars.yml
  roles:
    - satellite-manage-subscription

[user@desktop ~]$ ansible-playbook playbook.yml
----

Tips to update Role
------------------

To extend role works for other version, create new file named  version_{{satellite_version}}.yml and import newly created file in main.yml

for reference look at link:{main_file}[main.yml] , link:{version_file}[version_6.4.yml] and script 

link:{script_file}[subscription_script_version_6.4.sh]


Author Information
------------------

{author}
