= ocp-workload-aws-jumpbox - Set up AWS Jumpbox Taskss on Bastion

== Role overview

* This role installs playbooks and shell scripts to deploy a Jumpbox for AWS based deployments. A Jumpbox is necessary to SSH into any OCP 4 Cluster Nodes (including masters).

Once this role has been executed there is a directory `/opt/jumpbox` with the necessary files to deploy a jumpbox. SSH into the bastion, change to the `/opt/jumpbox` directory and run `./setup_jumpbox.sh`. This script will execute the playbook to deploy a Jumpbox into the region specified.

Currently only `eu-central-1`, `us-east-1` and `us-east-2` are supported. This is because only for these three regions the AMI for the RHEL 8 image is specified.

. The role consists of the following tasks files:
** Tasks: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an
 environment for the workload deployment
*** Debug task will print out: `pre_workload Tasks completed successfully.`

** Tasks: link:./tasks/workload.yml[workload.yml] - Install the Jumpbox Playbooks onto the Bastion
*** Debug task will print out: `workload Tasks completed successfully.`

** Tasks: link:./tasks/post_workload.yml[post_workload.yml] - Used to
 configure the workload after deployment
*** This role doesn't do anything here
*** Debug task will print out: `post_workload Tasks completed successfully.`

** Tasks: link:./tasks/remove_workload.yml[remove_workload.yml] - Used to
 delete the workload
*** This role doesn't do anything here
*** Debug task will print out: `remove_workload Tasks completed successfully.`

== Review the defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you need to define to control the deployment of your workload.
* The variable *ocp_username* is mandatory to assign the workload to the correct OpenShift user.
* A variable *silent=True* can be passed to suppress debug messages.
* You can modify any of these default values by adding `-e "variable_name=variable_value"` to the command line

=== Deploy a Workload with the `ocp-workload` playbook [Mostly for testing]

----
TARGET_HOST="bastion.GUID.example.opentlc.com"
OCP_USERNAME="wkulhane-redhat.com"
WORKLOAD="ocp-workload-aws-jumpbox"
GUID=1001
AWS_REGION=us-east-1 # or us-east-2 or eu-central-1
CLUSTER_NAME=xxxxx

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=ec2-user" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"aws_region=${AWS_REGION}" \
    -e"cluster_name=${CLUSTER_NAME}" \
    -e"ACTION=create"
----
