= ocp4-workload-rhte-analytics_data_ocp_workshop - Workshop workload for the Red Hat Tech Exchange Analytics and Data Engineering on OpenShift workshop

This workshop workoad will create user(s) project to deploy link:http://opendatahub.io[Open Data Hub] v0.4.0.

The individual workload task includes

* Creation of the project and project RBAC for the user
* Add the Open Data Hub to the project's Catalog of `Installed Operators`
* Deploy the Open Data Hub and Strimzi Operator
* OPTIONAL: Create an Open Data Hub deployment for the user

== Role overview

* This is a workshop role to setup the Open Data Hub project for a specific user. This role requires that the infrastructure has all Open Data Hub required and dependent CRDS loaded and Rook Ceph Object storage has been installed. This role must be run after the link:../ocp4-workload-rhte-analytics_data_ocp_infra[ocp4-workload-rhte-analytics_data_ocp_infra] role. It consists of the following tasks files:
** Tasks: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an environment for the workload deployment
*** This role doesn't do anything here
*** Debug task will print out: `pre_workload Tasks completed successfully.`

** Tasks: link:./tasks/workload.yml[workload.yml] - Creates the each user's project space, adds the ODH ClusterServiceVersion to the project, deploys the opendatahub-operator and *OPTIONAL* deploys Open Data Hub
*** This role only prints the current username for which this role is provisioning.
*** Debug task will print out: `workload Tasks completed successfully.`

** Tasks: link:./tasks/post_workload.yml[post_workload.yml] - Used to configure the workload after deployment
*** This role doesn't do anything here
*** Debug task will print out: `post_workload Tasks completed successfully.`

** Tasks: link:./tasks/remove_workload.yml[remove_workload.yml] - Deletes the project created for each user
*** Debug task will print out: `remove_workload Tasks completed successfully.`

== Review the defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you need to define to control the deployment of your workload.
* The variable *ocp_username* is mandatory to assign the workload to the correct OpenShift user.
* A variable *silent=True* can be passed to suppress debug messages.
* You can modify any of these default values by adding `-e "variable_name=variable_value"` to the command line

=== Deploy a Workload with the `ocp-workload` playbook [Mostly for testing]

----
TARGET_HOST="bastion.na39.openshift.opentlc.com"
ANSIBLE_USER=<User with SSH access to bastion host>
OCP_USERNAME=opentlc-mgr
WORKLOAD="ocp4-workload-rhte-analytics_data_ocp_workshop"
GUID=<GUID assigned by RHPDS>
# ROOK CEPH RGW info would be provided by role ocp4-workload-rhte-analytics_data_ocp_infra
ROOK_CEPH_RGW_SERVICE_IP=XX.YY.ZZ.WW
ROOK_CEPH_RGW_SERVICE_PORT=8000
WORKSHOP_USER_COUNT=50

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=${ANSIBLE_USER}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"rgw_service_ip=${ROOK_CEPH_RGW_SERVICE_IP}"
    -e"rgw_service_port=${ROOK_CEPH_RGW_SERVICE_PORT}"
    -e"user_count=${WORKSHOP_USER_COUNT}" \
    -e"ACTION=create"
----

=== To Delete an environment

----
TARGET_HOST="bastion.na39.openshift.opentlc.com"
ANSIBLE_USER=<User with SSH access to bastion host>
OCP_USERNAME=opentlc-mgr
WORKLOAD="ocp4-workload-rhte-analytics_data_ocp_workshop"
GUID=<GUID assigned by RHPDS>
WORKSHOP_USER_COUNT=50

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=${ANSIBLE_USER}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"guid=${GUID}" \
    -e"user_count=${WORKSHOP_USER_COUNT}" \
    -e"ACTION=remove"
----


== Other related information:

=== Deploy Workload on OpenShift Cluster from an existing playbook:

[source,yaml]
----
- name: Deploy a workload role on a master host
  hosts: all
  become: true
  gather_facts: False
  tags:
    - step007
  roles:
    - { role: "ocp4-workload-rhte-analytics_data_ocp_infra", when: 'ocp_workload is defined' }
    - { role: "ocp4-workload-rhte-analytics_data_ocp_workshop", when: 'ocp_workload is defined' }
----
NOTE: You might want to change `hosts: all` to fit your requirements


=== Set up your Ansible inventory file

* You can create an Ansible inventory file to define your connection method to your host (Master/Bastion with `oc` command)
* You can also use the command line to define the hosts directly if your `ssh` configuration is set to connect to the host correctly
* You can also use the command line to use localhost or if your cluster is already authenticated and configured in your `oc` configuration

.Example inventory file
[source, ini]
----
[gptehosts:vars]
ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem
ansible_user=ec2-user

[gptehosts:children]
openshift

[openshift]
bastion.cluster1.openshift.opentlc.com
bastion.cluster2.openshift.opentlc.com
bastion.cluster3.openshift.opentlc.com
bastion.cluster4.openshift.opentlc.com

[dev]
bastion.cluster1.openshift.opentlc.com
bastion.cluster2.openshift.opentlc.com

[prod]
bastion.cluster3.openshift.opentlc.com
bastion.cluster4.openshift.opentlc.com
----
