= ocp4_workload_authentication_htpasswd_user - Add user to OpenShift htpasswd authentication

This workload adds a single user to an existing OpenShift htpasswd oauth secret.

== Role overview

* This role enables authentication on an OpenShift 4 Cluster. It consists of the following tasks files:
** Tasks: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an
 environment for the workload deployment.
*** Debug task will print out: `pre_workload Tasks completed successfully.`

** Tasks: link:./tasks/workload.yml[workload.yml] - Used to configure authentication
*** Debug task will print out: `workload Tasks completed successfully.`

** Tasks: link:./tasks/post_workload.yml[post_workload.yml] - Used to
 configure the workload after deployment
*** This role doesn't do anything here
*** Debug task will print out: `post_workload Tasks completed successfully.`

** Tasks: link:./tasks/remove_workload.yml[remove_workload.yml] - Used to
 delete the workload
*** This role removes authentication from OCP 4. This role does *not* recreate the kubeadmin user - the only way to use OpenShift after removing the workload is via the `system:admin` user from the bastion VM.
*** Debug task will print out: `remove_workload Tasks completed successfully.`

== Review the defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you need to define to control the deployment of your workload.
* The variable *ocp_username* is mandatory to assign the workload to the correct OpenShift user.
* A variable *silent=True* can be passed to suppress debug messages.
* You can modify any of these default values by adding `-e "variable_name=variable_value"` to the command line

=== Deploy the Workload with the `ocp-workloads` config

----
TARGET_HOST="bastion.gbhxg.sandbox379.opentlc.com"
GUID=abcde
OCP_USERNAME="user-${GUID}"
WORKLOAD="ocp4_workload_authentication_htpasswd_user"

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, main.yml \
    -e"env_type=ocp-workloads" \
    -e"cloud_provider=none" \
    -e"software_to_deploy=none" \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=ec2-user" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"ACTION=provision"
----

=== Remove user with using `ocp-workloads` config

----
TARGET_HOST="bastion.gbhxg.sandbox379.opentlc.com"
GUID=abcde
OCP_USERNAME="user-${GUID}"
WORKLOAD="ocp4_workload_authentication_htpasswd_user"

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, main.yml \
    -e"env_type=ocp-workloads" \
    -e"cloud_provider=none" \
    -e"software_to_deploy=none" \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=ec2-user" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"ACTION=delete"
----
