= ocp4_workload_authentication_htpasswd_user - Add user to OpenShift htpasswd authentication

== Role overview

This workload adds a single user to an existing OpenShift htpasswd oauth secret.

The provisioning infrastructure will set a variable `ACTION` to be either `provision` or `destroy` depending on the operation.

== Review the defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] configures this workload.
** `ocp4_workload_authentication_htpasswd_user_name` is the user name to add and defaults to `user-{{ guid }}`.
** `ocp4_workload_authentication_htpasswd_user_password` allows password to be configured. If omitted then a password will be dynamically generated.
** `ocp4_workload_authentication_htpasswd_user_password_length` configures length of generated password.
** `ocp4_workload_authentication_htpasswd_user_enable_data` enable reporting user data for user name and password.
** `ocp4_workload_authentication_htpasswd_user_enable_messages` enable reporting user messages for user name and password.
