= Ansible Provisioner Env_Type

In this directory we keep the files for an "Ansible Provisioner" environment type.

This set of playbooks will:

- setup users
* AWS credentials
* authorized_keys to access by SSH
* symlinks (for Cloudform integration with OPEN_Admin repository)
* copy private key
- download repositories (ansible_agnostic_deployer, private OPEN_Admin)
- installed dependencies to run ansible_agnostic_deployer

//
// we create folders, yml files, and other items we want to over ride default variables.
//
// For example, we will include things such as ec2 instance names, secret
// variables such as private/public key pair information, passwords, etc.
//
// Eventually, all sensitive information will be encypted via Ansible Vault. The
// inclusion as well as instructions on doing this will be included in a later
// release.


== Set up your "Secret" variables

* You need to provide some credentials for deployments to work
* you can set these for each "Standard Config" in it's directory or have a
 global variables file that will overwrite any "Config" specific variable file.

* Create a file called `env_secret_vars.yml` in the "environment type" directory

.Example contents of "Secret" Vars file
[source,yaml]
----
# ## Logon credentials for Red Hat Network
# ## Required if using the subscription component
# ## of this playbook.
rhel_subscription_user: ''
rhel_subscription_pass: ''
# ## AWS Credentials. This is required.
aws_access_key_id: ""
aws_secret_access_key: ""

# Github login/password for OPEN_Admin repo, required with default mgr_users
github_user: ""
github_token: ""
----


For managing users on the ansible provisioner, you can override the `mgr_users` variable. The default is located in `{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/mgr_users.yml`, and looks like :

.Default mgr_users.yml
[source,yaml]
----
mgr_users:
  - name: opentlc-mgr
    home: /home/opentlc-mgr
    git_repos:
      - repo: "https://github.com/redhat-cop/agnosticd"
        dest: "/home/opentlc-mgr/ansible_agnostic_deployer"
        version: master
      - repo: "https://github.com/redhat-cop/agnosticd"
        dest: "/home/opentlc-mgr/dev_ansible_agnostic_deployer"
        version: development
      - repo: "https://github.com/redhat-gpe/OPEN_Admin"
        branch: master
        dest: "/home/opentlc-mgr/OPEN_Admin"
        user: "{{ github_user }}"
        password: "{{ github_token }}"
    private_key: ocpkey
    authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4OojwKH74UWVOY92y87Tb/b56CMJoWbz2gyEYsr3geOc2z/n1pXMwPfiC2KT7rALZFHofc+x6vfUi6px5uTm06jXa78S7UB3MX56U3RUd8XF3svkpDzql1gLRbPIgL1h0C7sWHfr0K2LG479i0nPt/X+tjfsAmT3nWj5PVMqSLFfKrOs6B7dzsqAcQPInYIM+Pqm/pXk+Tjc7cfExur2oMdzx1DnF9mJaj1XTnMsR81h5ciR2ogXUuns0r6+HmsHzdr1I1sDUtd/sEVu3STXUPR8oDbXBsb41O5ek6E9iacBJ327G3/1SWwuLoJsjZM0ize+iq3HpT1NqtOW6YBLR opentlc-mgr@inf00-mwl.opentlc.com
    aws_access_key_id: "{{aws_access_key_id}}"
    aws_secret_access_key: "{{aws_secret_access_key}}"
    symlinks:
      - src: OPEN_Admin/OPENTLC-OCP3/provision_workshop_env.sh
        path: bin/provision_workshop_env.sh
      - src: OPEN_Admin/OPENTLC-OCP3/provision-ose-projects.sh
        path: bin/provision-ose-projects.sh
      - src: OPEN_Admin/OPENTLC-OCP3/deploy_scripts
        path: bin/deploy_scripts
----

[NOTE]
--
- `github_*`: if you keep the default mgr_uers, those need to be set in order to download the OPEN_Admin private repository.
- `private_key`: key locally located in `~/.ssh/{{ private_key }}.pem` will be uploaded to host
- `git_repos`: list of repositories to be downloaded for user
--

For example you can add another user:

.managing users ("Secret" Vars file or Env Vars file)
[source,yaml]
----
  - name: fridim
    home: /home/fridim
    authorized_keys:
      - https://github.com/fridim.keys
    aws_access_key_id: "{{fridim_aws_access_key_id}}"
    aws_secret_access_key: "{{fridim_aws_secret_access_key}}"
    git_repos:
      - repo: "https://github.com/redhat-cop/agnosticd"
        dest: "/home/fridim/ansible_agnostic_deployer"
        version: master
      - repo: "https://github.com/redhat-cop/agnosticd"
        dest: "/home/fridim/dev_ansible_agnostic_deployer"
        version: development
----

== Review the Env_Type variable file

* This file link:./env_vars.yml[./env_vars.yml] contains all the variables you
 need to define to control the deployment of your environment.

== Running Ansible Playbook



. You can run the playbook with the following arguments to overwrite the default variable values:
[source,bash]
----
REGION=ap-southeast-2
KEYNAME=somekey
GUID=guid
ENVTYPE="ansible-provisioner"
CLOUDPROVIDER=ec2
HOSTZONEID='Z3IHLWJZOU9SRT'

time ansible-playbook ./main.yml \
-e "guid=${GUID}" \
-e "env_type=${ENVTYPE}"  \
-e "cloud_provider=${CLOUDPROVIDER}" \
-e "aws_region=${REGION}"  \
-e "HostedZoneId=${HOSTZONEID}"  \
-e "key_name=${KEYNAME}"  \
-e "subdomain_base_suffix=.example.opentlc.com"  \
-e "software_to_deploy=none"
----

. To Delete an environment
[source,bash]
----
REGION=ap-southeast-2
KEYNAME=somekey
GUID=guid
ENVTYPE="ansible-provisioner"
CLOUDPROVIDER=ec2

#To Destroy an Env
ansible-playbook ./configs/${ENVTYPE}/destroy_env.yml \
 -e "guid=${GUID}" \
 -e "env_type=${ENVTYPE}"  \
 -e "cloud_provider=${CLOUDPROVIDER}" \
 -e "aws_region=${REGION}"  \
 -e "HostedZoneId=${HOSTZONEID}"  \
 -e "key_name=${KEYNAME}"  \
 -e "subdomain_base_suffix=.example.opentlc.com"
----
