= AAP2 Ansible Workshops Config

Ansible Workshops is an example of an existing deployer being wrapped by Ansible.
This is the AAP2 (Ansible Automation Platform 2) version of the workshops.
link:https://github.com/ansible/workshops.git[Ansible Workshops] is capable of deploying multiple different types of Ansible based workshops:

* RHEL - 4 Linux nodes
* F5
* Networking - a 4 switch/router lab available in 4 different configurations
** multivendor (2 x Arista, Cisco, Juniper)
** 4 x Arista
** 4 x Cisco
** 4 x Juniper
* Windows
* Security


The `aap2-ansible-workshops` deployer is called by first running a fairly typical `Ansible Agnostic Deployer`
`pre_infra.yml` but at the end of that playbook:

Cloning the `aap2-ansible-workshops` repo to a specfic commit, this is currently hard coded into the deployer script
and executing the cloned provisioioning playbook. `aap2-ansible-workshops` specfic vars are made availble via:

* common_all_ansible_workshop_vars.yml

And one of:

* f5_tower_workshop_vars.yml
* networking_arista_tower_workshop_vars.yml
* networking_cisco_tower_workshop_vars.yml
* networking_juniper_tower_workshop_vars.yml
* networking_multivendor_tower_workshop_vars.yml
* rhel_tower_workshop_vars.yml
* security_tower_workshop_vars.yml
* windows_tower_workshop_vars.yml


== How the Different Labs get Configured

For deployment via RHPDS or similar deployer script will substitute the value of
`student_workloads` into a call to the relevant lab var file e.g.

Deployer Usage:
[source,bash]
----
$ mydeploy-script.sh --student_workloads=f5_tower_workshop --more_args ...
----

[source,bash]
----
ansible-playbook main.yml \
  -e ANSIBLE_REPO_PATH=${ANSIBLE_REPO_PATH} \
  -e guid=${GUID} \
  ..... args omitted for brevity
  -e @configs/aap2-ansible-workshops/common_all_ansible_workshop_vars.yml
  -e @configs/aap2-ansible-workshops/${STUDENT_WORKLOAD}_vars.yml 
----


== Set up your "Secret" variables

* You may need to provide some credentials for deployments to work
* Create a file called "env_secret_vars.yml" and put it in the
 ./ansible/configs/CONFIGNAME/ directory.
** At this point this file *has to be created* even if no vars from it are used.
* You can choose to provide these values as extra vars (-e "var=value") in the
 command line if you prefer not to keep sensitive information in a file.

.Example contents of "Secret" Vars file
----
foo: bar
----

== Running Ansible Playbook

You can run the playbook with the following arguments 

[NOTE]
====

Also it sets an ANSIBLE_CONFIG var to load a specfic set of vars for these labs.
This is the HIGHEST precedence for `ansible.cfg` so will mask any other
`ansible.cfg`
====

=== New sample vars format

[source,bash]
----
AWS_PROFILE=ansiblebu
ANSIBLE_CONFIG=configs/aap2-ansible-workshops/ansible.cfg
ANSIBLE_REPO_PATH=$(pwd)

ansible-playbook main.yml                                                   \
  -e ANSIBLE_REPO_PATH=${ANSIBLE_REPO_PATH}                                 \
  -e @configs/aap2-ansible-workshops/sample_vars.yml                             \
  -e @configs/aap2-ansible-workshops/vars/common_all_ansible_workshop_vars.yml   \
  -e @configs/aap2-ansible-workshops/vars/f5_tower_workshop_vars.yml             \
  -e @~/secret.yml                                                          \
  --skip-tags=deploy_infrastructure,pre_software_tasks,deploy_software,post_software,email \
  -vv

----

== Deploying other Ansible Workshops


=== To Delete an environment

This deletes the Ansible Engine Lab, notes below for the Networking labs

[source,bash]
----
GUID=td08
ENV_TYPE=aap2-ansible-workshops

EC2_NAME_PREFIX=${GUID}
EC2_REGION=us-east-1

ANSIBLE_REPO_PATH=$(pwd)

ansible-playbook ${ANSIBLE_REPO_PATH}/configs/${ENV_TYPE}/destroy_env.yml \
  -e ANSIBLE_REPO_PATH=${ANSIBLE_REPO_PATH} \
  -e ec2_name_prefix=${GUID} \
  -e ec2_region=${EC2_REGION} \
  -e @configs/aap2-ansible-workshops/vars/common_all_ansible_workshop_vars.yml   \
  -e @configs/aap2-ansible-workshops/vars/f5_tower_workshop_vars.yml             \
----

