---
- name: Step 001 Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step001
    - infrastructure

  tasks:

    - name: "Step 001 Infrastructure"
      ansible.builtin.debug:
        msg: "Step 001 Infrastructure"

    - name: Call Role to scale OpenShift using Assisted Installer
      when: openshift_cnv_assisted_scale | default(false) | bool
      ansible.builtin.include_role:
        name: host-ocp4-assisted-scale
