---

- name: Step 005 post software
  hosts: localhost
  connection: local
  gather_facts: false
  tags:
    - step005_01
    - post_software
  tasks:
    - debug:
        msg: "Post-Software tasks Started"

- name: PostSoftware flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step005_03
    - post_software
  tasks:
    - debug:
        msg: "Post-Software checks completed successfully"
