== Overview

*multi-network-app-pntae* is based on ansible-multitier-infra catalog with custom osp_cloud_template_master.j2 template to handle multiple networks per VM  
Check default_vars_osp.yml for sample usage of multiple networks per instance.

It makes an ideal base infrastructure to build on and can easily be extended via it's `env_vars.yml` to less or more machines and also to different operating system images.


== Supported Cloud Providers

* OSP

== Review the Env_Type variable file

The link:./env_vars.yml[./env_vars.yml] file contains all the variables you need to define to control the deployment of your environment.

This includes the ability to:

* Change the number of machines deployed
* Changed the operating system image (e.g. Ansible AMI or similar)
* Change the tags carried by any instances
* Change the base packages installed 
* Change/set the `ansible_user` and `remote_user`

These can be over-ridden at `ansible-playbook` runtime via `-e` options or perhaps more compactly by overriding vars in your own var file and invoking via `-e @my_env_vars.yml`

For further information on customizing images consult the link:../../../docs/Creating_a_config.adoc[Creating a Config Guide] 

== Deploying the `multi-network-app-pntae` config

You can deploy this config by running the following command from the `ansible`
directory. You will have to provide credentials and adjust settings to your own
environment.

`ansible-playbook main.yml -e @configs/multi-network-app-pntae/sample_vars_ec2.yml -e @<YOUR_SECRET_VARS.yml>`

=== To Delete an environment
----
`ansible-playbook destroy.yml -e @configs/multi-network-app-pntae/sample_vars_ec2.yml -e @<YOUR_SECRET_VARS.yml>`

----




