#!/bin/bash

argocd cluster add cluster1 &> /tmp/clusteradd

if [ $? -ne 0 ]
then
  SECRET_NAME=$(cat /tmp/clusteradd | grep Secret | perl -pe 's|.*?(argocd-manager-dockercfg-.*?)\\.*|\1|')
  oc --context cluster1 -n kube-system delete secret $SECRET_NAME &> /dev/null
  argocd cluster add cluster1 &> /tmp/clusteradd
fi

argocd cluster add cluster2 &> /tmp/clusteradd

if [ $? -ne 0 ]
then
  SECRET_NAME=$(cat /tmp/clusteradd | grep Secret | perl -pe 's|.*?(argocd-manager-dockercfg-.*?)\\.*|\1|')
  oc --context cluster2 -n kube-system delete secret $SECRET_NAME &> /dev/null
  argocd cluster add cluster2 &> /tmp/clusteradd
fi

argocd cluster add cluster3 &> /tmp/clusteradd

if [ $? -ne 0 ]
then
  SECRET_NAME=$(cat /tmp/clusteradd | grep Secret | perl -pe 's|.*?(argocd-manager-dockercfg-.*?)\\.*|\1|')
  oc --context cluster3 -n kube-system delete secret $SECRET_NAME &> /dev/null
  argocd cluster add cluster3 &> /tmp/clusteradd
fi
