#!/bin/bash

for context in cluster1 cluster2 cluster3
do
  if [ "0${context}" != "0$(oc config get-contexts ${context} -o name 2>/dev/null)" ]
  then
    echo "[ERROR] Context ${context} doesn't exist. Review the instructions"
    exit 1
  fi
done

echo "[OK] Contexts cluster1, cluster2 and cluster3 detected"

CLUSTER1_URL=$(oc config get-contexts cluster1 --no-headers=true | sed "s/  */@/g" | awk -F "@" '{print $3}')
CLUSTER2_URL=$(oc config get-contexts cluster2 --no-headers=true | sed "s/  */@/g" | awk -F "@" '{print $3}')
CLUSTER3_URL=$(oc config get-contexts cluster3 --no-headers=true | sed "s/  */@/g" | awk -F "@" '{print $3}')

if [ $(echo $CLUSTER1_URL $CLUSTER2_URL $CLUSTER3_URL | tr " " "\n" | sort -u | wc -l) -ne 3 ]
then
  echo "[ERROR] Duplicated API Endpoints found in your contexts, make sure you have used the correct api endpoint for each cluster"
  exit 1
fi

echo "[OK] Contexts cluster1, cluster2 and cluster3 use different api endpoints"

for context in cluster1 cluster2 cluster3
do
  if [ "0namespace/default" != "0$(oc --context ${context} get namespace default -o name)" ]
  then
    echo "[ERROR] Context ${context} is not working. Review you've provided correct credentials"
  fi
done

echo "[OK] All checks passed"
