---
- name: Step 002 Post Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step002
    - post_infrastructure
  tasks:
    - name: IBM Classic Baremetal Host Post Infrastructure Message
      ansible.builtin.debug:
        msg: "Step 002 Post Infrastructure - IBM Classic Baremetal Host Ready for Software Installation" 