---
- name: Step 003 Pre Software
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step003
    - pre_software
  tasks:
    - name: IBM Cloud Classic Baremetal Pre Software Message
      ansible.builtin.debug:
        msg: "Step 003 Pre Software - No software deployment required for IBM Cloud Classic Baremetal management" 