---
- name: "Deploy Jaeger instance in {{ t_user }}-project"
  k8s:
    namespace: "{{ t_user }}-project"
    state: present
    definition: "{{ lookup('file', './files/jaeger_instance.yaml') | from_yaml }}"
