= setup_instructlab

This role will install instructlab on a RHEL or Fedora machine.
Currently it is opininated and assumes that the machine has an Nvidia GPU and CUDA

It currently supports:

- RHEL 9 (tested aginst RHEL 9.3)
- Fedora (tested against Fedora 39)

In addition it stores a small number of pre-requsities (e.g. `gcc`) that are required for the installation of the NVIDIA drivers and CUDA Toolkit.

== Role Variables

This role is entirely self container ie is _fire and forget_ and does not require any variables to be set.

However the following link:./defaults/main.yml[variables] can be set to control the installation:
+

[source,sh]
----

setup_instructlab_repo_url: "https://github.com/instructlab/instructlab"
setup_instructlab_taxonomy_repo_url: "https://github.com/instructlab/taxonomy"
setup_instructlab_user: "instruct"
setup_instructlab_install_path_base: "/home/{{ setup_instructlab_user }}"  # Change this to your path
setup_instructlab_cuda_home: "/usr/local/cuda"
setup_instructlab_cuda_lib_path: "/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64"

setup_instructlab_developer_packages:
  - g++
  - gcc
  - git
  - make
  - python3.11
----

== Dependencies

None

== Example Playbook

Including an example of how to use your role (for instance, with variables passed in as parameters) is always nice for users too:

[source,yaml]
----
---
- name: Test EDA dispatcher
  hosts: localhost
  gather_facts: true
  become: true

  roles:
    - setup_instructlab
----

== Author Information

Tony Kay (tok@redhat.com) 2024-05-01
