= ocp4_workload_openshift_data_foundation - Deploys OpenShift Data Foundation (OCS)

== Role overview

* This role deploys OpenShift Data Foundation (formerly known as OpenShift Container Storage). It consists of the following tasks files:
** Tasks: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an environment for the workload deployment
*** Debug task will print out: `pre_workload Tasks completed successfully.`

** Tasks: link:./tasks/workload.yml[workload.yml] - Used to deploy the actual workload, i.e, 3scale, Mobile, some Demo or OpenShift customization
*** This role only prints the current username for which this role is provisioning.
*** Debug task will print out: `workload Tasks completed successfully.`

** Tasks: link:./tasks/post_workload.yml[post_workload.yml] - Used to configure the workload after deployment
*** This role doesn't do anything here
*** Debug task will print out: `post_workload Tasks completed successfully.`

** Tasks: link:./tasks/remove_workload.yml[remove_workload.yml] - Used to delete the workload
*** This role doesn't do anything here
*** Debug task will print out: `remove_workload Tasks completed successfully.`

== The defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you need to define to control the deployment of the workload.
* The variable *ocp_username* is mandatory to assign the workload to the correct OpenShift user.
* A variable *silent=True* can be passed to suppress debug messages.
* You can modify any of these default values by adding `-e "variable_name=variable_value"` to the command line
* You can modify any of these default values by adding `-e "variable_name=variable_value"` to the command line
* Your deployer will override any of these variables (usually CloudForms)
* Add long-name scoped workload parameters. Example: `ocp4_workload_example_machineconfigpool_name: worker`

=== Variable Naming

You *must* use long-name scope parameters for your workload to avoid variable clashing.
Ansible lacks robust variable scoping.
For example, parameters named `ocp4_workload_openshift_container_storage_*` would be recognized as unique to this workload

== Deploy a Workload with the `ocp-workload` playbook [Mostly for testing]

. If your workload uses parameters create a `<role name>_vars.yaml` input file.
+
.ocp4_workload_openshift_container_storage_vars.yaml
[source,yaml]
----
# You can set any variable, not just the dictionary
silent: true

# Set Variable 2
ocp4_workload_openshift_container_storage_variable_2: "My variable 2"
----

. Set up Environment Variables for the bastion you want to run this role on.
+
[source,yaml]
----
TARGET_HOST="bastion.dev.openshift.opentlc.com"
OCP_USERNAME="system:admin"
ANSIBLE_USER="ec2-user"
WORKLOAD="ocp4_workload_openshift_container_storage"
GUID=1001
----

. Finally run the workload passing the input files as parameters:
+
[source,sh]
----
# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=${ANSIBLE_USER}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"guid=${GUID}" \
    -e"ACTION=create" \
    -e @./ocp4_workload_openshift_container_storage_example_vars.yaml
----
+

=== To Delete an environment

----
TARGET_HOST="bastion.dev.openshift.opentlc.com"
OCP_USERNAME="system:admin"
ANSIBLE_USER="ec2-user"
WORKLOAD="ocp4_workload_openshift_container_storage"
GUID=1002

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=ec2-user" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"guid=${GUID}" \
    -e"ACTION=remove" \
    -e @./ocp4_workload_openshift_container_storage_vars.yaml \
    -e @./ocp4_workload_openshift_container_storage_secrets.yaml
----



