== s3_asset_injector

Injects asset into host directly from S3 bucket ie no CloudFront. Useful if asset is > 20GB eg LLM tar archives etc

=== Capabilities

Copies a single S3 asset to a host. This is useful for large assets that are too big to be served by CloudFront.
This could easily be extended to loop if need be

=== Requirements

N/A - these are basic ansible modules that should be available in any ansible installation.

=== Role Variables

See `defaults/main.yml` for the list of variables that can be overridden.

----

# Venv path

s3_asset_injector_venv_path: /tmp/s3_venv

# S3 asset data

s3_asset_injector_bucket: ""
s3_asset_injector_path: ""
s3_asset_injector_dest: ""
s3_asset_injector_mode: get

# AWS auth

s3_asset_injector_aws_access_key: "{{ s3_aws_access_key }}"
s3_asset_injector_aws_secret_key: "{{ s3_aws_secret_key }}"
s3_asset_injector_aws_region: "{{ aws_region }}"

# Unarchive if tar archive

s3_asset_injector_unarchive: false
s3_asset_injector_unarchive_path: ""
----

=== Dependencies

`boto3` python module on remote host, however this will be installed in a virtualenv on the remote host by the role

=== Example Playbook

Including an example of how to use your role (for instance, with variables passed in as parameters) is always nice for users too:

[source,yaml]
----
- hosts: servers
  tasks:

    - name: Inject assets
      include_role:
        name:s3_asset_injector
----

=== License

BSD

== Author Information

tony kay tok@redhat.com
