:role: satellite-manage-compute-profile
:author: Satellite Team
:tag1: configure_satellite
:tag2: satellite_compute_profile
:main_file: tasks/main.yml

Role: {role}
============

This role creates a compute profile in satellite

Requirements
------------

. Satellite must be installed and setted up.
. All the resources, that the compute profile is using needs to be ready, so all the content roles should run beforehand.


Role Variables
--------------

* Following are the variable to customize this role

  - name: "RHEL-8"
    compute_resource: 'LibvirtLocal'
    nics_attributes:
      0:
        type: network
        network: default
        model: virtio
    volume_attributes:
      0:
        pool_name: default
        capacity: 10G
        format_type: raw


[cols="2a,1a,3a"]
|===
|satellite_version: "Digit" |Required |satellite version
|satellite_admin: "String" |Required |Satellite admin username
|satellite_admin_password: "String" |Required |Satellite admin password
|satellite_compute_profiles: [list of {Dictionary}]
!===
!name: "String"
!compute_resource: "String"
!nics_attributes: "String"
!volume_attributes: "String"
!cpus: "String"
!memory: "String"
!===
|Required
!===
!Required
!Required
!Required
!Required
!Optional
!Optional
!===
|List of compute profile to create
!===
!Name of the compute-profile
!What compute resource to deploy on
!Nics attributes
!Volume attributes
!CPUs
!Memory
!===
|===

* Exammple variables

[source=text]
----
satellite_version: 6.7
satellite_admin: admin
satellite_admin_password: 'changeme'

satellite_compute_profiles:
  - name: "RHEL-8"
    compute_resource: 'LibvirtLocal'
    nics_attributes:
      0:
        type: network
        network: default
        model: virtio
    volume_attributes:
      0:
        pool_name: default
        capacity: 10G
        format_type: raw

----

Tags
---

|===
|{tag1} |Consistent tag for all satellite config roles
|{tag2} |This tag is specific to this role only
|===


Example Playbook
----------------

How to use your role (for instance, with variables passed in playbook).

[source=text]
----
[user@desktop ~]$ cat sample_vars.yml
satellite_version: 6.7
satellite_admin: admin
satellite_admin_password: 'changeme'

satellite_compute_profiles:
  - name: "RHEL-8"
    compute_resource: 'LibvirtLocal'
    nics_attributes:
      0:
        type: network
        network: default
        model: virtio
    volume_attributes:
      0:
        pool_name: default
        capacity: 10G
        format_type: raw

[user@desktop ~]$ cat playbook.yml
- hosts: satellites
  vars_files:
    - sample_vars.yml
  roles:
    - satellite-provisioning

[user@desktop ~]$ ansible-playbook playbook.yml
----


Tips to update Role
------------------

for reference look at link:{main_file}[main.yml].

Author Information
------------------

{author}
