= ocp4-workload-rhel-worker - Set up AWS RHEL8 worker via tasks on Bastion

== Role overview

* This role installs one or more AWS RHEL8 instances after OpenShift cluster installation.
* The student is expected to run the `openshift-ansible` playbook on the bastion host in order for the RHEL8 Workers to join the cluster.

* This role was created because the AWS EC2 instances created for the RHEL8 Workers nodes must be deployed AFTER the OpenShift cluster.
** This is so because the OpenShift clouster deployer creates a new VPC for the OpenShift cluster, and AWS EC2 instances' VPC_id and subnets cannot be modified after they have been deployed.
* It sets up all AWS permissions necessary for the new RHEL nodes to join the cluster.
* It updates the bastion host with a checkout of the openshift-ansible project and a list of RHEL_workers.txt to be added to an ansible inventory.
* The user/student must run the openshift-ansible playbooks from the Bastion in order to install OpenShift on the RHEL nodes, and the playbooks will approve the CSRs and have the new RHEL workers join the cluster.
* There is the added benefit of allowing this workoad role to be run after ANY config that deploys a suitable AWS OpenShift cluster.
* You can deploy more than one worker by setting `ocp4_workload_rhel_worker_exact_count`.
* RHEL Worker ocp4_workload_rhel_worker_ami_name: "RHEL-8.4.0_HVM-20210825-x86_64-0-Access2-GP2" is fixed because it's proven to work, and can be found in many AWS regions.

. The role consists of the following tasks files:
** Tasks: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an environment for the workload deployment
*** Debug task will print out: `pre_workload Tasks completed successfully.`

** Tasks: link:./tasks/workload.yml[workload.yml] - Install the RHEL 8 Worker Playbooks onto the Bastion
*** Debug task will print out: `workload Tasks completed successfully.`

** Tasks: link:./tasks/post_workload.yml[post_workload.yml] - Used to configure the workload after deployment
*** This role doesn't do anything here
*** Debug task will print out: `post_workload Tasks completed successfully.`

** Tasks: link:./tasks/remove_workload.yml[remove_workload.yml] - Used to delete the workload
*** This role doesn't do anything here
*** Debug task will print out: `remove_workload Tasks completed successfully.`

== Review the defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you need to define to control the deployment of your workload.
* A variable *silent=True* can be passed to suppress debug messages.
* You can modify any of these default values by adding `-e "variable_name=variable_value"` to the command line

=== Deploy a Workload with the `ocp-workload` playbook [Mostly for testing]

----
TARGET_HOST="bastion.GUID.example.opentlc.com"
OCP_USERNAME="jmaltin-redhat.com"
WORKLOAD="ocp4-workload-rhel-worker"
GUID=1001
AWS_REGION=us-east-1 # or us-east-2 or eu-central-1
CLUSTER_NAME=xxxxx

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=ec2-user" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"aws_region=${AWS_REGION}" \
    -e"cluster_name=${CLUSTER_NAME}" \
    -e"ACTION=create"
----
