:role: satellite-manage-userroles
:author: Satellite Team
:tag1: configure_satellite
:tag2: satellite_authorization
:main_file: tasks/main.yml
:role_file: tasks/role.yml
:user_file: tasks/user.yml

Role: {role}
============

This role add ability to configure authorization in satellite.
It can add roles and users to the main organization.

Requirements
------------

. Satellite must be installed and setted up.


Role Variables
--------------

* Following are the variable to customize this role

[cols="3,1,3"]
|===
|satellite_admin: "String" |Required |Satellite admin username
|satellite_admin_password: "String" |Required |Satellite admin password
|satellite_roles: [list of {Dictionary}] |Required | User roles to add
|satellite_users: [list of {Dictionary}] |Required | Users to add
|===

For more reference on variables take a look at foreman-ansible-documentation of modules *foreman_role* and *foreman_user* as this role is using those and basically just copy the arguments over.

* Exammple variables

[source=text]
----
satellite_admin: admin
satellite_admin_password: 'changeme'
satellite_roles:
  - name: Report Template Generator
    description: Role to allow template management
    filters:
      - permissions:
          - lock_report_templates
          - generate_report_templates
          - edit_report_templates
          - destroy_report_templates
          - create_report_templates
          - view_report_templates

satellite_users:
  - name: summit-admin
    description: 'User with template management permissions'
    firstname: Summit
    lastname: Admin
    mail: 'admin@summit.example.com'
    admin: yes
    password: summit2020
  - name: template_user
    description: 'User with template management permissions'
    firstname: Template
    lastname: User
    mail: 'template@user.com'
    password: changeme
    roles:
      - Report Template Generator

----

Tags
---

|===
|{tag1} |Consistent tag for all satellite config roles
|{tag2} |This tag is specific to this role only
|===


Example Playbook
----------------

How to use your role (for instance, with variables passed in playbook).

[source=text]
----
[user@desktop ~]$ cat sample_vars.yml
satellite_version: 6.7
satellite_admin: admin
satellite_admin_password: 'changeme'

satellite_roles:
  - name: Report Template Generator
    description: Role to allow template management
    filters:
      - permissions:
          - lock_report_templates
          - generate_report_templates
          - edit_report_templates
          - destroy_report_templates
          - create_report_templates
          - view_report_templates

satellite_users:
  - name: summit-admin
    description: 'User with template management permissions'
    firstname: Summit
    lastname: Admin
    mail: 'admin@summit.example.com'
    admin: yes
    password: summit2020
  - name: template_user
    description: 'User with template management permissions'
    firstname: Template
    lastname: User
    mail: 'template@user.com'
    password: changeme
    roles:
      - Report Template Generator

[user@desktop ~]$ cat playbook.yml
- hosts: satellites
  vars_files:
    - sample_vars.yml
  roles:
    - satellite-provisioning

[user@desktop ~]$ ansible-playbook playbook.yml
----

Tips to update Role
------------------

for reference look at link:{main_file}[main.yml] and specific for roles link:{role_file}[role.yml] and for user link:{user_file}[user.yml].

Author Information
------------------

{author}
