---
ocp4_workload_osc_configure_aro_osc_channel: stable

ocp4_workload_osc_configure_aro_update_kata_rpm: true
ocp4_workload_osc_configure_aro_kata_rpm_gdrive_id: "1kYV-CIAMCafxGYDVwc5z7yGrbbMbaxXq"
ocp4_workload_osc_configure_aro_kata_rpm_url: ""

ocp4_workload_osc_configure_aro_peerpod_instance_size: "Standard_D4as_v5"
ocp4_workload_osc_configure_aro_peerpod_instance_sizes: >-
  Standard_D2as_v5,Standard_D2es_v5,Standard_D4as_v5,
  Standard_D4es_v5,Standard_D8es_v5,Standard_D8as_v5
ocp4_workload_osc_configure_aro_peerpods_limit_per_node: "10"

ocp4_workload_osc_configure_aro_operator_wait_timeout: 600
ocp4_workload_osc_configure_aro_mcp_wait_timeout: 900
ocp4_workload_osc_configure_aro_runtimeclass_wait_timeout: 1200
