= Generic Example Env_Type

In this directory we keep the files for a "Generic Example" environment type.

we create folders, yml files, and other items we want to over ride default variables.

For example, we will include things such as ec2 instance names, secret
variables such as private/public key pair information, passwords, etc.

Eventually, all sensitive information will be encypted via Ansible Vault. The
inclusion as well as instructions on doing this will be included in a later
release.

== Set up your "Secret" variables

* You need to provide some credentials for deployments to work
* you can set these for each "Standard Config" in it's directory or have a
 global variables file that will overwrite any "Config" specific variable file.

* Create a file called env_secret_vars.yml in the "environment type" directory

.Example contents of "Secret" Vars file
[source,bash]
----
#####################################################
# subscription_manager |  Subscribe RHEL Nodes
#####################################################
username:                     ""
password:                     ""
pool_id:                      ""
#####################################################
# aws.infra.terraform  |  AWS API Keys terraform.tfvars
#####################################################
aws_access_key:               ""
aws_secret_key:               ""
#####################################################
# aws.infra.terraform  |  Domain Name you own
#####################################################
domain_name:                  ""
zone_id:                      ""
----

== Review the Env_Type variable file

* This file link:./env_vars.yml[./env_vars.yml] contains all the variables you
 need to define to control the deployment of your environment.

== Running Ansible Playbook



.You can run the playbook with the following arguments to overwrite the default variable values:
[source,bash]
----
ansible-playbook -i ansible/inventory/ec2.py \
                 -e "env_type=ansible-tower-terraform" \
                 -e "workshop_prefix=testing123" \
                 -e "ANSIBLE_REPO_PATH | default('.')='{{ lookup('env','PWD') }}/ansible'" \
                 -e "cloud_provider=terraform" \
                 -e "software_to_deploy=none" \
                 ansible/main.yml
----

.To Delete an environment
[source,bash]
----
ansible-playbook -i ansible/inventory/ec2.py \
                 -e "env_type=ansible-tower-terraform" \
                 -e "workshop_prefix=testing123" \
                 -e "ANSIBLE_REPO_PATH | default('.')='{{ lookup('env','PWD') }}/ansible'" \
                 -e "cloud_provider=terraform" \
                 -e "software_to_deploy=none" \
                 ansible/destroy.yml
----
