## automation_platform_loader


This role is intended to be used to load resources onto an Ansible Automation Controller

* Optionally generate an ssh keypair for use by the Automation Controller
* Iterates through a list of resources to be loaded onto the Automation Controller

NOTE: The role wraps the link:https://github.com/redhat-cop/controller_configuration/[infra.controller_configuration] collection, which is well documented


### Variables

The role is inherently simple, creating temporary `id_ed25519` and `id_ed25519.pub` files in `/tmp`. These are deleted after being captured into a fact `generated_ssh_keypair` which is then used by the `infra.controller_configuration` collection.
[source,sh]
----
automation_platform_loader_generate_ssh_keypair: true

automation_platform_loader_ssh_key_type: ed25519
automation_platform_loader_ssh_key_path: "/tmp/id_{{ automation_platform_loader_ssh_key_type }}" 
----

In normal usage, you would not need to override these variable

### Dependencies

N/A

Example Playbook
----------------

Including an example of how to use your role (for instance, with variables passed in as parameters) is always nice for users too:
+
[source,sh]
----
    - hosts: controller
      environment:
        CONTROLLER_HOST: "{{ controller_host }}"
        CONTROLLER_USERNAME: "{{ controller_username | default('admin') }}"
        CONTROLLER_PASSWORD: "{{ controller_password }}"
        CONTROLLER_VERIFY_SSL: "{{ controller_verify_ssl | default('true') }}"
      vars:
        controller_configuration_dispatcher_roles:
          - role: organizations
            var: controller_organizations
            tags: organizations
          - role: projects
            var: controller_projects
            tags: projects

        controller_organizations:
          - name: engineering
            description: "Engineering Organization"
          - name: sales
            description: "Sales Organization"
          
         controller_projects:

          - name: "GitLab playbook-rhaap"
            scm_url: "https://gitlab.com/ansible-ssa/playbook-rhaap.git"
            organization: Default
            scm_type: git
            scm_branch: "{{ project_version | default('main') }}"
            scm_update_on_launch: true
            scm_delete_on_update: true
            state: "{{ controller_state | default('present') }}"

      roles:
         -  /automation_platform_loader
----

Author Information
------------------

Tony Kay 2023-04-26
