---
galaxy_info:
  role_name: ocp4_workload_open_ssh_from_bastion
  author: Red Hat, Cluster Platform (ITCP) (itcp-team@redhat.com)
  description: |
    Open/allow SSH communication from the Bastion host to the nodes of the OCP4 cluster
  license: MIT
  min_ansible_version: "2.9"
  platforms: []
  galaxy_tags:
  - ocp
  - openshift
dependencies: []
