== Showroom

Showroom is an Ansible role that installs and configures Showroom, a replacement for bookbag.
Showroom provides views (1 or more webpages) onto external web based resouces (e.g. websites, webapps, etc.).
It's primary use case is to provide a 1 stop console for demos, workshops, and labs.

=== Core Concepts

* Views - a view is a webpage that is displayed in the browser, it can include:
** Demo, lab, workshop content - typically created in asciidoc with Antora or similar
** Tabs (iframed) - internal or external http based services e.g.
*** Terminal(s) (tty) e.g. Butterfly, xtermjs etc
*** IDEs such as VSCode/CodeServer, JupyterNotes etc
*** Consoles e.g. OpenShift, ArgoCD, Automation Controller etc

NOTE: Consoles are typically iframed into a view, but can be opened in a new tab/window.
Issues *may* arise with iframing some consoles, e.g. OpenShift, ArgoCD, Automation Controller etc and these are actively being investiagted.


=== Requirements

* Ansible 2.9 or higher

Any pre-requisites that may not be covered by Ansible itself or the role should be mentioned here. For instance, if the role uses the EC2 module, it may be a good idea to mention in this section that the boto package is required.

=== Role Variables


A description of the settable variables for this role should go here, including any variables that are in defaults/main.yml, vars/main.yml, and any variables that can/should be set via parameters to the role. Any variables that are read from other roles and/or the global scope (ie. hostvars, group vars, etc.) should be mentioned here as well.

=== Dependencies

A list of other roles hosted on Galaxy should go here, plus any details in regards to parameters that may need to be set for other roles, or variables that are used from other roles.

=== Example Playbook


    - hosts: servers
      roles:
         - showroom

==== License

BSD

===== Author Information

- Tony Kay (tok@redhat.com)

