= OPENTLC-SHARED standard config

In this directory, we create folders, yml files, and other items
we want to over ride default variables.

For example, we will include things such as ec2 instance names, secret
variables such as private/public key pair information, passwords, etc.

Eventually, all sensitive information will be encypted via Ansible Vault. The
inclusion as well as instructions on doing this will be included in a later
release.

== Set up your "Secret" variables

* You need to provide some credentials for deployments to work
* you can set these for each "Standard Config" in it's directory or have a
 global variables file that will overwrite any "Config" specific variable file.

=== "Config" specific method:

* Create a file called anything_secret.yml in the
 Config/standard_configs/opentlc-shared:

.Example contents of "Secret" Vars file
----
# ## Logon credentials for Red Hat Network
# ## Required if using the subscription component
# ## of this playbook.
rhel_subscription_user: ''
rhel_subscription_pass: ''
#
# ## LDAP Bind Password
bindPassword: ''
#
# ## Desired openshift admin name and password
admin_user: ""
admin_user_password: ""
#
# ## AWS Credentials. This is required.
aws_access_key_id: ""
aws_secret_access_key: ""
----

=== "Global" Overwrite method:

* Create a file called globalsomething_secret.yml in the
 Config/custom_config/opentlc-shared:

.Example contents of "Secret" Vars file
----
# ## Logon credentials for Red Hat Network
# ## Required if using the subscription component
# ## of this playbook.
rhel_subscription_user: ''
rhel_subscription_pass: ''
#
# ## LDAP Bind Password
bindPassword: ''
#
# ## Desired openshift admin name and password
admin_user: ""
admin_user_password: ""
#
# ## AWS Credentials. This is required.
aws_access_key_id: ""
aws_secret_access_key: ""
----

== Running Ansible Playbook



. You can run the playbook with the following arguments to overwrite the default variable values:
[source,bash]
----
ansible-playbook -i 127.0.0.1 ansible/main.yml \
  -e "env_type=opentlc-shared" \
  -e "aws_region=ap-southeast-2" \
  -e "guid=youruniqueidentifier" \
  -e "HostedZoneId=Z1TQFSYFZUAO0D" \
  -e "key_name=default_key_name" \
  -e "subdomain_base_suffix=.openshift.opentlc.com" \
  -e "bastion_instance_type=t2.large" \
  -e "master_instance_type=t2.large" \
  -e "infranode_instance_type=r3.xlarge" \
  -e "node_instance_type=r3.xlarge" \
  -e "nfs_instance_type=c3.large" \
  -e "node_instance_count=2"
----
