= Ansible CI/CD Hackathon environment.

== Introduction

This environment has been initially jointly created by the AMS, EMEA and GPTE teams for the RHTE 2018 sessions.

All servers in this environment have an internal and an external name using the GUID you've got through the grabber or directly through RHPDS:

- an external name: *NAME*.*GUID*.example.opentlc.com
- an internal name: *NAME*.*GUID*.internal

The servers have following names:

- bastion - this is the host through which you can easily connect to all the other ones.
- tower1 - the Ansible Tower server
- cicd1 - The CI/CD server (or build and test host) with Jenkins and Gogs pre-installed
* the Jenkins server is available under http://cicd1.GUID.example.opentlc.com:8080, the user is _admin_ (with the usual password)
- app1 and appdb1 - two "playground" hosts

You may connect to the bastion host using the credentials given to you (by e-mail or GUID grabber) and from there jump to the other servers.

TODO continue the description once the details and quirks are out

== Running Ansible Playbook

You can run the playbook with the following arguments to overwrite the default variable values:
[source,bash]
----

# Generic Vars
ENVTYPE="ansible-cicd-lab"
GUID=cicdtest3

# Cloud Provider Settings
KEYNAME=ocpkey
REGION=ap-southeast-2
CLOUDPROVIDER=ec2
HOSTZONEID='Z3IHLWJZOU9SRT'
BASESUFFIX='.example.opentlc.com'

# OCP Vars
REPO_VERSION=3.11


ansible-playbook ansible/main.yml \
  -e "guid=${GUID}" \
  -e "env_type=${ENVTYPE}" \
  -e "osrelease=${OSRELEASE}" \
  -e "repo_version=${REPO_VERSION}" \
  -e "cloud_provider=${CLOUDPROVIDER}" \
  -e "aws_region=${REGION}" \
  -e "HostedZoneId=${HOSTZONEID}" \
  -e "key_name=${KEYNAME}" \
  -e "subdomain_base_suffix=${BASESUFFIX}" \
  -e "email=name@example.com" -e"output_dir=/opt/workdir" -e"output_dir=/opt/workdir" -e"software_to_deploy=tower" -e@../secret.yml -vvvv
----


* Additional Vars:
+
[source,bash]
----
ADMIN_PASSWORD=somepassword
LICENSE_URL=https://admin.example.com/download/ansible_bootcamp/tower/licenses/license.txt

      -e"license_file_url=${LICENSE_URL}" \
      -e "repo_method=file" -e "own_repo_path=${REPO_PATH}" -e "repo_version=${REPO_VERSION}" \
      -e "software_to_deploy=tower" \
      -e"deploy_tower_demo=true" \
      -e"tower_admin_password=${ADMIN_PASSWORD}"
----

== Running Ansible Playbook for Homework Assignment

You can run the playbook with the following arguments to overwrite the default variable values:
[source,bash]
----
REGION=ap-southeast-2
KEYNAME=bennokey
GUID=testbenno2
ENVTYPE="ans-tower-lab"
CLOUDPROVIDER=ec2
HOSTZONEID='Z3IHLWJZOU9SRT'
REPO_PATH='http://admin.example.com/repos/ocp/3.6/'

BASESUFFIX='.example.opentlc.com'
DEPLOYER_REPO_PATH=`pwd`

ansible-playbook \
   ${DEPLOYER_REPO_PATH}/main.yml  \
    -e "ANSIBLE_REPO_PATH=${DEPLOYER_REPO_PATH}" \
      -e "guid=${GUID}" \
      -e "env_type=${ENVTYPE}" \
      -e "key_name=${KEYNAME}" \
      -e "subdomain_base_suffix=${BASESUFFIX}" \
        -e "cloud_provider=${CLOUDPROVIDER}" \
        -e "aws_region=${REGION}" \
        -e "HostedZoneId=${HOSTZONEID}" \
        -e "email=name@example.com" \
      -e "install_ipa_client=false" \
      -e "repo_method=file" -e "own_repo_path=${REPO_PATH}" -e "repo_version=${REPO_VERSION}" \
      -e "software_to_deploy=none" -e "deploy_tower_demo=false" -e "install_win_ssh=false"  -e "install_win_ad=false" -e "deploy_tower_homework=true"
----



=== To Delete an environment

[source,bash]
----
# Generic Vars
ENVTYPE="ansible-cicd-lab"
GUID=ocpwtest1

# Cloud Provider Settings
REGION=ap-southeast-2
CLOUDPROVIDER=ec2
#To Destroy an Env
ansible-playbook  ./ansible/configs/${ENVTYPE}/destroy_env.yml -e "aws_region=${REGION}"   -e "guid=${GUID}" -e "env_type=${ENVTYPE}"  -e "cloud_provider=${CLOUDPROVIDER}"   -e@../secret.yml -vv

----
