---
# -------------------------------------------------------------
# Create an Azure federated identity credential linking the 
# service account in OpenShift Container Platform to the Azure user-assigned managed identity.
# -------------------------------------------------------------
open-env-azure-aro-ai-search-federated-app-id: "f1dd0a37-89c6-4e07-bcd1-ffd3d43d8875"
open-env-azure-aro-ai-search-federated-id-cred-name: "{{ azure_resource_group }}-identity"
open-env-azure-aro-ai-search-sa-namespace: "user"
open-env-azure-aro-ai-search-sa-name: "user"
open-env-azure-aro-ai-search-location: "eastus"
open-env-azure-aro-ai-search-user-ai-sub: "{{ azure_subscription_id }}"
open-env-azure-aro-ai-search-user-ai-rg: "rhdp-ai"
open-env-azure-aro-ai-search-user-ai-search-name: "parasol-workshop-search"
open-env-azure-aro-ai-search-user-ai-name: "llm-gpt4-lightspeed"