---
# -------------------------------------------------------------
# Create an Azure federated identity credential linking the 
# service account in OpenShift Container Platform to the Azure user-assigned managed identity.
# -------------------------------------------------------------
open-env-azure-aro-ai-search-federated-app-id: "f1dd0a37-89c6-4e07-bcd1-ffd3d43d8875"
open-env-azure-aro-ai-search-federated-id-cred-name: "{{ RESOURGEGROUP }}-identity"
open-env-azure-aro-ai-search-sa-namespace: "user"
open-env-azure-aro-ai-search-sa-name: "parasol"
open-env-azure-aro-ai-search-location: "eastus"
open-env-azure-aro-ai-search-user-ai-sub: "{{ azure_subscription_id }}"
open-env-azure-aro-ai-search-user-ai-rg: "change-me"
open-env-azure-aro-ai-search-user-ai-search-name: "change-me"
open-env-azure-aro-ai-search-user-ai-name: "change-me"
open-env-azure-aro-ai-search-user-ai-search-scope: "/subscriptions/{{ open-env-azure-aro-ai-search-user-ai-sub }}/resourceGroups/{{ open-env-azure-aro-ai-search-user-ai-rg }}/providers/Microsoft.Search/searchServices/{{ open-env-azure-aro-ai-search-user-ai-search-name }}"
open-env-azure-aro-ai-search-user-ai-scope: "/subscriptions/{{ open-env-azure-aro-ai-search-user-ai-sub }}/resourceGroups/{{ open-env-azure-aro-ai-search-user-ai-rg }}/providers/Microsoft.CognitiveServices/accounts/{{ open-env-azure-aro-ai-search-user-ai-name }}"

