{
 "title": "Camel - Quarkus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(camel_exchanges_total,job)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(camel_exchanges_total{job=\"$job\"},pod)"
    }
   },
   {
    "name": "routeId",
    "label": "RouteId",
    "query": {
     "query": "label_values(camel_exchanges_total{job=\"$job\"},routeId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "JVM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"$job\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "jvm_threads_live_threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"$job\",pod=\"$pod\"}",
     "legendFormat": "$pod"
    }
   ]
  },
  {
   "title": "jvm_memory_used_bytes - heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"$job\",pod=\"$pod\",area=\"heap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "jvm_memory_used_bytes - non heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"$job\",pod=\"$pod\",area=\"nonheap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Camel Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "camel_exchanges_succeeded_total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "camel_exchanges_succeeded_total{ job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}"
    }
   ]
  },
  {
   "title": "camel_exchanges_inflight",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "camel_exchanges_inflight{ job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}"
    }
   ]
  },
  {
   "title": "camel_exchanges_failed_total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "camel_exchanges_failed_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}"
    }
   ]
  }
 ]
}