---
- name: Set up MTV provider(s) for VMware
  ansible.builtin.include_tasks: vcenter_setup_mtv_providers.yml

- name: Set single-user agnosticd user info data for vCenter
  when: ocp4_workload_virt_roadshow_fvmw_num_users | int == 1
  agnosticd_user_info:
    data:
      vcenter_user: "{{ ocp4_workload_virt_roadshow_fvmw_vcenter_user }}"
      vcenter_password: "{{ ocp4_workload_virt_roadshow_fvmw_vcenter_user_password }}"
      vcenter_full_user: "{{ ocp4_workload_virt_roadshow_fvmw_vcenter_user }}"
      vcenter_console: "{{ fvmw_hostname }}"
      vcenter_datastore: "{{ ocp4_workload_virt_roadshow_fvmw_datastore }}"

- name: Set multi-user agnosticd user info data for vCenter
  when: ocp4_workload_virt_roadshow_fvmw_num_users | int > 1
  agnosticd_user_info:
    user: "{{ ocp4_workload_virt_roadshow_fvmw_auth_user_base }}{{ user_number }}"
    data:
      vcenter_user: "{{ ocp4_workload_virt_roadshow_fvmw_auth_user_base }}{{ user_number }}"
      vcenter_password: "{{ ocp4_workload_virt_roadshow_fvmw_vcenter_user_password }}"
      vcenter_full_user: "{{ ocp4_workload_virt_roadshow_fvmw_auth_user_base }}{{ user_number }}"
      vcenter_console: "{{ fvmw_hostname }}"
      vcenter_datastore: "{{ ocp4_workload_virt_roadshow_fvmw_datastore }}"
  loop: "{{ range(1, ocp4_workload_virt_roadshow_fvmw_num_users | int + 1) | list }}"
  loop_control:
    loop_var: user_number

- name: Set agnosticd user info data for vCenter common to all users
  agnosticd_user_info:
    data:
      vcenter_password: "{{ ocp4_workload_virt_roadshow_fvmw_vcenter_user_password }}"
      vcenter_console: "{{ fvmw_hostname }}"
      vcenter_datastore: "{{ ocp4_workload_virt_roadshow_fvmw_datastore }}"
      guid: "{{ guid }}"

# Leave this as the last task in the playbook.
# --------------------------------------------
- name: Workload tasks complete
  when: not silent|bool
  ansible.builtin.debug:
    msg: "Workload Tasks completed successfully."
