= ocp-workload-amq-enmasse

== Overview

=== Purpose
This role creates a `single-tenant` enmasse project primarily for supporting elab students of the _AMQ Enmasse Foundations_ course.

The alternative would be a `mulit-tenant` environment.
However, a multi-tenant enmasse deployment requires the OCP user to be provided with _cluster-admin_ role.

A multi-tenant environment would be better suited for an ILT where a dedicated _OCP Workshop_ environment existed.
The course instructor would provision the multi-tenant enmasse using the _opentlc-mgr_ account (which is a cluster-admin).
Students (via accounts user[1-100] ), would authenticate into the multi-tenant enmasse address-controller.

=== Why this ansible ?

The enmasse project already includes ansible playbooks link://https://github.com/EnMasseProject/enmasse/tree/master/templates/install[found here].

However, there are challenges with leveraging that community enmasse ansible from this ansible-agnostic-deployer role as indicated in link:https://gist.github.com/jbride/e421267bc82493229a42220bd0c8f66c[this gist].

Subsequentlly, the approach is to copy ansible into this ansible-agnostic-deployer role from the following two projects:

. https://github.com/btison/enmasse-ansible
. https://github.com/EnMasseProject/enmasse

== Deploy a Workload with the `ocp-workload` playbook
----
GUID=jb45
HOST_GUID=dev39
TARGET_HOST="bastion.$HOST_GUID.openshift.opentlc.com"
OCP_USERNAME="jbride-redhat.com"
WORKLOAD="ocp-workload-amq-enmasse"
SSH_USERNAME="jbride-redhat.com"
SSH_PRIVATE_KEY="id_ocp"

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
                 -e"ansible_ssh_private_key_file=~/.ssh/${SSH_PRIVATE_KEY}" \
                 -e"ansible_user=${SSH_USERNAME}" \
                    -e"ocp_username=${OCP_USERNAME}" \
                    -e"ocp_workload=${WORKLOAD}" \
                    -e"guid=${GUID}" \
                    -e"ocp_user_needs_quota=true" \
                    -e"ocp_apps_domain=apps.${HOST_GUID}.openshift.opentlc.com" \
                    -e"namespace=amq-enmasse-${GUID}" \
                    -e"ACTION=create"

----

== To Delete an environment
----
GUID=jb45
HOST_GUID=dev39
TARGET_HOST="bastion.$HOST_GUID.openshift.opentlc.com"
OCP_USERNAME="jbride-redhat.com"
WORKLOAD="ocp-workload-amq-enmasse"
SSH_USERNAME="jbride-redhat.com"
SSH_PRIVATE_KEY="id_ocp"

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
                 -e"ansible_ssh_private_key_file=~/.ssh/${SSH_PRIVATE_KEY}" \
                 -e"ansible_user=${SSH_USERNAME}" \
                    -e"ocp_username=${OCP_USERNAME}" \
                    -e"ocp_workload=${WORKLOAD}" \
                    -e"guid=${GUID}" \
                    -e"namespace="amq-enmasse-${GUID} \
                    -e"ACTION=remove"
----
