:role: satellite-manage-manifest
:author: GPTE Team
:tag1: configure_satellite
:tag2: configure_satellite_manifest
:main_file: tasks/main.yml
:version_file: tasks/version_6.4.yml

Role: {role}
============

This role upload manifest onto satellite server.

Requirements
------------

Following are the requirements:

. Satellite must be install and setup.
. Hammer cli config must be configured/updated with privileged user and password to run the satellite cli.
 

Role Variables
--------------

* Following are the variable which needs to be defined 

|===
|satellite_version: "Digit" |Required |satellite version
|org: "String" |Required |Organization name
|org_label: "String" |Not-equired | Organization label in string without space
|org_description: "String" |Not-required | Organization description
|subscription_name: "String" |Required |Subscription name for manifest 
|manifest_file: "String" |Required |Holds local path of manifest file
|===
    
* Exammple variables

[source=text]
----
satellite_version: 6.4
org: "gpte"
org_label: "gpte"
org_description: "Global Partner Training and Enablement"
subscription_name: "Employee SKU"
manifest_file: /home/user/manifest.zip
----

Tags
---

|===
|{tag1} |Consistent tag for all satellite config roles
|{tag2} |This tag is specific to this role only
|===

* Example tags

----
## Tagged jobs
ansible-playbook playbook.yml --tags configure_satellite,configure_satellite_manifest

## Skip tagged jobs
ansible-playbook playbook.yml --skip-tags configure_satellite,configure_satellite_manifest
----

Example Playbook
----------------

How to use your role (for instance, with variables passed in playbook).

[source=text]
----
[user@desktop ~]$ cat sample_vars.yml
satellite_version: 6.4
org: "gpte"
org_label: "gpte"
org_description: "Global Partner Training and Enablement"
subscription_name: "Employee SKU"
manifest_file: /home/user/manifest.zip


[user@desktop ~]$ cat playbook.yml
- hosts: satellite.example.com
  vars_files:
    - sample_vars.yml
  roles:
    - satellite-manage-manifest

[user@desktop ~]$ ansible-playbook playbook.yml
----

Tips to update Role
------------------

To extend role works for other version, create new file named  version_{{satellite_version}}.yml and import newly created file in main.yml

for reference look at link:{main_file}[main.yml] and link:{version_file}[version_6.4.yml]


Author Information
------------------

{author}
