:role: satellite-manage-manifest
:author: GPTE Team
:tag1: configure_satellite
:tag2: configure_satellite_manifest
:main_file: tasks/main.yml
:version_file: tasks/version_6.x.yml

Role: {role}
============

This role upload manifest onto satellite server.

Requirements
------------

Following are the requirements:

. Satellite must be install and setup.


Role Variables
--------------

* Following are the variable which needs to be defined

[cols="4a,2a,4a"]
|===
|satellite_version: "Digit" |Required |satellite version
|org: "String" |Required |Organization name
|org_label: "String" |Optional | Organization label in string without space
|org_description: "String" |Optional | Organization description
|cdn_repository_url: "String"|Optional | If to sync content from another cdn than https://cdn.redhat.com/
|satellite_manifest: {Dictionary}
[cols="1"]
!===
!type: "String"
!path: "String"
!url: "String"
!username: "String"
!password: "String"
!===
|Required
[cols="1"]
!===
!Required
!Required for 'file'
!Required for 'url'
!Optional for 'url'
!Optional for 'url'
!===
|Holds info to access the manifest file
[cols="1"]
!===
! Type of the storage (One of 'file', 'url')
! Path to the local file
! Url for the remote file
! Basic auth username for the remote file
! Basic auth password for the remote file
!===
|===


* Exammple variables

[source=text]
----
satellite_version: 6.7
org: "gpte"
org_label: "gpte"
org_description: "Global Partner Training and Enablement"
cdn_repository_url: "http://my.local.com/cdn"

satellite_manifest:
  type: file
  path: /home/user/manifest.zip
# or
satellite_manifest:
  type: url
  path: http://my-private.server.com/manifest.zip
  username: basicAuthUser
  password: verySecretPass
----

Tags
---

|===
|{tag1} |Consistent tag for all satellite config roles
|{tag2} |This tag is specific to this role only
|===

* Example tags

----
## Tagged jobs
ansible-playbook playbook.yml --tags configure_satellite,configure_satellite_manifest

## Skip tagged jobs
ansible-playbook playbook.yml --skip-tags configure_satellite,configure_satellite_manifest
----

Example Playbook
----------------

How to use your role (for instance, with variables passed in playbook).

[source=text]
----
[user@desktop ~]$ cat sample_vars.yml
satellite_version: 6.7
org: "gpte"
org_label: "gpte"
org_description: "Global Partner Training and Enablement"
cdn_repository_url: "http://my.local.com/cdn"
satellite_manifest:
  type: url
  path: http://my-private.server.com/manifest.zip
  username: basicAuthUser
  password: verySecretPass

[user@desktop ~]$ cat playbook.yml
- hosts: satellite.example.com
  vars_files:
    - sample_vars.yml
  roles:
    - satellite-manage-manifest

[user@desktop ~]$ ansible-playbook playbook.yml
----

Tips to update Role
------------------

To extend role works for other version, if necessary create new file named  version_{{satellite_version}}.yml and import newly created file in main.yml

for reference look at link:{main_file}[main.yml] and link:{version_file}[version_6.x.yml]


Author Information
------------------

{author}
