#!/bin/bash
set -euxo pipefail

until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]; do
    echo "Waiting for instruqt bootstrap to complete"
    sleep 1
done

echo "Setup script for satellite"


echo "Adding wheel" > /root/post-run.log
usermod -aG wheel rhel

echo "setting password" >> /root/post-run.log
echo redhat | passwd --stdin rhel

echo "DONE" >> /root/post-run.log

export LOCALHOST=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1') > /dev/null 2>&1

grep -qxF "${LOCALHOST} satellite.lab" /etc/hosts || echo "${LOCALHOST} satellite.lab" >> /etc/hosts

echo "export LANG=en_US.UTF-8" >> /root/.bashrc

hammer -u admin -p bc31c9a6-9ff0-11ec-9587-00155d1b0702 subscription upload --file /home/myee/manifest_satellite-6.10-instruqt_20230116T214917Z.zip --organization "Acme Org"
rm -rf /home/myee/manifest_satellite-6.10-instruqt_20230116T214917Z.zip

hammer subscription refresh-manifest --organization "Acme Org"
hammer ansible roles import --proxy-id 1