---
- name: Create Container "{{ _container.name }}"
  vars:
    _spec: |
      restartPolicy: Always
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: "{{ _container.cpu | default(1) }}"
              memory: "{{ _container.memory | default("32Mi") }}"
            requests:
              cpu: "{{ _container.cpu | default(1) }}"
              memory: "{{ _container.memory | default("32Mi") }}"
          env: {{ _container.environment | dict2items(key_name='name', value_name='value') }}
          name: "{{ _container.name }}"
          ports: {{ _container.ports }}
          imagePullPolicy: Always
          image: "{{ _container.image }}"
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        name: "{{ _container.name }}"
        namespace: "{{ openshift_cnv_namespace }}"
        labels:
          app.kubernetes.io/name: "{{ _container.name }}"
      spec: "{{ _spec | from_yaml }}"
  register: r_openshift_cnv_container
  until: r_openshift_cnv_container is success
  retries: "{{ openshift_cnv_retries }}"
  delay: "{{ openshift_cnv_delay }}"

- name: Wait till Cotainer is running
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    name: "{{ _container.name }}"
    namespace: "{{ openshift_cnv_namespace }}"
  register: r_container_status
  until: r_container_status.resources[0].status.printableStatus | default('') == "Running"
  retries: 30
  delay: 10

- ansible.builtin.set_fact:
    r_openshift_cnv_containers: "{{ r_openshift_cnv_containers + [item] }}"
  loop: "{{ r_openshift_cnv_container.results | list }}"
