= Showroom for OCP

* one or multiple OpenShift users.
* deploy the showroom helm chart https://github.com/rhpds/showroom-deployer/charts/showroom
* If Argo CD is present, it will deploy via Application or ApplicationSet from templated manifests in this role.
* If Argo CD is NOT present, it will deploy the Helm chart.
* deploys to your cluster or the shared cluster

== Are you deploying OpenShift and want Showroom deployed on it?

. Add the ocp4_workload_showroom infra role to your CI:

[source,yaml]
====
infra_workloads:
[ ... all your other infra roles ... ]
- ocp4_workload_showroom   # last
====

== Which "showroom" repo of antora and asciidoc to deploy?

[source,yaml]
====
ocp4_workload_showroom_content_git_repo: "https://github.com/rhpds/showroom_template_default.git"
====

== Enable Bastion Auto-SSH in your env_type/config

. Make sure your env_type/config puts the following values in user_data:

.Example
[source,yaml]
====

- name: Provide installed bastion data
  agnosticd_user_info:
    data:
      bastion_ssh_command: "ssh {{ remote_user }}@bastion.{{ guid }}.{{ azure_root_dns_zone }}"
      bastion_public_hostname: "bastion.{{ guid }}.{{ cluster_dns_zone }}"
      bastion_ssh_user_name: "{{ remote_user }}"
      bastion_ssh_password: "{{ generated_password }}"
====

NOTE: Key based authentication is TODO

== Deploying showroom to the shared cluster

Are you not deploying OpenShift with your config/env_type ?

. Add the following to your config/env-type's post_software.yml.
It needs a bation, afaict.

.`config/env_type/post_software.yml`
[source,yaml]
====
    - name: Deploy Showroom
      when: showroom_deploy_shared_cluster_enable | default(false) | bool
      include_role:
        name: ocp4_workload_showroom
====

. Add the following to AgnosticV

.AgnosticV
[source,yaml]
====
#include /includes/secrets/showroom-shared-410.yaml <1>

# --------------------------------------------------------------------
# Showroom
# --------------------------------------------------------------------
showroom_deploy_shared_cluster_enable: true <2>
ocp4_workload_showroom_content_git_repo: https://github.com/rhpds/showroom_template_default.git
====
