= Showroom for OCP

== Overview

* Deploys to your demo cluster or the shared cluster
** Deploying to your demo's openshift: <<your_openshift>>
** Deploying to our OCP 410 shared OCP Cluster: <<shared_cluster>>
* One or multiple OpenShift users, autodetected.
* Deploy the showroom helm chart https://github.com/rhpds/showroom-deployer/charts/showroom-single-pod
* Supports deployment via OpenShift GitOps (ArgoCD) or a locally installed helm cli (will be installed if not there).
* Supports multiple deployment options
** Just lab content
** Lab content and a Wetty terminal that can be configured to automatically ssh to a bastion
** Lab content and a ttyd terminal - using available images for ocp/rosa/aro/etc

== Usage

.Integrating Showroom into your `config/env_type`:
* Setup your `config/env_type` to support Showroom on OCP <<env_type>>
* Setup auto-login to your bastion <<bastion_auto_ssh>>

[#your_openshift]
== Are you deploying OpenShift and want Showroom deployed on it?

. Add the `ocp4_workload_showroom` infra role to your CI:

[source,yaml]
----
infra_workloads:
[ ... all your other infra roles ... ]
- ocp4_workload_showroom   # last
----

== Which "showroom" repo of antora and asciidoc to deploy?

[source,yaml]
----
ocp4_workload_showroom_content_git_repo: "https://github.com/rhpds/showroom_template_default.git"
# Optional: tag, branch, etc. Default is main.
ocp4_workload_showroom_content_git_repo_ref: main
----

[#env_type]
== Update your `config/env_type` to support showroom on ocp

. Add the following to your config/env-type's post_software.yml.
It needs a bastion, afaict.

.`config/env_type/post_software.yml`
+
.Example
[source,yaml]
----
    - name: Deploy Showroom
      when: showroom_deploy_shared_cluster_enable | default(false) | bool
      include_role:
        name: ocp4_workload_showroom
----

== Selecting the Helm Chart

Regardless of deployment type (below) showroom is always deployed using a Helm Chart whose source can be found at https://github.com/rhpds/showroom-deployer/charts/showroom-single-pod

If newer charts are available than the default version in the workload (`1.0.0`) you will need to specify the version to use. If you want to use another chart (careful: it needs to be compatible) you can pick that, too.
+
.Example
[source,yaml]
----
# Usually don't have to change the chart package URL:
ocp4_workload_showroom_chart_package_url: https://rhpds.github.io/showroom-deployer

# Usually don't have to change the chart name:
ocp4_workload_showroom_deployer_chart_name: showroom-single-pod

# Pick the latest chart available from https://github.com/rhpds/showroom-deployer/releases
ocp4_workload_showroom_deployer_chart_version: "1.0.0"
----

== Picking Deployment Type

If you don't pick a deployment type the default is `helm` cli locally (on the bastion) If `helm` is not available it will be installed first.

To use `ArgoCD` you need to give the right permissions to the system ArgoCd by using the workload and workload options as specified.
+
.Example
[source,yaml]
----
# How to deploy Showroom. Options are `helm` and `argocd`
# For `argocd' ocop4_workload_openshift_gitops must have been deployed first with the following options:
# (OpenShift GitOps 1.10 or newer is preferred but it should work just as well with older versions)
#   ocp4_workload_openshift_gitops_channel: gitops-1.10
#   ocp4_workload_openshift_gitops_setup_cluster_admin: true
#   ocp4_workload_openshift_gitops_update_route_tls: true
#   ocp4_workload_openshift_gitops_rbac_update: true
# Deploying using `argocd` without these options will fail
ocp4_workload_showroom_deployment_type: argocd
----

== Show just lab instructions (whole window)

. To show just lab instructions and no terminal simply set the repo variables and then set the variable to show content only. Any settings for terminals will be ignored.
+
.Example
[source,yaml]
----
ocp4_workload_showroom_content_git_repo: "https://github.com/rhpds/showroom_template_default.git"
ocp4_workload_showroom_content_git_repo_ref: main

ocp4_workload_showroom_content_only: true
----

== Enable Bastion Auto-SSH in your env_type/config

This is only possible for the `wetty` terminal.

. Make sure your env_type/config puts the following values in user_data:
+
.Example
[source,yaml]
----
- name: Provide installed bastion data
  agnosticd_user_info:
    data:
      bastion_ssh_command: "ssh {{ remote_user }}@bastion.{{ guid }}.{{ azure_root_dns_zone }}"
      bastion_public_hostname: "bastion.{{ guid }}.{{ cluster_dns_zone }}"
      bastion_ssh_user_name: "{{ remote_user }}"
      bastion_ssh_password: "{{ generated_password }}"
----

. Set up your config for Wetty and automatic ssh:
+
.Example
[source,yaml]
----
# Select wetty as the terminal type
ocp4_workload_showroom_terminal_type: wetty

# Change the image if you want a different image. Otherwise this line is
# the default
ocp4_workload_showroom_wetty_image: docker.io/wettyoss/wetty:latest

# Set auto login to true:
ocp4_workload_showroom_wetty_ssh_bastion_login: true
----

[NOTE]
====
Key based authentication is TODO
====

== Running terminal in a pod

Showroom also includes the capability to run the terminal in a pod rather than ssh-ing to the bastion. This enables use cases without bastions - and it also enables multi-user showroom deployments.

Multi-user showroom is automatic - if the `user-data.yaml` has individual user data then showroom is automatically deployed in multi-user mode.

=== Available terminal container images

There are a number of container images available to be used as a terminal.

Source code for the images below is available at https://github.com/rhpds/openshift-showroom-terminal-image

* *Base Image:* this image has the base capability to run on OpenShift but it has no tools installed besides the bare-bones Linux tools
** `quay.io/rhpds/openshift-showroom-terminal-baseimage:latest`
* *OCP Image:* this image builds on top of the base image and additionally has all necessary OpenShift tools installed (oc, tkn, kn, ...)
** `quay.io/rhpds/openshift-showroom-terminal-ocp:latest`
* *ROSA Image:* this image builds on top of the OCP image and additionally has `rosa` and `aws` installed.
** `quay.io/rhpds/openshift-showroom-terminal-rosa:latest`
* *ARO Image:* this image builds on top of the OCP image and additionally has `az` (Azure CLI) installed.
** `quay.io/rhpds/openshift-showroom-terminal-aro:latest`

If you need specialized tools it is suggested to start with one of the above and add your tools to the image.

=== Configuring OpenShift Terminal

In order to use the terminal pod set the terminal type to `showroom`, set the and set the image you need.
+
.Example
[source,yaml]
----
# Select showroom as the terminal type
ocp4_workload_showroom_terminal_type: showroom

# Change the image if you want a different image. Otherwise this line is
# the default
ocp4_workload_showroom_terminal_image: quay.io/rhpds/openshift-showroom-terminal-ocp:latest
----

[#shared_cluster]
== Deploying Showroom to the Shared Cluster

. Add the following to AgnosticV

.AgnosticV
[source,yaml]
----
#include /includes/secrets/showroom-shared-410.yaml <1>

# --------------------------------------------------------------------
# Showroom
# --------------------------------------------------------------------
showroom_deploy_shared_cluster_enable: true <2>
ocp4_workload_showroom_content_git_repo: https://github.com/rhpds/showroom_template_default.git
----
