== Deploying OpenShift and want Showroom deployed on it?

. Add the ocp4_workload_showroom infra role to your CI:

[source,yaml]
====
infra_workloads:
[ ... all your other infra roles ... ]
- ocp4_workload_showroom
====

== Which repo of antora and asciidoc to deploy

[source,yaml]
====
ocp4_workload_showroom_content_git_repo: "https://github.com/rhpds/showroom_template_default.git"
====

== Enable Bastion Auto-SSH in your env_type/config

. Make sure your env_type/config puts the following in user_data:

.Example
[source,yaml]
====
    - name: Provide installed bastion data
      agnosticd_user_info:
        data:
          bastion_ssh_command: "ssh {{ remote_user }}@bastion.{{ guid }}.{{ azure_root_dns_zone }}"
          bastion_public_hostname: "bastion.{{ guid }}.{{ cluster_dns_zone }}"
          bastion_ssh_user_name: "{{ remote_user }}"
          bastion_ssh_password: "{{ generated_password }}"

====


== No OCP installed in your env_type/config?

. Add the following to your config's post_software.yml

[source,yaml]
====
    - name: Deploy Showroom
      when: showroom_deploy_shared_cluster_enable | default(false) | bool
      include_role:
        name: ocp4_workload_showroom
====
