= Showroom for OCP

* Deploys to your demo cluster or the shared cluster
** Deploying to your demo's openshift:  <<your_openshift>>
** Deploying to our OCP 410 shared OCP Cluster: <<shared_cluster>>
* one or multiple OpenShift users, autodetected.
* deploy the showroom helm chart https://github.com/rhpds/showroom-deployer/charts/showroom
* Supports deployment via OpenShift GitOps (ArgoCD) or a locally installed helm cli.

.Integrating Showroom into your `config/env_type`
* Setup your `config/env_type` to support Showroom on OCP <<env_type>>
* Setup auto-login to your bastion <<bastion_auto_ssh>>

[#your_openshift]
== Are you deploying OpenShift and want Showroom deployed on it?

. Add the ocp4_workload_showroom infra role to your CI:

[source,yaml]
----
infra_workloads:
[ ... all your other infra roles ... ]
- ocp4_workload_showroom   # last
----

== Which "showroom" repo of antora and asciidoc to deploy?

[source,yaml]
----
ocp4_workload_showroom_content_git_repo: "https://github.com/rhpds/showroom_template_default.git"
----

[#env_type]
== Update your `config/env_type` to support showroom on ocp

. Add the following to your config/env-type's post_software.yml.
It needs a bation, afaict.

.`config/env_type/post_software.yml`
[source,yaml]
----
    - name: Deploy Showroom
      when: showroom_deploy_shared_cluster_enable | default(false) | bool
      include_role:
        name: ocp4_workload_showroom
----

== Picking Deployment Type

If you don't pick a deployment type the default is helm cli locally (on the bastion).
To use ArgoCD you need to give the right permissions to the system ArgoCd by using the workload and
workload options as specified.

[source,yaml]
----
# How to deploy Showroom. Options are `helm` and `argocd`
# For `argocd' ocop4_workload_openshift_gitops must have been deployed first with the following options:
# (OpenShift GitOps 1.10 or newer is preferred but it should work just as well with older versions)
#   ocp4_workload_openshift_gitops_channel: gitops-1.10
#   ocp4_workload_openshift_gitops_setup_cluster_admin: true
#   ocp4_workload_openshift_gitops_update_route_tls: true
#   ocp4_workload_openshift_gitops_rbac_update: true
# Deploying using `argocd` without these options will fail
ocp4_workload_showroom_deployment_type: helm
----

== Enable Bastion Auto-SSH in your env_type/config

. Make sure your env_type/config puts the following values in user_data:

.Example
[source,yaml]
----
- name: Provide installed bastion data
  agnosticd_user_info:
    data:
      bastion_ssh_command: "ssh {{ remote_user }}@bastion.{{ guid }}.{{ azure_root_dns_zone }}"
      bastion_public_hostname: "bastion.{{ guid }}.{{ cluster_dns_zone }}"
      bastion_ssh_user_name: "{{ remote_user }}"
      bastion_ssh_password: "{{ generated_password }}"
----

NOTE: Key based authentication is TODO

[#shared_cluster]
== Deploying Showroom to the Shared Cluster

. Add the following to AgnosticV

.AgnosticV
[source,yaml]
----
#include /includes/secrets/showroom-shared-410.yaml <1>

# --------------------------------------------------------------------
# Showroom
# --------------------------------------------------------------------
showroom_deploy_shared_cluster_enable: true <2>
ocp4_workload_showroom_content_git_repo: https://github.com/rhpds/showroom_template_default.git
----
