---

- name: Step 000 Pre Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step000
    - pre_infrastructure
    - generate_env_keys

  tasks:
    - name: Generate Petname Hostnames for Systems
      when: pet_name_generator_enable | default(false) | bool
      ansible.builtin.include_role:
        name: pet_name_generator

    - name: Pull Latest Windows Image
      when: base_infra_windows_enable | default(false) | bool
      ansible.builtin.include_role:
        name: windows-ami-finder

    - name: "Step 000 Pre Infrastructure"
      ansible.builtin.debug:
        msg: "Step 000 Pre Infrastructure"

# ----------------------------------------------------------------------
# Post-Software Workloads as role
# ----------------------------------------------------------------------
- name: Import pre_infra workloads
  import_playbook: >-
    {{ 'workloads.yml' if pre_infra_workloads is mapping else 'noop.yml' }}
  vars:
    _workload_title_: "Pre Infra"
    _workloads_: "{{ pre_infra_workloads | default([]) }}"

- name: Run host_workloads for pre_infra_workloads
  any_errors_fatal: true
  hosts: localhost
  gather_facts: false
  tags:
    - step005
    - pre_infrastructure
  tasks:
    - name: Include host_workloads for pre_infra
      when:
        - pre_infra_workloads is iterable
        - pre_infra_workloads is not mapping
        - pre_infra_workloads is not string
      vars:
        agnosticd_stage: pre_infra
        host_workloads: "{{ pre_infra_workloads }}"
      ansible.builtin.include_role:
        name: host_workloads
...
