---

- name: Step 00xxxxx software
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step005
    - software

  tasks:

    - name: "Software tasks Started"
      ansible.builtin.debug:
        msg: "Software tasks Started"

# ----------------------------------------------------------------------
# Software Workloads as role
# ----------------------------------------------------------------------
- name: Import Software workloads
  import_playbook: >-
    {{ 'workloads.yml' if software_workloads is mapping else 'noop.yml' }}
  vars:
    _workload_title_: "Software"
    _workloads_: "{{ software_workloads }}"

- name: Run host_workloads for software_workloads
  any_errors_fatal: true
  hosts: all:localhost
  gather_facts: false
  tags:
    - step005
    - software
  tasks:
    - name: Include host_workloads for software
      when:
        - software_workloads is iterable
        - software_workloads is not mapping
        - software_workloads is not string
      vars:
        agnosticd_stage: software
        host_workloads: "{{ software_workloads }}"
      ansible.builtin.include_role:
        name: host_workloads

- name: Software flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:

    - name: "Software checks completed successfully"
      ansible.builtin.debug:
        msg: "Software checks completed successfully"
