== Overview

*ansible-workshop-rhel* is an _AgnosticD Native_ Port of the link:https://github.com/ansible/workshops[Ansible Workshops RHEL Workshop].
The `config`, by design, only supports a single seat (i.e., 1 student), but the codebase includes some appropriate constructs to allow _possible_ future support for a _single deploy, many students deploy.


=== Supported Cloud Providers (`cloud_provider`)

* AWS EC2           # `cloud_provider: ec2`

[NOTE]
====
OpenStack support should be a relatively simple add, requiring the definition of appropriate:

* Networks
* Security Groups (SGs)
* Instances
* Keys

====

=== Pre-requisites

* AWS Credentials

== To Provision an environment

The config supports multiple different configurations; the simplest deployment is recreated below
[source,sh]
----
ansible-playbook ansible/main.yml \
        -e env_type=ansible-workshops-rhel \
        -e @../secrets-aws.yml \
        -e cloud_provider=ec2 \
        -e guid=<YOUR_GUID>
----

== To Destroy, Stop, or Start an environment

The `config` also supports 

* destroy `destroy.yml`   # Deletes a deploy (completely, no recovery option)
* start `start.yml`       # Wakes a stopped deploy
* stop `stop.yml`         # Puts a running deploy to sleep

Substitute the appropriate playbook for `ansible/main.yml` e.g.
[source,sh]
----
ansible-playbook ansible/destroy.yml \
        -e env_type=ansible-workshops-rhel \
        -e @../secrets-aws.yml \
        -e cloud_provider=ec2 \
        -e guid=<YOUR_GUID>
----


=== `secrets-aws.yml`

Goes without saying hopefully to store this outside of your repo.

[source,sh]
---
aws_access_key_id:      <YOUR-AWS-ACCESS-KEY-ID>
aws_secret_access_key:  <YOUR-AWS-SECRET-ACCESS-KEY-ID>

offline_token:           <







=== To Delete an environment
----
`ansible-playbook destroy.yml -e @configs/ansible-workshop-rhel/sample_vars_ec2.yml -e @<YOUR_SECRET_VARS.yml>`

----




