== Overview

*ansible-workshops-rhel* is an _AgnosticD Native_ Port of the link:https://github.com/ansible/workshops[Ansible Workshops RHEL Workshop].
It uses the Ansible Workshop Collection - see `requirements.yml`.
The `config`, by design, only supports a single seat (i.e., 1 student), but the codebase includes some appropriate constructs to allow _possible_ future support for a _single deploy, many students deploy.
The config modifies or avoids updating a number of the traditional workshop files, e.g., the `inventory` and `/etc/hosts` and
can subsequently be stopped and started without breaking the workshop functionality.
It uses DNS for all hosts internally.

=== Additional Information

Created: Tony Kay (tok @ redhat.com)
Date: 2021-09-02

=== Supported Cloud Providers (`cloud_provider`)

* AWS EC2               # `cloud_provider: ec2`
* OpenStack             # `cloud_provider: osp`

[NOTE]
====
By supported it means the above cloud providers support:

* deploy
* stop  # suspend all instances
* start # restart all instances
* destroy

Both on `ec2` and `osp` services restart and DNS takes care of any changes in IP addresses etc. No rewriting of `/etc/hosts`, `/etc/ansible/hosts` or similar is required.
====

=== Pre-requisites

These will all appear, as `yaml` variables, in your *secrets* file, discussed below.

* AWS Credentials or OSP Credentials
* `registry.redhat.io` Credentials - for `ansible-navigator`, `ansible-builder`, and `podman` to work with Execution Environments
* For OSP:
** Satellite, repo, or RHN creds and URL
* Red Hat Network Auth Access Token

** See https://access.redhat.com/articles/3626371#bgenerating-an-access-tokenb-4

[NOTE]
====

In general practice the `-e` vars below would almost certainly be contained in a single file but the key vars are called out in the provisioning commands below.
Future enhancements may include bundling them up into vars files e.g. `sample_vars/rhel-osp.yml` etc.

====
== To Provision an AWS environment

The config supports multiple different configurations; the most straightforward deployment is recreated below
[source,sh]
----
ansible-playbook ansible/main.yml \
        -e env_type=ansible-workshops-rhel \
        -e @../secrets/aws-secrets.yml \
        -e cloud_provider=ec2 \
        -e guid=<YOUR_GUID>
----


== To Provision an OSP environment

The config supports multiple different configurations; the simplest deployment is recreated below
[source,sh]
----
ansible-playbook ansible/main.yml \
        -e env_type=ansible-workshops-rhel \
        -e @~/secrets/secrets-osp-gpte-ansible-workshops.yml \
        -e aap_archive=~/Downloads/aap.tar.gz \
        -e cloud_provider=osp \
        -e cloud_provider=ec2 \
        -e guid=<YOUR_GUID>

----

=== To Delete an environment

This will completely delete your deployment and is irreversible.
Take care, after this you *cannot* recover your work.
Consider saving anything you want to keep:

* Create a git repo and commit and push your work 
* Create a tar archive and `scp` it to your laptop or other location

[source,sh]
----
ansible-playbook ansible/destroy.yml \
        -e env_type=ansible-workshops-rhel \
        -e @../secrets/<CLOUD_PROVIDER>-secrets.yml \
        -e cloud_provider=<YOUR_CLOUD_PROVIDER> \
        -e guid=<YOUR_GUID>
----

== To Stop or Start an environment

The `config` also supports the AWS ec2 `cloud_provider`:

* start `start.yml`       # Wakes a stopped deploy
* stop `stop.yml`         # Puts a running deploy to sleep


Substitute the appropriate `-e ACTION=` `start|stop` 

[NOTE]
====
Currently AWS requires `-e aws_region=<YOUR-AWS-AZ>` and OSP requires `-e osp_project_name=${GUID}-project`.
Both will be engineered out shortly.
====

[source,sh]
----
ansible-playbook ansible/lifecycle.yml \
  -e env_type=ansible-workshops-rhel \
  -e @../secrets/aws-secrets.yml \
  -e cloud_provider=ec2 \
  -e guid=<YOUR-GUID> \
  -e ACTION=start 
----

=== `secrets-aws.yml`

You hopefully will store this file outside of your repo!
Sooner or later, `.gitignore` will fail you, and you will sync your creds - we've all done it... 
This file is specified in the above commands with the line `-e @../secrets/aws-secrets.yml`

[source,yml]
----
aws_access_key_id:      <YOUR-AWS-ACCESS-KEY-ID>
aws_secret_access_key:  <YOUR-AWS-SECRET-ACCESS-KEY-ID>

redhat_username:        username for registry.redhat.com used by podman for EEs
redhat_password:        password for registry.redhat.com used by podman for EEs

offline_token:           Red Hat Network Oauth 2 token, documented with link earlier in the README

----