== Overview

*ansible-workshops-rhel* is an AgnosticD port of the Ansible Workshops

== Supported Cloud Providers (`cloud_provider`)

* OSP (Novello)   # `cloud_provider: osp`

== Review the Env_Type variable file

The link:./sample-vars/rhel-workshop.yml[./sample-vars/rhel-workshop.yml] file contains all the variables you need to define to control the deployment of your environment.

This includes the ability to:

* Change the number of machines deployed
* Changed the operating system image 
* Change the tags carried by any instances
* Change the base packages installed 
* Change/set the `ansible_user` and `remote_user`

These can be over-ridden at `ansible-playbook` runtime via `-e` options or perhaps more compactly by overriding vars in your own var file and invoking via `-e @my_env_vars.yml`

For further information on customizing images consult the link:../../../docs/Creating_a_config.adoc[Creating a Config Guide] 

== Deploying the `ansible-workshops-rhel` config

You can deploy this config by running the following command from the `ansible`
directory. You will have to provide credentials and adjust settings to your own
environment.

`ansible-playbook main.yml -e @configs/ansible-workshops-rhel/./sample-vars/rhel-workshop.yml -e @<YOUR_SECRET_VARS.yml>`


=== Sample Var files

A number of sample var files are provided for both OpenStack and AWS:



=== To Delete an environment
----
`ansible-playbook destroy.yml -e @configs/ansible-workshops-rhel/sample_vars_ec2.yml -e @<YOUR_SECRET_VARS.yml>`
----




