---
# defaults file for ocp4_workload_advanced_developer_suite
ocp4_workload_advanced_developer_suite_tssc_cli_repo: https://github.com/redhat-appstudio/rhtap-cli
ocp4_workload_advanced_developer_suite_tssc_cli_revision: release-1.6

ocp4_workload_advanced_developer_suite_keycloak_namespace: tssc-keycloak
ocp4_workload_advanced_developer_suite_dh_namespace: tssc-dh

ocp4_workload_advanced_developer_suite_tssc_user_base_name: user
ocp4_workload_advanced_developer_suite_tssc_user_password: password
ocp4_workload_advanced_developer_suite_tssc_user_count: "{{ num_users | default(3) }}"

ocp4_workload_advanced_developer_suite_tssc_admin_user: admin
ocp4_workload_advanced_developer_suite_tssc_admin_password: password

ocp4_workload_advanced_developer_suite_tssc_openshift_keycloak_client_secret: password
ocp4_workload_advanced_developer_suite_tssc_dh_keycloak_client_secret: password
ocp4_workload_advanced_developer_suite_tssc_dh_dynamic_plugins_enable:
- disabled: false
  package: ./dynamic-plugins/dist/backstage-community-plugin-catalog-backend-module-keycloak-dynamic