---
become_override: false
ocp_username: admin
silent: false

ocp4_workload_advanced_developer_suite_tssc_cli_repo: https://github.com/redhat-appstudio/rhtap-cli
ocp4_workload_advanced_developer_suite_tssc_cli_revision: release-1.6