= OCP 4 Disconnected Install Lab 

== Config Description

The following config includes:

* One bastion host for installation (ClientVM)
* DNS and other AWS resources for OCP4
* SSH access setup

== Review the Env_Type variable file

* This file link:./env_vars.yml[./env_vars.yml] contains all the variables you need to define to control the deployment of your environment.  These are the deafults.

* Override the defaults for your environment by creating your own myenvironment-variables.yml file, as below.

== Running Ansible Playbook

=== Running Playbook With Environment and Secrets files

You can create yaml files of your desired configs and secrets and execute them:

`ansible-playbook ansible/main.yaml -e @myenvironment-variables.yml  -e@my-secrets.yml`

=== To Delete an environment


Infra stages in config provides:
* Bastion/clientVM
* Utility VM

Software stages in config provide:
* Pull copy of the installer to bastion
* Pull copy of the oc binary to bastion
* Clone ansible for generating the IaaS to bastion
** Go through the IPI created assets and create those?
** Talk to engineering and see what they are creating?
* Install any load balancer to utility VM?
* Install registry to utility VM?

Tear down:
* Delete the HOT
* Delete project

Lab:
* Explain UPI
* Explain OpenStack environment and requirements
* Prep work
* Create IaaS components
* OpenShift install
* OLM install workaround?


Infrastructure components for UPI:
* object storage container for bootstrap ignition file


To prepare an admin host to deploy this config. This has been tested on RHEL 7.7.
sudo subscription-manager register
sudo subscription-manager attach --pool=<yourpool>
sudo subscription-manager repos --disable=* --enable rhel-7-server-optional-rpms \
  --enable rhel-7-server-rpms --enable rhel-7-server-extras-rpms \
  --enable rhel-7-server-ansible-2.7-rpms

sudo yum update -y

sudo yum install python-virtualenv git gcc
virtualenv ~/venv-openstack
source ~/venv-openstack/bin/activate

pip install -r admin_host_requirements.txt

git clone https://github.com/redhat-cop/agnosticd.git
cd agnosticd
git checkout disco-ocp4

Possibly need to:
pip install passlib

Identify what we need to move to agnosticv


User access:
student_name is defined either in sample_vars or from deployer script. This is the account that people will use and will generally match their opentlc ID. lab-user is the default defined in the role

Pre-software:
Student name is set up by the bastion-student-user role
  It generates a password if not defined in student_password
  It creates a user on the bastions
    *We should have it create on all nodes (i.e. utilityVM also)
  It adds student_key to the student_user account on bastion
    *We should have it create on all nodes
    Where do we get student_key from?
  It adds env_authorized_key to the student_user account on bastion
    What is this key actually used for? It gets generated in set_env_authorized_key role
    If this key is dynamically generated per run, can we send it in email?
    What about the guid-infra-key we create in heat template - can we use that instead of this?
    *We should have it create on all nodes
  It enables password auth and passwordless sudo
Nate added tasks to copy priv key, pub key, ssh conf from root > student .ssh directory
  There is probably a better way

Software:
We connect as ansible_user, which is cloud-user for OSP
We install python Openstack modules using pip3
  We need to make this available for all users, or at least student_name
  Add /usr/local/bin to system wide PATH



  

