= ocp4_workload_nexus_operator - Deploy a Nexus Operator and Shared Nexus on OCP4

== Role overview

* This role enables the Nexus Operator on an OpenShift 4 Cluster. It consists of the following playbooks:
** Playbook: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an
 environment for the workload deployment.
*** Debug task will print out: `pre_workload Tasks completed successfully.`

** Playbook: link:./tasks/workload.yml[workload.yml] - Used to deploy the Nexus Operator and then deploy a shared Nexus instance
*** Debug task will print out: `workload Tasks completed successfully.`

** Playbook: link:./tasks/post_workload.yml[post_workload.yml] - Used to
 configure the workload after deployment
*** This role doesn't do anything here
*** Debug task will print out: `post_workload Tasks completed successfully.`

** Playbook: link:./tasks/remove_workload.yml[remove_workload.yml] - Used to
 delete the workload
*** This role removes the shared Nexus and Nexus operator from OCP 4. This role does *not* remove the project - there may be other items in it.
*** Debug task will print out: `remove_workload Tasks completed successfully.`

== Review the defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you need to define to control the deployment of your workload.
* The variable *ocp_username* is mandatory to assign the workload to the correct OpenShift user.
* A variable *silent=True* can be passed to suppress debug messages.
* You can modify any of these default values by adding `-e "variable_name=variable_value"` to the command line

== Nexus Custom Resource

The operator uses a custom resource *Nexus.gpte.opentlc.com/v1alpha1* to set the quota for all users in the cluster. Variables are in defaults/main.yaml and can be overwritten by setting them globally.

[source,yaml]
----
apiVersion: gpte.opentlc.com/v1alpha1
kind: Nexus
metadata:
  name: "{{ _nexus_name }}"
  namespace: "{{ _nexus_operator_project }}"
spec:
  nexusVolumeSize: "{{ _nexus_volume_size }}"
  nexusSsl: "{{ _nexus_ssl }}"
  nexusImage: "{{ _nexus_image }}"
  nexusImageTag: "{{ _nexus_image_tag }}"
  nexusCpuRequest: "{{ _nexus_cpu_request }}"
  nexusCpuLimit: "{{ _nexus_cpu_limit }}"
  nexusMemoryRequest: "{{ _nexus_memory_request }}"
  nexusMemoryLimit: "{{ _nexus_memory_limit }}"
----

=== Deploy a Workload with the `ocp-workload` playbook [Mostly for testing]

----
TARGET_HOST="bastion.na4.openshift.opentlc.com"
OCP_USERNAME="wkulhane-redhat.com"
WORKLOAD="ocp4_workload_nexus_operator"
GUID=1001

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=ec2-user" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"ACTION=create"
----

=== To Delete an environment

----
TARGET_HOST="bastion.na4.openshift.opentlc.com"
OCP_USERNAME="wkulhane-redhat.com"
WORKLOAD="ocp4_workload_nexus_operator"
GUID=1002

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=ec2-user" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"guid=${GUID}" \
    -e"ACTION=remove"
----
