---
# Implement your Workload deployment tasks here

- name: Deploy hub cluster via kcli
  ansible.builtin.shell:
    cmd: kcli create cluster openshift --pf hub.yml -P force=true &> /root/kcli-hub-deploy.log
  args:
    chdir: /root/
  when: again is undefined

- name: Ensure we can login into the hub cluster with the generated credentials
  ansible.builtin.shell:
    cmd: oc login https://{{ lab_api_host }} -u admin -p {{ strong_admin_password }}  --insecure-skip-tls-verify=true > /dev/null
  register: result
  until: result.rc == 0
  retries: 120
  delay: 60
  when: again is undefined 

- name: Ensure kubernetes manifests are downloaded
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.destination }}"
    mode: "{{ item.mode }}"
  # yamllint disable rule:line-length
  with_items:
    - {url: "https://raw.githubusercontent.com/{{ repo_user }}/5g-ran-deployments-on-ocp-lab/{{ lab_version }}/lab-materials/lab-env-data/hub-cluster/argocd-patch.json", destination: "/tmp/argocd-openshift-gitops-patch.json", mode: "0644"}
    - {url: "https://raw.githubusercontent.com/{{ repo_user }}/5g-ran-deployments-on-ocp-lab/{{ lab_version }}/lab-materials/lab-env-data/hub-cluster/hub-operators-argoapps.yaml", destination: "/tmp/hub-operators-argoapps.yaml", mode: "0644"}
    - {url: "https://raw.githubusercontent.com/{{ repo_user }}/5g-ran-deployments-on-ocp-lab/{{ lab_version }}/lab-materials/lab-env-data/hub-cluster/sno1-argoapp.yaml", destination: "/tmp/sno1-argoapp.yaml", mode: "0644"}
    - {url: "https://raw.githubusercontent.com/{{ repo_user }}/5g-ran-deployments-on-ocp-lab/{{ lab_version }}/lab-materials/lab-env-data/hub-cluster/argocd-clusterrolebinding.yaml", destination: "/tmp/argocd-clusterrolebinding.yaml", mode: "0644"}
  # yamllint enable rule:line-length

- name: Ensure we have the kubeconfig file for the hub cluster copied in the bastion
  ansible.builtin.copy:
    src: /root/.kcli/clusters/hub/auth/kubeconfig
    dest: /root/hub-kubeconfig
    remote_src: true

- name: Remove kubeadmin user
  kubernetes.core.k8s:
    kubeconfig: /root/hub-kubeconfig
    state: absent
    api_version: v1
    kind: Secret
    namespace: kube-system
    name: kubeadmin

- name: Ensure ArgoCD instance is patched for ZTP support
  kubernetes.core.k8s:
    kubeconfig: /root/hub-kubeconfig
    api_version: argoproj.io/v1alpha1
    kind: ArgoCD
    name: openshift-gitops
    namespace: openshift-gitops
    state: patched
    src: /tmp/argocd-openshift-gitops-patch.json
    merge_type: merge
  register: result
  until: result.failed != true
  retries: 5
  delay: 60

- name: Apply ArgoCD ClusterRoleBinding manifest to the cluster
  kubernetes.core.k8s:
    kubeconfig: /root/hub-kubeconfig
    state: present
    src: /tmp/argocd-clusterrolebinding.yaml
  register: result
  until: result.failed != true
  retries: 5
  delay: 60

- name: Wait until ArgoCD Pods are ready
  kubernetes.core.k8s_info:
    kubeconfig: /root/hub-kubeconfig
    kind: Pod
    namespace: openshift-gitops
    label_selectors:
      - app.kubernetes.io/name = openshift-gitops-repo-server
  register: result
  until:
    - result.resources[0].status.phase == "Running"
    - result.resources[0].status.containerStatuses[0].ready == true
  retries: 25
  delay: 5

- name: Apply HUB Cluster Operators APPs
  kubernetes.core.k8s:
    kubeconfig: /root/hub-kubeconfig
    state: present
    src: /tmp/hub-operators-argoapps.yaml
  register: result
  until: result.failed != true
  retries: 5
  delay: 60

- name: Wait until LVMCluster is ready
  kubernetes.core.k8s_info:
    kubeconfig: /root/hub-kubeconfig
    api_version: lvm.topolvm.io/v1alpha1
    kind: LVMCluster
    name: lvmcluster
    namespace: openshift-storage
  register: lvmcluster
  retries: 60
  delay: 60
  until:
    - lvmcluster is defined
    - lvmcluster.resources | length > 0
    - lvmcluster.resources[0].status.state == "Ready"

- name: Ensure LVMCLuster storageclass is set as default
  kubernetes.core.k8s:
    kubeconfig: /root/hub-kubeconfig
    state: patched
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: lvms-vg1
    definition:
      metadata:
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
  register: result
  until: result.failed != true
  retries: 5
  delay: 60

- name: Wait until ArgoCD APP for HUB Cluster Operators deployment is ready
  kubernetes.core.k8s_info:
    kubeconfig: /root/hub-kubeconfig
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: hub-operators-deployment
    namespace: openshift-gitops
  register: argocd_app_hub_operators
  retries: 100
  delay: 10
  until:
    - argocd_app_hub_operators is defined
    - argocd_app_hub_operators.resources | length > 0
    - argocd_app_hub_operators.resources[0].status is defined
    - argocd_app_hub_operators.resources[0].status.health.status == "Healthy"
    - argocd_app_hub_operators.resources[0].status.sync.status == "Synced"

- name: Wait until ArgoCD APP for HUB Cluster Operators config is ready
  kubernetes.core.k8s_info:
    kubeconfig: /root/hub-kubeconfig
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: hub-operators-config
    namespace: openshift-gitops
  register: argocd_app_hub_operators
  retries: 100
  delay: 10
  until:
    - argocd_app_hub_operators is defined
    - argocd_app_hub_operators.resources | length > 0
    - argocd_app_hub_operators.resources[0].status is defined
    - argocd_app_hub_operators.resources[0].status.health.status == "Healthy"
    - argocd_app_hub_operators.resources[0].status.sync.status == "Synced"

- name: Wait until MultiClusterHub is ready
  kubernetes.core.k8s_info:
    kubeconfig: /root/hub-kubeconfig
    api_version: operator.open-cluster-management.io/v1
    kind: MultiClusterHub
    name: multiclusterhub
    namespace: open-cluster-management
  register: rhacm_multiclusterhub
  retries: 100
  delay: 10
  until:
    - rhacm_multiclusterhub is defined
    - rhacm_multiclusterhub.resources | length > 0
    - rhacm_multiclusterhub.resources[0].status is defined
    - rhacm_multiclusterhub.resources[0].status.phase is defined
    - rhacm_multiclusterhub.resources[0].status.phase == "Running"

- name: Wait until MultiClusterEngine is ready
  kubernetes.core.k8s_info:
    kubeconfig: /root/hub-kubeconfig
    api_version: multicluster.openshift.io/v1
    kind: MultiClusterEngine
    name: multiclusterengine
    namespace: multicluster-engine
  register: mce_multiclusterengine
  retries: 60
  delay: 10
  until:
    - mce_multiclusterengine is defined
    - mce_multiclusterengine.resources | length > 0
    - mce_multiclusterengine.resources[0].status is defined
    - mce_multiclusterengine.resources[0].status.phase is defined
    - mce_multiclusterengine.resources[0].status.phase == "Available"

- name: Ensure SNO ssh key is downloaded
  ansible.builtin.get_url:
    # yamllint disable rule:line-length
    url: "http://infra.5g-deployment.lab:3000/student/5g-ran-deployments-on-ocp-lab/raw/branch/{{ lab_version }}/lab-materials/lab-env-data/hypervisor/ssh-key"
    # yamllint enable rule:line-length
    dest: "/root/.ssh/snokey"
    mode: "0400"

- name: Apply SNO Seed Cluster Deployment APPs
  kubernetes.core.k8s:
    kubeconfig: /root/hub-kubeconfig
    state: present
    src: /tmp/sno1-argoapp.yaml
  register: result
  until: result.failed != true
  retries: 5
  delay: 60

- name: Wait until ArgoCD APP for SNO Seed Cluster deployment is ready
  kubernetes.core.k8s_info:
    kubeconfig: /root/hub-kubeconfig
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: sno-seed-deployment
    namespace: openshift-gitops
  register: argocd_app_snoseed_deployment
  retries: 60
  delay: 10
  until:
    - argocd_app_snoseed_deployment is defined
    - argocd_app_snoseed_deployment.resources | length > 0
    - argocd_app_snoseed_deployment.resources[0].status is defined
    - argocd_app_snoseed_deployment.resources[0].status.health.status == "Healthy"
    - argocd_app_snoseed_deployment.resources[0].status.sync.status == "Synced"

- name: Wait for SNO Seed cluster to start deploying
  kubernetes.core.k8s_info:
    kubeconfig: /root/hub-kubeconfig
    api_version: extensions.hive.openshift.io/v1beta1
    kind: AgentClusterInstall
    name: sno-seed
    namespace: sno-seed
  register: snoseed_agentclusterinstall
  retries: 20
  delay: 60
  until:
    - snoseed_agentclusterinstall is defined
    - snoseed_agentclusterinstall.resources | length > 0
    - snoseed_agentclusterinstall.resources[0].status is defined
    # yamllint disable rule:line-length
    - snoseed_agentclusterinstall.resources[0].status.debugInfo.state == "preparing-for-installation" or snoseed_agentclusterinstall.resources[0].status.debugInfo.state == "adding-hosts"
    # yamllint enable rule:line-length

- name: Wait for SNO Seed cluster to be deployed
  kubernetes.core.k8s_info:
    kubeconfig: /root/hub-kubeconfig
    api_version: extensions.hive.openshift.io/v1beta1
    kind: AgentClusterInstall
    name: sno-seed
    namespace: sno-seed
  register: snoseed_agentclusterinstall
  retries: 120
  delay: 60
  until:
    - snoseed_agentclusterinstall is defined
    - snoseed_agentclusterinstall.resources | length > 0
    - snoseed_agentclusterinstall.resources[0].status is defined
    - snoseed_agentclusterinstall.resources[0].status.debugInfo.state == "adding-hosts"

- name: Extract SNO Seed kubeconfig
  ansible.builtin.shell:
    cmd: oc --kubeconfig /root/hub-kubeconfig -n sno-seed extract secret/sno-seed-admin-kubeconfig --to=- > /root/seed-cluster-kubeconfig
  register: result
  retries: 3
  delay: 10

- name: Ensure kubernetes manifests for seed cluster are downloaded
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.destination }}"
    mode: "{{ item.mode }}"
  # yamllint disable rule:line-length
  with_items:
    - {url: "https://raw.githubusercontent.com/{{ repo_user }}/5g-ran-deployments-on-ocp-lab/{{ lab_version }}/lab-materials/sno-config/02_oadp_deployment.yaml", destination: "/tmp/02_oadp_deployment.yaml", mode: "0644"}
    - {url: "https://raw.githubusercontent.com/{{ repo_user }}/5g-ran-deployments-on-ocp-lab/{{ lab_version }}/lab-materials/sno-config/02_lca_deployment.yaml", destination: "/tmp/02_lca_deployment.yaml", mode: "0644"}
    - {url: "https://raw.githubusercontent.com/{{ repo_user }}/5g-ran-deployments-on-ocp-lab/{{ lab_version }}/lab-materials/sno-config/02_sriov_deployment.yaml", destination: "/tmp/02_sriov_deployment.yaml", mode: "0644"}
    - {url: "https://raw.githubusercontent.com/{{ repo_user }}/5g-ran-deployments-on-ocp-lab/{{ lab_version }}/lab-materials/sno-config/02_lvms_deployment.yaml", destination: "/tmp/02_lvms_deployment.yaml", mode: "0644"}
    - {url: "https://raw.githubusercontent.com/{{ repo_user }}/5g-ran-deployments-on-ocp-lab/{{ lab_version }}/lab-materials/sno-config/03_sriovoperatorconfig.yaml", destination: "/tmp/03_sriovoperatorconfig.yaml", mode: "0644"}
    - {url: "https://raw.githubusercontent.com/{{ repo_user }}/5g-ran-deployments-on-ocp-lab/{{ lab_version }}/lab-materials/sno-config/03_sriov-nw-du-netdev.yaml", destination: "/tmp/03_sriov-nw-du-netdev.yaml", mode: "0644"}
    - {url: "https://raw.githubusercontent.com/{{ repo_user }}/5g-ran-deployments-on-ocp-lab/{{ lab_version }}/lab-materials/sno-config/03_sriov-nw-du-vfio.yaml", destination: "/tmp/03_sriov-nw-du-vfio.yaml", mode: "0644"}
    - {url: "https://raw.githubusercontent.com/{{ repo_user }}/5g-ran-deployments-on-ocp-lab/{{ lab_version }}/lab-materials/sno-config/04_performance_profile.yaml", destination: "/tmp/04_performance_profile.yaml", mode: "0644"}
    - {url: "https://raw.githubusercontent.com/{{ repo_user }}/5g-ran-deployments-on-ocp-lab/{{ lab_version }}/lab-materials/sno-config/05_TunedPerformancePatch.yaml", destination: "/tmp/05_TunedPerformancePatch.yaml", mode: "0644"}
  # yamllint enable rule:line-length

- name: Install LCA, OADP, LVMS and SR-IOV operators in SNO Seed
  kubernetes.core.k8s:
    kubeconfig: /root/seed-cluster-kubeconfig
    state: present
    src: "{{ item }}"
  with_items:
    - /tmp/02_lca_deployment.yaml
    - /tmp/02_oadp_deployment.yaml
    - /tmp/02_lvms_deployment.yaml
    - /tmp/02_sriov_deployment.yaml
  register: result
  until: result.failed != true
  retries: 12
  delay: 10

- name: Wait until OADP is installed
  kubernetes.core.k8s_info:
    kubeconfig: /root/seed-cluster-kubeconfig
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    label_selectors:
      - "operators.coreos.com/redhat-oadp-operator.openshift-adp"
    namespace: openshift-adp
  register: oadpoperator
  retries: 12
  delay: 10
  until:
    - oadpoperator is defined
    - oadpoperator.resources | length > 0
    - oadpoperator.resources[0].status.phase == "Succeeded"

- name: Wait until LCA is installed
  kubernetes.core.k8s_info:
    kubeconfig: /root/seed-cluster-kubeconfig
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    label_selectors:
      - "operators.coreos.com/lifecycle-agent.openshift-lifecycle-agent"
    namespace: openshift-lifecycle-agent
  register: lcaoperator
  retries: 12
  delay: 10
  until:
    - lcaoperator is defined
    - lcaoperator.resources | length > 0
    - lcaoperator.resources[0].status.phase == "Succeeded"

- name: Wait until LVMS is ready
  kubernetes.core.k8s_info:
    kubeconfig: /root/seed-cluster-kubeconfig
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    label_selectors:
      - "operators.coreos.com/lvms-operator.openshift-storage"
    namespace: openshift-storage
  register: lvmsoperator
  retries: 12
  delay: 10
  until:
    - lvmsoperator is defined
    - lvmsoperator.resources | length > 0
    - lvmsoperator.resources[0].status.phase == "Succeeded"

- name: Wait until SR-IOV is ready
  kubernetes.core.k8s_info:
    kubeconfig: /root/seed-cluster-kubeconfig
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    label_selectors:
      - "operators.coreos.com/sriov-network-operator.openshift-sriov-network-operator"
    namespace: openshift-sriov-network-operator
  register: sriovoperator
  retries: 12
  delay: 10
  until:
    - sriovoperator is defined
    - sriovoperator.resources | length > 0
    - sriovoperator.resources[0].status.phase == "Succeeded"

- name: Configure SR-IOV in SNO Seed
  kubernetes.core.k8s:
    kubeconfig: /root/seed-cluster-kubeconfig
    state: present
    src: "{{ item }}"
  with_items:
    - /tmp/03_sriovoperatorconfig.yaml
    - /tmp/03_sriov-nw-du-netdev.yaml
    - /tmp/03_sriov-nw-du-vfio.yaml
  register: result
  until: result.failed != true
  retries: 12
  delay: 10

- name: Wait until SR-IOV is configured
  kubernetes.core.k8s_info:
    kubeconfig: /root/seed-cluster-kubeconfig
    api_version: v1
    kind: Node
    name: openshift-master-0
  register: sriovconfigured
  retries: 6
  delay: 30
  until:
    - sriovconfigured is defined
    - sriovconfigured.resources | length > 0
    - sriovconfigured.resources[0].status.allocatable|json_query('\"openshift.io/virt-enp4s0\"') == "2"

- name: Apply performance tuning to SNO Seed
  kubernetes.core.k8s:
    kubeconfig: /root/seed-cluster-kubeconfig
    state: present
    src: "{{ item }}"
  with_items:
    - /tmp/04_performance_profile.yaml
    - /tmp/05_TunedPerformancePatch.yaml
  register: result
  until: result.failed != true
  retries: 12
  delay: 10

- name: Wait Performance Profile is applied
  kubernetes.core.k8s_info:
    kubeconfig: /root/seed-cluster-kubeconfig
    api_version: v1
    kind: PerformanceProfile
    name: openshift-node-performance-profile
  register: performance
  retries: 6
  delay: 30
  until:
    - performance is defined
    - performance.resources | length > 0
    - "{{ performance.resources[0].status.conditions|json_query('[?type==`Available`].status') }}"

- name: Rebooting
  debug:
    msg: "The node is about to be rebooted to apply performance tuning"

# Leave this as the last task in the playbook.
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool
