:config: ansible-tower-implementation 
:author3: Mitesh The Mouse <mitsharm@redhat.com>
:author1: Prakhar Srivastava <psrivast@redhat.com>
:author2: Tony Kay <tok@redhat.com>
:team: GPTE DevOps & Automation

 
Config: {config}
===============

The {config} config deploys bastion, tower, git and server nodes. Deployment can be done on OpenStack (Novello) and AWS cloud providers.


Requirements
------------

Following are the requirements:

. All required yum repositories or subscription must be available. 
. AWS credentials are required for AWS deployment.
. OSP credentials are required for Openstack deployment.
 

Config Variables
----------------

* Cloud specfic settings related variables.
[cols="4",options="header"]
|====
|*Variable* | *State* |*Description*
| env_type: ansible-tower-implementation  |Required | Name of the config
| output_dir: /tmp/workdir |Required | Writable working directory
| email: email_id@example.com |Required |  User email ID for notifications
| guid: defaultguid | Reqired |Unique identifier
| cloud_provider: "String" |Required | Cloud Provider ec2/osp 
|====

    
* Example variables for Openstack(Novello)

. Sample of sample_vars_osp.yml
+
[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible
[user@desktop ~]$ cat ./configs/ansible-tower-implementation /sample_vars_osp.yml
----
for reference  link:sample_vars_osp.yml[click]  here.

. Sample of secrets.yml for Openstack(Novello)
+
[source=text]
----
[user@desktop ~]$ cat ~/secrets_osp.yml
osp_auth_url: http://x.x.x.x:5000/v3
osp_auth_username: admin
osp_auth_password: "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
osp_auth_project_domain: "default"
osp_auth_user_domain: "default"
ddns_key_name: admin_host
ddns_key_secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
admin_user: admin
osp_cluster_dns_zone: dev.osp.opentlc.com
own_repo_path: http://localrepopath/to/repo
tower_version: 3.6.0-1
----

* Example variables for AWS

. Sample of sample_vars_ec2.yml
+
[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible
[user@desktop ~]$ cat ./configs/ansible-tower-implementation /sample_vars_ec2.yml
----
for reference  link:sample_vars_ec2.yml[click]  here.

. Sample of secrets_ec2.yml for AWS.
+
[source=text]
----
[user@desktop ~]$ cat ~/secrets.yml
aws_access_key_id: xxxxxxxxxxxxxxxx
aws_secret_access_key: xxxxxxxxxxxxxxxxxx
own_repo_path: http://localrepopath/to/repo
----


Example to run config 
---------------------

. How to use config.
+
[source=sh]
----
[user@desktop ~]$ cd agnosticd/ansible
[user@desktop ~]$ ansible-playbook  main.yml \
  -e @./configs/ansible-tower-implementation/sample_vars_osp.yml \
  -e @~/secrets_osp.yml \
  -e guid=defaultguid  \
----

. How to destroy environment 
+
[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible

[user@desktop ~]$ ansible-playbook  ./configs/ansible-tower-implementation/destroy.yml \
  -e @./configs/ansible-tower-implementation/sample_vars_osp.yml \
  -e @~/secrets_osp.yml \
  -e guid=defaultguid 
----


Author Information
------------------

* Author/owner:
** {author1}

* Alternative Contacts:
** {author2}
** {author3}

* Team:
** {team}