== Overview

*binder-aap2-default* is a _default_ binder designed to work in tandem with any `base-aap2-*` config.
It is effectively a "One Role*" binder using the collection `infra.controller_configuration`


== Usage

You will need Automation controller credentials to use this binder in a dictionary called `aap_auth`

[source,yaml]
----
aap_auth:
  controller_host: <URL>
  controller_username: <USERNAME> # defaults to 'admin'
  controller_password: <PASSWORD>
  controller_verify_ssl: <BOOL> # defaults to true
----

Everything happens in `software.yml`

. Get a token
. Run the `infra.controller_configuration.dispatch` role

[source,yaml]
----

    - name: Configure AAP2 Controller and Hub with resources
      when: controller_configuration_dispatcher_roles is defined
      block:

        - name: Create a new AAP2 Auth token using controller username/password
          awx.awx.token:
            description: Creating token to configure AAP2 resources
            scope: write
            state: present

        - name: Configure AAP2 Controller and Hub
          ansible.builtin.import_role:
            name: infra.controller_configuration.dispatch
----

== Roles

There is little point in documenting the infra.controller_configuration.dispatch role, as it is link:https://github.com/redhat-cop/controller_configuration/tree/devel/roles/dispatch[fully documented here]

However in short it consumes a dictionary of `infra.controller_configuration` roles to run and dispatches to them the appropriate dictionary. Be aware ordering can be important ie you can't create a `job_template` before you have created a `project` to point to.

. Sample `controller_configuration_dispatcher_roles` dictionary
[source,yaml]
----
controller_configuration_dispatcher_roles:

  - role: settings
    var: controller_settings
    tags: settings

  - role: organizations
    var: controller_organizations
    tags: organizations

  - role: projects
    var: controller_projects
    tags: projects
----

. Sample `controller_projects` dictionary
[source,yaml]
----
controller_projects:

  - name: "GitLab playbook-rhaap"
    scm_url: "https://gitlab.com/ansible-ssa/playbook-rhaap.git"
    organization: Default
    scm_type: git
    scm_branch: "{{ project_version | default('main') }}"
    scm_update_on_launch: true
    scm_delete_on_update: true
    state: "{{ controller_state | default('present') }}"

  - name: "GitLab playbook-lamp"
    scm_url: "https://gitlab.com/ansible-ssa/playbook-lamp.git"
    organization: Default
    scm_type: git
    scm_branch: "{{ project_version | default('main') }}"
    scm_update_on_launch: true
    scm_delete_on_update: true
    state: "{{ controller_state | default('present') }}"
----





