#!/bin/bash

for context in hub spoke1 spoke2
do
  if [ "0${context}" != "0$(oc config get-contexts ${context} -o name 2>/dev/null)" ]
  then
    echo "[ERROR] Context ${context} doesn't exist. Review the instructions"
    exit 1
  fi
done

echo "[OK] Contexts hub, spoke1 and spoke2 detected"

HUB_URL=$(oc config get-contexts hub --no-headers=true | sed "s/  */@/g" | awk -F "@" '{print $3}')
SPOKE1_URL=$(oc config get-contexts spoke1 --no-headers=true | sed "s/  */@/g" | awk -F "@" '{print $3}')
SPOKE2_URL=$(oc config get-contexts spoke2 --no-headers=true | sed "s/  */@/g" | awk -F "@" '{print $3}')

if [ $(echo $HUB_URL $SPOKE1_URL $SPOKE2_URL | tr " " "\n" | sort -u | wc -l) -ne 3 ]
then
  echo "[ERROR] Duplicated API Endpoints found in your contexts, make sure you have used the correct api endpoint for each cluster"
  exit 1
fi

echo "[OK] Contexts hub, spoke1 and spoke2 use different api endpoints"

for context in hub spoke1 spoke2
do
  if [ "0namespace/default" != "0$(oc --context ${context} get namespace default -o name)" ]
  then
    echo "[ERROR] Context ${context} is not working. Review you've provided correct credentials"
  fi
done

echo "[OK] All checks passed"
