= Multi-region-tower

This config deploys towers in multiple regions.


. You specify the target regions using the `target_regions` variable, for example:
+
[source,yaml]
----
target_regions:
  - region: us-east-1
    stack: default
    name: na
    vpc_cidr: 10.1.0.0/16
    subnet_cidr: 10.1.0.0/24
  - region: eu-central-1
    stack: worker.j2
    name: emea
    vpc_cidr: 10.1.0.0/16
    subnet_cidr: 10.1.0.0/24
  - region: ap-southeast-1
    stack: worker.j2
    name: apac
    vpc_cidr: 10.1.0.0/16
    subnet_cidr: 10.1.0.0/24
----
+
This will deploy the same stack (default) in the specified regions. The default CloudFormation template is used: either in the config dir, or the default cloudformation template if there is none in the config dir.
+
If you want to use a specific template in a region, just specify the file name and store the template in `configs/multi-region-example/files/cloud_providers/FILENAME`.
+
. In this config the first region specified under target_regions dictionary will have master cluster installed which will include tower nodes and database node.
. Respective other regions next specified list under target_regions will be used to create Isolated group i.e. "name: emea" = [isolated_group_emea ] and worker nodes will be added. 

Have a look at link:sample_vars.yml[] too for example vars.
