---
ocp4_workload_create_rwx_volume_enable: false

ocp4_workload_create_rwx_volume_silent: "{{ silent | default(false) }}"

ocp4_workload_create_rwx_volume_virtualenv_path: /opt/virtualenvs/k8s

ocp4_workload_create_rwx_volume_region: "{{ aws_region }}"
ocp4_workload_create_rwx_volume_access_key_id: "{{ aws_access_key_id }}"
ocp4_workload_create_rwx_volume_secret_access_key: "{{ aws_secret_access_key }}"

ocp4_workload_create_rwx_volume_installer_root_url: https://mirror.openshift.com/pub/openshift-v4/clients
ocp4_workload_create_rwx_volume_helm_version: 3.19.5

ocp4_workload_create_rwx_volume_s3_bucket_name: "s3-bucket-{{ guid }}-for-rwx"

ocp4_workload_create_rwx_volume_helm_s3_driver_repo_url: https://awslabs.github.io/mountpoint-s3-csi-driver

ocp4_workload_create_rwx_volume_pv_storage: 1200Gi
ocp4_workload_create_rwx_volume_pv_name: s3-volume-pv
