#!/bin/bash

# copy web certs
cp --preserve=mode,timestamps -r certs /etc/httpd

# copy ca cert
cp --preserve=mode,timestamps certs/example-ca-cert.pem /etc/pki/ca-trust/source/anchors

update-ca-trust

mkdir /etc/crypto-override
echo 0 >/etc/crypto-override/fips_enabled

if ! grep -q crypto2 /etc/hosts ; then
cat <<EOF >>/etc/hosts
127.0.0.2   crypto2-tls11.example.com
127.0.0.3   crypto2-sha1.example.com
127.0.0.4   crypto2-ed25519.example.com
EOF
fi

# semanage ports
semanage port -a -t http_port_t -p tcp 1443
semanage port -a -t http_port_t -p tcp 2443
semanage port -a -t http_port_t -p tcp 3443

# httpd override mount
mkdir -p /etc/systemd/system/httpd.service.d
cp --preserve=mode,timestamps override.conf /etc/systemd/system/httpd.service.d
systemctl daemon-reload

# httpd configuration
cp --preserve=mode,timestamps crypto2.conf /etc/httpd/conf.d

# provide rudimentary index.html
echo WORKS! >/var/www/html/index.html

# httpd enable and start
systemctl enable httpd.service
systemctl restart httpd.service
