= satellite-multi-region

*This config deploys satellite and capsule servers in multiple regions.*


== Following are the important variable which needs to be defined 

* You specify the target regions using the `target_regions` variable, for example:
+
[source,yaml]
----
target_regions:
  - region: ap-southeast-2
    stack: default
    name: apac
    vpc_cidr: 10.1.0.0/16
    subnet_cidr: 10.1.0.0/24
  - region: ap-southeast-1
    stack: capsule.j2
    name: emea
    vpc_cidr: 10.2.0.0/16
    subnet_cidr: 10.2.0.0/24
----

* List of variables of config
|===
| env_type: satellite-multi-region | Name of the config
| output_dir: /tmp/workdir         | Writable working scratch directory
| email: satellite_multi_region@example.com |  User info for notifications
| guid: defaultguid | Unique identifier
| cloud_provider: ec2         | Which AgnosticD Cloud Provider to use
|===


* List of variables of satellite installation  (for more details refer role Readme file)
|===
| satellite_version: 6.4           | Satellite version to install
|===

* List of variables for satellite configuration (for more details refer role Readme file)

|===
| satellite_admin: admin | Satellite primary user name
| satellite_admin_password: xxxxxxxx | Satellite primary password
| org: gpte | Organization name
| org_label: gpte | Organization label
| org_description: "Global Partner Training and Enablement" | |Organization description
| manifest_file: /path/to/manifests.zip | Local path of manifest file
| content_view_name: "capsule server content" | Content view name
| activation_key_name: "capsule_activation_key" | Activation key name
| life_cycle_env_name: "Library" | Life cycle name
|===

* Below is way to writte repo list which can be enabled and synchronized.

+
[source,yaml]
----
satellite_repository:
  - organization: "{{org}}"
    product: 'Red Hat Enterprise Linux Server' 
    basearch: 'x86_64'
    releasever:  '7Server'
    name: 'Red Hat Enterprise Linux 7 Server (RPMs)' 

  - organization: "{{org}}"
    product: 'Red Hat Satellite Capsule' 
    basearch: 'x86_64'
    name: 'Red Hat Satellite Capsule 6.4 (for RHEL 7 Server) (RPMs)'
----

=== Example

* To run satellite-multi-region config

[source,text]
----
ansible-playbook  main.yml \
  -e @./configs/satellite-multi-region/sample_vars.yml \
  -e @~/secrets.yml \
  -e guid=defaultguid  \
  -e satellite_admin=admin \
  -e 'satellite_admin_password=password' \
  -e manifest_file=/path/to/manifest_satellite-vm_1.zip

----

* To destroy satellite-multi-region environment

[source,text]
----
ansible-playbook  ./configs/satellite-multi-region/destroy.yml \
  -e @./configs/satellite-multi-region/sample_vars.yml \
  -e @~/secrets.yml \
  -e guid=defaultguid 

----

* To stop environment
[source,text]
----
ansible-playbook  ./configs/satellite-multi-region/stop.yml \
  -e @./configs/satellite-multi-region/sample_vars.yml \
  -e @~/secrets.yml \
  -e guid=defaultguid  

----

* To start environment

[source,text]
----
ansible-playbook  ./configs/satellite-multi-region/start.yml \
  -e @./configs/satellite-multi-region/sample_vars.yml \
  -e @~/secrets.yml \
  -e guid=defaultguid 

----

* Have a look at link:sample_vars.yml[] too for example vars.
