:config: satellite-multi-region
:author: GPTE Team
:tag1: install_satellite
:tag2: configure_satellite


Config: {config}
===============

This config deploys bastion, satellite and multi region capsules.

Requirements
------------

Following are the requirements:

. Yum repositories are required for bastion and satellite host.
. Aws credentials are required. 
 

Config Variables
----------------

* Cloud specfic settings related variables.

|===
|*Variable* | *State* |*Description*
| env_type: satellite-multi-region |Required | Name of the config
| output_dir: /tmp/workdir |Required | Writable working scratch directory
| email: satellite_multi_region@example.com |Required |  User info for notifications
| guid: defaultguid | Reqired |Unique identifier
| cloud_provider: ec2 |Required        | Which AgnosticD Cloud Provider to use
|===

* Multi region sepfic settings related variables.

|===
|*Variable* | *State* |*Description*
|target_regions: [List] |Required | Main list to define regions
|region: "String" |Required | region name as per aws
|stack: "String" |Required | cloud formation template name
|name: "String" |Required | Freindly region name
|vpc_cidr: "IP addr" |Required | vpc cidr ip address
|subnet_cidr: "IP Addr" |Required | subnet ip address
|===



* Satellite specfic settings related variables.

|===
|*Variable* | *State* |*Description*
|install_satellite: Boolean   |Required | To enable installation roles
|configure_satellite: Boolean |Required | To enable configuration roles
|install_capsule: Boolean   |Required | To enable capsule installation roles
|configure_capsule: Boolean |Required | To enable capsule configuration roles
|satellite_version: "Digit" |Required |satellite version
|org: "String" |Required |Organization name
|org_label: "String" |Required | Organization label in string without space
|org_description: "String" |Required | Organization description
|lifecycle_environment_path: [list] |Required | Contains nested list of environment path
|satellite_content: [list] |Required | Main List variable
|subscription_name: "String" |Required | Subscription name mainly required for manifest role
|===

[NOTE] 
For more about variables read README.adoc of the roles.
    
* Example variables

[source=text]
----
env_type: satellite-multi-region      
output_dir: /tmp/workdir               
email: satellite_multi_region@example.com 
cloud_provider: ec2 

target_regions:
  - region: ap-southeast-2
    stack: default
    name: apac
    vpc_cidr: 10.1.0.0/16
    subnet_cidr: 10.1.0.0/24
  - region: ap-southeast-1
    stack: capsule.j2
    name: emea
    vpc_cidr: 10.2.0.0/16
    subnet_cidr: 10.2.0.0/24

install_satellite: True
configure_satellite: True 
install_capsule: True
configure_capsule: True
satellite_version: 6.4
org: gpte
org_label: gpte
org_description: "Global Partner Training and Enablement"
subscription_name: "Employee SKU"

lifecycle_environment_path:
    - name: "Dev"
      label: "dev"
      description: "Development Environment"
      prior_env: "Library"
    - name: "QA"
      label: "qa"
      description: "Quality Environment"
      prior_env: "Dev"
    - name: "Prod"
      label: "prod"
      description: "Production Enviornment"
      prior_env: "QA"

satellite_content:
  - name:             "Capsule Server"
    activation_key:   "capsule_key"
    subscriptions:
      - "Employee SKU"
    life_cycle:       "Library"
    content_view:     "Capsule Content"
    content_view_update: False
    repos:  
      - name: 'Red Hat Enterprise Linux 7 Server (RPMs)' 
        product: 'Red Hat Enterprise Linux Server' 
        basearch: 'x86_64'
        releasever:  '7Server'
        
      - name: 'Red Hat Satellite Capsule 6.4 (for RHEL 7 Server) (RPMs)'
        product: 'Red Hat Satellite Capsule' 
        basearch: 'x86_64'
  - name:             "Three Tier App"
    activation_key:   "three_tier_app_key"
    content_view:     "Three Tier App Content"
    life_cycle:       "Library"
    subscriptions:
      - "Employee SKU"
    repos: 
      - name: 'Red Hat Enterprise Linux 7 Server (RPMs)' 
        product: 'Red Hat Enterprise Linux Server' 
        basearch: 'x86_64'
        releasever:  '7Server'    
----

Roles
-----

* List of satellite and capsule roles


|===
|*Role*| *Link* | *Description*
|satellite-public-hostname | link:../../roles/satellite-public-hostname[satellite-public-hostname] | Set public hostname
|satellite-installation |link:../../roles/satellite-installation[satellite-installation] | Install and configure satellite 
|satellite-hammer-cli |link:../../roles/satellite-hammer-cli[satellite-hammer-cli] | Setup hammer cli
|satellite-manage-organization |link:../../roles/satellite-manage-organization[satellite-manage-organization] | Create satellite organization
|satellite-manage-manifest |link:../../roles/ssatellite-manage-manifest[satellite-manage-manifest] | uploads manifest
|satellite-manage-subscription |link:../../roles/satellite-manage-subscription[satellite-manage-subscription] | Manage subscription/repository
|satellite-manage-sync |link:../../roles/satellite-manage-sync[satellite-manage-sync] | Synchronize repository
|satellite-manage-lifecycle |link:../../roles/satellite-manage-lifecycle[satellite-manage-lifecycle]  | Create lifecycle environment
|satellite-manage-content-view |link:../../roles/satellite-manage-content-view[satellite-manage-content-view]  | Create content-view
|satellite-manage-activationkey |link:../../roles/satellite-manage-activationkey[satellite-manage-content-view]  | Create activation key
|satellite-manage-capsule-certificate | link:../../roles/satellite-manage-capsule-certificate[satellite-manage-capsule-certificate]  | Create certificates for capsule installation on satellite 
|satellite-capsule-installation |link:../../roles/satellite-capsule-installation[satellite-capsule-installation]  | Install capsule packages
|satellite-capsule-configuration | link:../../roles/satellite-capsule-configuration[satellite-capsule-configuration] | Setup capsule server
|===

Tags
---

|===
|{tag1} |Consistent tag for all satellite installation roles
|{tag2} |Consistent tag for all satellite configuration roles
|===

* Example tags

----
## Tagged jobs
ansible-playbook playbook.yml --tags configure_satellite

## Skip tagged jobs
ansible-playbook playbook.yml --skip-tags install_satellite
----

Example to run config 
---------------------

How to use config (for instance, with variables passed in playbook).

[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible

[user@desktop ~]$ cat ./configs/satellite-multi-region/sample_vars.yml

env_type: satellite-multi-region      
output_dir: /tmp/workdir               
email: satellite_multi_region@example.com 
cloud_provider: ec2 

target_regions:
  - region: ap-southeast-2
    stack: default
    name: apac
    vpc_cidr: 10.1.0.0/16
    subnet_cidr: 10.1.0.0/24
  - region: ap-southeast-1
    stack: capsule.j2
    name: emea
    vpc_cidr: 10.2.0.0/16
    subnet_cidr: 10.2.0.0/24

install_satellite: True
configure_satellite: True 
install_capsule: True
configure_capsule: True
satellite_version: 6.4
org: gpte
org_label: gpte
org_description: "Global Partner Training and Enablement"
lifecycle_environment_path:
    - name: "Dev"
      label: "dev"
      description: "Development Environment"
      prior_env: "Library"
    - name: "QA"
      label: "qa"
      description: "Quality Environment"
      prior_env: "Dev"
    - name: "Prod"
      label: "prod"
      description: "Production Enviornment"
      prior_env: "QA"

subscription_name: "Employee SKU"
satellite_content:
  - name:             "Capsule Server"
    activation_key:   "capsule_key"
    subscriptions:
      - "Employee SKU"
    life_cycle:       "Library"
    content_view:     "Capsule Content"
    content_view_update: False
    repos:  
      - name: 'Red Hat Enterprise Linux 7 Server (RPMs)' 
        product: 'Red Hat Enterprise Linux Server' 
        basearch: 'x86_64'
        releasever:  '7Server'
        
      - name: 'Red Hat Satellite Capsule 6.4 (for RHEL 7 Server) (RPMs)'
        product: 'Red Hat Satellite Capsule' 
        basearch: 'x86_64'
  - name:             "Three Tier App"
    activation_key:   "three_tier_app_key"
    content_view:     "Three Tier App Content"
    life_cycle:       "Library"
    subscriptions:
      - "Employee SKU"
    repos: 
      - name: 'Red Hat Enterprise Linux 7 Server (RPMs)' 
        product: 'Red Hat Enterprise Linux Server' 
        basearch: 'x86_64'
        releasever:  '7Server' 

[user@desktop ~]$ ansible-playbook  main.yml \
  -e @./configs/satellite-multi-region/sample_vars.yml \
  -e @~/secrets.yml \
  -e guid=defaultguid  \
  -e satellite_admin=admin \
  -e 'satellite_admin_password=password' \
  -e manifest_file=/path/to/manifest_satellite_6.4.zip
----

Example to stop environment 
---------------------------

[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible

[user@desktop ~]$ ansible-playbook  ./configs/satellite-multi-region/stop.yml \
  -e @./configs/satellite-multi-region/sample_vars.yml \
  -e @~/secrets.yml \
  -e guid=defaultguid  
----

Example to start environment 
---------------------------

[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible

[user@desktop ~]$ ansible-playbook  ./configs/satellite-multi-region/start.yml \
  -e @./configs/satellite-multi-region/sample_vars.yml \
  -e @~/secrets.yml \
  -e guid=defaultguid  
----

Example to destroy environment 
------------------------------

[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible

[user@desktop ~]$ ansible-playbook  ./configs/satellite-multi-region/destroy.yml \
  -e @./configs/satellite-multi-region/sample_vars.yml \
  -e @~/secrets.yml \
  -e guid=defaultguid 
----



for reference look at link:sample_vars.yml[]  


Author Information
------------------

{author}
