= agnosticd_dynamic

This Ansible role is used during AgnosticD setup to download dynamic sources from Ansible Galaxy and Git.

== Variables

`agnosticd_dynamic_roles_dir` - Directory in which to install Ansible roles.
This directory should be included in the `ANSIBLE_ROLES_PATH`, which may be set by the `roles_path` in the `[defaults]` section of `ansible.cfg`.
Default value `{{ playbook_dir }}/dynamic-roles`.

`agnosticd_dynamic_cache_dir` - Directory in which to install sources which should be saved between executions.
Default value `{{ playbook_dir }}/dynamic-cache`, but should be configured outside of the playbook directory to preserve data when executing inside Ansible Tower.

`agnosticd_dynamic_role_galaxy_sources` - List of Ansible Galaxy role sources.
Values are specified as in an Ansible `requirements.yml` (https://galaxy.ansible.com/docs/using/installing.html).
If the version is specified with a semantic version syntax then the role source is saved to a cache directory and a link is created from the roles directory.

--------------------
agnosticd_dynamic_role_galaxy_sources:
  - name: k8s_config
    src: redhat-cop.k8s_config
    version: 0.2.0
--------------------

`agnosticd_dynamic_git_sources` - List of Git sources to install.
Each source is specified using options to the `git` module (https://docs.ansible.com/ansible/latest/modules/git_module.html).
In addition, `role_paths` may be specified as a dictionary of names and paths within the repository:

--------------------
agnosticd_dynamic_git_sources:
  - repo: https://github.com/redhat-cop/agnosticd.git
    version: ocp4-workshop-prod-1.41
    role_paths:
      ocp4-workload-infra-nodes: ansible/roles/ocp4-workload-infra-nodes
--------------------
