:role: satellite-capsule-installation
:author: GPTE Team
:tag1: install_capsule
:main_file: tasks/main.yml
:version_file: tasks/version_6.4.yml

Role: {role}
============

This role installs capsule server.

Requirements
------------

Following are the requirements:

. Satellite must be install and setup.
. Satellite should have capsule activation key and repositories. 
 
Role Variables
--------------

* Following are the variable which needs to be defined 

|===
|satellite_version: "Digit" |Required |satellite version
|org: "String" |Required |Organization name
|org_label: "String" |Notrequired | Organization label in string without space
|org_description: "String" |Not-required | Organization description
|satellite_content: {Dictionary} |Required | Main dictionary variable
|name: "String" |Required | Must be "Capsule Sever" for capsules
|activation_keys: "String" |Required | Name of the activation key
|vars/repos: [list] | Required | List of repos to enable in vars directory
|===
    
* Exammple variables

. variable in sample_vars.yml

[source=text]
----
satellite_version: 6.4
org: "gpte"
org_label: "gpte"
org_description: "Global Partner Training and Enablement"
satellite_content:
  - name:             "Capsule Server"
    activation_key:   "capsule_key"
       
  - name:             "Three Tier App"
    activation_key:   "three_tier_app_key"
    
----
. Variable in vars directory

[source=text]
----
[user@desktop ~]$ cat vars/main.yml

repos:
  - rhel-7-server-rpms
  - rhel-server-rhscl-7-rpms
  - rhel-7-server-satellite-maintenance-6-rpms
  - rhel-7-server-ansible-2.6-rpms
  - rhel-7-server-satellite-capsule-6.4-rpms
    
----

Dependencies
------------
* Role is dependent on following roles
  . satellite-public-hostname
  . satellite-manage-capsule-certificate


Tags
---

|===
|{tag1} | This tag is specific to installation tasks.
|===

* Example tags

----
## Tagged jobs
ansible-playbook playbook.yml --tags install_capsule

## Skip tagged jobs
ansible-playbook playbook.yml --skip-tags install_capsule
----

Example Playbook
----------------

How to use your role (for instance, with variables passed in playbook).

[source=text]
----

[user@desktop ~]$ cat playbook.yml
- hosts: capsule.example.com
  vars_files:
    - sample_vars.yml
  roles:
    - satellite-public-hostname
    - satellite-capsule-installation

[user@desktop ~]$ ansible-playbook playbook.yml

----


Tips to update Role
------------------

To extend role works for other version, create new file named  version_{{satellite_version}}.yml and import newly created file in main.yml

for reference look at link:{main_file}[main.yml] and link:{version_file}[version_6.4.yml] .


Author Information
------------------

{author}
