:role: satellite-capsule-installation
:author: GPTE Team
:tag1: install_capsule
:main_file: tasks/main.yml
:version_file: tasks/version_6.4.yml

Role: {role}
============

This role installs capsule server.

Requirements
------------

Following are the requirements:

. Satellite must be install and setup.
. Satellite should have capsule activation key and repositories. 
 
Role Variables
--------------

* Following are the variable which needs to be defined 

|===
|satellite_version: "Digit" |Required |satellite version
|satellite_public_fqdn: "String" |Required | Satellite public accessible fully qualified domain name
|capsule_org: "String" |Required |Organization name
|capsule_activationkey: "String" |Required | Name of the activation key
|defaults/capsule_repos: [list] | Required | List of repos to enable in vars directory
|defaults/firewall_capsule_services: [list] | Required | List of firewalld services to enable
|defaults/firewall_capsule_ports: [list] | Required | List of firewalld ports to enable
|===
    
* Exammple variables

. variable in sample_vars.yml

[source=text]
----
satellite_version: 6.4
satellite_public_fqdn: satellite.example.com
capsule_activationkey: capsule_key
capsule_org: gpte


    
----
. Variable in defaults directory

[source=text]
----
[user@desktop ~]$ cat defaults/main.yml

capsule_repos:
  - rhel-7-server-rpms
  - rhel-server-rhscl-7-rpms
  - rhel-7-server-satellite-maintenance-6-rpms
  - rhel-7-server-ansible-2.6-rpms
  - rhel-7-server-satellite-capsule-6.4-rpms
  - rhel-7-server-satellite-tools-6.4-rpms

firewall_capsule_services:
  - ssh

firewall_capsule_ports:
  - 80/tcp
  - 443/tcp
  - 5000/tcp
  - 5646/tcp
  - 5647/tcp

----

Dependencies
------------
* Role is dependent on following roles
  . satellite-public-hostname
  . satellite-manage-capsule-certificate


Tags
---

|===
|{tag1} | This tag is specific to installation tasks.
|configure_capsule_firewalld | This tag is specific to firewalld tasks.
|===

* Example tags

----
## Tagged jobs
ansible-playbook playbook.yml --tags install_capsule

## Skip tagged jobs
ansible-playbook playbook.yml --skip-tags install_capsule
----

Example Playbook
----------------

How to use your role (for instance, with variables passed in playbook).

[source=text]
----

[user@desktop ~]$ cat playbook.yml
- hosts: capsule.example.com
  vars_files:
    - sample_vars.yml
  roles:
    - satellite-public-hostname
    - satellite-capsule-installation

[user@desktop ~]$ ansible-playbook playbook.yml

----


Tips to update Role
------------------

To extend role works for other version, create new file named  version_{{satellite_version}}.yml and import newly created file in main.yml

for reference look at link:{main_file}[main.yml] and link:{version_file}[version_6.4.yml] .


Author Information
------------------

{author}
