---
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: kube-rbac-proxy-mirror
spec:
  imageDigestMirrors:
  - source: gcr.io/kubebuilder/kube-rbac-proxy
    mirrors:
    - registry.k8s.io/kubebuilder/kube-rbac-proxy
