---
apiVersion: config.openshift.io/v1
kind: ImageTagMirrorSet
metadata:
  name: kube-rbac-proxy-tag-mirror
spec:
  imageTagMirrors:
  - source: gcr.io/kubebuilder/kube-rbac-proxy
    mirrors:
    - registry.k8s.io/kubebuilder/kube-rbac-proxy
