

- name: Install and configure Apache Camel CLI if jbang is not installed
  ansible.builtin.shell: |
    curl -Ls https://sh.jbang.dev | bash -s - app setup && \
    {{cli_jbang}} trust add https://github.com/apache/camel/ && \
    {{cli_jbang}} app install -Dcamel.jbang.version=4.15.0 camel@apache/camel && \
    {{cli_jbang}} camel@apache/camel plugin add kubernetes && \
    {{cli_camel}} version
  register: camel_install
  # when: jbang_check.rc != 0
  changed_when: camel_install.rc == 0
  failed_when: camel_install.rc != 0

- name: Show test Camel CLI
  debug:
    msg: "{{ camel_install }}"
