:config: smart-management
:author1: Mitesh The Mouse <mitsharm@redhat.com>
:author2: Prakhar Srivastava <psrivast@redhat.com>
:author3: Tony Kay <tok@redhat.com>
:team: GPTE DevOps & Automation

Config Name: {config}
=====================

The {config} config deploys bastion, Ansible tower, Satellite and RHEL host on OpenStack cloud providers.


Requirements
------------

* Following are the requirements:
. Yum repositories are required for bastion and satellite host.
. OSP credentials are required. 
. openstacksdk and apypie python modules required.

Config Variables
----------------

. Cloud specfic settings related variables.
+
[cols="4",options="header"]
|===
|*Variable* | *State* | *Default* |*Description*
| env_type: "string"| Required | None| Name of the config (smart-management)
| output_dir: "path string" |Required | /tmp/workdir | Writable working scratch directory
| email: "string" | Required | smart-management@example.com | User info for notifications
| guid: "string" | Reqired |defaultguid |Unique identifier
| cloud_provider: "string" |Required   | osp      | Which AgnosticD Cloud Provider to use
|rhel_repos: [list] |Required | Default  | List for rhel repos
|===

. Tower specfic variables.
+
[cols="4",options="header"]
|===
|*Variable* | *State* | *Default* | *Description* 
|tower_version: 'digits' | Required | None | Tower version for installation
|tower_admin_password: "string" | Optional |  Auto | Tower admin password
|software_to_deploy: "string" | Required | tower | Tower installation playbook
| tower_default_workloads: [list] | Required |   [tower-license-injector, cleanup-tower-default] | Default workload (list of roles)
| tower_infra_workloads: [list] | Required | None | Infra workload (list of roles)
|===
+
[NOTE] 
For role related variables, read Tower role's README.adoc.

. Satellite specfic variables.
+
[cols="4",options="header"]
|===
|*Variable* | *State* | *Default* |*Description*
|install_satellite: Bool   | Required | True | To enable installation roles
|configure_satellite: Bool |Required | False | To enable configuration roles
|satellite_version: "Digit" |Required | 6.7 |satellite version
|satellite_repos: [list] |Required | Default for 6.7 | List for satellite repos
|org: "String" |Required | None |Organization name
|org_label: "String" |Required | None | Organization label in string without space
|org_description: "String" |Required | None | Organization description
|===
+
[NOTE] 
For role related variables, read satellite role's README.adoc.
    
Example variables and values
----------------------------

. Sample of sample_osp_vars.yml
+
[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible
[user@desktop ~]$ cat ./configs/smart-management/sample_osp_vars.yml
guid: defaultguid
osp_cluster_dns_zone: red.osp.opentlc.com
admin_user: opentlc-mgr
student_name: student
student_password: "changeme"
tower_version: "3.6.4-1"
software_to_deploy: tower            
tower_infra_workloads:
  - tower-org-create
tower_organization:
  - name: gpte
configure_satellite: true
satellite_version: 6.7
satellite_infra_workloads:
  - satellite-manage-organization
  - satellite-manage-manifest
org: gpte
org_label: gpte
org_description: "Global Partner Training and Enablement"
----
+
[NOTE]
For reference  link:sample_vars_osp.yml[click] here.  

. Sample of secrets.yml
+
[source=text]
----
[user@desktop ~]$ cat ~/secrets.yml
osp_auth_url: http://x.x.x.x:5000/v3
osp_auth_username: admin
osp_auth_password: "xxxxxxxxxxxxxxxxxxxxxxxxx"
osp_auth_project_domain: "default"
osp_auth_user_domain: "default"
osp_cluster_dns_zone: xxxxxxx.osp.opentlc.com
ddns_key_name: xxxxxxxxxxxxx
ddns_key_secret: "xxxxxxxxxxxxxxxxxxxxxx"
own_repo_path: http://some.yum.com/repos/
satellite_manifest:
  type: file
  path: ~/manifest_satellite-infrastructure-may-2020.zip
tower_license: >
  {
    "subscription_name": "Ansible Tower by Red Hat, Standard (50 Managed Nodes)", 
    "eula_accepted": true, 
    "instance_count": 50, 
    "trial": false, 
    "contact_email": "ankay@redhat.com", 
    "company_name": "Red Hat, Inc", 
    "license_type": "enterprise", 
    "contact_name": "Tony Kay", 
    "license_date": 1640926800, 
    "license_key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  }
----


Tags
---
. List of tags used in {config} config-
+
[cols="2",options="header"]
|===
| Tag | Description 
|install_satellite |Consistent tag for all satellite installation roles
|configure_satellite |Consistent tag for all satellite configuration roles
|install-tower | Consistent tag for all tower installation tasks
|tower-cli |  Consistent tag for all tower-cli tasks
|===

. Examples how to use tags
+
----
## Tagged jobs
[user@desktop ~]$ ansible-playbook playbook.yml --tags configure_satellite

## Skip tagged jobs
[user@desktop ~]$ ansible-playbook playbook.yml --skip-tags install_satellite,install-tower
----

Examples, How to use config 
---------------------------

. How to deploy {config} config.
+
[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible
[user@desktop ~]$ ansible-playbook  main.yml \
  -e @./configs/smart-management/sample_vars_osp.yml \
  -e @~/secrets.yml \
  -e guid=<Alphanum>  
----

. How to destroy deployed environment 
+
[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible
[user@desktop ~]$ ansible-playbook  ./configs/smart-management/destroy.yml \
  -e @./configs/smart-management/sample_vars_osp.yml \
  -e @~/secrets.yml \
  -e guid=defaultguid 
----

Author Information
------------------

* Author/owner:
** {author1}

* Alternative Contacts:
** {author2}
** {author3}

* Team:
** {team}
