Role Name
=========

ocp-workload-rh-sso role is intended to add a red hat sso authentication infrastructure with a persistent rh-ssh instance.

It is intended to have a security domain for each student to configure and integrate additional applications to this role based authentication server.

Requirements
------------

* **OC Client tools**: As this is a provisioning role for an OCP workshop environment.

== Execution using localhost oc client

-----
WORKLOAD="ocp-workload-rh-sso"
GUID=jb45
OCP_USERNAME="jbride-redhat.com"
HOST_GUID=`oc whoami --show-server | cut -d'.' -f 2`

ansible-playbook -i localhost, -c local ./configs/ocp-workloads/ocp-workload.yml \
                    -e"ANSIBLE_REPO_PATH=`pwd`" \
                    -e"ocp_workload=${WORKLOAD}" \
                    -e"ocp_user_needs_quota=true" \
                    -e"guid=$GUID" \
                    -e"ACTION=create" \
                    -e"ocp_username=${OCP_USERNAME}"

ansible-playbook -i localhost, -c local ./configs/ocp-workloads/ocp-workload.yml \
                    -e"ANSIBLE_REPO_PATH=`pwd`" \
                    -e"ocp_workload=${WORKLOAD}" \
                    -e"guid=$GUID" \
                    -e"ACTION=remove" \
                    -e"ocp_username=${OCP_USERNAME}"
-----



=== Deploy a Workload with the `ocp-workload` playbook [Mostly for testing]
----
GUID=jb45
HOST_GUID=dev39
TARGET_HOST="bastion.$HOST_GUID.openshift.opentlc.com"
OCP_USERNAME="jbride-redhat.com"
WORKLOAD="ocp-workload-rh-sso"
SSH_USERNAME="jbride-redhat.com"
SSH_PRIVATE_KEY="id_ocp"

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
                 -e"ansible_ssh_private_key_file=~/.ssh/${SSH_PRIVATE_KEY}" \
                 -e"ansible_ssh_user=${SSH_USERNAME}" \
                    -e"ANSIBLE_REPO_PATH=`pwd`" \
                    -e"ocp_username=${OCP_USERNAME}" \
                    -e"ocp_workload=${WORKLOAD}" \
                    -e"guid=${GUID}" \
                    -e"ocp_user_needs_quota=true" \
                    -e"ocp_apps_domain=apps.${HOST_GUID}.openshift.opentlc.com" \
                    -e"ACTION=create"

----

=== To Delete an environment

----
GUID=jb45
HOST_GUID=dev39
TARGET_HOST="bastion.$HOST_GUID.openshift.opentlc.com"
OCP_USERNAME="jbride-redhat.com"
WORKLOAD="ocp-workload-rh-sso"
SSH_USERNAME="jbride-redhat.com"
SSH_PRIVATE_KEY="id_ocp"

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
                 -e"ansible_ssh_private_key_file=~/.ssh/${SSH_PRIVATE_KEY}" \
                 -e"ansible_ssh_user=${SSH_USERNAME}" \
                    -e"ANSIBLE_REPO_PATH=`pwd`" \
                    -e"ocp_username=${OCP_USERNAME}" \
                    -e"ocp_workload=${WORKLOAD}" \
                    -e"guid=${GUID}" \
                    -e"ACTION=remove"
----

License
-------

BSD

Author Information
------------------

dtorresf, honghuac
