#!/bin/bash

# systemctl enable --now cockpit.socket


echo "Adding wheel" > /root/post-run.log
usermod -aG wheel rhel

echo "setting password" >> /root/post-run.log
echo redhat | passwd --stdin rhel

dnf install -y nc

systemctl enable --now libvirtd


echo "${SSHKEY}" > r4ekey
chmod 600 r4ekey

virsh attach-interface --domain vm1 --type network --source default --model virtio