= Modify a-base-config Lab

In this lab you will modify a-base-config from a single RHEL 8 server deployment into a two node RHEL 7.7 webserver environment.

To accomplish this task you will need to:

* Create a new security group named `webserver_sg` to allow port `tcp:80` to be accessible.

TIP: Copy and paste an existing security group in the variable file for a template.

* Modify the existing or create a new `instance` dictionary to deploy 2 webservers running RHEL 7.7.

TIP: Recall that Openstack has specific image names that can be listed with `openstack image list --os-cloud=<my-cloud>`

* Modify the repository list to reflect RHEL 7 values.
* Modify a secrets file with the appropriate repository information.

*Bonus Challenge:* Include `a_simple_webserver` workload.

== Solutions

*Step 1.* +
Copy sample_variables/rhel8_server_on_osp.yml to 2_rhel7_webservers_on_osp.yml

....
$ cp ~/agnosticd/ansible/configs/a-base-config/sample_variables/rhel8_server_on_osp.yml \
~/2_rhel7_webservers_on_osp.yml
....

*Step 2.* +
Create a new security group named `webserver_sg` to allow port `tcp:80` to be accessible.

TIP: Copy and paste an existing security group in the variable file for a template.

....
$ vi ~/2_rhel7_webservers_on_osp.yml

# Security groups and associated rules. This will be provided
# when the Heat template is generated separate groups and rules
security_groups:
- name: node_sg
  description: Node security group allows basic icmp and SSH ingress and egress.
  rules:
  - protocol: icmp
    description: "Ping"
    direction: ingress
    rule_type: Ingress
  - protocol: tcp
    description: "SSH Access"
    direction: ingress
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
    rule_type: Ingress

- name: webserver_sg
  description: Security group for public webservers
  rules:
  - name: webserverHTTPPorts
    description: "HTTP Public"
    direction: ingress
    rule_type: Ingress
    port_range_min: 80
    port_range_max: 80
    protocol: tcp
    remote_ip_prefix: 0.0.0.0/0
....

*Step 3.* +
Modify the existing or create a new `instance` dictionary to deploy 2 webservers on RHEL 7.7.

TIP: Recall that Openstack has specific image names that can be listed with `openstack image list --os-cloud=<my-cloud>`

....
$ openstack image list --os-cloud=<my-cloud> | grep -n "7\.7"

| 93de52d1-2982-43e6-8481-491fc93225e9 | rhel-server-7.7           | active |
| 49271e6c-2d3e-4f78-95c8-4cab3c96ac29 | rhel-server-7.7-update-2  | active |
....
....
$ vi ~/2_rhel7_webservers_on_osp.yml

instances:
- name: webserver
  count: "{{ webserver_instance_count }}"
  public_dns: true
  dns_loadbalancer: false
  floating_ip: true
  image_id: "{{ webserver_instance_image }}"
  flavor:
    osp: "{{ webserver_instance_type }}"
  metadata:
    - AnsibleGroup: "webservers"
    - function: webserver
    - user: "{{ student_name }}"
    - ostype: linux
  network: node_network
  security_groups:
    - webserver_sg
    - node_sg

rhel_image: rhel-server-7.7
webserver_instance_count: 2
webserver_instance_image: "{{ rhel_image }}"
webserver_instance_type: 2c2g30d
....

*Step 4.* +
Modify the repository list to include common RHEL 7 repos.

....
$ vi ~/2_rhel7_webservers_on_osp.yml

rhel_repos:
  - rhel-7-server-rpms
  - rhel-7-server-rh-common-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-optional-rpms
  - rhel-server-rhscl-7-rpms

....

*Step 5.* +
Modify a secrets file with the appropriate repository information.

....
$ vi ~/secrets.yml

repo_method: rhn
rhel_subscription_user: CHANGEME
rhel_subscription_pass: CHANGEME
rhsm_pool_ids: CHANGEME
....

*Bonus Challenge:* +
Include `a_simple_webserver` workload.

....
$ vi ~/2_rhel7_webservers_on_osp.yml

infra_workloads:
- a_simple_webserver

firewalld_active: true

....
