= Modify a-base-config Lab

In this lab you will modify a-base-config from a single RHEL 8 server deployment into a two node RHEL 7.7 webserver environment.

To accomplish this task you will need to:

* Create a new security group named `webserver_sg` to allow port `tcp:80` to be accessible.

TIP: Copy and paste an existing security group in the variable file for a template.

* Modify the existing or create a new `instance` dictionary to deploy 2 webservers running RHEL 7.7.

TIP: Recall that Openstack has specific image names that can be listed with `openstack image list --os-cloud=<my-cloud>`

* Modify the repository list to reflect RHEL 7 values.
* Modify a secrets file with the appropriate repository information.

*Bonus Challenge:* Include `a_simple_webserver` workload.

== Solutions

*Step 1.* +
Copy sample_variables/rhel8_server_on_osp.yml to 2_rhel7_webservers_on_osp.yml

....
$ cp ~/agnosticd/ansible/configs/a-base-config/sample_variables/rhel8_server_on_osp.yml \
~/2_rhel7_webservers_on_osp.yml
....

*Step 2.* +
Create a new security group named `webserver_sg` to allow port `tcp:80` to be accessible.

TIP: Copy and paste an existing security group in the variable file for a template.

....
$ vi ~/2_rhel7_webservers_on_osp.yml

# Security groups and associated rules. This will be provided
# when the Heat template is generated separate groups and rules
security_groups:
- name: node_sg
  description: Node security group allows basic icmp and SSH ingress and egress.
  rules:
  - protocol: icmp
    description: "Ping"
    direction: ingress
    rule_type: Ingress
  - protocol: tcp
    description: "SSH Access"
    direction: ingress
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
    rule_type: Ingress

- name: webserver_sg
  description: Security group for public webservers
  rules:
  - name: webserverHTTPPorts
    description: "HTTP Public"
    direction: ingress
    rule_type: Ingress
    port_range_min: 80
    port_range_max: 80
    protocol: tcp
    remote_ip_prefix: 0.0.0.0/0
....

*Step 3.* +
Modify the existing or create a new `instance` dictionary to deploy 2 webservers on RHEL 7.7.

TIP: Recall that Openstack has specific image names that can be listed with `openstack image list --os-cloud=<my-cloud>`

....
$ openstack image list --os-cloud=<my-cloud> | grep -n "7\.7"

| 93de52d1-2982-43e6-8481-491fc93225e9 | rhel-server-7.7           | active |
| 49271e6c-2d3e-4f78-95c8-4cab3c96ac29 | rhel-server-7.7-update-2  | active |
....
....
$ vi ~/2_rhel7_webservers_on_osp.yml

instances:
- name: webserver
  count: "{{ webserver_instance_count }}"
  public_dns: true
  dns_loadbalancer: false
  floating_ip: true
  image_id: "{{ webserver_instance_image }}"
  flavor:
    osp: "{{ webserver_instance_type }}"
  metadata:
    - AnsibleGroup: "webservers"
    - function: webserver
    - user: "{{ student_name }}"
    - ostype: linux
  network: node_network
  security_groups:
    - webserver_sg
    - node_sg

rhel_image: rhel-server-7.7
webserver_instance_count: 2
webserver_instance_image: "{{ rhel_image }}"
webserver_instance_type: 2c2g30d
....

*Step 4.* +
Modify the repository list to include common RHEL 7 repos.

....
$ vi ~/2_rhel7_webservers_on_osp.yml

rhel_repos:
  - rhel-7-server-rpms
  - rhel-7-server-rh-common-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-optional-rpms
  - rhel-server-rhscl-7-rpms

....

*Step 5.* +
Modify the flavor of the webserver nodes you are going to create. In order to see the available flavors in our OpenStack environment just do:
[source,bash]
----
$ openstack flavor list
+--------------------------------------+---------------------------------------------------------------------------------+--------+------+-----------+-------+-----------+
| ID                                   | Name                                                                            |    RAM | Disk | Ephemeral | VCPUs | Is Public |
+--------------------------------------+---------------------------------------------------------------------------------+--------+------+-----------+-------+-----------+
| 0a15d1ed-ca28-43b8-8b60-1f4a3619e1fc | 4c18g60d                                                                        |  18432 |   60 |         0 |     4 | True      |
| b5d1c5f1-6dc4-4541-ab0a-5c0b139870f0 | 4c16g100d                                                                       |  16384 |  100 |         0 |     4 | True      |
| b9072ce3-2440-4abf-9278-cf468f9c3c8e | 8c32g100d                                                                       |  32768 |  100 |         0 |     8 | True      |
| cdefd435-7328-40e4-bb32-309dbabc9c92 | 4c8g30d                                                                         |   8192 |   30 |         0 |     4 | True      |
| e056c22a-ed5e-4281-bdcc-e7076dd9f16d | 16c30g100d                                                                      |  30720 |  100 |         0 |    16 | True      |
...
----

And then simply set the value of `webserver_instance_type: 4c8g30d`

*Step 6.* +
Modify a secrets file with the appropriate repository information.

....
$ vi ~/secrets.yml

repo_method: rhn
rhel_subscription_user: CHANGEME
rhel_subscription_pass: CHANGEME
rhsm_pool_ids: CHANGEME
....

*Bonus Challenge:* +
Include `a_simple_webserver` workload.

....
$ vi ~/2_rhel7_webservers_on_osp.yml

infra_workloads:
- a_simple_webserver

firewalld_active: true

== Check out your webservers

Let's take a quick look at our newly deployed servers, to verify if it's all as we have defined on our variables file.

We are going to verify the firewall is installed (by default is stopped), Apache is up and running and check it's actualy serving http content (this has been deployed with the `a_simple_webserver` role):

[source,bash]
----
$ ssh webserver0
[cloud-user@webserver0 ~]$ sudo -i
[root@webserver0 ~]# systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:firewalld(1)
[root@webserver0 ~]# systemctl status httpd
● httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2020-06-19 12:31:28 EDT; 18min ago
     Docs: man:httpd(8)
           man:apachectl(8)
  Process: 11306 ExecReload=/usr/sbin/httpd $OPTIONS -k graceful (code=exited, status=0/SUCCESS)
 Main PID: 11203 (httpd)
   Status: "Total requests: 0; Current requests/sec: 0; Current traffic:   0 B/sec"
   CGroup: /system.slice/httpd.service
           ├─11203 /usr/sbin/httpd -DFOREGROUND
           ├─11307 /usr/sbin/httpd -DFOREGROUND
           ├─11308 /usr/sbin/httpd -DFOREGROUND
           ├─11309 /usr/sbin/httpd -DFOREGROUND
           ├─11310 /usr/sbin/httpd -DFOREGROUND
           └─11311 /usr/sbin/httpd -DFOREGROUND

Jun 19 12:31:28 webserver0 systemd[1]: Starting The Apache HTTP Server...
Jun 19 12:31:28 webserver0 systemd[1]: Started The Apache HTTP Server.
Jun 19 12:31:28 webserver0 systemd[1]: Reloading The Apache HTTP Server.
Jun 19 12:31:28 webserver0 systemd[1]: Reloaded The Apache HTTP Server.
[root@webserver0 ~]# curl http://localhost:80
<html>
   <head>
       <title>AgnosticD infrastructure role website</title>
   </head>
   <body>
       <h1>Welcome to your website deployed by an AgnosticD infrastructure role!</h1>
   </body>
</html>
----