#!/bin/bash
LOG=/root/setup-log
#LOG=/dev/null


dnf install -y libguestfs guestfs-tools >> $LOG
hostnamectl set-hostname rhel-$(uuidgen | cut -c 32-)
echo "export LIBGUESTFS_BACKEND=direct" >> /root/.bashrc
exec $SHELL