{
 "title": "App Performance",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "userid",
    "label": "User ID",
    "query": "user1,user2,user3,user4,user5,user6,user7,user8,user9,user10,user11,user12,user13,user14,user15,user16,user17,user18,user19,user20,user21,user22,user23,user24,user25,user26,user27,user28,user29,user30,user31,user32,user33,user34,user35,user36,user37,user38,user39,user40,user41,user42,user43,user44,user45,user46,user47,user48,user49,user50,user51,user52,user53,user54,user55,user56,user57,user58,user59,user60"
   }
  ]
 },
 "panels": [
  {
   "title": "Max CPU usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"\", namespace=\"${userid}-staging\", pod=~\"quarkus-app.+\"}) by (pod))",
     "legendFormat": "Quarkus CPU Usage (Max)"
    },
    {
     "expr": "max(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"\", namespace=\"${userid}-staging\", pod=~\"micronaut-app.+\"}) by (pod))",
     "legendFormat": "Micronaut CPU Usage (Max)"
    },
    {
     "expr": "max(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"\", namespace=\"${userid}-staging\", pod=~\"springboot-app.+\"}) by (pod))",
     "legendFormat": "Springboot CPU Usage (Max)"
    }
   ]
  },
  {
   "title": "Avg Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=\"${userid}-staging\", container!=\"\", image!=\"\", pod=~\"quarkus-app-.+\"}) by (pod))",
     "legendFormat": "Quarkus Mem Usage (Avg) "
    },
    {
     "expr": "avg(sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=\"${userid}-staging\", container!=\"\", image!=\"\", pod=~\"micronaut-app-.+\"}) by (pod))",
     "legendFormat": "Micronaut Mem Usage (Avg) "
    },
    {
     "expr": "avg(sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=\"${userid}-staging\", container!=\"\", image!=\"\", pod=~\"springboot-app-.+\"}) by (pod))",
     "legendFormat": "Springboot Mem Usage (Avg) "
    }
   ]
  },
  {
   "title": "# Replicas",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"${userid}-staging\", pod=~\"quarkus-app.+\", phase=\"Running\"})",
     "legendFormat": "Quarkus # Replicas"
    },
    {
     "expr": "count(kube_pod_status_phase{namespace=\"${userid}-staging\", pod=~\"micronaut-app.+\", phase=\"Running\"})",
     "legendFormat": "Micronaut # Replicas"
    },
    {
     "expr": "count(kube_pod_status_phase{namespace=\"${userid}-staging\", pod=~\"springboot-app.+\", phase=\"Running\"})",
     "legendFormat": "Springboot # Replicas"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(revision_app_request_count{namespace=\"$${userid}-staging\", revision_name=~\"quarkus-app.*\", configuration_name=~\"quarkus-app.*\", container_name=\"queue-proxy\"}[1m]))",
     "legendFormat": "Quarkus # reqs/min"
    },
    {
     "expr": "sum(rate(revision_app_request_count{namespace=\"${userid}-staging\", revision_name=~\"micronaut-app.*\", configuration_name=~\"micronaut-app.*\", container_name=\"queue-proxy\"}[1m]))",
     "legendFormat": "Micronaut # reqs/min"
    },
    {
     "expr": "sum(rate(revision_app_request_count{namespace=\"${userid}-staging\", revision_name=~\"springboot-app.*\", configuration_name=~\"springboot-app.*\", container_name=\"queue-proxy\"}[1m]))",
     "legendFormat": "Springboot # reqs/min"
    }
   ]
  }
 ]
}