= Service Telemetry Framework - OpenStack all-in-one 

== Overview
One of the central pieces when operating a Red Hat OpenStack environment is the monitoring system. You can use the centralized information in your monitoring system as the source for alerts, visualization, or the source of truth for orchestration frameworks. Service Telemetry Framework (STF) is an application that runs on Red Hat OpenShift Container Platform (OCP) that provides metrics and events data collection from OpenStack infrastructure, fast and reliable transport of data, and built-in data storage and alerting capabilities.

This config deploys an OSP 16.1 standalone connected to an OpenShift Container Platorm standalone (using codeready containers) with STF installed on top.

OSP 16.1 is using the following installation parameters:
- OVS instead of OVN
- Heat service is installed

== Supported Cloud Providers

* OpenStack

== Ansible prerequisites ==

This config uses ipaddr() filter migrated to the ansible.netcommon collection. 

[source,bash]
.Make use to install netcommon collection using the following command:
----
ansible-galaxy collection install ansible.netcommon
----

If this command can't be executed in the ansible controller set the variable create_demo_provider_network to false. The demo executor will then have to create the demo provider network when provisioning demo vms.

== Environment Configuration

The link:./default_vars.yml[./default_vars.yml] file contains all the variables needed to control the deployment of your environment.

These can be over-ridden at `ansible-playbook` runtime using the `-e` option or by passing a custom variable file using the file syntax `-e @my_env_vars.yml`

== Running Ansible Playbook

To get started on OpenStack, please read link:../../../docs/First_OSP_Env_walkthrough.adoc[First OSP Env warlkthrough].

== Secrets configuration ==

For installing Code Ready Container instance, you will need a valid OpenShift user pull secret (codeready_containers_hacks_pull_secret_content variable). Copy or download the pull secret from the Pull Secret section of the https://cloud.redhat.com/openshift/install/crc/installer-provisioned [Install on Laptop: Red Hat CodeReady Containers] page on cloud.redhat.com.

For installing Red Hat Openstack, you will also need credentials to access registry.redhat.io content. For more information, see [https://access.redhat.com/RegistryAuthentication] "Red Hat Container Registry Authentication" (registry.redhat.io: username: USER_CHANGEME, token: TOKEN_CHANGEME)

[source,bash]
.Update your secrets file with the secrets_example_osp.yml
----
cp configs/osp-stf/sample_variables/secrets_example_osp.yml \
  ~/secrets_example_osp.yml
vim ~/secrets_example_osp.yml @~/secrets.yml
----

=== Deploying the config

You can deploy this config by running the following command from the `ansible`
directory. You will have to provide credentials and adjust settings to your own
environment.

Example workflow executing agnosticD with custom variables:

[source,bash]
.Create your own copy of sample_vars.yml
----
cp configs/osp-stf/default_vars.yml \
  configs/osp-stf/my_vars.yml
----

[source,bash]
.Run agnosticd provision
----
ansible-playbook main.yml \
  -e @configs/osp-stf/my_vars.yml \
  -e @~/secrets.yml
----

=== To Delete an environment

To delete an environment, just run `destroy.yml` instead of `main.yml` with the same set of variables.

[source,bash]
.Run agnosticd destroy
----
ansible-playbook destroy.yml \
  -e @configs/osp-stf/my_vars.yml \
  -e @~/secrets.yml
----
