= ocp4-workload-debug-workshop - Deploy Debugging Workshop to OpenShift

== Role overview

* This role enables the Workshop Operator on an OpenShift 4 Cluster. It consists of the following tasks files:
** Tasks: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an
 environment for the workload deployment.
*** Debug task will print out: `pre_workload Tasks completed successfully.`

** Tasks: link:./tasks/workload.yml[workload.yml] - Used to deploy the Workshop Operator and then deploy a Workshop instance
*** Debug task will print out: `workload Tasks completed successfully.`

** Tasks: link:./tasks/post_workload.yml[post_workload.yml] - Used to
 configure the workload after deployment
*** This role doesn't do anything here
*** Debug task will print out: `post_workload Tasks completed successfully.`

** Tasks: link:./tasks/remove_workload.yml[remove_workload.yml] - Used to
 delete the workload
*** This role removes the Workshop Instance and Workshop operator from OCP 4. This role does *not* remove the project - there may be other items in it.
*** Debug task will print out: `remove_workload Tasks completed successfully.`

== Review the defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you need to define to control the deployment of your workload.
* The variable *ocp_username* is mandatory to assign the workload to the correct OpenShift user.
* A variable *silent=True* can be passed to suppress debug messages.
* You can modify any of these default values by adding `-e "variable_name=variable_value"` to the command line

== Workshop Custom Resource

The operator uses a custom resource *workshops.openshift.redhat.com/v1alpha1* to set the quota for all users in the cluster. Variables are in defaults/main.yaml and can be overwritten by setting them globally.

[source,yaml]
----
apiVersion: openshift.redhat.com/v1alpha1
kind: Workshop
metadata:
  name: debugging-workshop
spec:
  users: {{ workshop_users }}
  etherpad:
    enabled: {{ workshop_etherpad_enabled }}
  gogs:
    enabled: {{ workshop_gogs_enabled }}
  nexus:
    enabled: {{ workshop_nexus_enabled }}
  servicemesh:
    enabled: {{ workshop_servicemesh_enabled }}
    jaegerOperatorImage: {{ workshop_servicemesh_jaegerOperatorImage }}
    kialiOperatorImage: {{ workshop_servicemesh_kialiOperatorImage }}
    istioOperatorImage: {{ workshop_servicemesh_istioOperatorImage }}
  guide:
    enabled: {{ workshop_guide_enabled }}
    openshiftConsoleUrl: {{ workshop_guide_openshiftConsoleUrl }}
    openshiftApiUrl: {{ workshop_guide_openshiftApiUrl }}
    openshiftUserPassword: {{ workshop_guide_openshiftUserPassword }}
    gitRepositoryLabPath: {{ workshop_guide_gitRepositoryLabPath }}
    gitRepositoryLabReference: {{ workshop_guide_gitRepositoryLabReference }}
    gitRepositoryGuidePath: {{ workshop_guide_gitRepositoryGuidePath }}
    gitRepositoryGuideReference: {{ workshop_guide_gitRepositoryGuideReference }}
    gitRepositoryGuideContext: {{ workshop_guide_gitRepositoryGuideContext }}
    gitRepositoryGuideFile: {{ workshop_guide_gitRepositoryGuideFile }}
  workspaces:
    enabled: {{ workshop_workspaces_enabled }}
    openShiftoAuth: {{ workshop_workspaces_openShiftoAuth }}
----

=== Deploy a Workload with the `ocp4-workload` playbook [Mostly for testing]
                   
----
GUID=d071
TARGET_HOST="bastion.${GUID}.example.opentlc.com"
WORKLOAD="ocp4-workload-debugging-workshop"
AWS_REGION="eu-west-1"

ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml    \
  -e"ansible_python_interpreter=/opt/virtualenvs/k8s/bin/python"   \
  -e"ansible_ssh_private_key_file=~/.ssh/id_rsa"    \
  -e"ansible_user=mcouliba-redhat.com"   \
  -e"ocp_workload=${WORKLOAD}"  \
  -e"silent=False"  \
  -e"guid=${GUID}"   \
  -e"aws_region=${AWS_REGION}" \
  -e"subdomain_base=${TARGET_HOST}" \
  -e"ACTION=create"
----

=== To Delete an environment

----
GUID=d071
TARGET_HOST="bastion.${GUID}.example.opentlc.com"
WORKLOAD="ocp4-workload-debugging-workshop"
AWS_REGION="eu-west-1"

ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml    \
  -e"ansible_python_interpreter=/opt/virtualenvs/k8s/bin/python"   \
  -e"ansible_ssh_private_key_file=~/.ssh/id_rsa"    \
  -e"ansible_user=mcouliba-redhat.com"   \
  -e"ocp_workload=${WORKLOAD}"  \
  -e"silent=False"  \
  -e"guid=${GUID}"   \
  -e"aws_region=${AWS_REGION}" \
  -e"subdomain_base=${TARGET_HOST}" \
  -e"ACTION=remove"
----


== Other related information:

=== Deploy Workload on OpenShift Cluster from an existing playbook:

[source,yaml]
----
- name: Deploy a workload role on a master host
  hosts: all
  become: true
  gather_facts: False
  tags:
    - step007
  roles:
    - { role: "{{ocp_workload}}", when: 'ocp_workload is defined' }
----
NOTE: You might want to change `hosts: all` to fit your requirements


=== Set up your Ansible inventory file

* You can create an Ansible inventory file to define your connection method to your host (Master/Bastion with `oc` command)
* You can also use the command line to define the hosts directly if your `ssh` configuration is set to connect to the host correctly
* You can also use the command line to use localhost or if your cluster is already authenticated and configured in your `oc` configuration

.Example inventory file
[source, ini]
----
[gptehosts:vars]
ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem
ansible_user=ec2-user

[gptehosts:children]
openshift

[openshift]
bastion.cluster1.openshift.opentlc.com
bastion.cluster2.openshift.opentlc.com
bastion.cluster3.openshift.opentlc.com
bastion.cluster4.openshift.opentlc.com

[dev]
bastion.cluster1.openshift.opentlc.com
bastion.cluster2.openshift.opentlc.com

[prod]
bastion.cluster3.openshift.opentlc.com
bastion.cluster4.openshift.opentlc.com
----
