= OCP Client VM (ocp-clientvm) Standard Config

== Review the Env_Type variable file

* This file link:./env_vars.yml[./env_vars.yml] contains all the variables you need to define to control the deployment of your environment.

== Running Ansible Playbook

=== Running Playbook With Environment and Secrets files

You can create yaml files of your desired configs and secrets and execute them:

`ansible-playbook ansible/main.yaml -e @myenvironment-variables.yml  -e@judd_secret.yml`

=== Running with Env from command line

You can run the playbook with the following arguments to overwrite the default variable values:

[source,bash]
----
GUID=sborenstest1
REGION=us-east-1
KEYNAME=ocpkey
ENVTYPE="ocp4-shared"
CLOUDPROVIDER=ec2
HOSTZONEID='Z3IHLWJZOU9SRT'
BASESUFFIX='.example.opentlc.com'
OSRELEASE=3.11.43
REPO_VERSION=3.11

ansible-playbook ansible/main.yml \
  -e "guid=${GUID}" \
  -e "env_type=${ENVTYPE}" \
  -e "osrelease=${OSRELEASE}" \
  -e "repo_version=${REPO_VERSION}" \
  -e "cloud_provider=${CLOUDPROVIDER}" \
  -e "aws_region=${REGION}" \
  -e "HostedZoneId=${HOSTZONEID}" \
  -e "key_name=${KEYNAME}" \
  -e "subdomain_base_suffix=${BASESUFFIX}" \
  -e "software_to_deploy=none" -e@../secret.yml



=== To Delete an environment
----
REGION=us-east-1
KEYNAME=ocpkey
GUID=testclientvm1
ENVTYPE="ocp-clientvm"
CLOUDPROVIDER=ec2
HOSTZONEID='Z186MFNM7DX4NF'

ansible-playbook ./configs/${ENVTYPE}/destroy_env.yml \
 -e "guid=${GUID}" \
 -e "env_type=${ENVTYPE}"  \
 -e "cloud_provider=${CLOUDPROVIDER}" \
 -e "aws_region=${REGION}" \
 -e "HostedZoneId=${HOSTZONEID}" \
 -e "key_name=${KEYNAME}" \
 -e "subdomain_base_suffix=${BASESUFFIX}"
----
