= ai_setup_nvidia_cuda

This role will install NVIDIA drivers and their CUDA Toolkit on the target machine(s). 

It currently supports:

- RHEL 9 (tested aginst RHEL 9.3)
- Fedora (tested against Fedora 39)

In addition it stores a small number of pre-requsities (e.g. `gcc`) that are required for the installation of the NVIDIA drivers and CUDA Toolkit.

== Role Variables

This role is entirely self container ie is _fire and forget_ and does not require any variables to be set.

However the following link:./defaults/main.yml[variables] can be set to control the installation:
+

[source,sh]
----
# Common Vars (to both RHEL and Fedora)

ai_setup_nvidia_cuda_python_version:
ai_setup_nvidia_cuda_cuda_version:
ai_setup_nvidia_cuda_debug:

ai_setup_nvidia_cuda_rhel_repos:
ai_setup_nvidia_cuda_common_dnf_packages:

# RHEL Vars

ai_setup_nvidia_cuda_nvidia_rhel_dnf_packages: 
ai_setup_nvidia_cuda_rhel_repos:

# Fedora Vars

ai_setup_nvidia_cuda_fedora_version:
ai_setup_nvidia_cuda_nvidia_fedora_dnf_packages: 

----

== Dependencies

None

== Example Playbook

Including an example of how to use your role (for instance, with variables passed in as parameters) is always nice for users too:

[source,yaml]
----
---
- name: Test EDA dispatcher
  hosts: localhost
  gather_facts: true
  become: true

  roles:
    - ai_setup_nvidia_cuda
----

== Author Information

Tony Kay (tok@redhat.com) 2024-04-25