== Overview

*ansible-rhel-workshop* is a deployment of multiple systems to support a series of introductory exercises highlighting Red Hat Enterprise Linux 9

Source for the workshop is available at:

https://github.com/xtophd/RHEL9-Workshop

== Supported Cloud Providers (`cloud_provider`)

* AWS EC2         # `cloud_provider: ec2`
* OSP (Novello)   # `cloud_provider: osp`

== Deploying the `ansible-rhel-workshop` config

You can deploy this config by running the following command from the `ansible`
directory. You will have to provide credentials and adjust settings to your own
environment.

`ansible-playbook main.yml -e @configs/ansible-rhel-workshop/sample_vars_ec2.yml -e @<YOUR_SECRET_VARS.yml>`


=== Sample Var files

A number of sample var files are provided for both OpenStack and AWS:



=== To Delete an environment
----
`ansible-playbook destroy.yml -e @configs/ansible-rhel-workshop/sample_vars_ec2.yml -e @<YOUR_SECRET_VARS.yml>`

----

=== History

* the ansible-rhel-workshop config had it's origin from the ansible-multitier-infra config.  There may continue to be
  variables that have not been removed or cleaned up.


