:config: insights-technical-sales
:author1: Wilson Harris <wharris@redhat.com>
:team: GPTE DevOps & Automation

Config Name: {config}
=====================

The {config} config deploys bastion, Ansible tower, Satellite and RHEL host on OpenStack cloud providers.


Requirements
------------

* Following are the requirements:
. Yum repositories are required for control and node host.
. OSP credentials are required. 
. openstacksdk and apypie python modules required.

Config Variables
----------------

. Cloud specific settings related variables.
+
[cols="4",options="header"]
|===
|*Variable* | *State* | *Default* |*Description*
| env_type: "string"| Required | None| Name of the config (smart-management)
| output_dir: "path string" |Required | /tmp/workdir | Writable working scratch directory
| email: "string" | Required | smart-management@example.com | User info for notifications
| guid: "string" | Reqired |defaultguid |Unique identifier
| cloud_provider: "string" |Required   | osp      | Which AgnosticD Cloud Provider to use
|rhel_repos: [list] |Required | Default  | List for rhel repos
|===

Example variables and values
----------------------------

. Sample of sample_osp_vars.yml
+
[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible
[user@desktop ~]$ cat ./configs/insights-technical-sales/sample_osp_vars.yml
env_type: insights-technical-sales
output_dir: /tmp/workdir              # Writable working scratch directory
email: smart-management@example.com
cloud_provider: osp
guid: defaultguid

student_name: student
student_password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
lab_user: devops
----

. Sample of secrets.yml
+
[source=text]
----
[user@desktop ~]$ cat ~/secrets.yml
osp_auth_url: http://x.x.x.x:5000/v3
osp_auth_username: admin
osp_auth_password: "xxxxxxxxxxxxxxxxxxxxxxxxx"
osp_auth_project_domain: "default"
osp_auth_user_domain: "default"
osp_cluster_dns_zone: xxxxxxx.osp.opentlc.com
ddns_key_name: xxxxxxxxxxxxx
ddns_key_secret: "xxxxxxxxxxxxxxxxxxxxxx"
own_repo_path: http://some.yum.com/repos/
----

Examples, How to use config 
---------------------------

. How to deploy {config} config.
+
[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible
[user@desktop ~]$ ansible-playbook  main.yml \
  -e @./configs/smart-management/sample_vars_osp.yml \
  -e @~/secrets.yml \
  -e guid=<Alphanum>  
----

. How to destroy deployed environment 
+
[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible
[user@desktop ~]$ ansible-playbook  ./configs/smart-management/destroy.yml \
  -e @./configs/smart-management/sample_vars_osp.yml \
  -e @~/secrets.yml \
  -e guid=defaultguid 
----

Author Information
------------------

* Author/owner:
** {author1}

* Team:
** {team}
