= ocp4-workload-quarkus-super-heroes-demo - Deploy Quarkus Superheroes Demo into OCP4

== Role overview
This role deploys the https://github.com/quarkusio/quarkus-super-heroes/tree/rhbq-2.7[Quarkus Superheroes Sample application], using Red Hat Build of Quarkus, to OCP4.

3 projects are created in the cluster:

* `quarkus-superheroes-java11`
** Contains https://github.com/quarkusio/quarkus-super-heroes/blob/rhbq-2.13/deploy/k8s/java11-openshift.yml[JVM Java 11 version of the system]
* `quarkus-superheroes-java17`
** Contains https://github.com/quarkusio/quarkus-super-heroes/blob/rhbq-2.13/deploy/k8s/java17-openshift.yml[JVM Java 17 version of the system]
* `quarkus-superheroes-native`
** Contains https://github.com/quarkusio/quarkus-super-heroes/blob/rhbq-2.13/deploy/k8s/native-openshift.yml[Native version of the system]

This role additionally deploys https://access.redhat.com/documentation/en-us/red_hat_amq_streams[Red Hat AMQ Streams]. A separate Kafka cluster is deployed into each project. The applications within each project are reconfigured to use the AMQ Streams cluster within its project.

A Prometheus instance is also deployed in each project to monitor everything.

----
WORKLOAD="ocp4_workload_quarkus_super_heroes_demo"
OCP_USERNAME="opentlc-mgr"
GUID=gq4jj
SANDBOX_NUMBER=1438
TARGET_HOST="bastion.${GUID}.sandbox${SANDBOX_NUMBER}.opentlc.com"
SSH_KEY=~/.ssh/id_rsa
ANSIBLE_USER=lab-user

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
                    -e"ansible_ssh_private_key_file=${SSH_KEY}" \
                    -e"ansible_user=${ANSIBLE_USER}" \
                    -e"ocp_workload=${WORKLOAD}" \
                    -e"silent=False" \
                    -e"ACTION=create" \
                    -e"ocp_username=${OCP_USERNAME}" \
                    -e"guid=${GUID}" \
                    -e"subdomain_base=${TARGET_HOST}"
----

[NOTE]
====
If you haven't already downloaded the key into your ssh keys, you need to first run

----
ssh-copy-id ${ANSIBLE_USER}@${TARGET_HOST}
----
====