= ocp4-workload-camel3-workshop: Workshop - Camel 3

== Role overview

* This is a simple role that does the following:
** Tasks: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an
 environment for the workload deployment
*** Adds a user to a list of groups defined in the
 link:./defaults/main.yml[defaults file].
*** Sets a cluster resource quota for the user based on the variables in the
 link:./defaults/main.yml[defaults file] .
*** Debug task will print out: `pre_workload Tasks Complete`

** Tasks: link:./tasks/workload.yml[workload.yml] - Used to deploy the actual
 workload, i.e, Camel K, AMQ Streams or some Demo
*** This role doesn't do anything here
*** Debug task will print out: `workload Tasks Complete`

** Tasks: link:./tasks/post_workload.yml[post_workload.yml] - Used to
 configure the workload after deployment
*** This role doesn't do anything here
*** Debug task will print out: `post_workload Tasks Complete`



== Deploy the workload with the `ocp-workload` playbook [Mostly for testing]

The instructions below assume you have provisioned an OCP instance (tested with OCP 4.10), using RHPDS, and a bastion server is available.

* An example `user@bastion_server` would be:
+
----
lab-user@bastion.b9ck5.sandbox1880.opentlc.com
----

=== Steps

1. Generate an SSH Key
+
Generate an authorised key if you don't have one already.
+
With OpenSSH, an SSH key is created using ssh-keygen.
+
In the simplest form, just run `ssh-keygen` and answer the questions. 
+
Creating a key pair (public key and private key) only takes a minute. The key files are usually stored in the ~/.ssh directory.
+
{empty} +

1. Install the public key in the bastion server
+
----
ssh-copy-id -i ~/.ssh/my_public_key lab-user@bastion.b9ck5.sandbox1880.opentlc.com
----
+
{empty} +

1. Test the authorised key
+
----
ssh lab-user@bastion.b9ck5.sandbox1880.opentlc.com
----
+
The login should now complete without asking for a password.
+
Make sure you exit the bastion server after your test.
+

{empty} +


1. Set the following properties:
+
----
TARGET_HOST="lab-user@bastion.b9ck5.sandbox1880.opentlc.com"
OCP_USERNAME="opentlc-mgr"
WORKLOAD="ocp4-workload-camel3-workshop"
GUID=5432
USER_COUNT=1
----
+
NOTE: in the properties above, the default value for `USER_COUNT` is 1. Change this value if you want to test with more users. 
+
{empty} +

1. Deploy the workload
+
To execute the ansible creation playbook, run:
+
----
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
-e"ansible_ssh_private_key_file=~/.ssh/id_rsa" \
-e"ansible_user=lab-user" \
-e"ocp_username=${OCP_USERNAME}" \
-e"ocp_workload=${WORKLOAD}" \
-e"guid=${GUID}" \
-e"num_users=${USER_COUNT}" \
-e"ACTION=create"
----

{empty} +

=== To Delete an environment

To delete the deployment, run:

----
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
-e"ansible_ssh_private_key_file=~/.ssh/id_rsa" \
-e"ansible_user=lab-user" \
-e"ocp_username=${OCP_USERNAME}" \
-e"ocp_workload=${WORKLOAD}" \
-e"guid=${GUID}" \
-e"num_users=${USER_COUNT}" \
-e"ACTION=remove"
