--
- name: Get the current nodes
  kubernetes.core.k8s_info:
    api_version: v1
    validate_certs: false
    kind: Node
    label_selectors:
      - "node-role.kubernetes.io/worker="
  register: r_worker_nodes

- name: Count Ready nodes
  set_fact:
    ready_nodes_count: >-
      {{ r_worker_nodes
         | json_query("resources[].status.conditions[?type=='Ready' && status=='True']")
         | length }} }}

- name: Approve CertificateSigningRequests
  include_role:
    name: ocp4_approve_certificate_signing_requests

- name: Include this tasks again if nodes doesn't appear
  include_tasks: approve_csr_nodes.yaml
  when: "{{ current_instance_workers+worker_instance_count != _r_node_status|length }}"
