---
- name: Get the current nodes
  kubernetes.core.k8s_info:
    api_version: v1
    validate_certs: false
    kind: Node
    label_selectors:
      - "node-role.kubernetes.io/worker="
  register: r_worker_nodes

- name: Count Ready nodes
  set_fact:
    ready_nodes_count: >-
      {{ r_worker_nodes
         | json_query("resources[].status.conditions[?type=='Ready' && status=='True']")
         | length }}


- name: Approve CSR
  module_defaults:
    group/k8s:
      host: "{{ openshift_api_url }}"
      api_key: "{{ r_k8s_auth_results.k8s_auth.api_key }}"
      validate_certs: false
  block:
    - name: Get pending CSRs
      kubernetes.core.k8s_info:
        api_version: certificates.k8s.io/v1
        kind: CertificateSigningRequest
      register: all_csrs

    - name: Filter for pending CSRs
      set_fact:
        pending_csrs: "{{ all_csrs.resources | selectattr('status', 'eq', {}) | list }}"

    - name: Approve each pending CSR
      kubernetes.core.k8s_json_patch:
        api_version: certificates.k8s.io/v1
        host: "{{ openshift_api_url }}"
        api_key: "{{ r_k8s_auth_results.k8s_auth.api_key }}"
        validate_certs: false
        kind: CertificateSigningRequest
        name: "{{ item.metadata.name }}"
        patch:
          - op: replace
            path: /status
            value:
              conditions:
                - type: Approved
                  status: "True"
                  reason: "AnsibleApproval"
                  message: "CSR was approved by Ansible automation."
      loop: "{{ pending_csrs }}"
      when: pending_csrs is defined and pending_csrs | length > 0

- name: Include this tasks again if nodes doesn't appear
  when: current_instance_workers|int+worker_instance_count|int != _r_node_status|length
  block:
    - name: Wait for additional CertificateSigningRequests to appear
      pause:
        seconds: "60"
    - include_tasks: approve_csr_nodes.yaml
