---
- name: Log in (obtain access token)
  community.okd.openshift_auth:
    username: "{{ sandbox_openshift_username }}"
    password: "{{ sandbox_openshift_password }}"
    host: "{{ sandbox_openshift_api_url }}"
  register: k8s_auth_results
  when: sandbox_openshift_username | default(false)

- name: Destroy OCP using Assisted Installed
  module_defaults:
    group/k8s:
      host: "{{ sandbox_openshift_api_url }}"
      api_key: "{{ k8s_auth_results.k8s_auth.api_key|default(sandbox_openshift_api_key) }}"
      validate_certs: false

  block:
    - name: Get a list of clusters
      rhpds.assisted_installer.list_clusters:
        offline_token: "{{ ai_offline_token }}"
        owner: true
      register: listclusters

    - name: Filter the created clusters
      ansible.builtin.set_fact:
        cluster_id: "{{ item.id }}"
      when: item.name == cluster_name
      loop: "{{ listclusters.result }}"
      loop_control:
        label: "{{ item.name }}"
