---
- name: Remove X-Frame-Options header from default ingresscontroller
  kubernetes.core.k8s:
    api_version: operator.openshift.io/v1
    kind: IngressController
    name: default
    namespace: openshift-ingress-operator
    merge_type: merge
    definition:
      spec:
        httpHeaders:
          actions:
            response:
              - name: X-Frame-Options
                action:
                  type: Delete

- name: Get service-ca.crt from v4-0-config-system-service-ca ConfigMap
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ConfigMap
    name: v4-0-config-system-service-ca
    namespace: openshift-authentication
  register: service_ca_cm

- name: Extract service-ca.crt content
  set_fact:
    service_ca_crt: "{{ service_ca_cm.resources[0].data['service-ca.crt'] }}"

- name: Get definition of oauth-openshift Route
  kubernetes.core.k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: oauth-openshift
    namespace: openshift-authentication
  register: oauth_route

- name: Create oauth-openshift-showroom Route with reencrypt TLS and service-ca.crt
  kubernetes.core.k8s:
    api_version: route.openshift.io/v1
    kind: Route
    namespace: openshift-authentication
    definition: >-
      {{
        {
          "apiVersion": "route.openshift.io/v1",
          "kind": "Route",
          "metadata": {
            "name": "oauth-openshift-showroom",
            "namespace": "openshift-authentication",
            "labels": oauth_route.resources[0].metadata.get("labels", {}),
            "annotations": oauth_route.resources[0].metadata.get("annotations", {})
          },
          "spec": oauth_route.resources[0].spec | combine({
            "tls": {
              "termination": "reencrypt",
              "destinationCACertificate": service_ca_crt
            }
          }, recursive=True)
        }
      }}

- name: Delete original oauth-openshift Route
  kubernetes.core.k8s:
    api_version: route.openshift.io/v1
    kind: Route
    name: oauth-openshift
    namespace: openshift-authentication
    state: absent
