---
- name: Get current authentication-operator deployments
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    namespace: openshift-authentication-operator
    label_selectors:
      - app=authentication-operator
  register: auth_operator_deployments

- name: Save current authentication-operator revision
  set_fact:
    old_revision: "{{ auth_operator_deployments.resources[0].metadata.annotations['deployment.kubernetes.io/revision'] }}"

- name: Remove X-Frame-Options header from default ingresscontroller
  kubernetes.core.k8s:
    api_version: operator.openshift.io/v1
    kind: IngressController
    name: default
    namespace: openshift-ingress-operator
    merge_type: merge
    definition:
      spec:
        httpHeaders:
          actions:
            response:
              - name: X-Frame-Options
                action:
                  type: Delete

- name: Get service-ca.crt from v4-0-config-system-service-ca ConfigMap
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ConfigMap
    name: v4-0-config-system-service-ca
    namespace: openshift-authentication
  register: service_ca_cm

- name: Extract service-ca.crt content
  set_fact:
    service_ca_crt: "{{ service_ca_cm.resources[0].data['service-ca.crt'] }}"

- name: Wait for authentication-operator to apply new OAuth config
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: authentication-operator
    namespace: openshift-authentication-operator
  register: new_auth_operator
  until: >
    new_auth_operator.resources[0].metadata.annotations['deployment.kubernetes.io/revision'] != old_revision
  retries: 30
  delay: 10

- name: Ensure the authentication-operator rollout completed
  command: >
    oc rollout status deployment/authentication-operator -n openshift-authentication-operator

- name: Scale down authentication-operator deployment
  kubernetes.core.k8s:
    api_version: apps/v1
    kind: Deployment
    name: authentication-operator
    namespace: openshift-authentication-operator
    definition:
      spec:
        replicas: 0
    merge_type: merge

- name: Add nodeSelector to authentication-operator deployment
  kubernetes.core.k8s:
    api_version: apps/v1
    kind: Deployment
    name: authentication-operator
    namespace: openshift-authentication-operator
    definition:
      spec:
        template:
          spec:
            nodeSelector:
              node-role.kubernetes.io/test: ""
    merge_type: merge

- name: Patch oauth-openshift route to use reencrypt and service-ca.crt
  kubernetes.core.k8s:
    api_version: route.openshift.io/v1
    kind: Route
    name: oauth-openshift
    namespace: openshift-authentication
    definition:
      spec:
        tls:
          termination: reencrypt
          destinationCACertificate: "{{ service_ca_crt }}"
    merge_type: merge
