== container_service_deploy

`container_service_deploy` allows a RHEL, CentOS, Fedora host, to be configured with a `podman` based service.
For example a webserver or gitlab service running in one or more containers.
Or a lab frontend like GPTE's `classroom` providing interactive web browser with embedded terminal functionality etc.
It creates, enables, and starts a systemd `podman` based service.
It consumes a user provided `docker-compose` file, currently via Python's `podman-compose` package.
In the future this will be replaced via Podman 3's direct support for the compose format.

[source,sh]
----
  hosts: container_servers

  roles:
    - roles: container_service_deploy
      become: true
----


`container_service_deploy` *expects*

* A RHEL 8 or equivalent server
* A `container_service_deploy_url` pointing to either a tar archive *or* git repo
** Either the archive or repo which *MUST* contain a `resources/orchestration/docker-compose.yml`
** An example repo can be found link: https://github.com/tonykay/dojo-demo.git[here] with additional example resources.

The role installs and configures `podman` and supporting packages
[NOTE]
====
This roles does *not* configure any Firewall routes or underlying Security Groups in for example a cloud configuration.
The service may expose as many external ports as configured but the underlying server(s) must be configured for the appropriate access. 
Typically achieved in an AgnosticD configs `default_vars_<CLOUD_PROVIDER>.yml`
====

=== Role Flow

* Ensure pre-requisites are installed
** Linux RPM Packages, `container_service_deploy_linux_packages`, (e.g. podman, git)
** Python Pip Packages, `container_service_deploy_pip_packages` (e.g. podman-compose)
* Configure, if necessary, `podman`
* Install remote resources locally via `container_service_deploy_url`
** orchestration and any other resources e.g. bind_mounts, HTML etc
+
[NOTE]
====
The role can determine if the `container_service_deploy_url` points to a tar archive (`.tar`, or `.tar.gz`).
If *not* it assumes the URL points to a git repo
====
* Create systemd service
** Create service `container_compose_service_name`
** Enable service
** Start service

=== Requirements

Ansible 2.9 or greater

=== Role Variables



Ensure host has `podman` and Python 3 (Needed by `podman-compose`).
Set in `defaults/main.yml`

```
container_compose_packages:
  - podman
  - python3 # Assumes RHEL 8, RHEL may require `rh-python36` or similar. Not tested
```

Ensure host has `podman` and Python `podman-compose`
[NOTE]
====

`podman` 2 and earlier do not provide the ability to *directly* consume `docker-compose` files.
This feature is being added in `podman` 3.
For `podman` 2 installs orchestration is achieved by the Python package link:https://pypi.org/project/podman-compose/[podman-compose].
This is reflected in the `jinja` service template

====


`container_compose_python_packages`
`container_compose_resource_type`
* `git`
* `tar_archive`
`container_compose_service_name`

Dependencies
------------

None

[NOTE]
====
The role *does not* use the `container.podman` collection as it relies entirely on the Linux SystemD Service to activate, deactivate the service(s).
So this is not a dependency.

Example Playbook
----------------

Including an example of how to use your role (for instance, with variables passed in as parameters) is always nice for users too:

    - hosts: servers
      roles:
         - azure_ansible_execution_env

License
-------

BSD

Author Information
------------------

Original author: Tony Kay (tok) tok@redhat.com
tasks/download_and_configure_podman_payload.yml:- name: Set container_service_deploy_payload_type
tasks/download_and_configure_podman_payload.yml:    container_service_deploy_payload_type: >-
tasks/download_and_configure_podman_payload.yml:      {% if container_service_deploy_url.endswith('.tar')
tasks/download_and_configure_podman_payload.yml:           or container_service_deploy_url.endswith('.tar.gz') -%}
tasks/download_and_configure_podman_payload.yml:    path: "/opt/{{ container_service_deploy_name }}"
tasks/download_and_configure_podman_payload.yml:      when: container_service_deploy_payload_type == 'tar'
tasks/download_and_configure_podman_payload.yml:        src: "{{ container_service_deploy_url }}"
tasks/download_and_configure_podman_payload.yml:        dest: "/opt/{{ container_service_deploy_name }}"
tasks/download_and_configure_podman_payload.yml:      when: container_service_deploy_payload_type == 'git'
tasks/download_and_configure_podman_payload.yml:        repo: "{{ container_service_deploy_url }}"
tasks/download_and_configure_podman_payload.yml:        dest: "/opt/{{ container_service_deploy_name }}"
tasks/download_and_configure_podman_payload.yml:    dest: "/etc/systemd/system/{{ container_service_deploy_name | default('podman') }}.service"
tasks/download_and_configure_podman_payload.yml:    name: "{{ container_service_deploy_name | default('podman') }}.service"
tasks/install_podman_packages.yml:        name: "{{ container_service_deploy_linux_packages }}"
tasks/install_podman_packages.yml:        name: "{{ container_service_deploy_pip_packages }}"
tasks/main.yml:- name: If container_service_deploy_url IS set
tasks/main.yml:    container_service_deploy_url is defined
tasks/main.yml:    and container_service_deploy_url | length > 0
tasks/main.yml:- name: If container_service_deploy_url IS NOT set or valid
tasks/main.yml:    container_service_deploy_url is not defined
tasks/main.yml:    or container_service_deploy_url | length == 0
tasks/main.yml:      - No container_service_deploy_url defined or invalid
