---
- name: Pre workload tasks - Student provisioning
  ansible.builtin.debug:
    msg: "Provisioning {{ ocp4_workload_advanced_developer_suite_user_count }} students for Advanced Developer Suite"

- name: Verify platform role has been deployed
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    name: "{{ ocp4_workload_advanced_developer_suite_dh_namespace }}"
  register: r_dh_namespace
  failed_when: r_dh_namespace.resources | length == 0

- name: Verify Keycloak is deployed
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    name: "{{ ocp4_workload_advanced_developer_suite_keycloak_namespace }}"
  register: r_keycloak_namespace
  failed_when: r_keycloak_namespace.resources | length == 0

- name: Verify GitLab is deployed
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    name: "{{ ocp4_workload_advanced_developer_suite_gitlab_namespace }}"
  register: r_gitlab_namespace
  failed_when: r_gitlab_namespace.resources | length == 0
