---
# Add a user to GitLab development group
# User should already exist in GitLab (created by GitLab operator from Keycloak sync)

- name: Wait for GitLab user {{ username }} to be synced from Keycloak
  ansible.builtin.uri:
    url: "{{ _gitlab_url }}/api/v4/users?username={{ username }}"
    method: GET
    headers:
      PRIVATE-TOKEN: "{{ _gitlab_root_token }}"
    validate_certs: false
    status_code: 200
  register: r_gitlab_user
  retries: 30
  delay: 10
  until:
  - r_gitlab_user.json is defined
  - r_gitlab_user.json | length > 0

- name: Add {{ username }} to development group
  ansible.builtin.uri:
    url: "{{ _gitlab_url }}/api/v4/groups/{{ _gitlab_development_group_id }}/members"
    method: POST
    body_format: form-urlencoded
    body:
      user_id: "{{ r_gitlab_user.json[0].id }}"
      access_level: 50
    headers:
      PRIVATE-TOKEN: "{{ _gitlab_root_token }}"
    validate_certs: false
    status_code: [201, 409]
  register: r_group_user
  retries: 10
  delay: 5
  until: r_group_user.status in [201, 409]
