---
# Setup a single student
# Called in a loop for each student

- name: Create Keycloak user {{ student_username }}
  ansible.builtin.include_tasks:
    file: ./setup_keycloak_user.yml
  vars:
    username: "{{ student_username }}"
    keycloak_group_id: "{{ _keycloak_group_id }}"

- name: Create TPA user {{ student_username }}
  ansible.builtin.include_tasks:
    file: ./setup_tpa_user.yml
  vars:
    username: "{{ student_username }}"
    password: "{{ ocp4_workload_advanced_developer_suite_user_password }}"

- name: Add {{ student_username }} to GitLab
  ansible.builtin.include_tasks:
    file: ./setup_gitlab_user.yml
  vars:
    username: "{{ student_username }}"

- name: Deploy showroom for {{ student_username }}
  ansible.builtin.include_tasks:
    file: ./setup_student_showroom.yml
  vars:
    showroom_user: "{{ student_username }}"
    showroom_namespace: "{{ ocp4_workload_showroom_namespace }}-{{ student_username }}"

- name: Report user information for {{ student_username }}
  agnosticd_user_info:
    user: "{{ student_username }}"
    data:
      openshift_admin_user: "{{ ocp4_workload_advanced_developer_suite_admin_user }}"
      openshift_admin_password: "{{ ocp4_workload_advanced_developer_suite_admin_password }}"
      openshift_console_url: "{{ _ocp_console_url }}"
      openshift_api_url: "{{ _ocp_api_url }}"
      rhdh_url: "{{ _dh_url }}"
      rhdh_auth: oidc
      rhdh_user: "{{ student_username }}"
      rhdh_user_password: "{{ ocp4_workload_advanced_developer_suite_user_password }}"
      gitops_url: "{{ _gitops_url }}"
      gitops_admin_user: admin
      gitops_admin_password: "{{ _gitops_admin_password }}"
      gitlab_url: "{{ _gitlab_url }}"
      gitlab_user: "{{ student_username }}"
      gitlab_user_password: "{{ ocp4_workload_advanced_developer_suite_user_password }}"
      devspaces_url: "{{ _devspaces_url }}"
      devspaces_user: "{{ student_username }}"
      devspaces_user_password: "{{ ocp4_workload_advanced_developer_suite_user_password }}"
      tpa_url: "{{ _tpa_url }}"
      tpa_user: "{{ student_username }}"
      tpa_user_password: "{{ ocp4_workload_advanced_developer_suite_user_password }}"
      quay_url: "{{ _quay_url }}"
      quay_admin_user: "{{ ocp4_workload_advanced_developer_suite_quay_admin_user }}"
      quay_admin_password: "{{ ocp4_workload_advanced_developer_suite_quay_admin_password }}"
      acs_url: "{{ _acs_url }}"
      acs_admin_user: "{{ ocp4_workload_advanced_developer_suite_acs_admin_user }}"
      acs_admin_password: "{{ _acs_admin_password }}"
      showroom_url: "https://showroom-{{ showroom_namespace }}.{{ _ocp_apps_domain }}"
