---
# Student provisioning workload
# Requires platform to be deployed first

- name: Retrieve platform configuration
  ansible.builtin.include_tasks:
    file: ./retrieve_platform_facts.yml

- name: Provision students
  ansible.builtin.include_tasks:
    file: ./setup_student.yml
  vars:
    student_username: "{{ ocp4_workload_advanced_developer_suite_user_base_name }}{{ n + 1 }}"
    student_number: "{{ n + 1 }}"
  loop: "{{ range(0, ocp4_workload_advanced_developer_suite_user_count | int) | list }}"
  loop_control:
    loop_var: n
    label: "{{ ocp4_workload_advanced_developer_suite_user_base_name }}{{ n + 1 }}"
