=  A Base Config (a-base-config)

== Overview
This environment is used to deploy any number of RHEL nodes for generic use.
This makes an ideal base infrastructure to build upon.
It is also used as an example complete config for new contributors to Agnostic D.

== Supported Cloud Providers

* AWS
* Azure
* OpenStack

== Environment Configuration

The link:./default_vars.yml[./default_vars.yml] file contains all the variables needed to control the deployment of your environment.

These can be over-ridden at `ansible-playbook` runtime using the `-e` option or by passing a custom variable file using the file syntax `-e @my_env_vars.yml`

The directory `sample_variables` contains example configurations.

== Running Ansible Playbook

To get started on OpenStack, please read link:../../../docs/First_OSP_Env_walkthrough.adoc[First OSP Env warlkthrough].

=== Deploying the config

You can deploy this config by running the following command from the `ansible`
directory. You will have to provide credentials and adjust settings to your own
environment.

Example workflow executing agnosticD with custom variables:

[source,bash]
.Create your own copy of sample_vars.yml
----
cp configs/a-base-config/sample_vars_osp.yml \
  configs/a-base-config/my_vars.yml
----

[source,bash]
.Run agnosticd provision
----
ansible-playbook main.yml \
  -e @configs/a-base-config/my_vars.yml \
  -e @~/secret.yml
----

=== To Delete an environment

To delete an environment, just run `destroy.yml` instead of `main.yml` with the same set of variables.

[source,bash]
.Run agnosticd destroy
----
ansible-playbook destroy.yml \
  -e @configs/a-base-config/my_vars.yml \
  -e @~/secret.yml
----
