---
galaxy_info:
  author: AgnosticD Team
  description: Manages user accounts on Redfish-compliant BMCs
  company: Red Hat
  license: GPL-3.0+
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 8
        - 9
    - name: Ubuntu
      versions:
        - 20.04
        - 22.04
  galaxy_tags:
    - redfish
    - bmc
    - user
    - management
    - baremetal
    - infrastructure

dependencies: [] 