= Variable Deep Dive

This section covers defining typical variables seen within agnosticD var files.

This document focuses on Openstack as the cloud provider. Using direct examples in `rhel8_server_on_osp.yml` & `secrets_example_osp.yml`.

== Mandatory Variables

These two variables are the most important variables to set correctly.

* `cloud_provider` specifies what back-end will be used for deployment. Current options for `cloud_provider` are osp, ec2, and azure.

* `env_type` defines the config name to be deployed.

This is an example variable segment using Openstack as the provider deploying a-base-config.

....
cloud_provider: osp
env_type: a-base-config
....

== Environment Variables

=== GUID & Access Variables

* `guid` is the deployment unique identifier, it will be appended to all infrastructure tags, files, and anything that identifies this environment from another "just like it".

NOTE: `guid` can be set to anything, typically it is set to be a openstack project ID or a developer's initials.

* `email` is the email address of the person who will receive  updates regarding the environment. This is generally automatically handled at the time a catalog item is ordered.

* `output_dir` is a file path to an existing directory that will store information created by the deployment. This location is where you will retrieve ssh keys, ssh files, a copy of the cloud template, and user information after a config is kicked off.

* `admin_user` & `student_name` are created automatically with the provided guid. These values will be used by the environment to create a sudent user.

* `student_password` Change this value to customize the student password. Keep in mind that the system you create may be public facing and avoid using special characters like `@`.

....
guid: wth-01
email: example@example.com
output_dir: /tmp/output_dir
admin_user: "{{ guid }}-user"
student_name: "{{ guid }}-user"
student_password: "r3dh4t1!"
....

=== Networks

Networks are defined by A list of the private networks and subnets to create in the project.

You can create as many as you want, but at least one is required. To add a network simply copy the variables and modify them to your network requirements.

Later on the instance you associate with the network will automatically pull addressees from the allocation.

....
networks:
- name: node_network
  shared: "false"
  subnet_cidr: 192.168.47.0/24
  gateway_ip: 192.168.47.1
  allocation_start: 192.168.47.10
  allocation_end: 192.168.47.254
  dns_nameservers: []
  create_router: true
....

=== Security Groups and Associated Rules

Security groups govern access rules present on each corresponding instance.

Like networks, you can create as many security groups as is needed. These groups will be associated with specific instance groups.

....
security_groups:
- name: node_sg
  description: Node security group allows basic icmp and SSH ingress and egress.
  rules:
  - protocol: icmp
    description: "Ping"
    direction: ingress
    rule_type: Ingress
  - protocol: tcp
    description: "SSH Access"
    direction: ingress
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
    rule_type: Ingress
....

=== Defining Instances

The instances list defines systems to be provisioned in the project.
The values defined here will be used to generate a stack in Openstack.

NOTE: Like networks and security groups, multiple instances can be defined. A complex environment could include `webservers` `balancers` and `databases` as separate instances.

`name` what the systems should be labeled.

`count` The number of this instance to deploy for this environment. Defined by `node_instance_count`

`public_dns` Set the boolean to decide if the system will resolve to public_dns servers.

`floating_ip` Set the boolean for the systems to receive a floating ip address.

`metadata` This list defines Openstack metadata which can be used to differentiate stacks, set ansible groups, and many other tags used for organization and cleanup.

These variables were covered on an earlier page. Here is a quick review.

rhel_image: rhel-8.1                     # Image within OSP to use for systems
node_instance_count: 1                   # The number of nodes to deploy for this environment
node_instance_image: "{{ rhel_image }}"  # Image to use for the node_instance defined in the default_vars.yml
node_instance_type: 2c2g30d              # Existing OSP flavor
node_rootfs_size: 30                     # Size of the root filesystem

....
instances:
- name: node
  count: "{{ node_instance_count }}"
  public_dns: true
  floating_ip: true
  image_id: "{{ node_instance_image }}"
  flavor:
    osp: "{{ node_instance_type }}"
  metadata:
  - AnsibleGroup: "bastions,nodes"
  - function: node
  - user: "{{ student_name }}"
  - ostype: linux
  rootfs_size: "{{ node_rootfs_size }}"
  volumes:
    - name: '/dev/sda1'
      size: 40
  network: node_network
  security_groups:
  - node_sg

# Instance Variables

rhel_image: rhel-8.1
node_instance_count: 1
node_instance_image: "{{ rhel_image }}"
node_instance_type: 2c2g30d
node_rootfs_size: 30
....
