= ansible-tower-advanced lab config

Author: Eric Lavarde <elavarde@redhat.com>
Owner: Eric Lavarde <elavarde@redhat.com>
Alternative Contacts: Goetz Rieger <grieger@redhat.com>

== Overview

This config was create from the ansible-tower config and extended to cover the
Ansible Tower Advanced Lab.

== Setup

Copy the `sample_vars.yml` to a place outside of the Git repo (for security reasons)
and adapt the variables to your needs. You can also add and overwrite variables
present in the link:env_vars.yml[env_vars.yml file].

== Running Ansible Playbook

From the `agnosticd/ansible` directory run:

[source,bash]
----
ansible-playbook main.yml  \
      -e @.../my_adapted_sample_vars_with_my_secrets.yml \
----

TIP: you can repeat certain steps of the deployment by using tags, just make
     sure that the tags `must` and `create_inventory` are included, e.g.
     to only validate the Tower installation after it has been setup:
     `ansible-playbook ansible/main.yml --tags must,create_inventory,tower_validate -e ...`.

=== To Delete an environment

From the `agnosticd/ansible` directory run:

[source,bash]
----
ansible-playbook destroy.yml  \
      -e @.../my_adapted_sample_vars_with_my_secrets.yml \
----

CAUTION: it is recommended to destroy the environment if the deployment fails during the
         infrastructure deployment, as it might not properly recover. A failure during
         the software deployment can generally be recovered without destroy.
