= ansible-tower config

Author: Prakhar Srivastava, psrivast@redhat.com and Shachar Boresntein, sha@redhat.com
Owner: Prakhar Srivastava, psrivast@redhat.com
Alternative Contacts: Tony Kay, tok@redhat.com,

== Overview

ansible-tower config was initially created for the babylon Project to deploy Ansible Tower and worker ndoes (isolated nodes)


+
[source,yaml]
----
deploy_tower_homework: true
----

== NOTES

. There are 2 sets of deployer scripts:
**
**
. There are 2 sets of secrets files:
**
**

The "homework" lab requires additional secrets over and above the usual cloud (AWS)
credentails and repo path. These are traditionally stored on the admin host and
can be located via the relevant deployer scripts.


== Review the Env_Type variable file

* This file link:./env_vars.yml[./env_vars.yml] contains all the variables you
 need to define to control, or customize, the deployment of your environment. In
normal usage this should not need to be touched or ammended and one-off changes
can be tested by passing vars or var files with `-e` or `-e @my_version_vars.yml`.


== Secrets

As noted above a deploy of the normal lab requires just 3

== Running Ansible Playbook



You can run the playbook with the following arguments to overwrite the default variable values:
From the `ansible_agnostic_deployer/ansible` directory run
`
[source,bash]
----
ansible-playbook ansible/main.yml  \
      -e @./ansible/configs/ans-tower-prod/sample_vars.yml \
      -e @../secret.yml \
      -e "guid=sborenstest2" -vvvv
----

=== To Delete an environment
----

REGION=us-east-1
KEYNAME=ocpkey
GUID=test02
ENVTYPE=ans-tower-lab
CLOUDPROVIDER=ec2

ansible-playbook configs/${ENVTYPE}/destroy_env.yml \
        -e "guid=${GUID}" -e "env_type=${ENVTYPE}" \
        -e "cloud_provider=${CLOUDPROVIDER}" \
        -e "aws_region=${REGION}"  -e "key_name=${KEYNAME}"  \
        -e "subdomain_base_suffix=${BASESUFFIX}" \
        -e @~/secret.yml -vv
----
