= Generic Example Env_Type

In this directory we keep the files for a "Generic Example" environment type.

we create folders, yml files, and other items we want to over ride default variables.

For example, we will include things such as ec2 instance names, secret
variables such as private/public key pair information, passwords, etc.

Eventually, all sensitive information will be encypted via Ansible Vault. The
inclusion as well as instructions on doing this will be included in a later
release.

== Set up your "Secret" variables

* You need to provide some credentials for deployments to work
* you can set these for each "Standard Config" in it's directory or have a
 global variables file that will overwrite any "Config" specific variable file.

* Create a file called env_secret_vars.yml in the "environment type" directory

.Example contents of "Secret" Vars file
----
# ## Logon credentials for Red Hat Network
# ## Required if using the subscription component
# ## of this playbook.
rhel_subscription_user: ''
rhel_subscription_pass: ''
#
# ## LDAP Bind Password
bindPassword: ''
#
# ## Desired openshift admin name and password
admin_user: ""
admin_user_password: ""
#
# ## AWS Credentials. This is required.
aws_access_key_id: ""
aws_secret_access_key: ""
----

== Review the Env_Type variable file

* This file link:./env_vars.yml[./env_vars.yml] contains all the variables you
 need to define to control the deployment of your environment.

== Running Ansible Playbook



. You can run the playbook with the following arguments to overwrite the default variable values:
[source,bash]
----

## For a HA environment
REGION=ap-southeast-2
KEYNAME=osesharedkey
GUID=r2d2
ENVTYPE="ocp-ha-lab"
CLOUDPROVIDER=ec2
HOSTZONEID='Z3IHLWJZOU9SRT'

time ansible-playbook -i inventory/ ./main.yml \
-e "guid=${GUID}" -e "env_type=${ENVTYPE}"  -e "cloud_provider=${CLOUDPROVIDER}" -e "aws_region=${REGION}"  \
-e "HostedZoneId=${HOSTZONEID}"  -e "key_name=${KEYNAME}"  -e "subdomain_base_suffix=.example.opentlc.com"  \
-e "install_idm=htpasswd" \
-e "node_instance_count=4" -e "infranode_instance_count=2" -e "master_instance_count=3" -e "software_to_deploy=openshift" --skip-tags=installing_openshift



. To Delete an environment
----

REGION=ap-southeast-2
KEYNAME=osesharedkey
GUID=ocptestha4
ENVTYPE="ocp-ha-lab"
CLOUDPROVIDER=ec2
HOSTZONEID='Z3IHLWJZOU9SRT'
#To Destroy an Env
ansible-playbook -i inventory/ ./configs/${ENVTYPE}/destroy_env.yml \
 -e "guid=${GUID}" -e "env_type=${ENVTYPE}"  -e "cloud_provider=${CLOUDPROVIDER}" -e "aws_region=${REGION}"  \
 -e "HostedZoneId=${HOSTZONEID}"  -e "key_name=${KEYNAME}"  -e "subdomain_base_suffix=.example.opentlc.com"


----


. Testing AWS limits and quotas

----

REGION=us-east-1
KEYNAME=osesharedkey
GUID=awslimittest
ENVTYPE="ocp-ha-lab"
CLOUDPROVIDER=ec2
HOSTZONEID='Z3IHLWJZOU9SRT'

for envnumber in {1..10} ; do
echo ${GUID}${envnumber}

time ansible-playbook  ./main.yml \
-e "guid=${GUID}${envnumber}" -e "env_type=${ENVTYPE}"  -e "cloud_provider=${CLOUDPROVIDER}" -e "aws_region=${REGION}"  \
-e "HostedZoneId=${HOSTZONEID}"  -e "key_name=${KEYNAME}"  -e "subdomain_base_suffix=.example.opentlc.com"  \
-e "install_idm=htpasswd" \
-e "node_instance_count=4" -e "infranode_instance_count=2" -e "master_instance_count=3" -e "software_to_deploy=openshift" --tags=infrastucture_deployment

done
----
