---
galaxy_info:
  author: Anshul Behl
  description: Configure SSH client for network device connectivity
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 8
        - 9

  galaxy_tags:
    - networking
    - cisco
    - ssh
    - network_automation

dependencies:
  - role: control-user
    when: install_control_user | default(true) | bool
