#!/bin/bash
# until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
# do
#     echo "Waiting for Instruqt to finish booting the VM"
#     sleep 1
# done


tee -a soe.yml << EOF
---
- hosts: localhost
  vars:
    kernel_settings_sysctl:
      - name: vm.swappiness
        value: 20
      - name: vm.dirty_ratio
        value: 40
      - name: vm.dirty_expire_centisecs
        value: 500
      - name: vm.dirty_writeback_centisecs
        value: 100
      - name: kernel.sem
        value: "250 32000 100 128"
    tlog_scope_sssd: all
  roles:
    - role: rhel-system-roles.kernel_settings
    - role: rhel-system-roles.tlog
EOF

mkdir -p /root/.cloudrepos
mv /etc/yum.repos.d/google-cloud.repo /root/.cloudrepos/
mv /etc/yum.repos.d/rh-cloud.repo /root/.cloudrepos/

#useradd rhel
echo -e "test\ntest" | passwd rhel
mkdir -p /home/rhel/.ssh
cp .ssh/id_rsa.pub /home/rhel/.ssh/
cp .ssh/authorized_keys /home/rhel/.ssh/
chown rhel:rhel -R /home/rhel/.ssh/

ssh-keyscan -H client2 >> ~/.ssh/known_hosts
ssh-keyscan -H client1 >> ~/.ssh/known_hosts

#set up tmux so it has to restart itself whenever the system reboots

#step 1: make a script
tee ~/startup-tmux.sh << EOF
TMUX='' tmux new-session -d -s 'rhel-session' > /dev/null 2>&1
tmux set -g pane-border-status top
tmux setw -g pane-border-format ' #{pane_index} #{pane_current_command}'
tmux set -g mouse on
tmux set mouse on
EOF

#step 2: make it executable
chmod +x ~/startup-tmux.sh
#step 3: use cron to execute
echo "@reboot ~/startup-tmux.sh" | crontab -

#step 4: start tmux for the lab
~/startup-tmux.sh