= OSP Sandbox

== Config Description

This config is primarily used to simply provision an OpenStack project. The intended use is for development and testing of AgnosticD configs and workloads. The config includes:

* OSP project with basic quota
* One bastion host
* Credentials for OSP project
** clouds.yaml
** secrets.yml

== Review the Env_Type variable file

* This file link:./env_vars.yml[./default_vars.yml] contains all the variables you need to define to control the deployment of your environment.  These are the defaults.

* Override the defaults for your environment by creating your own myenvironment-variables.yml file, as below.

== Running Ansible Playbook

=== Running Playbook With Environment and Secrets files

You can create yaml files of your desired configs and secrets and execute them:

`ansible-playbook ansible/main.yaml -e @myenvironment-variables.yml  -e @my-secrets.yml`

=== To Delete an environment

Run the `destroy_env.yml` playbook.

Example:
[sh]
----
ansible-playbook ansible/configs/osp-sandbox/destroy_env.yml -e @myenvironment-variables.yml  -e @my-secrets.yml
----

The teardown process is roughly as follows:

* Delete compute & storage resources
** Use `openstack purge`
** ex: `openstack --os-cloud sten2 project purge --keep-project --project sten2-project`
* Delete network resources
** Use `neutron purge`
** ex: `neutron --os-cloud sten2 purge bb4e371f4bf443feb6e4435c8f5df6ae`
* Delete any trunk ports
* Delete the Heat stack
** If you don't delete the HOT as the user that created it, the keypair will not be deleted
* Delete Keypair if necessary
** TODO: add this functionality
* Cleanup DNS entries for bastion & OpenShift
* Delete project

== Workstation Setup:
With either RHEL or MacOS, you also need to have a `clouds.yaml` file on your system with credentials.
You can store this either in your working directory or in `~/.config/openstack/clouds.yaml`.

=== RHEL:

To prepare a RHEL host to deploy this config. This has been tested on RHEL 7.7.

[sh]
----
sudo subscription-manager register
sudo subscription-manager attach --pool=<yourpool>
sudo subscription-manager repos --disable=* --enable rhel-7-server-optional-rpms \
  --enable rhel-7-server-rpms --enable rhel-7-server-extras-rpms

sudo yum update -y

sudo yum install python-virtualenv git gcc

git clone https://github.com/redhat-cop/agnosticd.git
cd agnosticd
git checkout disco-ocp4

virtualenv ~/venv-openstack
source ~/venv-openstack/bin/activate

pip install -r ./ansible/configs/ocp4-disconnected-ha-lab/files/admin_host_requirements.txt
----

=== MacOS:

[sh]
----
# Install python
brew install python

# Make sure your path has this in it:
PATH="/usr/local/opt/python/libexec/bin:/usr/local/bin:$PATH"

# Make sure virtualenv and virtualenvwrapper are installed system wide
pip install virtualenv
pip install virtualenvwrapper

# Add this to your .bashrc
export WORKON_HOME=~/.virtualenvs
[ -f /usr/local/bin/virtualenvwrapper.sh ] && source /usr/local/bin/virtualenvwrapper.sh

# To start a new python virtual env
mkvirtualenv venv-openstack

# Activate virtual env
workon venv-openstack

# Clone repo and install python libraries
git clone https://github.com/redhat-cop/agnosticd.git
cd agnosticd
pip install -r ./ansible/configs/ocp4-disconnected-ha-lab/files/macos_requirements.txt
----

== Doing Something in The Sandbox
Now you have a sandbox environment, but how do you deploy an AgnosticD config into your new environment?
Here is an example of what you'd have to do in order to install the `ocp4-cluster` config in your new environment.
`ocp4-cluster` will deploy an OpenShift 4 cluster running on OpenStack.

. Provision this config.
. Log into `bastion`.
. Install the python requirements:
+
[sh]
---
sudo pip3 install -r $HOME/agnosticd/ansible/configs/osp-sandbox/files/openstack_requirements.txt
---
. Make sure your `openstack server list` command works.
. Copy the OSP `sample_vars*` file from the `$HOME/agnosticd/ansible/configs/ocp4-cluster/sample_vars` directory to your $HOME
. Make changes to this file, including...
.. osp_use_swift: False (for OCP 4.4+)
.. osp_project_create: False
.. rhcos_image_name: rhcos-ocp44
.. ocp4_installer_version: 4.4.0-rc.12
. Update your secrets file with things, including...
.. satellite_url
.. satellite_org
.. satellite_activationkey
.. ocp4_pull_secret
. Deploy the config
+
[sh]
----
ansible-playbook $HOME/agnosticd/ansible/main.yml -e @./<your-sample-vars.yml> -e @./secrets.yml -e guid=<something-unique>
----
