# ------------------------------
# DOCS
# ------------------------------

        # - name: Provision Solution Explorer
        #   include_tasks: provision_webapp.yaml
        #   vars:
        #     webapp_namespace: "webapp"
        #     snapshot_operator_project: "openshift-marketplace"


# - name: Install Showroom
#   ansible.builtin.include_tasks: provision_showroom.yaml

# - name: Provision Showroom OAuth Proxy
#   include_tasks: provision_showroom_proxy.yaml


- name: Delete the previously executed Job
  kubernetes.core.k8s:
    state: absent
    api_version: batch/v1
    kind: Job
    name: camel-jbang-job
    namespace: "{{ docs_namespace }}"
  register: delete_job_result

- name: Provision Camel DocServer System
  k8s:
    state: present
    namespace: "{{ docs_namespace }}"
    resource_definition: "{{ lookup('template', 'camel-docserver.yaml.j2') }}"

