---
- name: Evaluate ai-gateway namespace if not exists
  k8s:
    api_version: v1
    kind: Namespace
    name: ai-gateway
    state: present

- name: Create internal Gateway in ai-gateway
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'gateway-internal.yaml.j2') }}"

- name: Wait for internal Gateway to be programmed
  k8s_info:
    api_version: gateway.networking.k8s.io/v1
    kind: Gateway
    name: internal-gateway
    namespace: ai-gateway
  register: r_gateway
  retries: 50
  delay: 10
  until:
    - r_gateway.resources | length > 0
    - (r_gateway.resources[0].status | default({})).conditions | default([]) | selectattr('type', 'equalto', 'Programmed') | selectattr('status', 'equalto', 'True') | list | length > 0
