---
- name: Create Skupper Operator Subscription
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: skupper-operator
        namespace: "{{ operators_project }}"
      spec:
        channel: stable-2.1
        installPlanApproval: Manual
        name: skupper-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
        startingCSV: skupper-operator.v2.1.3-rh-1

- name: Wait until InstallPlan is available
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    namespace: "{{ operators_project }}"
    name: skupper-operator
  register: sub
  retries: 30
  delay: 10
  until:
    - sub.resources | length > 0
    - sub.resources[0].status.installplan.name is defined

- name: Approve InstallPlan
  shell:
    cmd: >
      oc patch installplan {{ sub.resources[0].status.installplan.name }}
      -n {{ operators_project }} --type=json -p='[{"op": "replace", "path": "/spec/approved", "value": true}]'

- name: Wait for Skupper Operator CSV to succeed
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: skupper-operator.v2.1.3-rh-1
    namespace: "{{ operators_project }}"
  register: skupper_csv
  retries: 30
  delay: 10
  until:
    - skupper_csv.resources | length > 0
    - skupper_csv.resources[0].status.phase is defined
    - skupper_csv.resources[0].status.phase == "Succeeded"
