---
- name: Enable Kuadrant Console Plugin
  kubernetes.core.k8s_json_patch:
    api_version: operator.openshift.io/v1
    kind: Console
    name: cluster
    patch:
      - op: add
        path: /spec/plugins/-
        value: kuadrant-console-plugin
