---
- name: Create internal HTTPRoute for {{ __user }}
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'http-route-internal.yaml.j2') }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: __user
