---
- name: Provision Gateway Class
  include_tasks: provision_cl_gateway_class.yaml

- name: Provision internal Gateway
  include_tasks: provision_cl_gateway.yaml

- name: Provision LLM API shadow service and Istio mesh config
  include_tasks: provision_cl_llm_api.yaml

- name: Provision internal HTTPRoute per user
  include_tasks: provision_cl_http_route_internal.yaml

- name: Provision Kuadrant (Connectivity Link)
  include_tasks: provision_cl_kuadrant.yaml

- name: Provision Kuadrant Console Plugin
  include_tasks: provision_cl_kuadrant_console.yaml

- name: Provision API user secrets (free and gold tier)
  include_tasks: provision_cl_api_users.yaml

- name: Provision ReferenceGrant for user HTTPRoutes
  include_tasks: provision_cl_refe_grant.yaml
