---
- name: Generate API keys for all users
  set_fact:
    api_keys: >-
      {{ api_keys | default({}) | combine({
        __user: {
          'lite': 'lite-' ~ __user ~ '-' ~ lookup('password', '/dev/null chars=ascii_lowercase,digits length=12'),
          'pro': 'pro-' ~ __user ~ '-' ~ lookup('password', '/dev/null chars=ascii_lowercase,digits length=12')
        }
      }) }}
  loop: "{{ users }}"
  loop_control:
    loop_var: __user

- name: Create lite-tier API key Secret for {{ __user }}
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'kuadrant-lite-user.yaml.j2') }}"
  vars:
    __api_key: "{{ api_keys[__user]['lite'] }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: __user

- name: Create pro-tier API key Secret for {{ __user }}
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'kuadrant-pro-user.yaml.j2') }}"
  vars:
    __api_key: "{{ api_keys[__user]['pro'] }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: __user
