---
# Restore original provision-user-data.yaml after Showroom deployment
- name: Restore provision-user-data.yaml
  delegate_to: localhost
  ansible.builtin.copy:
    dest: "{{ output_dir | default(playbook_dir) }}/provision-user-data.yaml"
    content: "{{ r_provision_user_data_backup.content | b64decode }}"
