---
- name: Create GatewayClass openshift-default
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'gateway-class.yaml.j2') }}"

# yamllint disable rule:line-length
- name: Wait for GatewayClass to be accepted
  k8s_info:
    api_version: gateway.networking.k8s.io/v1
    kind: GatewayClass
    name: openshift-default
  register: r_gateway_class
  retries: 20
  delay: 30
  until:
    - r_gateway_class.resources | length > 0
    - (r_gateway_class.resources[0].status | default({})).conditions | default([]) | selectattr('type', 'equalto', 'Accepted') | selectattr('status', 'equalto', 'True') | list | length > 0
# yamllint enable rule:line-length
