---
- name: Evaluate kuadrant-system namespace if not exists
  k8s:
    api_version: v1
    kind: Namespace
    name: kuadrant-system
    state: present

- name: Evaluate Kuadrant OperatorGroup
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'kuadrant-operatorgroup.yaml.j2') }}"

- name: Evaluate Kuadrant Subscription
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'kuadrant-subscription.yaml.j2') }}"

- name: Wait for Kuadrant operator CRD to be present
  k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: kuadrants.kuadrant.io
  register: crd_kuadrant
  retries: 20
  delay: 30
  until: crd_kuadrant.resources | list | length == 1

- name: Create Kuadrant instance
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'kuadrant.yaml.j2') }}"

- name: Wait for Kuadrant to be ready
  k8s_info:
    api_version: kuadrant.io/v1beta1
    kind: Kuadrant
    name: kuadrant
    namespace: kuadrant-system
  register: r_kuadrant
  retries: 20
  delay: 30
  until:
    - r_kuadrant.resources | length > 0
    - (r_kuadrant.resources[0].status | default({})).conditions | default([]) | selectattr('type', 'equalto', 'Ready') | selectattr('status', 'equalto', 'True') | list | length > 0
