---
- name: Create free-tier API key Secret for {{ __user }}
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'kuadrant-free-user.yaml.j2') }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: __user

- name: Create gold-tier API key Secret for {{ __user }}
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'kuadrant-gold-user.yaml.j2') }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: __user
