---
- name: Generate API keys for all users
  set_fact:
    api_keys: >-
      {{ api_keys | default({}) | combine({
        __user: {
          'silver': 'silver-' ~ __user ~ '-' ~ lookup('password', '/dev/null chars=ascii_lowercase,digits length=12'),
          'gold': 'gold-' ~ __user ~ '-' ~ lookup('password', '/dev/null chars=ascii_lowercase,digits length=12')
        }
      }) }}
  loop: "{{ users }}"
  loop_control:
    loop_var: __user

- name: Create silver-tier API key Secret for {{ __user }}
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'kuadrant-silver-user.yaml.j2') }}"
  vars:
    __api_key: "{{ api_keys[__user]['silver'] }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: __user

- name: Create gold-tier API key Secret for {{ __user }}
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'kuadrant-gold-user.yaml.j2') }}"
  vars:
    __api_key: "{{ api_keys[__user]['gold'] }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: __user
