---
galaxy_info:
  author: AgnosticD Team
  description: Retrieves information about IBM Cloud Classic bare metal servers
  company: Red Hat
  license: GPL-3.0+
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 8
        - 9
    - name: Ubuntu
      versions:
        - 20.04
        - 22.04
  galaxy_tags:
    - ibm
    - cloud
    - baremetal
    - infrastructure
    - classic

dependencies: [] 