#!/bin/bash
loginctl enable-linger $USER
export XDG_RUNTIME_DIR=/run/user/$(id -u)
export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus"
systemctl --user enable podman.socket --now

# Remove this after vscode on bastion is no longer needed.
