#!/usr/bin/bash

# Added by showroom 
# Enables tty ssh sessions, eg wetty, to automatically run in a tmux session

if command -v tmux >/dev/null 2>&1 && [ -z "$TMUX" ]; then
    # Check if the session exists, disregarding any error messages
    tmux has-session -t $1 2>/dev/null

    if [ $? != 0 ]; then
        # Create a new session if it doesn't exist
        tmux new-session -s $1 -n $1 -d
    fi

    # Attach to the session
    tmux attach-session -t $1
else
    if [ -z "$TMUX" ]; then
        echo "tmux is not installed. Please install tmux to use this feature."
    fi
fi


