= ocp4-workload-eap8-workshop - Deploy EAP7 to EAP8 Workshop into OCP4

== Role overview

* This role deploys the workshop into an OpenShift 4 Cluster. It depends on infrastructure nodes existing. It consists of the following tasks files:
** Tasks: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an
 environment for the workload deployment.
*** Debug task will print out: `pre_workload Tasks completed successfully.`

** Tasks: link:./tasks/workload.yml[workload.yml] - Used to deploy the guides and dev spaces
*** Debug task will print out: `workload Tasks completed successfully.`

** Tasks: link:./tasks/post_workload.yml[post_workload.yml] - Used to
 configure the workload after deployment
*** This role doesn't do anything here
*** Debug task will print out: `post_workload Tasks completed successfully.`

** Tasks: link:./tasks/remove_workload.yml[remove_workload.yml] - Used to
 delete the workload
*** This role removes the logging deployment and project but not the operator configs
*** Debug task will print out: `remove_workload Tasks completed successfully.`

== Review the defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you need to define to control the deployment of your workload.
* The variable *ocp_username* is mandatory to assign the workload to the correct OpenShift user.
* A variable *silent=True* can be passed to suppress debug messages.
* You can modify any of these default values by adding `-e "variable_name=variable_value"` to the command line

=== Deploy a Workload with the `ocp-workload` playbook [Mostly for testing]

Deploy an RHPDS OCP 4.13 cluster

Login to the bastion host and add your public key to the ~/.ssh/authorized_keys file


Set environment variaables with a script e.g.
export TARGET_HOST="bastion.vmlrl.sandbox1296.opentlc.com"
export OCP_USERNAME="lab-user"
export WORKLOAD="ocp4-workload-eap8-workshop"
export GUID=vmlrl
export USER_COUNT=1
export SSH_KEY=~/.ssh/id_rsa
export AWS_REGION=us-east-1
export MODULE_TYPE="m1"

Set environment variables for HTTP downloads using values from cloudfront

export HTTP_USERNAME=
export HTTP_PASSWORD=
export HTTP_URL=https://xxx.domain.com 

Run the ansible playbook

ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=${SSH_KEY}" \
    -e"ansible_user=${OCP_USERNAME}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"aws_region=${AWS_REGION}" \
    -e"num_users=${USER_COUNT}" \
    -e"module_type=${MODULE_TYPE}" \
    -e"subdomain_base=${TARGET_HOST}" \
    -e"HTTP_USERNAME=${HTTP_USERNAME}" \
    -e"HTTP_PASSWORD=${HTTP_PASSWORD}" \
    -e"HTTP_URL=${HTTP_URL}" \
    -e"ACTION=create"
----

=== To Delete an environment


# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=${SSH_KEY}" \
    -e"ansible_user=${OCP_USERNAME}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"aws_region=${AWS_REGION}" \
    -e"num_users=${USER_COUNT}" \
    -e"module_type=${MODULE_TYPE}" \
    -e"subdomain_base=${TARGET_HOST}" \
    -e"ACTION=remove"
----


== Other related information:

=== Deploy Workload on OpenShift Cluster from an existing playbook:

[source,yaml]
----
- name: Deploy a workload role on a master host
  hosts: all
  become: true
  gather_facts: False
  tags:
    - step007
  roles:
    - { role: "{{ocp_workload}}", when: 'ocp_workload is defined' }
----
NOTE: You might want to change `hosts: all` to fit your requirements


=== Set up your Ansible inventory file

* You can create an Ansible inventory file to define your connection method to your host (Master/Bastion with `oc` command)
* You can also use the command line to define the hosts directly if your `ssh` configuration is set to connect to the host correctly
* You can also use the command line to use localhost or if your cluster is already authenticated and configured in your `oc` configuration

.Example inventory file
[source, ini]
----
[gptehosts:vars]
ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem
ansible_user=ec2-user

[gptehosts:children]
openshift

[openshift]
bastion.cluster1.openshift.opentlc.com
bastion.cluster2.openshift.opentlc.com
bastion.cluster3.openshift.opentlc.com
bastion.cluster4.openshift.opentlc.com

[dev]
bastion.cluster1.openshift.opentlc.com
bastion.cluster2.openshift.opentlc.com

[prod]
bastion.cluster3.openshift.opentlc.com
bastion.cluster4.openshift.opentlc.com
----


## Install JBoss EAP 7

cd /shared
unzip jboss-eap-7.4.0.zip


## start JBoss EAP 7 
export EAP_HOME=/shared/jboss-eap-7.4
$EAP_HOME/bin/standalone.sh   -b 0.0.0.0 

## configure EAP 7
cp -r /projects/jboss7-quickstarts/sample-app/modules/* $EAP_HOME/modules
$EAP_HOME/bin/jboss-cli.sh --connect


/subsystem=datasources/jdbc-driver=postgresql:add(driver-name=postgresql,driver-module-name=org.postgresql)

data-source add --name=postgresql --jndi-name=java:/jdbc/postgresql --driver-name=postgresql --connection-url=jdbc:postgresql://127.0.0.1:5432/postgresDB --user-name=postgresUser --password=postgresPW

## Deploy app to EAP 7

cd /projects/jboss7-quickstarts/sample-app

mvn clean install wildfly:deploy

## Migrate configuration to EAP 8

export EAP_PREVIOUS_HOME=/home/jboss/EAP-7.4.0
export EAP_HOME=~/eap8/

/shared/jboss-server-migration/jboss-server-migration.sh -s $EAP_PREVIOUS_HOME -t $EAP_HOME

## Start EAP 8

$EAP_HOME/bin/standalone.sh   -b 0.0.0.0 

## Deploy EAP 8 version of the app

cd /projects/jboss7-quickstarts/sample-app-eap8

mvn clean wildfly:deploy

## Run MTR

./run_windup.sh  -b 0.0.0.0


http://simple-gitea.gitea.svc.cluster.local:3000/user1/jboss7-quickstarts.git

export HOSTNAME=user1-workshop

https://devspaces.apps.cluster-v6k6n.v6k6n.sandbox2818.opentlc.com/user1/jboss-workshop/13133/


http://user1-jboss-workshop-keycloak.apps.cluster-kg45v.kg45v.sandbox2868.opentlc.com/