---
# handlers file for gitea_vm_setup
- name: Restart the nginx configuration
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
  listen: nginx_reload

# - name: Reload the nginx configuration
#   ansible.builtin.command: /usr/sbin/nginx -s reload  # as root
#   listen: nginx_reload
