:role: satellite-provisioning
:author: Satellite Team
:tag1: configure_satellite
:tag2: satellite_provisioning
:tag3: satellite_provisioning_libvirt
:main_file: tasks/main.yml
:resources_file: tasks/provisioning_resources.yml

Role: {role}
============

This role prepares satellite network based provisioning.
As of now, it handles only internal libvirt.

Requirements
------------

. Satellite must be installed and setted up.
. For libvirt, libvirt must be installed and it's service running.


Role Variables
--------------

* Following are the variable to customize this role

[cols="2a,1,3a"]
|===
|satellite_version: "Digit" |Required |satellite version
|satellite_admin: "String" |Required |Satellite admin username
|satellite_admin_password: "String" |Required |Satellite admin password
|satellite_libvirt_provisioning: "Bool" |Optional(*false*) | Whether configure libvirt provisioning
|satellite_libvirt_network: {Dictionary}
!===
!name: "String"
!domain: "String"
!network: "String"
!gateway: "String"
!netmask: "String"
!range_from: "String"
!range_to: "String"
!dns_primary: "String"
!boot_mode: "String"
!===
|Optional
|Libvrit default network setting
!===
!Name of the subnet
!What domain should the subnet belong to
!Network address
!Gateway address - this is the hosting system address in this nat network
!Network mask - full format
!First IP to be included in the subnet used for provisioning
!Last IP to be included in the subnet used for provisioning
!Dns primary server - used for subnet module, defaults to the gateway server
!Boot mode for this subnet - method of obtaining the IP setting
!===
|===

* Exammple variables

[source=text]
----
satellite_version: 6.7
satellite_admin: admin
satellite_admin_password: 'changeme'
satellite_libvirt_provisioning: yes
satellite_libvirt_network:
  name: LibvirtSubnet
  domain: example.org
  network: '192.168.122.0'
  gateway: '192.168.122.1'
  netmask: '255.255.255.0'
  range_from: '192.168.122.2'
  range_to: '192.168.122.254'
----

Tags
---

|===
|{tag1} |Consistent tag for all satellite config roles
|{tag2} |This tag is specific to this role only
|{tag3} |This tag is specific to this role and libvirt provisioning
|===


Example Playbook
----------------

How to use your role (for instance, with variables passed in playbook).

[source=text]
----
[user@desktop ~]$ cat sample_vars.yml
satellite_version: 6.7
satellite_admin: admin
satellite_admin_password: 'changeme'
satellite_libvirt_provisioning: yes
satellite_libvirt_network:
  name: LibvirtSubnet
  domain: example.org
  network: '192.168.122.0'
  gateway: '192.168.122.1'
  netmask: '255.255.255.0'
  range_from: '192.168.122.2'
  range_to: '192.168.122.254'

[user@desktop ~]$ cat playbook.yml
- hosts: satellites
  vars_files:
    - sample_vars.yml
  roles:
    - satellite-provisioning

[user@desktop ~]$ ansible-playbook playbook.yml
----


Tips to update Role
------------------

for reference look at link:{main_file}[main.yml] and provisioning resources registration ling:{resources_file}[provisioning_resources.yml]

Author Information
------------------

{author}
