= SQL Server Workload

== Overview

This is a workload for SQL Server. It also includes a sample app which uses the SQL server as backend database. Follow instructions in following sections to deploy this workload on your OCP cluster.

== Deploying SQL Server workload

[source, bash]
----
ansible-playbook -i "bastion.${GUID}.${BASE_DOMAIN}", ./ansible/configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=${ANSIBLE_USER_KEY_FILE}" \
    -e"ansible_user=${ANSIBLE_USER}" \ 
    -e"ocp_workload=ocp-workload-mssql" \ 
    -e"silent=False" \
    -e"ACTION=create" \
    -e @./secret.yaml \ <1>
    -e @./workload_vars.yaml <2>
----
<1> This is the same file you used while deploying OCP cluster using agnosticd. Optionally, include sensitive workload variables here.
<2> This file contains all the variables required by the workload.

This workload comes with a default configuration. You may choose to change the default behaviour by overriding variables.

=== Variables 

|===
| Variable | Default Value | Description | Required

| mssql_pv_provider
| default
| Type of PV to use (Supported : default)
| No

| mssql_namespace
| mssql-persistent
| Namespace for the workload
| No

| mssql_image
| mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
| Container image for MsSQL server
| No

| mssql_sa_password
| P@ssw0rd1!
| Password for admin user
| No

| mssql_cpu_limit
| "2"
| CPU limit for MsSql
| No

| mssql_memory_limit
| "3Gi"
| Memory limit for MsSql
|

| mssql_port
| 1433
| SQL server port
| No

| mssql_volume_mount_name
| mssql-vol
| Name for pv resource
| No

| mssql_pvc_name
| mssql-pvc
| Name for pvc resource
| No

| mssql_app_name
| mssql-container
| Name for pod resource
| No

| mssql_secret_name
| mssql-secret
| Name for secret resource
| No

| mssql_service_name
| mssql-service
| Name for service resource
| No

| mssql_deployment_name
| mssql-deployment
| Name for deployment resource
| No
|===

=== Delete MsSQL Workload

[source, bash]
----
ansible-playbook -i "bastion.${GUID}.${BASE_DOMAIN}", ./ansible/configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=${ANSIBLE_USER_KEY_FILE}" \
    -e"ansible_user=${ANSIBLE_USER}" \
    -e"ocp_workload=ocp-workload-mssql" \ 
    -e"silent=False" \
    -e"ACTION=remove" \
    -e @./secret.yaml \
    -e @./workload_vars.yaml
----