= Just Some Nodes Example

== Environment Overview

This environment is used to deploy any number of RHEL nodes for generic use.
It is also used as an example for new contributors to Agnostic D as an example

== Review the Env_Type variable file

* This file link:./env_vars.yml[./env_vars.yml] contains all the variables you
 need to define to control the deployment of your environment.


== Running Ansible Playbook

You can run the playbook with the following arguments to overwrite the default variable values:
[source,bash]
----
# Generic Vars

ENVTYPE="just-some-nodes-example"
GUID=nodestest1

# Cloud Provider Settings
KEYNAME=ocpkey
REGION=ap-southeast-2
CLOUDPROVIDER=ec2
HOSTZONEID='Z3IHLWJZOU9SRT'
BASESUFFIX='.example.opentlc.com'


ansible-playbook ansible/main.yml \
  -e "guid=${GUID}" \
  -e "env_type=${ENVTYPE}" \
  -e "cloud_provider=${CLOUDPROVIDER}" \
  -e "aws_region=${REGION}" \
  -e "HostedZoneId=${HOSTZONEID}" \
  -e "key_name=${KEYNAME}" \
  -e "subdomain_base_suffix=${BASESUFFIX}" \
  -e "node_instance_count=2" \
  -e "email=name@example.com" -e"output_dir=/opt/workdir" -e"output_dir=/opt/workdir" -e@../secret.yml -vv


----

if you wanted to deploy one of the roles from the `./ansible/roles` directory,
 you can add `-e"infra_workloads=ipa-server,molecule"`

=== To Delete an environment
----

GUID=airplanetest1
ENVTYPE="just-some-nodes-example"
CLOUDPROVIDER=ec2
DEPLOYER_REPO_PATH=`pwd`
#To Destroy an Env
ansible-playbook ./configs/${ENVTYPE}/destroy_env.yml \
    -e "ANSIBLE_REPO_PATH=${DEPLOYER_REPO_PATH}" \
 -e "guid=${GUID}" -e "env_type=${ENVTYPE}"  -e "cloud_provider=${CLOUDPROVIDER}" -e "aws_region=${REGION}"

----




== Set up your "Secret" variables

Just like any environment you would need to specify some variables that should
 not be committed into github.

It is recommended to put those variables and values in a file called
 `env_secret_vars.yml` as we included it in the .gitignore file, just in case.

.Example on how to use `ansible-vault` to encrypt a file
[source,bash]
----
$ ansible-vault encrypt env_secret_vars.yml
New Vault password: <MYCOOLPASSWORD>
Confirm New Vault password: <MYCOOLPASSWORD>
Encryption successful
----

.Example contents of a "env_secret_vars.yml" file
[source,yaml]
----
# ## Logon credentials for Red Hat Network
# ## Required if using the subscription component
# ## of this playbook.
rhel_subscription_user: ''
rhel_subscription_pass: ''
#
# ## LDAP Bind Password
bindPassword: ''
#
# ## Desired admin name and password if required
admin_user: ""
admin_user_password: ""
#
# ## AWS Credentials. This is required.
aws_access_key_id: ""
aws_secret_access_key: ""
#If using repo_method: satellite, you must set these values as well.
satellite_url: https://satellite.example.com
satellite_org: Sat_org_name
satellite_activationkey: "rhel7basic"

----
