= AgnosticD Training Package

:toc:

== AgnosticD Advanced

== Introduction: 
Infrastructure as a code developer Story/Path
Goal: Introduce learner to AgnosticD more advanced topics. Students will be able to explain what AgnosticD is, what the currently supported cloud providers are, how the repository is structured and differences between configs and workloads are

=== Agenda: 
. Advanced Best Practices
.. Proper usage of variables in files
.. Adding more than one RHEL version, specific bastion roles for RHEL 7 v 8
.. Adding users, ssh keys, password guidelines
. Explain relationship between agV and agD, maybe going thru main.yml in agD
. Advanced networking
.. Networking: adding 2 NICs to a VM
.. DNS: explain about activating public_dns flags make them go inside DNS

. Customized HEAT template: to take advantage of a given functionality of OSP
https://github.com/redhat-cop/agnosticd/tree/development/ansible/roles-infra/infra-osp-template-create
https://github.com/redhat-cop/agnosticd/tree/development/ansible/roles-infra/infra-osp-template-generate
Can provide customized heat templates within the "files/cloud_providers/" sub directory of config, Master template is below for OSP
https://github.com/redhat-cop/agnosticd/blob/development/ansible/roles-infra/infra-osp-template-generate/templates/cloud_template_master.j2
