= AgnosticD Training Package

:toc:

== AgnosticD Advanced

== Introduction: 
Infrastructure as a code developer Story/Path.

Goal: Introduce learner to AgnosticD more advanced topics. Students will be able to explain what AgnosticD is, what the currently supported cloud providers are, how the repository is structured and differences between configs and workloads are.
The ultimate goal, is to allow students to extend an existing config to meet their needs.

=== Agenda: 
. Advanced Best Practices
.. Proper usage of variables in files
.. Adding more than one RHEL version, specific bastion roles for RHEL 7 v 8
.. Adding users, ssh keys, password guidelines
. Understanding the main.yml in AgnosticD

=== Competencies covered:
Learning to Create Labs for RHPDS using AgnosticD Is a course designed to prepare associates to understand automated infrastructure deployments and customization utilizing AgnosticD. By the end of this introductory module, will be able to answer the following questions: 

1. Where do I declare variables?
2. What does the main.yml file do?
3. How do I extend a config?
4. How do I create users on AgnosticD configs?
5. How do I add different versions of RHEL to my AgnosticD configs?

=== Pre requisites:
In order to fully understand and follow the topics covered in this course, it is mandatory that you first complete link:https://learning.redhat.com/course/view.php?id=2751[Creating Labs for Red Hat Product Demo System using Agnostic D - Foundational]

NOTE: To get started and order your environment, please refer to link:https://github.com/redhat-cop/agnosticd/blob/development/training/02_Getting_Started/02_config_your_environment.adoc[instructions]