= How to add more than one version of RHEL on your nodes machines

It is a very common practice to have multiple versions of RHEL on different nodes on your deployment, to cover different use cases of real life. It is not trivial to have those mixed on a single deployment file in AgnosticD, and we are going to cover it here.

We will use the AgnosticD config `a-base-config` comes with sample vars files included for OpenStack, locally at `~/agnosticd/ansible/configs/a-base-config/sample_variables/rhel8_server_on_osp.yml`. We will need to modify some of those vars.

== Preparing your a-base-config vars

. Copy the `rhel8_server_on_osp.yml` file and call it `my_vars.yml`.
+
[source,bash]
----
[agilpipp-redhat.com@bastion ~]$ cd agnosticd/ansible
[agilpipp-redhat.com@bastion ~]$ cp configs/a-base-config/sample_variables/rhel8_server_on_osp.yml \
  ~/my_vars.yml
----

. Edit your copy of the vars file, changing the value of guid to a valid subdomain name (For example an alphanumeric string starting with a letter). The values that need changing are identified below:
+
[source,bash]
----
# RHEL 8 Server on OpenStack.
# This example creates a single RHEL 8 server

# Mandatory Variables
cloud_provider: osp                  # This var file is meant for an openstack deployment
env_type: a-base-config              # Name of the config to deploy
software_to_deploy: none             # Not deploying any software onto the environment

# Environment Variables

# guid is the deployment unique identifier, it will be appended to all tags,
# files and anything that identifies this environment from another "just like it"
# The current value is an example guid based on a openstack project name.
guid: CHANGE_ME
email: example@example.com               # User info for notifications

----

*WARNING*: Do not pick the same *GUID* as the one you got for access to the OSP cluster.	

== Setting the repo method

In order to be able to mix different RHEL repos from different versions to be able to provision different versions of RHEL, the only option is to use a Satellite server. This way, we can define a aepo dictionary that can contain both RHEL 7 and 8 if using a satellite content view. 

*NOTE*: Content view creation is out of the scope of this training.

Add the following lines to the vars file, `~/my_vars.yml`

[source,bash]
----
[agilpipp-redhat.com@bastion ~]$ vi ~/my_vars.yml
use_content_view: false

rhel_repos_el7:
  - rhel-7-server-rpms
  - rhel-7-server-rh-common-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-optional-rpms
  - rhel-server-rhscl-7-rpms

rhel_repos_el8:                              # Repositories that will be available in the environment.
  - rhel-8-for-x86_64-baseos-rpms
  - rhel-8-for-x86_64-appstream-rpms
  - ansible-2-for-rhel-8-x86_64-rpms

update_packages: true                    # Update all packages on system after configuration. true/false
software_to_deploy: none                 # Not deploying any software onto the environment
----

Let's explain a bit more what is happening behind the curtains.

Satellite is populated using the following tasks file `roles/set-repositories/tasks/satellite-repos.yml` and it populates repos in this way:

[source,bash]
----
[agilpipp-redhat.com@bastion ~]$ cd agnosticd/ansible
[agilpipp-redhat.com@bastion ~]$ vi roles/set-repositories/tasks/satellite-repos.yml
- name: Register with activation-key
  when: set_repositories_satellite_activationkey != ''
  redhat_subscription:
    state: present
    consumer_name: "{{ set_repositories_subscription_hostname }}"
    server_hostname: "{{ set_repositories_satellite_hostname }}"
    activationkey: "{{ set_repositories_satellite_activationkey }}"
    org_id: "{{ set_repositories_satellite_org | default(satellite_org) }}"

- name: Enable repos
  rhsm_repository:
    name: "*"
    state: enabled
  when:
  - use_content_view
  - set_repositories_satellite_activationkey != ''

- name: Enable repos for RHEL
  rhsm_repository:
    name: "{{ item }}"
    state: enabled
  with_items:
    - '{{ rhel_repos }}'
  when:
  - not use_content_view
  - rhel_repos is defined
----

When an activation key is defined, then it will enable all the repos defined on the dictionaries in `my_vars.yml` file, of course, then each instance will only enable the ones it needs (this is given by the `rhel_image` variable).

Then, we simply need to add the packages we want to install in both el7 and el8 hosts on a dictionary:
[source,bash]
----
[agilpipp-redhat.com@bastion ~]$ vi ~/my_vars.yml
[...]
common_packages:                         # Packages to be installed on each node
  - python
  - unzip
  - bash-completion
  - tmux
  - wget
  - git
  - vim-enhanced
  - at
  - firewalld
  - ansible

common_packages_el8:
  - python3
  - python3-pip
  - unzip
  - bash-completion
  - tmux
  - bind-utils
  - wget
  - git
  - vim-enhanced
  - at
  - gcc
  - ansible
----