= How to add more than one user on your nodes machines

It is a very common practice to have multiple users on the nodes on your deployment, to cover different use cases of real life.

In this part of the training we will cover how to create new users on your machines and how the SSH keys are created and pushed into the machines.

In order to create new users, we are going to extend the possibilities of the `a-base-config` config to adapt it to our needs. This is a very common practice when developing with agnosticD.

== Adding users

=== Add tasks on tasks file post_software.yml

 First step, is to locate the file in which users are created. This file is not on a-base-config, since this is a basic config that does not create extra users on the nodes. There are multiple configs that do create users, let's find out which one we could use:

[source,bash]
----
[agilpipp-redhat.com@bastion configs]$ find . -name setup_lab_user.yml
./ans-tower-lab-ng/setup_lab_user.yml
./ans-tower-lab/setup_lab_user.yml
./ansible-platform-foundations/setup_lab_user.yml
./ansible-tower-pntae/setup_lab_user.yml
./hacluster-breakfix1-pntae/setup_lab_user.yml
./hacluster-pntae/setup_lab_user.yml
./multi-network-app-pntae/setup_lab_user.yml
./pntae-jabn/setup_lab_user.yml
./pntae-vilt-bastion/setup_lab_user.yml
./smart-management-foundations/setup_lab_user.yml
./smart-management/setup_lab_user.yml
./three-tier-app/setup_lab_user.ym 
----

We can use, for instance, `./smart-management/setup_lab_user.yml` 
[source,bash]
----
[agilpipp-redhat.com@bastion configs]$ cat ./smart-management/setup_lab_user.yml
---
- name: Create lab-user
  user:
    name: "{{ lab_user }}"
    group: "users"
    state: present

- name: Enable sudoers
  lineinfile:
    path: '/etc/sudoers'
    state: present
    line: "{{ lab_user }}  ALL=(ALL) NOPASSWD: ALL"
----

This file could works for us, although it just create one user.

We copy the file into our config (our modified config, we could later simply rename it to make it *our config* and get that code approved and merged into the main agnosticD branch) and modify the tasks so it create several users.
[source,bash]
----
[agilpipp-redhat.com@bastion configs]$ cp ./smart-management/setup_lab_user.yml ./a-base-config/setup_lab_user.yml
[agilpipp-redhat.com@bastion configs]$ cd a-base-config/
[agilpipp-redhat.com@bastion a-base-config]$ vi setup_lab_user.yml
- name: Create lab-user
  user:
    name: "{{ __users }}"
    group: "users"
    state: present
  loop: "{{ lab_users }}"
  loop_control:
    loop_var: __users

- name: Enable sudoers
  lineinfile:
    path: '/etc/sudoers'
    state: present
    line: "{{ __sudoers }}  ALL=(ALL) NOPASSWD: ALL"
    insertafter: 'EOF'
  loop: "{{ lab_users }}"
  loop_control:
    loop_var: __sudoers
----

In order to be able to create multiple users, we use a loop, that iterates within `lab_users` and uses `__users` as control variable. We do same with `Enable sudoers tasks`, using `__sudoers` as the control variable.

*NOTE*: we could use `item` as a control variable, but declaring variables will allow us to use them later on, if needed.

=== Defining user list

Now that we've been able to add more users, we'd need to define the list of users for our node machines. For that, simply define the `users` list in the `my_vars.yml` file:

[source,bash]
----
[agilpipp-redhat.com@bastion configs]$ cd ~
[agilpipp-redhat.com@bastion a-base-config]$ vi ~/my_vars.yml
[...]
lab_users:
  - amaya
  - wilson
[...]
----

=== Calling the right task
We've just added the task and users, but we have not called it yet. In order to make the task to be called, we need to place it in the right place

[source,bash]
----
- name: Setup lab-user
  hosts: all
  become: true
  tasks:
    - name: Setup lab-user
      include_tasks: ./setup_lab_user.yml
----

== Setting up ssh keys
Even if users have been created, no ssh keys have been defined, so we have not clue on how to log into the nodes machines, as we do not have a password.

We want to be able to create ssh keys for our users and we need to be able to let our users to access them, easily (in case someone wants to re use our config).

SSH keys configuration tasks are also listed on the `setup_lab_user.yml` file. Again, as we did with users, please add loops for all of the tasks (final result is shown below):

[source,bash]
----
[agilpipp-redhat.com@bastion configs]$ cd a-base-config/
[agilpipp-redhat.com@bastion a-base-config]$ vi setup_lab_user.yml
[...]
- name: create /home/{{ __ssh_dir }}/.ssh
  file:
    dest: /home/{{ __ssh_dir }}/.ssh
    mode: 0700
    owner: "{{ __ssh_dir }}"
    group: "users"
    state: directory
  loop: "{{ lab_users }}"
  loop_control:
    loop_var: __ssh_dir

- name: copy the environment .pem key
  copy:
    src: "{{ output_dir }}/{{ env_authorized_key }}"
    dest: "/home/{{ __ssh_pem }}/.ssh/{{ env_authorized_key }}.pem"
    owner: "{{ __ssh_pem }}"
    group: "users"
    mode: 0400
  loop: "{{ lab_users }}"
  loop_control:
    loop_var: __ssh_pem

- name: copy the environment .pub key
  copy:
    src: "{{ output_dir }}/{{ env_authorized_key }}.pub"
    dest: "/home/{{ __ssh_pub }}/.ssh/{{ env_authorized_key }}.pub"
    owner: "{{ __ssh_pub }}"
    group: "users"
    mode: 0400
  loop: "{{ lab_users }}"
  loop_control:
    loop_var: __ssh_pub

- name: copy .ssh/config template
  template:
    src: ./files/ssh_config.j2
    dest: /home/{{ __ssh_conf }}/.ssh/config
    owner: "{{ __ssh_conf }}"
    group: "users"
    mode: 0400
  loop: "{{ lab_users }}"
  loop_control:
    loop_var: __ssh_conf
----

As you can see, what we are doing here is:
1. Create .ssh directory for each user (task "create /home/{{ __ssh_dir }}/.ssh")
2. Copy the PEM key file (task "copy the environment .pem key")
3. Copy the PUB key file (task "copy the environment .pub key")
4. Copy ssh config file template (task "copy .ssh/config template")

At this point you may have already realized that we are not really creating keys here, but copying existing ones. The acutal file is created with the `/files/ssh_config.j2` jinja2 template, as seen in the last task.

Let's take a look at it:
[source,bash]
----
Host * 

  {% if cloud_provider == 'ec2' %}
  User ec2-user
  {% elif cloud_provider == 'osp' %}
  User cloud-user
  {% endif %}
  IdentityFile ~/.ssh/{{ guid }}key.pem
  ForwardAgent yes
  StrictHostKeyChecking no
  ConnectTimeout 60
  ConnectionAttempts 10
  ControlMaster auto
  ControlPath /tmp/%h-%r
  ControlPersist 5m
----

The actual key is generated in file `infra-role/infra-local-create-ssh-keys.yml` file

 setup_lab_user.yml --> them to create

 ssh config on pre_software (ssh_config.j2)

 actual key gen is on infra-role/infra-local-create-ssh-keys.yml

 added hosts_template.j2