= How to add more than one user on your nodes machines

It is a very common practice to have multiple users on the nodes on your deployment, to cover different use cases of real life.

In this part of the training we will cover how to create new users on your machines and how the SSH keys are created and pushed into the machines.

In order to create new users, we are going to extend the possibilities of the `a-base-config` config to adapt it to our needs. This is a very common practice when developing with agnosticD.

== Adding users

=== Add tasks on tasks file post_software.yml

First step, is to locate the file in which users are created. This file is not on a-base-config, since this is a basic config that does not create extra users on the nodes. There are multiple configs that do create users, let's find out which one we could use:

[source,bash]
----
[agilpipp-redhat.com@bastion configs]$ find . -name setup_lab_user.yml
./ans-tower-lab-ng/setup_lab_user.yml
./ans-tower-lab/setup_lab_user.yml
./ansible-platform-foundations/setup_lab_user.yml
./ansible-tower-pntae/setup_lab_user.yml
./hacluster-breakfix1-pntae/setup_lab_user.yml
./hacluster-pntae/setup_lab_user.yml
./multi-network-app-pntae/setup_lab_user.yml
./pntae-jabn/setup_lab_user.yml
./pntae-vilt-bastion/setup_lab_user.yml
./smart-management-foundations/setup_lab_user.yml
./smart-management/setup_lab_user.yml
./three-tier-app/setup_lab_user.ym 
----

We can use, for instance, `./smart-management/setup_lab_user.yml` 
[source,bash]
----
[agilpipp-redhat.com@bastion configs]$ cat ./smart-management/setup_lab_user.yml
---
- name: Create lab-user
  user:
    name: "{{ lab_user }}"
    group: "users"
    state: present

- name: Enable sudoers
  lineinfile:
    path: '/etc/sudoers'
    state: present
    line: "{{ lab_user }}  ALL=(ALL) NOPASSWD: ALL"
----

This file could works for us, although it just create one user.

We copy the file into our config (our modified config, we could later simply rename it to make it *our config* and get that code approved and merged into the main agnosticD branch) and modify the tasks so it create several users.
[source,bash]
----
[agilpipp-redhat.com@bastion configs]$ cp ./smart-management/setup_lab_user.yml ./a-base-config/setup_lab_user.yml
[agilpipp-redhat.com@bastion configs]$ cd a-base-config/
[agilpipp-redhat.com@bastion a-base-config]$ vi setup_lab_user.yml
- name: Create lab-user
  user:
    name: "{{ __users }}"
    group: "users"
    state: present
  loop: "{{ lab_users }}"
  loop_control:
    loop_var: __users
  when: lab_users is defined

- name: Enable sudoers
  lineinfile:
    path: '/etc/sudoers'
    state: present
    line: "{{ __sudoers }}  ALL=(ALL) NOPASSWD: ALL"
    insertafter: 'EOF'
  loop: "{{ lab_users }}"
  loop_control:
    loop_var: __sudoers
  when: lab_users is defined
----

In order to be able to create multiple users, we use a loop, that iterates within `lab_users` and uses `__users` as control variable. We do same with `Enable sudoers tasks`, using `__sudoers` as the control variable.

*NOTE*: we could use `item` as a control variable, but declaring variables will allow us to use them later on, if needed.

=== Defining user list

Now that we've been able to add more users, we'd need to define the list of users for our node machines. For that, simply define the `users` list in the `my_vars.yml` file:

[source,bash]
----
[agilpipp-redhat.com@bastion configs]$ cd ~
[agilpipp-redhat.com@bastion ~]$ vi ~/my_vars.yml
[...]
lab_users:
  - amaya
  - wilson
[...]
----

=== Calling the right task
We've just added the task and users, but we have not called it yet. In order to make the task to be called, we need to place it in the right place, that is `post_software.yml`, as this is where checks, user notifications and clean up tasks take place.

[source,bash]
----
[agilpipp-redhat.com@bastion ]$ vi configs/a-base-config/post_software.yml
- name: Setup lab-user
  hosts: all
  become: true
  tasks:
    - name: Setup lab-user
      include_tasks: ./setup_lab_user.yml
----

NOTE: A fully configured file has been provided to you under training/2Users.yml