== Setting up ssh keys
Even if users have been created, no ssh keys have been defined, so we have not clue on how to log into the nodes machines, as we do not have a password.

We want to be able to create ssh keys for our users and we need to be able to let our users to access them, easily (in case someone wants to re use our config).

SSH keys configuration tasks are also listed on the `setup_lab_user.yml` file. Again, as we did with users, please add loops for all of the tasks (final result is shown below):

[source,bash]
----
[agilpipp-redhat.com@bastion configs]$ cd a-base-config/
[agilpipp-redhat.com@bastion a-base-config]$ vi setup_lab_user.yml
[...]
- name: create /home/{{ __ssh_dir }}/.ssh
  file:
    dest: /home/{{ __ssh_dir }}/.ssh
    mode: u+rwx,g-rwx,o-rwx
    owner: "{{ __ssh_dir }}"
    group: "users"
    state: directory
  loop: "{{ lab_users }}"
  loop_control:
    loop_var: __ssh_dir

- name: copy the environment .pem key
  copy:
    src: "{{ output_dir }}/{{ env_authorized_key }}"
    dest: "/home/{{ __ssh_pem }}/.ssh/{{ env_authorized_key }}.pem"
    owner: "{{ __ssh_pem }}"
    group: "users"
    mode: u+r,g-rwx,o-rwx
  loop: "{{ lab_users }}"
  loop_control:
    loop_var: __ssh_pem

- name: copy the environment .pub key
  copy:
    src: "{{ output_dir }}/{{ env_authorized_key }}.pub"
    dest: "/home/{{ __ssh_pub }}/.ssh/{{ env_authorized_key }}.pub"
    owner: "{{ __ssh_pub }}"
    group: "users"
    mode: u+r,g-rwx,o-rwx
  loop: "{{ lab_users }}"
  loop_control:
    loop_var: __ssh_pub

- name: copy .ssh/config template
  template:
    src: ./files/ssh_config.j2
    dest: /home/{{ __ssh_conf }}/.ssh/config
    owner: "{{ __ssh_conf }}"
    group: "users"
    mode: u+r,g-rwx,o-rwx
  loop: "{{ lab_users }}"
  loop_control:
    loop_var: __ssh_conf
----

As you can see, what we are doing here is:
1. Create .ssh directory for each user (task "`create /home/{{ __ssh_dir }}/.ssh`")
2. Copy the PEM key file (task "`copy the environment .pem key`")
3. Copy the PUB key file (task "`copy the environment .pub key`")
4. Copy ssh config file template (task "`copy .ssh/config template`")

At this point you may have already realized that we are not really creating keys here, but copying existing ones. 

The actual key is generated in file `infra-role/infra-local-create-ssh-keys.yml` file called from `./agnosticd/ansible/configs/a-base-config/pre_software.yml` let's look at it:

[source,bash]
----
- name: Generate SSH keys
  shell: ssh-keygen -b 2048 -t rsa -f "{{output_dir}}/{{env_authorized_key}}" -q -N ""
  args:
    creates: "{{output_dir}}/{{env_authorized_key}}"
  when: set_env_authorized_key | bool

- name: fix permission
  file:
    path: "{{output_dir}}/{{env_authorized_key}}"
    mode: 0400
  when: set_env_authorized_key | bool

- name: Generate SSH pub key
  shell: ssh-keygen -y -f "{{output_dir}}/{{env_authorized_key}}" > "{{output_dir}}/{{env_authorized_key}}.pub"
  args:
    creates: "{{output_dir}}/{{env_authorized_key}}.pub"
  when: set_env_authorized_key | bool
----

There are a number of useful tasks related to the infrastructure already provided to us by Agnostic D, those can be found on /agnosticd/ansible/roles-infra, and are normally called in the pre deploy stage, with the pre_software.yml file, as we just saw.

=== Setting the variables
Now that we have defined how we want ssh keys to be created, we do need to reference it in our variables file (`my_vars.yml` in this case).

The following variables are used in different roles, depending on what they are to accomplish:
* set_env_authorized_key role: This role creates the directories and copies the keys to the right directory for the user (root user).
* bastion-lite: This role creates the OpenSSH client-side configuration file. It configures the file stanzas for each node we define and stores them in the `output_dir`.

[source,bash]
----
# Environment Variables for SSH key generation and assignment
# set_env_authorized_key role
set_env_authorized_key: true
env_authorized_key: "{{guid}}key"

# bastion-lite role
use_own_key: true
key_name: opentlc_admin_backdoor

# files/hosts_template.j2 used by bastion
ansible_ssh_private_key_file: ~/.ssh/{{key_name}}.pem
----

== Logging into our nodes

Now we need to log into our nodes and test everything is ok, that is, our users have been created and we are able to log into those machines.
First of all, we need to locate the ssh keys under our output directory:

[source,bash]
----
[agilpipp-redhat.com@bastion ansible]$ ls /tmp/output_dir/
/tmp/output_dir/test-01key
/tmp/output_dir/test-01key.pub
/tmp/output_dir/a-base-config.test-01.osp_cloud_master_template.yaml
/tmp/output_dir/test-01_infra_ssh_key.pem
/tmp/output_dir/a-base-config_test-01_ssh_conf
/tmp/output_dir/a-base-config_test-01_ssh_known_hosts
----