= ocp4_workload_fraud_detection_usecase - Deploys fraud detection usecase on OCP

== Role overview

* This role installs a RHODS and Starburst operator and basic configuration into an OpenShift Cluster. It consists of the following tasks files:
** Tasks: link:./tasks/pre_workload.yml[pre_workload.yml]:
*** Create's AWS s3 bucket and uploads the link:./files/creditcard_with_empty_values.tar.gz[dataset] used in this usecase.
*** Debug task will print out: `pre_workload Tasks completed successfully.`

** Tasks: link:./tasks/workload.yml[workload.yml]: 
*** Installs link:https://www.redhat.com/en/technologies/cloud-computing/openshift/openshift-data-science[RHODS] and link:https://catalog.redhat.com/software/container-stacks/detail/5ec3fa5078e79e6a879fa212[Starburst] operator. 
*** Configures Starburst operands to connect to s3 bucket (created earlier).
*** Debug task will print out: `workload Tasks completed successfully.`

** Tasks: link:./tasks/post_workload.yml[post_workload.yml]:
*** Checks starburst pods installation.
*** Deletes staruburst secret containing the license.
*** Debug task will print out: `post_workload Tasks completed successfully.`

** Tasks: link:./tasks/remove_workload.yml[remove_workload.yml]:
*** Uninstalls this role.
*** Debug task will print out: `remove_workload Tasks completed successfully.`

== Review the defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you need to define to control the deployment of your workload.

* You can modify any of these default values by adding `-e "variable_name=variable_value"` to the command line

=== Deploy a Workload with the `ocp-workload` playbook [Mostly for testing]

----
TARGET_HOST="bastion.abcd.example.opentlc.com"
OCP_USERNAME="vpower-redhat.com"
WORKLOAD="ocp4_workload_fraud_detection_usecase"
GUID="somecluster"
ANSIBLE_USER="vpower-redhat.com"

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=${ANSIBLE_USER}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"ACTION=create"
----

=== To Delete an environment

----
TARGET_HOST="bastion.abcd.example.opentlc.com"
OCP_USERNAME="vpower-redhat.com"
WORKLOAD="ocp4_workload_fraud_detection_usecase"
GUID="somecluster"
ANSIBLE_USER="vpower-redhat.com"

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=${ANSIBLE_USER}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"ACTION=remove"
----
