= Introduction to AgnosticD Training

Welcome! By following this guide you will begin your journey to a world of automated infrastructure deployments
and customization utilizing AgnosticD.

By the end of this introductory module, will be able to answer the following questions:

* What is AgnosticD
** Meet our developer friends and understand how it helps them
* What is a Cloud Provider
* What is a config, what is an infra-role, what is a ocp-workload role.
* How we use this in Production
** See a configuration live in production
** See an OpenShift workload live in production

NOTE: This training is built for RedHatters that work directly with the Global Partner and Technical Enablement team. They will have access to specific tools and pre-configured environments utilized in the learning exercises presented. If you are not a RedHatter or intend to manage your own infrastructure with AgnosticD, the information in this training is still useful, but your company/team's admins will have to set all the resources and credentials up and share them with you.

During this training, you will follow the story of Inara and Malcolm, two developers who will learn how AgnosticD can help them achieve their goals while learning about it with you.
