== Configs and Roles

=== Configs

A config is simply a lab, workshop, or other deployment that has been defined and encapsulated in a series of playbooks, variable files, and templates in a config directory. 
This allows Ansible Agnostic Deployer to deploy it simply and repeatedly on one or more cloud providers.

More Specifically, configs build infrastructure in a cloud provider. Meaning that we will expect a set of resources to result from the execution of the config. Usually, these resources are defined in a jinja template, normally located in a /files or /templates directory in the config's hosting directory.

In the last three years, the team has worked in a set of configs that match most of our user needs. In order to avoid code repetition and config sprawl, it is recommended that before you start building, you review the existing configs and try to find the one that matches your use case best.

Throughout this training, you will learn how to modify an existing config, so that you don't have to start from scratch.

You can find our available configs in: link:https://github.com/redhat-cop/agnosticd/tree/development/ansible/configs[/ansible/configs]


=== Roles

In our daily work with AgnosticD, we use specific names for roles in order to understand what they are meant to do quickly.
At the end of the day, they are not any more complicated than regular Ansible roles. You will find throughout this training, and when dealing with us every day, the following "AgnosticD jargon":

* *"Infra-Role"*: a role oriented to modifying a base infrastructure deployment.
It will be usually called as a part of a config, and will be hosted under the /roles-infra directory.
For example, a typical infra role would be a role that installs a web server in an instance.

* *"OCP-Workloads"*: these roles are specifically created to deploy a set of applications in an OpenShift cluster.
This type of role will take care of tasks like: quota creation, limit and request setup, application deployment, deployment verification and route publishing.
This roles are called *AFTER* the OpenShift cluster is deployed, and leverage a set of pre-configured users to deploy applications in a repetitive manner.
You are going to learn how all these ties up together in the "OpenShift Clusters & Workloads" module of this training.

You can find our existing roles at: link:https://github.com/redhat-cop/agnosticd/tree/development/ansible[/ansible]
You will be able to easily identify infra roles and OCP workloads by the directory name.

At the time of writing, the team is working hard in improving the directory structure and contribution guidelines. For the sake of learning "the latest and greatest best practices", ignore any other directories not referenced in this training. 
