== Cloud Providers in AgnosticD

So we just said that confgis deploy infrastructure to cloud providers, but Inara wonders "What is a cloud provider in the context of AgnosticD? Is it the same thing I have always worked with?"

Good question - The definition of a "cloud provider" within AgnosticD is no different than any other resource you have read in the past.
A cloud provider is a company that provides environments, managed or unamanaged, that abstract, pool, and share scalable resources across a network.

Later in this training, you will learn in detail how AgnosticD easily defines what cloud provider to hit with a variable, and utilizes cloud provider specific templates and tools to deploy infrastructure in them.

At the time of writing, you can find the the currently available cloud providers at: link:https://github.com/redhat-cop/agnosticd/tree/development/ansible/cloud_providers[/ansible/cloud_providers].

It is important to note, in spite of more being available, currently in production our support goes as far as:

* Amazon Web Services (AWS)
* Microsoft Azure
* Red Hat OpenStack Platform

