---
_ocp4_workload_dr_trident_fsx_admin_password: ""
_ocp4_workload_dr_trident_svm_admin_password: ""

_ocp4_workload_dr_trident_second_rosa_openshift_api_url: ""
_ocp4_workload_dr_trident_second_rosa_openshift_console_url: ""
_ocp4_workload_dr_trident_second_rosa_cluster_admin_password: ""
_ocp4_workload_dr_trident_second_rosa_cluster_admin_token: ""
