= RHEL Security



== Overview

This configuration provides the environment for the lab:

* Defend Yourself Using Built-in Red Hat Enterprise Linux Security Technologies

== Supported Cloud Providers


* AWS

== Review the Env_Type variable file

The link:./default_vars.yml[./default_vars.yml] and link:./default_vars_ec2.yml[./default_vars_ec2.yml] file contain all the variables you need to define to control the deployment of your environment.

This includes the ability to:

* Change the base packages installed 
* Change/set the `student_name` and `remote_user`

These can be over-ridden at `ansible-playbook` runtime via `-e` options or perhaps more compactly by overriding vars in your own var file and invoking via `-e @my_env_vars.yml`

For further information on customizing images consult the link:../../../docs/Creating_a_config.adoc[Creating a Config Guide] 


== Running Ansible Playbook


You can run the playbook with the following arguments, from the `ansible` directory, to overwrite the default variable values:
[source,bash]
----
REGION=us-east-1
KEYNAME=privkey
GUID=abc123
ENVTYPE="rhel-security"
CLOUDPROVIDER=ec2
HOSTZONEID='Z3IHLWJZOU9SRT'
BASESUFFIX='.example.opentlc.com'

ansible-playbook main.yml                       \
      -e "guid=${GUID}"                         \
      -e "env_type=${ENVTYPE}"                  \
      -e "key_name=${KEYNAME}"                  \
      -e "subdomain_base_suffix=${BASESUFFIX}"  \
      -e "cloud_provider=${CLOUDPROVIDER}"      \
      -e "aws_region=${REGION}"                 \
      -e "HostedZoneId=${HOSTZONEID}"           \
      -e "email=name@example.com"               \
      -e "output_dir=/tmp/workdir"              \
      -e@../secret.yml -vv




----

=== To Delete an environment
----

REGION=us-east-1
KEYNAME=privkey
GUID=abc123
ENVTYPE="rhel-security"
CLOUDPROVIDER=ec2

ansible-playbook ./ansible/configs/${ENVTYPE}/destroy_env.yml \
 -e "guid=${GUID}" -e "env_type=${ENVTYPE}"  -e "cloud_provider=${CLOUDPROVIDER}" -e "aws_region=${REGION}"  \
 -e "key_name=${KEYNAME}"  -e "subdomain_base_suffix=${BASESUFFIX}"    -e@../secret.yml -vv

----
