---
- name: Get any existing infra nodes
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Node
    label_selectors:
      - node-role.kubernetes.io/infra: ""
  register: r_infra_nodes

- name: Skip making infranodes if infranodes already exist
  when: r_infra_nodes.resources | length == 0
  block:

    - name: Find nodes to make infra nodes
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Node
        label_selectors:
          - "{{ ocp4_workload_infra_nodes_find_label }}"
      register: r_nodes

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ r_nodes.resources | length }}"

    - name: Fail for less than number of desired infra nodes
      ansible.builtin.assert:
        that: r_nodes.resources | length >= ocp4_workload_infra_nodes_count
        success_msg: "More than {{ ocp4_workload_infra_nodes_count }} infra nodes. Continuing."
        fail_msg: "Less than {{ ocp4_workload_infra_nodes_count }} infra nodes detected. Cannot make infranodes."

    - name: Debug names labels to nodes
      ansible.builtin.debug:
        msg: "{{ item.metadata.name }}"
      loop: "{{ r_nodes.resources[:ocp4_workload_infra_nodes_count] | list }}"

    - name: Add labels to nodes
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Node
          metadata:
            name: "{{ item.metadata.name }}"
            labels:
              "{{ ocp4_workload_infra_nodes_labels }}"
      loop: "{{ r_nodes.resources[:ocp4_workload_infra_nodes_count] | list }}"

    - name: Add taints to nodes, if desired
      when: ocp4_workload_infra_nodes_taints_enabled | bool
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Node
          metadata:
            name: "{{ item.metadata.name }}"
          spec:
            taints:
              "{{ ocp4_workload_infra_nodes_taints }}"
      loop: "{{ r_nodes.resources[:ocp4_workload_infra_nodes_count] | list }}"

    - name: Remove worker label from nodes, if desired
      when: ocp4_workload_infra_nodes_remove_worker_labels | bool
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Node
          metadata:
            name: "{{ item.metadata.name }}"
            labels:
              node-role.kubernetes.io/worker: NULL
              node-role.kubernetes.io=worker: NULL
      loop: "{{ r_nodes.resources[:ocp4_workload_infra_nodes_count] | list }}"
