= How to create an Environment Using Terraform


== Concept

Ansible is used to wrap Terraform and it's execution. A SSH key is created to be used for Ansible to connect to the new AWS instances it will configure. Ansible kicks the first playbook to create a SSH key from AWS and then parse the return json for the private ssh key that it then writes to `ansible/workdir/{{ workshop_prefix }}/{{ workshop_prefix }}-tower` with workshop_prefix being the unique identifier to separate different workshops. This `workshop_prefix` is prepended to all AWS tags for the workshop. This helps to keep clean separation inside the AWS account.

The next part Ansible uses the template module to template the aws.tf file to the workdir and have it pick up any custom variables. Then Terraform is run. Terraform is added as another cloud_provider in

[source]
----
ansible_agnostic_deployer/ansible/cloud_providers/terraform_infrastructure_deployment.yml
----

After the instances are created the rest of the Ansible Playbooks are run to configure the instances.


== Create a base for your new environment type using Terraform

Copy the `aws.tf` from the `files/cloud_providers/aws.tf` and make any modifications to the AWS infrastructure there in that file. You can update several infrastructure components such as;

- Terraform Variables
- API Keys
- VPC Settings
- Subnet Settings
- Route Associations
- Security Groups
- DNS Names
- AMI Settings
