---
- name: Clone tssc repository
  ansible.builtin.git:
    accept_hostkey: true
    force: true
    repo: "{{ ocp4_workload_advanced_developer_suite_tssc_cli_repo }}"
    dest: "~/tssc_cli"
    version: "{{ ocp4_workload_advanced_developer_suite_tssc_cli_revision }}"
  environment:
    GIT_SSL_NO_VERIFY: "true"

- name: Set environment type to development
  ansible.builtin.replace:
    path: ~/tssc_cli/installer/charts/tssc-dh/templates/app-config-content.yaml
    regexp: '^  environment: production'
    replace: '  environment: development'

- name: Create default authentication mode
  ansible.builtin.blockinfile:
    path: ~/tssc_cli/installer/charts/tssc-dh/templates/app-config-content.yaml
    block: |
      {% raw %}
        {{- if (and (not $azureSecretData) (not $githubSecretObj) (not $gitlabSecretData)) }}
          guest:
            dangerouslyAllowOutsideDevelopment: true
        {{- end }}
      {% endraw %}
    insertbefore: '^backend:$'
    create: yes

- name: Build tssc cli and install
  become: true
  ansible.builtin.shell: |
    make build
  args:
    chdir: ~/tssc_cli

- name: Deploy platform
  ansible.builtin.shell: |
    ./bin/tssc config --create
    ./bin/tssc deploy
  args:
    chdir: ~/tssc_cli

- name: Get developer hub environment secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    namespace: "{{ ocp4_workload_advanced_developer_suite_dh_namespace }}"
    name: tssc-developer-hub-env
  register: r_dh_env

- name: Get developer hub dynamic plugins config
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ConfigMap
    namespace: "{{ ocp4_workload_advanced_developer_suite_dh_namespace }}"
    name: tssc-developer-hub-dynamic-plugins
  register: r_dh_dyn_plg

- name: Get developer hub app config
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ConfigMap
    namespace: "{{ ocp4_workload_advanced_developer_suite_dh_namespace }}"
    name: tssc-developer-hub-app-config
  register: r_dh_app_config

- name: Set developer hub config facts
  set_fact:
    _dh_env: "{{ r_dh_env.resources[0] }}"
    _dh_dyn_plg: "{{ r_dh_dyn_plg.resources[0].data['dynamic-plugins.yaml'] | from_yaml }}"
    _dh_app_config: "{{ r_dh_app_config.resources[0].data['app-config.tssc.yaml'] | from_yaml }}"