---
- name: Create Devspaces resources
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', item) | from_yaml }}"
  loop:
  - openshift-gitops-application-controller-admin.yml.j2 d