---
- name: Retrieve Ingress config
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: Ingress
    name: cluster
  register: r_ingress_config

- name: Set global facts
  ansible.builtin.set_fact:
    ocp4_workload_advanced_developer_suite_apps_domain: "{{ r_ingress_config.resources[0].spec.domain }}"

- name: Install RHTAP platform
  ansible.builtin.include_tasks:
    file: ./install_platform.yml
    apply:
      become: true

- name: Configure keycloak
  ansible.builtin.include_tasks:
    file: ./setup_keycloak.yml

- name: Update dynamic plugins
  ansible.builtin.include_tasks:
    file: ./setup_dh_dynamic_plugins.yml

- name: Print Developer Hub secrets and config
  debug:
    msg: "{{ item }}"
  loop:
  - "{{ _dh_env }}"
  - "{{ _dh_dyn_plg }}"
  - "{{ _dh_app_config }}"

- name: Update developer hub app config
  kubernetes.core.k8s:
    state: present
    definition:
      api_version: v1
      kind: ConfigMap
      metadata:
        namespace: "{{ ocp4_workload_advanced_developer_suite_dh_namespace }}"
        name: tssc-developer-hub-app-config
      data:
        app-config.tssc.yaml: "{{ _dh_app_config | to_nice_yaml(indent=2) }}"

- name: Update developer hub secret
  kubernetes.core.k8s:
    state: present
    definition:
      api_version: v1
      kind: Secret
      metadata:
        namespace: "{{ ocp4_workload_advanced_developer_suite_dh_namespace }}"
        name: tssc-developer-hub-env
      data: "{{ _dh_env.data }}"

- name: Update developer hub dynamic plugins config
  kubernetes.core.k8s:
    state: present
    definition:
      api_version: v1
      kind: ConfigMap
      metadata:
        namespace: "{{ ocp4_workload_advanced_developer_suite_dh_namespace }}"
        name: tssc-developer-hub-dynamic-plugins
      data:
        dynamic-plugins.yaml: "{{ _dh_dyn_plg | to_nice_yaml(indent=2) }}"
