== Overview

*vld-pattern-base-binder* _config_ is used to do cross-cluster tasks
after all sub-components have been deployed

== Supported Cloud Providers

No cloud providers have been configured because this env_type is not meant to deploy resources, only interact with already available resources.

== Review the Env_Type variable file

For further information on customizing images consult the link:../../../docs/Creating_a_config.adoc[Creating a Config Guide]

== Review the `sample_vars.yml` variable file

----

---
guid:               test-config-00
env_type:           vld-pattern-base-binder
cloud_provider:     none
...

----

== Developing with `vld-pattern-base-binder`

You should get a file of "extra-vars" from the AnarchySubject of this base component.

Find the AnarchySubject for this component and copy out the appropriate job data into a local yaml file on your laptop.
You might call it `my_sample_vars.yaml`

While developing, you can deploy this config by running the following command from the `ansible`
directory.

`ansible-playbook main.yml -e @my_sample_vars.yaml -e @configs/vld-pattern-base-binder/sample_vars.yml`

