#!/bin/bash
yum remove -y google-rhui-client-rhel8.noarch
yum clean all

dnf install -y tree
TMUX='' tmux new-session -d -s 'Terminal1' > /dev/null 2>&1
tmux set -g pane-border-status top
tmux setw -g pane-border-format ' #{pane_index} #{pane_current_command}'