- name: Set home directory when user is not root
  set_fact:
    _home_dir: "/home/{{ ansible_user }}/"
  when: ansible_user != "root"

- name: Set home directory when user is not root
  set_fact:
    _home_dir: "/root/"
  when: ansible_user == "root"

- name: Generate SSH keys
  ansible.builtin.shell: ssh-keygen -b 2048 -t rsa -f {{ _home_dir }}/.ssh/id_rsa -q -N ""
  args:
    creates: "{{ _home_dir }}/.ssh/id_rsa"

- name: Generate SSH pub key
  ansible.builtin.shell: ssh-keygen -y -f {{ _home_dir }}/.ssh/id_rsa > {{ _home_dir }}/.ssh/id_rsa.pub
  args:
    creates: "{{ _home_dir }}/.ssh/id_rsa.pub"

- name: Slurp public key
  ansible.builtin.slurp:
    path: "{{ _home_dir }}/.ssh/id_rsa.pub"
  register: idrsapub

- name: Create cluster directory
  ansible.builtin.file:
    path: "{{ _home_dir }}/{{ cluster_name }}"
    state: directory
    mode: "0775"

- name: Check if version specific install-config.j2 exists
  ansible.builtin.stat:
    path: templates/install-config.yaml.{{ ocp4_installer_version }}.j2
  register: rconfig
  delegate_to: localhost
  become: false

- name: Use version-specific template for install-config-yaml
  when: rconfig.stat.exists
  ansible.builtin.set_fact:
    install_config_template_path: templates/install-config.yaml.{{ ocp4_installer_version }}.j2

- name: Use default template for install-config-yaml
  when: not rconfig.stat.exists
  ansible.builtin.set_fact:
    install_config_template_path: templates/install-config.yaml.j2

- name: Generate config install-config.yaml
  ansible.builtin.template:
    src: "{{ install_config_template_path }}"
    dest: "{{ _home_dir }}/{{ cluster_name }}/install-config.yaml"
    owner: "{{ ansible_user }}"
    mode: "0660"

- name: Make a copy of the cluster install config
  ansible.builtin.copy:
    remote_src: true
    src: "{{ _home_dir }}/{{ cluster_name }}/install-config.yaml"
    dest: "{{ _home_dir }}/{{ cluster_name }}/install-config.yaml.bak"
    owner: "{{ ansible_user }}"
    mode: "0660"
