---
- name: Get RELEASE_IMAGE
  ansible.builtin.shell: openshift-install version | awk '/release image/ {print $3}'
  environment:
    OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: quay.io/openshift-release-dev/ocp-release:4.18.4-x86_64
  register: r_release_image

- name: Generate /tmp/pull-secret.txt
  ansible.builtin.copy:
    content: "{{ ocp4_pull_secret | to_json if ocp4_pull_secret is mapping else ocp4_pull_secret }}"
    dest: /tmp/pull-secret.txt

- name: Get CCO_IMAGE
  ansible.builtin.shell: oc adm release info --image-for='cloud-credential-operator' {{ r_release_image.stdout }} -a /tmp/pull-secret.txt
  environment:
    OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: quay.io/openshift-release-dev/ocp-release:4.18.4-x86_64
  register: r_cco_image

- name: Extract ccoctl tool
  ansible.builtin.shell: |
    oc image extract {{ r_cco_image.stdout }} \
    --file="/usr/bin/ccoctl.rhel9" \
    -a /tmp/pull-secret.txt
  environment:
    OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: quay.io/openshift-release-dev/ocp-release:4.18.4-x86_64

- name: Copy ccoctl tool
  ansible.builtin.copy:
    remote_src: true
    src: ccoctl.rhel9
    dest: /home/{{ ansible_user }}/ccoctl
    mode: 0755

- name: Extract credentials
  ansible.builtin.shell: |
    oc adm release extract \
      --from={{ r_release_image.stdout }} \
      --credentials-requests \
      --install-config=/home/{{ ansible_user }}/{{ cluster_name }}/install-config.yaml.bak \
      --to=/home/{{ ansible_user }}/{{ cluster_name }}/credentials/
  environment:
    OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: quay.io/openshift-release-dev/ocp-release:4.18.4-x86_64

- name: Create IBMMService IDs
  environment:
    IBMCLOUD_API_KEY: "{{ ibmcloud_api_key }}"
  ansible.builtin.shell: |
    /home/{{ ansible_user }}/ccoctl ibmcloud create-service-id \
      --credentials-requests-dir=/home/{{ ansible_user }}/{{ cluster_name }}/credentials/ \
      --name={{ cluster_name }} \
      --output-dir=/home/{{ ansible_user }}/{{ cluster_name }}/ \
      --resource-group-name={{ ibmcloud_resource_group_name }}
  environment:
    OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: quay.io/openshift-release-dev/ocp-release:4.18.4-x86_64
