---
- name: Add API CNAME to Route53
  delegate_to: localhost
  amazon.aws.route53:
    aws_access_key: "{{ route53_aws_access_key_id }}"
    aws_secret_key: "{{ route53_aws_secret_access_key }}"
    hosted_zone_id: "{{ route53_aws_zone_id }}"
    zone: "{{ base_domain }}"
    record: "api.{{ cluster_name }}.ocp.{{ base_domain }}"
    type: "CNAME"
    ttl: 300
    value: "{{ lookup('community.general.dig', 'api.' + cluster_name + '.ocp.' + base_domain + '/CNAME')}}"
    overwrite: true
    state: "present"

- name: Add APPS CNAME to Route53
  delegate_to: localhost
  amazon.aws.route53:
    aws_access_key: "{{ route53_aws_access_key_id }}"
    aws_secret_key: "{{ route53_aws_secret_access_key }}"
    hosted_zone_id: "{{ route53_aws_zone_id }}"
    zone: "{{ base_domain }}"
    record: "*.apps.{{ cluster_name }}.ocp.{{ base_domain }}"
    type: "CNAME"
    ttl: 300
    value: "{{ lookup('community.general.dig', '*.apps.' + cluster_name + '.ocp.' + base_domain + '/CNAME')}}"
    state: "present"
  
- name: Delete NS record to Route53
  delegate_to: localhost
  amazon.aws.route53:
    aws_access_key: "{{ route53_aws_access_key_id }}"
    aws_secret_key: "{{ route53_aws_secret_access_key }}"
    hosted_zone_id: "{{ route53_aws_zone_id }}"
    zone: "{{ base_domain }}"
    record: "ocp.{{ base_domain }}"
    type: "NS"
    ttl: 300
    state: "absent"
