---
- name: Pre workload tasks - Platform setup
  ansible.builtin.debug:
    msg: "Setting up Advanced Developer Suite Platform - Infrastructure Only"

- name: Check if user is cluster admin
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: ClusterVersion
  register: r_cluster_version
  failed_when: r_cluster_version.resources | length == 0
