---
- name: Clone tssc repository
  become: true
  ansible.builtin.git:
    accept_hostkey: true
    force: true
    repo: "{{ ocp4_workload_advanced_developer_suite_platform_tssc_cli_repo }}"
    dest: "~/tssc_cli"
    version: "{{ ocp4_workload_advanced_developer_suite_platform_tssc_cli_revision }}"
  environment:
    GIT_SSL_NO_VERIFY: "true"

- name: Set environment type to development
  become: true
  ansible.builtin.replace:
    path: ~/tssc_cli/installer/charts/tssc-dh/templates/app-config-content.yaml
    regexp: '^  environment: production'
    replace: '  environment: development'

- name: Create default authentication mode
  become: true
  ansible.builtin.blockinfile:
    path: ~/tssc_cli/installer/charts/tssc-dh/templates/app-config-content.yaml
    block: |
      {% raw %}
        {{- if (and (not $azureSecretData) (not $githubSecretObj) (not $gitlabSecretData)) }}
          guest:
            dangerouslyAllowOutsideDevelopment: true
        {{- end }}
      {% endraw %}
    insertbefore: '^backend:$'
    create: yes

- name: Build tssc cli and install
  become: true
  ansible.builtin.shell: |
    make build
  args:
    chdir: ~/tssc_cli

- name: Deploy platform
  become: true
  ansible.builtin.shell: |
    ./bin/tssc config --create
    ./bin/tssc deploy
  args:
    chdir: ~/tssc_cli

- name: Set platform dependent products
  include_tasks: ./setup_platform_dependencies.yml