
:role: satellite-installation
:author: GPTE Team
:tag1: install_satellite
:tag2: install_firewalld
:tag3: public_hostname
:tag4: update_satellite_host
:tag5: setup_satellite
:main_file: tasks/main.yml
:version_file: tasks/version_6.4.yml


Role: {role}
============

This role installs and configure satellite and setup firewalld. 

Requirements
------------

. Basic repository should be configure to install packages. 

Role Variables
--------------

|===
|satellite_version: "Digit" |Required |satellite version
|satellite_admin: "String" |Required |Satellite admin username
|satellite_admin_password: "String" |Required |Satellite admin password
|firewall_services: [List] |Not-Required |List of services to enable, Default value are in defaults/main.yml
|firewall_ports: [List] |Not-Required |List of ports to enable, Default value are in defaults/main.yml
|===

* Example variables

[source=text]
----
satellite_version: 6.4
satellite_admin: admin
satellite_admin_password: password
firewall_services:
  - ssh
  - RH-Satellite-6
firewall_ports:
  - 22/tcp
  - 80/tcp
  - 443/tcp
----

Tags
---

|===
|{tag1} |Consistent tag for all satellite install tasks
|{tag2} |For firewall tasks
|{tag3} |For hostname setup tasks
|{tag4} |For host update tasks
|{tag5} |For satellite setup tasks 
|===

* Example tags

[source=text]
----
## Tagged jobs
ansible-playbook playbook.yml --tags install_satellite

## Skip tagged jobs
ansible-playbook playbook.yml --skip-tags install_satellite

----


Example Playbook
----------------

How to use your role (for instance, with variables passed in playbook).

[source=text]
----
[user@desktop ~]$ cat sample_vars.yml
satellite_version: 6.4
firewall_services:
  - ssh
  - RH-Satellite-6
firewall_ports:
  - 22/tcp
  - 80/tcp
  - 443/tcp

[user@desktop ~]$ cat playbook.yml
- hosts: satellite.example.com
  vars_files:
    - sample_vars.yml
  roles:
    - satellite-public-hostname
    - satellite-install

[user@desktop ~]$ ansible-playbook playbook.yml -e 'satellite_admin: admin' -e 'satellite_admin_password: password'
----

Dependencies
------------

Role has dependency of role satellite-public-hostname. 


Tips to update Role
------------------

To extend role works for other version, create new file named  version_{{satellite_version}}.yml and import newly created file in main.yml

for reference look at link:{main_file}[main.yml] and link:{version_file}[version_6.4.yml]


Author Information
------------------

{author}