= ocp4_workload_open_ssh_from_bastion - Configure the cloud to allow the Bastion host in OCP4 cluster to SSH to the control plane and worker nodes of the cluster

== Role overview

* This role creates a VPC peering connection between the Bastion and the associated OCP4 cluster VPCs.  It then modifies the associated routes and security groups to allow the Bastion host to SSH directly to the control plane and worker nodes of the cluster.  This access is essential for Red Hat Support teams to troubleshoot and recover OCP4 clusters where the recommended process ie. `oc debug node/<nodename>` is unavailable due to an outage/failure of the OpenShift API which is a common recovery scenario.

** Tasks: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an
 environment for the workload deployment.
*** Debug task will print out: `pre_workload Tasks completed successfully.`

** Tasks: link:./tasks/workload.yml[workload.yml] - Used to open the SSH communication between Bastion and OpenShift hosts
*** Debug task will print out: `workload Tasks completed successfully.`

** Tasks: link:./tasks/post_workload.yml[post_workload.yml] - Used to
 configure the workload after deployment
*** This role doesn't do anything here
*** Debug task will print out: `post_workload Tasks completed successfully.`

** Tasks: link:./tasks/remove_workload.yml[remove_workload.yml] - Used to
 delete the workload
*** This role doesn't do anything here
*** Debug task will print out: `remove_workload Tasks completed successfully.`

== Review the defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you need to define to control the deployment of your workload.
* The variable *ocp4_workload_open_ssh_from_bastion_enable=true* is mandatory to enable this role, by default, the role will not run.
* A variable *ocp4_workload_open_ssh_from_bastion_silent=false* can be passed to increase debug messages.
* The variables *ocp4_workload_open_ssh_from_bastion_region*, *ocp4_workload_open_ssh_from_bastion_access_key_id* and *ocp44_workload_open_ssh_from_bastion_secret_access_key* are required to be passed with the appropriate AWS sandbox values for this role to function.
* You can modify any of these default values by adding `-e "variable_name=variable_value"` to the command line

=== Deploy a Workload with the `ocp-workload` playbook [Mostly for testing]

----
TARGET_HOST="bastion.na4.openshift.opentlc.com"
WORKLOAD="ocp4_workload_open_ssh_from_bastion"
GUID=1001

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=ec2-user" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"ocp4_workload_open_ssh_from_bastion_silent=False" \
    -e"guid=${GUID}" \
    -e"ACTION=create"
----

=== To Delete an environment

----
TARGET_HOST="bastion.na4.openshift.opentlc.com"
OCP_USERNAME="wkulhane-redhat.com"
WORKLOAD="ocp4_workload_cert_manager"
GUID=1002

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=ec2-user" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"guid=${GUID}" \
    -e"ACTION=remove"
----
