= Custom images

== What happens during deployment

The AMI is detected before the cloudformation stack is created.

There is 2 detection strategies:

. Common images using the image name
+
Variable: `custom_image_filter`
+
Example:
+
[source,yaml]
----
custom_image_filter: RHEL 7.5 GOLD packer 1542702393
----
. Opiniated image using tags and the tuple (env_type, version, stage)
+
Variable: `custom_image_stage`  (env_type and version are already provided)
+
This allows us to enable or disable an AMI easily by adding or not the stage into its tag `stages`. env_type and version have to match the values in the tags of the image too.
+
Example:
+
[source,yaml]
----
custom_image_stage: PROD
----


If no AMI is found, then it defaults to what is used in the template.

== Build common images

=== Build to your account

Create and copy the image to multiple regions:

[source,bash]
----
packer build -var-file=${HOME}/secrets/gpte.json rhel_gold.json
----

== Requirements to use custom images

When deploying a config:

. Make sure either:
  * the config is using the common CloudFormation template
  * the CF template in the config directory supports the variable `custom_image`
. Run the playbook with `-e custom_image_filter=IMAGENAME`. For example:
+
----
-e "custom_image_filter='RHEL 7.5 GOLD packer 1542702393'"
----

If the image is found, then it will be used, otherwise, playbook defaults to what is defined in the CloudFormation template.

== Build opiniated images

TODO
