== How we use AgnosticD in Production

The Engineering team has been using AgnosticD in production for approximately 3 years. In May of 2020, considering both our platforms, Sales and Learning oriented, we have deployed almost 19.000 environments.
Plain environment would utilize only *configs*. However, the vast majority of these environments are customized after deploy. This means we also utilize actively a huge number of the *infra roles and OCP workloads* you will find in the repository. 

In order to help you close the circle and help you see live what all these is about, we will be mentioning a couple of the live deployments you can go look at in our platforms, and the config and ocp-workloads that build them.


=== Example of Config + OCP Workloads

*OpenShift Workshop 4.4:* One of the latest additions to Red Hat Product Demo System (RHPDS for short), the OpenShift 4.4 Workshop deploys an OpenShift cluster on AWS, pre-configured with:
* htpasswd authentication including 1 admin user and 200 regular users,
* OpenShift Ingress Namespace setup,
* Customizations specific to our OPEN Training program.
* a terminal pod to allow users to have in-browser terminal capabilities,
* Let's Encrypt certificates.

All these is achieved by executing the link:https://github.com/redhat-cop/agnosticd/tree/development/ansible/configs/ocp4-workshop[ocp4-workshop] config, and the following ocp-workloads:

* link:https://github.com/redhat-cop/agnosticd/tree/development/ansible/roles_ocp_workloads/ocp4_workload_authentication[ocp4_workload_authentication]
* link:https://github.com/redhat-cop/agnosticd/tree/development/ansible/roles_ocp_workloads/ocp4_workload_project_request_template[ocp4_workload_project_request_template] 
* link:https://github.com/redhat-cop/agnosticd/tree/development/ansible/roles_ocp_workloads/ocp4_workload_opentlc_production[ocp4_workload_opentlc_production]
* link:https://github.com/redhat-cop/agnosticd/tree/development/ansible/roles/ocp-workload-terminal[ocp_workload_terminal]
* link:https://github.com/redhat-cop/agnosticd/tree/development/ansible/roles/ocp4-workload-enable-lets-encrypt-certificates[ocp4_workload_enable_lets_encrypt_certificates]

NOTE: Please note that according to the new standard all OCP workloads must be named with underscores. Please ignore any inconsistencies you may be seeing here, we are migrating to a new format.

* TIP: This seems to Malcolm, like a good environment to test against while developing from his laptop. In this way, he can build a role that deploys what he needs and test it against the cluster. Once all is ready, it must be easy for the GPTE Engineering Team to get his OCP Workload to run against this type of cluster that they know so well.

=== Configs + Infra Roles

In the case of a live config that makes good use of infra roles, you can look at link:https://github.com/redhat-cop/agnosticd/tree/development/ansible/configs/ansible-advanced[ansible-tower-advanced]
You can order this laboratory in link:https://labs.opentlc.com[our Learning Platform]

Due to the changes currently happening in our repo this config is today not following the best practices that we are proposing during the training, you will know a way to do better - Why not collaborate to improve this one if you have time?

* TIP: By learning how to appropriately use infra roles with this training, Inara will be able to achieve an automated Ansible Tower installation just like the one in this example, or even install all sorts of different software!


