---
- name: Include pre-checks
  import_tasks: pre_checks.yml

- name: Include Terraform deployment
  import_tasks: terraform_deploy.yml
  when: ACTION == 'provision'

- name: Include Terraform destroy
  import_tasks: terraform_destroy.yml
  when: ACTION == 'destroy' 