= Overview

*minimal* is indeed minimal and provides zero deployment logic.
IE run by itself with no vars it will simple run through all the stage playbooks and do nothing.

It is intended to be used as a config where the user brings all their own logic in the form of workload roles.

== Workloads

Workloads are defined as a set of roles that are applied to a host and/or cloud.

[source,sh]
----
pre_infra_workloads
infra_workloads
post_infra_workloads
pre_software_workloads
software_workloads
post_software_workloads
----

In addition workloads can be provided for stop, start, and destroying

[source,sh]
----
destroy_workloads
stop_workloads
start_workloads
----

== Usage

[source,sh]
----
ansible-playbook ansible/main.yml -e @ansible/configs/minimal/default_vars.yml
----

| This will run through all the stage playbooks and do nothing.

== Use Cases

* Immutable Operating Systems eg RHEL AI (traditional configs by default assume mutability)
* Highly customized infrastructure bypassing a traditional cloud_provider

=== Cloud Support

None - it is intended to be used as a config where the user brings all their own logic in the form of workload roles.

=== Architecture

None

== Developers Notes

Authors: Tony Kay (ankay@redhat.com) 2025-01-03
