= ocp4_workload_ansible_automation_platform - Ansible Automation Platform Workload Role

== Role overview

Deploys Ansible Automation Platform onto an OpenShift cluster, into a new project or an existing project.

* Automation Controller and Private Automation Hub (PAH)
* Injects Manifest if provided *and* requested (see below)

Created by: Tony Kay, tok@redhat.com
Date: 2022-04-18

== Role Returns

This role returns, via agnosticd_user_info (info and data) the following:

[source,yaml]
----
aap_controller_web_url: "https://{{ automation_controller_hostname }}"
aap_controller_admin_user: "{{ ocp4_workload_ansible_automation_platform_admin_username | default('admin') }}"
aap_controller_admin_password: "{{ ocp4_workload_ansible_automation_platform_admin_password }}"
----

=== Resources and PriorArt

. link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/deploying_the_red_hat_ansible_automation_platform_operator_on_openshift_container_platform/index[Deploying the Red Hat Ansible Automation Platform operator on OpenShift Container Platform]
.. Especially Chapter 5 - link:https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/deploying_the_red_hat_ansible_automation_platform_operator_on_openshift_container_platform/ansible-automation-platform-operator#installing-the-operator[Installing the Operator]
.. Note the `oc apply` documented in Chapter 5 will fail, as the Subscription needs time to be created. The `oc apply` command should be run again after a few moments.
. link:https://github.com/redhat-cop/agnosticd/tree/development/ansible/roles_ocp_workloads/ocp4_workload_lpe_automation_controller[Agnosticd LPE role]
. link:https://gitlab.com/ansible-ssa/role-aap-operator[Ansible SSA AAP Operator role]
.. Very comprehensive

== Review the defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you need to define to control the deployment of your workload.
* A variable *silent=True* can be passed to suppress debug messages.
* You can modify any of these default values by adding `-e "variable_name=variable_value"` to the command line


=== Providing and Injecting a Manifest

By default *no* Manifest is injected. To inject a manifest, you need to provide the following variables:

[source,yaml]
----
ocp4_workload_ansible_automation_platform_manifest:
  inject: true
  url: https://example.com/manifest <1>
  username: <USER> <2>
  password: <PASSWORD> <3>
----

. Valid Automation Controller Manifest file
. username - username for an external authentication eg external CDN via htpasswd etc
. password - password for an external authentication eg external CDN via htpasswd etc


=== Deploy a Workload with the `ocp-workload` playbook [Mostly for testing]

. Authenticate to the cluster e.g. `oc login ...`
. Run a playbook calling the `ocp4_workload_ansible_automation_platform` role

.Sample Playbook
[source,yaml]
----
---

- name: Test ocp4_workload_ansible_automation_platform role
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    ACTION: create
    ocp4_workload_ansible_automation_platform_admin_password: <DESIRED_PASSWORD>

  roles:

    - ocp4_workload_ansible_automation_platform
----

=== To Delete an environment

Simply call the above playbook with `ACTION: remove`
