== Overview

*ansible-multi-node* is a more modern derivitive from the earlier *Three Tier App* _config_

It makes an ideal base infrastructure to build on and can easily be extended via it's `env_vars.yml` to less or more machines and also to different operating system images.


== Supported Cloud Providers (`cloud_provider`)

* AWS EC2           # `cloud_provider: ec2`
* OSP (OpenStack)   # `cloud_provider: osp`

== Review the `default_vars.yml` variable files

The link:./default_vars.yml[./env_vars.yml] file contains all the variables you need to define to control the deployment of your environment.

This includes the ability to:

* Set the `cloud_provider`
* Change the number of machines deployed
* Changed the operating system image (e.g. Ansible AMI or similar)
* Change the tags carried by any instances
* Change the base packages installed
* Change/set the `ansible_user` and `remote_user`

These can be over-ridden at `ansible-playbook` runtime via `-e` options or perhaps more compactly by overriding vars in your own var file and invoking via `-e @my_env_vars.yml`

For further information on customizing images consult the link:../../../docs/Creating_a_config.adoc[Creating a Config Guide]

== Deploying the `ansible-multitier-infra` config

You can deploy this config by running the following command from the `ansible`
directory. You will have to provide credentials and adjust settings to your own
environment.

`ansible-playbook main.yml -e @configs/ansible-multitier-infra/sample_vars_ec2.yml -e @<YOUR_SECRET_VARS.yml>`


=== Sample Var files

A number of sample var files are provided for both OpenStack and AWS:

=== To Delete an environment
----
`ansible-playbook destroy.yml -e @configs/ansible-multitier-infra/sample_vars_ec2.yml -e @<YOUR_SECRET_VARS.yml>`

----




