---
- name: Step 002 Post Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step002
    - post_infrastructure
  tasks:
    - name: XClarity Post Infrastructure Message
      ansible.builtin.debug:
        msg: "Step 002 Post Infrastructure - XClarity Console User Deployment Complete" 