---
- name: Step 000 Pre Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step000
    - pre_infrastructure
  tasks:
    - name: XClarity Pre Infrastructure Message
      ansible.builtin.debug:
        msg: "Step 000 Pre Infrastructure - XClarity Console User" 