FROM registry.access.redhat.com/ubi8/ubi:8.7

USER root
WORKDIR /root

RUN dnf install -y python39-pip \
        bind-utils \
        findutils \
        gcc \
        git \
        gnupg2 \
        jq \
        krb5-devel \
        krb5-libs \
        libcurl-devel \
        libxml2-devel \
        openssl \
        openssl-devel \
        python39 \
        python39-devel \
        rsync \
        tar \
        unzip \
        vim \
        curl \
        wget \
    && dnf clean all

# Python

RUN alternatives --set python /usr/bin/python3.9
RUN alternatives --install /usr/bin/pip pip /usr/bin/pip3.9 1
RUN pip install --upgrade pip
COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

# Galaxy collections and roles

COPY ansible.cfg /root/.ansible.cfg
COPY requirements.yml /tmp/requirements.yml
RUN ansible-galaxy role install $ANSIBLE_GALAXY_CLI_ROLE_OPTS \
    -r /tmp/requirements.yml \
    --roles-path "/usr/share/ansible/roles"
RUN ANSIBLE_GALAXY_DISABLE_GPG_VERIFY=1 \
    ansible-galaxy collection install -vv \
    $ANSIBLE_GALAXY_CLI_COLLECTION_OPTS -r /tmp/requirements.yml \
    --collections-path "/usr/share/ansible/collections"

# AWS, Bitwarden, OC client
COPY install_binaries.sh /tmp/install_binaries.sh
RUN /tmp/install_binaries.sh

# Azure CLI

COPY azure-cli.repo /etc/yum.repos.d/azure-cli.repo
RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc \
    && dnf install -y azure-cli \
    && dnf clean all


RUN pip freeze

RUN rm -rf /tmp/*

# In OpenShift, container will run as a random uid number and gid 0. Make sure things
# are writeable by the root group.
RUN for dir in \
      /home/runner \
      /home/runner/.ansible \
      /home/runner/.ansible/tmp \
      /runner \
      /home/runner \
      /runner/env \
      /runner/inventory \
      /runner/project \
      /runner/artifacts ; \
    do mkdir -m 0775 -p $dir ; chmod -R g+rwx $dir ; chgrp -R root $dir ; done && \
    for file in \
      /home/runner/.ansible/galaxy_token \
      /etc/passwd \
      /etc/group ; \
    do touch $file ; chmod g+rw $file ; chgrp root $file ; done

VOLUME /runner
WORKDIR /runner

ENV HOME=/home/runner

ADD https://raw.githubusercontent.com/ansible/ansible-runner/devel/utils/entrypoint.sh /usr/local/bin/entrypoint
RUN chmod 755 /usr/local/bin/entrypoint

COPY --from=quay.io/ansible/receptor:v1.3.0 /usr/bin/receptor /usr/bin/receptor
RUN mkdir -p /var/run/receptor

ENTRYPOINT ["entrypoint"]
CMD ["/usr/local/bin/ansible-runner", "run", "/runner"]
#USER 1000

LABEL ansible-execution-environment=true \
      name="agnosticd/ee-multicloud" \
      maintainer="Red Hat CoP"
