== Changelog ==

=== v0.0.11 ===

* Install requirements of the different collections
* python modules `pip freeze`: link:https://gist.github.com/fridim/d772d92cba92c07c0ffa00ddd2035c4e[gist]
* ansible galaxy collections:
+
----
Collection                     Version
------------------------------ -------
amazon.aws                     5.2.0
ansible.netcommon              4.1.0
ansible.posix                  1.5.1
ansible.utils                  2.9.0
awx.awx                        21.12.0   NEW
azure.azcollection             1.14.0
community.aws                  5.2.0
community.general              6.3.0
community.vmware               3.3.0
equinix.metal                  1.4.1
google.cloud                   1.1.2
infra.controller_configuration 2.2.5
kubernetes.core                2.4.0
openstack.cloud                2.0.0
----

=== v0.0.10 ===
* Add infra.controller_configuration collection
* Add google.cloud collection
* Add community.vmware collection
* Add equinix.metal collection

=== v0.0.9 ===
* `ansible-galaxy collection install`: Do not disable GPG verification
* More cleanup of build and cache files
* Don't cache pip files
* Fix alternatives python3 was pointing to python3.6 and that can fail in some edge cases. Switch it to python3.9

=== v0.0.8 ===
* Migrate to a simple Containerfile using UBI8 image, see https://github.com/redhat-cop/agnosticd/pull/5926

=== v0.0.7 ===

* add `openssl` binaries

=== v0.0.6 ===

* Cleanup requirements.txt file, let builder pull the dependencies from collections
* add `azure.azcollection` collection
* add `ansible.utils` collection
* add ansible-core package (rpm) to fix collection routing
* add vim and find binary
* add `dnspython` to python requirements.txt

=== v0.0.5 ===

* add `gnupg2` to EE
