#!/bin/bash

yum remove -y google-rhui-client-rhel8.noarch
yum clean all

dnf install -y python2

echo "Adding wheel" > /root/post-run.log
usermod -aG wheel rhel

echo "setting password" >> /root/post-run.log
echo redhat | passwd --stdin rhel

echo "adding cockpit" >> /root/post-run.log
yum -y install cockpit cockpit-packagekit

echo "starting cockpit" >> /root/post-run.log
systemctl start cockpit

#Set the password expiry for the rhel user to never
chage -M -1 rhel

echo "DONE" >> /root/post-run.log

curl -o /root/install_sql.sh https://raw.githubusercontent.com/rhel-labs/learn-katacoda/master/sql-server-crypto-policy/install_sql.sh
sudo chmod +x ./install_sql.sh
sudo ./install_sql.sh
export HOSTNAME=`hostname --all-fqdns`

# Enable ssh logins with a password.
sudo sed -i "/^[^#]*PasswordAuthentication[[:space:]]no/c\PasswordAuthentication yes" /etc/ssh/sshd_config
systemctl reload sshd