= Cluster Application Migration Workload

== Overview

This is a workload for Cluster Application Migration Tool.

It includes the migration operator which deploys migration controller, migration ui and Velero.

=== Deploy the workload
[source,'bash']
----
ansible-playbook -i "bastion.${GUID}.${BASE_DOMAIN}", ./ansible/configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=${ANSIBLE_USER_KEY_FILE}" \
    -e"ansible_user=${ANSIBLE_USER}" \
    -e"ocp_workload=ocp-workload-migration" \
    -e"silent=False" \
    -e"ACTION=create" \
    -e @./secret.yaml <1> \
    -e @./workload.yaml <2>
----
<1> This is the file you used when deploying your cluster with AgnosticD.
<2> All variables required by the workload go in this file.

=== Variables

This workload does not require any variables. Following variables can be overridden if you do not want default behaviour.

|===
| Variable | Default Value | Description

| mig_operator_deploy_velero
| true
| Deploy Velero?
| No

| mig_operator_deploy_controller
| default
| Deploy migration controller?
| No

| mig_operator_deploy_ui
| true
| Deploy migration UI?
| No

| mig_controller_limits_memory
| '600Mi'
| Memory limits for controller
| No

| mig_controller_requests_memory
| '512Mi'
| Memory requests for controller
| No
|===


=== Delete the workload

[source,'bash']
----
ansible-playbook -i "bastion.${GUID}.${BASE_DOMAIN}", ./ansible/configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=${ANSIBLE_USER_KEY_FILE}" \
    -e"ansible_user=${ANSIBLE_USER}" \
    -e"ocp_workload=ocp-workload-velero" \
    -e"silent=False" \
    -e"ACTION=delete" \
    -e @./secret.yaml \
    -e @./workload.yaml
----

