---
become_override: false
ocp_username: system:admin
silent: false

ocp4_workload_aro_machineset_suffix: "v5"
ocp4_workload_aro_machineset_replicas: 1
ocp4_workload_aro_machineset_instance_type: "Standard_D8s_v5" # too small, but what quota allows 2025-09-25
ocp4_workload_aro_machineset_disk_size: 128

ocp4_workload_aro_machineset_wait_for_nodes: false

ocp4_workload_aro_machineset_wait_for_nodes_retries: 10
ocp4_workload_aro_machineset_wait_for_nodes_delay: 60

####################################################
# This must match the other machines in the ARO cluster.
# But for your amusement, azure image details are available through the az cli:
# az vm image list --all --offer aro4 --publisher azureopenshift -o table > arotable.txt
ocp4_workload_aro_machineset_azure_image_offer: aro4
# publisher: azureopenshift
ocp4_workload_aro_machineset_azure_image_publisher: azureopenshift
# resourceID: ""
# sku: aro_418
ocp4_workload_aro_machineset_azure_image_sku: aro_417
# version: 417.94.20240701
# version: 418.94.20241122
ocp4_workload_aro_machineset_azure_image_version: 417.94.20240701
####################################################
