:scrollbar:
:data-uri:
:toc2:
:linkattrs:

= 3scale Multitenant API Manager 

:numbered:

== Overview

This workload provisions all the required resources for 3scale API Manager & tenants On OpenShift 4. The following are provisioned:

. 3scale Operator
. 3scale Multitenant API Manager 2.9 (using RWO System Storage or S3 compatible provider)
. 3scale Tenants for specified number of users
. 3scale Gateway Projects for each user:
.. Gateway Operator 2.9
.. Portal Endpoint secret for connecting to corresponding 3scale tenant admin
.. Staging & Production API Gateways


=== Prerequisites and assumptions

An OCP 4 cluster is provisioned and this role is run using a cluster admin.


. The version of 3scale provisioned in this lab (v2.9) is known to run on OpenShift Container Platform v4.*.
+
This version of OpenShift should already be pre-installed before executing this ansible role.

. Using a version of oc utility that corresponds to your target OCP cluster, ensure oc utility is already authenticated as the cluster-admin.

. This ansible role requires installation of the lxml python module on target host executing this ansible. ie:
+
-----
# dnf install python3-lxml
-----

. It is highly recommended that you SSH into the bastion node of your OCP cluster. The following tasks are best executed on the bastion node.
+
-----
# ssh -i ~/.ssh/your_private_key_name <OPENTLC_ID>@bastion.<GUID>.openshift.opentlc.com
-----

. Ensure that you are explicitly logged onto the master API of the OCP cluster, from your bastion node.
+
-----
# oc login master.<GUID>.openshift.opentlc.com
-----


==== SMTP Providers
You'll want to have registered with an smtp provider to enable the 3scale API Manager with the ability to send emails.

In 3scale, smtp settings are configured globally and is leveraged by all API _tenants_.
When provisioning 3scale, you can specify the following ansible variables:

* smtp_host
* smtp_userid
* smtp_passwd
* smtp_authentication


A few SMTP providers with _Free Plans_ that this ansible role has been tested with are listed below:

. *SocketLabs:* Currently offering a free plan that allows for link:https://www.socketlabs.com/signup/[2000 emails per month]
. *SendGrid:* Currently offering a free plan that allows for link:https://sendgrid.com/pricing/[100 emails per day]

You can choose to provision your 3scale API Manager such that it is not configured to send emails.
To do so, ensure that the value of _smtp_userid_ = "changeme"

=== Project Layout

. Notice the directory layout and files included in this project:
+
-----
$ tree

├── defaults
│   └── main.yml
├── meta
│   └── main.yml
├── README.adoc
├── tasks
│   ├── main.yml
│   ├── pre_workload.yml
│   ├── remove_workload.yml
│   ├── wait_for_deploy.yml
│   └── workload.yml
│   └── post_workload.yml
│   └── tenant_loop.yml
└── templates
    └── << all the k8s object J2 files >>
-----

. Highlights of the most important files are as follows:

.. *defaults/main.yml* : ansible variables and their defaults
.. *tasks/workload.yml* : ansible tasks executed when provisioning 3scale API Manager




== Deployment

=== Environment Variables

-----
# Update the following:


$ api_manager_namespace=3scale-amp      # OCP namespace where 3scale API Manager resides

# Execute the following:
$ source ~/.bashrc


# SMTP Configurations to enable API Manager to send emails
# If the SMTP values are not provided SMTP is not set up for 3scale & emails cannot be sent. This does not impact the usability in demos or workshops that do not use this feature.
$ smtp_host=smtp.socketlabs.com
$ smtp_port=587
$ smtp_authentication=login
$ smtp_userid=<change me>
$ smtp_passwd=<change me>
$ smtp_domain=redhat.com

# Admin Email user and domain:
    
$ adminEmailUser=<change me>            # e.g 3scaleadmin
$ adminEmailDomain=<change me>          # e.g redhat.com


use_rwo_for_cms=false                   #   3scale control plane consists of a Content Management System (CMS) that typically is scaled out for improved performance in a production environment
                                        #   This CMS subsequently requires a ReadWriteMany access mode for its corresponding "system-storage" PVC
                                        #   In a deployment of 3scale control plane to OCP 4.* where AWS EBS is used for storage, a ReadWriteMany access mode is not available
                                        #     Reference:   https://docs.openshift.com/container-platform/4.2/storage/understanding-persistent-storage.html#pv-access-modes_understanding-persistent-storage
                                        #   In that scenario, set this environment variable to: true
                                        #   Doing so hacks the 3scale control plane template to specify ReadWriteOnce (and not ReadWriteMany)
                                        #   If you set this to true, then do not attempt to create more than one replica of the system-app pod 

$ rht_service_token_user=<change me>    #   RHT Registry Service Account name as per:   https://access.redhat.com/terms-based-registry
$ rht_service_token_password=<changeme> #   RHT Registry Service Account passwd as per: https://access.redhat.com/terms-based-registry/

# Create tenants
$ number_of_tenants=1                   #   Number of tenant accounts to be created. Default is 1.

$ create_tenants: True                  #   If tenant accounts need to be created as part of the provisioning. Default is `True`
$ number_of_tenants: 1                  #   Number of tenant accounts to be created. Default is 1.
tenant_admin_name_base: api             #   Name of the Admin user in each tenant.
ocp_user_name_base: user                #   Name of the OCP users in the cluster. Default is `user` on RHPDS we get user1 .. user50 pre-created.
tenant_admin_password: admin            #   Default password for each tenant admin.
create_gws_with_each_tenant: True       #   To create a Gateway Project & deploy APIcast staging & production as self-managed gateways for each tenant.
-----

=== Provision  API CICD Lab

The OCP namespace for 3scale multi-tenant app will be owned by the admin user.


. Execute:
+
-----

# 3scale Multitenant API Manager & Tenants Provisoning
$  ansible-playbook -i localhost, -c local ./configs/ocp-workloads/ocp-workload.yml \
                    -e ocp_workload=ocp4-workload-3scale-s3 \
                    -e ACTION=create \
                    -e"api_manager_namespace=$api_manager_namespace" \
                    -e"smtp_port=$smtp_port" \
                    -e"smtp_authentication=$smtp_authentication" \
                    -e"smtp_host=$smtp_host" \
                    -e"smtp_userid=$smtp_userid" \
                    -e"smtp_passwd=$smtp_passwd" \
                    -e"smtp_domain=$smtp_domain" \
                    -e"adminEmailUser=$adminEmailUser" \
                    -e"adminEmailDomain=$adminEmailDomain" \
                    -e"rht_service_token_user=$rht_service_token_user" \
                    -e"rht_service_token_password=$rht_service_token_password" \
                    -e"use_rwo_for_cms=$use_rwo_for_cms" \
                    -e"number_of_tenants=$number_of_tenants"
-----

. After about 5 minutes, provisioning of the  API Manager should complete.


=== Remove Provisioned Artifacts

Run the remove workload with *ACTION=remove* in order to remove all of the projects created as part of this workload. 

. Execute:
+
----

$ ansible-playbook -i localhost, -c local ./configs/ocp-workloads/ocp-workload.yml \
                    -e ocp_workload=ocp4-workload-3scale-s3 \
                    -e number_of_tenants=1
                    -e ACTION=remove

----

All the projects created as part of this workload will be removed.



