= How to create an Environment Type

== Create a base for your new environment type

* Duplicate the "generic-example" environemnt type directory or use another
 environment type directory that is closer to your end goal.

== Edit your cloud provider "blueprint" or "template"

NOTE: At this point this is "aws" based, with time we will have other providers.

* Edit the link:./files/cloud_providers/ec2_cloud_template.j2[./files/cloud_provides/ec2_cloud_template.j2]

* Add Security Groups if you require any.
* Add LaunchConfigs and AutoScale Groups

----
"HostLC": {
  "Type": "AWS::AutoScaling::LaunchConfiguration",
  "Properties": {
    "AssociatePublicIpAddress": true,
    "ImageId": {
      "Fn::FindInMap": [
        "RegionMapping",
        {
          "Ref": "AWS::Region"
        },
        "AMI"
      ]
    },
    "InstanceType": "{{host_instance_type}}",
    "KeyName": "{{key_name}}",
    "SecurityGroups": [
      {
        "Ref": "HostSG"
      }
    ],
    "BlockDeviceMappings": [
      {
        "DeviceName": "/dev/xvda",
        "Ebs": {
          "VolumeSize": 30
        }
      },
      {
        "DeviceName": "/dev/xvdb",
        "Ebs": {
          "VolumeSize": 100
        }
      }
    ]
  }
},
"HostAsg": {
  "Type": "AWS::AutoScaling::AutoScalingGroup",
  "Properties": {
    "DesiredCapacity": {{host_instance_count}},
    "LaunchConfigurationName": {
      "Ref": "HostLC"
    },
    "MaxSize": 100,
    "MinSize": 1,
    "Tags": [
      {
        "Key": "Name",
        "Value": "host",
        "PropagateAtLaunch": true
      },
      {
        "Key": "AnsibleGroup",
        "Value": "hosts",
        "PropagateAtLaunch": true
      },
      {
        "Key": "Project",
        "Value": "{{project_tag}}",
        "PropagateAtLaunch": true
      },
      {
        "Key": "{{ project_tag }}",
        "Value": "host",
        "PropagateAtLaunch": true
      }
    ],
    "VPCZoneIdentifier": [
      {
        "Ref": "PublicSubnet"
      }
    ]
  }
},
----

** Pay attention to the Tags created for the different AS groups

----

{
  "Key": "Project",
  "Value": "{{project_tag}}",
  "PropagateAtLaunch": true
},
{
  "Key": "{{ project_tag }}",
  "Value": "host",
  "PropagateAtLaunch": true
}

----


* Add DNS Entries you need for your environment:
----
"MasterDNS": {
  "Type": "AWS::Route53::RecordSetGroup",
  "DependsOn": "Master",
  "Properties": {
    "HostedZoneId": "{{HostedZoneId}}",
    "RecordSets": [
      {
        "Name": "{{master_public_dns}}",
        "Type": "A",
        "TTL": "10",
        "ResourceRecords": [
          {
            "Fn::GetAtt": [
              "Master",
              "PublicIp"
            ]
          }
        ]
      }
    ]
  }
},

----

* Add S3 or other resources you require:
----

"RegistryS3": {
  "Type": "AWS::S3::Bucket",
  "Properties": {
    "BucketName": "{{ env_type }}-{{ guid }}",
    "Tags": [
      {
        "Key": "Name",
        "Value": "s3-{{ env_type }}-{{ guid }}"
      },
      {
        "Key": "Project",
        "Value": "{{project_tag}}"
      }
    ]
  }
}
},
----

* Add any "outputs" you need from the cloud provider:
----
"RegistryS3Output": {
  "Description": "The ID of the S3 Bucket",
  "Value": {
    "Ref": "RegistryS3"
  }},

----



== Internal DNS file


* Edit the internal dns template: link:./files/ec2_internal_dns.json.j2[./files/ec2_internal_dns.json.j2]
** You can create nicely indexed internal hostname by creating a for loop in the file  for each host group
----
{% for host in groups['support'] %}
    {
      "Action": "{{DNS_action}}",
      "ResourceRecordSet": {
        "Name": "support{{loop.index}}.{{zone_internal_dns}}",
        "Type": "A",
        "TTL": 20,
        "ResourceRecords": [ { "Value": "{{hostvars[host]['ec2_private_ip_address']}}" } ]
      }
    },

----
