= ocp4_workload_dso - Install and Configure Hands-On Lab for Advanced DevSecOps App Development

== Role overview

* This role enables the DevSecOps Workshop Dev Track on an OpenShift 4 Cluster. It consists of the following playbooks:
** Playbook: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an
 environment for the workload deployment
*** Adds a user to a list of groups defined in the
 link:./defaults/main.yml[defaults file].
*** Sets a cluster resource quota for the user based on the variables in the
 link:./defaults/main.yml[defaults file] .
*** Debug task will print out: `pre_workload Tasks Complete`

** Playbook: link:./tasks/workload.yml[workload.yml] - Used to deploy the actual
 workload, i.e, 3scale, Mobile or some Demo
*** This role doesn't do anything here
*** Debug task will print out: `workload Tasks Complete`

** Playbook: link:./tasks/post_workload.yml[post_workload.yml] - Used to
 configure the workload after deployment
*** This role doesn't do anything here
*** Debug task will print out: `post_workload Tasks Complete`

== Review the defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you
 need to define to control the deployment of your workload.

* You can modify any of these default values by adding
`-e"variable_name=variable_value"` to the command line

=== Deploy a Workload with the `ocp4_workload_dso` playbook [Mostly for testing]

----
GUID=raleigh-fb78
NUM_USERS=3
DOMAIN="$GUID.openshiftworkshop.com"
SSH_PRIVATE_KEY="id_rsa"
SSH_USER="ec2-user"
TARGET_HOST="bastion.$DOMAIN"
WORKLOAD="ocp4_workload_dso"
# Retrieve QUAY password here: https://access.redhat.com/solutions/3533201
QUAY_PULL_USERNAME=UPDATE_ME
QUAY_PULL_PASSWORD=UPDATE_ME

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
                 -e"ansible_ssh_private_key_file=~/.ssh/${SSH_PRIVATE_KEY}" \
                 -e"ansible_user=${SSH_USER}" \
                 -e"ansible_python_interpreter=/opt/virtualenvs/k8s/bin/python" \
                 -e"ocp_workload=${WORKLOAD}" \
                 -e"ocp4_dso_guid=${GUID}" \
                 -e"ocp4_dso_domain=${DOMAIN}" \
                 -e"ocp4_dso_user_count=${NUM_USERS}" \
                 -e"ocp4_dso_quay_pull_user=${QUAY_PULL_USERNAME}" \
                 -e"ocp4_dso_quay_pull_password=${QUAY_PULL_PASSWORD}" \
                 -e"ACTION=create"
----

=== To Delete an environment

----
GUID=raleigh-fb78
NUM_USERS=3
DOMAIN="$GUID.openshiftworkshop.com"
SSH_PRIVATE_KEY="id_rsa"
SSH_USER="ec2-user"
TARGET_HOST="bastion.$DOMAIN"
WORKLOAD="ocp4_workload_dso"
# Retrieve QUAY password here: https://access.redhat.com/solutions/3533201
QUAY_PULL_USERNAME=UPDATE_ME
QUAY_PULL_PASSWORD=UPDATE_ME

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
                 -e"ansible_ssh_private_key_file=~/.ssh/${SSH_PRIVATE_KEY}" \
                 -e"ansible_user=${SSH_USER}" \
                 -e"ansible_python_interpreter=/opt/virtualenvs/k8s/bin/python" \
                 -e"ocp_workload=${WORKLOAD}" \
                 -e"ocp4_dso_guid=${GUID}" \
                 -e"ocp4_dso_domain=${DOMAIN}" \
                 -e"ocp4_dso_user_count=${NUM_USERS}" \
                 -e"ocp4_dso_quay_pull_user=${QUAY_PULL_USERNAME}" \
                 -e"ocp4_dso_quay_pull_password=${QUAY_PULL_PASSWORD}" \
                 -e"ACTION=remove"
----

== Other related information:

=== Deploy Workload on OpenShift Cluster from an existing playbook:

[source,yaml]
----
- name: Deploy a workload role on a master host
  hosts: all
  become: true
  gather_facts: False
  tags:
    - step007
  roles:
    - { role: "{{ ocp_workload }}", when: 'ocp_workload is defined' }

----
NOTE: You might want to change `hosts: all` to fit your requirements

== Additional configuration
You can alter the defaults provided when running your ansible role by
providing the name of the variable via *ENV* variable (with -e).

The values that can be set (and the defaults) are:

----
ocp4_admin_project: ocp-workshop
ocp4_dso_user_count_start: 1
ocp4_dso_user_count: 50
ocp4_dso_user_format: user%d  # Possible value: user%02d
ocp4_dso_user_password: openshift

ocp4_dso_gogs_admin_user: gogsadmin
ocp4_dso_gogs_user: gogs
ocp4_dso_gogs_user_password: openshift

ocp4_dso_reponame_local: SecurityDemos
ocp4_dso_reponame: SecurityDemos
----

== Install the dependent roles
If you need to install the roles in this workload, read them from link:../../configs/ocp4_workload_dso/requirements.yml[../../configs/ocp4_workload_dso/requirements.yml]
and then use ansible galaxy.

An example would be:
----
ansible-galaxy install siamaksade.openshift_common_facts,ocp-3.9 --force
ansible-galaxy install siamaksade.openshift_sonatype_nexus,ocp-3.9 --force
ansible-galaxy install siamaksade.openshift_gogs,ocp-3.9 --force
ansible-galaxy install siamaksade.openshift_workshopper,ocp-3.9 --force
----

NOTE: Make sure to use --force if you have those roles with different version, and Make
sure to use the roles defined in that file (and the versions there).
