= Cluster Application Migration Workload

== Overview

The workload includes migration operator which deploys migration controller, migration ui and Velero.

== Supported Versions

This workload supports following versions of Cluster Application Migration Tool

- release-1.0

Older version are no longer supported

=== Deploy the workload
[source,'bash']
----
ansible-playbook -i "bastion.${GUID}.${BASE_DOMAIN}", ./ansible/configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=${ANSIBLE_USER_KEY_FILE}" \
    -e"ansible_user=${ANSIBLE_USER}" \
    -e"ocp_workload=ocp-workload-migration" \
    -e"silent=False" \
    -e"ACTION=create" \
    -e @./secret.yaml <1> \
    -e @./workload.yaml <2>
----
<1> This is the file you used when deploying your cluster with AgnosticD.
<2> All variables required by the workload go in this file.

=== Variables

This workload does not require any variables. Following variables can be overridden if you do not want default behaviour.

|===
| Variable | Default Value | Description

| mig_operator_repo
| https://github.com/fusor/mig-operator
| Repository for migration operator

| mig_operator_repo_branch
| master
| Branch in operator repo

| mig_operator_version
| latest
| Migration operator version 

| mig_ocp_version
| 4
| Version of OpenShift cluster
|===


=== Delete the workload

[source,'bash']
----
ansible-playbook -i "bastion.${GUID}.${BASE_DOMAIN}", ./ansible/configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=${ANSIBLE_USER_KEY_FILE}" \
    -e"ansible_user=${ANSIBLE_USER}" \
    -e"ocp_workload=ocp-workload-migration" \
    -e"silent=False" \
    -e"ACTION=delete" \
    -e @./secret.yaml \
    -e @./workload.yaml
----

