= ocp4_workload_image_registry - Configure OpenShift Image Registry

== Role overview

* This is a working no-op role that can be used to develop new OpenShift 4 workload roles. It consists of the following tasks files:
** Tasks: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an environment for the workload deployment
*** Debug task will print out: `pre_workload Tasks completed successfully.`

** Tasks: link:./tasks/workload.yml[workload.yml] - Used to deploy the actual workload
*** This role configures the `cluster` resource `configs.imageregistry.operator.openshift.io`
*** Debug task will print out: `workload Tasks completed successfully.`

** Tasks: link:./tasks/post_workload.yml[post_workload.yml] - Used to configure the workload after deployment
*** This role doesn't do anything here
*** Debug task will print out: `post_workload Tasks completed successfully.`

** Tasks: link:./tasks/remove_workload.yml[remove_workload.yml] - Used to delete the workload
*** This role doesn't do anything here
*** Debug task will print out: `remove_workload Tasks completed successfully.`

== The defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you need to define to control the deployment of your workload.
* A variable *silent=True* can be passed to suppress debug messages.
* You can modify any of these default values by adding `-e "variable_name=variable_value"` to the command line
* Your deployer will override any of these variables (usually CloudForms)

=== Variable Naming

You *must* use long-name scope parameters for your workload to avoid variable clashing.
Ansible lacks robust variable scoping.
For example, parameters named `ocp4_workload_image_registry_*` would be recognized as unique to this workload

== Deploy a Workload with the `ocp-workload` playbook [Mostly for testing]

. If your workload uses parameters create a `<role name>_vars.yaml` input file.
+
.ocp4_workload_image_registry_vars.yaml
[source,yaml]
----
# You can set any variable, not just the dictionary
silent: true
----

. Set up Environment Variables for the bastion you want to run this role on.
+
[source,yaml]
----
TARGET_HOST="bastion.dev.openshift.opentlc.com"
ANSIBLE_USER="ec2-user"
WORKLOAD="ocp4_workload_image_registry"
GUID=1001
----

. Finally run the workload passing the input files as parameters:
+
[source,sh]
----
# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=${ANSIBLE_USER}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"guid=${GUID}" \
    -e"ACTION=create" \
    -e @./ocp4_workload_image_registry_vars.yaml
----
