== Overview

== Supported Cloud Providers

No cloud providers have been configured because this env_type is not meant to deploy resources, only interact with already available resources.

== Review the Env_Type variable file

For further information on customizing images consult the link:../../../docs/Creating_a_config.adoc[Creating a Config Guide]

== Review the `sample_vars.yml` variable file

----

---
guid:               test-config-00
env_type:           roadshow-virt-binder
cloud_provider:     none
...

----

== Developing with `vmware-roadshow`

. Examine the defaults in `configs/vmware-roadshow/sample_vars.yml`

. Set the number of users you'd like.

. Make sure you use the binder to actually configure MTV.
The OpenShift cluster is not available from this config.

== Deploying the `vmware-roadshow`

You can deploy this config by running the following command from the `ansible`
directory.

`ansible-playbook main.yml -e @my_sample_vars.yaml -e @configs/vmware-roadshow/sample_vars.yml`

=== To Delete an environment

`ansible-playbook destroy.yml -e @configs/vmware-roadshow/sample_vars.yml`
