---
- name: Create virtual network and subnet
  ansible.builtin.include_tasks:
    file: ./login-to-cluster.yml

- name: Install ARO using az commands (with managed identities)
  ansible.builtin.include_tasks:
    file: ./aro-ai-search-federated.yml

- name: Save ansible vars to user_info data
  agnosticd_user_info:
    data:
      user_assigned_identity_object_id: "{{ identity_object_id }}"
      user_assigned_identity_client_id: "{{ identity_client_id }}"
