#!/bin/bash

virsh start centos


usermod -aG wheel rhel
echo redhat | passwd --stdin rhel

echo "${SSHKEY}" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa
ssh-keygen -f /root/.ssh/id_rsa -y > /root/.ssh/id_rsa.pub

# MAC Addresses
# vm1:          52:54:00:d6:0c:72
# centos:       52:54:00:68:79:84
# converted:    52:54:00:87:d3:fc
# rhel07:       52:54:00:02:ce:bb
# rhel08:       52:54:00:43:26:d3
# rhel09:       52:54:00:7f:e1:4e
# upgraded08:   52:54:00:22:37:93
# upgraded09:   52:54:00:e6:14:ee

# Get the IP of the VM belonging to cento based on arp.
while ! [ $( arp -an | grep 52:54:00:68:79:84 | awk '{print $2}' | tr -d '()' )  ]; do echo "Waiting for arp to return centos MAC address."; sleep 10; done;
echo "$( arp -an | grep 52:54:00:68:79:84 | awk '{print $2}' | tr -d '()' ) centos" >> /etc/hosts