---
galaxy_info:
  role_name: ocp4_workload_sandbox_ddns
  author: Red Hat, Alberto Gonzalez (josegonz@redhat.com)
  description: |
    Sandbox DNS
  license: MIT
  min_ansible_version: "2.9"
  platforms: []
  galaxy_tags:
  - ocp
  - openshift
dependencies: []
