:role: satellite-manage-lifecycle
:author: GPTE Team
:tag1: configure_satellite
:tag2: configure_satellite_lifecycle
:main_file: tasks/main.yml
:version_file: tasks/version_6.7.yml


Role: {role}
============

This role creates lifecycle environment path.

Requirements
------------

. Satellite must be install and setup.

Role Variables
--------------

|===
|satellite_version: "Digit" |Required |satellite version
|org: "String" |Required |Organization name
|org_label: "String" |Optional | Organization label in string without space
|org_description: "String" |Optional | Organization description
|lifecycle_environment_path: [List] |Required | Contains nested list with dictinary keys and values
|name: "String" |Required |Name of environment
|label: "String" |Required |label of environment
|descritpion: "String" |Required |Description for environment
|prior_env: "String" |Required |Name of the prior environment

|===

* Example variables

[source=text]
----
satellite_version: 6.7
org: "gpte"
org_label: "gpte"
org_description: "Global Partner Training and Enablement"
lifecycle_environment_path:
  - name: "Development"
    label: "dev"
    description: "Development Environment"
    prior_env: "Library"
  - name: "Staging"
    label: "qa"
    description: "Quality Environment"
    prior_env: "Development"
  - name: "Production"
    label: "prod"
    description: "Production Enviornment"
    prior_env: "Staging"
----

Tags
---

|===
|{tag1} |Consistent tag for all satellite config roles
|{tag2} | This tag is specific to this role only
|===

* Example tags

[source=text]
----
## Tagged jobs
ansible-playbook playbook.yml --tags configure_satellite,configure_satellite_lifecycle

## Skip tagged jobs
ansible-playbook playbook.yml --skip-tags configure_satellite_lifecycle

----


Example Playbook
----------------

How to use your role (for instance, with variables passed in playbook).

[source=text]
----
[user@desktop ~]$ cat sample_vars.yml
satellite_version: 6.7
org: "gpte"
org_label: "gpte"
org_description: "Global Partner Training and Enablement"
lifecycle_environment_path:
  - name: "Development"
    label: "dev"
    description: "Development Environment"
    prior_env: "Library"
  - name: "Staging"
    label: "qa"
    description: "Quality Environment"
    prior_env: "Development"
  - name: "Production"
    label: "prod"
    description: "Production Enviornment"
    prior_env: "Staging"

[user@desktop ~]$ cat playbook.yml
- hosts: satellite.example.com
  vars_files:
    - sample_vars.yml
  roles:
    - satellite-manage-organization

[user@desktop ~]$ ansible-playbook playbook.yml
----

Tips to update Role
------------------

To extend role works for other version, if needed create new file named  version_{{satellite_version}}.yml and import newly created file in main.yml

for reference look at link:{main_file[main.yml] and link:{version_file}[version_6.x.yml]


Author Information
------------------

{author}
