---
# Implement your Workload deployment tasks here

- name: Disable mirroring since we're running in a golden image
  ansible.builtin.lineinfile:
    path: /root/hub.yml
    regexp: '^disconnected_update: True'
    line: "disconnected_update: {{ disconnected_update }}"

- name: Configure golden image registry CA
  ansible.builtin.blockinfile:
    path: /root/hub.yml
    block: |
      ca: |
        -----BEGIN CERTIFICATE-----
        MIIFSzCCAzOgAwIBAgIUEz9Cc3eC77zRr/y6Eg7wPLzjYBswDQYJKoZIhvcNAQEL
        BQAwIjEgMB4GA1UEAwwXaW5mcmEuNWctZGVwbG95bWVudC5sYWIwIBcNMjIxMTIx
        MTcwMDIwWhgPMjA1MDA0MDcxNzAwMjBaMCIxIDAeBgNVBAMMF2luZnJhLjVnLWRl
        cGxveW1lbnQubGFiMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAm/dG
        FbJkusaOpMlDJ9GJ1+Z3Y2G0/RxVRuqZ5E7ufZk69vp9DaERclN/KwiTNMoRUvcZ
        gtIj2HAfaN8L7FfwN8qqMfeJg/fdh9X0sqNydMaZ/fSA60LxmUqmU4e7g01obTmH
        e6j2vjRprDDzfE1683VvgWkecroeG4mujHUUREHs9xfgoW7+nHDpKWZ1vLaZdFKy
        Zrzz1IBvPo+DxgL+3n8orb0aM3uQdufQ2uHZ2fYrxrKUzIVFv+CTT7ctEG/PjQxJ
        tjswizCG6Obk9+B3CMp/s6mT6W7P9xzpbW3aRZLMxSR3/lSAxpWTP/57G3ZyXoNJ
        Cp2UtZEyxRGG1M0f3epzvu4H8JYuXTs/+w6JRLJTN7BF+dThuDKCmbkzq7NzJ/Kq
        ln3qEvFVgMKLprkY7hzU/e/Egr6QA26c2nvwJ2vV5COJrqaPSq52NubseVGPnK2s
        kkKWdf4wPwE1/LrbcjxpcUwJysy+oOmowYhx8X8GUUBZk8ejupYkg/gGop2F9JWD
        sOwmWqRBqn7yKJF4GyJZ0h62xhEfQdBHKub6VLfh6GFNrNHvNpy+DFq3nWGKnV7j
        y5wxx2bR5exN/qZ8wyaFq5k9tVLFd1CMAzQkWkmT9EpI6y4Ux9tPGXgB6h6yjjnK
        gxbLH84ejwDaaiSc2NBVP+47b7Vhoiw4++hNBqcCAwEAAaN3MHUwHQYDVR0OBBYE
        FGQeCqTJ5HZJIXNKx2t7dY+fRYo1MB8GA1UdIwQYMBaAFGQeCqTJ5HZJIXNKx2t7
        dY+fRYo1MA8GA1UdEwEB/wQFMAMBAf8wIgYDVR0RBBswGYIXaW5mcmEuNWctZGVw
        bG95bWVudC5sYWIwDQYJKoZIhvcNAQELBQADggIBAEvsOv4uVMHUZrFQrwUYJRV7
        MC/FB0bgZZ1VhqpL+7+W98+HEYVZRuK9IKjGRfen9wOrLI6hc6zZYOwMDJgfuFwd
        X6qv/HZKp+TfZrFu1IhgDeTPkJX7t7ECD63BgOSNc8OgmGL34dP5qCB3qaSzuP9x
        mukIAZyvHwf2ZfWzrpvR9GLzTuh01GHqQyojC9ntWvlzgKec3nZNFt8tWRyMraAr
        C/a++HeOlZCeRtH9gSOy49H1B7/kfTwFw/Y/h0oVMpH6x8dewyuefe8Q5fvURO3T
        y4B/esUA9R/h971BGIoYk5pAZAJdkD8GAmegyj47vFg6mw095dwB1eNAD7ddqdQn
        RCqwrqYEV1TExI23mC0oiDck0RY8FWI+Q034MOnZFn6Dv6EYMF4IBjJIJICMqvSf
        MA/AXZ111P5/5j+qODTwJ/IDhiT46HMY/SN3MW96uZuJKchJchMNQG+MOuTJb6gd
        cVVyItPgufANPzlf4GpF0+OaOMRjg2BdeRJKluWhie1rSKT/DpvB9ZBWU6ng/MFa
        oW5xpMLuZIUF45kP2ZhQhbRA2zjIaZ8XPgaHPNr4INhSW5pqqLISZCJvkMJV07eT
        s+KzXHlydQpzajOOzwRgq+dIGl6y4GYM1Y0EElHY7S/LvJBNpcw8BDjWmZfpie0y
        /fp7Z8v3m9S2+TmGjDVC
        -----END CERTIFICATE-----

- name: Ensure manifests folder exists
  ansible.builtin.file:
    path: /root/manifests
    state: directory
    mode: '0755'

- name: Ensure NTP extra manifest exists
  ansible.builtin.blockinfile:
    path: /root/manifests/ntp.yaml
    create: true
    block: |
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      metadata:
        labels:
          machineconfiguration.openshift.io/role: master
        name: 99-master-chrony-configuration
      spec:
        config:
          ignition:
            config: {}
            security:
              tls: {}
            timeouts: {}
            version: 3.1.0
          networkd: {}
          passwd: {}
          storage:
            files:
            - contents:
                source: data:text/plain;charset=utf-8;base64,c2VydmVyIDAubm9ydGgtYW1lcmljYS5wb29sLm50cC5vcmcgaWJ1cnN0CmRyaWZ0ZmlsZSAvdmFyL2xpYi9jaHJvbnkvZHJpZnQKbWFrZXN0ZXAgMS4wIDMKcnRjc3luYwpsb2dkaXIgL3Zhci9sb2cvY2hyb255Cg==
              mode: 420
              overwrite: true
              path: /etc/chrony.conf
        osImageURL: ""

- name: Configure CatalogSource extra manifest for golden image env
  ansible.builtin.copy:
    dest: /root/manifests/disconnected-catalog-source.yaml
    content: |
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      metadata:
        name: cs-redhat-operator-index-v4-20-176943
        namespace: openshift-marketplace
        annotations:
          target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      spec:
        displayName: Red Hat Operators
        image: "{{ disconnected_catalog_image }}"
        publisher: Red Hat
        sourceType: grpc
        updateStrategy:
          registryPoll:
            interval: 1h
    owner: root
    group: root
    mode: '0644'
  when: not disconnected_update|bool

- name: Deploy hub cluster via kcli
  ansible.builtin.shell:
    cmd: kcli create cluster openshift --pf hub.yml -P force=true &> /root/kcli-hub-deploy.log
  args:
    chdir: /root/
  when: again is undefined

- name: Ensure kubernetes manifests are downloaded #execute while waiting for the hub to be deployed
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.destination }}"
    mode: "{{ item.mode }}"
    force: true
  # yamllint disable rule:line-length
  loop:
    - {url: "https://raw.githubusercontent.com/{{ repo_user }}/5g-core-deployments-on-ocp-lab/{{ lab_version }}/lab-materials/lab-env-data/hub-cluster/argocd-patch.json", destination: "/tmp/argocd-openshift-gitops-patch.json", mode: "0644"}
    - {url: "https://raw.githubusercontent.com/{{ repo_user }}/5g-core-deployments-on-ocp-lab/{{ lab_version }}/lab-materials/lab-env-data/hub-cluster/hub-operators-argoapps.yaml", destination: "/tmp/hub-operators-argoapps.yaml", mode: "0644"}
    - {url: "https://raw.githubusercontent.com/{{ repo_user }}/5g-core-deployments-on-ocp-lab/{{ lab_version }}/lab-materials/lab-env-data/hub-cluster/argocd-clusterrolebinding.yaml", destination: "/tmp/argocd-clusterrolebinding.yaml", mode: "0644"}
  # yamllint enable rule:line-length
  delay: 10
  retries: 5

- name: Ensure we can login into the hub cluster with the generated credentials
  ansible.builtin.shell:
    cmd: |
      oc login https://{{ lab_api_host }} \
        -u admin \
        -p {{ strong_admin_password }} \
        --insecure-skip-tls-verify=true \
        > /dev/null
  register: hub_login_result
  until: hub_login_result.rc == 0
  retries: 120
  delay: 60
  when: again is undefined
  failed_when: hub_login_result.rc != 0
  changed_when: hub_login_result.rc == 0

- name: Ensure we have the kubeconfig file for the hub cluster copied in the bastion
  ansible.builtin.copy:
    src: /root/.kcli/clusters/hub/auth/kubeconfig
    dest: "/home/{{ student_name }}/hub-kubeconfig"
    remote_src: true
    owner: "{{ student_name }}"

- name: Remove kubeadmin user
  kubernetes.core.k8s:
    kubeconfig: "/home/{{ student_name }}/hub-kubeconfig"
    state: absent
    api_version: v1
    kind: Secret
    namespace: kube-system
    name: kubeadmin

- name: Label nodes with cluster.ocs.openshift.io/openshift-storage
  kubernetes.core.k8s:
    kubeconfig: "/home/{{ student_name }}/hub-kubeconfig"
    state: present
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: "{{ item }}"
        labels:
          cluster.ocs.openshift.io/openshift-storage: ""
  loop:
    - hub-ctlplane-0.5g-deployment.lab
    - hub-ctlplane-1.5g-deployment.lab
    - hub-ctlplane-2.5g-deployment.lab

- name: Ensure ArgoCD instance is patched for ZTP support
  kubernetes.core.k8s:
    kubeconfig: "/home/{{ student_name }}/hub-kubeconfig"
    api_version: argoproj.io/v1alpha1
    kind: ArgoCD
    name: openshift-gitops
    namespace: openshift-gitops
    state: patched
    src: /tmp/argocd-openshift-gitops-patch.json
    merge_type: merge
  register: argocd_patch_result
  until: argocd_patch_result.failed != true
  retries: 10
  delay: 10
  failed_when: argocd_patch_result.failed
  changed_when: not argocd_patch_result.failed

- name: Apply ArgoCD ClusterRoleBinding manifest to the cluster
  kubernetes.core.k8s:
    kubeconfig: "/home/{{ student_name }}/hub-kubeconfig"
    state: present
    src: /tmp/argocd-clusterrolebinding.yaml
  register: result
  until: result.failed != true
  retries: 10
  delay: 10

- name: Wait until ArgoCD Pods are ready
  kubernetes.core.k8s_info:
    kubeconfig: "/home/{{ student_name }}/hub-kubeconfig"
    kind: Pod
    namespace: openshift-gitops
    label_selectors:
      - app.kubernetes.io/name = openshift-gitops-repo-server
  register: result
  until:
    - result.resources | length > 0
    - result.resources[0].status is defined
    - result.resources[0].status.phase is defined
    - result.resources[0].status.phase == "Running"
    - result.resources[0].status.containerStatuses is defined
    - result.resources[0].status.containerStatuses | length > 0
    - result.resources[0].status.containerStatuses[0].ready == true
  retries: 10
  delay: 10

- name: Apply HUB Cluster Operators APPs
  kubernetes.core.k8s:
    kubeconfig: "/home/{{ student_name }}/hub-kubeconfig"
    state: present
    src: /tmp/hub-operators-argoapps.yaml
  register: result
  until: result.failed != true
  retries: 10
  delay: 10

- name: Wait until StorageCluster is ready
  kubernetes.core.k8s_info:
    kubeconfig: "/home/{{ student_name }}/hub-kubeconfig"
    api_version: ocs.openshift.io/v1
    kind: StorageCluster
    name: ocs-storagecluster
    namespace: openshift-storage
  register: storagecluster
  retries: 15
  delay: 60
  until:
    - storagecluster is defined
    - storagecluster.resources | length > 0
    - storagecluster.resources[0].status is defined
    - storagecluster.resources[0].status.phase is defined
    - storagecluster.resources[0].status.phase == "Ready"

- name: Ensure Ceph RBD storageclass is set as default
  kubernetes.core.k8s:
    kubeconfig: "/home/{{ student_name }}/hub-kubeconfig"
    state: patched
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: ocs-storagecluster-ceph-rbd
    definition:
      metadata:
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
  register: result
  until: result.failed != true
  retries: 10
  delay: 30

- name: Wait until ArgoCD APP for HUB Cluster Operators deployment is ready
  kubernetes.core.k8s_info:
    kubeconfig: "/home/{{ student_name }}/hub-kubeconfig"
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: hub-operators-deployment
    namespace: openshift-gitops
  register: argocd_app_hub_operators
  retries: 100
  delay: 10
  until:
    - argocd_app_hub_operators is defined
    - argocd_app_hub_operators.resources | length > 0
    - argocd_app_hub_operators.resources[0].status is defined
    - argocd_app_hub_operators.resources[0].status.health is defined
    - argocd_app_hub_operators.resources[0].status.health.status is defined
    - argocd_app_hub_operators.resources[0].status.health.status == "Healthy"
    - argocd_app_hub_operators.resources[0].status.sync is defined
    - argocd_app_hub_operators.resources[0].status.sync.status is defined
    - argocd_app_hub_operators.resources[0].status.sync.status == "Synced"

- name: Wait until ArgoCD APP for HUB Cluster Operators config is ready
  kubernetes.core.k8s_info:
    kubeconfig: "/home/{{ student_name }}/hub-kubeconfig"
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: hub-operators-config
    namespace: openshift-gitops
  register: argocd_app_hub_operators
  retries: 100
  delay: 10
  until:
    - argocd_app_hub_operators is defined
    - argocd_app_hub_operators.resources | length > 0
    - argocd_app_hub_operators.resources[0].status is defined
    - argocd_app_hub_operators.resources[0].status.health is defined
    - argocd_app_hub_operators.resources[0].status.health.status is defined
    - argocd_app_hub_operators.resources[0].status.health.status == "Healthy"
    - argocd_app_hub_operators.resources[0].status.sync is defined
    - argocd_app_hub_operators.resources[0].status.sync.status is defined
    - argocd_app_hub_operators.resources[0].status.sync.status == "Synced"

- name: Wait until MultiClusterHub is ready
  kubernetes.core.k8s_info:
    kubeconfig: "/home/{{ student_name }}/hub-kubeconfig"
    api_version: operator.open-cluster-management.io/v1
    kind: MultiClusterHub
    name: multiclusterhub
    namespace: open-cluster-management
  register: rhacm_multiclusterhub
  retries: 100
  delay: 10
  until:
    - rhacm_multiclusterhub is defined
    - rhacm_multiclusterhub.resources | length > 0
    - rhacm_multiclusterhub.resources[0].status is defined
    - rhacm_multiclusterhub.resources[0].status.phase is defined
    - rhacm_multiclusterhub.resources[0].status.phase == "Running"

- name: Wait until MultiClusterEngine is ready
  kubernetes.core.k8s_info:
    kubeconfig: "/home/{{ student_name }}/hub-kubeconfig"
    api_version: multicluster.openshift.io/v1
    kind: MultiClusterEngine
    name: multiclusterengine
    namespace: multicluster-engine
  register: mce_multiclusterengine
  retries: 60
  delay: 10
  until:
    - mce_multiclusterengine is defined
    - mce_multiclusterengine.resources | length > 0
    - mce_multiclusterengine.resources[0].status is defined
    - mce_multiclusterengine.resources[0].status.phase is defined
    - mce_multiclusterengine.resources[0].status.phase == "Available"

- name: Wait until MultiClusterObservability is ready
  kubernetes.core.k8s_info:
    kubeconfig: "/home/{{ student_name }}/hub-kubeconfig"
    api_version: observability.open-cluster-management.io/v1beta2
    kind: MultiClusterObservability
    name: observability
    namespace: open-cluster-management-observability
  register: mco_multiclusterobservability
  retries: 60
  delay: 10
  until:
    - mco_multiclusterobservability is defined
    - mco_multiclusterobservability.resources | length > 0
    - mco_multiclusterobservability.resources[0].status is defined
    - mco_multiclusterobservability.resources[0].status.conditions|json_query('[?type==`Ready`].status')

- name: Get rook-ceph-tools pod
  kubernetes.core.k8s_info:
    kubeconfig: "/home/{{ student_name }}/hub-kubeconfig"
    api_version: v1
    kind: Pod
    namespace: openshift-storage
    label_selectors:
      - app=rook-ceph-tools
  register: rook_ceph_tools_pod

- name: Download create-external-cluster-resources.py script into rook-ceph-tools pod
  kubernetes.core.k8s_exec:
    kubeconfig: "/home/{{ student_name }}/hub-kubeconfig"
    namespace: openshift-storage
    pod: "{{ rook_ceph_tools_pod.resources[0].metadata.name }}"
    command: >-
      curl -Ls
      https://raw.githubusercontent.com/rook/rook/refs/heads/release-1.19/deploy/examples/create-external-cluster-resources.py
      -o /tmp/create-external-cluster-resources.py
  retries: 5
  delay: 10

- name: Run create-external-cluster-resources.py script
  kubernetes.core.k8s_exec:
    kubeconfig: "/home/{{ student_name }}/hub-kubeconfig"
    namespace: openshift-storage
    pod: "{{ rook_ceph_tools_pod.resources[0].metadata.name }}"
    command: >-
      python3 /tmp/create-external-cluster-resources.py
      --rbd-data-pool-name ocs-storagecluster-cephblockpool
  register: external_cluster_resources_output

- name: Save external Ceph config to file
  ansible.builtin.copy:
    content: "{{ external_cluster_resources_output.stdout }}"
    dest: "/home/{{ student_name }}/external-ceph-config.json"
    mode: "0644"
    owner: "{{ student_name }}"

- name: Ensure MNO ssh key is downloaded
  ansible.builtin.get_url:
    # yamllint disable rule:line-length
    url: "http://infra.5g-deployment.lab:3000/student/5g-core-deployments-on-ocp-lab/raw/branch/{{ lab_version }}/lab-materials/lab-env-data/hypervisor/ssh-key"
    # yamllint enable rule:line-length
    dest: "/home/{{ student_name }}/.ssh/mnokey"
    mode: "0400"
    owner: "{{ student_name }}"
  retries: 3
  delay: 5

- name: Workload tasks complete (Hub and ArgoCD ready; user deploys MNO)
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool
