---

- name: Set user info for showroom
  agnosticd_user_info:
    user: "{{ ocp4_workload_kafka_workshop_user_prefix }}{{ n }}"
    data:
      user_name: "{{ ocp4_workload_kafka_workshop_user_prefix }}{{ n }}"
      user_password: "{{ ocp4_workload_authentication_htpasswd_user_password }}"
      openshift_cluster_console: "https://{{ r_console_route.resources[0].spec.host }}"
      openshift_api_internal: "{{ ocp4_workload_kafka_workshop_openshift_api_internal }}"
      openshift_cluster_subdomain: "{{ r_openshift_subdomain }}"
      globex_web_url: "https://globex-web-globex-{{ ocp4_workload_kafka_workshop_user_prefix }}{{ n }}.{{ r_openshift_subdomain }}"
  loop: "{{ range(1, 1 + ocp4_workload_kafka_workshop_user_count | int) | list }}"
  loop_control:
    loop_var: n
    label: "{{ ocp4_workload_kafka_workshop_user_prefix }}{{ n }}"
