:role: satellite-libvirt
:author: Satellite Team
:tag1: satellite_provisioning
:tag2: satellite_provisioning_libvirt
:defaults_file: defaults/main.yml
:main_file: tasks/main.yml
:libvirt_tasks: tasks/libvirt.yml
:proxy_tasks: tasks/proxy_libvirt.yml
:network_template: templates/network/default.xml.j2
:pool_template: templates/pool/default.xml.j2

Role: {role}
============

This role installs libvirt and prepares it to be used for provisioning.
It can be installed eigther directly on satellite, or on the capsule.

Requirements
------------

. libvirt packages needs to be enabled


Role Variables
--------------

* Following are the variable to customize this role

[cols="2a,1,3a"]
|===
|satellite_libvirt_provisioning: "Bool" |Optional(*false*) | Whether configure libvirt provisioning
|satellite_libvirt_network: {Dictionary}
!===
!domain: "String"
!network: "String"
!gateway: "String"
!netmask: "String"
!range_from: "String"
!range_to: "String"
!===
|Optional
|Libvrit default network setting
!===
!What domain should the subnet belong to
!Network address
!Gateway address - this is the hosting system address in this nat network
!Network mask - full format
!First IP to be included in the subnet used for provisioning
!Last IP to be included in the subnet used for provisioning
!===
|===

* Exammple variables

[source=text]
----
satellite_libvirt_provisioning: yes
satellite_libvirt_network:
  domain: example.org
  network: '192.168.122.0'
  gateway: '192.168.122.1'
  netmask: '255.255.255.0'
  range_from: '192.168.122.2'
  range_to: '192.168.122.254'
----

Tags
---

|===
|{tag1} |Consistent tag for all satellite config roles
|{tag2} |This tag is specific to this role only
|{tag3} |This tag is specific to this role and libvirt provisioning
|===


Example Playbook
----------------

How to use your role (for instance, with variables passed in playbook).

[source=text]
----
[user@desktop ~]$ cat sample_vars.yml
satellite_version: 6.7
satellite_admin: admin
satellite_admin_password: 'changeme'
satellite_libvirt_provisioning: yes
satellite_libvirt_network:
  domain: example.org
  network: '192.168.122.0'
  gateway: '192.168.122.1'
  netmask: '255.255.255.0'
  range_from: '192.168.122.2'
  range_to: '192.168.122.254'

[user@desktop ~]$ cat playbook.yml
- hosts: satellites
  vars_files:
    - sample_vars.yml
  roles:
    - satellite-provisioning

[user@desktop ~]$ ansible-playbook playbook.yml
----

Tips to update Role
------------------

The libvirt installation tasks are at link:{libvirt_tasks}[libvirt.yml],
for resource definition look at network definition link:{network_template}[network/default.xml.j2]
and storage pool link:{pool_template}[pool/default.xml.j2]
The enablement of libvirt in the capsule tasks are in link:{proxy_tasks}[proxy_libvirt.yml]

for reference look at link:{main_file}[main.yml] for the variable reference at link:{defaults}[defaults/main.yml].

Author Information
------------------

{author}
