= ocp4-workload-homeroomlab-dev-tools

== Role overview

* This is a simple role that does the following:
** Tasks: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an
 environment for the workload deployment
*** Copies ~/.kube/config to a temp directory and sets the KUBECONFIG env variable.
*** Debug task will print out: `pre_workload Tasks Complete`

** Tasks: link:./tasks/workload.yml[workload.yml] - Used to deploy the 
 lab environment.
*** Creates a new project and a deployment for the learning portal.
*** Debug task will print out: `workload Tasks Complete`

** Tasks: link:./tasks/post_workload.yml[post_workload.yml] - Used to
 configure the workload after deployment
*** Removes the temp .kube/config file.
*** Debug task will print out: `post_workload Tasks Complete`

** Tasks: link:./tasks/pre_remove_workload.yml[pre_remove_workload.yml] - Sets up an
 environment for the workload removal
*** Copies ~/.kube/config to a temp directory and sets the KUBECONFIG env variable.
*** Debug task will print out: `pre_workload Removal Tasks Complete`

** Tasks: link:./tasks/remove_workload.yml[remove_workload.yml] - Used to clean up the environment and delete all resources.
*** Deletes resources and projects that were created.
*** Debug task will print out: `workload Removal Tasks Complete`

** Tasks: link:./tasks/post_remove_workload.yml[post_remove_workload.yml] - Used to
 configure the workload after deployment
*** Removes the temp .kube/config file.
*** Debug task will print out: `post_workload Removal Tasks Complete`

== Review the defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you
 need to define to control the deployment of your workload.

* You can modify any of these default values by adding
`-e"variable_name=variable_value"` to the command line

=== Deploy Workload on OpenShift Cluster from an existing playbook:

[source,yaml]
----
- name: Deploy a workload role on a master host
  hosts: all
  become: true
  gather_facts: False
  tags:
    - step007
  roles:
    - { role: "{{ocp_workload}}", when: 'ocp_workload is defined' }

----
NOTE: You might want to change `hosts: all` to fit your requirements

=== Common configuration to run these playbooks
You should have these environment variables defined/exported in your system in order
to run these playbooks.

----
OCP_USERNAME="opentlc-mgr"
GUID=sampleuser
# WORKLOAD SPECIFICS
WORKSHOP_PROJECT="labs"
WORKLOAD="ocp4-workload-homeroomlab-dev-tools"
----

=== Deploy a Workload with the `ocp-workload` playbook [Mostly for testing]
----
ansible-playbook -c local -i ${TARGET_HOST}, configs/ocp-workloads/ocp-workload.yml \
      -e ansible_python_interpreter=/opt/app-root/bin/python \
      -e ocp_workload=${WORKLOAD} \
      -e guid=${GUID} \
      -e project_name=${WORKSHOP_PROJECT} \
      -e ocp_username=${OCP_USERNAME} \
      -e ACTION="create"
----

=== To Delete an environment
----
ansible-playbook -c local -i ${TARGET_HOST}, configs/ocp-workloads/ocp-workload.yml \
      -e ansible_python_interpreter=/opt/app-root/bin/python \
      -e ocp_workload=${WORKLOAD} \
      -e guid=${GUID} \
      -e project_name=${WORKSHOP_PROJECT} \
      -e ocp_username=${OCP_USERNAME} \
      -e"ACTION=remove"
----

=== Additional information

== Additional configuration
You can alter the defaults provided when running your ansible role by
providing the name of the variable via *ENV* variable (with -e).

The values that can be set (and the defaults) are:

----
become_override: false # set to true if your SSH_USER is something other than opentlc-mgr, e.g. ec2-user 
ocp_username: opentlc-mgr

project_name: workshop
----
