= Setup

. Create a namespace for the pipeline
+
[source,sh]
----
oc create namespace ama-pipeline
----

. Create namespace `retail` if it doesn't exist.
+
[source,sh]
----
oc create namespace retail
----

. Create a secret to be used to access Gitea
+
[source,sh]
----
cat << EOF >gitea-secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-secret
  annotations:
    tekton.dev/git-0: https://gitea.apps.cluster-wkama.wkama.example.opentlc.com/lab-user/appmod-enablement
type: kubernetes.io/basic-auth
stringData:
  username: lab-user
  password: openshift
EOF
----

. Create the secret:
+
[source,sh]
----
oc apply -n ama-pipeline -f gitea-secret.yaml
----

. Link to the `pipeline` service account
+
[source,sh]
----
oc secrets link pipeline gitea-secret -n ama-pipeline
----

. Grant the pipeline service account permission to manipulate the retail namespace
+
[source,sh]
----
oc create rolebinding retail-pipeline --clusterrole=edit --serviceaccount=ama-pipeline:pipeline --namespace=retail 
----

. Allow applications to access the Kubernetes API
+
[source,sh]
----
oc create rolebinding default-view --clusterrole=view --serviceaccount=retail:default --namespace=retail
----

. Deploy the Tekton Pipeline Resources:
+
[source,sh]
----
oc apply -f https://gitea.apps.cluster-wkama.wkama.example.opentlc.com/lab-user/appmod-enablement/customers-tomcat-gitops/tekton
----

. Start the pipeline
+
[source,sh]
----
tkn pipeline start customers-deployment-pipeline \
  --use-param-defaults \
  --param git-url=https://gitea.apps.cluster-wkama.wkama.example.opentlc.com/lab-user/appmod-enablement \
  --param app-subdir=customers-tomcat-gitops \
  --param target-namespace=retail \
  --workspace name=ws,claimName=customers-pvc \
  --showlog \
  -n ama-pipeline
----

== ArgoCD

. Create a new ArgoCD instance in the `retail` namespace:

+
[source,sh]
----
cat << EOF >$HOME/demo/argocd.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: retail
spec:
  dex:
    openShiftOAuth: true
  server:
    insecure: true
    route:
      enabled: true
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
EOF

oc apply -f $HOME/demo/argocd.yaml
----


== Customers

. Update ArgoCD Application
+
[source,sh]
----
vim ~/appmod-enablement/argocd/customers-application.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customers-tomcat-gitops
  namespace: retail
spec:
  project: default
  source:
    repoURL: https://gitea.apps.cluster-wkama.wkama.example.opentlc.com/lab-user/appmod-enablement
    targetRevision: main
    path: customers-tomcat-gitops/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: retail
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
----

. Update Helm Chart persistence.properties in https://gitea.apps.cluster-wkama.wkama.example.opentlc.com/lab-user/appmod-enablement/customers-tomcat-gitops/helm/secret/persistence.properties
.. Update Oracle DB Service Name
.. Update Oracle DB User and Password if appropriate

. Create application
+
[source,sh]
----
oc apply -f ~/appmod-enablement/argocd/customers-application.yaml -n retail
----

. Log into Argo to follow along
+
[source,sh]
----
https:/argocd-server-retail.apps.cluster-wkama.wkama.example.opentlc.com
----

. Create a route for the customer service (AutoPrune needs to be turned off - otherwise the route gets deleted immediately)
+
[source,sh]
----
oc expose svc customers
----

. Test that the service is working:
+
[source,sh]
----
curl customers-retail.apps.cluster-wkama.wkama.example.opentlc.com/customers-tomcat-0.0.1-SNAPSHOT/customers/1
----
+
.Sample Output
[source,texinfo]
----
{"id":1,"username":"phlegm_master_19","name":"Guybrush","surname":"Threepwood","address":"1060 West Addison","zipCode":"ME-001","city":"Melee Town","country":"Melee Island"}
----

. Delete the route
+
[source,sh]
----
oc delete route customers
----

== Orders Service

. Create a PostgreSQL database
+
[source,sh]
----
oc new-app postgresql-persistent \
  --param DATABASE_SERVICE_NAME=postgresql-orders \
  --param POSTGRESQL_DATABASE=orders \
  --param POSTGRESQL_USER=orders \
  --param POSTGRESQL_PASSWORD=orders \
  -n retail
----

. Use ArgoCD to deploy the orders service:
+
[source,sh]
----
oc apply -f ~/appmod-enablement/argocd/orders-application.yaml -n retail
----

. Create a route for the orders service (AutoPrune needs to be turned off - otherwise the route gets deleted immediately)
+
[source,sh]
----
oc expose svc orders
----

. Test that it's working:
+
[source,sh]
----
curl orders-retail.apps.cluster-wkama.wkama.example.opentlc.com/orders/1
----
+
.Sample Output
[source,texinfo]
----
{"id":1,"customerUID":1,"date":"30-05-2018","items":[{"id":1,"productUID":4,"quantity":1,"price":30.00},{"id":2,"productUID":3,"quantity":1,"price":50.00},{"id":3,"productUID":5,"quantity":1,"price":200.00},{"id":4,"productUID":1,"quantity":4,"price":5.00},{"id":5,"productUID":2,"quantity":1,"price":60.00},{"id":6,"productUID":6,"quantity":1,"price":20.00}]}
----

. Delete the route
+
[source,sh]
----
oc delete route orders
----

== Inventory Service

. Create a PostgreSQL database
+
[source,sh]
----
oc new-app postgresql-persistent \
  --param DATABASE_SERVICE_NAME=postgresql-inventory \
  --param POSTGRESQL_DATABASE=inventory \
  --param POSTGRESQL_USER=inventory \
  --param POSTGRESQL_PASSWORD=inventory \
  -n retail
----

. Use ArgoCD to deploy the inventory service:
+
[source,sh]
----
oc apply -f ~/appmod-enablement/argocd/inventory-application.yaml -n retail
----

. Create a route for the inventory service (AutoPrune needs to be turned off - otherwise the route gets deleted immediately)
+
[source,sh]
----
oc expose svc inventory
----

. Test that it's working:
+
[source,sh]
----
curl inventory-retail.apps.cluster-wkama.wkama.example.opentlc.com/inventory/1
----
+
.Sample Output
[source,texinfo]
----
{"id":1,"customerUID":1,"date":"30-05-2018","items":[{"id":1,"productUID":4,"quantity":1,"price":30.00},{"id":2,"productUID":3,"quantity":1,"price":50.00},{"id":3,"productUID":5,"quantity":1,"price":200.00},{"id":4,"productUID":1,"quantity":4,"price":5.00},{"id":5,"productUID":2,"quantity":1,"price":60.00},{"id":6,"productUID":6,"quantity":1,"price":20.00}]}
----

. Delete the route
+
[source,sh]
----
oc delete route inventory
----

== Gateway Service

. Use ArgoCD to deploy the gateway service:
+
[source,sh]
----
oc apply -f ~/appmod-enablement/argocd/gateway-application.yaml -n retail
----

. Create a route for the gateway service (AutoPrune needs to be turned off - otherwise the route gets deleted immediately)
+
[source,sh]
----
oc expose svc gateway
----

. Test that it's working:
+
[source,sh]
----
curl gateway-retail.apps.cluster-wkama.wkama.example.opentlc.com/gateway/1
----
+
.Sample Output
[source,texinfo]
----
{"id":1,"customerUID":1,"date":"30-05-2018","items":[{"id":1,"productUID":4,"quantity":1,"price":30.00},{"id":2,"productUID":3,"quantity":1,"price":50.00},{"id":3,"productUID":5,"quantity":1,"price":200.00},{"id":4,"productUID":1,"quantity":4,"price":5.00},{"id":5,"productUID":2,"quantity":1,"price":60.00},{"id":6,"productUID":6,"quantity":1,"price":20.00}]}
----

. Delete the route
+
[source,sh]
----
oc delete route gateway
----

== Frontend Service

. Use ArgoCD to deploy the frontend service:
+
[source,sh]
----
oc apply -f ~/appmod-enablement/argocd/frontend-application.yaml -n retail
----

. Create a route for the frontend service (AutoPrune needs to be turned off - otherwise the route gets deleted immediately)
+
[source,sh]
----
oc expose svc frontend
----

. Open Web browser and navigate to `http://ordersfrontend-retail.apps.cluster-wkama.wkama.example.opentlc.com` (http, not https)
