= ansible-automation-platform config

Author: Ivan Aragonés <iaragone@redhat.com>
Owner: Ivan Aragonés <iaragone@redhat.com>
Alternative Contacts: Silvio Perez <sperezto@redhat.com>, Adonis García <agarciac@redhat.com>

== Overview

This config is meant to deploy one old instance of AWX and one new instance of AAP 2.4, and let test the migration process from the old to the new one using Configuration as Code.

== Running Ansible Playbook

From the `agnosticd/ansible` directory run:

[source,bash]
----
export GUID=<GUID>; \
export AWS_ACCESS_KEY_ID=<ACCESS_KEY>; \
export AWS_SECRET_ACCESS_KEY=<SECRET_KEY>; \
time ansible-playbook main.yml \
      -e@configs/controller-migration-casc/env_vars.yml \
      -e@~/secret.yml \
      -e "{aws_access_key_id: ${AWS_ACCESS_KEY_ID}, aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}, dump_vars: true}" \
      --vault-password-file ~/.vault_password
----

TIP: Presumably the playbook can be run using `ansible-navigator` and EE `quay.io/agnosticd/ee-multicloud:v0.1.1` (version `>=v0.1.1`).

TIP: you can repeat certain steps of the deployment by using tags, just make
     sure that the tags `must` and `create_inventory` are included, e.g.
     to only validate the Tower installation after it has been setup:
     `ansible-playbook main.yml --tags must,create_inventory,tower_validate -e ...`.

=== To Delete an environment

From the `agnosticd/ansible` directory run:

[source,bash]
----
export GUID=<GUID>; \
export AWS_ACCESS_KEY_ID=<ACCESS_KEY>; \
export AWS_SECRET_ACCESS_KEY=<SECRET_KEY>; \
time ansible-playbook destroy.yml \
      -e@configs/controller-migration-casc/env_vars.yml \
      -e@~/secret.yml \
      -e "{aws_access_key_id: ${AWS_ACCESS_KEY_ID}, aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}}"
----

CAUTION: it is recommended to destroy the environment if the deployment fails during the infrastructure deployment, as it might not properly recover.
A failure during the software deployment can generally be recovered without destroy.
