---
- name: Step 000 Pre Infrastructure
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tags:
  - step000
  - pre_infrastructure
  tasks:
  - ansible.builtin.debug:
      msg: "Step 000 Pre Infrastructure"
