= ocp4_workload_cert_manager_operator

== Role overview

Deploys Red Hat OpenShift Cert Master Operator


Created by: Tony Kay, tok@redhat.com
Date: 2022-05-04

== Review the defaults variable file

* This file link:./defaults/main.yml[./defaults/main.yml] contains all the variables you need to define to control the deployment of your workload.
* A variable *silent=True* can be passed to suppress debug messages.
* You can modify any of these default values by adding `-e "variable_name=variable_value"` to the command line

[source,yaml]
----
---
become_override: false
silent: false

ocp4_workload_cert_manager_operator_channel_dir: /tmp/{{ guid }}
ocp4_workload_cert_manager_operator_channel_tmp_kubeconfig: >-
  {{ ocp4_workload_cert_manager_operator_channel_dir }}/.kube/config

# channel tech-preview at original workload creation 2023-05-04 tok@redhat.com

ocp4_workload_cert_manager_operator_channel: tech-preview
----

=== Deploy a Workload 

. Authenticate to the cluster e.g. `oc login ...`
. Run a playbook calling the `ocp4_workload_cert_manager_operator` role

.Sample Playbook
[source,yaml]
----
---

- name: Test ocp4_workload_cert_manager_operator role
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    ACTION: create

  roles:

    - ocp4_workload_cert_manager_operator

=== To Delete an environment

Simply call the above playbook with `ACTION: remove`
