---
# handlers file for infra-ibm-classic-bm-pxe-server role

- name: restart dhcpd
  ansible.builtin.systemd:
    name: dhcpd
    state: restarted
  become: true

- name: restart httpd
  ansible.builtin.systemd:
    name: httpd
    state: restarted
  become: true

- name: restart tftp
  ansible.builtin.systemd:
    name: tftp
    state: restarted
  become: true

- name: restart haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
  become: true 