=== Overview

ansible-infoblox deploys an Infbolox vNIOS instance along with Ansible Tower and VSCode. This can be used to demonstrate IP Administration (IPAM) automation with Infoblox NIOS and Ansible.  It can also be used as a base config for demonstrating NIOS IPAM with other workflows.

=== Deploying the config

Before deployment, you will need to update the sample_infoblox_lab.yml and secrets.yaml files, . You will have to provide credentials and adjust settings to your own environment. It is not advised to change `nios_temp_license` unless you have a specific need.

===== Variables

.important sample_vars/sample_infoblox_lab.yml variables

[options="header,footer"]
|=======================
|Variable | Value | Definition
|email    | gejames@redhat.com | replace with your email address
|key_name | gejames-key | replace with a unique key name
|guid     | nioslab     | a short unique identifier
|nios_temp_license  |nios IB-V825 dns dhcp enterprise     |NIOS license types
|pip_packages       |infoblox-client psutil ansible |python packages to install in the venv
|=======================

===== Secrets

.The following should be in your secrets.yaml file

[source,yaml]
----
set_repositories_satellite_url: "{{ satellite_url }}"
set_repositories_satellite_org: "{{ satellite_org }}"
set_repositories_satellite_activationkey: "{{ satellite_activationkey }}"

# Manifest for Tower 3.8
satellite_manifest:
  username: "{{ sat_username }}"
  password: "{{ sat_password }}"
  url: "{{ sat_url }}"   # url to the Tower manifest zip file
  filename: "{{ manifest_filename }}"
----

===== Deploy

You can deploy this config by running the following command from the `ansible` directory.

[source,bash]
$ ansible-playbook main.yml -e @configs/ansible-infoblox/sample_vars/sample_infoblox_lab.yml -e @<YOUR_SECRET_VARS.yml>

===== Delete

[source,bash]
$ ansible-playbook destroy.yml -e @configs/ansible-multitier-infra/sample_vars_ec2.yml -e @<YOUR_SECRET_VARS.yml>


=== Working with the config

===== Requirements

* When writing plabyooks, use the `infoblox.nios_module` collection
* You will need to pass `ansible_python_interpreter: /usr/bin/python3` to your playbook. 


===== Virtualenv

A virtualenv is created in `/var/lib/awx/venv/nios` on the Tower and Bastion instances during lab deployment.  This will have the `infoblox-client` and `ansible` python packages installed.  When adding Job Templates in Tower, us this virtualenv for your `ANSIBLE ENVIRONMENT` or the job will fail. If you need additional python packages installed in this venv, add them to `pip_packages` in your vars file.

To access access the venv from the bastion: `$ source /var/lib/awx/venv/nios/bin/activate`

===== Variables

The following variables can be used in your playbooks to connect to the NIOS instance. They will be added to Tower during deployment for reference.

[options="header,footer"]
|=======================
|Variable           |Definition   | Tower Assest
|nios_grid_ip       |private IP of the NIOS Grid server  | nios inventory
|nios_grid_url      |public url used for API calls | nios inventory
|ansible_python_interpreter |/usr/bin/python3 | nios inventory
|wapi_version       | defaults to 2.11.1  | nios inventory
|nios_grid_admin    |defaults to admin | nios credential
|nios_grid_password |lab generated password  | nios credential

|=======================



===== Sample playbook

[source,yaml]
---
- name: get next available network from nios
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - infoblox.nios_modules
  vars:
    wapi_version: 2.11.1
    parent_container: 10.0.0.0/8
    cidr: 24
    nios_provider:
      host: "{{ nios_grid_url }}"
      username: "{{ nios_grid_username }}"
      password: "{{ nios_grid_password }}"
      wapi_version: "{{ wapi_version }}"
  tasks:
    - name: RETURN NEXT AVAILABLE NETWORK
      set_fact:
        networkaddr: "{{ lookup('nios_next_network', parent_container, cidr=cidr, provider=nios_provider) }}"

=== Change log

1.0 Initial release

==== Software Versions

[options="header,footer"]
|=======================
| Software | Version
| NIOS     | 8.5.1
| Tower    | 3.8
| RHEL     | 7.8
| ansible  | 2.9
| infoblox.nios_modules | 1.0.2
| awx.awx  | 17.1.0
| infoblox-cli | 0.5.0
|=======================
