=== Overview

ansible-infoblox deploys an Infbolox NIOS instance along with Ansible Tower, VSCode, and a bastion. This can be used to demonstrate IP Administration (IPAM) with NIOS and Ansible.  It can also be used a base config for demonstrating NIOS IPAM with other workflows.

=== Requirements

Your localhost should have the latest infoblox.nios_modules collection and the tower-cli pytyhon module installed.  The playbook will install them for you if they are not present.

.To install manually
[source,bash]
$ ansible-galaxy collection install infoblox.nios_modules
$ sudo pip install infoblox-cli



=== Review the sample_vars/sample_infoblox_lab.yml variable file

.The most important variables to change
[options="header,footer"]
|=======================
| Variable | Value | Definition
| email    | gejames@redhat.com | Replace with your email address
| key_name | gejames-key | Replace with a unique key name
| guid     | nioslab     | A short unique identifier
|=======================


.Variable definitions.
[options="header,footer"]
|=======================
|Variable           |Value                                |Definition 
|nios_temp_license  |nios IB-V825 dns dhcp enterprise     |NIOS license types
|pip_executable     |/usr/bin/pip3     |Path to your local pip binary
|repo_method        |satellite         |satellite is used for repos
|env_type           |ansible-infoblox  |name of the config
|=======================


=== Secrets file

.The following should be in your secrets.yaml file

[source,yaml]
set_repositories_satellite_url: "{{ satellite_url }}"
set_repositories_satellite_org: "{{ satellite_org }}"
set_repositories_satellite_activationkey: "{{ satellite_activationkey }}"

.Manifest for Tower 3.8

[source,yaml]
satellite_manifest:
  username: "{{ sat_username }}"
  password: "{{ sat_password }}"
  url: "{{ sat_url }}"   # url to the Tower manifest zip file
  filename: "{{ manifest_filename }}"
  
=== Deploying ansible-infoblox

You can deploy this config by running the following command from the `ansible`
directory. You will have to provide credentials and adjust settings to your own
environment.

[source,bash]
$ ansible-playbook main.yml -e @configs/ansible-infoblox/sample_vars/sample_infoblox_lab.yml -e @<YOUR_SECRET_VARS.yml>

=== To Delete an environment

[source,bash]
$ ansible-playbook destroy.yml -e @configs/ansible-multitier-infra/sample_vars_ec2.yml -e @<YOUR_SECRET_VARS.yml>






