=== Overview

ansible-infoblox deploys an Infbolox vNIOS instance along with Ansible Tower and VSCode. This can be used to demonstrate IP Administration (IPAM) with Infoblox NIOS and Ansible.  It can also be used as a base config for demonstrating NIOS IPAM with other workflows.

=== Requirements

When writing plabyooks, use the infoblox.nios_modules collection


   collections:
    - infoblox.nios_modules


.Virtualenv

A virtualenv is created in `/var/lib/awx/venv/nios` on the Tower and Bastion during lab deployment.  This will have the `infoblox-client` and `ansible` python packages installed.  When adding Job Templates in Tower, us this virtualenv for your `ANSIBLE ENVIRONMENT` or the job will fail. If you need additional python packages installed in this venv, add them to `pip_packages` in your vars file.

To access access the venv from the bastion: `$ source /var/lib/awx/venv/nios/bin/activate`

=== Variables

.sample variables
[options="header,footer"]
|=======================
|Variable | Value | Definition
|email    | gejames@redhat.com | replace with your email address
|key_name | gejames-key | replace with a unique key name
|guid     | nioslab     | a short unique identifier
|nios_temp_license  |nios IB-V825 dns dhcp enterprise     |NIOS license types
|pip_packages       |infoblox-client psutil ansible |python packages to install in the venv
|repo_method        |satellite         |satellite is used for repos
|env_type           |ansible-infoblox  |name of the config
|=======================

.NIOS variables available in Tower
The following variables can be used in your playbooks to connect to the NIOS instance.
[options="header,footer"]
|=======================
|Variable           |Definition   | Tower Assest
|nios_grid_ip       |private IP of the NIOS Grid server  | nios inventory
|nios_grid_url      |public url used for API calls | nios inventory
|nios_grid_admin    |defaults to admin | nios credential
|nios_grid_password |lab generated password  | nios credential
|wapi_version       | defaults to 2.11.1  | nios_inventory
|=======================

=== Sample playbook

[source,yaml]
---
- name: return next available network 
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - infoblox.nios_modules
  vars:
    wapi_version: 2.11.1
    parent_container: 10.0.0.0/8
    cidr: 24
    nios_provider:
      host: "{{ nios_grid_url }}"
      username: "{{ nios_grid_username }}"
      password: "{{ nios_grid_password }}"
      wapi_version: "{{ wapi_version }}"
  tasks:
    - name: RETURN NEXT AVAILABLE NETWORK
      set_fact:
        networkaddr: "{{ lookup('nios_next_network', parent_container, cidr=cidr, provider=nios_provider) }}"


=== Secrets file

.The following should be in your secrets.yaml file

[source,yaml]
set_repositories_satellite_url: "{{ satellite_url }}"
set_repositories_satellite_org: "{{ satellite_org }}"
set_repositories_satellite_activationkey: "{{ satellite_activationkey }}"

.Manifest for Tower 3.8

[source,yaml]
satellite_manifest:
  username: "{{ sat_username }}"
  password: "{{ sat_password }}"
  url: "{{ sat_url }}"   # url to the Tower manifest zip file
  filename: "{{ manifest_filename }}"

=== Deploying ansible-infoblox

You can deploy this config by running the following command from the `ansible`
directory. You will have to provide credentials and adjust settings to your own
environment.

[source,bash]
$ ansible-playbook main.yml -e @configs/ansible-infoblox/sample_vars/sample_infoblox_lab.yml -e @<YOUR_SECRET_VARS.yml>

=== To Delete an environment

[source,bash]
$ ansible-playbook destroy.yml -e @configs/ansible-multitier-infra/sample_vars_ec2.yml -e @<YOUR_SECRET_VARS.yml>

=== Software Versions

[options="header,footer"]
|=======================
| Software | Version
| NIOS     | 8.5.1
| ansible  | 2.9
| infoblox.nios_modules | 1.0.2
| awx.awx  | 17.1.0
| infoblox-cli | 0.5.0
| Tower    | 3.8
| RHEL     | 7.8
|=======================


=== Change log

1.0 

