=== Overview

ansible-infoblox deploys an Infbolox NIOS instance along with Ansible Tower, VSCode, and a bastion. This can be used to demonstrate IP Administration (IPAM) with NIOS and Ansible.  It can also be used as a base config for demonstrating NIOS IPAM with other workflows.

=== Requirements




.Virtualenv

To ensure future stability, a virtualenv in /var/lib/awx/venv/nios will be created during lab deployment.  This venv will have the infoblox-client and Ansible python packages installed.  When adding Job Templates in Tower, us this virtualenv for your ANSIBLE ENVIRONMENT or the jobs will fail.

If you need additional python packages instlled in this venv, add them to the pip_packages variable in your vars file.


=== Review the sample_vars/sample_infoblox_lab.yml variable file

.The most important variables to change
[options="header,footer"]
|=======================
| Variable | Value | Definition
| email    | gejames@redhat.com | Replace with your email address
| key_name | gejames-key | Replace with a unique key name
| guid     | nioslab     | A short unique identifier
|=======================


.Variable definitions.
[options="header,footer"]
|=======================
|Variable           |Value                                |Definition
|nios_temp_license  |nios IB-V825 dns dhcp enterprise     |NIOS license types
|pip_packages       |infoblox-client psutil ansible |list of python packages to install in the venv
|repo_method        |satellite         |satellite is used for repos
|env_type           |ansible-infoblox  |name of the config
|=======================


=== Secrets file

.The following should be in your secrets.yaml file

[source,yaml]
set_repositories_satellite_url: "{{ satellite_url }}"
set_repositories_satellite_org: "{{ satellite_org }}"
set_repositories_satellite_activationkey: "{{ satellite_activationkey }}"

.Manifest for Tower 3.8

[source,yaml]
satellite_manifest:
  username: "{{ sat_username }}"
  password: "{{ sat_password }}"
  url: "{{ sat_url }}"   # url to the Tower manifest zip file
  filename: "{{ manifest_filename }}"

=== Deploying ansible-infoblox

You can deploy this config by running the following command from the `ansible`
directory. You will have to provide credentials and adjust settings to your own
environment.

[source,bash]
$ ansible-playbook main.yml -e @configs/ansible-infoblox/sample_vars/sample_infoblox_lab.yml -e @<YOUR_SECRET_VARS.yml>

=== To Delete an environment

[source,bash]
$ ansible-playbook destroy.yml -e @configs/ansible-multitier-infra/sample_vars_ec2.yml -e @<YOUR_SECRET_VARS.yml>

=== Software Versions

[options="header,footer"]
|=======================
| Software | Version
| NIOS     | 8.5.1
| ansible  | 2.9.4
| infoblox.nios_modules | 1.0.2
| awx.awx  | 17.0.0
| infoblox-cli | 0.5.0
| Tower    | 3.8.1-1
| RHEL     | 7.8





