== Overview

*ansible-infoblox deploys an Infbolox NIOS instance along with Ansible Tower and a bastion

== Requirements

Your localhost host should have the latest infoblox.nios_modules collection and the tower-cli pytyhon module installed.  The playbook will install them for you if they are not present.

`$ ansible-galaxy collection install infoblox.nios_modules`

`$ sudo pip install infoblox-cli`



== Review the sample_vars/sample_infoblox_lab.yml variable file

The sample_infoblox_lab.yml file contains all the variables you need to define to control the deployment of your environment.

The most important variables to change: 
* email: gejames@redhat.com 
* key_name: gejames-key
* guid: nioslab  # a short unique identifier 
* pip_executable: /usr/bin/pip3  # path to your local pip executable; /usr/bin/pip, usr/bin/pip3


== Deploying ansible-infoblox

You can deploy this config by running the following command from the `ansible`
directory. You will have to provide credentials and adjust settings to your own
environment.

`ansible-playbook main.yml -e @configs/ansible-infoblox/sample_vars/sample_infoblox_lab.yml -e @<YOUR_SECRET_VARS.yml>`



=== To Delete an environment
----
`ansible-playbook destroy.yml -e @configs/ansible-multitier-infra/sample_vars_ec2.yml -e @<YOUR_SECRET_VARS.yml>`

----




