#!/bin/bash
# Args:
#   aad_destroy guid <config_name> <secret_name>
# Example:
#   aad_destroy wkaws aws_sno aws
# Note:
#   config_name uses a file `<config_name>.yaml`
#   secret_name uses a file `secret-<secret_name>.yaml`

cd ${HOME}/Development/agnosticd

ansible-playbook ${HOME}/Development/agnosticd/ansible/destroy.yml \
  -e guid=$1 \
  -e @${HOME}/Development/agnosticd-vars/$2.yaml \
  -e @${HOME}/Development/agnosticd-vars/secrets.yaml \
  -e @${HOME}/Development/agnosticd-vars/secrets-$3.yaml \
  -e output_dir=${HOME}/Development/agnosticd-output/$1

cd -
