#!/bin/bash
# Args:
#   aad_create guid config_name <secret_name>
# Example:
#   aad_create wkaws aws_sno aws
# Note:
#   config_name uses a file `<config_name>.yaml`
#   secret_name uses a file `secret-<secret_name>.yaml`

rm -rf ${HOME}/Development/agnosticd-output/$1

cd ${HOME}/Development/agnosticd

ansible-playbook ${HOME}/Development/agnosticd/ansible/main.yml \
  -e guid=$1 \
  -e @${HOME}/Development/agnosticd-vars/$2.yaml \
  -e @${HOME}/Development/agnosticd-vars/secrets.yaml \
  -e @${HOME}/Development/agnosticd-vars/secrets-$3.yaml \
  -e output_dir=${HOME}/Development/agnosticd-output/$1

cd -
