#!/bin/bash
# Args:
#   aad_workload action guid basedomain workload_name
# Example:
#   aad_workload create myguid sandbox2794.opentlc.com ocp4_workload_pipelines
#   aad_workload remove myguid sandbox2794.opentlc.com ocp4_workload_pipelines

ACTION=${1}
GUID=${2}
HOSTGUID=${2}
BASE_DOMAIN="${3}"
WORKLOAD=${4}

TARGET_HOST=bastion.${HOSTGUID}.${BASE_DOMAIN}
OCP_USERNAME="system:admin"

CLOUD_PROVIDER=ec2
ANSIBLE_USER=ec2-user

#VERBOSITY=-vvvv

# Your private key file matching the public key on Github
ANSIBLE_USER_KEY_FILE="~/.ssh/private-key.pem"

rm -rf $HOME/Development/agnosticd-output/${WORKLOAD}

# Deploy the Workload
ansible-playbook ${VERBOSITY} -i ${TARGET_HOST}, ~/Development/agnosticd/ansible/configs/ocp-workloads/ocp-workload.yml \
  --private-key=${ANSIBLE_USER_KEY_FILE} \
  -e"ansible_user=${ANSIBLE_USER}" \
  -e"ocp_username=${OCP_USERNAME}" \
  -e"ocp_workload=${WORKLOAD}" \
  -e"subdomain_base=${BASE_DOMAIN}" \
  -e"subdomain_base_suffix=.${BASE_DOMAIN}" \
  -e"silent=False" \
  -e"guid=${GUID}" \
  -e"ACTION=${ACTION}" \
  -e"become_override=False" \
  -e"output_dir=$HOME/Development/agnosticd-output/${WORKLOAD}" \
  -e"cloud_provider=${CLOUD_PROVIDER}" \
  -e"target_host=bastion.${GUID}.${BASE_DOMAIN}" \
  -e @$HOME/Development/agnosticd-vars/workload-${WORKLOAD}.yaml \

