#!/bin/bash
# Args:
#   aad_workload action guid target_host basedomain workload_name
# Example:
#   aad_workload create myguid bastion.guid.sandbox2794.opentlc.com sandbox2794.opentlc.com ocp4_workload_pipelines
#   aad_workload remove myguid bastion.guid.sandbox2794.opentlc.com sandbox2794.opentlc.com ocp4_workload_pipelines

ACTION=${1}
GUID=${2}
TARGET_HOST="${3}"
BASE_DOMAIN=$"${4}"
WORKLOAD=${5}

OCP_USERNAME="wkulhane-redhat.com"
#OCP_USERNAME="system:admin"

CLOUD_PROVIDER=ec2
ANSIBLE_USER=opentlc-mgr
#ANSIBLE_USER=ec2-user

# Enable verbosity for debugging purposes
#VERBOSITY=-vvvv

# The key used to set up your cluster
#ANSIBLE_USER_KEY_FILE="~/Development/agnosticd-output/${GUID}/ssh_provision_${GUID}"
ANSIBLE_USER_KEY_FILE="~/.ssh/opentlc_admin_backdoor.pem"
# Your private key file matching the public key on Github
# You can override with your own private key
# ANSIBLE_USER_KEY_FILE="~/.ssh/xxxxxxx-github"

rm -rf $HOME/Development/agnosticd-output/${WORKLOAD}

cd $HOME/Development/agnosticd

# Deploy the Workload
ansible-playbook ${VERBOSITY} -i ${TARGET_HOST}, ~/Development/agnosticd/ansible/configs/ocp-workloads/ocp-workload.yml \
  --private-key=${ANSIBLE_USER_KEY_FILE} \
  -e"ansible_user=${ANSIBLE_USER}" \
  -e"ocp_username=${OCP_USERNAME}" \
  -e"ocp_workload=${WORKLOAD}" \
  -e"subdomain_base=${BASE_DOMAIN}" \
  -e"subdomain_base_suffix=.${BASE_DOMAIN}" \
  -e"silent=False" \
  -e"guid=${GUID}" \
  -e"ACTION=${ACTION}" \
  -e"become_override=False" \
  -e"output_dir=$HOME/Development/agnosticd-output/${WORKLOAD}" \
  -e"cloud_provider=${CLOUD_PROVIDER}" \
  -e"target_host=bastion.${GUID}.${BASE_DOMAIN}" \
  -e @$HOME/Development/agnosticd-vars/${WORKLOAD}.yaml \

cd -
