#!/bin/bash

# calls ansible_playbook with a specified environment

# for use with ansible_agnostic_deployer

THIS_FILE=`readlink -f $0`
ORIGINAL_DIR=`pwd`
AGNOSTIC_DEPLOYER_ROOT=$(realpath `dirname $(readlink -f $0)`/../../..)
GUID=dbenoit
ENVID=80
CLOUDPROVIDER=ravello
ENVTYPE=rhcls-scalable-infra
SOFTWARE=rhcls-scalable-infra
REMOTE_USER=cloud-user
SSH_USER=cloud-user
DELETE_APP=false
OWN_KEY=false
REPO_VERSION=3.5
OSRELEASE=''
REPO_METHOD=rhn
INSTALL_IPA_CLIENT=false
ENV_EXPIRE=256
IPAPASS='ipapass -p cloud-user'
INSTALL_IDM=htpasswd
NFSPVS=/dev/vdb

cd $AGNOSTIC_DEPLOYER_ROOT

# If called without --no-increment flag, 
# execute ansible-playbook and increment iteration
if [[ "$1" == "--no-increment" ]]; then
     ansible-playbook $AGNOSTIC_DEPLOYER_ROOT/ansible/main.yml \
      -e "env_type=$ENVTYPE" \
      -e "cloud_provider=$CLOUDPROVIDER" \
      -e "software_to_deploy=$SOFTWARE" \
      -e "guid=$GUID-`printf '%x' $ENVID`" \
      -e "ANSIBLE_REPO_PATH=$AGNOSTIC_DEPLOYER_ROOT/ansible" \
      -e "delete_app_post_deploy=$DELETE_APP" \
      -e "remote_user=$REMOTE_USER" \
      -e "ansible_ssh_user=$SSH_USER" \
      -e "use_own_key=$OWN_KEY" \
      -e "repo_version=$REPO_VERSION" \
      -e "repo_method=$REPO_METHOD" \
      -e "install_ipa_client=$INSTALL_IPA_CLIENT" \
      -e "env_expire=$ENV_EXPIRE" \
      -e "ipa_host_password=$IPAPASS" \
      -e "install_idm=$INSTALL_IDM" \
      -e "osrelease=$OSRELEASE" \
      -e "nfs_pvs=$NFSPVS" \
        -vvvv  # --tags
else
  sed -i "s/ENVID=$ENVID/ENVID=$(($ENVID+1))/" $THIS_FILE
  script -c "time $THIS_FILE --no-increment" \
            $AGNOSTIC_DEPLOYER_ROOT/ansible/workdir/$ENVTYPE-`printf '%x' $ENVID`-output
fi

cd $ORIGINAL_DIR

