---
become_override: false
ocp_username: opentlc-mgr
silent: false

# sets up the first N worker nodes as infra nodes

# number of infranodes desired
ocp4_workload_infra_nodes_count: 2

# what label on the nodes to make infra nodes
ocp4_workload_infra_nodes_find_label: node-role.kubernetes.io/worker

# labels to add
ocp4_workload_infra_nodes_labels:
  - node-role.kubernetes.io/infra=""
  - node-role.kubernetes.io="infra"

# should worker label be removed
ocp4_workload_infra_nodes_remove_worker_labels: false

# add infranode taints
ocp4_workload_infra_nodes_taints_enabled: true
ocp4_workload_infra_nodes_taints:
  - key: node-role.kubernetes.io/infra
    value: "reserved"
    effect: NoSchedule
  - key: node-role.kubernetes.io/infra
    value: "reserved"
    effect: NoExecute
