= agnosticd_save_output_dir

Save AgnosticD `output_dir` contents to cloud storage.

== Configuration

`agnosticd_save_output_dir_archive` -
Archive to create of content of `output_dir` and upload to cloud storage.

`agnosticd_save_output_dir_s3_bucket` -
S3 storage bucket in which to save output archive.

`agnosticd_save_output_dir_s3_region` -
Region for S3 storage bucket.

`agnosticd_save_output_dir_s3_access_key_id` -
AWS access key id to use to authenticate to S3.

`agnosticd_save_output_dir_s3_secret_access_key` -
AWS secret access key to use to authenticate to S3.

`agnosticd_save_output_dir_archive_password` -
Protect archive with password, it can be useful if the S3 bucket is shared between multiple users. Behind the scene, it uses GPG symmetric encryption. Default: undefined.

== AWS policy to attach to IAM users ==

In case you have a shared bucket, here is the minimal Policy to attach to IAM users to let them use the bucket to save agnosticd output_dir. In the following policy the bucket name is `agnosticd-output-dir`, change it if needed. Users will only be able to push or pull an object if they know the name of the bucket and the archive (usually name contains uuid).

.Minimal Policy
[source,json]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "objects",
            "Effect": "Allow",
            "Action": [
                "s3:GetObjectVersionTagging",
                "s3:GetObjectAcl",
                "s3:GetObjectAttributes",
                "s3:PutObject",
                "s3:PutObjectTagging",
                "s3:GetObject",
                "s3:GetObjectTagging",
                "s3:PutObjectAcl",
                "s3:DeleteObject",
                "s3:GetObjectVersionAcl",
                "s3:GetObjectVersion"
            ],
            "Resource": [
                "arn:aws:s3:::agnosticd-output-dir/*"
            ]
        }
    ]
}
----
