---
# Implement your Pre Workload deployment tasks here

- name: Check for required variables
  ansible.builtin.assert:
    that:
    - ocp4_workload_rhoso_ipam4lab_service_url is defined
    - ocp4_workload_rhoso_ipam4lab_service_url != ''
    - ocp4_workload_rhoso_ipam4lab_allocation_name is defined
    - ocp4_workload_rhoso_ipam4lab_allocation_name != ''
    quiet: true
    fail_msg: "Required variables not defined: ocp4_workload_rhoso_ipam4lab_service_url and ocp4_workload_rhoso_ipam4lab_allocation_name must be set"

- name: Pre_workload tasks complete
  when: not silent | bool
  ansible.builtin.debug:
    msg: "Pre-Workload tasks completed successfully."
