:role: satellite-register-host
:author: Satellite Team
:tag1: configure_satellite
:tag2: satellite_register_hosts
:main_file: tasks/main.yml
:register_file: tasks/register.yml
:katello_file: tasks/katello_agent.yml
:rex_file: tasks/remote_execution.yml

Role: {role}
============

This role register content hosts to the satellite instance and enables remote execution to be run on the host.

Requirements
------------

. Satellite must be installed and setted up.
. Activation key must be available and it's variable setted up.


Role Variables
--------------

* Following are the variable which needs to be defined

|===
|satellite_version: "Digit" |Required |satellite version
|org_label: "String" |Required |Organization label
|satellite_hosts_register_key: "String" |Required | Activation key name
|satellite_hostname: "String" |Required | Hostname of satellite to register to
|satellite_tools_repo: "String" |Optional | Repository to enable on host to install tools from
|===

* Exammple variables

[source=text]
----
satellite_version: 6.4
org_label: "gpte"
satellite_hosts_register_key: 'three-tier-app'
satellite_tools_repo: 'rhel-7-server-satellite-tools-6.3-rpms'

# This is to illustrate how you'd get the key in your satellite
# It's not used in this role
satellite_content:
  - name:             "Three Tier App"
    content_view:     "Three Tier App"
    activation_key:   "three-tier-app"
----

Tags
---

|===
|{tag1} |Consistent tag for all satellite config roles
|{tag2} |This tag is specific to this role only
|===


Example Playbook
----------------

How to use your role (for instance, with variables passed in playbook).

[source=text]
----
[user@desktop ~]$ cat sample_vars.yml
satellite_version: 6.7
org: "gpte"
org_label: "gpte"
org_description: "Global Partner Training and Enablement"
satellite_hosts_register_key: three_tier_app
satellite_content:
  - name:             "Three Tier App"
    content_view:     "Three Tier App"
    activation_key:   three_tier_app
    repos:
      - name: 'Red Hat Enterprise Linux 7 Server (RPMs)'
        product: 'Red Hat Enterprise Linux Server'
        basearch: 'x86_64'
        releasever:  '7Server'

[user@desktop ~]$ cat playbook.yml
- hosts: satellite_hosts
  vars_files:
    - sample_vars.yml
  vars:
    satellite_hostname: "{{ hostvars[groups['satellites'][0]]['publicname'] }}"
  roles:
    - satellite-register-host

[user@desktop ~]$ ansible-playbook playbook.yml
----

Tips to update Role
------------------

For reference look at link:{main_file}[main.yml]. For host registration at link:{register_file}[register.yml], for katello-agent install at link:{katello_file}[katello_agent.yml] and for remote execution enablement at link:{rex_file}[remote_execution.yml].


Author Information
------------------

{author}
