---
galaxy_info:
  role_name: ocp4_workload_create_rwx_volume
  author: Red Hat, Cluster Platform (ITCP) (itcp-team@redhat.com)
  description: |
    Creates a S3 bucket and the PersistentVolume for it, accessing it as ReadWriteMany
  license: MIT
  min_ansible_version: "2.9"
  platforms: []
  galaxy_tags:
    - ocp
    - openshift
dependencies: []
