- name: Test Dynamic User Provisioning
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    ACTION: "{{ ACTION | default('create') }}"
    guid: "{{ guid | default('test123') }}"

  tasks:
    - name: Include dynamic user provisioning role
      include_role:
        name: ocp4_workload_dynamic_user_provisioning
      vars:
        ocp4_workload_dynamic_user_provisioning_openshift_api_url: "https://api.cluster-29m2x.dynamic.redhatworkshops.io:6443"
        ocp4_workload_dynamic_user_provisioning_admin_user: "admin"
        ocp4_workload_dynamic_user_provisioning_admin_password: "MTg4ODk3"
        become_override: false