---
galaxy_info:
  author: AgnosticD Team
  description: Infrastructure role for managing SSH keys in IBM Cloud Classic
  license: BSD
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
        - 9
    - name: Ubuntu
      versions:
        - 18.04
        - 20.04
        - 22.04
  galaxy_tags:
    - cloud
    - infrastructure
    - ibm
    - ssh
    - classic
    - agnosticd

dependencies: []

collections:
  - ansible.builtin
  - ansible.posix 