#!/bin/bash


yum remove -y google-rhui-client-rhel8.noarch
yum clean all

yum -y install wget
wget https://raw.githubusercontent.com/rhel-labs/learn-katacoda/master/sql-server-cstore/CSIndex.sql
wget https://raw.githubusercontent.com/rhel-labs/learn-katacoda/master/sql-server-cstore/CSNoIndex.sql

mkdir /root/Scripts/
mv CSIndex.sql /root/Scripts/
mv CSNoIndex.sql /root/Scripts/

#Download the install script and run it
curl -o /root/install_sql.sh https://raw.githubusercontent.com/rhel-labs/learn-katacoda/master/sql-server-crypto-policy/install_sql2019.sh
sudo chmod +x ./install_sql.sh

sudo ./install_sql.sh
export HOSTNAME=`hostname --all-fqdns`

firewall-cmd --zone=public --add-service=https --permanent
firewall-cmd --reload

systemctl --now enable httpd

GREEN='\033[0;32m'
NC='\033[0m' # No Color

clear
echo -e "${GREEN}Ready to start your scenario${NC}"