:role: satellite-capsule-configuration
:author: GPTE Team
:tag1: configure_capsule
:main_file: tasks/main.yml
:version_file: tasks/version_6.4.yml

Role: {role}
============

This role installs capsule server.

Requirements
------------

Following are the requirements:

. Satellite must be install and setup.
. Satellite should have capsule activation key and repositories. 
. Capsule packages should be installed.
. Capsule certifcate
 
Role Variables
--------------

* Following are the variable which needs to be defined 

|===
|satellite_version: "Digit" |Required |satellite version
|satellite_public_fqdn: "String" |Required | Satellite public accessible fully qualified domain name
|consumer_key | Required | Key which can be found in capsule-certs-generate   command's output
|consumer_secret | Required | Secret which can be found in capsule-certs-generate   command's output
| capsule_cert_path | Required | Capsule ertificate path
|===
    
* Exammple variables

. variable in sample_vars.yml
+
[source=text]
----
satellite_public_fqdn: satellite1.<guid>.example.opentlc.com
consumer_key:  "************************************"
consumer_secret: "******************************"
capsule_cert_path:  /tmp/capsule-cert.tar 
----


Dependencies
------------
* Role is dependent on following roles
  . satellite-public-hostname
  . satellite-capsule-installation

* Role is dependent on Capsule certificate 
  . Below is example to generate capsule certificate manually
+
[source=text]
----
[root@satellite ~]# capsule-certs-generate \
      --foreman-proxy-fqdn capsule1.<guid>.example.com \
      --certs-tar /tmp/capsule-certs.tar

[root@satellite ~]# scp /tmp/capsule-certs.tar root@capsule1.<guid>.example.com:/tmp/capsule-certs.tar
    
----
** Sample output
+
[source=text]
----
Resetting puppet server version param...
Installing             Done                                               [100%] [....................................................................]
  Success!
ATTENTION. For Capsule upgrades:
  Please see official documentation for steps and parameters to use when upgrading a 6.3 Capsule to 6.4.

  ==== output omitted ====

  satellite-installer --scenario capsule\
                      --foreman-proxy-content-parent-fqdn           "satellite1.<guid>.example.opentlc.com"\
                      --foreman-proxy-register-in-foreman           "true"\
                      --foreman-proxy-foreman-base-url              "https://satellite1.<guid>.example.opentlc.com"\
                      --foreman-proxy-trusted-hosts                 "satellite1.<guid>.example.opentlc.com"\
                      --foreman-proxy-trusted-hosts                 "capsule.<guid>.red.osp.opentlc.com"\
                      --foreman-proxy-oauth-consumer-key            "******************************"\
                      --foreman-proxy-oauth-consumer-secret         "************************"\
                      --foreman-proxy-content-certs-tar             "/tmp/capsule-cert.tar"\
                      --puppet-server-foreman-url                   "https://satellite1.<guid>.example.opentlc.com"
  The full log is at /var/log/foreman-installer/foreman-proxy-certs-generate.log
    
----

[NOTE]
====
* Don't generate certificate manually for *_multi-region-capsule_* config instead use role *_satellite-manage-capsule-certificate_*

====



Tags
---

|===
|{tag1} | This tag is specific to installation tasks.
|===

* Example tags

----
## Tagged jobs
ansible-playbook playbook.yml --tags install_capsule

## Skip tagged jobs
ansible-playbook playbook.yml --skip-tags install_capsule
----

Example Playbook
----------------

How to use your role (for instance, with variables passed in playbook).

[source=text]
----

[user@desktop ~]$ cat playbook.yml
- hosts: capsule.example.com
  vars_files:
    - sample_vars.yml
  roles:
    - satellite-public-hostname
    - satellite-capsule-installation
    - satellite-capsule-configuration

[user@desktop ~]$ ansible-playbook playbook.yml

----


Tips to update Role
------------------

To extend role works for other version, create new file named  version_{{satellite_version}}.yml and import newly created file in main.yml

for reference look at link:{main_file}[main.yml] and link:{version_file}[version_6.4.yml] .


Author Information
------------------

{author}
