= ocp-workload-3scale-multitenant

== NOTES

. Using a version of oc utility that corresponds to your target OCP cluster, ensure oc utility is already authenticated as the cluster-admin:   opentlc-mgr
. This workload requires installation of xmlstarlet on target host executing this ansible
. This workload only needs to be executed once per OCP cluster
. This workload provisions a single centralized 3scale multi-tenant app in a single OCP namespace called: 3scale-mt-$GUID
. The OCP namespace for 3scale multi-tenant app will be owned by the following user:
.. user100
.. user100 will be assigned a clusterquota so as to manage limits and requests assigned to 3scale
. This workload can optionally create multiple tenants in this single multi-tenant 3scale.  If so then ensure the following when invoking this ansible:
.. specify TAGS is either "all" or "tenants"
..  specify "start_tenant" and "end_tenant" variables


== Execution using localhost oc client

-----
WORKLOAD="ocp-workload-3scale-multitenant"

# valid values:  "all" , "3scale" or "tenants"
TAGS=all

START_TENANT=1
END_TENANT=2

HOST_GUID=`oc whoami --show-server | cut -d'.' -f 2`
OCP_DOMAIN=$HOST_GUID.openshift.opentlc.com
GUID=adm0

ansible-playbook -i localhost, -c local ./configs/ocp-workloads/ocp-workload.yml \
                    -e"ANSIBLE_REPO_PATH=`pwd`" \
                    -e"ocp_workload=${WORKLOAD}" \
                    -e"guid=$GUID" \
                    -e"ACTION=create" \
                    -e"ocp_domain=$OCP_DOMAIN" \
                    -e"start_tenant=$START_TENANT" \
                    -e"end_tenant=$END_TENANT" \
                    -t $TAGS

ansible-playbook -i localhost, -c local ./configs/ocp-workloads/ocp-workload.yml \
                    -e"ANSIBLE_REPO_PATH=`pwd`" \
                    -e"ocp_workload=${WORKLOAD}" \
                    -e"guid=$GUID" \
                    -e"ACTION=remove"
-----
