= ocp-workload-3scale-multitenant

== NOTES

=== API Manager
. Using a version of oc utility that corresponds to your target OCP cluster, ensure oc utility is already authenticated as the cluster-admin:   opentlc-mgr
. This workload requires installation of xmlstarlet on target host executing this ansible
. This workload only needs to be executed once per OCP cluster
. This workload provisions a single centralized 3scale multi-tenant app in a single OCP namespace called: 3scale-mt-$GUID
. The OCP namespace for 3scale multi-tenant app will be owned by the following non-existant user: {{admin_username}}
.. {{admin_username}} will be assigned a clusterquota so as to manage limits and requests assigned to 3scale

=== Tenants

This workload can optionally create multiple tenants in this single multi-tenant 3scale.  If so then ensure the following when invoking this ansible:

. specify ACTION = "tenant_mgmt"
. specify "start_tenant" and "end_tenant" variables
. set value of CREATE_GWS_WITH_EACH_TENANT (true / false) to automate provisioning of a staging and production GW for each tenant


== Execution using localhost oc client

-----


WORKLOAD="ocp-workload-3scale-multitenant"
SUBDOMAIN_BASE=`oc whoami --show-server | cut -d'.' -f 2,3,4,5 | cut -d':' -f 1`


# API manager provision
ansible-playbook -i localhost, -c local ./configs/ocp-workloads/ocp-workload.yml \
                    -e"ANSIBLE_REPO_PATH=`pwd`" \
                    -e"ocp_workload=${WORKLOAD}" \
                    -e"ACTION=create" \
                    -e"subdomain_base=$SUBDOMAIN_BASE"


# Tenant management
START_TENANT=1
END_TENANT=1
CREATE_GWS_WITH_EACH_TENANT=true

# Tenant Management
ansible-playbook -i localhost, -c local ./configs/ocp-workloads/ocp-workload.yml \
                    -e"ANSIBLE_REPO_PATH=`pwd`" \
                    -e"ocp_workload=${WORKLOAD}" \
                    -e"ACTION=tenant_mgmt" \
                    -e"start_tenant=$START_TENANT" \
                    -e"end_tenant=$END_TENANT" \
                    -e"create_gws_with_each_tenant=$CREATE_GWS_WITH_EACH_TENANT" \
                    -e"subdomain_base=$SUBDOMAIN_BASE"


# Delete
REMOVE_TENANTS_ONLY=true
ansible-playbook -i localhost, -c local ./configs/ocp-workloads/ocp-workload.yml \
                    -e"ANSIBLE_REPO_PATH=`pwd`" \
                    -e"ocp_workload=${WORKLOAD}" \
                    -e"ACTION=remove" \
                    -e"subdomain_base=$SUBDOMAIN_BASE" \
                    -e"REMOVE_TENANTS_ONLY=$REMOVE_TENANTS_ONLY"
-----

-----
-e"subdomain_base=$SUB_DOMAIN"
-----
