= OCP 4 Workshop

== Review the Env_Type variable file

* These are all the possible variables you might want to define, and the default for this config
** link:./env_vars.yml[./env_vars.yml]

* You should create your own myenvironment-variables.yaml, based on the example above and use it as below.

== Running Ansible Playbook

=== Running Playbook With Environment and Secrets files

You can create yaml files of your desired configs and secrets and execute them:

* `cd agnosticd/`
* `ansible-playbook ansible/main.yaml -e @/home/myself/myenvironment-variables.yml -e@/home/myself/my_secret.yml`

=== To Delete an environment

just replace in the command used to deploy, the `main.yml` with `destroy.yml`

* `ansible-playbook ansible/destroy.yaml -e @/home/myself/myenvironment-variables.yml -e@/home/myself/my_secret.yml`

== Sample Environmet Variables

[source,yaml]
----
---
env_type: ocp4-workshop
guid: myguid
cloud_provider: ec2
cloud_tags: {'Purpose': 'development'}
aws_region: us-east-2
cloudformation_retries: 0
key_name: ocpkey
software_to_deploy: none
install_ipa_client: false
osrelease: '4.1'
repo_version: '4.1.0'
own_repo_path: http://CHANGEME/{{ repo_version }}
email: jmaltin@redhat.com
install_ocp4: yes
default_workloads: []
install_idm: htpasswd
install_student_user: true
admin_user: admin
admin_password: CHANGEME
student_sudo: false
student_name: lab-user
student_password: 'changeme'
student_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3Avw03Dmh1R2QWQ4CV7JgEsXnHQjNhfppD5aZmh0q/64p6lW+2oNKTT7fVQcrsdmlJwrMd5apkUGrOcq0hHXQMEVZEKUmEjko2BqD5A9/zNX7apObW88bFFfgxc91lOT+e+wfCFsrr3b2SJ3+KL6nTBJV7Lf46i6z86vhiDPjqL7U9kTS+bK9ldU20vpn8h+ZAIaiafVWfjihUjhNpcUY46klixV1YcAkBGCbE+YR6RAAc6vWy0zB3YJnTUl9OFt213ofi1qjuWKVMmOxORxPKB4/JQ+hfAsCMysoVFnFYs10dWxaySK63OgY9uLNyaIwkEaVVIfcViRVm0DZfoNH
subdomain_base_suffix: .openshift.opentlc.com
HostedZoneId: Z186MFNM7DX4NF
worker_instance_type: m4.xlarge
worker_instance_count: 1
ocp4_token: >-
  Your OCP token from try.openshift.com
----
