FROM registry.access.redhat.com/ubi8/ubi-minimal:latest
RUN microdnf install -y python3 openssh

LABEL maintainer="Guillaume Core (fridim) <gucore@redhat.com>"

RUN pip3 install --upgrade pip
RUN pip3 install ansible==2.9.23 awscli
RUN pip3 install boto boto3

USER ${USER_UID}
