FROM centos/python-36-centos7

LABEL maintainer="Guillaume Core (fridim) <gucore@redhat.com>"

USER root

RUN pip install --upgrade pip
RUN pip install ansible
RUN pip install \
    openstacksdk \
    python-heatclient \
    python-openstackclient \
    dnspython


USER ${USER_ID}