FROM centos:8
LABEL MAINTAINER "Rafael Marins (rmarins) <rmarins@redhat.com>"

ADD packer/google-cloud-sdk.repo /etc/yum.repos.d/

RUN yum update -y && \
    yum install -y wget google-cloud-sdk python36 git which unzip tmux

#RUN wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm && \
#    yum -y install `ls *epel*.rpm` && rm -rf `ls *epel*.rpm`

RUN pip3 install boto boto3 && \
    pip3 install -r https://raw.githubusercontent.com/redhat-cop/agnosticd/development/ansible/configs/ocp4-cluster/files/requirements_k8s.txt
#    pip install -t lib/ google-cloud google-cloud-ndb

USER ${USER_UID}

#####
#ln -sf /usr/lib/google-cloud-sdk/lib/gcloud.py /usr/lib/gcloud.py
#pip install -t lib/ google-cloud-ndb
#apt-get install python-six


#####
#docker run -it --rm gcr.io/google.com/cloudsdktool/cloud-sdk /bin/bash
#pip install --upgrade pip && pip install ansible boto boto3