FROM python:alpine

RUN apk add --no-cache --purge -uU \
  gcc \
  musl-dev \
  libffi-dev \
  openssl-dev \
  libressl-dev \
  openssh-client \
  sudo \
  curl \
  ca-certificates

RUN mkdir -p /etc/ansible \
    && ln -s /usr/local/bin/python /usr/bin/python \
    && rm -rf /var/cache/apk/* /tmp/*

RUN pip3 install --no-cache --upgrade pip

RUN pip3 install --no-cache \
    ansible \
    openstacksdk \
    python-heatclient \
    python-openstackclient \
    dnspython

USER ${USER_UID}
