This role implements link:https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-capacity-reservations.html[on-demand capacity reservation] in agnosticd.

== Core role `agnosticd_aws_capacity_reservation` ==

The goal of the role is to provide a mean for us to make sure the capacity is reserved in the early stages of agnosticd (pre_infra), instead of failing later when it tries to create the instances.


input:

[source,yaml]
.In agnosticv
----
# credentials must be set
aws_access_key_id: ...
aws_secret_access_key: ...
agnosticd_aws_capacity_reservation:
  regions: # <1>
  - us-east-1
  - us-east-2
  reservations:
    az1:
      - instance_count: 1
        instance_platform: Linux/UNIX
        instance_type: t3a.medium
      - instance_count: 2
        instance_platform: Linux/UNIX
        instance_type: m5a.4xlarge
    az2:
      - instance_count: 3
        instance_platform: Linux/UNIX
        instance_type: m5a.2xlarge
----
<1> for mono-region provisioning, here we can use `aws_region` passed from cloudforms:
+
----
regions:
- "{{ aws_region }}"
----

Ideally, that variable should be configured in the `default_vars_ec2.yaml` directly in the config. For ex:
[source,yaml]
.input as part of `default_vars_ec2.yaml`
----
agnosticd_aws_capacity_reservation:
  regions:
  - "{{ aws_region }}"
  reservations:
    az1:
      - instance_count: 1
        instance_platform: Linux/UNIX
        instance_type: "{{ bastion_instance_type }}"
      - instance_count: "{{ worker_instance_count }}"
        instance_platform: Linux/UNIX
        instance_type: "{{ worker_instance_type }}"
    az2:
      - instance_count: "{{ master_instance_count }}"
        instance_platform: Linux/UNIX
        instance_type: "{{ master_instance_type }}"
----

The role will set the following variables, that can be used in later stages in agnosticd:

.output
[source,yaml]
----
aws_region: us-east-1

agnosticd_aws_capacity_reservation_results:
  region: us-east-1
  az1:
    availability_zone: us-east-1a
    reservations_ids:
      - cr-03ede0234dabf424e
      - cr-08daa70b36405528d
  az2:
    availability_zone: us-east-1b
    reservations_ids:
      - cr-07d8ae35483fe8c98
----

az1 and az2 keys must be chosen carefully and must make sense in the agnosticd config which must support the use of the `agnosticd_aws_capacity_reservation_results` dictionary.
:

NOTE: az1 and az2 found by the role are not necessarly different, they can be the same. The goal of the role is to provide capacity. Later we could add an option to ensure it's spread across AZs and that all the AZ are different. But that's not part of initial implementation.

If there is only one AZ key in the `agnosticd_aws_capacity_reservation` dictionary (all instances are in the same availability zone), then the role also automatically sets the variable `aws_availability_zone`:

[source,yaml]
.Output with only one AZ
----
agnosticd_aws_capacity_reservation_results:
  region: us-east-1
  single_availability_zone: us-east-1a
  az1:
    availability_zone: us-east-1a
    reservations_ids:
      - cr-03ede0234dabf424e
      - cr-08daa70b36405528d

aws_region: us-east-1
aws_availability_zone: us-east-1a
----

=== How ? ===

The role will iterate on all the regions asked, and then for each reservation group, will try to create the capacity reservations in the available AZs.

NOTE: During that process, if a reservation for an instance type fails, the role will delete previous capacity reservations made on that AZ for the other instances types and continue with the next AZ on the list, until an AZ that can host all instances types of the reservation group is found. We shoud probably implement that *in python* and not in ansible, because that kind of tasks are difficult to approach and hard to maintain in ansible.

The capacity reservation will be created with a *TTL of 1h*. That should give plenty of time for agnosticd to create the infra.

When several instance types are under the same AZ group, only an AZ that can host all of them will be selected.

WARNING: Keep in mind that if `aws_region` or `aws_availability_zone` are defined as extra-vars (agnosticV or simply passed to ansible), then the role will not be able to override them.

[source,yaml]
.reservation properties
----
  - instance_count: Integer
    instance_match_criteria: open | targeted # <1>
    instance_platform: String # (usually  Linux/UNIX)
    instance_type: String  # ex: m5a.4xlarge
    tenancy: default | dedicated # <2>
----
<1> default: open, in case of targeted, aws_capacity_reservation_ids is set (in order)
<2>  shared or dedicated hardware. You probably want to keep the default. For more info see https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/dedicated-instance.html

For more info, see link:https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-capacityreservation.html#cfn-ec2-capacityreservation-tagspecifications[AWS doc].

When `instance_match_criteria` is set to `targeted`, the role will also set the `aws_capacity_reservation_ids` var:

[source,yaml]
.output
----
aws_capacity_reservation_ids:
  az1: cr-123456789
  az2: cr-123456789
----

If `instance_match_criteria` is set to `targeted`, the agnosticd config must support it and the ids must be used in the config, otherwise the reservation will not be used for the instances.

=== Should i use open or targeted ? ===

When you're in sandboxes, you can use `open`, and should not really care about `targeted`, as the only thing running in the sandbox will be the current provision.

When in a shared account (ex: GPTE prod account 'gpe'), `targeted` must be used, otherwise there no guarantee which instances will be part of the reservation. Already running instances could match the criteria of the reservation.

At first we would probably use this feature only as `open`, in AWS sandboxes.

WARNING: If you use `targeted`, keep in mind to adjust the TTL properly. Instances targeting a capacity reservation cannot be easily stopped/started. The instances can no longer launch if the target capacity reservation has expired or was canceled.

=== When ? ===

The role would be executed if:

* `agnosticd_aws_capacity_reservation` is defined and not empty
* `agnosticd_aws_capacity_reservation_enable` is true (default is true)


== How to use ODCR in agnosticd config ? ==

The best way is to define the `agnosticd_aws_capacity_reservation` in default vars `default_vars_ec2.yaml` file.

Then, use the
