Role Name
=========

install-rhsso role is intended to add a common red hat sso authentication server for workshop installation. The red hat sso container, services and routes will be added to the shared containers namespace (normally `shared-opentlc`).

In the case of workshops like the RH-PAM workshop, authentication and authorization assets keep unchanged for all students, and different users are required for the student to experiment as different personas participating through the execution of the labs, hence the student is familiarized with the product experience from different perspectives.

For projects where the student will perform changes to the authentication and authorization assets, it is best to keep the authentication server (Red Hat SSO) as a particular asset for the student workshop environment, instead of a shared resource.

Requirements
------------

* **OC Client tools**: As this is a provisioning role for an OCP workshop environment.

Role Variables
--------------

> A description of the settable variables for this role should go here, including any variables that are in defaults/main.yml, vars/main.yml, and any variables that can/should be set via parameters to the role. Any variables that are read from other roles and/or the global scope (ie. hostvars, group vars, etc.) should be mentioned here as well.

* **shared_ns**: Intended to install the rh-sso server in the shared resources for workshop environment. Normally expecting this parameter value to be `shared-opentlc`


Example Playbook
----------------

```yaml
  - hosts: masters
    roles:
    - role: "{{ ANSIBLE_REPO_PATH }}/roles/ocp-workload-rhsso"
      shared_ns: "{{admin_project}}"
```

Testing with workshop available master node:

  . Using a version of oc utility that corresponds to your target OCP cluster, ensure oc utility is already authenticated as the cluster-admin:   opentlc-mgr

== Execution using localhost oc client

-----
WORKLOAD="ocp-workload-rh-sso"
GUID=jb45

HOST_GUID=`oc whoami --show-server | cut -d'.' -f 2`
OCP_DOMAIN=$HOST_GUID.openshift.opentlc.com

ansible-playbook -i localhost, -c local ./configs/ocp-workloads/ocp-workload.yml \
                    -e"ANSIBLE_REPO_PATH=`pwd`" \
                    -e"ocp_workload=${WORKLOAD}" \
                    -e"ocp_user_needs_quota=true" \
                    -e"guid=$GUID" \
                    -e"ocp_domain=$OCP_DOMAIN" \
                    -e"ACTION=create" \
                    -e"ocp_username=dtorresf-redhat.com"

ansible-playbook -i localhost, -c local ./configs/ocp-workloads/ocp-workload.yml \
                    -e"ANSIBLE_REPO_PATH=`pwd`" \
                    -e"ocp_workload=${WORKLOAD}" \
                    -e"guid=$GUID" \
                    -e"ACTION=remove" \
                    -e"ocp_username=dtorresf-redhat.com"
-----



=== Deploy a Workload with the `ocp-workload` playbook [Mostly for testing]
----
GUID=jb45
HOST_GUID=dev39
TARGET_HOST="bastion.$HOST_GUID.openshift.opentlc.com"
OCP_USERNAME="jbride-redhat.com"
WORKLOAD="ocp-workload-rh-sso"
SSH_USERNAME="jbride-redhat.com"
SSH_PRIVATE_KEY="id_ocp"

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
                 -e"ansible_ssh_private_key_file=~/.ssh/${SSH_PRIVATE_KEY}" \
                 -e"ansible_ssh_user=${SSH_USERNAME}" \
                    -e"ANSIBLE_REPO_PATH=`pwd`" \
                    -e"ocp_username=${OCP_USERNAME}" \
                    -e"ocp_workload=${WORKLOAD}" \
                    -e"guid=${GUID}" \
                    -e"ocp_user_needs_quota=true" \
                    -e"ocp_apps_domain=apps.${HOST_GUID}.openshift.opentlc.com" \
                    -e"ACTION=create"

----

=== To Delete an environment

----
GUID=jb45
HOST_GUID=dev39
TARGET_HOST="bastion.$HOST_GUID.openshift.opentlc.com"
OCP_USERNAME="jbride-redhat.com"
WORKLOAD="ocp-workload-rh-sso"
SSH_USERNAME="jbride-redhat.com"
SSH_PRIVATE_KEY="id_ocp"

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
                 -e"ansible_ssh_private_key_file=~/.ssh/${SSH_PRIVATE_KEY}" \
                 -e"ansible_ssh_user=${SSH_USERNAME}" \
                    -e"ANSIBLE_REPO_PATH=`pwd`" \
                    -e"ocp_username=${OCP_USERNAME}" \
                    -e"ocp_workload=${WORKLOAD}" \
                    -e"guid=${GUID}" \
                    -e"ACTION=remove"
----

License
-------

BSD

Author Information
------------------

dtorresf