:role: rhel_zero_touch_user (draws from role rhel_zero_touch_user)
:author1: Tony Kay <tok@redhat.com>
:team: Portfolio Technology Engineering
:date: 2023-11-01


Role: {role}
============

The role {role} is largely derived from the ansible service account centric  rhel_zero_touch_user

* creates a user
** enable sudoers 
** sets up ssh keys/config
** sets up resource directory
** and copies content/files in resource dir .

Requirements
------------

* Ansible `>=2.9`
* To run the role it needs `become: true`

Role tree structure
-------------------

[source=textinfo]
----
rhel_zero_touch_user/
├── README.adoc
├── defaults
│   └── main.yml
├── files
│   └── .vimrc
├── meta
│   └── main.yml
└── tasks
    ├── copy-contents.yml
    ├── copy-files.yml
    ├── copy-templates.yml
    ├── create-directory.yml
    ├── create-user.yml
    ├── main.yml
    └── ssh-config.yml

4 directories, 11 files
----

Role Variables
--------------

. List of variables used in {role} role-
+
[cols="5",options="header"]
|===
| Variable | Type | Required/Default | Example | Description

| rhel_zero_touch_user_enable_skel | Bool | true | rhel_zero_touch_user_enable_skel=true | Enable skel task, Click link:tasks/main.yml#L8[task] to read

| rhel_zero_touch_user_skel_files | List of files | [.vimrc] | rhel_zero_touch_user_skel_files=[.vimrc, ./files/test.txt] | list of user skel files, Click link:tasks/main.yml#L7[task] to read

| rhel_zero_touch_user_name | String  | devops | control_user=devops | User name, Click link:tasks/create-user.yml#L5[task] to read

| rhel_zero_touch_user_private_group  | String | users | rhel_zero_touch_user_private_group=users | User's private group name, Click link:tasks/create-user.yml#L6[task] to read

| rhel_zero_touch_user_groups_append | Bool | true | rhel_zero_touch_user_groups_append=true | Click link:tasks/create-user.yml#L7[task] to read

| rhel_zero_touch_user_groups | Comma separated list | omit | rhel_zero_touch_user_groups=wheel,root | List of secondary groups, Click link:tasks/create-user.yml#L8[task] to read

| rhel_zero_touch_user_password | Hash | omit | rhel_zero_touch_user_password="{{ 'redhat' \| password_hash( 'sha512' ) }}"| User's password, Click link:tasks/create-user.yml#L9[task] to read

| contole_user_password_update | String | omit |  contole_user_password_update=always | Run password update, Click link:tasks/create-user.yml#L10[task] to read

| rhel_zero_touch_user_enable_sudoers | Bool | true | rhel_zero_touch_user_enable_sudoers=true | Enable sudoers, Click link:tasks/main.yml#L21[task] to read

| rhel_zero_touch_user_sudo_commands | String | "NOPASSWD: ALL" | rhel_zero_touch_user_sudo_commands: "NOPASSWD: ALL" or "ALL" | Sudoer's commands, Click link:tasks/main.yml#L18[task] to read

| rhel_zero_touch_user_enable_env_ssh_keys | Bool | true | rhel_zero_touch_user_enable_env_ssh_keys=true | Copy config environment key to user, Click link:tasks/ssh-config.yml#L11[task] to read

| rhel_zero_touch_user_custom_ssh_keys | List of files | None | rhel_zero_touch_user_custom_ssh_keys=[private.pem, public.pub] | Copy custom ssh keys to user, Click link:tasks/ssh-config.yml#L37[task] to read

| rhel_zero_touch_user_ssh_config | file | None | rhel_zero_touch_user_ssh_config=ssh_config.j2 | Copy ssh host config, Click link:tasks/ssh-config.yml#L43[task] to read

| rhel_zero_touch_user_resource_dir_name | String | None | rhel_zero_touch_user_resource_dir_name=materials | Resource Directory name, Click link:tasks/create-directory.yml#L4[task] to read 

| rhel_zero_touch_user_directories | List of directories | None | rhel_zero_touch_user_directories=[ files, .config ] | Creates directories in user's home, Click link:tasks/create-directory.yml#L20[task] to read 

| rhel_zero_touch_user_copy_user_files | List of nested dictionary | None | Look at variables examples below | Dictionary of files to copy, Click link:tasks/copy-files.yml[task] to read 

| rhel_zero_touch_user_copy_user_templates | List of nested dictionary | None | Look at variables examples below | Dictionary of templates to copy, Click link:tasks/copy-templates.yml[task] to read 

| rhel_zero_touch_user_copy_user_contents | List of nested dictionary | None | Look at variables examples below | Dictionary of contents to copy, Click link:tasks/copy-contents.yml[task] to read 

|===
 
Example of Variables and Values
--------------------------------
. Example -- following variables will copy files in /etc/skel directory
+
[source=text]
----
rhel_zero_touch_user_enable_skel: true  
rhel_zero_touch_user_skel_files:
  - .vimrc
  - .bashrc
  - .bash_profile
----

. Example -- following variables will create user and groups
+
[source=text]
----
## User's variable used in tasks/create-user.yml
rhel_zero_touch_user_name: devops                    
rhel_zero_touch_user_private_group: users       
rhel_zero_touch_user_groups_append: true
rhel_zero_touch_user_groups: root,wheel
rhel_zero_touch_user_password: "{{ 'redhat' \| password_hash( 'sha512' ) }}"
contole_user_password_update: true
----


. Example -- following variables will create user's directory in user's home
+
[source=text]
----
rhel_zero_touch_user_resource_dir_name: materials
rhel_zero_touch_user_directories:
  - ".config/openstack"
  - "public_html"  

----


. Example -- following variables will setup sudoers
+
[source=text]
----
rhel_zero_touch_user_enable_sudoers: true  
rhel_zero_touch_user_sudo_commands: "NOPASSWD: ALL"
----

. Example -- following variables will setup ssh keys and copy them in ~/.ssh/ directory
+
[source=text]
----
## SSH setup variables           
rhel_zero_touch_user_enable_env_ssh_keys: true  
rhel_zero_touch_user_custom_ssh_keys:
  - private.key
  - public.key
  - openstack.pem
  - openstack.pub
rhel_zero_touch_user_ssh_config: ./file/ssh_config.j2 
----

. Example -- following variables will copy files
+
[source=text]
----
# Variable as list
rhel_zero_touch_user_copy_user_files:
  - file: ./file/clouds.yaml        # Source files 
    resource: clouds.yaml           # (optional) Destination will be resource directory
    home: .clouds.yaml              # (optional) Destination will be home directory
    path: /etc/openstack/clouds.yml # (optional) Destination is path
  
  - file: source
    resource: dest

  - file: source
    home: dest
    path: /path/dest

# We can use all (resource, home, path ) together or one, two of them. 
----

. Example -- following variables will copy templates
+
[source=text]
----
# Variable as list
rhel_zero_touch_user_copy_user_templates:
  - template: ./file/clouds.yaml.j2        # Source files 
    resource: clouds.yaml           # (optional) Destination will be resource directory
    home: .clouds.yaml              # (optional) Destination will be home directory
    path: /etc/openstack/clouds.yml # (optional) Destination is path
  
  - template: source
    resource: dest

  - template: source
    home: dest
    path: /path/dest

# We can use all (resource, home, path ) together or one, two of them. 
----

. Example -- following variables will  copy contents
+
[source=text]
----
## Copy contents as defined
rhel_zero_touch_user_copy_user_contents:
  - content: "Welcome to my page"   # Source files 
    resource: index.html            # (optional) Destination will be resource directory
    home: .public_html/index.html   # (optional) Destination will be home directory
    path: /var/www/html/index.html  # (optional) Destination is path

rhel_zero_touch_user_copy_user_contents:
  - content: "{{ tower_lisence | from_json }}"
    resource: lisence.txt
    home: tower_lisence.txt

# We can use all (resource, home, path ) together or one, two of them.
----

Example of Sample Variables and Playbook
----------------------------------------

. Example-
+
[source=text]
----
[user@desktop ~]$ cat sample_variables.yml
rhel_zero_touch_user_name: bob

rhel_zero_touch_user_skel_files:
    - ./files/.vimrc

rhel_zero_touch_user_sudo_commands: "NOPASSWD: /bin/fdisk,/bin/ip"

rhel_zero_touch_user_ssh_config: ./templates/ssh_config.j2

rhel_zero_touch_user_resource_dir_name: lab_materials

----
+
[source=text]
----
[user@desktop ~]$ cat playbook.yml

- hosts: all
  roles:
   - control-user

[user@desktop ~]$ ansible-playbook playbook.yml -e sample_variables.yml

----

. Example-
+
[source=text]
----
[user@desktop ~]$ cat playbook.yml

- hosts: all
  roles:
   - role: control-user
     vars: 
       rhel_zero_touch_user_name: bob
       rhel_zero_touch_user_ssh_config: ./templates/ssh_config.j2
       rhel_zero_touch_user_copy_user_contents:
         - content: "{{ tower_license | from_json }}"
           home: "license.txt"
----

. Example-
+
[source=text]
----
[user@desktop ~]$ cat playbook.yml

- hosts: all
  tasks:
   - include_role: 
        name: control-user
     vars: 
       rhel_zero_touch_user_name: bob
       rhel_zero_touch_user_ssh_config: ./templates/ssh_config.j2
       rhel_zero_touch_user_copy_user_contents:
         - content: "{{ tower_license | from_json }}"
           home: "license.txt"
----


Author Information
------------------

* Author/owner:
** {author1}

* Alternative Contacts:
** {author2}
** {author3}

* Team:
** {team}
