---
- name: Get resource groups
  ansible.builtin.uri:
    url: "https://resource-controller.cloud.ibm.com/v2/resource_groups?account_id={{ sandbox_account_id }}"
    headers:
      Authorization: Bearer {{ auth_token }}
  register: r_resource_groups
  until: r_resource_groups.status == 200
  retries: 3
  delay: 10

- name: Set default resource group ID
  ansible.builtin.set_fact:
    sandbox_default_resource_group: "{{ r_resource_groups.json | to_json | from_json | json_query(_rg_query) }}"
  vars:
    _rg_query: "resources[?contains(keys(@), 'name')] | [?name=='Default'].id | [0]"

- name: Create containers-kubernetes policy
  ansible.builtin.uri:
    url: "https://iam.cloud.ibm.com/v1/policies"
    method: POST
    headers:
      Authorization: Bearer {{ auth_token }}
    status_code: 201
    body_format: json
    body:
      type: "access"
      description: "Sandbox - Containers-kubernetes policy"
      subjects:
        - attributes:
          - name: "access_group_id"
            value: "{{ sandbox_access_group }}"
      roles:
        - role_id: "crn:v1:bluemix:public:iam::::role:Administrator"
        - role_id: "crn:v1:bluemix:public:iam::::serviceRole:Writer"
      resources:
        - attributes:
          - name: "accountId"
            operator: "stringEquals"
            value: "{{ sandbox_account_id }}"
          - name: "serviceName"
            operator: "stringEquals"
            value: "containers-kubernetes"
  register: r_sandbox_kube_policy
  until: r_sandbox_kube_policy.status == 201
  retries: 3
  delay: 10

- name: Create cloud object storage policy
  ansible.builtin.uri:
    url: "https://iam.cloud.ibm.com/v1/policies"
    method: POST
    headers:
      Authorization: Bearer {{ auth_token }}
    status_code: 201
    body_format: json
    body:
      type: "access"
      description: "Sandbox - Cloud object storage policy"
      subjects:
        - attributes:
          - name: "access_group_id"
            value: "{{ sandbox_access_group }}"
      roles:
        - role_id: "crn:v1:bluemix:public:iam::::role:Administrator"
      resources:
        - attributes:
          - name: "accountId"
            operator: "stringEquals"
            value: "{{ sandbox_account_id }}"
          - name: "serviceName"
            operator: "stringEquals"
            value: "cloud-object-storage"
  register: r_sandbox_cos_policy
  until: r_sandbox_cos_policy.status == 201
  retries: 3
  delay: 10

- name: Create container registry policy
  ansible.builtin.uri:
    url: "https://iam.cloud.ibm.com/v1/policies"
    method: POST
    headers:
      Authorization: Bearer {{ auth_token }}
    status_code: 201
    body_format: json
    body:
      type: "access"
      description: "Sandbox - Container registry policy"
      subjects:
        - attributes:
          - name: "access_group_id"
            value: "{{ sandbox_access_group }}"
      roles:
        - role_id: "crn:v1:bluemix:public:iam::::role:Administrator"
      resources:
        - attributes:
          - name: "accountId"
            operator: "stringEquals"
            value: "{{ sandbox_account_id }}"
          - name: "serviceName"
            operator: "stringEquals"
            value: "container-registry"
  register: r_sandbox_registry_policy
  until: r_sandbox_registry_policy.status == 201
  retries: 3
  delay: 10

- name: Create iam-identity policy
  ansible.builtin.uri:
    url: "https://iam.cloud.ibm.com/v1/policies"
    method: POST
    headers:
      Authorization: Bearer {{ auth_token }}
    status_code: 201
    body_format: json
    body:
      type: "access"
      description: "Sandbox - IAM-identity policy"
      subjects:
        - attributes:
          - name: "access_group_id"
            value: "{{ sandbox_access_group }}"
      roles:
        - role_id: "crn:v1:bluemix:public:iam-identity::::serviceRole:ServiceIdCreator"
        - role_id: "crn:v1:bluemix:public:iam-identity::::serviceRole:UserApiKeyCreator"
        - role_id: "crn:v1:bluemix:public:iam::::role:Editor"
      resources:
        - attributes:
          - name: "accountId"
            operator: "stringEquals"
            value: "{{ sandbox_account_id }}"
          - name: "serviceName"
            operator: "stringEquals"
            value: "iam-identity"
  register: r_sandbox_iam_policy
  until: r_sandbox_iam_policy.status == 201
  retries: 3
  delay: 10

- name: Create cloudcerts policy
  ansible.builtin.uri:
    url: "https://iam.cloud.ibm.com/v1/policies"
    method: POST
    headers:
      Authorization: Bearer {{ auth_token }}
    status_code: 201
    body_format: json
    body:
      type: "access"
      description: "Sandbox - Cloudcerts policy"
      subjects:
        - attributes:
          - name: "access_group_id"
            value: "{{ sandbox_access_group }}"
      roles:
        - role_id: "crn:v1:bluemix:public:iam::::role:Editor"
        - role_id: "crn:v1:bluemix:public:iam::::serviceRole:Manager"
      resources:
        - attributes:
          - name: "accountId"
            operator: "stringEquals"
            value: "{{ sandbox_account_id }}"
          - name: "serviceName"
            operator: "stringEquals"
            value: "cloudcerts"
  register: r_sandbox_cloudcerts_policy
  until: r_sandbox_cloudcerts_policy.status == 201
  retries: 3
  delay: 10

- name: Create global catalog policy
  ansible.builtin.uri:
    url: "https://iam.cloud.ibm.com/v1/policies"
    method: POST
    headers:
      Authorization: Bearer {{ auth_token }}
    status_code: 201
    body_format: json
    body:
      type: "access"
      description: "Sandbox - Global catalog policy"
      subjects:
        - attributes:
          - name: "access_group_id"
            value: "{{ sandbox_access_group }}"
      roles:
        - role_id: "crn:v1:bluemix:public:iam::::role:Viewer"
      resources:
        - attributes:
          - name: "accountId"
            operator: "stringEquals"
            value: "{{ sandbox_account_id }}"
          - name: "serviceName"
            operator: "stringEquals"
            value: "globalcatalog"
  register: r_sandbox_catalog_policy
  until: r_sandbox_catalog_policy.status == 201
  retries: 3
  delay: 10

- name: Create kms policy
  ansible.builtin.uri:
    url: "https://iam.cloud.ibm.com/v1/policies"
    method: POST
    headers:
      Authorization: Bearer {{ auth_token }}
    status_code: 201
    body_format: json
    body:
      type: "access"
      description: "Sandbox - KMS policy"
      subjects:
        - attributes:
          - name: "access_group_id"
            value: "{{ sandbox_access_group }}"
      roles:
        - role_id: "crn:v1:bluemix:public:iam::::role:Administrator"
        - role_id: "crn:v1:bluemix:public:iam::::serviceRole:Manager"
        - role_id: "crn:v1:bluemix:public:kms::::serviceRole:KeyPurge"
      resources:
        - attributes:
          - name: "accountId"
            operator: "stringEquals"
            value: "{{ sandbox_account_id }}"
          - name: "serviceName"
            operator: "stringEquals"
            value: "kms"
  register: r_sandbox_kms_policy
  until: r_sandbox_kms_policy.status == 201
  retries: 3
  delay: 10

- name: Create default resource group policy
  ansible.builtin.uri:
    url: "https://iam.cloud.ibm.com/v1/policies"
    method: POST
    headers:
      Authorization: Bearer {{ auth_token }}
    status_code: 201
    body_format: json
    body:
      type: "access"
      description: "Sandbox - Default resource group policy"
      subjects:
        - attributes:
          - name: "access_group_id"
            value: "{{ sandbox_access_group }}"
      roles:
        - role_id: "crn:v1:bluemix:public:iam::::role:Viewer"
      resources:
        - attributes:
          - name: "accountId"
            operator: "stringEquals"
            value: "{{ sandbox_account_id }}"
          - name: "resourceType"
            operator: "stringEquals"
            value: "resource-group"
          - name: "resource"
            operator: "stringEquals"
            value: "{{ sandbox_default_resource_group }}"
  register: r_sandbox_rg_policy
  until: r_sandbox_rg_policy.status == 201
  retries: 3
  delay: 10

- name: Create schematics policy
  ansible.builtin.uri:
    url: "https://iam.cloud.ibm.com/v1/policies"
    method: POST
    headers:
      Authorization: Bearer {{ auth_token }}
    status_code: 201
    body_format: json
    body:
      type: "access"
      description: "Sandbox - Schematics policy"
      subjects:
        - attributes:
          - name: "access_group_id"
            value: "{{ sandbox_access_group }}"
      roles:
        - role_id: "crn:v1:bluemix:public:iam::::role:Administrator"
        - role_id: "crn:v1:bluemix:public:iam::::serviceRole:Manager"
      resources:
        - attributes:
          - name: "accountId"
            operator: "stringEquals"
            value: "{{ sandbox_account_id }}"
          - name: "serviceName"
            operator: "stringEquals"
            value: "schematics"
  register: r_sandbox_schematics_policy
  until: r_sandbox_schematics_policy.status == 201
  retries: 3
  delay: 10
