== About

The purpose of this software is to deploy pre-configured Red Hat Enterprise
Linux environments to various cloud hosting providers.  The ultimate goal is 
to provide a cross-cloud-provider Ansible-based framework for creating 
Red Hat Enterprise Linux environment configurations.  

== Contact

== Status

This software should be considered in early development stages.

* Support is currently being developed for the following cloud providers:
- Amazon AWS
- Oracle Ravello

It is currently possible to create deployment configurations targeting all 
supported providers, but we are still working on creating the necessary 
infrastructure for a write-once, run-anywhere workflow.  Some functionality 
will still require provider-specific configuration sections. We have done 
our best to isolate these sections into their own includeable files, which 
are called in the background by this tool.  These files are prefixed with 
the name of the cloud provider, and are called inside playbooks using the 
variable {{ cloud_provider }} in place of the prefix.

Most of the existing example configurations are compatible with Amazon AWS, 
and were written before Ravello support was added.  We are currently working 
on updating these examples to also support Ravello.  Likewise, some 
Ravello-based examples may not be fully compatible with Amazon AWS yet.  Each 
example in the  `configs` directory should contain information regarding 
cloud-provider compatibility status.
