== Contributing

If you're reading this, hopefully you are considering helping out with the Ansible Agnostic Deployer for Red Hat enablement.

Herein lies the contribution guidelines for helping out with this project. Do take the guidelines here literally, if you find issue with any of them or you see room for improvement, please let us know via a GitHub issue.

=== General rules

* The Ansible link:https://docs.ansible.com/ansible/latest/community/code_of_conduct.html[Code of Conduct] still applies.
* For git messages, branch names, ..., follow link:https://github.com/redhat-cop/agnosticd/blob/development/docs/git-style-guide.adoc[Git Style Guide].
* Should you wish to work on a completely new standard, GREAT, but please file an **issue** for tracking. In your Pull Request, specify `closes #NUM` to automatically close the issue when the PR is merged.
* To contribute, fork and make a pull request against the `development` branch.
*  Use link:https://asciidoctor.org/docs/asciidoc-writers-guide/[asciidoc] for documentation.
* Pull requests should only change one role, one config, or one role as applied to one config. There may be exceptions to this rule, but you must explain why a special exception should apply to a PR. Ask yourself, « Can this pull request be separeted in several smaller pull requests ? »
* Pull Request titles:
** Must start with `Add | Change | Fix | HOTFIX | Remove`
** followed by `config | workload | role | core | test | documentation`
** followed by the **name** of the config, workload, cloud provider, test or documentation
** followed by a short description
* Pull Request must be tested. Explain how you tested your change.
* Owner of any new role or config must be identified.
* If your Pull Request is not ready for review, open it as link:https://github.blog/2019-02-14-introducing-draft-pull-requests/[Draft]] or add `WIP` in the title.

=== Code Quality Rules

. a YAML `.yamllint` file should be added to every role and config when any substantial change is applied to the role or config, all new roles and configs must include a `.yamllint`.
. All tasks should be in YAML literal. No `foo=bar` inline notation. See <<yamlliteral,here>>.
. Indentation is 2 white-spaces.
. No in-line JSON format in Ansible
. No use of `command` or `shell` module when specific Ansible module exists to do the same, without justification
** If you have to, prefer `command` module to `shell` module when possible.
** Use `k8s` and `k8s_info` modules as much as possible and not `oc` command.
. All tasks must have names
. All plays must have names
. Roles must have README that document role variables.
** In README, list and describe common variables and secrets
. Roles must have `meta/main.yml` with author/contact information for support
. Be extra careful with external dependencies. Spot them (external github repos, libs, etc) and make sure the versions are **pinned** (use versions, git tags, or commit ID).
. In a role, ensure all variables names are prefixed with the role name to avoid name collisions with other roles.
. Do not add `ignore_errors` to a task without justification. Prefer use of `failed_when` if a condition is not an error.

=== About reviewing Pull Requests

. Do not merge a PR after reviewing unless explicitely asked for
** Approval and merging are different.
** Other people might be reviewing at the same time, or want to review that PR
** The PR might not be fully tested by the author yet
. If a specific person was requested for review, don't merge before that person reviewed, or before the request was canceled.
. Take your time. If your PR is merged tomorrow instead of today, is it a big deal ?
. Pull request for urgent critical fix for production must be titled and labeled accordingly.
+
.Example
----
HOTFIX config ansible-tower, update Windows AMI Ids for all regions

Those images have been deleted and are not available anymore.
This change, if applied, will update the AMI Ids in 'foobar' config for all region.

closes #1234

labels: BUG,HOTFIX
----
. Please use labels to categorize Pull Requests and Issues.


=== Ansible rules

[[yamlliteral]]

[source,xml]
----
# This
- name: Create a directory
  file:
      state: directory
      path: /tmp/deletethis

# Not this
- name: Create a directory
  file: state=directory path=/tmpt/deletethis
----

* Module arguments should be indented two spaces

[source,yml]
----
# This
- name: Create a directory
  file:
    state: directory
    path: /tmp/deletethis

# Not This
- name: Create a directory
  file:
      state: directory
      path: /tmp/deletethis
----

* There should be a single line break between tasks
* Tags should be in multi-line format and indented two spaces just like module arguments above

[source,xml]
----
# This
- name: "Check hosts.equiv"
  stat:
    path: /etc/hosts.equiv
  register: hosts_equiv_audit
  always_run: yes
  tags:
    - tag1
    - tag2


# Not This
- name: "Check hosts.equiv"
  stat:
      path: /etc/hosts.equiv
  register: hosts_equiv_audit
  always_run: yes
  tags: [tag1,tag2]
----

* Every task must be named and provide brief descriptions about the task being accomplished.

=== Git

Please follow the link:https://github.com/agis/git-style-guide[Git style guide].

Note: during the review process, you may add new commits to address review comments or change existing commits. However, before getting your PR merged, please squash commits to a minimum set of meaningful commits. This can be done directly in the github web UI.

If you've broken your work up into a set of sequential changes and each commit pass the tests on their own then that's fine. If you've got commits fixing typos or other problems introduced by previous commits in the same PR, then those should be squashed before merging.

=== Tips and links

* link:https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History[Rewriting Git History]
* link:http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html[Squashing commits with rebase]
* link:http://docs.ansible.com/ansible/community.html#community-code-of-conduct[Code of Conduct]
* link:https://docs.ansible.com/ansible/latest/community/code_of_conduct.html[Ansible Code of Conduct]
* link:https://github.com/redhat-cop/agnosticd/blob/development/docs/git-style-guide.adoc[Git Style Guide]
