image::https://travis-ci.org/redhat-cop/agnosticd.svg?branch=development[link="https://travis-ci.org/redhat-cop/agnosticd"]

=== Config on OpenShift (Workloads)

An _OpenShift Workload_ is simply a workload that is applied to an existing, 
 running, OpenShift cluster. For example if you wish to deploy 3Scale, Prometheus,
  or a MicroService application you can define it as a _Workload_ then simply and
   consistently deploy it with a single command to your OpenShift cluster.

This document assumes more than a passing familiarity with OpenShift but if
 you just want to "copy and hack" an existing Workload take a look at the 
link:../ansible/roles/ocp-workload-3scale-demo/readme.adoc[OpenShift 3Scale] workload.

Other OpenShift Workloads  link:../ansible/roles[here.] OpenShift Workloads all begin 
 `ocp-workload-` and follow the traditional structure of an Ansible Role.

==== Creating Workloads that install OpenShift operators

When creating a workload that installs an operator into a cluster you need to be aware of the fact that operators change quite frequently. To prevent your workload from breaking when a new release of the operator is released into the online catalog it is highly recommended to create an link:./Operator_Catalog_Snapshots.adoc[operator catalog snapshot].

==== How are _Workloads_ Deployed?

OpenShift _Workloads_ are deployed by applying an Ansible link:https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html[role] to an existing, running, cluster.

New and existing _workloads_ can be deployed, and developed, on any OpenShift
 cluster including locally on your laptop (`oc cluster` and `Minishift`).

Each _Workload_ Role includes a detailed `README.adoc` and they are applied by
 invoking the `ocp-workload` _config_.which is actually a Playbook and will apply
  the workload in the value `ocp_workload`. For example:

[source,bash]
----
ansible-playbook -i localhost, -c local ./configs/ocp-workloads/ocp-workload.yml \
                    -e ocp_workload=ocp-workload-3scale-multitenant \
                    -e ACTION=create \
                    -e subdomain_base=$SUBDOMAIN_BASE \
                    -e admin_username=$ADM_USERNAME
----
