== Deploying to Cloud Providers

A deployment is executed by running the `main.yml` playbook with Ansible.  
The following are variables are always necessary to be specified on the
command line:

`env_type`
  the name (not path) of a directory in 
  `ansible_agnostic_deployer/ansible/configs`

`cloud_provider`
  the name of the cloud provider to use

`ANSIBLE_REPO_PATH`
  full path to `ansible_agnostic_deployer/ansible`

Some environments in `configs` will require extra ansible variables to be 
passed on the command line.  Be sure to read the individual documentation 
for an environment configuration before attempting to deploy it.

In addition, credentials will need to provided for any cloud-provider you 
wish to use. Please see link:Credentials.adoc[Credentials] 
for details.

Example usage:

```
ansible-playbook main.yml \
  -e "env_type=hello_world" \
  -e "cloud_provider=ravello" \
  -e "ANSIBLE_REPO_PATH=/path/to/ansible_agnostic_deployer/ansible"
```

Once run, `main.yml` will execute a series of playbooks based on the command 
line arguments it was passed.  The resulting deployment is be considered to 
occur in two sequential phases, an infrastructure phase, and a software phase.

=== Infrastructure Deployment Phase

The infrastructure deployment phase configures the virtual hardware and base operating 
system.  The primary work which happens in this phase occurs in 
`ansible/cloud_providers/<cloud_provider>_infrastructure_deployment.yml`.

The `<cloud_provider>_infrastructure_deployment.yml` playbook makes API calls 
to the cloud provider to set up the virtual hardware and disk images as it is 
defined in the environment config's cloud template.  This template is located 
in `ansible_agnostic_deployer/ansible/configs/files/cloud_providers/
<cloud_provider>_cloud_template.j2`.

Cloud templates are provider specific, and a template must exist for each 
provider the environment is intended to be deployed to.  Information on 
creating cloud provider templates is located at link:Cloud-Templates.adoc[Cloud-Templates.adoc]. 
We are working on making this process more provider agnostic.  In the meantime, we 
have created some tools to assist in generating these templates, located in the
link:../ansible/tools[ansible_agnostic_deployer/ansible/tools] directory.  

It is possible to manually configure the infrastructure deployment phase 
before and after the `<cloud_provider>_infrastructure_deployment.yml` playbook 
is called by adding tasks to the `pre_infra.yml` and `post_infra.yml` playbooks 
respectively.  

The entire calling order of playbooks in the infrastructure phase is as follows:

```
configs/<env_type>/pre_infra.yml 
  Extra configuration tasks which occur before virtual hardware provisioning
    |
    V
cloud_providers/<cloud_provider>_infrastructure_deployment.yml 
  Provisions virtual hardware and registers hostnames with ansible
    |
    V
configs/<env_type>post_infra.yml
  Extra provisioning tasks which occur after the basic 
```

=== Software Deployment Phase

The software deployment phase installs and configures software in a deployed 
environment.  The principal playbook for this task will be selected from 
`ansible/software_playbooks`. 


It is possible to manually configure the software deployment phase before and 
after `software_playbooks/<software_to_install>.yml` is called by adding tasks 
to the `pre_software.yml` and `post_software.yml` playbooks respectively.  

The entire calling order of playbooks in the infrastructure phase is as follows:

```
configs/<env_type>/pre_software.yml 
  Extra environment-specific tasks which occur before software is installed
    |
    V
software_playbooks/<software_to_install>.yml
  Installs and configures a software environment
  (these are shared between environment configurations)
    |
    V
configs/<env_type>post_infra.yml
  Extra environment-specific configuration tasks 
  which occur after the software playbook is called
```

