== Directory Structure

This section discusses the subdirectories of 
`ansible_agnostic_deployer/ansible`.  

Unless otherwise stated, files contained within a given directory are not 
intended to be modified as part of general use.

==== cloud_providers 

Playbooks which interact with cloud provider APIs.

==== configs

Directory to store environment configurations.

Each subdirectory corresponds to a preconfigured environment type, and 
contains playbooks and config files used to deploy and configure the 
environment.

Ansible recognizes exactly one of these configs per deployment via the 
variable `{{ env_type }}`.  Exactly one `env_type` may be specified per 
deployment.  

Users are intended to copy and modify existing environment configs to suit 
their own needs, or write their own configs following the following minimum 
file structure:

```
<config_name>/
  pre_infra.yml
  post_infra.yml
  pre_software.yml
  post_software.yml
  env_vars.yml
  env_secret_vars.yml
  ssh_vars.yml
  files/
    cloud_providers/
      <cloud_provider>_cloud_template.j2
```
The purpose of each file will be discussed later in this document.

==== library

Python modules for communicating with cloud providers. 

==== roles

Ansible roles which are common among multiple configurations.

==== software_playbooks

Playbooks which install and configure a software environment.  Must be cross 
environment compatible provided hardware, software, and ansible hostvars 
dependencies are met.

Hardware, software, and ansible hostvars dependencies should be documented 
in each playbook.

Ansible recognises exactly one of these software playbooks per environment via 
the ansible variable `software_to_deploy`.

Users may utilise existing software playbooks, modify copies of existing 
software playbooks, or write their own software playbooks from scratch.

==== workdir

Empty directory which is used to store temporary files at runtime.

=== tools

Optional tools for generating environment configs and cloud provider templates.  
A tutorial for these tools can be found at link:Tools.adoc[Tools.adoc].


