
== Order OpenStack Project

In this step we will use link::labs.opentlc.com to order our OSP project so we can start working with AgnosticD and our OpenStack environment


=== Environment

Log in to link:https://labs.opentlc.com[OpenTLC^].
Go to *Services* -> *Catalogs* -> *OPENTLC OpenShift 4 Labs* -> *OpenShift 4 Install VM - OpenStack*.
Click *Order* -> *Submit*

You will receive three emails indicating the status of the environment and instructions for accessing the environment.
In the third email you receive all information you need to login to the client machine that would have the rest of required information.

NOTE: You can use the VM as your ansible host or copy the files over to your laptop and work locally.

=== Configure your environment for running OpenStack Ansible

. Install `virtualenv` and `pip3`:
----
# on Linux
sudo yum install python3-pip python-virtualenv -y
# on Mac
brew install python pyenv-virtualenv
----

. Create virtualenv environment and download python requirements:
----
virtualenv AgnosticD-OSP
source AgnosticD-OSP/bin/activate

# on Mac
pip3 install -r https://raw.githubusercontent.com/redhat-cop/agnosticd/development/ansible/configs/ocp4-disconnected-osp-lab/files/macos_requirements.txt

# on Linux
pip3 install -r https://raw.githubusercontent.com/redhat-cop/agnosticd/development/ansible/configs/ocp4-disconnected-osp-lab/files/openstack_requirements.txt
----

=== Getting your OpenStack Credentials

. Copy the `~/.config/openstack/clouds.yaml` file from the remote VM to your laptop
+
[source,bash]
----
mkdir -p ~/.config/openstack
scp shacharb-redhat.com@bastion.35eb.blue.osp.opentlc.com:~/.config/openstack/clouds.yaml ~/.config/openstack/clouds.yaml
# Enter password for your linux user specified in the email.
----

. Review your `~/.config/openstack/clouds.yaml`:
[source,bash]
----
cat ~/.config/openstack/clouds.yaml
clouds:
  35eb-project:
    auth:
      auth_url: "http://169.47.17.15:5000/v3"
      username: "35eb-user"
      project_name: "35eb-project"
      project_id: "1a79cf800ff94754bb495e2c1fd9d433"
      user_domain_name: "Default"
      password: "hXvT2sZuRK3Z"
    region_name: "regionOne"
    interface: "public"
    identity_api_version: 3
----

. Check that your credentials are working:
----
$ openstack --os-cloud=35eb-project servers list
+--------------------------------------+-----------+--------+------------------------------------------------+-------+---------+
| ID                                   | Name      | Status | Networks                                       | Image | Flavor  |
+--------------------------------------+-----------+--------+------------------------------------------------+-------+---------+
| 653fb842-6ce8-4eb0-a51a-dc0f3d5fb103 | bastion   | ACTIVE | 35eb-ocp-network=192.168.47.33, 169.47.183.214 |       | 2c2g30d |
| 689f4d44-df61-4088-a934-c1cca971f077 | utilityvm | ACTIVE | 35eb-ocp-network=192.168.47.35                 |       | 2c2g30d |
+--------------------------------------+-----------+--------+------------------------------------------------+-------+---------+
----

. Try to login to OpenStack UI: link:http://api.blue.osp.opentlc.com/dashboard/auth/login/[]

. Clone the AgnosticD repository:
----
git clone https://github.com/redhat-cop/agnosticd
----

. Create your secret.yml file oustide the repository, and edit it using the correct credentials based on your `clouds.yml` file
----
cat << EOF >> ./secret.yml
# Authenication for OpenStack in order to create the things
# BLUE
osp_auth_username: CHANGEME usually GUID-user
osp_auth_password: CHANGEME
osp_project_name: CHANGEME  usually GUID-project
osp_project_id: "CHANGEME"


# AFTER HERE, DON"T CHANGE
osp_auth_url: http://169.47.17.15:5000/v3
osp_auth_project_domain: default
osp_auth_user_domain: default

ddns_key_name: opentlc_osp_host
ddns_key_secret: 8P25dqCrFmEl/avbniFIM7Ldew6gqc26adtohOOEX7+TGEKJFYOFhBX3 Jw+xKf+mJxwDp30g/heL810IdCe9eQ==

# for three-tier-app only
own_repo_path: http://d3s3zqyaz8cp2d.cloudfront.net/repos/ocp/{{ osrelease }}

# Do not create PROJECT
osp_project_create: false
EOF
----

. Copy the sample_vars.yml file and call it my_vars.yml
----
cp agnosticd/ansible/configs/ocp-clientvm/sample_vars_osp.yml agnosticd/ansible/configs/ocp-clientvm/my_vars.yml
----

. Edit the `my_vars.yml` and change the `guid` value to something short and unique.

. Run the ansible-playbook command to deploy ocp-clientvm
----
cd agnosticd/
ansible-playbook ansible/main.yml -e @./ansible/configs/ocp-clientvm/my_vars.yml -e@../secret.yml
----

NOTE: If you are having python2 Vs. Python3 issues, Add `/usr/bin/python3.6` before the ansible-playbook command. For example: `/usr/bin/python3.6 ansible-playbook ansible/main.yml -e @./ansible/configs/ocp-clientvm/my_vars.yml -e@../secret.yml`


. Check that the VM was installed and ssh into the box using the created key
----
openstack --os-cloud=35eb-project server list
ssh -i /tmp/output_dir/${GUID}key cloud-user@169.47.183.41
----

=== Clean up

. Destroy the deployment:
----

ansible-playbook ansible/configs/ocp-clientvm/destroy_env.yml -e @./ansible/configs/ocp-clientvm/my_vars.yml -e@../secret.yml

----
