
== Setting up for OpenStack deployments

In this document we will explain how one could setup their laptop for AgnosticD deployment with OpenStack.

If you are a Red Hatter, you can use link::labs.opentlc.com to request access to our OpenStack cluster.
. Log in to link:https://labs.opentlc.com[https://labs.opentlc.com] using your opentlc user.
. Go to *Services* -> *Catalogs* -> *OPENTLC OpenShift 4 Labs* -> *OpenShift 4 Install VM - OpenStack*.
. Click *Order* -> *Submit*

NOTE: You will receive three emails indicating the status of the environment and instructions for accessing the environment.
In the third email you receive all information you need to login to the client machine that would have the rest of required information.

NOTE: You can use the VM as your ansible host or copy the files over to your laptop and work locally.

=== Configure your environment for running OpenStack Ansible

. Install `virtualenv` and `pip3` (On your laptop or on the clientVM):
+
[source, shell]
----
# on Linux
$ sudo yum install python3-pip python-virtualenv -y
# on Mac
$ brew install python pyenv-virtualenv
----

. Create virtualenv environment and download python requirements:
+
[source, shell]
----
$ virtualenv AgnosticD-OSP
$ source AgnosticD-OSP/bin/activate

# on Mac
$ pip3 install -r https://raw.githubusercontent.com/redhat-cop/agnosticd/development/ansible/configs/ocp4-disconnected-osp-lab/files/macos_requirements.txt

# on Linux
$ pip3 install -r https://raw.githubusercontent.com/redhat-cop/agnosticd/development/ansible/configs/ocp4-disconnected-osp-lab/files/openstack_requirements.txt
----

=== Getting your OpenStack Credentials

. Copy the `~/.config/openstack/clouds.yaml` file from the remote VM to your laptop (Use your user name and GUID in the commands below)
+
[source,bash]
----
$ mkdir -p ~/.config/openstack
$ scp shacharb-redhat.com@bastion.GUID.blue.osp.opentlc.com:~/.config/openstack/clouds.yaml ~/.config/openstack/clouds.yaml
# Enter password for your linux user specified in the email.
----

. Review your `~/.config/openstack/clouds.yaml`:
+
[source,bash]
----
cat ~/.config/openstack/clouds.yaml
clouds:
  35eb-project:
    auth:
      auth_url: "http://169.47.17.15:5000/v3"
      username: "35eb-user"
      project_name: "35eb-project"
      project_id: "1a79cf800ff94754bb495e2c1fd9d433"
      user_domain_name: "Default"
      password: "YOUR_TEMP_PASSWORD"
    region_name: "regionOne"
    interface: "public"
    identity_api_version: 3
----

. Check that your credentials are working:
+
[source,bash]
----
$ openstack --os-cloud=GUID-project server list
+--------------------------------------+-----------+--------+------------------------------------------------+-------+---------+
| ID                                   | Name      | Status | Networks                                       | Image | Flavor  |
+--------------------------------------+-----------+--------+------------------------------------------------+-------+---------+
| 653fb842-6ce8-4eb0-a51a-dc0f3d5fb103 | bastion   | ACTIVE | 35eb-ocp-network=192.168.47.33, 169.47.183.214 |       | 2c2g30d |
| 689f4d44-df61-4088-a934-c1cca971f077 | utilityvm | ACTIVE | 35eb-ocp-network=192.168.47.35                 |       | 2c2g30d |
+--------------------------------------+-----------+--------+------------------------------------------------+-------+---------+
----

. Try to login to OpenStack UI: link:http://api.blue.osp.opentlc.com/dashboard/auth/login/[]. You must use the credentials from `.config/openstack/clouds.yaml` to login to the UI. 

=== Setting up AgnosticD and your development environment

. Clone the AgnosticD repository:
+
[source,bash]
----
git clone https://github.com/redhat-cop/agnosticd
----

. Create your `secret.yml` file *oustide the repository*, and edit it using the correct credentials based on your `clouds.yml` file:
+
[source,bash]
----
cat << EOF >> ~/secret.yml
# Authenication for OpenStack in order to create the things
# BLUE
osp_auth_username: CHANGEME
osp_auth_password: CHANGEME
osp_project_name: CHANGEME
osp_project_id: "CHANGEME"


osp_auth_url: http://169.47.17.15:5000/v3
osp_auth_project_domain: default
osp_auth_user_domain: default

ddns_key_name: opentlc_osp_host
ddns_key_secret: PROVIDED_BY_ADMIN

# for three-tier-app only
own_repo_path: PROVIDED_BY_ADMIN

# Do not create PROJECT
osp_project_create: false
EOF
----

. Copy the `sample_vars.yml` file and call it `my_vars.yml`
+
[source,bash]
----
cp agnosticd/ansible/configs/ocp-clientvm/sample_vars_osp.yml agnosticd/ansible/configs/ocp-clientvm/my_vars.yml
----

. Edit the `my_vars.yml` and change the `guid` value to something short and unique.

. Run the ansible-playbook command to deploy ocp-clientvm
+
[source,bash]
----
cd agnosticd/
ansible-playbook ansible/main.yml -e @./ansible/configs/ocp-clientvm/my_vars.yml -e@~/secret.yml
----
+
NOTE: If you are having python2 Vs. Python3 issues, Add `/usr/bin/python3.6` before the ansible-playbook command. For example: `/usr/bin/python3.6 ansible-playbook ansible/main.yml -e @./ansible/configs/ocp-clientvm/my_vars.yml -e@../secret.yml`


. Check that the VM was installed and ssh into the box using the created key
+
[source,bash]
----
openstack --os-cloud=35eb-project server list
ssh -i /tmp/output_dir/${GUID}key cloud-user@169.47.183.41
----

=== Clean up

. Destroy the deployment:
+
[source,bash]
----

ansible-playbook configs/ocp-clientvm/destroy_env.yml -e @configs/ocp-clientvm/sample_vars_osp.yml -e @my_secret.yml

----
