= SSH keys and access =

This section describes how SSH keys are managed in agnosticd.

== Scope ==

Here is the list of agnosticd cloud providers that follow this workflow:

* ec2

Long-term, we want all cloud providers to comply.

== Workflow ==

. PRE-INFRA cloud-agnostic role `create_ssh_provision_key` generates a per-environment, for infra, local SSH key
** output file: private and public key in output_dir
** output facts:
*** `ssh_provision_key_name`        ex: `ssh_provision_{{ guid }}`
*** `ssh_provision_key_path`        ex: `/tmp/output_dir/ssh_provision_{{ guid }}`
*** `ssh_provision_pubkey_path`     ex: `/tmp/output_dir/ssh_provision_{{ guid }}.pub`
*** `ssh_provision_pubkey_content`
** Role is idempotent and can be used to only set the facts
. INFRA role `infra-{{ cloud_provider }}-ssh-key` to create the keypair in the cloud provider
. INFRA in the cloud providers, use the key previously created to provision the infra
. POST-INFRA generate ssh configuration using the `provision_ssh_key`
. POST-INFRA cloud-agnosticd post-infra role to update the authorized_keys on all hosts
** Input var:  `ssh_authorized_keys`: list of content pub keys and key options. That's where we set the content of the *public* keys for additional access (admins, backdoor key, ...).
+
[source,yaml]
.example `ssh_authorized_keys` (preferred)
----
ssh_authorized_keys:
  - key: ssh-rsa ...
  - key: ssh-rsa ...
    key_options: no-port-forwarding,from="10.0.0.1"
  - key: https://github.com/fridim.keys
----
*** `all_ssh_authorized_keys` list is also supported (backward-compatible)
+
[source,yaml]
.example `all_ssh_authorized_keys`  (legacy only)
----
all_ssh_authorized_keys:
  - ssh-rsa ...
  - ssh-rsa ...
  - https://github.com/fridim.keys
----
. DESTROY role `infra-{{ cloud_provider }}-ssh-key` to delete the keypair in the cloud provider

== Bring your own provision key ==
In some cases the SSH key generation described above is not working well (e.g., the key pair can be lost if not stored at persistent storage and destroy job will fail).
It is possible to specify existed SSH key which will be used for the environment provisioning and destroy by setting following variables:

* `ssh_provision_key_path`
* `ssh_provision_key_name`
* `ssh_provision_pubkey_content` (optional)
+
[source,yaml]
.example setting `ssh_privision_*` variables
----
ssh_provision_key_name: "my_private_ssh_key.pem"
ssh_provision_key_path: "/home/account/.ssh/{{ ssh_provision_key_name }}"
ssh_provision_pubkey_content: ssh-rsa AAAAB3NzaC1 ...rest of the key... JjQ==
----

== Roles ==

* `create_ssh_provision_key`
+
Generate locally a private SSH key, in `output_dir`. The resulting public key is used to provision the instances
* `infra-{{ cloud_provider }}-ssh-key`
+
Create the key resource in the cloud provider so it can be attached to instances
* `infra-common-ssh-config-generate`
+
Generate the SSH configuration in `output_dir`
* `ssh_authorized_keys`
+
Populate `authorized_keys` files on the instances for additional access.
