= SSH keys and access =

Workflow:

. PRE-INFRA cloud-agnostic role `create_ssh_provision_key` generates a per-environment, for infra, local SSH key
** output file: private and public key in output_dir
** output facts:
*** `ssh_provision_key_name`        ex: `ssh_provision_{{ guid }}`
*** `ssh_provision_key_path`        ex: `/tmp/output_dir/ssh_provision_{{ guid }}`
*** `ssh_provision_pubkey_path`     ex: `/tmp/output_dir/ssh_provision_{{ guid }}.pub`
*** `ssh_provision_pubkey_content`
. INFRA role `infra-{{ cloud_provider }}-ssh-key` to create the keypair in the cloud provider
. INFRA in the cloud providers, use the key previously created to provision the infra
. POST-INFRA generate ssh configuration using the `provision_ssh_key`
. POST-INFRA cloud-agnosticd post-infra role to update the authorized_keys on all hosts
** Input var:  `all_ssh_authorized_keys` that is a list of content pub keys. That's where we would put the content of the *public* key for admin_backdoor_key
. DESTROY role `infra-{{ cloud_provider }}-ssh-key` to delete the keypair in the cloud provider
