---
apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  creationTimestamp: null
  name: {{ hcp_extra_nodepool.name }}
  namespace: {{ hcp_namespace }}
spec:
  arch: amd64
  clusterName: hcp-{{ guid }}
  management:
    autoRepair: false
    upgradeType: Replace
  nodeDrainTimeout: 0s
  platform:
    aws:
      instanceProfile: hcp-{{ guid }}-worker
      instanceType: {{ hcp_extra_nodepool.instance_type }}
      rootVolume:
        size: 120
        type: gp3
      subnet:
        id: {{ aws_subnet_id }}
    type: AWS
  release:
    image: {{ ocp_release_image }}
{% if hcp_extra_nodepool.autoscale | default(false) %}
  autoScaling:
    min: {{ hcp_extra_nodepool.min_count | int }}
    max: {{ hcp_extra_nodepool.max_count | int }}
{% else %}
  replicas: {{ hcp_extra_nodepool.count | int }}
{% endif %}
