---
apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  creationTimestamp: null
  name: hcp-{{ guid }}
  namespace: {{ namespace }}
spec:
  autoscaling: {}
  configuration:
    apiServer:
      servingCerts:
        namedCertificates:
          - servingCertificate:
              name: oauth-{{ guid }}
            names:
              - oauth-{{ namespace }}-hcp-{{ guid }}.{{ sandbox_hcp.sandbox_openshift_apps_domain }}
{% if hcp_authentication | default('none') == "htpasswd" %}
    oauth:
      identityProviders:
      - name: democreds
        type: HTPasswd
        htpasswd:
          fileData:
            name: htpasswd-{{ guid }}
        mappingMethod: claim
      templates:
        error:
          name: ""
        login:
          name: ""
        providerSelection:
          name: ""
      tokenConfig: {}
{% endif %}

  controllerAvailabilityPolicy: {{ hcp_controller_availability_policy }}
  dns:
    baseDomain: {{ aws_sandbox_provision_data.aws_route53_domain[1:] }} 
    privateZoneID: {{ aws_route53_private_zone_id }}
    publicZoneID: {{ aws_route53_public_zone_id }}
  etcd:
    managed:
      storage:
        persistentVolume:
          size: {{ hcp_etcd_pvc_size }}
        type: PersistentVolume
    managementType: Managed
  fips: false
  infraID: hcp-{{ guid }}-{{ lookup('community.general.random_string', upper=false, numbers=false, special=false) }}
  issuerURL: "https://oidc-{{ sandbox_hcp.sandbox_openshift_cluster }}.s3.us-east-1.amazonaws.com/hcp-{{ guid }}"
  networking:
    clusterNetwork:
    - cidr: 10.132.0.0/14
    networkType: OVNKubernetes
    serviceNetwork:
    - cidr: 172.31.0.0/16
  olmCatalogPlacement: management
  platform:
    aws:
      cloudProviderConfig:
        subnet:
          id: "{{ aws_subnet_id }}"
        vpc: "{{ aws_vpc_id }}"
        zone: "{{ aws_sandbox_provision_data.aws_default_region }}a" # FIXME
      endpointAccess: Public
      multiArch: false
      region: "{{ aws_sandbox_provision_data.aws_default_region }}"
      rolesRef:
        controlPlaneOperatorARN: arn:aws:iam::{{ aws_account_id }}:role/hcp-{{ guid }}-control-plane-operator
        imageRegistryARN: arn:aws:iam::{{ aws_account_id }}:role/hcp-{{ guid }}-openshift-image-registry
        ingressARN: arn:aws:iam::{{ aws_account_id }}:role/hcp-{{ guid }}-openshift-ingress
        kubeCloudControllerARN: arn:aws:iam::{{ aws_account_id }}:role/hcp-{{ guid }}-cloud-controller
        networkARN: arn:aws:iam::{{ aws_account_id }}:role/hcp-{{ guid }}-cloud-network-config-controller
        nodePoolManagementARN: arn:aws:iam::{{ aws_account_id }}:role/hcp-{{ guid }}-node-pool
        storageARN: arn:aws:iam::{{ aws_account_id }}:role/hcp-{{ guid }}-aws-ebs-csi-driver-controller
    type: AWS
  pullSecret:
    name: hcp-{{ guid }}-pull-secret
  release:
    image: {{ ocp_release_image }}
  services:
  - service: APIServer
    servicePublishingStrategy:
      type: LoadBalancer
  - service: Ignition
    servicePublishingStrategy:
      type: Route
  - service: Konnectivity
    servicePublishingStrategy:
      type: Route
  - service: OAuthServer
    servicePublishingStrategy:
      type: Route
  sshKey: {}
