---
apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  creationTimestamp: null
  name: hcp-{{ guid }}
  namespace: {{ namespace }}
spec:
  arch: amd64
  clusterName: hcp-{{ guid }}
  management:
    autoRepair: false
    upgradeType: Replace
  nodeDrainTimeout: 0s
  platform:
    aws:
      instanceProfile: hcp-{{ guid }}-worker
      instanceType: m5.large
      rootVolume:
        size: 120
        type: gp3
      subnet:
        id: {{ aws_subnet_id }} # TODO: subnet-0c98d423bcf63da68
    type: AWS
  release:
    image: {{ ocp_release_image }}
{% if hcp_worker_autoscale %}
  autoScaling:
    min: {{ hcp_worker_instance_min_count | int }}
    max: {{ hcp_worker_instance_max_count | int }}
{% else %}
  replicas: {{ hcp_worker_instance_count | int }}
{% endif %}
