---
- name: Create SSH Public Key pair
  register: ibmcloud_ssh_public_key
  ibm.cloudcollection.ibm_is_ssh_key:
    name: "{{ ibmcloud_resource_group_name }}-ssh-key"
    resource_group: "{{ r_ibmcloud_resource_group_id }}"
    public_key: "{{ ssh_provision_pubkey_content }}"
    region: "{{ ibmcloud_region }}"

- name: Create SSH Public Key pair using ibmcloud CLI
  command: >-
    ibmcloud is key-create {{ ibmcloud_resource_group_name }}-ssh-key
    --resource-group-name {{ ibmcloud_resource_group_name }}
    --public-key "{{ ssh_provision_pubkey_content }}"

  register: r_ibmcloud_ssh_public_key
  until: r_ibmcloud_ssh_public_key is succeeded
  failed_when: >-
    r_ibmcloud_ssh_public_key.rc != 0
    and 'already exists' not in r_ibmcloud_ssh_public_key.stderr
  changed_when: >-
    r_ibmcloud_ssh_public_key.rc == 0
