= Base ROSA
== Config Description

The following config includes:

* One bastion host for ROSA installation
* SSH access setup
* Base ROSA config gives option to select number of worker nodes and instance type. 

== Review the `default_vars.yml` variable file

* This file link:./default_vars.yml[./default_vars.yml] contains all the variables you need to define to control the deployment of your environment.  These are the defaults.

* Override the defaults for your environment by creating your own myenvironment-variables.yml file, as below.

* To update worker node machine type check `rosa_machine_type: "m5.2xlarge"` variable.

== AWS Prereqs for ROSA

Please see https://docs.openshift.com/rosa/rosa_getting_started/rosa-aws-prereqs.html for a list of pre-reqs for the target AWS account.

== Secrets

You will need to define the `rosa_token` variable in order to deploy this config.  Add this variable to your secret file.

This token can be created and downloaded from https://cloud.redhat.com/openshift/token/rosa

It should look like:

[source,yaml]
----
rosa_token: "eyJ<..REDACTED..>dz8"
----

== Running Ansible Playbook

=== Running Playbook With Environment and Secrets files

You can create yaml files of your desired configs and secrets and execute them:

`ansible-playbook ansible/main.yaml -e @myenvironment-variables.yml  -e@my-secrets.yml`

=== To Delete an environment

Run the `destroy_env.yml` playbook.

Ex: `ansible-playbook ansible/configs/rosa/destroy_env.yml -e @myenvironment-variables.yml  -e@my-secrets.yml`

The teardown process is roughly as follows:
* Delete sandbox

== Software stages in config provide

* Install AWS CLI on bastion
* Install ROSA CLI on bastion
* Optionally run ROSA installer (default is to run installer)

== Developer
* Tyrell Reddy
* Mitesh Sharma
* Ritesh Shah
* Prakhar Srivastava