#!/bin/bash
# Create an output file
touch /root/post-run.log
# configure rhel account
usermod -aG wheel rhel
echo redhat | passwd --stdin rhel


# setup webui
# Create a done file to signal we have finished
touch /root/post-run.log.done