= ocp4_workload_example_dedicated_cluster - Example Workload Role for a Dedicated Cluster

== Preparation to Use This Role

=== Get Access to Your Dedicated Cluster

This example role assumes you'll be deployiung your own cluster and preparing it for a demo or workshop with a series of workloads.

There should be a catalog item in CloudForms to lauch your dedicated cluster.  You'll then deploy the suggested roles to prepare the cluster.  Finally, you'll deploy this role to deploy sample applications for your users to explore.

== Description

This role builds upon `ocp4_workshop_example_shared_cluster` to prepare a dedicated cluster and deploy the sample application for multiple users.

Admin access to the cluster is required.

This role is meant to be run after serveral important depenendent roles, including setup of
* Let's Encrypt certificates
* htpasswd authentication for multiple users
* a project request template
See the commandline and AgnosticV configs at the end of this document for details.

Workload roles can be executed several different ways: on the command line from config files, as part of an AgnosticV configuration, or through CloudForms and any other catalog.

The role is meant to be run after the deployment of the AgnosticD env_config: `ocp4-cluster`. In addition, it can also work against any pre-deployed dedicated OpenShift cluster with `system:admin` access, as long as the appropriate secrets are supplied.

When removed by the deployer (CloudForms or command line), this role deletes resources it created.

Sample AgnosticV configs are at the end of this file.

For more information on dedicated clusters and setting up self-provisioner capable users and quotas on your own dedicated clusters, see "ocp4_workload_shared_cluster_access"

== Role overview

* This is a working simple role that can be used to develop new OpenShift 4 workload roles on dedicated clusters. It consists of the following tasks files:

=== Task Files

** Tasks: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an environment for the workload deployment
*** Debug task will print out: `pre_workload Tasks completed successfully.`

** Tasks: link:./tasks/workload.yml[workload.yml] - Used to deploy the actual workload, i.e, 3scale, Mobile, some Demo or OpenShift customization
*** Read this role for our recommended best practices for working with ansible and OpenShift
*** This role creates an OpenShift project, deploys a simple application, and notifies on success or failure.
*** Debug task will print out: `workload Tasks completed successfully.`

** Tasks: link:./tasks/post_workload.yml[post_workload.yml] - Used to configure the workload after deployment
*** This role doesn't do anything
*** Debug task will print out: `post_workload Tasks completed successfully.`

** Tasks: link:./tasks/remove_workload.yml[remove_workload.yml] - Used to delete the workload
*** This role deletes the OpenShift projected created for the user.
*** Debug task will print out: `remove_workload Tasks completed successfully.`

=== The defaults variable file

* This file ./defaults/main.yml contains all the variables you need to define to control the deployment of your workload.

* The variable ocp_username is mandatory to assign the workload to the correct OpenShift user.

* A variable silent=True can be passed to suppress debug messages.

* You can override any of these default values by adding -e "variable_name=variable_value" to the command line

* Your deployer will override any of these variables (usually CloudForms)

* Note that this role uses long-name scoped workload parameters. Example: ocp4_workload_example_shared_cluster_project_name: my-project-name, not just project_name

=== Understand how paremeters to your workload should be specified

* Please use long-name scope parameters for your workload.
* Ansible lacks robust variable scoping.
* For parameters passed into your workload role, prepend the role name.
* For parameters shared across workloads, have a catch-all name that applies to your goal.
** For example, parameters named `ocp4_workload_example_dedicated_cluster_*` would apply to workloads `ocp4-workload-example_dedicated_cluster` itself *and* `ocp4_workload_example_dedicated_cluster_minio`.

=== Provide info to users

To provide information to users, use the agnosticd_user_info module built into AgnosticD.  You'll also see this information in the agnosticd workload logs.

.Using the `agnosticd_user_info` module
----
  - name: Report URL for web console
    agnosticd_user_info:
      msg: "OpenShift Web Console: {{ _openshift_console_url }}
----

In RHPDS and OpenTLC, CloudForms will pick up this information and email it to your user.

More info about the `agnosticd_user_info` module here: link:../../../docs/User_Info.adoc

== Suggested Roles for Dedicatd Clusters

=== Let's Encrypt for Dedicated Clusters

Install Let's Encrypt Certificates into your dedicated cluster so users don't have to bother with self-signed certs.

https://github.com/redhat-cop/agnosticd/tree/development/ansible/roles_ocp_workloads/ocp4_workload_le_certificates

=== User Authentication on Dedicated Clusters

The `ocp4_workload_authentication` role allows you to setup the authentication system that makes sense for you:
. link:https://github.com/redhat-cop/agnosticd/blob/development/ansible/roles_ocp_workloads/ocp4_workload_authentication/defaults/main.yml

=== Project Request Template for Dedicated Clusters

Your users will likely be creating their own projects to the cluster.  Use the following role to setup a Project Request Template to set project-scoped limit ranges, network policies, service accounts and rolebindings.

https://github.com/redhat-cop/agnosticd/tree/development/ansible/roles_ocp_workloads/ocp4_workload_project_request_template

== Deploy a Workload from the command line with the `ocp4-workload` playbook [Mostly for testing]

After you have deployed all the preparatory workloads for your dedicated cluster, deploy this sample application and give your users access to them.

. If your workload uses parameters create a `<role name>_vars.yaml` input file.
+
.ocp4_workload_example_dedicated_cluster_vars.yaml
[source,yaml]
----
# You can set any variable
silent: true

# Set a variable scoped to the role.  In this case, a variable for a project name to be created.
ocp4_workload_example_dedicated_cluster_project_name: "sample-application-{{ ocp_username }}"
----

. Set up Environment Variables for the bastion you want to run this role on.
+
[source,bash]
----
TARGET_HOST="bastion.dev.openshift.opentlc.com"
OCP_USERNAME="wkulhane-redhat.com"
ANSIBLE_USER="ec2-user" # Will become OpenTLC username
WORKLOAD="ocp4_workload_example_dedicated_cluster"
GUID="1001"
----

. Finally run the workload passing the input files as parameters:
+
[source,sh]
----
# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=${ANSIBLE_USER}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"guid=${GUID}" \
    -e"ACTION=create" \
    -e @./ocp4_workload_example_dedicated_cluster_vars.yaml \
    -e @./ocp4_workload_example_dedicated_cluster_secrets.yaml
----
+

=== To Delete a Workload from the CLI

----
TARGET_HOST="bastion.dev.openshift.opentlc.com"
OCP_USERNAME="wkulhane-redhat.com"
ANSIBLE_USER="ec2-user" # Will become OpenTLC username
WORKLOAD="ocp_workload_example_dedicated_cluster"
GUID="1001"

# a TARGET_HOST is specified in the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=ec2-user" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"guid=${GUID}" \
    -e"ACTION=remove" \
    -e @./ocp_workload_example_dedicated_cluster_vars.yaml \
    -e @./ocp_workload_example_dedicated_cluster_secrets.yaml
----

== Deploying a Workload with AgnosticV from the Command Line

When creating a configuration in AgnosticV that includes the deployment of the workload you can specify the variables straight in the AgnosticV config.
AgnosticV configs are usually created by combining a `common.yaml` file with either `dev.yaml`, `test.yaml` or `prod.yaml`.
You can specify different variables in each of these files.
For example you could have common values defined in the `common.yaml` file and then specific values overriding the common ones for development or production environments in `dev.yaml` or `prod.yaml`.

AgnosticV merges the definition files starting with `common.yaml` and then adding/overwriting what comes from either `dev.yaml` or `prod.yaml`.

Example of a simple AgnosticV config:

.common.yaml
[source,yaml]
----
# --- Example Shared Cluster Workload Deployment for RPDS
# --- System: RHPDS
# --- Catalog: OpenShift Demos
# --- Catalog Item: Quay 3 on OpenShift 4

# --- Platform
platform: rhpds

# --- Cloud Provider
cloud_provider: none

# --- Config
env_type: ocp4-cluster
ocp_workload: ocp4_workload_example_dedicated_cluster
# If your workload requires sudo, additional privileges are required.
# For now, workload must be run as ec2-user (or cloud-user on OpenStack)
ansible_user: ec2-user
ansible_ssh_private_key_file: /home/opentlc-mgr/.ssh/opentlc_admin_backdoor.pem

# --- Ensure the workload prints the correct statements for CloudForms to realize it finished
workload_shared_deployment: true

# --- Workload Configuration
ocp4_workload_example_dedicated_cluster_project_name: "ocp4-workload-example-{{ ocp_username }}"

# --- AgnosticV Meta variables
agnosticv_meta:
  params_to_variables:
    user: ocp_username
  secrets:
  # A secret file that might hold something your role needs
  - ocp4_workload_example_dedicated_cluster_secrets.yml
----

.dev.yaml
[source,yaml]
----
purpose: development

# --- Use specific variable values for Development
target_host: bastion.dev4.openshift.opentlc.com

# --- Workload Configuration Overrides
ocp4_workload_example_dedicated_cluster_project_name:  "ocp4-workload-example-{{ ocp_username }}-dev"
----

.prod.yaml
[source,yaml]
----
---
purpose: production

# --- Use specific variable values for Production
target_host: bastion.rhpds.openshift.opentlc.com

# --- Workload Configuration Overrides
ocp4_workload_example_dedicated_cluster_project_name:  "ocp4-workload-example-{{ ocp_username }}-prod"

# --- AgnosticV Meta variables
agnosticv_meta:
  agnosticd_git_tag_prefix: ocp4-workload-example-dedicated-cluster-prod
----

== Further Learning - More Complex Examples

If you want to see more examples of how this works in a real world workload the following workloads already use this approach:

* ocp4_workload_authentication
* ocp4_workload_machinesets
* ocp4_workload_logging
* ocp4_workload_quay_operator

== AgnosticV Samples

.AgnosticV common.yaml
----
---
# Platform
platform: RHPDS

# Config
env_type: ocp4-workshop
install_ocp4: true
software_to_deploy: none
ocp4_installer_version: "4.3.21"
install_lets_encrypt_certificates: true
enable_workshops_catalog: true
# ignore_self_provisioners: true
install_ipa_client: false
run_ocp_diagnostics: false
key_name: ocpkey
# install_ipa_client and ipa_host_password passed from cloudforms

# test user base var in agnosticd
# ocp4_workload_integreatly_user_base: 0

# Integreatly-specific config
ocp4_workload_integreatly_user_count: 50
ocp4_workload_integreatly_user_base: evals
ocp4_workload_integreatly_admin_username: admin
ocp4_workload_integreatly_user_password: openshift
ocp4_workload_integreatly_dedicated_admin_user_password: openshift
ocp4_workload_integreatly_admin_user_password: openshift
ocp4_workload_authentication_htpasswd_admin_password: openshift

# subdomain_base_suffix and HostedZoneIdcome from the account
#subdomain_base_suffix: .open.redhat.com
#HostedZoneId: ZCRCH49OF7I9E

# emergency fix for account issue:
subdomain_base_suffix: .example.opentlc.com
HostedZoneId: Z3IHLWJZOU9SRT

# Repos
ig_version: 2.2.0
osrelease: 4.3.0
# osrelease and ig_version passed from cloudforms dialog parameter
repo_method: file

# OCP Authentication
admin_user: admin
ocp4_workload_authentication_idm_type: htpasswd
ocp4_workload_authentication_htpasswd_user_base: evals
ocp4_workload_authentication_htpasswd_user_password: openshift
ocp4_workload_authentication_htpasswd_user_count: 50
ocp4_workload_authentication_admin_user: admin
ocp4_workload_authentication_admin_user_password: r3dh4t1!
ocp4_workload_authentication_remove_kubeadmin: true

infra_workloads:
  - ocp4_workload_le_certificates
  - ocp4_workload_integreatly_minio
  - ocp4_workload_authentication
  - ocp4_workload_integreatly

agnosticv_meta:
  virtualenv: aws-ansible-2.9
  params_to_variables:
    username: student_name
    letsencrypt: install_lets_encrypt_certificates
    infra_workloads: infra_workloads
    student_workloads: student_workloads
  secrets:
    - gpte
    - ocp4_token
----

.AgnosticV dev.yaml
----

---
lets_encrypt_production: false
run_ocp_diagnostics: false
cloudformation_retries: 0

#"AWS instance types"
bastion_instance_type: t3.medium
_infra_node_instance_type: m5.4xlarge
_infra_node_replicas: 3
clientvm_instance_type: t2.medium
clientvm_instance_count: 1
master_instance_type: m5.2xlarge
master_instance_count: 3
worker_instance_type: m4.2xlarge
worker_instance_count: 10
support_instance_type: t3.medium

agnosticv_meta:
  idle_after_deploy: 10
  idle_after_start: 10
  params_to_variables:
    nodecount: worker_instance_count_ignored
----

.AgnosticV test.yaml
----

---
lets_encrypt_production: true
run_ocp_diagnostics: false
cloudformation_retries: 0

#"AWS instance types"
bastion_instance_type: t3.medium
_infra_node_instance_type: m5.4xlarge
_infra_node_replicas: 3
clientvm_instance_type: t2.medium
clientvm_instance_count: 1
master_instance_type: m5.2xlarge
master_instance_count: 3
worker_instance_type: m4.2xlarge
worker_instance_count: 5
support_instance_type: t3.medium

agnosticv_meta:
  idle_after_deploy: 10
  idle_after_start: 10
  params_to_variables:
    nodecount: worker_instance_count_ignored
  agnosticd_git_tag_prefix: ocp4-workload-integreatly-test
----

.AgnosticV prod.yaml
----

---
purpose: production
lets_encrypt_production: true

run_ocp_diagnostics: false
cloudformation_retries: 0

#"AWS instance types"
bastion_instance_type: t3.medium
_infra_node_instance_type: m5.4xlarge
_infra_node_replicas: 3
clientvm_instance_type: t2.medium
clientvm_instance_count: 1
master_instance_type: m5.2xlarge
master_instance_count: 3
worker_instance_type: m4.2xlarge
worker_instance_count: 10
support_instance_type: t3.medium

agnosticv_meta:
  idle_after_deploy: 9999
  idle_after_start: 9999
  params_to_variables:
    nodecount: worker_instance_count_ignored
  agnosticd_git_tag_prefix: ocp4-workload-integreatly-prod
----
