---
galaxy_info:
  author: AgnosticD Team
  description: Infrastructure role for setting up PXE server for IBM Classic baremetal systems
  license: BSD
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 8
        - 9
        - 10
  galaxy_tags:
    - cloud
    - infrastructure
    - ibm
    - classic
    - baremetal
    - pxe
    - agnosticd

dependencies: []

collections:
  - ansible.builtin
  - ansible.posix
  - community.general 