:toc:

== Ansible Execution environments ==

=== Naming convention ===

Supported Execution environments for agnosticd should be named using one of the following conventions:

* `ee-<python virtualenv>` - Execution Environments for legacy python virtualenvs available on link:../virtualenvs[../virtualenvs]
Ex: `ee-ansible2.9-python3.6-2021-11-30`

* `ee-<purpose>` - execution environment customized for a particular purpose.
For example, the `<purpose>` string could be to support a particular version of a cloud provider different from what is included in the multi-cloud environment.
Ansible version should be 2.9+ and python version should be 3.6+.
Ex: `ee-multicloud`.
Version can be added as tag using semantic versioning.

=== Run agnosticd ===

==== Supported Images ====

Available public images are listed on Quay here: https://quay.io/repository/redhat-pfe/agnosticd?tab=tags

Supported images, based on supported Execution Environments, are available in our private registry image-registry.apps.open.redhat.com.

=== ansible-navigator ===

* Upstream project: https://github.com/ansible/ansible-navigator


`ansible-navigator` is the preferred way for running AgnosticD. With this CLI tool, you can use the supported agnosticd images. It has both a static stdout mode and an interactive mode.


==== Installation ====

See Upstream project: https://github.com/ansible/ansible-navigator for complete instructions.

You can use link:requirements-ee.txt[requirements-ee.txt]  or just install it with `pip`:
----
pip3 install 'ansible-navigator[ansible-core]'
----

==== Usage with agnosticd  ====

.Example with test-empty-config
[source,shell]
----
# Run from agnosticd directory
cd agnosticd

ansible-navigator run ansible/main.yml \
--eei image-registry.apps.open.redhat.com/agnosticd/ee-ansible2.9-python3.6-2021-11-30 \
-e @ansible/configs/test-empty-config/sample_vars.yml
----

NOTE: Add `--mode stdout` option to mimic `ansible-playbook` simple output.

.Example with test-empty-config With AWS
[source,shell]
----
# Run from agnosticd directory
cd agnosticd

ansible-navigator run ansible/main.yml \
--eei image-registry.apps.open.redhat.com/agnosticd/ee-ansible2.9-python3.6-2021-11-30 \
--eev ~/secrets:/secrets \
-e @ansible/configs/test-empty-config/sample_vars_ec2.yml \
-e @/secrets/dev.yml
----

=== ansible-runner (reference only) ===

For development and CLI interactions, we recommend `ansible-navigator`. But it is also possible to use the underlying `ansible-runner` command.

.Example with test-empty-config
[source,shell]
----
# Run from agnosticd directory
cd agnosticd

ansible-runner run \
--container-image=image-registry.apps.open.redhat.com/agnosticd/ee-ansible2.9-python3.6-2021-11-30 \
-p main.yml \
--cmdline "-e @configs/test-empty-config/sample_vars.yml" \
--process-isolation \
$PWD
----

.Example with test-empty-config With AWS
[source,shell]
----
mkdir -p ~/secrets
vim ~/secrets/dev.yml # add your credential variables

# Run from agnosticd directory

ansible-runner run \
--container-image=image-registry.apps.open.redhat.com/agnosticd/ee-ansible2.9-python3.6-2021-11-30 \
-p main.yml \
--cmdline "-e @configs/test-empty-config/sample_vars_ec2.yml -e @/secrets/dev.yml" \
--process-isolation \
--container-volume-mount ~/secrets:/secrets \
$PWD
----

== Build supported images ==

Requirements:

* podman installed and configured
* `oc login` to the OCP4 cluster hosting the registry
** Download CLI: https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/stable/openshift-client-linux.tar.gz
* `agnosticd` namespace present and configured on the cluster hosting the registry

.Setup your workstation
----
mkdir -p ~/virtualenvs/ansible-builder
python3 -mvenv ~/virtualenvs/ansible-builder
. ~/virtualenvs/ansible-builder/bin/activate
pip install --upgrade pip
pip install -r requirements-ee.txt
----

Execution environment images should always target specific dated versions.

.Example
----
ansible-builder build --tag ee-ansible2.9-python3.6-2021-10-29
----

=== Push to the private registry ===

* DEV image-registry.apps-dev.open.redhat.com
* PROD image-registry.apps.open.redhat.com

.Login to the registry
----
# dev
podman login -u unused -p $(oc whoami -t) image-registry.apps-dev.open.redhat.com
# prod
podman login -u unused -p $(oc whoami -t) image-registry.apps.open.redhat.com
----

.Push a tag
----
registry=image-registry.apps.open.redhat.com

#replace with the image tag you want to push
name=ee-ansible2.9-python3.6-2021-10-29
podman push $name $registry/agnosticd/$name

name=ee-multicloud:v0.1.1
podman push $name $registry/agnosticd/$name
----
