---
- import_playbook: ../include_vars.yml

- name: Delete Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Delete TSIG key via bind-key-api
      ansible.builtin.uri:
        url: "http://{{ cluster_dns_server }}:8080/keys/cluster-{{ guid }}.{{ cluster_dns_zone }}"
        method: DELETE
        headers:
          Authorization: "Bearer {{ ocp4_workload_sandbox_ddns_token }}"
        status_code: [204]

    - name: Run infra-openshift-cnv-resources
      ansible.builtin.include_role:
        name: infra-openshift-cnv-resources
      vars:
        ACTION: destroy

