PRJ_NAME="rhpam7-oih"
PRJ_DESCRIPTION="Red Hat Process Automation Manager 7 Order IT Hardware Demo"

BUSINESS_CENTRAL_REST_URL="$BC_URL/rest"
SPACE="MySpace"
DEFAULT_GROUPID="com.myspace"
#PROJECT_GIT="https://github.com/DuncanDoyle/IT_Orders.git"
PROJECT_GIT="https://github.com/jbossdemocentral/rhpam7-order-it-hw-demo-repo"
PROJECT_ID="IT_Orders"
PROJECT_NAME="IT Orders"
USERNAME="adminUser"
PASSWORD="test1234!"
