:role: satellite-manage-hostgroup
:author: Satellite Team
:tag1: configure_satellite
:tag2: satellite_hostgroup
:main_file: tasks/main.yml

Role: {role}
============

This role creates hostgroup in satellite

Requirements
------------

. Satellite must be installed and setted up.
. All the resources, that the hostgroup is using needs to be ready, so all the content roles should run beforehand.


Role Variables
--------------

* Following are the variable to customize this role

[cols="2a,1a,3a"]
|===
|satellite_version: "Digit" |Required |satellite version
|satellite_admin: "String" |Required |Satellite admin username
|satellite_admin_password: "String" |Required |Satellite admin password
|satellite_hostgroups: [list of {Dictionary}]
!===
!name: "String"
!architecture: "String"
!operatingsystem: "String"
!compute_resource: "String"
!compute_profile: "String"
!domain: "String"
!subnet: "String"
!subnet6: "String"
!lifecycle_environment: "String"
!content_view: "String"
!kickstart_repository: "String"
!medium: "String"
!pxe_loader: "String"
!ptable: "String"
!root_pass: "String"
!===
|Required
!===
!Required
!Optional(*x86_64*)
!Required
!Optional(*''*)
!Optional
!Optional
!Optional
!Optional
!Required
!Required
!Required if no *medium*
!Required if no *kickstart*
!Required
!Required
!Required(*changeme*)
!===
|List of hostgroups to create
!===
!Name of the hostgroup
!Architecture of the OS
!Name of the OS
!What compute resource to deploy on
!What compute profile to deploy
!Which domain to register the host to
!Which IPv4 subnet should the host use
!Which IPv6 subnet should the host use
!Environment to promote hosts to
!What content view should the hosts use
!Repository to provision from
!Medium to provision from
!Pxe loader type
!Partition table to use
!Root password for hosts
!===
|===

* Exammple variables

[source=text]
----
satellite_version: 6.7
satellite_admin: admin
satellite_admin_password: 'changeme'

satellite_hostgroups:
  - name: "RHEL-8"
    root_pass: rhpds123
    operatingsystem: 'RadHat 8.1'
    lifecycle_environment: Staging
    content_view: 'RHEL 8 Content'
    kickstart_repository: 'Red_Hat_Enterprise_Linux_8_for_x86_64_-_BaseOS_Kickstart_8_1'
    ptable: 'Kickstart default'
    pxe_loader: 'PXELinux BIOS'
    compute_resource: 'LibvirtLocal'
    compute_profile: 'Medium'
    domain: 'example.org'
    subnet: 'LibvirtNetwork'
    subnet6: 'LibvirtNetwork_v6'

----

Tags
---

|===
|{tag1} |Consistent tag for all satellite config roles
|{tag2} |This tag is specific to this role only
|===


Example Playbook
----------------

How to use your role (for instance, with variables passed in playbook).

[source=text]
----
[user@desktop ~]$ cat sample_vars.yml
satellite_version: 6.7
satellite_admin: admin
satellite_admin_password: 'changeme'

satellite_hostgroups:
  - name: "RHEL-8"
    root_pass: rhpds123
    operatingsystem: 'RadHat 8.1'
    lifecycle_environment: Staging
    content_view: 'RHEL 8 Content'
    kickstart_repository: 'Red_Hat_Enterprise_Linux_8_for_x86_64_-_BaseOS_Kickstart_8_1'
    ptable: 'Kickstart default'
    pxe_loader: 'PXELinux BIOS'
    compute_resource: 'LibvirtLocal'
    compute_profile: 'Medium'
    domain: 'example.org'
    subnet: 'LibvirtNetwork'
    subnet6: 'LibvirtNetwork_v6'

[user@desktop ~]$ cat playbook.yml
- hosts: satellites
  vars_files:
    - sample_vars.yml
  roles:
    - satellite-provisioning

[user@desktop ~]$ ansible-playbook playbook.yml
----


Tips to update Role
------------------

for reference look at link:{main_file}[main.yml].

Author Information
------------------

{author}
