= Ceph Workload

This workload deploys and configures Rook Ceph operator on OpenShift 4 cluster. 

== Prerequisite

Before deploying this workload on your OpenShift 4 cluster, make sure you have at least 3 compute / worker nodes running and schedulable. Ceph requires additional EBS volumes attached to each of your worker nodes. This workload creates those volumes using your AWS credentials. Make sure you have access to create at least as many volumes as number of worker nodes in your cluster.

== Deploy the workload
[source, bash]
----
ansible-playbook -i "bastion.${GUID}.${BASE_DOMAIN}", ./ansible/configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=${ANSIBLE_USER_KEY_FILE}" \
    -e"ansible_user=${ANSIBLE_USER}" \ 
    -e"ocp_workload=ocp-workload-velero" \ 
    -e"silent=False" \
    -e"ACTION=create" \
    -e @./secret.yaml \ <1>
    -e @./workload_vars.yaml <2>
----
<1> This is the same file you used while deploying OCP cluster using agnosticd. Your AWS credentials go in this file

== Configuration

You need to provide following variables to deploy this workload.

[source, yaml]
----
aws_access_key_id: <YOUR_ACCESS_KEY_ID>
aws_secret_access_key: <YOUR_SECRET_ACCESS_KEY>
aws_region: <AWS_REGION>
----

Optionally, you may choose to override following default variables.

=== Variables
[source, yaml]
----
ceph_image: ceph/ceph:v14.2.2-20190722 
ceph_rook_operator_image: rook/ceph:v1.0.0-306.g81dde4b
ceph_rook_toolbox_image: rook/ceph:master     
ceph_mahineset_namespace: openshift-machine-api
----

== Delete the workload
----
ansible-playbook -i "bastion.${GUID}.${BASE_DOMAIN}", ./ansible/configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=${ANSIBLE_USER_KEY_FILE}" \
    -e"ansible_user=${ANSIBLE_USER}" \ 
    -e"ocp_workload=ocp-workload-velero" \ 
    -e"silent=False" \
    -e"ACTION=remove" \
    -e @./secret.yaml \ <1>
    -e @./workload_vars.yaml <2>
----
<1> This is the same file you used while deploying OCP cluster using agnosticd. Your AWS credentials go in this file
