:role: handle-course-data-pntae
:author: PNTAE Team



Role: {role}
============

This role handles PNTAE's course specific data for the published catalog.
When this role is included in pntae's catalog, it enables PNTAE's content developers 
to make necessary modifications to the catalog without modifying agnosticd.

PNTAE's content developers can push all the necessary modifications for the catalog 
at PNTAE's git repository or any other public url and the training catalog willl pull 
and execute the data from there.

Requirements
------------

. This role depends on variable.


Role Variables
--------------

|===
|coursecode: tech-elmod-ansible-111 |Required | PNTAE's module code
|courseurl: URL | Required | URL containing PNTAE's course data in archive form
|guid: ID | Required | Unique ID for current running instance of the lab
|===

* Example variables

[source=text]
----
coursecode: tech-elmod-ansible-111
courseurl: https://raw.githubusercontent.com/pntae-training/courses/master/
guid: aks
----

Example Playbook
----------------

How to use your role (for instance, with variables passed in playbook).

[source=text]
----
$ cat configs/three-tier-app/sample_vars_osp.yml 
---
# sample vars configuration file
env_type: three-tier-app                # Name of config to deploy
output_dir: /tmp/output_dir             # Writable working scratch directory
email: name@example.com                 # User info for notifications
guid: guid01                            # Your Global UNIQUE Identifier
cloud_provider: osp                     # Which AgnosticD Cloud Provider to use
ansible_user: cloud-user
remote_user: cloud-user 
osp_cluster_dns_zone: red.osp.opentlc.com
coursecode: "cee-an-120"
courseurl: "https://raw.githubusercontent.com/pntae-training/courses/master"

repo_version: 3.7.0-4
own_repo_path: http://admin.example.com/repos/tower

----

Sample files on PNTAE's github url

[source=text]
----
courses]$ find cee-an-120
cee-an-120
cee-an-120/cee-an-120.sh
cee-an-120/cee-an-120.yml
cee-an-120/cee-an-120-bastion.yml
cee-an-120/cee-an-120-frontend.yml
cee-an-120/cee-an-120-app1.yml

----

The course data contents listed above should be made available in the form of an archive via url
Example:
[source=text]
----
$ tar -zcvf cee-an-120.tar.gz cee-an-120
https://github.com/pntae-training/courses/blob/master/cee-an-120.tar.gz
----

Author Information
------------------

Ashish Shah(ashishks@redhat.com)
