:role: handle-course-data-pntae
:author: PNTAE Team



Role: {role}
============

This role handles PNTAE's course specific data for the published catalog.
When this role is included in pntae's catalog, it enables PNTAE's content developers 
to make necessary modifications to the catalog without modifying agnosticd.

PNTAE's content developers can push all the necessary modifications for the catalog 
at PNTAE's git repository or any other public url and the training catalog willl pull 
and execute the data from there.

Requirements
------------

. This role depends on variable.


Role Variables
--------------

|===
|coursecode: tech-elmod-ansible-111 |Required | PNTAE's module code
|courseurl: URL | Required | URL containing PNTAE's course data in archive form
|guid: ID | Required | Unique ID for current running instance of the lab
|===

* Example variables

[source=text]
----
coursecode: tech-elmod-ansible-111
courseurl: https://raw.githubusercontent.com/pntae-training/courses/master/
guid: aks
----

Example Playbook
----------------

How to use your role (for instance, with variables passed in playbook).

[source=text]
----

----


Author Information
------------------

Ashish Shah(ashishks@redhat.com)
