#!/bin/bash

virsh start vm1


usermod -aG wheel rhel
echo redhat | passwd --stdin rhel

echo "${SSHKEY}" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa
ssh-keygen -f /root/.ssh/id_rsa -y > /root/.ssh/id_rsa.pub

# MAC Addresses
# vm1:      52:54:00:d6:0c:72
# centos:   52:54:00:68:79:84

# Get the IP of the VM belonging to vm1 based on arp.
while ! [ $( arp -an | grep 52:54:00:d6:0c:72 | awk '{print $2}' | tr -d '()')  ]; do echo "Waiting for arp to return rhelvm MAC address."; sleep 1; done;
echo "$( arp -an | grep 52:54:00:d6:0c:72 | awk '{print $2}' | tr -d '()' ) rhelvm" >> /etc/hosts

TMUX='' tmux new-session -d -s 'firewall-testing'
tmux set -g pane-border-status top
tmux setw -g pane-border-format ' #{pane_index} #{pane_current_command}'

while ! ping -c 1 -W 1 rhelvm; do echo "\nWaiting for rhelvm - network interface might be down."; sleep 1; done
ssh -o "StrictHostKeyChecking no" root@rhelvm subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force
TMUX='' tmux new-session -d -s 'firewall-testing-rhelvm' 'ssh -o "StrictHostKeyChecking no" root@rhelvm; clear'