---
become_override: false
ocp_username: opentlc-mgr
silent: false

# Folder where the pool VMs (described above) are located
ocp4_workload_virt_roadshow_fvmw_vcenter_pool_folder: "Roadshow"

# Enable/disable certificate validation on vCenter API
ocp4_workload_virt_roadshow_fvmw_enable_cert_validation: true

# Network to use in vCenter
ocp4_workload_virt_roadshow_fvmw_vcenter_network: segment-migrating-to-ocpvirt

ocp4_workload_virt_roadshow_fvmw_num_users: 1

# User base for OCP Authentication (to assign vCenter users to OCP users in agnosticd_user_info)
ocp4_workload_virt_roadshow_fvmw_vcenter_user: user1
ocp4_workload_virt_roadshow_fvmw_auth_user_base: user

# Set up MTV with a VMware provider (single-user)
ocp4_workload_virt_roadshow_fvmw_enable_mtv: false

# MTV Namespace base to use for multi user.
# For single user the namespace is always `openshift-mtv`
ocp4_workload_virt_roadshow_fvmw_mtv_namespace_base: "mtv-{{ ocp4_workload_virt_roadshow_fvmw_auth_user_base }}"
