include::../../tools/00_0_Lab_Header.adoc[]

== Simple Workload - Lab

.Goals

* Understand the structure and function of a OCP Workload Role
* Understand the Workload Development Process
* Setup Environment for a Workload Role
* Run a Simple Workload Role
* Create your own workload role
* Understand Variable Conventions

include::../../tools/00_0_Lab_Setup.adoc[]

[[labexercises]]
:numbered:

== Overview

=== About OCP Workloads

In previous modules you were introduced to AgnosticD's _base configs_.  You were able to deploy virtual machines, networks, and general infrastructure.

In this module you will learn how to write and deploy OpenShift workloads. These are workloads specifically created to be deployed on top of the OpenShift base configs provided within the AgnosticD repository. This is the case of our friend Malcolm, who needs to apply custom configurations to an OpenShift cluster to create an event lab. You can also support some sort of demonstration, workshop, or class with this type of workloads: For example, all of GPTE's OpenShift classes are created in the same way we are going to introduce you today. In this module you'll be using OpenShift 4 workloads to prepare a demo sample application.

To execute a workload, you execute the base config `ocp-workload`, and supply it your workload's name and any necessary variables.  This will be covered in depth in this lab.

Make sure you use the DEV OSP Sandbox that you ordered when doing Module 02 - "Getting Started". If this Sandbox expired, please order a new one by logging in to link:labs.opentlc.com[labs.opentlc.com], *Services* -> *Catalogs*, and select *DEV OSP Sandbox* under the *Novello testing* Catalog.

== Create your own OCP4 Workload Role

=== Copying the Example Workload

All workload roles must be developed in the proper location in the AgnosticD directory tree.  The option to create workloads outside the tree will be covered in later training, as the option becomes available.

OCP4 based workloads must be placed in a subdirectory of `agnosticd/ansible/roles_ocp_workloads/`, and named with a prefix of `ocp4_workload_`.  For example, `ocp4_workload_example`.

Workload roles are a pattern based on standard Ansible roles.  As in Ansible, the typical subdirectories are supported.

. Examine the role directories as follows:


+
[source,sh]
----
cd agnosticd/
tree ansible/roles_ocp_workloads/ocp4_workload_example
----
+
.Sample Output
[source,sh]
----
ocp4_workload_example
├── README.md
├── defaults
│   └── main.yml
├── files
├── meta
│   └── main.yml
├── readme.adoc
├── tasks
│   ├── main.yml
│   ├── post_workload.yml
│   ├── pre_workload.yml
│   ├── remove_workload.yml
│   └── workload.yml
└── templates
----
+
To create your own new workload role, follow on with this lab.

. Set your Ansible working directory environment variables.
We assume you've cloned AgnosticD into your $HOME, so export the following:
+
[source,sh]
----
export WORKLOADS=$HOME/agnosticd/ansible/roles_ocp_workloads
----
+
. Create your own workload directory:
+
[source,sh]
----
mkdir $WORKLOADS/ocp4_workload_${GUID}
----

. Copy the example role into your new role directory:
+
[source,sh]
----
cp -rv ${WORKLOADS}/ocp4_workload_example/*  ${WORKLOADS}/ocp4_workload_${GUID}
----

=== Default Variables

You have a new role structure, but you don't know what it does. Worse, many of the variable names in it are still the old name and will not work in your new role.
Let's edit the files, describe what they do, and update the variables to support our new role.

. Change directory into your new role directory to begin working on it:
+
[source,sh]
----
cd ${WORKLOADS}/ocp4_workload_${GUID}
----
. Edit the default role variables
+
The variables in default/main.yml define the defaults variable values that will be shipped with your role.  They should be "sane defaults" that work in as many forseeable contexts as possible.  In this case, we have five variables. The first three variables are critical for AgnosticD to work, and the last two are unique to the role:
+
WARNING: These variables are critical to your workload functioning properly. Your deployer (like CloudForms), or AgnosticV, will override them as necessary, or as instructed in each stage.
+
[source,sh]
----
cat defaults/main.yml
----
+
.Example Output
[source,yaml]
----
become_override: False <1>
ocp_username: wkulhane-redhat.com <2>
silent: False <3>

# If your workload needs customization options provide variables to be used.
# Variable names must be prefixed by the role name "<role name>_<variable>".
# Therefore because this example workload is called "ocp4_workload_example" the variables
# should be named "ocp4_workload_example_variable".
#
# You can override the defaults as parameters to the Ansible run that runs
# your workload.

# Documentation for variable 1 (what does it do?)
ocp4_workload_example_variable_1: "value 1" <4>

# Documentation for variable 2 (what does it do?)
ocp4_workload_example_variable_2: "value 2" <5>
----
+
<1> `False` is the default.  If you must run your workload as the root user, set to `True`
<2> Your should use this ocp_username to own OpenShift objects.  It is usually supplied by the user or deployment system.
<3> Debugging
<4> A role variable.  Note that it is prefixed by the role name (`ocp4_workload_example_`) and suffixed with the name of the variable (`variable_2`)
<5> Another role variable.

. Change the name of your default role variables to match your new role name:
+
[source,sh]
----
perl -pi -e "s/_example_/_${GUID}_/g" defaults/main.yml
----
+
. Examine the file to make sure the `_example_` string was replaced correctly.
+
----
cat defaults/main.yml
----

=== Role Tasks and the Workload Pattern

The tasks are the most important parts of the role, and the most complicated.  The base config `ocp-workload` understands how to process and apply the tasks to the OCP cluster you've already deployed.

. Examine the `tasks/main.yml` to understand how the other tasks are called.
+
[source,sh]
----
cat tasks/main.yml
----
+
.Sample Output
[source,yaml]
----
---
# Do not modify this file

- name: Running Pre Workload Tasks
  include_tasks:
    file: ./pre_workload.yml
    apply:
      become: "{{ become_override | bool }}"
  when: ACTION == "create" or ACTION == "provision"

- name: Running Workload Tasks
  include_tasks:
    file: ./workload.yml
    apply:
      become: "{{ become_override | bool }}"
  when: ACTION == "create" or ACTION == "provision"

- name: Running Post Workload Tasks
  include_tasks:
    file: ./post_workload.yml
    apply:
      become: "{{ become_override | bool }}"
  when: ACTION == "create" or ACTION == "provision"

- name: Running Workload removal Tasks
  include_tasks:
    file: ./remove_workload.yml
    apply:
      become: "{{ become_override | bool }}"
  when: ACTION == "destroy" or ACTION == "remove"
----
+
There are four included tasks above.  Three of them are executed during "create" or "provision" phases, and one is executed during the "destroy" or "remove" phase.  When you execute this workload, you will indicate which phase you'd like `ocp_workload` to run by setting the environment variable ACTION.
+
* *pre_workload.yml* - Write tasks here to set up an environment for the workload deployment.
* *workload.yml* - Write tasks here to deploy the actual workload, i.e, 3scale, Mobile, some Demo or OpenShift customization
* *post_workload.yml* - Write tasks here to configure the workload after deployment, i.e. add workload users or storage

=== Example `workload.yml`

The `workload.yml` playbook is usually the most important and complex.  This is where you will deploy your workload to the OCP cluster.  This is a simple example for you to build from.  Further labs will have more realistic and complex examples.

. Examine the playbook.  Note that this role only emits a debug messages.  It emits standard debug messages, and the value of the workload variables.
+
[source,sh]
----
cat tasks/workload.yml
----
+
.Sample Output
[source,yaml]
----
---
- name: Setting up workload for user <1>
  debug:
    msg: "Setting up workload for user ocp_username = {{ ocp_username }}"

# To Do: Implement your workload deployment tasks here
# -------------------------------------------------------------------------

- name: Example Workload, print variable values
  debug:
    msg: "{{ item }}"
  loop:
  - "Variable 1: {{ ocp4_workload_example_variable_1 }}" <2>
  - "Variable 2: {{ ocp4_workload_example_variable_2 }}" <2>

# Leave this as the last task in the playbook.
# --------------------------------------------
- name: workload tasks complete <1>
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool
----
+
<1> These are standard debug messages that should be in EVERY workload playbook to track progress.  Do not remove them.
<2> These are your custom workload variables.  You should change these to match the name of your workload.
+
. Use a text editor or the follow script to edit the `workload.yml` file and change the variable names to match your new workload role.
+
[source,sh]
----
perl -pi -e "s/_example_/_${GUID}_/g" tasks/workload.yml
----
+
. Verify your changes produced the desired variable names.
+
[source,sh]
----
cat tasks/workload.yml
----

=== Update Role Metadata, Test, and ReadMe

Your workload is nearly ready to test, but some best-practice housekeeping is necessary.

. Edit the `meta/main.yml` file to ensure that you and your role can be identified properly in the AgnosticD and Ansible Galaxy tools.
. Take some time to thoroughly edit the README.adoc file. Properly describe the tasks you add to each of the included tasks of the playbooks.
Make sure users and operators of your workload will understand its purpose and any gotchas you experienced or think might arise.

Your workload is now properly reconfigured and is ready to begin testing.

== Setup Your Testing Execution Environment

This is usually done on your laptop, or on a dedicated development host.

Executing workloads differs only in minor ways to executing the base configs you're already accustomed to. You'll setup a variables file, if needed.  You'll setup some environment variables.  And you'll prepare a command line with the TARGET_HOST variable being the bastion of the OCP cluster you have access to.

. Gather Details
.. *GUID* of the OCP cluster you plan to deploy to.
.. *Target Host* is the *Fully Qualified Domain Name* of the bastion host of that cluster.
.. *Ansible User* of the bastion host of that cluster.  On AWS, it's `ec2-user`, on OpenStack, it's `cloud-user`. Must be setup for passwordless SSH.
+
[NOTE]
====
* You'll need the proper ssh keys setup for passwordless login to the *Ansible User* account.
* You might have an email with an SSH username and password for the cluster.  Do a `ssh-copy-id <username>@<bastion host>` to setup passwordless SSH.
* You might already have keys setup if you created the cluster.  Validate that they work from the command line.
====
+
.. *OCP Username* of the user you want to be on the OpenShift cluster.

In order for you to complete the training easily, you can request access to our shared development cluster. Go to link:[https://labs.opentlc.com] and request the item "DEV OpenShift Shared Cluster Latest" from the catalog "Shared Cluster Development".

Before you move forward with the execution, please take a minute to login to the cluster console, and also via oc client in your laptop or sandbox bastion, by following the instructions in the final e-mail received.

To install the oc command line tools, please follow the instructions in this link:https://docs.openshift.com/container-platform/4.2/cli_reference/openshift_cli/getting-started-cli.html#cli-installing-cli-on-linux_cli-developer-commands[page] 

----
mkdir .local
cd .local
mkdir bin
cd bin
wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
tar xvfz openshift-client-linux.tar.gz
oc
----
+
You should see an output similar to this
+
----
OpenShift Client

This client helps you develop, build, deploy, and run your applications on any
OpenShift or Kubernetes cluster. It also includes the administrative
commands for managing a cluster under the 'adm' subcommand.

To familiarize yourself with OpenShift, login to your cluster and try creating a sample application:

    oc login mycluster.mycompany.com
    oc new-project my-example
    oc new-app django-psql-example
    oc logs -f bc/django-psql-example
(...)
----

You can later verify the results of your workload execution. Having the oc client installed will enable you to verify your results via command line, as well as the already available graphical console.

=== `<role name>_vars.yaml` File

To make testing complex workloads that require many parameters easier, create a `<role name>_vars.yaml` input file to add to your command line.

. Create a variables file that you can use to pass in new and updated variables as you run your workload. Save this file in your role directory as ocp4_workload_${GUID}_vars.yaml.
+
[source,sh]
----
# You can set any variable
# This one is used by the ocp-workload to provide debug logging
silent: False

# Set Variable 2
# Write a comment to Describe your variable
ocp4_workload_example_variable_2: "My variable 2"
----
+
[IMPORTANT]
====
* We recommend creating this file with sample values and including it in your workload role in order to aid other developers and operators in the use of the workload.
* We recommend creating this file and including it FIRST in the order of `ansible-playbook -e @./filename.yaml` instead of using environment variables or `ansible-playbook -e` values.
====

=== Environment Variables

Set up Environment Variables indicating the bastion host you want to run this role to run on. 

. Change the various values to match your environment.
+
[source,sh]
----
export TARGET_HOST="bastion.dev4.openshift.opentlc.com" <1>
export OCP_USERNAME="YOURKERBEROS-redhat.com" <2>
export ANSIBLE_USER="ec2-user" <3>
export WORKLOAD="ocp4_workload_${GUID}" <4>
----
<1> Change to match your cluster bastion.
<2> Change to match your OCP username - the user must already exist. In OpenTLC, users will be dynamically created.
<3> `ec2-user` for AWS, `cloud-user` for OpenStack
<4> The workload is all your hard work!
+
[NOTE]
====
* Use environment variables for parameters that will be re-used through your deploy-test-fix-remove development cycle.
* Use `ansible-playbook -e` command line variables for values that will change from test run to test run.
====

=== Command Line Variables

The `ansible-playbook` command that you will be running evaluates variables in order of appearance, last one wins.  The last variables on the command line override all prior variables.

. Examine this command.  *Do not execute this.*  Simplynderstand the structure of the command.
+
[source,sh]
----
ansible-playbook -i ${TARGET_HOST}, -vvv ./configs/ocp-workloads/ocp-workload.yml \ (1)
    -e @./ocp4_workload_${GUID}_vars.yaml \ (2)
    -e"ocp4_workload_${GUID}_variable_2=New Test Variable" <3> \
    -e"ansible_user=${ANSIBLE_USER}" \ (4)
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"guid=${GUID}" \
    -e"ACTION=create" (5)
----
<1> This is the base config that understands how to deploy ocp-workloads.  Note that we are running very, very, very verbose.
<2> This is the sample role vars file you setup above.
<3> This is a variable with a literal value.  This overrides the variable of the same name that exists in the `<role name>_vars.yaml` file.
<4> This is a variable with a value derived from a shell environment variable.  It will override variable of the same name that occured prior in this command line.
<5> The set of playbooks to be run from the workload role, as defined in `tasks/main.yml`

== Run the Workload with Verbose logs

You are now ready to start the deployment of your workload, and the first step of the deploy-test-fix-remove loop of developing workload roles.

Before you do so, let's validate that you can properly connect to your TARGET_HOST. Make sure you have the key provided by the instructor in your sandbox and let's test ssh connection:

[source,sh]
----
touch ~/.ssh/ocpkey.pem

vi ~/.ssh/ocpkey.pem

## Paste the contents of the key provided in vi, save and quit.

chmod 0400 ~/.ssh/ocpkey.pem

ssh -i ~/.ssh/ocpkey.pem ec2-user@bastion.dev4.openshift.opentlc.com
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Fri Jun 26 06:21:00 2020 from 169.47.188.113
[ec2-user@bastion ~]$ hostname
bastion.dev4.internal
[ec2-user@bastion ~]$ oc get nodes
NAME                                         STATUS   ROLES                  AGE   VERSION
ip-10-0-128-55.us-west-2.compute.internal    Ready    infra,worker           49d   v1.17.1+3f6f40d
ip-10-0-138-173.us-west-2.compute.internal   Ready    worker                 30d   v1.17.1+3f6f40d
ip-10-0-138-67.us-west-2.compute.internal    Ready    master                 49d   v1.17.1+3f6f40d
ip-10-0-139-119.us-west-2.compute.internal   Ready    worker                 49d   v1.17.1+3f6f40d
ip-10-0-143-209.us-west-2.compute.internal   Ready    elasticsearch,worker   49d   v1.17.1+3f6f40d
ip-10-0-144-13.us-west-2.compute.internal    Ready    master                 49d   v1.17.1+3f6f40d
ip-10-0-155-33.us-west-2.compute.internal    Ready    worker                 49d   v1.17.1+3f6f40d
ip-10-0-156-6.us-west-2.compute.internal     Ready    worker                 30d   v1.17.1+3f6f40d
ip-10-0-160-8.us-west-2.compute.internal     Ready    master                 49d   v1.17.1+3f6f40d
[ec2-user@bastion ~]$ exit
logout
Connection to bastion.dev4.openshift.opentlc.com closed.
----

. Back in your Sandbox, create a shell script file with the following, or run it directly from the command line.
+
[source,sh]
----
# a TARGET_HOST is specified in the command line, without using an inventory file
cd $HOME/agnosticd/ansible
ansible-playbook -i ${TARGET_HOST}, -vvv ./configs/ocp-workloads/ocp-workload.yml \
    -e @$HOME/agnosticd/ansible/roles_ocp_workloads/ocp4_workload_${GUID}/ocp4_workload_${GUID}_vars.yaml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=${ANSIBLE_USER}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"guid=${GUID}" \
    -e"ACTION=create"
----
+
[IMPORTANT]
====
All these parameters can be delivered to the `./configs/ocp-workload.yml` playbook the way that works best for you.

For example, you can include them all literally in the shell script file, or export them into your environment, or you can put the majority of them in the `<role name>_vars.yaml` file.

As above, we recommend setting variables as follows:

* `<role name>_vars.yaml` file for safe example variables for all deployers.
* Environment variables for settings that will not change for your current development working session.
* `ansible-playbook -e` variable settings for values that will change between your test runs.
* For more information on how variables take precedence in Ansible, please consult the official Ansible documentation.
====

. The output of the run should be quite verbose.  Examine the output for the desired outcomes, especially the tasks and expected debug messages.  You should see verbose output thanks to the `-vvv` in the `ansible-playbook` command AND debugging output thanks to the `silent: False` variable.

. After inspecting the output, you might be able to run the command again to correct errors.
You might need to prepare and run the `remove.yml` playbook from this workload to reset the cluster to run another test without interference from resources created by this run.  In this case, no changes were made, so you are free to run the workload role again.  We will cover writing and running the `remove.yml` playbook in the next lab.

== Modify Variables and Run Again

=== Modify from the Command Line or Environment

During testing, you'll want it to be easy to experiment with different parameters and values.  Use the command line or environment to make changing those values easy.

. Change an environment variable
+
[source,sh]
----
export WORKLOAD_VAR_2="Var2: Changed in Environment"
----

. Change a command line environment variable to output different data:
+
[source,sh]
----
cd $HOME/agnosticd/ansible
ansible-playbook -i ${TARGET_HOST}, -vvv ./configs/ocp-workloads/ocp-workload.yml \
    -e @$HOME/agnosticd/ansible/roles_ocp_workloads/ocp4_workload_${GUID}/ocp4_workload_${GUID}_vars.yaml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=${ANSIBLE_USER}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"guid=${GUID}" \
    -e"ACTION=create" \
    -e"ocp4_workload_${GUID}_variable_1='New Test Variable'" \ (1)
    -e"ocp4_workload_${GUID}_variable_2='${WORKLOAD_VAR_2}'" (2)
----
+
<1> Variable 1 uses a literal.
<2> Variable 2 was exported in the shell environment in the previous step and included in the `-e` values.
+
NOTE: BOTH of these variables override the value in the *_vars.yaml file.

=== Modify from Parameters Files

. Change the vars file you created earlier to reflect a parameter that you don’t expect to change during this development session. This file should be saved in your role directory as ocp4_workload_${GUID}_vars.yaml.
+
[source,sh]
----


# You can set any variable
# Silent: False emits debug logging for your role
silent: False

# Set Variable 2
# Write a comment about what this variable does
ocp4_workload_${GUID}_variable_2: "Example of my variable 2 for other deployers"

----
+
WARNING: Be sure to update the `ocp4_workload_example_variable_2` name to match your role name.

. Remove the variable_2 you were passing in with the -e on the the command line and execute again:
+
[source,sh]
----

cd $HOME/agnosticd/ansible
ansible-playbook -i ${TARGET_HOST}, -vvv ./configs/ocp-workloads/ocp-workload.yml \
    -e @$HOME/agnosticd/ansible/roles_ocp_workloads/ocp4_workload_${GUID}/ocp4_workload_${GUID}_vars.yaml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=${ANSIBLE_USER}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"guid=${GUID}" \
    -e"ACTION=create" \
    -e"ocp4_workload_${GUID}_variable_1='New Test Variable'"

----
+
NOTE: Variable 2 is now used from the `<role name>_vars.yaml` file.

=== Modify the Role Defaults Variables File

Now that you are confident in your variable names and values, go ahead and enshrine them in the `defaults/main.yml`.
Every deployer that does not set this variable explicitly will pick up this value.
This is the BEST place to document your variables - other than the README.

. Edit the `defaults/main.yml` default role variables file:
+
[source,yaml]
----
become_override: False
ocp_username: wkulhane-redhat.com
silent: False

# If your workload needs customization options provide variables to be used.
# Variable names must be prefixed by the role name "<role name>_<variable>".
# Therefore because this example workload is called "ocp4_workload_example" the variables
# should be named "ocp4_workload_example_variable".
#
# You can override the defaults as parameters to the Ansible run that runs
# your workload.

# Documentation for variable 1 (what does it do?)
ocp4_workload_${GUID}_variable_1: "Workload Role Default value 1"

# Documentation for variable 2 (what does it do?)
ocp4_workload_${GUID}_variable_2: "Workload Role Default value 2"
----

. Run the command line again, to see what variables actually passed through to the logs.
+
[source,sh]
----
cd $HOME/agnosticd/ansible
ansible-playbook -i ${TARGET_HOST}, -vvv ./configs/ocp-workloads/ocp-workload.yml \
    -e @$HOME/agnosticd/ansible/roles_ocp_workloads/ocp4_workload_${GUID}/ocp4_workload_${GUID}_vars.yaml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=${ANSIBLE_USER}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=${WORKLOAD}" \
    -e"guid=${GUID}" \
    -e"ACTION=create" \
    -e"ocp4_workload_${GUID}_variable_1=New Test Variable"
----
. Look at the output and the command and figure out what you need to do in order to preserve the default vars.

== Lab Complete

Congratulations!

You are now familiar with:

* The naming and structure of OCP Workload roles and variables
* The execution of Workload roles with ACTION and the order in which they are executed.
* The precedence and best practices using variables.
* How to do tight-loop development of workloads

Go onto the next lab, where you will

* start creating, modifying, and deleteing OpenShift resources.
* sending debug information to your customers/students.

