= Ansible Lightbulb Config

Ansible Lightbulb is an example of an existing deployer being wrapped by Ansible

https://github.com/ansible/lightbulb

== Set up your "Secret" variables

* You need to provide some credentials for deployments to work
* Create a file called "env_secret_vars.yml" and put it in the
 ./ansible/configs/CONFIGNAME/ directory.
** At this point this file *has to be created* even if no vars from it are used.
* You can choose to provide these values as extra vars (-e "var=value") in the
 command line if you prefer not to keep sensitive information in a file.

.Example contents of "Secret" Vars file
----
# ## Logon credentials for Red Hat Network
# ## Required if using the subscription component
# ## of this playbook.
rhel_subscription_user: ''
rhel_subscription_pass: ''
#
# ## LDAP Bind Password
bindPassword: ''
#
# ## Desired admin name and password if required
admin_user: ""
admin_user_password: ""
#
# ## AWS Credentials. This is required.
aws_access_key_id: ""
aws_secret_access_key: ""
#If using repo_method: satellite, you must set these values as well.
satellite_url: https://satellite.example.com
satellite_org: Sat_org_name
satellite_activationkey: "rhel7basic"

----

== Review the Env_Type variable file

* This file link:./env_vars.yml[./env_vars.yml] contains all the variables you
 need to define to control the deployment of your environment.


== Running Ansible Playbook

You can run the playbook with the following arguments to overwrite the default variable values:
[source,bash]
----
ec2_key_name: ocpkey                  # SSH key in AWS to put in all the instances
ec2_region: us-east-1                 # region where the nodes will live
ec2_az: us-east-1a                    # the availability zone
ec2_name_prefix: lightbulb            # name prefix for all the VMs
admin_password: ansible              # Set this to something better if you'd like. Defaults to 'LearnAnsible[two digit month][two digit year]', e.g., LearnAnsible0416
## Optional Variables
email: no                             # Set this if you wish to disable email
users:
  - name: tony kay
    username: tok
    email: tok@redhat.com

#USERS='{"users":[{ "name": "Alice", "username": "alice", "email": "alice@example.com" }, { "name": "Bob", "username":"bob", "email": "bob@example.com" }]}'
#REPO_PATH='https://admin.example.com/repos/ocp/3.6/'
#        -e "repo_method=file" -e "own_repo_path=${REPO_PATH}" -e "repo_version=${REPO_VERSION}" \
   #     -e ${USERS} \

REGION=us-east-1
AVAILABILITYZONE=us-east-1a
EC2NAMEPREFIX=lightbulb
KEYNAME=ocpkey
GUID=lightbulb
ENVTYPE=lightbulb
ADMINPASSWORD=lightbulb
EMAILUSERS=no
CLOUDPROVIDER=ec2
HOSTZONEID='Z3IHLWJZOU9SRT'

BASESUFFIX='.example.opentlc.com'
DEPLOYER_REPO_PATH=`pwd`

ansible-playbook \
     ${DEPLOYER_REPO_PATH}/main.yml  \
        -e "ANSIBLE_REPO_PATH=${DEPLOYER_REPO_PATH}" \
        -e "ec2_key_name=${KEYNAME}" \
        -e "ec2_region=${REGION}" \
        -e "ec2_az=${AVAILABILITYZONE}" \
        -e "ec2_name_prefix=${EC2NAMEPREFIX}" \
        -e "admin_password=${ADMINPASSWORD}" \
        -e "email=${EMAILUSERS}" \
        -e "guid=${GUID}" \
        -e "env_type=${ENVTYPE}" \
        -e "key_name=${KEYNAME}" \
        -e "subdomain_base_suffix=${BASESUFFIX}" \
        -e "cloud_provider=${CLOUDPROVIDER}" \
        -e "aws_region=${REGION}" \
        -e "HostedZoneId=${HOSTZONEID}" \
        -e "install_ipa_client=false" \
        -e "software_to_deploy=none" \
        --skip-tags=deploy_infrastructure,post_infra_tasks,pre_software_tasks,deploy_software,post_software,email




----

=== To Delete an environment

[source,bash]
----
REGION=us-east-1
AVAILABILITYZONE=us-east-1a
EC2NAMEPREFIX=lightbulb
KEYNAME=ocpkey
GUID=lightbulb
ENVTYPE=lightbulb
ADMINPASSWORD=lighbulb
EMAILUSERS=no
USERS='{"users":[{ "name": "Alice", "username":"alice", "email": "alice@example.com" }, { "name": "Bob", "username":"bob", "email": "bob@example.com" }]}'
CLOUDPROVIDER=ec2
HOSTZONEID='Z3IHLWJZOU9SRT'
REPO_PATH='https://admin.example.com/repos/ocp/3.6/'

BASESUFFIX='.example.opentlc.com'
DEPLOYER_REPO_PATH=`pwd`

#To Destroy an Env

ansible-playbook \
     ${DEPLOYER_REPO_PATH}/configs/${ENVTYPE}/destroy_env.yml \
        -e "ANSIBLE_REPO_PATH=${DEPLOYER_REPO_PATH}" \
        -e "ec2_key_name=${KEYNAME}" \
        -e "ec2_region=${REGION}" \
        -e "ec2_az=${AVAILABILITYZONE}" \
        -e "ec2_name_prefix=${EC2NAMEPREFIX}" \
        -e "admin_password=${ADMINPASSWORD}" \
        -e "email=${EMAILUSERS}" \
        -e ${USERS} \
        -e "guid=${GUID}" \
        -e "env_type=${ENVTYPE}" \
        -e "key_name=${KEYNAME}" \
        -e "subdomain_base_suffix=${BASESUFFIX}" \
        -e "cloud_provider=${CLOUDPROVIDER}" \
        -e "aws_region=${REGION}" \
        -e "HostedZoneId=${HOSTZONEID}" \
        -e "install_ipa_client=false" \
        -e "repo_method=file" -e "own_repo_path=${REPO_PATH}" -e "repo_version=${REPO_VERSION}" \
        -e "software_to_deploy=none"
----
