= ocp4_workload_sepsis_detection

HIMSS 2021 Sepsis Detection Demo

== Role overview

* This role deploys a full instance of the link:https://github.com/redhat-naps-da/himss_interoperability_showcase_2021/blob/master/README.adoc[HIMSS 2021 Sepsis Detection demo].


** Tasks: link:./tasks/pre_workload.yml[pre_workload.yml] - Sets up an
 environment for the workload deployment.
*** Debug task will print out: `pre_workload Tasks completed successfully.`

** Tasks: link:./tasks/workload.yml[workload.yml] - Used to deploy
*** This role creates a namespace (project) and deploys all the components of the demo.
*** Debug task will print out: `workload Tasks completed successfully.`

** Tasks: link:./tasks/post_workload.yml[post_workload.yml] - Used to
 configure the workload after deployment
*** This role doesn't do anything here
*** Debug task will print out: `post_workload Tasks completed successfully.`

** Tasks: link:./tasks/remove_workload.yml[remove_workload.yml] - Used to
 delete the workload
*** This role removes OpenShift Pipelines
*** Debug task will print out: `remove_workload Tasks completed successfully.`

=== Deploy a Workload with the `ocp-workload` config [Mostly for testing]

. Ensure you are logged into an OCP 4.8 environment as _clusteradmin_
. From the Agnosticd/ansible directory run the playbook:
+
----
SUBDOMAIN_BASE=`oc whoami --show-server | cut -d'.' -f 2,3,4,5,6 | cut -d':' -f 1`
ADM_USERNAME=user1
ansible-playbook -i localhost, -c local ./configs/ocp-workloads/ocp-workload.yml \
                    -e ocp_workload=ocp4_workload_sepsis_detection \
                    -e ACTION=create \
                    -e subdomain_base=$SUBDOMAIN_BASE \
                    -e admin_username=$ADM_USERNAME
----

=== To Delete an environment

. From the Agnosticd/ansible directory run the playbook:
+
----
SUBDOMAIN_BASE=`oc whoami --show-server | cut -d'.' -f 2,3,4,5,6 | cut -d':' -f 1`
ADM_USERNAME=user1
ansible-playbook -i localhost, -c local ./configs/ocp-workloads/ocp-workload.yml \
                    -e ocp_workload=ocp4_workload_sepsis_detection \
                    -e ACTION=remove \
                    -e subdomain_base=$SUBDOMAIN_BASE \
                    -e admin_username=$ADM_USERNAME
----
