#!/usr/bin/env bash


if [ $# -ne 2 ];
then  
  echo "Usage: solve-lab course-name lab-number"
  echo
  echo "lab-number in format 03_01"
  exit 1
fi  

COURSE_NAME=$1
LAB_NUMBER=$2

# wrapper script for grading playbook for lab
#

VIRTUALENV=/opt/virtualenvs/venv-grading
FTL_REPO_HOME=/opt/ftl-repo-clone/

# Make sure ansible finds the correct roles if it loads a new ansible.cfg

export ANSIBLE_ROLES_PATH=${FTL_REPO_HOME}/roles:${FTL_REPO_HOME}/roles-ftl-runtime
export FILE=${FTL_REPO_HOME}/courses/${COURSE_NAME}/ansible.cfg

if [ -f $FILE ]; then
   export ANSIBLE_CONFIG=${FILE}
fi

# Activate a protected vurtualenv with all dependencies and it's own ansible

echo "Starting Grading Process"

source ${VIRTUALENV}/bin/activate

( cd ${FTL_REPO_HOME};  ansible-playbook main.yml                  \
  -e @vars/global_vars.yml                                          \
  -e course_name=${COURSE_NAME}                                     \
  -e purpose=solve                                                  \
  -e lab_number=${LAB_NUMBER}  )
