= Generic Example Env_Type

In this directory we keep the files for a "Generic Example" environment type.

we create folders, yml files, and other items we want to over ride default variables.

For example, we will include things such as ec2 instance names, secret
variables such as private/public key pair information, passwords, etc.

Eventually, all sensitive information will be encypted via Ansible Vault. The
inclusion as well as instructions on doing this will be included in a later
release.

== Set up your "Secret" variables

* You need to provide some credentials for deployments to work
* you can set these for each "Standard Config" in it's directory or have a
 global variables file that will overwrite any "Config" specific variable file.

* Create a file called env_secret_vars.yml in the "environment type" directory

.Example contents of "Secret" Vars file
----
# ## Logon credentials for Red Hat Network
# ## Required if using the subscription component
# ## of this playbook.
rhel_subscription_user: ''
rhel_subscription_pass: ''
#
# ## LDAP Bind Password
bindPassword: ''
#
# ## Desired openshift admin name and password
admin_user: ""
admin_user_password: ""
#
# ## AWS Credentials. This is required.
aws_access_key_id: ""
aws_secret_access_key: ""
----

== Review the Env_Type variable file

* This file link:./env_vars.yml[./env_vars.yml] contains all the variables you
 need to define to control the deployment of your environment.

== Running Ansible Playbook



. You can run the playbook with the following arguments to overwrite the default variable values:
[source,bash]
----

## For a HA environment
REGION=ap-southeast-2
KEYNAME=osesharedkey
GUID=r2d2
ENVTYPE="ocp-ha-lab"
CLOUDPROVIDER=ec2
HOSTZONEID='Z3IHLWJZOU9SRT'

time ansible-playbook -i inventory/ ./main.yml \
-e "guid=${GUID}" -e "env_type=${ENVTYPE}"  -e "cloud_provider=${CLOUDPROVIDER}" -e "aws_region=${REGION}"  \
-e "HostedZoneId=${HOSTZONEID}"  -e "key_name=${KEYNAME}"  -e "subdomain_base_suffix=.example.opentlc.com"  \
-e "install_idm=htpasswd" \
-e "node_instance_count=2" -e "infranode_instance_count=2" -e "master_instance_count=3" -e "software_to_deploy=openshift" --skip-tags=installing_openshift


REGION=us-west-1
KEYNAME=osesharedkey
GUID=aaab
ENVTYPE="ocp-ha-lab"
CLOUDPROVIDER=ec2
HOSTZONEID='Z3IHLWJZOU9SRT'

time ansible-playbook -i inventory/ ./main.yml \
-e "guid=${GUID}" -e "env_type=${ENVTYPE}"  -e "cloud_provider=${CLOUDPROVIDER}" -e "aws_region=${REGION}"  \
-e "HostedZoneId=${HOSTZONEID}"  -e "key_name=${KEYNAME}"  -e "subdomain_base_suffix=.example.opentlc.com"  \
-e "install_idm=htpasswd" \
-e "node_instance_count=2" -e "infranode_instance_count=1" -e "master_instance_count=1" -e "loadbalancer_instance_count=0"  -e "software_to_deploy=openshift"


. To Delete an environment
----

REGION=ap-southeast-2
KEYNAME=osesharedkey
GUID=ocptestha4
ENVTYPE="ocp-ha-lab"
CLOUDPROVIDER=ec2
HOSTZONEID='Z3IHLWJZOU9SRT'
#To Destroy an Env
ansible-playbook -i inventory/ ./configs/${ENVTYPE}/destroy_env.yml \
 -e "guid=${GUID}" -e "env_type=${ENVTYPE}"  -e "cloud_provider=${CLOUDPROVIDER}" -e "aws_region=${REGION}"  \
 -e "HostedZoneId=${HOSTZONEID}"  -e "key_name=${KEYNAME}"  -e "subdomain_base_suffix=.example.opentlc.com"


----


. Testing AWS limits and quotas

----

REGION=us-east-1
KEYNAME=osesharedkey
GUID=aaalb
ENVTYPE="ocp-ha-lab"
CLOUDPROVIDER=ec2
HOSTZONEID='Z3IHLWJZOU9SRT'


time ansible-playbook  ./main.yml \
-e "guid=${GUID}" -e "env_type=${ENVTYPE}"  -e "cloud_provider=${CLOUDPROVIDER}" -e "aws_region=${REGION}"  \
-e "HostedZoneId=${HOSTZONEID}"  -e "key_name=${KEYNAME}"  -e "subdomain_base_suffix=.example.opentlc.com"  \
-e "install_idm=htpasswd" \
-e "node_instance_count=4" -e "infranode_instance_count=2" -e "master_instance_count=3" -e "software_to_deploy=openshift" \
--skip-tags=installing_openshift


----


REGION=us-east-1
KEYNAME=osesharedkey
ENVTYPE="ocp-ha-lab"
CLOUDPROVIDER=ec2
HOSTZONEID='Z3IHLWJZOU9SRT'

for GUID in `cat ../${REGION}` ; do
echo ${GUID}



REGION=us-east-1
KEYNAME=osesharedkey
GUID=aaalb
ENVTYPE="ocp-ha-lab"
CLOUDPROVIDER=ec2
HOSTZONEID='Z3IHLWJZOU9SRT'

time ansible-playbook  ./main.yml \
-e "guid=${GUID}" -e "env_type=${ENVTYPE}"  -e "cloud_provider=${CLOUDPROVIDER}" -e "aws_region=${REGION}"  \
-e "HostedZoneId=${HOSTZONEID}"  -e "key_name=${KEYNAME}"  -e "subdomain_base_suffix=.example.opentlc.com"  \
-e "install_idm=htpasswd" \
-e "node_instance_count=4" -e "infranode_instance_count=2" -e "master_instance_count=3" -e "software_to_deploy=openshift" --skip-tags=openshfit_installer,get_openshift_credentials

done

REGION=us-west-1
KEYNAME=osesharedkey
ENVTYPE="ocp-ha-lab"
CLOUDPROVIDER=ec2
HOSTZONEID='Z3IHLWJZOU9SRT'

for GUID in `cat ../${REGION}` ; do
echo ${GUID}

time ansible-playbook  ./main.yml \
-e "guid=${GUID}" -e "env_type=${ENVTYPE}"  -e "cloud_provider=${CLOUDPROVIDER}" -e "aws_region=${REGION}"  \
-e "HostedZoneId=${HOSTZONEID}"  -e "key_name=${KEYNAME}"  -e "subdomain_base_suffix=.example.opentlc.com"  \
-e "install_idm=htpasswd" \
-e "node_instance_count=4" -e "infranode_instance_count=2" -e "master_instance_count=3" -e "software_to_deploy=openshift" --skip-tags=infrastucture_deployment,openshfit_installer,get_openshift_credentials

done



REGION=us-east-1
KEYNAME=osesharedkey
ENVTYPE="ocp-ha-lab"
CLOUDPROVIDER=ec2
HOSTZONEID='Z3IHLWJZOU9SRT'
GUID=asaf
time ansible-playbook  ./main.yml \
-e "guid=${GUID}" -e "env_type=${ENVTYPE}"  -e "cloud_provider=${CLOUDPROVIDER}" -e "aws_region=${REGION}"  \
-e "HostedZoneId=${HOSTZONEID}"  -e "key_name=${KEYNAME}"  -e "subdomain_base_suffix=.example.opentlc.com"  \
-e "install_idm=htpasswd" \
-e "node_instance_count=4" -e "infranode_instance_count=2" -e "master_instance_count=3" \
 -e "software_to_deploy=openshift"




## This is a workshop example
REGION=ap-southeast-2
KEYNAME=sborenstkey
GUID=apactest
ENVTYPE="opentlc-shared"
CLOUDPROVIDER=ec2
HOSTZONEID='Z186MFNM7DX4NF'

ansible-playbook -i inventory/ ./main.yml \
 -e "guid=${GUID}" -e "env_type=${ENVTYPE}"  -e "cloud_provider=${CLOUDPROVIDER}" -e "aws_region=${REGION}"  \
 -e "HostedZoneId=${HOSTZONEID}"  -e "key_name=${KEYNAME}"  -e "subdomain_base_suffix=.openshift.opentlc.com"  \
  -e "bastion_instance_type=t2.large" -e "master_instance_type=c4.xlarge" \
  -e "infranode_instance_type=c4.4xlarge"  -e "node_instance_type=c4.4xlarge" \
  -e "nfs_instance_type=m3.large" -e "node_instance_count=8" -e "install_idm=htpasswd" \
  -e "software_to_deploy=openshift"

for index in {1..5}  ; do

echo INDEX IS $index;
GUID=ocp${index}

echo GUID is $GUID


REGION=us-east-1
KEYNAME=osesharedkey
ENVTYPE="ocp-ha-lab"
CLOUDPROVIDER=ec2
HOSTZONEID='Z3IHLWJZOU9SRT'

time ansible-playbook -vvvv -i inventory/ ./main.yml -e "guid=${GUID}" -e "env_type=${ENVTYPE}"  -e "cloud_provider=${CLOUDPROVIDER}" -e "aws_region=${REGION}"  -e "HostedZoneId=${HOSTZONEID}"  -e "key_name=${KEYNAME}"  -e "subdomain_base_suffix=.example.opentlc.com"  -e "install_idm=htpasswd" -e "node_instance_count=3" -e "infranode_instance_count=2" -e "master_instance_count=3"   -e "software_to_deploy=openshift" --skip-tags=installing_openshift
done


for index in {1..4}  ; do

echo INDEX IS $index;
GUID=uswest${index}

echo GUID is $GUID


REGION=us-east-1
KEYNAME=osesharedkey
ENVTYPE="ocp-ha-lab"
CLOUDPROVIDER=ec2
HOSTZONEID='Z3IHLWJZOU9SRT'

time ansible-playbook -vvvv -i inventory/ ./main.yml -e "guid=${GUID}" -e "env_type=${ENVTYPE}"  -e "cloud_provider=${CLOUDPROVIDER}" -e "aws_region=${REGION}"  -e "HostedZoneId=${HOSTZONEID}"  -e "key_name=${KEYNAME}"  -e "subdomain_base_suffix=.example.opentlc.com"  -e "install_idm=htpasswd" -e "node_instance_count=3" -e "infranode_instance_count=2" -e "master_instance_count=3"   -e "software_to_deploy=openshift" --skip-tags=installing_openshift
done
time ansible-playbook -vvvv -i inventory/ ./main.yml -e "guid=${GUID}" -e "env_type=${ENVTYPE}"  -e "cloud_provider=${CLOUDPROVIDER}" -e "aws_region=${REGION}"  -e "HostedZoneId=${HOSTZONEID}"  -e "key_name=${KEYNAME}"  -e "subdomain_base_suffix=.example.opentlc.com"  -e "install_idm=htpasswd" -e "node_instance_count=3" -e "infranode_instance_count=2" -e "master_instance_count=3"   -e "software_to_deploy=openshift" --tags=common_tasks


time ansible-playbook -vvvv -i inventory/ ./main.yml -e "guid=${GUID}" -e "env_type=${ENVTYPE}"  -e "cloud_provider=${CLOUDPROVIDER}" -e "aws_region=${REGION}"  -e "HostedZoneId=${HOSTZONEID}"  -e "key_name=${KEYNAME}"  -e "subdomain_base_suffix=.example.opentlc.com"  -e "install_idm=htpasswd" -e "node_instance_count=3" -e "infranode_instance_count=2" -e "master_instance_count=3"   -e "software_to_deploy=openshift" --tags=
