= Ansible Linklight Config

Ansible Linklight is an example of an existing deployer being wrapped by
Ansible. Linklight is capable of deploying multiple different lab environments:
* Engine (4 nodes, for lightbulb labs) 
* Networking (2 nodes + 2 routers, for linklight labs)
** (This is acheieved by seting the varaible `networking; true` 

The `linklight` deployer is called by first running a fairly typical `Ansible Agnostic Deployer`
`pre_infra.yml` but at the end of that playbook:

* cloning the `lightbulb` repo to a specfic commit
* executing the cloned provisioioning playbook
** `linklight` vars are made availble via env_vars.yml


https://github.com/ansible/lightbulb

== Set up your "Secret" variables

* You need to provide some credentials for deployments to work
* Create a file called "env_secret_vars.yml" and put it in the
 ./ansible/configs/CONFIGNAME/ directory.
** At this point this file *has to be created* even if no vars from it are used.
* You can choose to provide these values as extra vars (-e "var=value") in the
 command line if you prefer not to keep sensitive information in a file.

.Example contents of "Secret" Vars file
----
# ## Logon credentials for Red Hat Network
# ## Required if using the subscription component
# ## of this playbook.
rhel_subscription_user: ''
rhel_subscription_pass: ''
#
# ## LDAP Bind Password
bindPassword: ''
#
# ## Desired admin name and password if required
admin_user: ""
admin_user_password: ""
#
# ## AWS Credentials. This is required.
aws_access_key_id: ""
aws_secret_access_key: ""
#If using repo_method: satellite, you must set these values as well.
satellite_url: satellite.example.com
satellite_org: Sat_org_name
satellite_activationkey: "rhel7basic"

----

== Review the Env_Type variable file

* This file link:./env_vars.yml[./env_vars.yml] contains all the variables you
 need to define to control the deployment of your environment.


== Running Ansible Playbook

You can run the playbook with the following arguments to overwrite the default variable values:
[source,bash]
----
GUID=special4
ENV_TYPE=linklight-networking-allcisco
CLOUD_PROVIDER=ec2

EC2_REGION=us-east-1
EC2_AVAILABILITY_ZONE=us-east-1a
EC2_NAME_PREFIX=${GUID}
EC2_KEYNAME=${GUID}-link
WORKSHOP_DNS_ZONE=example.opentlc.com

# set NETWORKING to f to deploy Ansible Engine env
NETWORKING=true
SPECIAL=all_cisco
LOCAL_SECURITY=false
ADMIN_PASSWORD=ansible
EMAIL_USERS=no
CREATE_LOGIN_PAGE=false
STUDENT_TOTAL=1

USERS='{"users":[{ "name": "Alice", "username": "alice", "email": "alice@example.com" }, { "name": "Bob", "username":"bob", "email": "bob@example.com" }]}'
ANSIBLE_REPO_PATH=$(pwd)

ansible-playbook main.yml \
  -e ANSIBLE_REPO_PATH=${ANSIBLE_REPO_PATH} \
  -e host_key_checking=False \
  -e guid=${GUID} \
  -e env_type=${ENV_TYPE} \
  -e project_tag=${ENV_TYPE}-${GUID} \
  -e ec2_key_name=${EC2_KEYNAME} \
  -e ec2_region=${EC2_REGION} \
  -e ec2_az=${EC2_AVAILABILITY_ZONE} \
  -e ec2_name_prefix=${GUID} \
  -e cloud_provider=${CLOUD_PROVIDER} \
  -e workshop_dns_zone=${WORKSHOP_DNS_ZONE} \
  -e "{'student_total': ${STUDENT_TOTAL}}" \
  -e admin_password=${ADMIN_PASSWORD} \
  -e localsecurity=${LOCAL_SECURITY} \
  -e create_login_page=${CREATE_LOGIN_PAGE} \
  -e email=${EMAIL_USERS} \
  -e users=${USERS} \
  -e software_to_deploy=none \
  -e networking=${NETWORKING} \
  -e special=${SPECIAL} \
  --skip-tags=deploy_infrastructure,post_infra_tasks,pre_software_tasks,deploy_software,post_software,email

----

=== Optional Additional Variables

. Ansible Linklight has a new networking lab `_v2` under active development. To
  deploy this configuration set the following:
+
[source,bash]
----
-e special=all_cisco 
----
. To change from the default ssh key behaviour set the following:
+
[source,bash]
----
#use_own_key: true
#env_authorized_key: "{{guid}}key"
#set_env_authorized_key: true
----

=== To Delete an environment

[source,bash]
----
GUID=td05
ENV_TYPE=linklight-networking-allcisco

EC2_NAME_PREFIX=${GUID}
EC2_REGION=us-east-1
EC2_AVAILABILITY_ZONE=us-east-1a

ANSIBLE_REPO_PATH=$(pwd)

ansible-playbook ${ANSIBLE_REPO_PATH}/configs/${ENV_TYPE}/destroy_env.yml \
  -e ANSIBLE_REPO_PATH=${ANSIBLE_REPO_PATH} \
 -e 'host_key_checking=False \
  -e ec2_name_prefix=${GUID} \
  -e ec2_region=${EC2_REGION} \
  -e s3_state=absent \
  -e create_login_page=true \
  -e ec2_az=${EC2_AVAILABILITY_ZONE}
----
