= OPENTLC OCP-HA-LAB Env_Type config


For the Homework environment, we will NOT preserve the complete hosts file. We
will add the following "--skip-tags"
[source,text]
----
preserve_complete_ansible_inventory
openshift_nfs_config


----

CNS nodes are not deployed.  Not yet part of homeowkr.




For example, we will include things such as ec2 instance names, secret
variables such as private/public key pair information, passwords, etc.

Eventually, all sensitive information will be encrypted via Ansible Vault. The
inclusion as well as instructions on doing this will be included in a later
release.

== Set up your "Secret" variables

* You need to provide some credentials for deployments to work
* Create a file called "env_secret_vars.yml" and put it in the
 ./ansible/configs/CONFIGNAME/ directory.
** At this point this file *has to be created* even if no vars from it are used.
* You can choose to provide these values as extra vars (-e "var=value") in the
 command line if you prefer not to keep sensitive information in a file.

.Example contents of "Secret" Vars file
----
# ## Logon credentials for Red Hat Network
# ## Required if using the subscription component
# ## of this playbook.
rhel_subscription_user: ''
rhel_subscription_pass: ''
#
# ## LDAP Bind Password
bindPassword: ''
#
# ## Desired openshift admin name and password
admin_user: ""
admin_user_password: ""
#
# ## AWS Credentials. This is required.
aws_access_key_id: ""
aws_secret_access_key: ""

#If using repo_method: satellite, you must set these values as well.
# satellite_url: satellite.example.com
# satellite_org: Sat_org_name
# satellite_activationkey: "rhel7basic"
----


== Review the Env_Type variable file

* This file link:./env_vars.yml[./env_vars.yml] contains all the variables you
 need to define to control the deployment of your environment.

== Running Ansible Playbook

. You can run the playbook with the following arguments to overwrite the default variable values:
[source,bash]
----
# Set the your environment variables (this is optional, but makes life easy)

REGION=ap-southeast-1
KEYNAME=ocpkey
GUID=testnewec21
ENVTYPE="ocp-ha-lab"
CLOUDPROVIDER=ec2v2
HOSTZONEID='Z3IHLWJZOU9SRT'
REPO_PATH='https://admin.example.com/repos/ocp/3.6/'

BASESUFFIX='.example.opentlc.com'
IPAPASS=aaaaaa
REPO_VERSION=3.6
NODE_COUNT=2
DEPLOYER_REPO_PATH=`pwd`
LOG_FILE=$(pwd)/${ENVTYPE}-${GUID}.log

## For a HA environment that is not installed with OpenShift


  ansible-playbook ${DEPLOYER_REPO_PATH}/main.yml  \
      -e "guid=${GUID}" -e "env_type=${ENVTYPE}" -e "key_name=${KEYNAME}" \
      -e "cloud_provider=${CLOUDPROVIDER}" -e "aws_region=${REGION}" -e "HostedZoneId=${HOSTZONEID}" \
      -e "subdomain_base_suffix=${BASESUFFIX}" \
      -e "bastion_instance_type=t2.medium" -e "master_instance_type=t2.large" \
      -e "infranode_instance_type=t2.large" -e "node_instance_type=t2.large" \
      -e "support_instance_type=t2.medium" -e "node_instance_count=${NODE_COUNT}" \
      -e "ipa_host_password=${IPAPASS}" -e "install_idm=htpasswd"  \
      -e "email=name@example.com" \
      -e "repo_method=file" -e "own_repo_path=${REPO_PATH}" -e "repo_version=${REPO_VERSION}" \
      -e "software_to_deploy=openshift" -e "osrelease=3.6.173.0.21" -e "docker_version=1.12.6" \
      -e "ANSIBLE_REPO_PATH | default('.')=${DEPLOYER_REPO_PATH}" \
      --skip-tags=installing_openshift,get_openshift_credentials 1>> $LOG_FILE 2>> $LOG_FILE

. To Delete an environment
----
#To Destroy an Env
ansible-playbook  \
    ${DEPLOYER_REPO_PATH}/configs/${ENVTYPE}/destroy_env.yml \
    -e "guid=${GUID}" -e "env_type=${ENVTYPE}" \
    -e "cloud_provider=${CLOUDPROVIDER}" -e "aws_region=${REGION}"  -e "HostedZoneId=${HOSTZONEID}" \
    -e "ANSIBLE_REPO_PATH | default('.')=${DEPLOYER_REPO_PATH}" \
    -e "key_name=${KEYNAME}"  -e "subdomain_base_suffix=${BASESUFFIX}"

----
