:config: smart-management
:author: GPTE Team
:tag1: install_satellite
:tag2: configure_satellite



Config: {config}
===============

With {config}, we can deploy bastion, Ansible tower, Satellite and RHEL host on OpenStack cloud providers.


Requirements
------------

Following are the requirements:

. Yum repositories are required for bastion and satellite host.
. OSP credentials are required. 
. apypie python module required.
 

Config Variables
----------------

* Cloud specfic settings related variables.

|===
|*Variable* | *State* |*Description*
| env_type: smart-management|Required | Name of the config
| output_dir: /tmp/workdir |Required | Writable working scratch directory
| email: satellite_vm@example.com |Required |  User info for notifications
| guid: defaultguid | Reqired |Unique identifier
| cloud_provider: osp |Required        | Which AgnosticD Cloud Provider to use
|===


* Satellite specfic settings related variables.

|===
|*Variable* | *State* |*Description*
|install_satellite: Boolean   |Required | To enable installation roles
|configure_satellite: Boolean |Required | To enable configuration roles
|satellite_version: "Digit" |Required |satellite version
|org: "String" |Required |Organization name
|org_label: "String" |Required | Organization label in string without space
|org_description: "String" |Required | Organization description
|===

[NOTE] 
For more about variables read README.adoc of the roles.
    
* Example variables files

. Sample of sample_vars.yml
[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible

[user@desktop ~]$ cat ./configs/smart-management/sample_vars.yml

env_type: smart-management     
output_dir: /tmp/workdir               
email: satellite_vm@example.com 
cloud_provider: osp 
aws_region: ap-southeast-2

install_satellite: True
configure_satellite: True 
satellite_version: 6.4
org: gpte
org_label: gpte
org_description: "Global Partner Training and Enablement"
subscription_name: "Employee SKU"

   
----
for reference look at link:sample_vars.yml[]  

. Sample of secrets.yml
[source=text]
----
[user@desktop ~]$ cat ~/secrets.yml
aws_access_key_id: xxxxxxxxxxxxxxxx
aws_secret_access_key: xxxxxxxxxxxxxxxxxx
own_repo_path: http://localrepopath/to/repo
openstack_pem: ldZYgpVcjl0YmZNVytSb2VGenVrTG80SzlEU2xtUTROMHUzR1BZdzFoTEg3R2hXM
====Omitted=====
25ic0NTTnVDblp4bVE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

openstack_pub: XZXYgpVcjl0YmZNVytSb2VGenVrTG80SzlEU2xtUTROMHUzR1BZdzFoTEg3R2hXM
====Omitted=====
53ic0NTTnVDblp4bVE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
----



Tags
---

|===
|{tag1} |Consistent tag for all satellite installation roles
|{tag2} |Consistent tag for all satellite configuration roles
|===

* Example tags

----
## Tagged jobs
ansible-playbook playbook.yml --tags configure_satellite

## Skip tagged jobs
ansible-playbook playbook.yml --skip-tags install_satellite
----

Example to run config 
---------------------

How to use config .

[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible

[user@desktop ~]$ ansible-playbook  main.yml \
  -e @./configs/smart-management/sample_osp_vars.yml \
  -e @~/secrets.yml \
  -e guid=defaultguid  
----

Example to stop environment 
---------------------------

[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible

[user@desktop ~]$ ansible-playbook  ./configs/smart-management/stop.yml \
  -e @./configs/smart-management/sample_vars.yml \
  -e @~/secrets.yml \
  -e guid=defaultguid  
----

Example to start environment 
---------------------------

[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible

[user@desktop ~]$ ansible-playbook  ./configs/smart-management/start.yml \
  -e @./configs/smart-management/sample_vars.yml \
  -e @~/secrets.yml \
  -e guid=defaultguid  
----

Example to destroy environment 
------------------------------

[source=text]
----
[user@desktop ~]$ cd agnosticd/ansible

[user@desktop ~]$ ansible-playbook  ./configs/smart-management/destroy.yml \
  -e @./configs/smart-management/sample_vars.yml \
  -e @~/secrets.yml \
  -e guid=defaultguid 
----




Author Information
------------------

{author}
