---
- name: Enable dynamic plugins
  set_fact:
    _dh_dyn_plg: "{{ _dh_dyn_plg | combine({'plugins': _dh_dyn_plg.plugins + ocp4_workload_advanced_developer_suite_post_install_dh_dynamic_plugins_enable}) }}"