:role: satellite-publish-content-views 
:author: Andy Mott <amott@redhat.com>
:tag1: configure_satellite
:main_file: tasks/main.yml
:version_file: tasks/version_6.x.yml

= Role: {role}

This role checks recent sync logs and publishes updated content views to Library.

The playbook is designed to be run daily, after a sync has been completed on the Satellite repositories.

All updated repositories are gathered, then the content views which contain them plus any composite content views they are in are evaluated and checked to make sure they haven't been updated in the last day and that composite views are not configured to auto-publish, then the remainder are published.


== Requirements

. Satellite must be installed and configured.
. foreman-ansible-modules must be installed.
. `apypie` module must be installed in Perl.
. Ansible must be using Python version 3. This can be configured in `ansible.cfg` with the line `interpreter_python = /usr/bin/python3`.

== Role Variables

[cols="4a,2a,4a"]
|===
|satellite_version: "Digit" | Required | Satellite version
|org: "String" | Required | Organization name
|satellite_admin: "String" | Required | Satellite admin username
|satellite_admin_password: "String" | Required | Satellite admin password
|publicname: "String" | Required | FQDN of Satellite server
|===


* Example variables

[source,text]
----
satellite_version: 6.7
org="My Organization"
satellite_admin="admin"
satellite_admin_password="MySecretPassword"
publicname="https://satellite.example.com"
----

== Tags

|===
|{tag1} | Consistent tag for all satellite config roles
|===

* Example tags

 ## Tagged jobs
 ansible-playbook playbook.yml --tags configure_satellite

 ## Skip tagged jobs
 ansible-playbook playbook.yml --skip-tags configure_satellite


== Author Information

{author}