= ocp-workload-openshift-applier - execute an openshift-applier run 

== Role overview

* This role uses the [openshift-applier](https://github.com/redhat-cop/openshift-applier)
 to manage content within an OpenShift Container Platform. It consists of the following tasks files:
** Tasks: link:./tasks/pre_workload.yml[pre_workload.yml] - Not used.
*** Debug task will print out: `pre_workload Tasks completed successfully.`

** Tasks: link:./tasks/workload.yml[workload.yml] - Used to
 execute the openshift-applier role.
*** Debug task will print out: `workload Tasks completed successfully.`

** Tasks: link:./tasks/post_workload.yml[post_workload.yml] - Not used.
*** Debug task will print out: `post_workload Tasks completed successfully.`

** Tasks: link:./tasks/remove_workload.yml[remove_workload.yml] - Not Used.
*** Debug task will print out: `remove_workload Tasks completed successfully.`

** Note: the workload accepts 'openshift_cluster_content' as a dictionary, or
 you can use 'openshift_cluster_content_list' for multiple 'openshift_cluster_content' content to be processed.

=== Deploy a Workload with the `ocp-workload` playbook [Mostly for testing]

----
TARGET_HOST="bastion.my.domain.com"
OCP_USERNAME="my-admin-user"
WORKLOAD="ocp-workload-openshift-applier"
GUID=1001
DEFAULT_WORKLOADS="{[ ocp-workload-openshift-applier ]}" 

# a TARGET_HOST is specified on the command line, without using an inventory file
ansible-playbook -i ${TARGET_HOST}, ./configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=~/.ssh/keytoyourhost.pem" \
    -e"ansible_user=ec2-user" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"default_workloads=${DEFAULT_WORKLOADS}" \
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"ACTION=create"
----

== Other related information:

=== Set up your Ansible inventory

* You can create an Ansible inventory file to define your connection method to your host (Master/Bastion with `oc` command)
* The below inventory needs tailoring to fit your environment to work correctly

inventory/hosts
----
[bastions]
192.168.10.1 ansible_user=ec2-user ansible_ssh_private_key_file=<path-to-private-key>
----

inventory/group_vars/all.yml
----
become_override: no 
silent: False

default_workloads:
- ocp-workload-openshift-applier

openshift_cluster_content:
- object: projectrequest
  content:
  - name: Create HTTPd project
    file: "https://raw.githubusercontent.com/redhat-cop/openshift-applier/master/tests/files/cluster-template/project1.yml"
    action: create

----
